### ISSUE TITLE
Incorrect text field sizes

### ISSUE THREAD

**Issue by bmihelac** [material-components/material-components-web#1002]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

> Please be specific, e.g. _major.minor.patch_

v0.15.0

### What browser(s) is this bug affecting?

Chrome, Firefox tested, probably others too

> Please include the browser version. A user-agent string is also quite helpful.

Version 62.0.3165.0 (Official Build) canary (64-bit)

### What OS are you using?

OSX

> Please include the OS version.

10.9.5

### What are the steps to reproduce the bug?

Open page https://material-components-web.appspot.com/textfield.html
Try to click on the first text field in the near the right edge. 

![text-field-width](https://user-images.githubusercontent.com/13813/28531635-bab6b54c-7097-11e7-9b71-11653eca4442.png)

## What is the expected behavior?

Text field should gain focus, but it does not, because field is smaller than a line (red vs blue box on image).

### What is the actual behavior?

Text field does not gain focus.
Fields with lot of text are cut before underline ends.

**Comment by yeelan0319** [comment]
Thanks for filing the issue, this definitely looks like a bug.

@bmihelac, would you like to file a PR to help us correct it?
Adding `width: 100%` to `.mdc-textfield__input` should fix the bug.

**Comment by bmihelac** [comment]
@yeelan0319 thanks for the tip. It works as expected with width set on input element. I have added PR.
