### ISSUE TITLE
List component - start-detail - wrong width on small screen

### ISSUE THREAD

**Issue by grafa** [material-components/material-components-web#1006]
### What MDC-Web Version are you using?

0.15

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

Linux

### What are the steps to reproduce the bug?

Create a list with start-detail item

### What is the expected behavior?

Same width of space for "start-detail"

### What is the actual behavior?

The space is shrinking

### Any other information you believe would be useful?

Let's see screenshot.

![image](https://user-images.githubusercontent.com/198654/28564836-93fe8ba8-712a-11e7-94d7-c147227a51a7.png)

When I change the underscored property "width" to "min-width" the start-detail is fixed now.

![image](https://user-images.githubusercontent.com/198654/28564782-69587bd4-712a-11e7-8270-10c82a673602.png)

I hope I've provided all needed informations.

Thank you and keep up guys!

**Comment by yeelan0319** [comment]
Close it because it is a duplication of #814, which we haven't yet got a chance to address.
Feel free to reopen it if you think it is a different problem
