### ISSUE TITLE
Component layout-grid on small screens

### ISSUE THREAD

**Issue by im-n1** [material-components/material-components-web#1007]
### What MDC-Web Version are you using?

0.15

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

Linux

### What are the steps to reproduce the bug?

Create a layout with "mobile" cells

### What is the expected behavior?

Correct cell witdh

### What is the actual behavior?

Cell width is not acting according to "mobile" styles.

### Any other information you believe would be useful?

Let's see screenshot. I have a cell of withth 3 for desktop and for mobile it's width of 2. The thing is the "mobile" rule is not being applied once I open the page on small screen. This thing worked on previous versions. I've checked for guideline updates and my code markup is up to date.

![image](https://user-images.githubusercontent.com/198654/28565175-bc900262-712b-11e7-8221-38d88c98c922.png)

I hope I've provided all needed informations.

Thank you and keep up guys!

**Comment by funkybg** [comment]
I've encountered the same problem. After looking at the css, you pretty much have to specify desktop, tablet and mobile without the default class. Using the default class (if it has a higher column count) overrides any size specific class.

**Comment by grafa** [comment]
Thank you. I get the solution but that's pretty much against documentation and grid system philosophy.

**Comment by akubasa** [comment]
I am also struggling with this issue.
Can anyone tell me?, when will this be resolved and released?
The grid is unuseable on smaller (non desktop) devices while this is not fixed :)

**Comment by aaronhudon** [comment]
@akubasa as @funkybg mentioned, you need to specify -desktop, -tablet, -phone for all columns
e.g.

```
<div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-2-tablet">
</div>
```
