### ISSUE TITLE
style/mdc-textfield--box

### ISSUE THREAD

**Issue by MrGrigri** [material-components/material-components-web#1009]
## Style improvement

I came across an inconsistency with the newly added text field boxes, specifically with its helper text. The helper text should have a left and right margin of 16 pixels. 

### What MDC-Web Version are you using?

0.16

### What browser(s) is this bug affecting?

all

### What OS are you using?

Windows 10 Enterprise (14393)

### What are the steps to reproduce the bug?

Click in the text field box that is required and then blur the input by clicking outside. The help text appears (as an error) and it is allgned to the left with no margins. 

### What is the expected behavior?

It should follow the MD Guidelines for text field boxes found [here](https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes)

### What is the actual behavior?

It is left alligned with no margins

### Any other information you believe would be useful?

Creating a pull request.

**Comment by touficbatache** [comment]
You're right. That's a bug!

**Comment by MrGrigri** [comment]
I fixed the order of the margin-left and -right to conform to CSS linting. The code has been pushed to the same branch.

**Comment by MrGrigri** [comment]
I'm not quite sure why this is failing. Does anyone have any idea?

**Comment by talhaishtiaq** [comment]
how about this error?
TypeError: Class constructor MDCComponent cannot be invoked without 'new'
