### ISSUE TITLE
MDCSelect object doesn't accept select element as root

### ISSUE THREAD

**Issue by Teoxoy** [material-components/material-components-web#1025]
At the end of the README file for the select package there is an example of how you can switch between selects for better cross-device UX. In the example the select element is being attached to an MDCSelect obj, that would not work because the initialize function tries to create a menu with a non existent root element.
Possible fixes: Update README to show a working example or allow and implement select element as root for MDCSelect

**Comment by kfranqueiro** [comment]
Sorry for being late to reply to this. We've made updates to MDC Select's DOM structure more recently and updated the README accordingly.
