### ISSUE TITLE
Toolbar: Wrong placement of last icon when there is a menu

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1026]
### What MDC-Web Version are you using?

> 0.16.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> Windows 7

### What are the steps to reproduce the bug?

> 1. Have a toolbar [like here](http://material-components-web.appspot.com/toolbar/default-toolbar.html)
> 2. Add a simple menu to the most right icon
> 3. Observe the right padding (placement) of the last icon

### What is the expected behavior?

> It should have a `padding-right: 16px;`

### What is the actual behavior?

> It has a `padding-right: 8px;` (like normal icons)

### Any other information you believe would be useful?

> This is caused by `mdc-toolbar__icon:last-child`. The toolbar icon isn't the last child because there is a simple menu after it. A simple fix would be to use `last-of-type` instead of `last-child`.
Would you like a PR to fix this?

**Comment by yeelan0319** [comment]
Sounds reasonable. Feel free to file an PR for it.

**Comment by touficbatache** [comment]
Done! @yeelan0319
