### ISSUE TITLE
`mdc-button--theme-dark` with `mdc-button--raised`, doesn't properly set `background-color`

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1030]
Check out the latest code and run `npm run dev`, navigate to http://localhost:8080/button.html (The latest version of the demo page is not available on https://material-components-web.appspot.com/button.html yet)

The `mdc-theme--dark` section shows a raised button with a black background (black is our theme's primary color).

![heorvsudm6z](https://user-images.githubusercontent.com/4703432/28686502-400a6a20-72c0-11e7-9f02-7dd3e34fd9e5.png)

However, the `mdc-button--theme-dark` section shows a raised button with a grey background.

![ogxgrxy7men](https://user-images.githubusercontent.com/4703432/28686559-6b3f76cc-72c0-11e7-9ab2-e5dc092b395d.png)

The second section, `mdc-button--theme-dark`, has the bug. The raised button should be black.

The fix is to correctly use the `@include mdc-theme-dark(".mdc-button")` within the `mdc-button--raised` context of mdc-button.scss. It needs to be updated to

```
@include mdc-theme-dark(".mdc-button", true /* compound */)
```

[`mdc-theme-dark`](https://github.com/material-components/material-components-web/tree/master/packages/mdc-theme#mdc-theme-darkroot-selector-compound) mixin requires `$compound` to be set to true if the 

> current selector is a compound selector with the base selector

...and `.mdc-button--raised` is a compound selector with `.mdc-button`.

**Comment by bhongy** [comment]
As of the current HEAD on master (f0b607), this seems to be fixed. Screenshot below.

<img width="815" alt="screen shot 2017-10-02 at 10 54 22 am" src="https://user-images.githubusercontent.com/3942264/31091673-9eadc6b0-a760-11e7-818b-084fbc98faeb.png">

@lynnjepsen is this still an issue?

**Comment by acdvorak** [comment]
Button no longer directly supports dark mode. You can achieve the same thing by overriding the colors yourself (see our [demo page](https://material-components-web.appspot.com/button.html) for an example).

**Comment by RhysyG** [comment]
Just to clarify, its recommended create a new class like this for a dark themed website?

.mdc-button {
	@include mdc-theme-prop(color, text-primary-on-dark);
}

Doesn't seem as easy to use as the theme variables (ie: background). Any reason why has it been hard coded light?
