### ISSUE TITLE
`mdc-button--theme-dark` with `:disabled`, doesn't properly set `background-color` or `color`

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1031]
Check out the latest code and run `npm run dev`, navigate to http://localhost:8080/button.html (The latest version of the demo page is not available on https://material-components-web.appspot.com/button.html yet)

The `mdc-theme--dark` section shows a disabled button with grey text

![ikgvjcpzimp](https://user-images.githubusercontent.com/4703432/28686874-952d20a0-72c1-11e7-8371-faf769bdd94a.png)

However, the `mdc-button--theme-dark` section shows a disabled button with black text.

![b8fyn9xemo3](https://user-images.githubusercontent.com/4703432/28686913-b53e74ac-72c1-11e7-8ae2-b3679d153056.png)

The second section, `mdc-button--theme-dark`, has the bug. The disabled button should have grey text.

The fix is to correctly use the `@include mdc-theme-dark(".mdc-button")` within the `:disabled` context of mdc-button.scss. It needs to be updated to

```
@include mdc-theme-dark(".mdc-button", true /* compound */)
```

[`mdc-theme-dark`](https://github.com/material-components/material-components-web/tree/master/packages/mdc-theme#mdc-theme-darkroot-selector-compound) mixin requires `$compound` to be set to true if the 

> current selector is a compound selector with the base selector

...and `:disabled` is a compound selector with `.mdc-button`.

**Comment by bhongy** [comment]
As of the current HEAD on master [f0b607](https://github.com/material-components/material-components-web/tree/f0b607de9b6b78f815ca29b74d5979457da7ea91), this seems to be fixed. Screenshot below.

<img width="838" alt="screen shot 2017-10-02 at 11 00 37 am" src="https://user-images.githubusercontent.com/3942264/31091852-359b8f26-a761-11e7-8050-4094b65c865f.png">

@lynnjepsen is this still an issue?

Note: anchor tag (Link) does not receive disabled style but that seems to be a separate issue.

**Comment by acdvorak** [comment]
Fixed by @yeelan0319.
