### ISSUE TITLE
`mdc-dialog--theme-dark` with `mdc-dialog____body`, doesn't properly set `color`

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1032]
Check out the latest code and run `npm run dev`, navigate to http://localhost:8080/dialog.html (The latest version of the demo page is not available on https://material-components-web.appspot.com/dialog.html yet)

The `mdc-theme--dark` section shows grey text in the dialog

![yyyejwvngs7](https://user-images.githubusercontent.com/4703432/28687099-3c715d54-72c2-11e7-8e89-2c198c4361fd.png)

However, the `mdc-dialog--theme-dark` section black text.

![r6kaddbqgpc](https://user-images.githubusercontent.com/4703432/28687127-4e334fca-72c2-11e7-92b2-1e323a4a8099.png)

The second section, `mdc-dialog--theme-dark`, has the bug. The dialog should have grey text.

The fix is to correct the `@include mdc-theme-dark(".mdc-dialog", true)` within the `.mdc-dialog__body` context of mdc-dialog.scss. It needs to be updated to

```
@include mdc-theme-dark(".mdc-dialog")
```

[`mdc-theme-dark`](https://github.com/material-components/material-components-web/tree/master/packages/mdc-theme#mdc-theme-darkroot-selector-compound) mixin requires `$compound` to be set to true if the 

> current selector is a compound selector with the base selector

...and `.mdc-dialog__body` is NOT a compound selector with `.mdc-dialog`.

**Comment by miguel-orange** [comment]
@lynnjepsen additionally, This seems to be the case with lists with two lines - the second line doesn't seem to get styling with `mdc-list--theme-dark`

**Comment by piotr-cz** [comment]
Bug is present in `@material/dialog 0.4.5` too
