### ISSUE TITLE
TypeError: Class constructor MDCComponent cannot be invoked without 'new'

### ISSUE THREAD

**Issue by talhaishtiaq** [material-components/material-components-web#1034]
TypeError: Class constructor MDCComponent cannot be invoked without 'new'

**Comment by amsheehan** [comment]
Please try to keep on topic in other issues. I noticed a few other threads where posted the same or similar question. We do issue triage twice a week so if you don’t hear back from a core contributor right away, understand we will get to every new issue in time. 

That said, if you are having a particular issue initializing a component, please provide a [codepen](codepen.io) reproducing the issue and one of us would be glad to help troubleshoot.

**Comment by yeelan0319** [comment]
Kindly ping the thread, is the issue still on going?

**Comment by codedbypaul** [comment]
I'm wondering if it's related to [this](https://github.com/facebookincubator/create-react-app/issues/1751#issuecomment-284763003) as I'm having a similar issue using create-react-app.

I found the Aurelia esnext webpack skeleton has this issue as well, but a project set up using Aurelia-cli doesn't.
