### ISSUE TITLE
None of pages included in demo folder are working.

### ISSUE THREAD

**Issue by bobsort** [material-components/material-components-web#1038]
Steps to reproduce.

1- Use Clone or download button on github page to download a copy of repository.
2- Extract it to a folder of your choice
3- Open any page included in demos folder (e.g. buttons.html)

```
    Inspecting the file shows that following references:
    assets/demo-styles.css.js  (does not exists in this repository)
    assets/material-components-web.css.js (does not exists in this repository)
    /images/logo_components_color_2x_web_48dp.png (Absolute path, even browsing to this page hoste in a folder in webserver will break the page)
    https://fonts.googleapis.com/css?  (external reference)
    https://fonts.googleapis.com/icon? (external reference)
```

I'm don't have npm, bower, travis or millions of different download managers which each project in github loves to use as their base. I believe a simple instruction on how to download via github regular download methods including dependency required to run examples is a great idea.

**Comment by yeelan0319** [comment]
@Garbee is right. If you wish to run the demos within this repository directly, `node` and `npm` is needed for that. Or you can use similar strategy as we mentioned here in our [codepen template](https://codepen.io/traviskaufman/pen/pNQmRp) (a CDN method). But, if you are just interested in looking at our demos, feel free to checkout our [catalogs](material-components-web.appspot.com)

**Comment by bobsort** [comment]
I do not have Node.JS on my production server and I'm not allowed to install it either. 

from 

_Production-ready components consumable in an a-la-carte fashion_

and 

_MDC-Web strives to seamlessly incorporate into a wider range of usage contexts, from simple static websites_

I'm expecting to find a way to be able to create simple *.js and *.css file which I can then copy to my server, even if I have to install npm locally and create the files. I'm failing to find a document or guide to how to _compile_ or create the mentioned files

By the way in **Including components** section of document at [git page](https://github.com/material-components/material-components-web) it explains how to use the scripts with _Webpack or SystemJS ..._ but there isn't any explanation on how to use them as just a plain *.js file which I think defies the _a-la-carte_ purpose.

**Comment by Garbee** [comment]
You can download the individual packages you want directly from NPM. Then look in the `dist` folders for the compiled assets.

In fish shell you do this command to get the tarball for a button: `wget (npm v @material/button dist.tarball)`.

Or you can simply `npm install @material/button` in the project, and then have you build pipeline copy the dist files for each module into your project before you deploy.

As far as Node being "on the production server", that isn't relevant. How you need to deploy and run your app is entirely independent of MCW. There are numerous ways to handle deployments and helping with that is out of the scope of what can be handled in the issue tracker. For help getting a better deployment flow in place, you'd need to reach out to more general support channels suck as StackOverflow. Or find somewhere with people willing to help with more targeted problems like deployments.

**Comment by bobsort** [comment]
Thank you for trying to help. I am running IIS on windows machine. 
My Node.js is version v6.11.3 (includes npm 3.10.10). 

I followed the instruction in [homepage](https://github.com/material-components/material-components-web) and run

    `npm install --save material-components-web`

Which produced following result:

![material1](https://user-images.githubusercontent.com/2040435/31077459-258e605e-a7b1-11e7-8cb4-bc41b72bf8dc.jpg)

Unlike other folders there are only 2 css files in `\nodejs\node_modules\@material\button\dist` folder **(image 1)**, so I assume I have to copy `material-components-web.css` and `material-components-web.js` from `\nodejs\node_modules\material-components-web` folder **(image 2)** to same folder as the `buttons.html` in my IIS **(image 4)**

Running the files without modification will show **(image 3)** but when I modify the `buttons.html` page and add `material-components-web.css` and `material-components-web.js` to it **(image 5)** I can see the toolbar and buttons **(image 6)**.  Buttons are responding to click (ripple effect).

If I replace `material-components-web.css` with `mdc.button.css` everything else goes haywire **(image 7)**

![material2](https://user-images.githubusercontent.com/2040435/31077804-86828902-a7b2-11e7-91d7-89ab749a3e7a.jpg)

Am I doing missing some files that I might need to copy into my app folder? As for asking here, I was trying to be sure if I followed the instructions correctly.  Is it possible that this issue related to [#2388 failed
](https://travis-ci.org/material-components/material-components-web/) ?
