### ISSUE TITLE
Meteor/Blaze example

### ISSUE THREAD

**Issue by Falieson** [material-components/material-components-web#1040]
> "If there's an example framework you'd like to see, or if you're a framework author who wants to provide an example, please consider letting us know and we'll work with you to have it contributed!"

People are still using MeteorJS and Blaze/spacebars/handlebars . I'd like an example of implementing mdc-web on an example meteor/blaze app.

Others would also benefit from the example:
- https://forums.meteor.com/t/material-components-web-import-from-node-to-meteor/33084
- https://stackoverflow.com/questions/45128796/how-to-use-material-components-web-sass-in-meteorjs

**Comment by yeelan0319** [comment]
Hi @Falieson ,
We have an ongoing thread about possibilities for our framework examples here #983 
I will close this issue here but feel free to contribute to the thread with your suggestions :)
