### ISSUE TITLE
Convert mixed usage of `td.function` and `td.func` to all use `td.func`

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1042]
I noticed while looking at tests today that we have a mix of `td.function` and `td.func` calls.  One is an alias to the other, but testdouble is potentially [planning to deprecate `td.function`](https://github.com/testdouble/testdouble.js/issues/214), so we should change our remaining invocations to be future-proof.

We might also want to decide on a consistent naming convention, since I see some instances where we pass a string that starts with `.` and many cases where we don't.

**Comment by allan-chen** [comment]
Closing since tests are migrated to Jasmine
