### ISSUE TITLE
Buttons only ripple once or not at all

### ISSUE THREAD

**Issue by Frame1910** [material-components/material-components-web#1045]
I'm currently attempting to attach ripples to all my buttons. The only problem is that applying `data-mdc-auto-init="MDCRipple"` does not add the ripple. If I use the inline `on-click` method it requires two clicks to ripple, only ripples once AND only apply it to one button on the page. This is mainly for my flat and raised buttons, list items seem to work fine.

**Comment by touficbatache** [comment]
Did you add this to the bottom of your page? `<script>mdc.autoInit()</script>`

**Comment by Frame1910** [comment]
I have solved the issue, I had put in `<script>mdc.autoInit()</script>` in the bottom, but for some reason, it needed to come after the js script as well. Why would the ordering be an issue in this case?

**Comment by touficbatache** [comment]
Because the js for MDC-Web has _not yet_ been imported and you're calling something _in_ that script. So, ordering is important. Feel free to submit a PR fixing the README so it says: "Make sure you call `mdc.autoInit()` after all scripts are loaded"

**Comment by yeelan0319** [comment]
PR merged. Thanks a lot!

**Comment by touficbatache** [comment]
No problem :smiley: @yeelan0319

**Comment by izzy25** [comment]
ouh this is my solution, thanks
