### ISSUE TITLE
Ripple for mdc-textfield--box renders incorrectly in firefox

### ISSUE THREAD

**Issue by tedypranolo** [material-components/material-components-web#1046]
### What MDC-Web Version are you using?

> 0.16.0

### What browser(s) is this bug affecting?

> Firefox 54.0.1 (32 bit)

### What OS are you using?

> Windows 10.0.15063

### What are the steps to reproduce the bug?

> Open https://material-components-web.appspot.com/textfield.html
> Go to the Textfield box demo and click inside the textfield

### What is the expected behavior?

> The ripple animates and completely fill the text box
![image](https://user-images.githubusercontent.com/3522930/28744304-8f5b41b8-7490-11e7-90ec-69a0af0d5d9f.png)

### What is the actual behavior?

> The ripple animates partially and ends as a visible circle in the middle of the text box
![image](https://user-images.githubusercontent.com/3522930/28744317-d985333e-7490-11e7-8a70-7f1b423858c8.png)

**Comment by TheMangoTrain** [comment]
I'm experiencing the same issue. Firefox 56 (64bit) on OSX 10.11.6. No issue in Chrome.

It looks like **the bug actually occurs while hovering the text field**. The ripple effect seems to render fine when clicking the text field.

**Comment by abhiomkar** [comment]
Not able to repro in latest text field version.
