### ISSUE TITLE
[mdc-form-field] Uncaught Error: Cannot find module "mdc-form-field"

### ISSUE THREAD

**Issue by wzup** [material-components/material-components-web#1049]
From here [https://github.com/material-components/material-components-web/tree/master/packages/mdc-form-field#es2015](https://github.com/material-components/material-components-web/tree/master/packages/mdc-form-field#es2015).

> import {MDCFormField, MDCFormFieldFoundation} from 'mdc-form-field';

This doesn't work

```bash
ERROR in ./src/js/AuthForm.js
    Module not found: Error: Can't resolve 'mdc-form-field' in 'C:\Users\user\app\src\js'
```

**Comment by touficbatache** [comment]
It should be `import {MDCFormField, MDCFormFieldFoundation} from '@material/form-field';`

**Comment by yeelan0319** [comment]
@touficbatache is right on this.
It seems like our `form-field` README.md didn't documented it correctly. @wzup Would you mind help us file a PR for correcting the documentation? Thanks!

**Comment by touficbatache** [comment]
All the components need an update @yeelan0319

**Comment by yeelan0319** [comment]
@touficbatache Agreed. There are a few components that doesn't have the including path documented correctly, so it would be great if someone helping with this case and also take a pass for other JavaScript enabled components.

**Comment by touficbatache** [comment]
I think I could do it later on @yeelan0319

**Comment by wzup** [comment]
@touficbatache 

> All the components need an update

You're right. I would even say all tutorial needs to be rewritten better. I spent one day trying to understand and implement GMD components from this package in my React app, and end up getting rid of the package completely. Rolled back to bullet-proof React-Bootstrap. IMO if Google will not support their Material Design by providing easy-to-use packages for different frameworks , this design concept may fall into oblivion.

Before I tried other project that implement GMD - React Toolbox and Material-UI - but was compelled to delete all of them. Sadly none of current GMD implementations come close to Bootstrap and its implementations.

**Comment by Teoxoy** [comment]
Someone should make a README template. Around 3-4 components don't even have the "Including in code" part with the imports.

**Comment by touficbatache** [comment]
@lynnjepsen is working on makinf the READMEs better

**Comment by Teoxoy** [comment]
I think this issue should be closed, all the es2015 imports were fixed.

**Comment by kfranqueiro** [comment]
Yup, you're right. Thanks!
