### ISSUE TITLE
What does it mean? "and add a property which will be set to the value of the MDC-Web Component"

### ISSUE THREAD

**Issue by wzup** [material-components/material-components-web#1050]
What does it mean? Cound you pls provide a code example. I can't understand what you mean. I'm sure many developers as well.

> Create a wrapper component for your framework of choice, and add a property which will be set to the value of the MDC-Web Component. We'll call this `mdcComponent`.

1. What _property_?
2. What _value_?
3. How to _add_ that _property_? Where to _add_ it?
4. What exactly do you call `mdcComponent`?

**Comment by Teoxoy** [comment]
When you use a framework, the framework usually has some sort of components (js files) that you can create. To use material-components-web in your framework, you can wrap the MDC-Web vanilla components (the index.js file in each component) or use the foundation file. I guess you are trying to wrap the vanilla components; to do that you need to import the index.js file, create a variable and assign it the value of your instantiated component.
To answer your questions:
1. you create it
2. the value of your instantiated component
3. add it to your js file
4. We'll call this `mdcComponent`. -> the variable will be called/named for example `mdcComponent` not call/invoke

**Comment by yeelan0319** [comment]
@Teoxoy Thanks for answering the question in detail. 
@wzup The answer Teoxoy provided is correct. Besides issue #407 do give a very good example how the thing could be used, I am going to close this issue here and hope this will help you.
