### ISSUE TITLE
Tabs / Edge 15: CSS-only tab bar has incorrect styles

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1055]
### What MDC-Web Version are you using?

0.16.0

### What browser(s) is this bug affecting?

Edge 15

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

In the [Tabs demo](http://material-components-web.appspot.com/tabs.html), look at the CSS-Only Tab Bar (2nd heading)

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/398379/28833340-11be3d22-76ad-11e7-95dc-6de9142dda18.png)

### What is the actual behavior?

![image](https://user-images.githubusercontent.com/398379/28833365-1cecb110-76ad-11e7-8e06-83cebd9dfe08.png)

In addition to the spurious background styles, nothing seems to happen on hover, whereas normally you'll see a faint underline and darker text if you hover over an unselected tab.

**Comment by Loggan08** [comment]
Same with mdc-Button

**Comment by kfranqueiro** [comment]
This is obsolete between the new implementation of MDC Tab Bar, and Edge's improved CSS variable support in 16+.
