### ISSUE TITLE
Broken demos in IE/Edge due to use of fat arrow and querySelectorAll().forEach

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1057]
### What MDC-Web Version are you using?

0.16.0

### What browser(s) is this bug affecting?

IE and Edge

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

I've noticed 2 demo pages that cause errors in IE and Edge due to this problem:

* [Slider](http://material-components-web.appspot.com/slider.html), when trying to use the checkboxes at the bottom of the page in Edge, or when the page loads in IE 11
* [Snackbar](http://material-components-web.appspot.com/snackbar.html) when the page loads in IE or Edge

### What is the expected behavior?

* The sliders in the Slider demo page should initialize, and the checkboxes at the bottom of the page should function correctly
* The snackbars in the Snackbar demo page should function correctly when you use the buttons at the bottom of the page

### What is the actual behavior?

* In the Slider page in IE 11, there is a syntax error due to use of fat arrow functions in the inline JS in the demo page
* In the Slider page in Edge, when you use the checkboxes at the bottom of the page, you get an error about `forEach`
* In the Snackbar page in IE 11 and Edge, the buttons at the bottom of the page don't open snackbars because the inline JS in the page encounters an error about `forEach` before it could finish executing

### Any other information you believe would be useful?

IIUC IE and Edge do not support `forEach` on the non-live NodeLists returned by `querySelectorAll`. Moreover, IE 11 does not support fat arrow functions since they're ES6-specific. Our demo pages are not transpiled so we need to stick to ES5 to accommodate all of our supported browsers.

Action items:

* [ ] Convert non-live NodeLists that will be iterated in these demos to arrays before calling `forEach`
* [ ] Convert fat-arrow functions to regular anonymous functions

**Comment by RobJacobs** [comment]
@kfranqueiro I can take this on...

**Comment by kfranqueiro** [comment]
@RobJacobs if you have spare cycles for it, that would be great! 🏁 

Thanks for offering, and let us know if you have any questions. 👍

**Comment by RobJacobs** [comment]
@kfranqueiro PR created, let me know if you see any problems.
