### ISSUE TITLE
Select CSS not displaying properly

### ISSUE THREAD

**Issue by DoubleTK** [material-components/material-components-web#1081]
### What MDC-Web Version are you using?

> material/select version^0.3.8

### What browser(s) is this bug affecting?

> Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### What OS are you using?

> Windows 8.1

### Framework

> Aurelia

### What are the steps to reproduce the bug?

> Import the mdc-select scss file

tk-select.scss
`@import "./node_modules/@material/select/mdc-select";`

> include that file in my material.scss file:

material.scss
`@import "./select/tk-select";`

> Include material.scss in my main app.scss file:

app.scss
`@import "./resources/material/material";`

> Reference it for select tags:

`select { @extend .mdc-select; }`

> Use it in my html:

app.html
`<select name="options" id="123">
        <option value="1">Test</option>
        <option value="2">Another test</option>
      </select>`

### What is the expected behavior?

> The component should look like this:

![image](https://user-images.githubusercontent.com/1087500/28996907-268f65b4-79d7-11e7-9081-3fcb2564a8a8.png)

### What is the actual behavior?

> The component looks like this:

![image](https://user-images.githubusercontent.com/1087500/28996910-413bd906-79d7-11e7-8dd3-4af57bb3fbca.png)

### Any other information you believe would be useful?

> Notice the extra "down arrow" for the select. It seems like it tries to do one style of CSS, and then loads the material css and applies that over the first one. A similar thing happens in Firefox. Also, the demo site works, so it's most likely something I'm doing, I just am not sure what.

**Comment by Teoxoy** [comment]
I had that issue. You are compiling sass without any autoprefixing. Quickfix for chrome: `-webkit-appearance: none;`. I would use an autoprefixer tho.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

The `appearance: none` declaration in `.mdc-select` should be suppressing the browser's default styles for `<select>`. I'm not sure why it's not working in this case.

I also haven't been able to reproduce the problem locally. Could you possibly provide a minimum-viable [CodePen](https://codepen.io/) so we can investigate further?

**Comment by acdvorak** [comment]
@DoubleTK, did the solution suggested by @Teoxoy work for you?

**Comment by acdvorak** [comment]
Feel free to reopen if you're still experiencing the issue 🙂

**Comment by DoubleTK** [comment]
Apologies for the late response, just now getting back to this project after vacation. @Teoxoy, your solution worked perfectly. I just used an autoprefixer and that did the trick. Thanks so much for your input. No need to re-open issue.
