### ISSUE TITLE
(dialog): Wrong z-index

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1095]
### What MDC-Web Version are you using?

> 0.17.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> All OS (Android 7, Windows 7 confirmed)

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/dialog.html
> 2. Open dialog
> 3. Observe the component's behavior

### What is the expected behavior?

> There should be a dark overlay over the toolbar

### What is the actual behavior?

> Dialogs z-index is 2 and there's no dark overlay over the toolbar

**Comment by acdvorak** [comment]
Nice catch, thanks @touficbatache!
