### ISSUE TITLE
(dialog): Wrong CSS with 'mdc-dialog__action'

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1096]
### What MDC-Web Version are you using?

> 0.17.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> All OS

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/dialog.html
> 2. Add the `mdc-dialog__action` class to any button
> 3. Observe the component's behavior

### What is the expected behavior?

> The button should be accent colored

### What is the actual behavior?

> Nothing happens

### Any other information you believe would be useful?

> This is because of wrong CSS, my last PR fixes it

**Comment by acdvorak** [comment]
Nice catch, thanks @touficbatache!
