### ISSUE TITLE
Theme: accent color should default to primary color

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#1099]
After talking to our designers, we felt that it doesn't really make sense to provide a specific default value for accent color, because it has a low likelihood of looking good with your brand's custom primary color.

**Comment by kfranqueiro** [comment]
Are we / should we be concerned about this being a breaking change? Also, what's the likelihood that users will customize primary but not accent?

Typically we want the accent color to be different than primary, correct? From a developer's point of view, I'd be concerned that this change would deliver the wrong point across - that it sounds like we're recommending primary = accent as a sane default, which IMO contradicts the purpose of accent color.

**Comment by acdvorak** [comment]
From discussion with our designers:

1. We want to explicitly support the use case where a client only customizes the primary color, and doesn't change anything else. This is likely a fairly common scenario, especially for folks who just want to download MDC-Web and quickly try it out, or for brands that don't have or want a secondary color.
2. We want MDC-Web to be "beautiful by default", and there's a significant chance that whatever we pick as a default for secondary color is **_not_** going to look good with your brand's primary color.
3. According to the [spec](https://material.io/guidelines/style/color.html#color-color-system), secondary color is optional; if it is not specified, we default it to primary color. So it's OK if they're both the same. However, you're absolutely right that we **_recommend_** choosing a secondary (accent) color that's different from your primary, so I added a comment to `mdc-theme/_variables.scss` in PR #1100 to that effect.

**Comment by Garbee** [comment]
I don't think that's exactly what the spec says on secondary.

> Using a secondary color is optional. It’s not necessary if you use variations of your primary color to accent elements.

I'm reading this as, if you don't have a secondary (accent) you should use a different *shade* from the same pallet. Not the exact same color itself. As the accent should still be distinct in some form from the primary so it can have the appropriate look where needed.

However, they also say above this:

> It can be complementary or analogous to your primary color, but it should not simply be a light or dark variation of your primary color.

Which tells me it shouldn't be just a different shade on the same color. But a color to either side of it on the pallet.

Overall, the spec seems to be contradicting itself here. My gut feeling though is they particularly don't want you to just re-use the same primary color as the accent outright. At least as it is written in the spec now.

**Comment by acdvorak** [comment]
Closing this issue after discussing with the team.

If the default secondary color clashes with a client's custom primary color, the client can simply change secondary to something else (including making it the same as primary).

Having a default secondary color that's different from the primary color is valuable because it makes it obvious to clients that there are two different theme slots which can be customized.
