### ISSUE TITLE
Button Shows no active state on iOS

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#110]
### What MDC-Web Version are you using?

Latest (0.1.1)

### What browser(s) is this bug affecting?

iOS Webkit (Chrome on iOS), 

### What OS are you using?

iOS 10.1.1

### What are the steps to reproduce the bug?

1. Navigate to http://material-components-web.appspot.com/button.html (or run the demo server)
2. Tap on the first button
3. Observe the result

### What is the expected behavior?

The button shows an active state

### What is the actual behavior?

There is no perceptible change

### Any other information you believe would be useful?

This happens because [Mobile Safari disables CSS active pseudo styles on web pages](https://alxgbsn.co.uk/2011/10/17/enable-css-active-pseudo-styles-in-mobile-safari/). Furthermore, we set `-webkit-tap-highlight-color` to transparent, so there is no highlight when the button is tapped.

I see two viable solutions to this:

1. Recommend that users follow the guidance in [this article](https://alxgbsn.co.uk/2011/10/17/enable-css-active-pseudo-styles-in-mobile-safari/), or use a library such as [FastClick](https://github.com/ftlabs/fastclick)
1. Experiment with setting `-webkit-tap-highlight-color` on the pseudo-element to the same color as it is when `:active`. We could also experiment with doing so on the button itself.

Ideally, I'd go for the second option since it requires no workarounds from the user, and plays nicely with what Mobile Safari does naturally. We could also instruct users to set `-webkit-tap-highlight-color` to transparent if they are using `FastClick` or the workarounds above.

**Comment by Garbee** [comment]
Option 2 is best. As it also allows it to operate without JS which is what we'd want here.

**Comment by sgomes** [comment]
Option 2 sounds good to me too 👍

**Comment by Garbee** [comment]
We just need to remember, that will also affect Chrome on other systems as well with touch. So, it would have wider effects than just iOS.

**Comment by traviskaufman** [comment]
Decided on option 2.
