### ISSUE TITLE
mdc-checkbox animationend event bubble

### ISSUE THREAD

**Issue by Ullfis** [material-components/material-components-web#1101]
### What MDC-Web Version are you using?

> material/checkbox 0.4.2

Many thanks for this project :)

### What is the actual behavior?

I am using your components together with Aurelia and have some trouble with `aurelia-animator-css` and page animations. The animator-css is listening for `webkitAnimationEnd` and `animationend` events and do some magic when that event raises. A problem I experience is that this event is raised and bubbles from `mdc-checkbox`. More specific here: https://github.com/material-components/material-components-web/blob/master/packages/mdc-checkbox/foundation.js#L73

Could you stop that event from bubbling? Something like this:

```javascript
this.animEndHandler_ = /** @private {!EventListener} */ ((e) => {

  // stop event propagation
  e.stopPropagation();

  clearTimeout(this.animEndLatchTimer_);
  this.animEndLatchTimer_ = setTimeout(() => {
    this.adapter_.removeClass(this.currentAnimationClass_);
    this.adapter_.deregisterAnimationEndHandler(this.animEndHandler_);
  }, numbers.ANIM_END_LATCH_MS);
});
```

**Comment by Garbee** [comment]
Hmm. These are native events being listened for. Stopping propagation may cause harm in other people's architecture if they are relying on them bubbling up.

Have you tried reaching out to the `aurelia-animator-css` team to see if they can scope when they do work to when they really need it instead of a broad stroke against all animation ends?

**Comment by Ullfis** [comment]
Ah... yeah you are right. I did not filter properly when listening for these animation events and focused my mind at wrong place. Thank you for the response and sry for the trouble.
