### ISSUE TITLE
Consider making a common package for browser utility functions

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1104]
I noticed we currently have 3 packages (drawer, ripple, toolbar) that define `util.applyPassive` for detecting passive event support and making use of it, and at least 2 packages (dialog and ripple) that define a function to detect support for custom CSS properties.

This leads to redundant implementation and test code, and in the latter case also has led to the two implementations skewing apart from each other.

We should consider putting common utilities like this in a centralized reusable package.  We should also probably check whether there is a reason (other than an oversight) why `supportsCssCustomProperties` in dialog's util hasn't kept up with the edge cases added to ripple's util.

**Comment by Spetnik** [comment]
My two cents: the lack of such a package threw me for a loop when replacing Array.prototype.find here: https://github.com/material-components/material-components-web/pull/1461/commits/5aa2b6b7d9e1dcc5383ae5bd90d4861d9b9dae31#diff-ab2630d7dd0cee3811f920a34f5efc3b

I felt like I should create a simple polyfill function (e.g. https://github.com/Spetnik/ie-Array.find/blob/master/README.md) but I really couldn't find a place where it made sense to add it. I would assume that this proposed package would be the perfect place for such a function.

**Comment by acdvorak** [comment]
We don't use polyfills in MDC-Web because we don't want to conflict with other libs or create weird hard-to-trace bugs, but I would love to create a centralized set of ponyfills (similar to polyfills, but without monkey-patching global prototypes) and other common utilities like `resize` event throttling.

**Comment by abhiomkar** [comment]
We now have `applyPassive` in @material/dom/events

Closing this.
