### ISSUE TITLE
Material Icons in FAB misaligned on iOS

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#111]
### What MDC-Web Version are you using?

Latest (0.1.1)

### What browser(s) is this bug affecting?

iOS (Chrome)

### What OS are you using?

iOS 10.1.1

### What are the steps to reproduce the bug?

1. Navigate to http://material-components-web.appspot.com/fab.html
1. Observe `Normal FABs` and `Disabled FABs` fieldsets

### What is the expected behavior?

The heart icons are aligned in the center of the FAB

### What is the actual behavior?

The heart icons are aligned to the left of the FAB

**Comment by Garbee** [comment]
I have a feeling this is Webkit not allowing `flex` based `button` elements.

**Comment by amsheehan** [comment]
I think @Garbee is correct. The fix I found was to add an element inside of the button and setting its width to 100%. There is a [post on Stackoverflow](http://stackoverflow.com/questions/35464067/flexbox-not-working-on-button-element-in-some-browsers) recommending to use the inner element as the flex container, but the browsers seem to be able to figure out the `justify-content` rule on the button and center the content in the inner `<span>`

The Chrome accessibility audit doesn't complain, but I would like to field other opinions on this implementation.

Lemme know what you all think

```html
<button class="mdc-fab material-icons">
    <span class="mdc-fab__icon">favorite_icon</span>
</button>
```

```css
.mdc-fab__icon {
    width: 100%;
}
```

**Comment by traviskaufman** [comment]
If the above works in all browser (incl. the ones which normally work with flex buttons), LGTM. The DOM change is unfortunate, but best we do it now.

FYI that we'll probably have to go through the demos and framework integration examples and change any instances of the FAB being used there as well.

**Comment by amsheehan** [comment]
It looks like the above will work. The exception being Edge/IE11. With Edge, the browser doesn't pick up the justify-content rule and apply it to the inner span. Instead, we must do as the original SO article recommends and apply flex and justify-content/align-items rules to that inner element.
