### ISSUE TITLE
Material ui compatible frameworks 

### ISSUE THREAD

**Issue by augmen** [material-components/material-components-web#1118]
whether material UI is compatible with polymer / React / Praectjs / vuejs / angularjs ? which is best framework for material UI ?

**Comment by tomscholz** [comment]
Try asking on stackoverflow. This is the wrong place to ask a question like this.

**Comment by acdvorak** [comment]
MDC-Web is designed to be framework-agnostic and easily integrate with other libraries.

See our [architecture docs](https://github.com/material-components/material-components-web/blob/master/docs/architecture.md) for more information.
