### ISSUE TITLE
Add missing typography leading spacing

### ISSUE THREAD

**Issue by joshunger** [material-components/material-components-web#1120]
Would it be possible to add the missing typography leading spacing?  

https://material.io/guidelines/style/typography.html#typography-line-height

How would you re-create each example in the above link using the CSS classes?

EDIT: looks like `mdc-typography--adjust-margin` is used to fix the leading spacing between typography styles.  It would be helpful to explain when and why you would need to adjust the margin.

**Comment by tqle** [comment]
New to this framework but forgive me  on if this is not implemented in ths framework. Still reading through this to see if what is there.  The style guide on the material link above is based on a type system, usually something based on golden rule of proportions.  This headings, body, text are based on the font chosen, in this case Roboto, and a base font size, something like 16px. Based on this default base font size and type, you can calculate the each of the font sizes and also the line-heights.  One of the issues, I see in most frameworks is the miss-use of line-height. Line-height is unitless and doesn't need to know it's unit.  This is a great link on line-height,https://css-tricks.com/almanac/properties/l/line-height/.  To create a strong typopgraphy system that properly scales and addresses line height issues I suggest reading this:  https://pearsonified.com/2011/12/golden-ratio-typography.php

The material site is missing some other things that should be addressed.
You can have H1-H6 headings, some of these smaller headings can be considered subheadings but I've worked on systems where you can use H1 or H6 . The dislay 1 to 4 can be misleading and should include those.  Most screen readers can read H1-H6.  Some of the text variations can have the same scale as these but with variables and mixins you scale and re-use. That is where having this calculated system with SASS/LESS is powerful.
You can easily assign the correct type scaling and line heights directly to the H1-H6,body, label, span, etc... assuming you have normalized or reset the type and body font size.

The key advanced of re-usable typography system is that you can use the same rules to scale for other languages that are not 16px or not based on Roboto. Line-height becomes an issues in other locales besides Noto Sans but areas like Arabic, Cyrillic have different type scales themselves. I've worked in systems where users want to change fonts to match their companies standards and having a strong type system defined fixes a lot of the line-height issues.  

I'm interested in what you have, so I have to dig in what you have or point me to what is implemented.  Still learning and reading through this framework.

**Comment by patrickrodee** [comment]
We now provide baseline mixins. Please use those.

https://github.com/material-components/material-components-web/blob/39ed5fe73c20ebf579aa7e5aef23dfdec3b5cda2/packages/mdc-typography/_mixins.scss#L79-L112
