### ISSUE TITLE
Grid Layout and form elements

### ISSUE THREAD

**Issue by battoualex** [material-components/material-components-web#1122]
Would it be possible use the grid layout to adjust the form's width (input, textfield, etc)? By default, inputs takes a width of 100%

Thanks

**Comment by acdvorak** [comment]
Could you provide a [CodePen](https://codepen.io/)?

**Comment by kfranqueiro** [comment]
Hi @battoualex,

We just released 0.18.0 today - do you still experience the same problem with the latest version, and if so, could you provide an example via our [CodePen template](http://codepen.io/traviskaufman/pen/pNQmRp) so we can easily reproduce the issue?

Thanks!

**Comment by kfranqueiro** [comment]
Given no further response and that we don't have enough details to address the specific question or problem, I'm closing this issue. Please feel free to reopen if you can provide a CodePen demonstrating your specific problem. Thanks!
