### ISSUE TITLE
A "Palette Library" for the web?

### ISSUE THREAD

**Issue by dobleuxyz** [material-components/material-components-web#1123]
Something similar to Palette Library on Android, so we can extract prominent color from images, translate them into Material Design colors and apply those over specific parts of the UI.

https://developer.android.com/training/material/palette-colors.html#set-up-the-library

This would be very useful and a nice addition since I know you are planning on bringing the material color palette to MCW too (https://github.com/material-components/material-components-web/issues/27). I think a tool like this would be a good incentive to start applying the material color palette across different projects as well, which I know is optional but still something the MD Spec seems to encourage.

Thank you.

**Comment by acdvorak** [comment]
We'd like to do this eventually, but it probably won't be anytime soon.

In the meantime, there's probably a third party JS lib that can do what you're looking for 🙂
