### ISSUE TITLE
Halo doesn't disappear after click switch.

### ISSUE THREAD

**Issue by eromoe** [material-components/material-components-web#1127]
For example:

![image](https://user-images.githubusercontent.com/3938751/29303480-c79a15d6-81bf-11e7-8080-de7e223a3d98.png)
![image](https://user-images.githubusercontent.com/3938751/29303508-f4f83012-81bf-11e7-9878-c276b4bbad43.png)

Need click at other place to make halo disappear:
![image](https://user-images.githubusercontent.com/3938751/29303500-e3286da2-81bf-11e7-82fa-848ec48f9af8.png)

Can reproduce on(chrome 60)
https://material-components-web.appspot.com/switch.html

If it is by design , would you please add a property for `switch` make halo disappeared after clicking?

**Comment by dessant** [comment]
I've also noticed the switch component is not finished yet. It will likely have a js API and ripple support, like checkbox and radio.

**Comment by acdvorak** [comment]
This is an intentional usability/accessibility feature, and mirrors the browser's default behavior for focusable elements (albeit with different styling).

Users who rely on keyboard navigation need to know which element currently has focus, so disabling the halo would make the component unusable for them.

**Comment by dessant** [comment]
@acdvorak, I think what the user is requesting is a full fidelity implementation of the switch component.

**Comment by eromoe** [comment]
@acdvorak ,  I totally understand what you concern. But I think auto disappeared halo may be the better default behave, because:

1. Most of people don't use keyboard in browser , current behave make them feel strange. (Maybe browser's default focus style is not so distinct)
2. On mobile, I think almost no one would use mini keyboard in browser .

**Comment by MihirNS** [comment]
I second @eromoe's opinion to add property to make halo disappear.
