### ISSUE TITLE
Does this work with Vue.js ?

### ISSUE THREAD

**Issue by srinivasdamam** [material-components/material-components-web#113]

**Comment by traviskaufman** [comment]
Hey @srinivasdamam,

As we mention in our [Material Components CONTRIBUTING docs](https://github.com/material-components/material-components/blob/develop/CONTRIBUTING.md#questions), please use StackOverflow for questions, and tag using `material-components` and `web`.

To answer this questions, yes, it does. Check out our [VueJS example](https://github.com/material-components/material-components-web/tree/master/framework-examples/vue). It may not work correctly as of yet (see #107), but we're working on that :)
