### ISSUE TITLE
Add package name to root package.json

### ISSUE THREAD

**Issue by simov** [material-components/material-components-web#1160]
Can you add a package name to the root `package.json` like this:

```json
"name": "material-components-web"
```

That way I'll be able to install the latest tag from GitHub:

```bash
npm i --save-dev https://github.com/material-components/material-components-web.git#v0.17.0
```
```
npm ERR! Can't install git+https://github.com/material-components/material-components-web.git#a88add69ea2872dc91061e0ab9e52fc3145863b9: 
Missing package name
```

I need that to create custom javascript build for my project, because otherwise I get too much code duplicates from the minified dist files published for each individual component on NPM.

Thanks!

**Comment by Garbee** [comment]
This isn't possible with the Lerna setup for generating the release packages. As the repository itself is never distributed as a whole. It is a subpackge (in `packages/material-components-web` ) that gets built and sent to NPM. So even if the name were there, it would be entirely different structurally then what you get via NPM.

**Comment by simov** [comment]
Hi @Garbee,

I want to install the contents of the GitHub repository using NPM, not the subpackage that gets published on NPM.

The `name` key is required for:

```bash
npm i --save-dev https://github.com/material-components/material-components-web.git#v0.17.0
```

to succeed.

Having `private: true` in the root `package.json` is good, you won't be able to publish it by mistake. In fact, you can set another `name` in the root `package.json`.

After I have the contents of the GitHub repository downloaded via NPM CLI, I can then build my own `material-components-web.min.js` containing only the components that I need. 

Having standalone dist versions of each component is not the same, because that way each component contains a copy of the same base code that it inherits.

**Comment by simov** [comment]
Just by looking at the installed packages again and it seems I got misled by the fact that some packages are css only, and I though that only the dist folder is being published. Anyway, I think I'll be able to build my own thing now :+1:
