### ISSUE TITLE
framework example vue can't be built -> webpack: Failed to compile.

### ISSUE THREAD

**Issue by TonySpegel** [material-components/material-components-web#1161]
Probably for @pgbross 

### What are the steps to reproduce the bug?
1. download the material-components-web repository
2. change into framework-examples/vue/
3. Run npm install within this folder
4. Run npm start to start the demo server
5. Navigate to http://localhost:8080 to view the demo.

### What is the expected behavior?
Seeing the demo

### What is the actual behavior?
Couple of undefined variables and this output:
![bildschirmfoto vom 2017-08-20 02-32-25](https://user-images.githubusercontent.com/1145514/29491047-d33e1584-854f-11e7-9474-8af840de5f3e.png)

`tony@Rhea:~/Schreibtisch/_dev-web/material-components-web-master/framework-examples/vue$ npm start

> v-mdc-example@0.1.0 start /home/tony/Schreibtisch/_dev-web/material-components-web-master/framework-examples/vue
> node build/dev-server.js

Listening at http://localhost:8080

webpack built 8c253ed4ac3fbfa712f0 in 5531ms
Hash: 8c253ed4ac3fbfa712f0
Version: webpack 1.15.0
Time: 5531ms
 Asset     Size  Chunks       Chunk Names
app.js  1.96 MB       0       app

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-2a55d13d!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
Module build failed: 
$mdc-elevation-transition-timing-function: $mdc-animation-standard-curve-timing-function !default;
                                          ^
      Undefined variable: "$mdc-animation-standard-curve-timing-function".
      in /home/tony/Schreibtisch/_dev-web/material-components-web-master/framework-examples/vue/node_modules/@material/elevation/_variables.scss (line 122, column 44)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-2a55d13d!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-240 13:2-17:4 14:20-246

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-dde26d9a!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/v-mdc-snackbar/Snackbar.vue
Module build failed: 
$mdc-elevation-transition-timing-function: $mdc-animation-standard-curve-timing-function !default;
                                          ^
      Undefined variable: "$mdc-animation-standard-curve-timing-function".
      in /home/tony/Schreibtisch/_dev-web/material-components-web-master/framework-examples/vue/node_modules/@material/elevation/_variables.scss (line 122, column 44)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-dde26d9a!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/v-mdc-snackbar/Snackbar.vue 4:14-257 13:2-17:4 14:20-263

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-60ce7e50!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/v-mdc-drawer/TemporaryDrawer.vue
Module build failed: 
$mdc-elevation-transition-timing-function: $mdc-animation-standard-curve-timing-function !default;
                                          ^
      Undefined variable: "$mdc-animation-standard-curve-timing-function".
      in /home/tony/Schreibtisch/_dev-web/material-components-web-master/framework-examples/vue/node_modules/@material/elevation/_variables.scss (line 122, column 44)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-60ce7e50!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/v-mdc-drawer/TemporaryDrawer.vue 4:14-264 13:2-17:4 14:20-270
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  22.6 kB       0       
webpack: Failed to compile.`

**Comment by pgbross** [comment]
Curious, I just made a fresh clone of the [https://github.com/material-components-web](https://github.com/material-components-web) repository (latest version master branch >0.17.0) as per your repo steps.

Then using node v8.4.0 ran:

```
1. cd framework-examples/vue
2. npm install
3. npm start
```

There were no faults so it is not clear why you are seeing errors. 

If you followed different steps or reused a previous clone of the github repository, can you try again with a fresh clone of the master repository to make sure you have a consistent set of sources. If that still fails then looking at differences in environment (node version, npm version, operating system version etc) is going to be needed as the `$mdc-animation-standard-curve-timing-function` variable is clearly defined in the `packages/mdc-animation/_variabled.scss` source file.

hope that help start to track down the fault for you.
--philip

**Comment by TonySpegel** [comment]
Hi Philip,

this was clearly a issue with my node-version because I had an older version installed (v6.x.x).
Installing v8.x.x solved my problem. I should have stated my version, sorry it was kind of late here.

Have a nice day
