### ISSUE TITLE
Buttons should have 2px border-radius

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1163]
### What MDC-Web Version are you using?

> 0.18.0

### What browser(s) is this bug affecting?

> All browsers.

### What OS are you using?

> All OS

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/button.html
> 2. Click on the button
> 3. Observe the component's behavior

### What is the expected behavior?

> The button should have a 2px `border-radius`

### What is the actual behavior?

> The button should has a 4px `border-radius`

### Any other information you believe would be useful?

> According to the guidelines, "Buttons should have a 2dp corner radius" : https://material.io/guidelines/components/buttons.html#buttons-style
![image](https://user-images.githubusercontent.com/17137918/29536180-795adb02-86c5-11e7-9d63-965a8195e97d.png)

**Comment by touficbatache** [comment]
So, what's up with that? I can fix it right now if needed.

**Comment by tomscholz** [comment]
This should be very easy to fix or was there a reason why choose 4px over 2px?

**Comment by touficbatache** [comment]
It acually is very easy! I'm not sure why they chose 4px over 2px 🤔

**Comment by yeelan0319** [comment]
@touficbatache Thanks for pointing this out.

We were constantly doing some experiments and this got accidentally changed. 
Addressing it in the coming PR.
