### ISSUE TITLE
Fix CommonJS and AMD examples in READMEs

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1168]
The CommonJS and AMD examples still reference non-namespaced package names. This was pointed out during the review process for #1091.

Moreover, I don't think the CommonJS examples would actually work verbatim, since loading each package's `index.js` will lead to errors due to Node.js not understanding ES2015 imports, so I think these examples should probably point to dist, and probably the same for the AMD examples. We should test to make sure the patterns used in the examples work before or during review of a PR for this.

**Comment by patrickrodee** [comment]
Can confirm that the CommonJS examples do not work without [babelify](https://github.com/babel/babelify) or some other ES2015 import converter.

[Here's a simple example on Glitch that shows the problem.](https://glitch.com/edit/#!/failing-commonjs-demo) Clicking on "Logs" in the upper left corner will show the error output.

Possible solutions are to suggest users either not use CommonJS or **strongly suggest** Babelify or equivalent to make the the build work.

**Comment by kfranqueiro** [comment]
If we update the examples to point to `.../dist/mdc.foo.js` instead, that should work in Node or with an AMD loader, because those files are wrapped in the UMD format. We certainly shouldn't need to make the examples as involved as requiring transpilation.
