### ISSUE TITLE
Getting Started docs shouldn't promote form-field around textfield

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1169]
This was pointed out by #1162. mdc-form-field is redundant in the context of mdc-textfield since the latter already manages its own label, and the former's styles will cause problems for textfields with help text. We should update the Getting Started guide somewhat akin to my forked codepen in the aforementioned issue:

* [ ] Apply a typography class to the form itself so it still uses the proper font
* [ ] Remove the use of mdc-form-field
* [ ] Update layout/styling as necessary

**Comment by asyncLiz** [comment]
Closing since [getting-started.md](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) no longer references form-field.
