### ISSUE TITLE
(ripple): Programmatically trigger ripple animation

### ISSUE THREAD

**Issue by AustP** [material-components/material-components-web#1171]
Given the following HTML:

    <label>
      <i
        aria-label="Add to favorites" tabindex="0"
        aria-pressed="false"
        class="mdc-icon-toggle material-icons"
        data-toggle-on='{"label": "Remove from favorites", "content": "favorite"}'
        data-toggle-off='{"label": "Add to favorites", "content": "favorite_border"}'
        id="icon-toggle"
        role="button"
      >
          favorite_border
      </i>
      <span id="span">Add to favorites</span>
    </label>

I want it so when someone clicks the `span`, the icon-toggle is clicked with the ripple animation. Right now the logic in my span click handler is this:

    iconToggleElement.click();
    mdcIconToggleInstance.ripple_.foundation_.animateActivation_();

This seems less than ideal since I'm accessing 3 internal APIs to activate the animation. I assumed that calling `click` on the element would trigger the animation automatically but it doesn't. What is the best way to trigger a ripple animation without relying on internal APIs?

**Comment by kfranqueiro** [comment]
The mdc-ripple component exposes a public `activate` API, but as you pointed out, it looks like the mdc-icon-toggle component doesn't expose its ripple instance. It seems like it would be reasonable for it to do so, as other components such as mdc-checkbox do.

Would you be willing to file a PR to [expose](https://github.com/material-components/material-components-web/blob/v0.18.0/packages/mdc-checkbox/index.js#L101) (and [test](https://github.com/material-components/material-components-web/blob/v0.18.0/test/unit/mdc-checkbox/mdc-checkbox.test.js#L134)) a getter for ripple at the component level?

Thanks!

**Comment by kfranqueiro** [comment]
Somehow this wasn't properly linked and closed, but `ripple` is now exposed on both the deprecated Icon Toggle component and the new Icon Button component which replaces it.
