### ISSUE TITLE
No way to chop tablet grid cells into thirds. 

### ISSUE THREAD

**Issue by SgtPooki** [material-components/material-components-web#1172]
### What MDC-Web Version are you using?

> 0.18.0

### What browser(s) is this bug affecting?

> All.

### What OS are you using?

> All.

### What are the steps to reproduce the bug?

1. Look at your source code.
2. Note that you don't support any possibility for dividing the tablet's 8 cols by 3 (you don't support 3_8, nor 2.6667, nor 1/3, etc..)
3. Also check out https://codepen.io/SgtPooki/pen/RZJWgv and be sure to look at the tablet size.

### What is the actual behavior?

> It's impossible to center three cells in tablet and phone view because your layout system isn't flexible enough to support this (why even provide a grid system if you're not going to provide more than flexbox?)

### Any other information you believe would be useful?

> Maybe i'm missing something but.. I feel like as a design framework you should provide guidance on layout as a minimum. Also, you should remove the deprecated warning from MDL because MDC seems like it's not even close to ready.

**Comment by aaronhudon** [comment]
"Thirds" are a fundamental part of design - can someone chime in on the decision of going with 8 and 4 for tablet and mobile respectively?
I'd think 12 - 9 - 3 would have been more appropriate, but what do I know...

**Comment by kfranqueiro** [comment]
Thanks for raising this question. We're reaching out to our designers for more information.

**Comment by kfranqueiro** [comment]
Thanks for your feedback; our design team will be taking it into consideration, and we'll be sure to update when we receive further direction.

In the interim, you may wish to use other CSS-based solutions in place of the MDC Web layout grid in order to accommodate your use case on mobile and tablet.

**Comment by touficbatache** [comment]
Is this being worked on? @kfranqueiro

**Comment by Garbee** [comment]
@touficbatache The team is awaiting feedback from the MD Spec team when they get around to reviewing this. Until that happens, nothing is getting worked on internally.

**Comment by touficbatache** [comment]
@Garbee Hmm, I'll try to find a workaround. Thanks!

**Comment by kfranqueiro** [comment]
We've discussed this with design, and currently there are no plans to change the [guidelines](https://material.io/guidelines/layout/responsive-ui.html). Given that MDC's current implementation (as well as MDL's before it) does align with the guidelines, we don't intend to change this at the moment.

I realize this design choice may be frustrating in some cases where it ends up conflicting with your own custom designs. In cases where you already have a clear design in mind which doesn't mesh well with the Material Design guidelines, it probably makes more sense to use a third-party CSS grid system (or native [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) if all of your targeted browsers [support it](http://caniuse.com/#feat=css-grid)) in place of MDC Layout Grid.

At the same time, I do intend to provide more information to our designers on how the web platform in particular may warrant more attention, so perhaps we can improve upon this in MDC Web in the future.
