### ISSUE TITLE
Slider: Discrete slider not initializing current value

### ISSUE THREAD

**Issue by archnode** [material-components/material-components-web#1173]
### What MDC-Web Version are you using?

v. 0.0.18

### What are the steps to reproduce the bug?

1. Set aria-valuenow to a certain value
2. Initialize the Slider with autoinit or js
3. Check the initialized sliders value

### What is the expected behavior?

The initial state of the slider is set to the value specified with aria-valuenow.

### What is the actual behavior?

The initial value of the slider is shown (and initialized as) zero.

### Other information

The behavior can be observed in the demos as well. 
Thanks for your work on these great components!

**Comment by aaronhudon** [comment]
Quick codepen using latest sources show's it's broken as of 2017-08-24

https://codepen.io/aaronhudon/pen/xLJPMY

**Comment by kfranqueiro** [comment]
Thanks for bringing this to our attention! Definitely seems like a bug.

**Comment by kfranqueiro** [comment]
Based on fiddling with the unpkg URLs in @aaronhudon's CodePen, it looks as if this worked in 0.14.0 but doesn't work in 0.15.0.  That should help us narrow down to investigate.

**Comment by archnode** [comment]
Tried my best to provide a pull request and a (micro) fix for this.
