### ISSUE TITLE
Error when import SCSS from node_modules

### ISSUE THREAD

**Issue by iamdubx** [material-components/material-components-web#1175]
I am using Vue CLI webpack starter. 

```
<style lang="scss">
@import '@material/checkbox/mdc-checkbox';
</style>
```
This gives me an error 
```
in ./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-563a1fd0","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Checkbox.vue
Module build failed: 
@import '@material/checkbox/mdc-checkbox';
^
      File to import not found or unreadable: @material/checkbox/mdc-checkbox.
Parent style sheet: stdin
      in /home/nman/Documents/WORK/frontend-dev/mdc-vue-integration/src/components/Checkbox.vue (line 72, column 1)
 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-563a1fd0","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Checkbox.vue 4:14-397 13:3-17:5 14:22-405
 @ ./src/components/Checkbox.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```
What is happening? Why so hard to get started?

**Comment by matsp** [comment]
Your webpack config is invalid.

Use this as rule:
```
{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            scss:[
              { loader: 'vue-style-loader' },
              { loader: 'css-loader', options: {minimize: true} },
              { loader: 'sass-loader',
                options: {
                  includePaths: glob.sync('node_modules').map((d) => path.join(root, d))
                }
              }]
}
```

**Comment by iamdubx** [comment]
@matsp thanks for the support. Let me try it. 

Also, I don't see any like this webpack config in this example - https://github.com/material-components/material-components-web/tree/master/framework-examples/vue

**Comment by iamdubx** [comment]
I tried it. Didn't work. Errors. Webpack config is killing me. Why to make so complicated so simple things!

**Comment by matsp** [comment]
Provide an error message please.

**Comment by iamdubx** [comment]
It's huge. Here's start:

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { console: [Getter],
  global: [Circular],
  process: 
   process {
     title: 'node',
     version: 'v8.2.1',
     moduleLoadList: 
      [ 'Binding contextify',
        'Binding natives',
        'Binding config',
        'NativeModule events',
        'Binding async_wrap',

```

**Comment by matsp** [comment]
require 'glob' and 'path' in your config. 

Just a tip of mine: start from scratch and learn one step after the other ;-)

**Comment by iamdubx** [comment]
I required it of course.

**Comment by iamdubx** [comment]
I don't need to learn webpack to import one file. Don't you think it's just strange tip?

**Comment by matsp** [comment]
Sorry my mistake... 'root' in my code have to point to your root of the project, so create the variable or type in the string directly. It is not easy to help with the information you provide.

**Comment by iamdubx** [comment]
>  It is not easy to help with the information you provide

I am using blank vue-cli webpack starter. That's literally all.

After changing `root` to `__dirname` I have no errors, but no styles are applied. So nothings working.

**Comment by matsp** [comment]
Are you building for production or development? Are you extracting CSS in one file or inline it? How does your sourcecode look like? Your package.json? Questions over questions..

Because of that my opinion is that you should get a feeling of webpack without any starter - it is too much magic in the first time.

I will help you but please tear down the destructive mood, it is the mdc repo and not Webpack or Vuejs.

**Comment by iamdubx** [comment]
> Are you building for production or development?

You mean how I ran app? In dev of course, I have nothing to build yet.

> Are you extracting CSS in one file or inline it? How does your sourcecode look like? Your package.json? Questions over questions..

This isn't a questions, dude, I told 2 times that I use vue-cli webpack starter. Don't say you never use it before :smile: 

> I will help you but please tear down the destructive mood, it is the mdc repo and not Webpack or Vuejs.

I really appreciate your support. Webpack config really can be tough. And I agree, that I need to change mood if I need to resolve this issue. Today I spend most time learning webpack already :+1:

**Comment by matsp** [comment]
I never used it... I invested a lot of time to understand the whole ecosystem piece by piece. This is the origin of my advice to you. Most people doesn't care about their used solutions and just want all features with no effort. They will get stuck after the first problem for sure.

**Comment by iamdubx** [comment]
...then you must now hat using webpack is really hard, especially when there are 70% examples with webpack 1, `vue-cli` using webpack 2, and `vue-loader` doesn't support webpack 3 fully yet :smile: 
I gone thought hell past 2 days with webpack. It's almost impossible to learn.

Anyway, I got working solution thanks to one very kind guy from Vue Discord channel.

**Comment by Ellanskii** [comment]
and what's the solution you got? I've spent hours with no result, I'm totaly stack

**Comment by BinaryShrub** [comment]
I'm struggling to get a solution as well. Here is what I currently have with no luck.
``` javascript
{
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      scss: [
        'vue-style-loader',
        'css-loader',
        {
          loader: 'sass-loader',
          options: {
            includePaths: ['./node_modules']
          }
        }
      ]
    }
  }
}
```

```
ERROR in ./src/pages/Home.vue?vue&type=style&index=0&id=5a90ec03&lang=scss&scoped=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Home.vue?vue&type=style&index=0&id=5a90ec03&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '@material/list/mdc-list';
^
      File to import not found or unreadable: @material/list/mdc-list.
      in [...]/src/pages/Home.vue (line 61, column 1)
```

Any help would be greatly appreciated...

**Comment by anlexN** [comment]
includePaths: [path.resolve(__dirname, 'node_modules/@syncfusion')]
