### ISSUE TITLE
Rewrite to RSCSS

### ISSUE THREAD

**Issue by JosefJezek** [material-components/material-components-web#1193]
BEM :hankey: :-1:
```html
<div class="mdc-layout-grid">
  <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6 mdc-layout-grid__cell--span-8-tablet"></div>
</div>
```

RSCSS :eyes: :+1:
```html
<div class="mdc-grid">
  <div class="cell -span-6 -span-8-tablet"></div>
</div>
```
http://rscss.io

**Comment by Garbee** [comment]
RSCSS due to having non-namespaced classes internally can lead to collisions with external code that could be pulled in. BEM was a specific design choice for the API since it namespaces everything provided into isolated components that have the least chance for external collisions.

If you'd like to use an RSCSS setup in your app, you have Sass available to write your own API layer.

**Comment by kfranqueiro** [comment]
As @Garbee explained, this was a conscious design decision by the material-components-web team. While BEM classnames are admittedly more verbose, they greatly reduce the chance of conflict when used together with other third-party libraries as well as your own styles, and also promote lower specificity selectors in general.

In contrast, using the RSCSS example above, it'd be very easy for multiple libraries or your own code to coincidentally define styles for the same selector (e.g., `.cell`) and end up in conflict with each other. It also seems to advocate nesting selectors to a higher degree, which has the potential to cause additional difficulties when the need arises to override styles.

Avoiding conflicts and difficulties with other code is crucial for a library like MDC Web, which is designed to be usable regardless of what other JS or CSS frameworks you may also be using. We appreciate the suggestion, but in this particular case, we have strong reasons for having chosen BEM.

**Comment by JosefJezek** [comment]
@kfranqueiro @Garbee rules `.mdc-grid > .cell` and `.mdc-grid > .cell.-span-6` have minimal conflict.

**Comment by JosefJezek** [comment]
https://medium.com/stantmob/rscss-styling-your-css-without-losing-your-sanity-36bca30520f1

**Comment by amsheehan** [comment]
We appreciate the suggestion, but we don’t plan on changing the convention for the foreseeable future.

Thank you

**Comment by Garbee** [comment]
@JosefJezek What about any other given library that defines `.cell` as a class name? Given your example those rules will then get applied to an `.mdc-grid > .cell` as well. Hence, conflicts. Collision isn't only about *within* MCW, it is also thinking about how *other* libraries or user-land code may interact with what is provided. BEM allows for the proper scoping and a well structured way to organize the code for maintenance.
