### ISSUE TITLE
MDC-Web Framework Integration Example for React - does not show how to import stylesheets aka theme

### ISSUE THREAD

**Issue by redimongo** [material-components/material-components-web#1218]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs
I followed your npm install for the example react project, however it is missing the theme. I went to put a toolbar in and the toolbar did not generate after I saved the .js file.

### What MDC-Web Version are you using?
v0.19.0 

### What browser(s) is this bug affecting?

Not browser but core code.

### What OS are you using?

windows 10

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.
>
> 1. Run npm install within this folder
> 2. Run npm start to start the demo server
>

### What is the expected behavior?

I just want to know how to add the theme and additional JS and CSS files.

**Comment by kfranqueiro** [comment]
Would it be possible for you to provide a gist or repo that demonstrates the changes you attempted to apply on top of the out-of-the-box react example, so we can attempt to provide help based on what you've tried? Thanks!

**Comment by j-o-d-o** [comment]
This seems more of a StackOverflow question then a GitHub issue, correct me if I'm wrong. Also, In my opinion, the example shows both of your questions. In _Checkbox.js_ you can find the code: `import '@material/checkbox/dist/mdc.checkbox.css';` which imports the styles needed for the mdc component.  In the same file you can also find the import of the JS file for the checkbox component: `import {MDCCheckboxFoundation} from '@material/checkbox/dist/mdc.checkbox';`

Here an example how to use a Dialog within React:
```
import React from 'react';
import { MDCDialog } from '@material/dialog/dist/mdc.dialog';

class DialogTest extends React.Component {
    constructor(props) {
        super(props);

        // Init state
        this.state = {
        };
    }

    componentDidMount() {
        this.dialog = new MDCDialog(this.refs.dialog);
        // provide control to parent component to open the dialog from there
        this.props.provideCtrl({
            show: () => this.dialog.show(),
            close: () => this.dialog.close()
        });
    }

    componentWillUnmount() {
        this.props.provideCtrl(null);
    }

    render() {
        return (
            <aside
                ref="dialog"
                id="test_dialog"
                className="mdc-dialog"
                role="alertdialog"
                aria-labelledby="test_dialog-label"
                aria-describedby="test_dialog-description">
                <div className="mdc-dialog__surface">
                    <header className="mdc-dialog__header">
                        <h2 id="test_dialog-label" className="mdc-dialog__header__title">Test Dialog</h2>
                    </header>
                    <section className="mdc-dialog__body">
                    </section>
                    <footer className="mdc-dialog__footer">
                        <button onClick={() => this.dialog.close()}>CLOSE</button>
                    </footer>
                </div>
                <div className="mdc-dialog__backdrop"></div>
            </aside>
        );
    }
}

export default DialogTest
```
With regards to CSS. I usually use SCSS and in my main SCSS files, I import all the SCCS files I need. e.g.:
```
@import 'scss/variables';

@import "@material/checkbox/mdc-checkbox";
@import "@material/dialog/mdc-dialog";
```
in variables.scss I would then override styles from the MDC styles I would like to have changed for my project. e.g.:
```
$mdc-theme-primary: #404040;
$mdc-theme-accent: #a349a3;
$mdc-theme-background: #fff;
```

**Comment by lynnjepsen** [comment]
@j-o-d-o's reply shows a good example on how to use mdc-theme in React, so closing this issue.
