### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by zomars** [material-components/material-components-web#1227]
### What MDC-Web Version are you using?

> 0.19.0

### What OS are you using?

> macOS Sierra

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.
>
> 1. Using react-scripts build
> 2. Do `yarn build`
>

### What is the expected behavior?

> No errors.

### What is the actual behavior?

> I get the following error:
```
$ yarn build
yarn build v0.27.5
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/@material/base/foundation.js:20

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

**Comment by isidrok** [comment]
Possibly related to https://github.com/material-components/material-components-web/issues/929

Try parsing the module to ES2015 first.

**Comment by lynnjepsen** [comment]
I think react went through some updates recently. If you update react (which will then update react-scripts) do you get the same error?

**Comment by Shyam-Chen** [comment]
#669

**Comment by zomars** [comment]
I'm getting the same message after updating.

**Comment by lynnjepsen** [comment]
We will investigate changing MDC web release to match create-react-app's policies more officially....but we need time to investigate if that breaks other parts of our release process, or other clients relying on us.

**Comment by isidrok** [comment]
I'm pretty sure that error is given because in the package.json the main property is pointing to ES6 modules , I haven't used react-apps before but from looking at the source it uses Webpack for the build process, with the this [configuration](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L290).

As you can see it is using UglifyJS for minimizing the output and as far as I know it doesn't work with ES6 modules (for example _class_ will be identified as an invalid keyword) and thats presummably why the error is given in the minify process.

To check it out use Babel to transpile ````@material``` modules inside node_modules before using the scripts or change the main of the package.json to the transpiled modules inside dist folder, for more information check the [issue](https://github.com/material-components/material-components-web/issues/929) I mentioned in my last comment.

**Comment by shatyajeet** [comment]
Hi. Is there an update this issue? Or a workaround for the time being?

**Comment by Shyam-Chen** [comment]
Webpack -> Rollup. Rollup is more friendly to the Library.

**Comment by asiop** [comment]
Quick temp workaround, not for production - Create-React-App: 

Go to:
/node_modules/react-scripts/config/webpack.config.prod.js
Mark out:
webpack.optimize.UglifyJsPlugin, 
(lines 288-304 that will probably be outdated by tomorrow)

Build product won't be minimized and without an eject, this will be overriden when you update-react-scripts
 
That's all I know :)

**Comment by isidrok** [comment]
I'm currently adding `node_modules/@material` to the include option of babel, haven't tried using Webpack but works fine with Rollup, to do so in Webpack modify [this line](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L173) inside `/node_modules/react-scripts/config/webpack.config.prod.js`

**Comment by pedro-sanchez** [comment]
I had the problem with webpack and solved.

first add npm devDependencies in package.json:
"babel-core": "6.26.0",
"babel-loader": "7.1.2",
"babel-preset-es2015": "^6.24.1"

Still in package.json add the code bellow  after block devDependencies
  "babel": {
    "presets": [
      "es2015"
    ]
  }

That's able compilation for es2015.
In webpack rules add the follow rule

{
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: helpers.root('node_modules'),
        include: [
        	MDC_DIR
        ]
    }

where MDC_DIR is location of material modules
var MDC_DIR = path.resolve(__dirname, '../../../../node_modules', '@material');

when i do this i can uglify material dependencies in my vendor.js

I hope I have helped

**Comment by endersaka** [comment]
@isidrok how should I modify that path? Honestly I am not expert with all this software packages.
I have tried: `include: [ paths.appSrc, paths.appNodeModules + "@material" ]`, but it doesn't work. I bet that I have passed the path in the wrong way. :-D

**Comment by isidrok** [comment]
@endersaka This works for me using `rollupjs`:
```js
babel({
            include: [
                'node_modules/@material/**',
                'src/**'
            ]
        })
```
With `webpack` you would need something like this (using `include`):
```js
 include: [
    path.resolve(__dirname, "src"),
    path.resolve(__dirname, "node_modules/@material")
  ]
```
or this (with `exclude`):
```
{
  test: /\.js$/,
  exclude: /node_modules\/(?!(@material)\/).*/,
}
```
Note that `include` and `exclude` cannot be used at the same time with `babel`.
Hope it helps!

**Comment by s-a** [comment]
@lynnjepsen any news about this issue? I recently got the same error as @zomars. Regarding to http://bit.ly/2tRViJ9 this issue could be resolved by deploying a precompiled file?

**Comment by kfranqueiro** [comment]
FYI the `main` property of each MDC Web package now points to the `dist` UMD module, so you should no longer need to explicitly transpile MDC Web's ES2015+ code by default (you can still choose to do so by directly importing `@material/foo/index` instead of just `@material/foo`).
