### ISSUE TITLE
Material ripple stays onMouseLeave

### ISSUE THREAD

**Issue by foreggs** [material-components/material-components-web#1233]
** PLEASE READ THIS BEFORE FILING AN ISSUE **
## Bugs
Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?
19.0

### What browser(s) is this bug affecting?
Chrome, possibly other

### What OS are you using?

Windows 10, android 7.1

### What are the steps to reproduce the bug?
Go to [Official MDC Button demo](https://material-components-web.appspot.com/button.html) hold left mouse button to activate ripple and move your mouse outside of the button.

### What is the expected behavior?

Stopping the ripple when the mouse is not over it.

### What is the actual behavior?
The ripple overlay stays there.

### Any other information you believe would be useful?
Here is a demo:
![broken-ripple-mdc3](https://user-images.githubusercontent.com/30264244/30003423-9c631e5e-90b4-11e7-9a7e-45a3211b53e4.gif)

**Comment by tinrab** [comment]
I've reported this in #1124.

**Comment by touficbatache** [comment]
Me too in #809

**Comment by lynnjepsen** [comment]
#1124 is the same bug, so closing this one.
