### ISSUE TITLE
Selection menu has wrong top position when a count of items more than ~20

### ISSUE THREAD

**Issue by apoterenko** [material-components/material-components-web#1235]
## Bug
Selection menu has wrong top position when a count of items more than ~20
See https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/foundation.js#L209

### Version
material-components-web: 0.19.0

### What browser(s) is this bug affecting?

Any browser

### What are the steps to reproduce the bug?

Need to pass to the component more than ~20  items.

### What is the expected behavior?
Selection menu has properly top position

### What is the actual behavior?
Selection menu has wrong top position

### Additional Info

This is my temporary workaround

```
  public componentDidMount(): void {
    super.componentDidMount();
    this.nativeMdcInstance.menu_.show = sequence(this.nativeMdcInstance.menu_.show, () => {
      const adapter = this.defaultFoundation.adapter_;
      const innerHeight = adapter.getWindowInnerHeight();
      const {top} = adapter.computeBoundingRect();
      const menuHeight = adapter.getMenuElOffsetHeight();
      const delta = top + menuHeight - innerHeight;
      const newTop = delta > 0 ? top - delta : top;
      adapter.setMenuElStyle('top', `${newTop}px`);
    }, this.nativeMdcInstance.menu_);
  }
```

**Comment by lynnjepsen** [comment]
Can you give us a codepen to reproduce this? We think it probably has nothing to do with react and is a valid bug, but it will be easier to fix if we can reproduce it exactly.

**Comment by apoterenko** [comment]
Pls see the source code and the screens. It should be clear enough :)

```
import { MDCSelect, MDCSelectFoundation } from '@material/select';
import * as React from 'react';

import { uuid } from 'core/util';
import { Field } from 'core/component/field';
import { AnyT, ChangeEventT } from 'core/definition.interface';
import { ISelectOption } from 'core/component/field/select';

export class Select2 extends Field<Select2, AnyT, AnyT, AnyT, AnyT> {

  constructor(props: AnyT) {
    super(props, MDCSelect);
  }

  public render() {
    const props = this.props;
    const optionsValues: ISelectOption[] = (String(Date.now()) + Date.now())
        .split('')
        .map(num => ({ label: `Test${num}`, value: uuid() }));

    const optionsTpl = optionsValues.map(option => (
        <li className='mdc-list-item'
            role='option'
            key={uuid()}
            value={option.value}
            aria-disabled={option.disabled === true}>
          {option.label ? this.t(option.label) : option.value}
        </li>
    ));

    return (
        <div ref='self'
             className='mdc-select'
             role='listbox'
        >
          <span className='mdc-select__selected-text'>...</span>
          <div ref='menu'
               style={ {maxHeight: 200} }
               className='mdc-simple-menu mdc-select__menu app-select-menu'>
            <ul className='mdc-list mdc-simple-menu__items'>
              {optionsTpl}
            </ul>
          </div>
        </div>
    );
  }

  protected getEmptyValue(): AnyT {
    return -1;
  }

  protected getRawValueFromEvent(event: ChangeEventT): AnyT {
    return this.nativeMdcInstance.selectedOptions[0].getAttribute('value');
  }
}

```

![step0](https://user-images.githubusercontent.com/12325691/30168494-3fdd80fc-93f2-11e7-94cd-cf30f1915b51.png)

![step1](https://user-images.githubusercontent.com/12325691/30168498-451cbba0-93f2-11e7-9793-50564a21f553.png)

![step2](https://user-images.githubusercontent.com/12325691/30168503-482aa578-93f2-11e7-92ff-6fa75ae814e6.png)

![step3](https://user-images.githubusercontent.com/12325691/30168511-4a894b6c-93f2-11e7-80f7-02bb2d483e2c.png)

**Comment by lynnjepsen** [comment]
If you remove max-height do you still have this problem? 

We think setting max-height causes the controller to incorrectly calculate where to position the menu.

**Comment by apoterenko** [comment]
Yes, the issue is gone, but this looks terrible because a height is equal 100%

```
    return (
        <div ref='self'
             className='mdc-select'
             role='listbox'
        >
          <span className='mdc-select__selected-text'>...</span>
          <div ref='menu'
               className='mdc-simple-menu mdc-select__menu app-select-menu'>
            <ul className='mdc-list mdc-simple-menu__items'>
              {optionsTpl}
            </ul>
          </div>
        </div>
    );
```

![no_height](https://user-images.githubusercontent.com/12325691/30214009-986416fc-94b3-11e7-876d-10ae2a8c8434.png)

**Comment by lynnjepsen** [comment]
Its not very clear from our existing https://material.io/guidelines/components/menus.html if we should handle limiting the menu height when the menu is bigger than the entire screen.

I've started talking to our designers more about this case, and I will update here with more information.

**Comment by lynnjepsen** [comment]
I filed a separate tracking bug to improve the logic that calculates the MDC Menu height. (#1279)

We need time to prototype multiple options for the design team to review, and we need time for the design team to investigate all the situations where a Menu is used.  I've placed the issue on our backlog, but we won't be able to investigate this for a couple months.

**Comment by apoterenko** [comment]
Thank you for your time!
