### ISSUE TITLE
How  to Create a Categorized Sub-Menu using select_menu or any other components?

### ISSUE THREAD

**Issue by nulldeba** [material-components/material-components-web#1246]
** Sub-menu feature **

## Feature Requests( New Components)

>Menu items with the children items.
>Menu with check List sub-menu.

**Comment by lynnjepsen** [comment]
Are you referring the "Cascading menu" shown here? 

https://material.io/guidelines/components/menus.html

We have an issue for this: https://github.com/material-components/material-components-web/issues/53, but it will be several months before our core team can make this

**Comment by MarkSFrancis** [comment]
@nulldeba While we're waiting for the official one, I've made my own version, you can check out that gist here:
https://gist.github.com/MarkSFrancis/20893f6a9c0f89f512e02dc312a25e10

It's not perfect, but it might help get you started

**Comment by amsheehan** [comment]
Checkbox items in a select menu (nested or otherwise) would require a change to MDC List and MDC Menu. Currently I don't believe we have plans to build in that support.
