### ISSUE TITLE
mdc-select__menu - overflow-y is set to scroll rather than auto

### ISSUE THREAD

**Issue by RobJacobs** [material-components/material-components-web#1247]
The mdc-select__menu style has an overflow-y set to scroll causing the scroll bar to appear in the select dropdown whether it's necessary or not: [link](https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/mdc-select.scss#L92).  Could this be changed to auto instead?

### What MDC-Web Version are you using?

0.20.0

### What browser(s) is this bug affecting?

All browsers are affected

### What OS are you using?

Win 10

### What are the steps to reproduce the bug?

A mdc-select with 2 options.

### What is the expected behavior?

The vertical scrollbar should only appear when necessary.

### What is the actual behavior?

The vertical scrollbar always appears.

**Comment by lynnjepsen** [comment]
Changing `overflow-y` to auto sounds reasonable. Would you like to submit a PR?

**Comment by RobJacobs** [comment]
@lynnjepsen Yes I would.

**Comment by trimox** [comment]
I'm pretty sure a scrollbar will now be shown during menu's `open transition scaling`, and disappear if the list is not large. Not sure if that was intended or not?

**Comment by RobJacobs** [comment]
@trimox @lynnjepsen You are correct.  Now that you mention it, I remembered that's why I originally went with setting the max-height to vh units (see discussion in related PR).  Let me know if you would like me to create another PR to correct this...

**Comment by deap82** [comment]
@trimox  is right, this can even be seen in the demo: http://material-components-web.appspot.com/simple-menu.html
ping @RobJacobs
