### ISSUE TITLE
dialog: enable modals

### ISSUE THREAD

**Issue by mikegleasonjr** [material-components/material-components-web#1259]
After reading the [Material guidelines on dialog](https://material.io/guidelines/components/dialogs.html#), they talk briefly about modals:

> _**Dismissing dialogs**_
> _Dialogs may be dismissed either by tapping outside of the dialog, or tapping the system back button (on Android). Alternatively, the user’s ability to dismiss a dialog may be disabled, so that one of the actions must be chosen before proceeding._

Is this in the roadmap?

Right now I know I can re-implement the whole adapter (read: copy/paste its current implementation and change it a bit), but maybe it would be great if the current foundation could support it.

**Comment by Garbee** [comment]
How is what is currently provided not able to allow for what is specified?

The backdrop click to dismiss was removed iirc since the way it was implemented didn't align with web events since the bubbling needed to be caught and dismissed which was problematic.

**Comment by mikegleasonjr** [comment]
>How is what is currently provided not able to allow for what is specified?

Well this is doable, just wondering if it can be easier. If anyone is interested, I did it like this:

1. you have to listen (capture mode) to the `keydown` event on the `document`, check if the key is `Escape`, and stop propagation.
2. you have to listen (capture mode) to the `click` event on the root node, check if the is the backdrop, stop the propagation.
3. (Bonus) If you want to execute an async action when a button is clicked before dismissing the dialog, you cannot use MDC events (`MDCDialog:accept`, `MDCDialog:cancel`). You have to listen on the buttons yourself and call stop propagation. Then call close and the end of whatever you did async.

> The backdrop click to dismiss was removed iirc since the way it was implemented didn't align with web events since the bubbling needed to be caught and dismissed which was problematic.

It is still there.

**Comment by lynnjepsen** [comment]
https://material.io/guidelines/components/dialogs.html#dialogs-behavior

> the user’s ability to dismiss a dialog may be disabled, so that one of the actions must be chosen before proceeding

It sounds like we need to add a feature to MDC Dialog to support disabling dismissing the dialog.

I'm going to filed a separate issue (#1275) just to keep things clear
