### ISSUE TITLE
sourcemap of demo-styles.css.js

### ISSUE THREAD

**Issue by DanielRuf** [material-components/material-components-web#1272]
Is it intended that there is still the sourcemap with `/Users/lynnjepsen/workspace/` @lynnjepsen?

**Comment by lynnjepsen** [comment]
It's not great.

We will try and scrub this.

**Comment by kfranqueiro** [comment]
This is obsolete since we made a new [catalog](https://material-components.github.io/material-components-web-catalog/#/) with a separate repo and build process.
