### ISSUE TITLE
MDC Dialog should support disabling dismissing the dialog

### ISSUE THREAD

**Issue by lynnmercier** [material-components/material-components-web#1275]
https://material.io/guidelines/components/dialogs.html#dialogs-behavior

> the user’s ability to dismiss a dialog may be disabled, so that one of the actions must be chosen before proceeding

See #1259 for background

**Comment by ray007** [comment]
Why not just use the html dialog element?

**Comment by Garbee** [comment]
@ray007 The dialog element wasn't used to avoid needing a polyfill for unsupported browsers. The polyfill ended up causing developers quite a bit of confusion when they didn't require it and the element didn't function. So by providing everything internally the docs are more straightforward for developers and everything is cohesive.

**Comment by ray007** [comment]
The answer to confusion is documentation.
Browser support for the dialog seems to be improving and it seems quite unfortunate to not use such a useful feature. And even with polyfill it's working a lot better than all other dialog solutions I've come across so far.

**Comment by Garbee** [comment]
> The answer to confusion is documentation.

Yah, we had it very clear in MDL that the dialog required developers include the polyfill on unsupported browsers. Everyone overlooked it and just included the CSS and JS from our CDN copy and expected it to just work fully.

You can only do so much in documentation. You can't help people that decide to ignore reading it in order to jump in to the API side and just use it. Then get confused when it doesn't work and complain. Best solution, no polyfill and just DIY until the element is widely supported in production browsers.

**Comment by ray007** [comment]
Why not include the polyfill in the material-components package?

**Comment by Garbee** [comment]
Because then you're forcing the download for all browsers and not just those that need it. Which isn't optimal.

**Comment by ray007** [comment]
Is the polyfill so much bigger than whatever mechanism you have now to manage dialogs?
If it is, maybe that's why it works so well?
Though I guess most people don't need stackable dialogs...

**Comment by peterculak** [comment]
I ended up extending all MDCDialog + foundation + adapter and to disable dismissing the dialog by clicking on scrim or pressing escape key or prevent it from closing while it's submitting etc ... but it would be nice if this was all included in default MDCDialog behavior so we don't need to keep extending it and adding our own behavior so often

**Comment by kfranqueiro** [comment]
This issue specifically covers dismissing the dialog via clicking the scrim or pressing escape, both of which are [possible to disable](https://github.com/material-components/material-components-web/tree/v0.43.1/packages/mdc-dialog#mdcdialog-properties-and-methods) in the new version of Dialog published as of 0.40.0.
