### ISSUE TITLE
Multi-line textfield label on IE 

### ISSUE THREAD

**Issue by KayvandenHeuvel** [material-components/material-components-web#1282]
**What MDC-Web Version are you using?**

0.20.0

**What browser(s) is this bug affecting?**

Internet Explorer 11.540.15063.0

**What OS are you using?**

Windows 10

**What are the steps to reproduce the bug?**

1. Open a project in Internet Explorer with a multi-line textfield.
2. Focus on the textfield.

Check this demo in Internet Explorer:
https://material-components-web.appspot.com/textfield.html

**What is the expected behavior?**

The label should be floating above the textfield, just like in other browsers.

**What is the actual behavior?**

The label goes to the top of the page instead of floating above the textfield.

**Comment by lynnjepsen** [comment]
Looks like a bug! Thanks for reporting it.

**Comment by moog16** [comment]
@KayvandenHeuvel, I couldn't reproduce the issue on IE 11.15.xx. I tried a single line text field and a multiline textarea and both seem to work as expected. I am using `v0.26.0`. Can you confirm? I've attached a screenshot.
<img width="775" alt="screen shot 2017-12-19 at 08 37 50" src="https://user-images.githubusercontent.com/579873/34173050-3f938ec4-e498-11e7-9695-47a3f9036c4e.png">

**Comment by KayvandenHeuvel** [comment]
@moog16 I guess that this problem is solved with the later versions of MDC because I also can't reproduce the problem. We are also using v0.26.0 and it looks good to me.
