### ISSUE TITLE
Toggle RTL buttons on the navbar demo doesn't match

### ISSUE THREAD

**Issue by Extarys** [material-components/material-components-web#1283]
On https://material-components-web.appspot.com/toolbar/index.html
The Toggle RTL buttons doesn't match the demo below it for the third and forth one.

**Comment by kfranqueiro** [comment]
Thanks for reporting this. We noticed this as well and it's already been fixed in the repo in #1268, so it'll be fixed on the demo site the next time we cut a release.

**Comment by Extarys** [comment]
Darn. I searched for it! RIP.

Thanks and sorry
