### ISSUE TITLE
Tab Bar Scroller: in mobile, clicking the right arrow indicator does not scroll if tab text is too long

### ISSUE THREAD

**Issue by danielraggs** [material-components/material-components-web#1289]
### What MDC-Web Version are you using?

MDC Tabs version `0.2.8`

### What browser(s) is this bug affecting?

Bug occurs in both Firefox `54.0.1 ` and Chrome `60.0.3112.113`.

### What OS are you using?

Mac OS X El Capitan

### What are the steps to reproduce the bug?

1. In mobile (or in a mobile screen width), open a project/page with an MDC Tab Bar Scroller. You can even use the Google MDC demo at http://material-components-web.appspot.com/tabs.html#one
2. Set/save the text for the active tab to be long enough that it goes past the boundary of the div with class `mdc-tab-bar-scroller__scroll-frame`.
3.  Re-size the window slightly so that the indicator adjusts itself (if you are in mobile, this step can be skipped)
4. Try clicking the right arrow indicator to see the next set of tabs

### What is the expected behavior?

The MDC Tab Bar Scroller should scroll to let you see the rest of your active tab and the other tabs.

### What is the actual behavior?

The MDC Tab Bar Scroller is unresponsive and does not scroll.

**Comment by lynnjepsen** [comment]
We need to check with our designers if we should be truncating text in tabs. Its probably reasonable for us to truncate very long tabs so that you can always see a little bit of the next tab.

But there also might be a bug in our layout logic for tabs. 

We'll explore both options and update this thread with any new info.

**Comment by kfranqueiro** [comment]
This is obsolete with the new implementation of MDC Tab Bar and its child components, which now make use of native scrolling.

RE one of Lynn's comments, the [design article](https://material.io/design/components/tabs.html#anatomy) indicates that tab text should not be truncated or resized.
