### ISSUE TITLE
Vertical alignment issues in nav bar icons

### ISSUE THREAD

**Issue by Extarys** [material-components/material-components-web#1296]
Basic code: https://gist.github.com/Extarys/cba6618f4c76de8733d3ab222de51ec0
Result:
![alignmentmaterial](https://user-images.githubusercontent.com/11581433/30356753-cb6f0946-9808-11e7-9b3b-a376eb93493d.png)

I also notice the same issue in the demo website where the right github icon isnt aligned properly and the drawer icon on the left have the same issue.

They appear a little bit too high, not centered.

EDIT: I copied the wrong issue, damn.

**Comment by lynnjepsen** [comment]
Our http://material-components-web.appspot.com/toolbar/index.html doesn't have any alignment issues I can see.

![q1frzbw1lsj](https://user-images.githubusercontent.com/4703432/30446758-ecaf8950-993e-11e7-9c12-dab005c6fd51.png)

What demo website are you referring to?

**Comment by Extarys** [comment]
Both **Firefox 55.0.2 x64** and **Firefox Nightly 57.0a1 x64** on **Linux Mint 18.2** (Fully up to date) have this issue on my machine. :/ (Sorry I forgot to tell browser/OS)

**Comment by trimox** [comment]
Duplicated in SauceLabs w/Firefox 55.0.2 (windows)

![image](https://user-images.githubusercontent.com/11887843/30484217-bacd4ae4-99f7-11e7-8b1b-54d9d733d5b4.png)

**Comment by kfranqueiro** [comment]
I noticed this in the toolbar demo's top toolbar yesterday, and @yeelan0319 pointed out that the toolbar takes a different height at different break points. I think the problem might exist specifically when the toolbar is not 56px tall.

**Comment by Extarys** [comment]
@kfranqueiro Maybe. I copied the exact code provided in the docs though.

**Comment by joshas** [comment]
Can confirm issue on Firefox 56.
Problem is that .mdc-toolbar__section has height: 100%, which has no effect on Chrome. On Firefox  .mdc-toolbar__section is stretched to 64px (desktop) and because icons are aligned to flex-start - they are off center.

**Comment by megabild** [comment]
Can confirm issue on Microsoft Edge 41.16299.15.0 (Fall Creators Update).
Sorry guys, I feel really dirty reporting this.
