### ISSUE TITLE
Wrap checkbox within a label to avoid dynamic id generation?

### ISSUE THREAD

**Issue by rodrigocfd** [material-components/material-components-web#1299]
The [textfield](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield) component [has an example](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#single-line---with-javascript) of how to wrap an `input` within a `label` to avoid dynamic `id` generation. There's no such example for the [checkbox](https://github.com/material-components/material-components-web/tree/master/packages/mdc-checkbox)... is it possible?

**Comment by lynnjepsen** [comment]
I don't think we can cram everything in MDC Checkbox into a `label`:

https://github.com/material-components/material-components-web/tree/master/packages/mdc-checkbox
