### ISSUE TITLE
Migration Guide from MDL to MDC

### ISSUE THREAD

**Issue by SabineMa** [material-components/material-components-web#130]
This is not a Feature Request and not a bug but the question: will you provide a migration guide for people using MDL and want to migrate to MDC?

**Comment by sgomes** [comment]
Thanks for the suggestion, @SabineMa! There's a big difference between the two, but it could prove useful as a complement to our Getting Started guide. @traviskaufman What do you think?

**Comment by igilham** [comment]
This would definitely be useful to anyone who uses MDL and wants to migrate.

**Comment by sgomes** [comment]
We've discussed this question a bit andthink there's a few things that could be useful in a migration guide. Let me try to summarize them:

- List of components in MDC-Web and MDL, and how they map to each other.
- Discussion of the different ways of depending on / using MDL, and the high-level changes you have to make to move from MDL to MDC-Web with each one. Plus discuss the new options only available in MDC-Web.
- Discussion of whether or not to use `mdc-auto-init` (auto initialization was mandatory in MDL, but not in MDC-Web).

All of this peppered with plenty of links into the existing MDC-Web documentation, for finding out more. How does this sound, @SabineMa @traviskaufman @amsheehan?

**Comment by ohdoukyoung** [comment]
I wonder if the scope of the browser support is also included in the migration guide.
Are there any plans to support IE9-10 like MDL?

**Comment by sgomes** [comment]
@ohdoukyoung No plans for IE9-10 in MDC-Web, sorry; it's missing too much, like flexbox and calc. We'll add that info to the guide.

**Comment by SabineMa** [comment]
Only for the sake of completeness 

- List of NEW components in MDC-Web

**Comment by sgomes** [comment]
@SabineMa Yes, sounds good!

@igilham Yep, good idea. It might also be useful have the indication of whether those missing components are planned for later, and which milestone (beta or stable) they're planned for.

**Comment by koutsenko** [comment]
Hello, will you implement DataTable component?
I've used it in react-mdl (MDL v.1 hasn't framework bindings, so additional react-mdl layer was necessary). But I don't see DataTable in the beta milestone of MDC-Web.

p.s. If you'll create a such task, please add the feature: data scrolling with fixed (visible)  header also.
Thanks a lot.

**Comment by sgomes** [comment]
This is now [merged](/material-components/material-components-web/blob/master/docs/migrating-from-mdl.md).
