### ISSUE TITLE
.mdc-theme--dark CSS compiled incorrectly? Put in-front of surrounding CSS definition

### ISSUE THREAD

**Issue by actra-gschuster** [material-components/material-components-web#1321]
I'm not sure if this is a bug with MDC, my SASS compiler (node-sass 4.5.3 with postcss 6.0.11, managed by webpack 3.5.6) or my browser.

### What MDC-Web Version are you using?

> 0.20.0

### What browser(s) is this bug affecting?

> Chrome 60.0.3112.113

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

Import mdc-web SCSS inside a CSS class of my projects SCSS file:
```
div.my-class {
    @import '~material-components-web/material-components-web';
}
```

### What is the actual behavior?

> .mdc-theme-dark is put in front of div.my-class in the generated CSS, thus requiring to set the class on an parent element of div.my-class in order to "fire".
```
div.my-class .mdc-textfield__input--theme-dark,
.mdc-theme--dark div.my-class .mdc-textfield__input {
  color: #fff;
  color: var(--mdc-theme-text-primary-on-dark, #fff);
}
```
> I'm using a "theme component" in angular 5 that should be able to switch between light and dark theme so it can only access the components root element or child elements but no parent.

### What is the expected behavior?

> .mdc-theme-dark should be put after div.my-class in generated CSS
```
div.my-class .mdc-textfield__input--theme-dark,
div.my-class .mdc-theme--dark .mdc-textfield__input {
  color: #fff;
  color: var(--mdc-theme-text-primary-on-dark, #fff);
}
```

**Comment by Garbee** [comment]
This is working as expected originally.

The decedent setup allows a developer to put `.mdc-theme--dark` on  something like the `body` node to style everything dark-by-default. That was the original design point with it. The "expected behavior" here would end up requiring another intermediary node between the container and input for the example to get dark mode styling. Which is unneeded nesting.

**Comment by actra-gschuster** [comment]
Thanks for your quick reply.
That's an acceptable answer, so I'll add a directive used outside of div.my-class.
