### ISSUE TITLE
(Feature Request) Drawer on the right side

### ISSUE THREAD

**Issue by actra-gschuster** [material-components/material-components-web#1324]
## Feature Requests

As per the guidelines, drawers may be positioned on the right side:
https://material.io/guidelines/layout/structure.html#structure-system-bars
> If present, side nav bars can be pinned for permanent display or float temporarily as overlays. Side navs can be positioned on the left or right side of the screen.
> The content appearing in the left nav is ideally navigation- or identity-based. Right nav content should be secondary to the main content on a page.

**Comment by aaronhudon** [comment]
If I'm following you correctly, this can be done through the RTL feature of the drawer.

```
    <aside class="mdc-temporary-drawer" dir="rtl">
        <nav class="mdc-temporary-drawer__drawer" dir="ltr">
            <header class="mdc-temporary-drawer__header">
                <div class="mdc-temporary-drawer__header-content">
                </div>
            </header>
            <nav class="mdc-temporary-drawer__content">                
            </nav>
        </nav>
    </aside>
```

**Comment by actra-gschuster** [comment]
I tried it and it doesn't work as expected (see screenshots), the closed drawer is visible (overlaying the content) and the open drawer is missing the border on the left (it's still on the right).

Code used with angular flex-layout:
```
<div fxflex="" fxlayout="row" id="content-container" ng-reflect-layout="row" ng-reflect-flex="" style="flex: 1 1 1e-09px; box-sizing: border-box; display: flex; flex-direction: row;">
    <am-persistent-drawer class="mdc-persistent-drawer--animating mdc-persistent-drawer--open mdc-persistent-drawer">
        <am-persistent-drawer-navigation class="mdc-persistent-drawer__drawer" role="navigation">
            <am-persistent-drawer-content style="width: 500px;" class="mdc-persistent-drawer__content">
                Links
            </am-persistent-drawer-content>
        </am-persistent-drawer-navigation>
    </am-persistent-drawer>
    <div fxflex="" style="padding: 10px; flex: 1 1 1e-09px; box-sizing: border-box;" ng-reflect-flex="">
        Toolbar and page content go inside here.
    </div>
    <am-persistent-drawer class="mdc-persistent-drawer--animating mdc-persistent-drawer--open mdc-persistent-drawer" ng-reflect-align="right" dir="rtl" direction="rtl">
        <am-persistent-drawer-navigation class="mdc-persistent-drawer__drawer" role="navigation" dir="ltr" direction="ltr">
            <am-persistent-drawer-content class="mdc-persistent-drawer__content">
                Rechts
            </am-persistent-drawer-content>        
        </am-persistent-drawer-navigation>
    </am-persistent-drawer>
</div>
```


![drawers-closed](https://user-images.githubusercontent.com/23024678/30578550-de936dc6-9d14-11e7-9233-30e1beaca992.png)
![drawers-open](https://user-images.githubusercontent.com/23024678/30578552-e91564c0-9d14-11e7-946d-ab5ab45d4a50.png)

**Comment by amsheehan** [comment]
We will reach out to design on guidance for this. In the past when this has come up we had no plans to make it possible. Lets see if that has changed since then. Thanks!

**Comment by actra-gschuster** [comment]
Thanks for your reply.
If it helps: @angular/material already supports drawers on the right side.

**Comment by aaronhudon** [comment]
@actra-gschuster 
Does this help: https://codepen.io/aaronhudon/pen/JrXNrb  ?

**Comment by actra-gschuster** [comment]
I don't see differences to the code I used so why does it work in your plunkr?
Well, to be honest, I switched back to `@angular/material` for the time being, waiting for the issue to be resolved in either way.

**Comment by amsheehan** [comment]
Hey, quick update; still having a conversation with our designers, but wanted to touch base on this.

1: RTL probably isn't the right tool for this job since it will mirror the order of all of your inline elements, e.g.: if you have a layout of nav links and icons inline, in your RTL drawer, the order of them will go from [icon] Label ==> Label [icon]

2: I had a few questions to clarify the guidance on left _or_ right drawers and am still waiting to hear back.

**Comment by ErraticFox** [comment]
Any update? I'd really like this feature as well. Example of usage, having a server list on one side and a users list on the other side, unless you guys have an idea of how to show both of those whenever like so. 👍

**Comment by aaronhudon** [comment]
@erraticfox see my post above on how to make it work.

**Comment by amsheehan** [comment]
Hey, still working on getting an answer to this. Thanks for everyone's patience. In the mean time, it does seem like @aaronhudon has a workaround.

**Comment by aaronhudon** [comment]
@amsheehan the workaround example isn't totally fleshed out e.g. for mdc-list-item, you need to "undo" the [dir=rtl] rule(s):
e.g. see below.  It seems the [dir=rtl] .mdc-list-item is too restrictive a selector.

```
[dir=rtl] .mdc-list-item {
    margin-left: 32px;
    margin-right: 0;
}
```

**Comment by aaronhudon** [comment]
Update for those interested, where you don't need to hack with dir="rtl":

Create a new modifier for the .mdc-temporary-drawer called --right, and apply the same type of transformations used for RTL in the library:

```
<aside class="mdc-temporary-drawer mdc-temporary-drawer--right">
...
</aside>

    .mdc-temporary-drawer.mdc-temporary-drawer--right .mdc-temporary-drawer__drawer {
        -webkit-transform: translateX(107%);
        transform: translateX(107%);
        -webkit-transform: translateX(calc(100% + 20px));
        transform: translateX(calc(100% + 20px));
        left: auto;
        right: 0;
    }
    .mdc-temporary-drawer--open.mdc-temporary-drawer--right .mdc-temporary-drawer__drawer {
        -webkit-transform: none;
        transform: none;
    }   
```

**Comment by ErraticFox** [comment]
@aaronhudon actually helps me a lot! I'd suggest this little change though: 
```css
.mdc-persistent-drawer--open.mdc-persistent-drawer--right .mdc-persistent-drawer__drawer {
  -webkit-transform: none;
  transform: none;
  border-right: 0px;
  border-left: 1px solid #e4e4e4;
}
```

**Comment by bonniezhou** [comment]
We've checked with our designers and this behavior isn't intended to be supported for navigation drawer specifically, but there are plans for more flexible components to accomplish this in the future.

**Comment by seb-ster** [comment]
Hi guys,
I know this is closed, but just incase someone stumbles upon this issue, like i did.
Like @aaronhudon said, with an "RTL" on the enclosing `aside`, you can easily switch the drawer to the right.

`<aside class="mdc-temporary-drawer" dir="rtl">`

Then use an "LTR" on the child `nav` element, to switch the content back to 'LTR'

`        <nav class="mdc-temporary-drawer__drawer" dir="ltr">`

I encountered the problem that the margins on the list icons were still set to 'RTL' styles
```
[dir="rtl"] .mdc-list-item .mdc-list-item__start-detail, .mdc-list-item[dir="rtl"] .mdc-list-item__start-detail {
    margin-left: 32px;
    margin-right: 0;
}
```

So i created a new rule that forces the margins back to 'LTR' style, if an 'LTR' setting is present in a parent.
```
[dir="ltr"] .material-icons.mdc-list-item__start-detail {
  margin-left: 0 !important;
  margin-right: 32px !important;
}
```

Add this rule to [https://material-components-web.appspot.com/drawer/temporary-drawer.html](https://material-components-web.appspot.com/drawer/temporary-drawer.html) and modify the `aside` and `nav` elements like above, to test this out.

**Comment by dranes** [comment]
For anyone interested in solving this using only dir attributes,  use an RTL in the first nav tag and then use LTR in the header to reset content's direction. 

``` 
<aside class="mdc-drawer mdc-drawer--temporary mdc-typography">
  <nav class="mdc-drawer__drawer" dir="rtl">
    <header class="mdc-drawer__header" dir="ltr">
```

https://codepen.io/dranes/pen/GxJVbp

**Comment by yousufftekhne** [comment]
Just add Below css it will work fine
.mdc-drawer--modal, .mdc-drawer--modal{
      left: initial;
      right: 0;
    }
    .mdc-drawer--animate, .mdc-drawer--animate{
      -webkit-transform: translateX(100%);
      transform: translateX(100%);
    }
    .mdc-drawer--opening, .mdc-drawer--opening{
      -webkit-transform: translateX(0);
          transform: translateX(0);
    }
    .mdc-drawer--closing, .mdc-drawer--closing{
      -webkit-transform: translateX(100%);
          transform: translateX(100%);
    }
