### ISSUE TITLE
Dragging the mouse causes ripple elements to retain highlighting

### ISSUE THREAD

**Issue by Spetnik** [material-components/material-components-web#1328]
### What MDC-Web Version are you using?

> 0.21.0

### What browser(s) is this bug affecting?

> Chrome Version 61.0.3163.91 (Official Build) (64-bit)
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

### What OS are you using?

> Windows 10 Version 1703 (OS Build 15063.608)

### What are the steps to reproduce the bug?

Use the "Dynamic view switching" demo at https://material.io/components/web/catalog/tabs/. Examples of this issue can be seen at https://codepen.io/AJSpetner/pen/RLrEmg, as well as http://material-components-web.appspot.com/tabs.html. Other elements with ripple are also affected. Try on https://material-components-web.appspot.com/button.html as well.

> 1. Mouse down on an element that will ripple
> 2. Move the mouse away from the element
> 3. Mouse up.

### What is the expected behavior?

> The element clicked in step 1 should no longer be highlighted.

### What is the actual behavior?

> The element retains the "mdc-ripple-upgraded--background-active-fill mdc-ripple-upgraded--foreground-activation" classes and remains highlighted.

**Comment by amsheehan** [comment]
This does appear to be a bug. Thanks for filing.

**Comment by Spetnik** [comment]
Perhaps this is related / same issue: I'm noticing that if I mouse-down on a tab or another element with a ripple (e.g. the buttons at https://material-components-web.appspot.com/button.html), move the mouse off the element, and then mouse-up - ALL before the animation completes, the element remains highlighted.

**Comment by Spetnik** [comment]
I have confirmed that my previous comment is the actual bug and that the original report of "clicking elsewhere before the animation completes" does not trigger the bug (but often one will inadvertently drag the mouse while trying to click quickly). I will edit the issue accordingly.

**Comment by Spetnik** [comment]
My guess is that the issue here is that the ripple code is listening for a mouseup on the element itself, which does not fire if the mouse is moved off of the element before the button is depressed. A solution could be to move the mouseup listener to the document or window. I'd be happy to try to fix this, but I'm unfamiliar with the code, so a pointer in the right direction of where to look would be helpful.

**Comment by Spetnik** [comment]
I discovered that the issue also occurs when the ripple is triggered via the keyboard (i.e. a 'keydown' event on a <button> element) and then the element loses focus before the 'keyup' event. The latest commit to #1461 fixes that as well.

**Comment by Spetnik** [comment]
Just noticed that this seems to be a duplicate of #1124.
