### ISSUE TITLE
(Feature Request) Make autoInit return the initialized components

### ISSUE THREAD

**Issue by blikblum** [material-components/material-components-web#1329]
## Feature Request

Return the components initialized by a call to `autoInit`

**Motivation**

Currently, when integrating mdc with a framework or with custom elements is necessary to individually create the components, store its references and destroy when appropriate. With `autoInit` is possible to accomplish the first step with one call (create the components) but will not provide the means to destroy the component instances

**Use case**

By `autoInit` returning the initialized components we could write components like the below which will initialize (and) finalize all mdc components with auto-init attribute

```

class MDAutoComponent extends HTMLElement {
  connectedCallback() {
    this.mdcComponents = mdc.autoInit(this)
  }
  disconnectedCallback() {
    this.mdcComponents.forEach((comp) => comp.destroy())
  }
}
```

**Comment by amsheehan** [comment]
Seems reasonable. Is this something you would like to change and make a pull request for?

**Comment by blikblum** [comment]
> Is this something you would like to change and make a pull request for?

Done
