### ISSUE TITLE
Dead link in main README.md file

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#1330]
The `README.md` in the root of the repository targets `https://github.com/material-components/material-components-web/blob/master/docs/developer.md` for the Developing MDC-Web Components link.

This is a dead link.

**Comment by amrtgaber** [comment]
Also found this dead link in `CONTRIBUTING.md` (line 23), `.github/ISSUE_TEMPLATE.md` (line 18), `docs/authoring_components.md` (line 67) and in `packages/mdc-base/README.md` (line 55). Would love to put in a pr to correct it but what's it supposed to be corrected to?

**Comment by LeaSak** [comment]
Hi @amsheehan and @amrtgaber. Yes, I found something similar. I'm not sure if this is the right place to mention this but the link on the external website `https://material.io/components/web/docs/` to the developer documentation is also dead. It should also lead to this `https://github.com/material-components/material-components-web/tree/master/docs/developer.md`.

**Comment by el1f** [comment]
This seems fixed now
