### ISSUE TITLE
Autocomplete Component Implementation (started building, all documentation complete) 

### ISSUE THREAD

**Issue by vandie** [material-components/material-components-web#1334]
I needed an autocomplete for my own project so have started to build one following the Material design spec ( found  [here](https://material.io/guidelines/components/text-fields.html#text-fields-layout) ) and following the guidlines set out by this repository. I filled in all needed documentation which can be found below but still need to write tests and finish the scss.

[Component Egineering Outline](https://docs.google.com/document/d/19ZCzqEHSoqN7k47l6PwUXT7zH82gUbCSRFPOJo7DxBw/edit?usp=sharing)

Image of a test
![Test gif](https://github.com/vandie/mdc-autoComplete/raw/master/images/autocomplete.gif)

[Example in codepen](https://codepen.io/vandie/pen/jGbgvQ)

[The repository](https://github.com/vandie/mdc-autoComplete)

**Comment by vandie** [comment]
the only thing that needs doing now is automated tests then I can make a pull request for full inspection.

**Comment by Garbee** [comment]
The functionality looks great for a starting point. Left a few comments on the doc for things to look out for and that will need renaming to keep things properly scoped and not cause errors for users (yes, HTML validation does matter to some.)

**Comment by vandie** [comment]
@Garbee I've made changes to both the code base and the outline. I'm unsure on the final point however. I've given more detail on my replies on the document.

**Comment by vandie** [comment]
Ok. I followed your advice for the final point. (code is updated as well)

**Comment by ciampo** [comment]
is there any plan for this autocomplete component to be added to the standard set of Material Components for the Web?

**Comment by vandie** [comment]
I don't think it will be based on the fact that they were changing the way textboxes worked while I was working on this. Of course, I'd love to be able to say it would 😄

**Comment by dandv** [comment]
This should be linked from #45.

**Comment by vandie** [comment]
@dandv while I appreciate that this has probably helped a fair few people. I haven't actually been able to keep this up to date with the latest structure or the code and have recently been made aware that this is no longer compatible. (That being said, I haven't had a chance to test for myself)

As a result, unless someone else wishes to help, I don't think this will be much use to anyone...

**Comment by asyncLiz** [comment]
Closing in favor of #45 to track autocomplete
