### ISSUE TITLE
Automatically inserted style attribute deforms 'mdc-select', and doesn't allow reading 'mdc-select__selected-text' -> mdc-select default "label" text (see attached example in CodePen).

### ISSUE THREAD

**Issue by aroms** [material-components/material-components-web#1335]
## Bug

Automatically inserted ```style``` attribute deforms ```mdc-select```, and doesn't allow reading ```mdc-select__selected-text``` (mdc-select default label text).
### What MDC-Web Version are you using?

> 0.21.0

### What browser(s) is this bug affecting?

> * Chrome Version 61.0.3163.91 (Official Build) (64-bit)
> * Firefox 55.0.3 (64-bit)

### What OS are you using?

> * Ubuntu Desktop 17.04
> * MacOS High Sierra 10.13

### What are the steps to reproduce the bug?

1. Copy and paste the mdc-select sample with javascript from the demo page.
2. Put a label (How old are you) longer than the available options (1, 2, 3).
3. Impossible to read the label 'How old are you?' since the size of mdc-select fits the size of the options, and the option is less long.

> NOTE: I have a template example of the bug: [bug template on CodePen](https://codepen.io/aroms/pen/RLadgq?editors=1000#0).

### What is the expected behavior?

> Do not automatically add any style attribute, since without that attribute it works perfectly.

### What is the actual behavior?

> Currently, the problem is that a style attribute with an incorrectly calculated width is added to the ```div``` that has the ```js-select``` ```id``` (see attached example in CodePen), if that style attribute is not added, the label size works perfectly

### Any other information you believe would be useful?
> Template example of the bug: [bug template on CodePen](https://codepen.io/aroms/pen/RLadgq?editors=1000#0).

**Comment by amsheehan** [comment]
We see that this can be reproduced. However, we recommend solving this on an implementation level. You can add a class to `mdc-select` and give it any width you'd like. We are hesitant to do it in MDC Select as there is no one solution to satisfy every implementation scenarios.

**Comment by kmmbvnr** [comment]
@amsheehan Could you consider reopen this?

The problem can't be solved by adding a class in addition to `mdc-select`, and even with inline `style="width:1000px"` attribute on the element.

Current select implementation overrides element width attribute. So in the codpen after mdc-select initialization we have `<div id="js-select" class="mdc-select" style="width: 9px;" role="listbox" tabindex="0">`

That 9px can be overridden by CSS on a user level
