### ISSUE TITLE
Public method to refresh tabs?

### ISSUE THREAD

**Issue by gpoitch** [material-components/material-components-web#1336]
I'm looking for a way to tell the tab bar component to refresh its knowledge of its underlying tabs.

The use case is I have a tab bar which can have items added or removed in different contexts. The tab bar can throw out of bounds exceptions because it isn't aware of the new tabs since they are only gathered at initialization.

**Comment by amsheehan** [comment]
Does `instanceOfTabBar.init()` not work? It should be reinitializing all of the MDC Tabs when called.

**Comment by gpoitch** [comment]
No luck with recalling `initialize()`.  I'll have to work up a minimal example.

**Comment by kfranqueiro** [comment]
Calling `initialize` (and the foundation's `init`) multiple times is probably not the best idea in general, since components' `init` methods tend to perform setup that is expected to occur exactly once, e.g. setting up event handlers.

Based on a brief look at the code, it seems to me what ultimately needs to happen here is `gatherTabs_` in `mdc-tab-bar/index.js` needs to be called again (as it is in `initialize`). I'm wondering if simply repeating that one line from `init` in `layout` would enable `layout` on the component to serve this purpose? Though if calling `initialize` again didn't solve it, then maybe I'm missing part of the issue.

I'm also not sure if there might still be issues e.g. if the active tab is removed, so an example would probably also help, thanks!

**Comment by gpoitch** [comment]
Made a minimal example (I was working with a react wrapper, making it more difficult) and it works pretty well by calling `initialize` +` layout`: https://codepen.io/anon/pen/xXOvbj?editors=1010

There is an exception thrown with active states if you select the 3rd tab, then swap the tabs in the demo.

**Comment by amsheehan** [comment]
Whooooaaaa definitely meant `layout()` My bad.

**Comment by danielraggs** [comment]
@gpoitch So I actually have a very similar need in an app I'm working on, and as @amsheehan suggested, `.layout()` seems to fix the issue.

**Comment by amsheehan** [comment]
@gpoitch does calling `.layout()` fix your issue?

**Comment by gpoitch** [comment]
Partially.  There is still a case where it breaks when there is a different number of new tabs. See my last comment and codepen.  Click the 3rd tab then click 'Change tabs', which replaces it with 2 tabs and thus throws an out of bounds exception.

**Comment by amsheehan** [comment]
Gotcha, can you give me some more context on what the use case is? Our designers initial reaction is that they wouldn't recommend a layout where something like this is necessary. Perhaps if I go back to them with a concrete use case they can advise and we can consider surfacing some method of doing this.

**Comment by gpoitch** [comment]
I was just trying to use the same tab bar component for my whole app and change the tabs in different contexts.  (e.g. a contacts app could have recents/favorites/all for the top level tabs, then change to info/history tabs when selecting a contact)  

I can solve it by instead creating a separate tab bar for each 'page'.  So it was an architectural convenience issue rather than a UX design issue.  Feel free to close.

**Comment by kfranqueiro** [comment]
Thanks for providing more context, and yes, in that case, it sounds like having one instance per "page" is more appropriate.

Given that MDC Tabs aren't designed for dynamic addition/removal, we're closing this issue.

**Comment by grosmar** [comment]
Do you have some update about this?
I think it's really not right to make this component static, as it's really common to have a need of adding/removing tabs.

**Comment by amsheehan** [comment]
@grosmar We don't plan on adding support for this. Let us know your use case though, and we can discuss how you would use MDC Tab Bar to satisfy those needs. If you would like to continue the conversation, please hop over to our [Discord](https://discord.gg/KuPrNhA) server so the thread doesn't get lost, as this issue has been closed.
