### ISSUE TITLE
Awkward normal-vs.-dense styling of textfields

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1352]
### What MDC-Web Version are you using?

0.21.1

### What browser(s) is this bug affecting?

All

### What OS are you using?

Any

### What are the steps to reproduce the bug?

Compare/contrast margin styles for dense textfield vs. regular textfield:

![image](https://user-images.githubusercontent.com/398379/30827548-73cbd21e-a208-11e7-9cef-7b1983aa8d97.png)

![image](https://user-images.githubusercontent.com/398379/30827679-f1a17e00-a208-11e7-9ecd-8a7908ef2dc8.png)

### What is the expected behavior?

Margins should ideally be consistent to avoid text fields "jumping"

### What is the actual behavior?

textfield--dense has a pronounced margin-top whereas textfield has no margin-top.

This is particularly noticeable if you have a sequence of textfield boxes one after the other vertically, as seen in the branch on #998.

In practice this might not be too terrible since you're likely to choose either normal or dense and stick with it, but I'm wondering if it's feasible to make the margin differences more negligible. It may be worth investigating in the future esp. if textfield boxes become the default or more "boxed" variants emerge.

**Comment by amsheehan** [comment]
Basically Design came back with "we haven't really thought about it"

So I think we can leave this for now. If a user files an issue we can revisit.

**Comment by r1cs1** [comment]
[Guideline](https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes) has a section "Dense layouts". It's not just margin top, but box height (56->44), label height, input height, and padding between label and input, margin bottom. Can we reopen this issue?

**Comment by kfranqueiro** [comment]
I believe all of those things are currently being adjusted for dense text fields; is there anything you noticed missing?

I entered this issue specifically because comparing dense vs. normal side-by-side, they end up misaligned with each other due to the top margin changing, and I wondered if we should try to even out the two.

(Incidentally, the design guidelines don't seem to cover the top _margin_ which is what I was pointing out, so I'm not really sure how we decided to implement the margin...)

**Comment by r1cs1** [comment]
@kfranqueiro margin-top does not part of the --box height. So it only gets pushed down by 12px but stays 56px height. If you set 44px height for the --dense version then it's going to be aligned if you place them next to each other but label will be misaligned within the box. 

Regarding the margin-top: I don't think a common usecase is to place a normal and a densed texbox next to each other, it's more like you use either normal or densed in your form and in that case densed texbox because of the margin-top does not make the form more densed :)
