### ISSUE TITLE
mdc-rtl-reflexive-position's use of `initial` is problematic on IE 11

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1353]
### What MDC-Web Version are you using?

0.21.1

### What browser(s) is this bug affecting?

IE 11

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Here's one instance in which the bug is evidenced:

* Look at the [snackbar demo](http://material-components-web.appspot.com/snackbar.html)
* Scroll down and click "show start aligned (RTL)"

### What is the expected behavior?

The snackbar should be the same width as the "show start aligned" (LTR) snackbar example

### What is the actual behavior?

The snackbar is super-wide because [IE 11 doesn't understand `initial`](http://caniuse.com/#feat=css-initial-value)

### Any other information you believe would be useful?

We should probably be setting to `auto` rather than `initial` to support IE11. Would there be any repercussions to doing that?

FYI this also affects RTL treatment of the trailing icon in #998.

**Comment by amsheehan** [comment]
Clearly a bug. Tracking.

**Comment by asyncLiz** [comment]
Closing as obsolete since IE11 support is being dropped
