### ISSUE TITLE
Is there a specific reason why all css 'mdc-theme' classes are using '!important'?

### ISSUE THREAD

**Issue by alanuecker** [material-components/material-components-web#1357]
Hi. Not sure if it is indented but all `.mdc-theme--` CSS classes use `!important` for the color, which makes it impossible to use them with your own colors. 
![image](https://user-images.githubusercontent.com/11522706/30925361-dcd865f6-a3b1-11e7-92cc-b8efdf7fceef.png)
<br>
The `true` in `@include mdc-theme-prop(color, $style, true);` sets all of them to `!important`.
https://github.com/material-components/material-components-web/blob/2314ad5dccd90c04b57f4c4727c94490154d787e/packages/mdc-theme/mdc-theme.scss#L25-L43

**Comment by Garbee** [comment]
Because these are specific color override classes. Which are included early in a component in order for them to even have the theme stuff to work with. So these need the importance to give them the best shot at taking effect as desired.

**Comment by amsheehan** [comment]
That is correct. These classes are there to append to your markup so that the colors override everything. This is intentional. If you have further questions about MDC Theme feel free to hop on our [Discord](https://discord.gg/KuPrNhA). Thanks!
