### ISSUE TITLE
Jittering on animated floating labels for textfields

### ISSUE THREAD

**Issue by TheMangoTrain** [material-components/material-components-web#1380]
### What MDC-Web Version are you using?

0.22.0

### What browser(s) is this bug affecting?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:56.0) Gecko/20100101 Firefox/56.0

### What OS are you using?

Intel Mac OS X 10.11

### What are the steps to reproduce the bug?

1 - Click a text field (link to [textfield demos](https://material-components-web.appspot.com/textfield.html))
2 - Carefully watch the floating label as it animates upward
3 - When it gets to the 'up' position, the label text has a jitter to it and/or an apparent state change from smoothed-font state to a crisp-font state
4 - It's easier to see if the label font color has more contrast (e.g. black text on white bg)
5 - It used to be really really noticeable on the multi-line textfield up until yesterday, and it seems today a new build came out that has changed the multi-line component making this issue less apparent, but still there.
6 - Looking at the full-width multi-line textfield, the labels state change from smooth-font to crisp-font seems to be more delayed than other textfield elements.

### What is the expected behavior?

Floating labels should ideally animate cleanly without apparent jitter.

### What is the actual behavior?

Floating labels animate with some apparent jitter, depending on circumstances.

### Any other information you believe would be useful?

The jittering is a known issue with some browsers when scaling with CSS transforms. Concerning MDC, textfield labels on other browsers on OSX look fine (Chrome, Safari). Anyways somehow hardware acceleration and/or font smoothing is involved. Various tricks exist to eliminate or minimize the issue, however there seems to be no silver bullet solution for all browsers. One trick that seems to have some effect, specifically on Firefox in OSX, is forcing the perspective parameter in the CSS transform. This seems to force a font-smoothing state on the text, so it never goes through a state change. It eliminates the jitter but results in the label looking too smooth/blurry.
```
.mdc-textfield--multiline .mdc-textfield__label--float-above {
     -webkit-transform: perspective(1px) translateY(calc(-100% - 6px)) scale(0.923, 0.923);
      transform: perspective(1px) translateY(calc(-100% - 6px)) scale(0.923, 0.923);

}
```

In any case, **_Material Design Lite doesn’t seem to have this jitter issue... I can’t see any jittering with their animated floating labels._** How are they achieving their animation? Can the technique be used in MDC? I could guess that maybe they’re stepping the font-size manually with JS, rather than relying on built-in CSS transform animation, and perhaps doing this eliminates any font state change related to smoothing?

**Comment by acdvorak** [comment]
Thanks for reporting this issue!

I was able to repro the jitter in Firefox and Chrome on Mac. It's much more pronounced in Firefox, but still happens (to a subtler extent) in Chrome.

Specifically, the hero textfield at the top of the demo page and the JavaScript-enabled textareas reliably show the jitter.

It's easier to see on a Mac if you zoom in using the system accessibility shortcut (System Preferences > Accessibility > Zoom > Use scroll gesture with modifier keys to zoom).

**Comment by williamernest** [comment]
I think this is a related issue, but specifically references it happening in keyframes. I'll continue to track this issue on chromium and file a new one if this bug doesn't resolve the issue. https://bugs.chromium.org/p/chromium/issues/detail?id=700790. 

This is the Firefox issue regarding the font smoothing change at the end of the transition
https://bugzilla.mozilla.org/show_bug.cgi?id=1423472

**Comment by abhiomkar** [comment]
Closing this as obsolete.
