### ISSUE TITLE
Menu opening animation shows scrollbar

### ISSUE THREAD

**Issue by j-o-d-o** [material-components/material-components-web#1387]
### What MDC-Web Version are you using?
0.22.0

### What browser(s) is this bug affecting?
Chrome Version 61.0.3163.100 (64-Bit)
MS Edge 40.15063.0.0

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
The bug occurs on the official demo site, but also in my own applications:
[https://material-components-web.appspot.com/simple-menu.html](url)

### What is the expected behavior?
Menu should open without scrollbar.

### What is the actual behavior?
Menu opening animation includes scrollbar until it is fully opened, looks ugly.

![bug_mdc](https://user-images.githubusercontent.com/15958535/31215062-6371e040-a9ae-11e7-94ce-a9fa9de7723f.png)

**Comment by j-o-d-o** [comment]
So a quick fix for the mean time is adding this to your css/sass:
`.mdc-simple-menu{ overflow: hidden !important; }`

Thus I am guessing the overflow property is somehow overridden during animation.

**Comment by acdvorak** [comment]
Appears to be caused by PR #1266

**Comment by jordyboytjuh** [comment]
There should be a scrollbar if the list in the menu is too long. Maybe it is possible to only set that overflow on auto if the animation is finished? On smaller lists, the scrollbar shouldn't be there.

**Comment by touficbatache** [comment]
@jordyboytjuh You're right, maybe we should set `overflow-y: auto;` after the animation is finished.
