### ISSUE TITLE
Persistent Drawer not visible on google Chrome when body has a scrollbar

### ISSUE THREAD

**Issue by torstahl** [material-components/material-components-web#1399]
Hello 

If the page body have a scroller the persistent drawer is not visible. See Code Pen 
If you remove the h1 tags to get a page with no scroller the drawer comes back.

### What MDC-Web Version are you using?
0.22.0
### What browser(s) is this bug affecting?
Google Chrome Version 57.0.2987.133 (64-bit) and Version 61.0.3163.100
### What OS are you using?
(OS Linux or Windows on both  the same bug)
openSUSE 42.2 (x86_64)
Windows 10
### What are the steps to reproduce the bug?
https://codepen.io/anon/pen/EwERYE

### What is the expected behavior?

persistant drawer is visible 
### What is the actual behavior?
persistant drawer is not visible 

Best Regards
Torsten

**Comment by Garbee** [comment]
It is visible here.

Elementary OS (Ubuntu 16.04) on Chrome Version 63.0.3230.0 (Official Build) dev (64-bit)

**Comment by acdvorak** [comment]
Looks like toolbar is actually the problem - the drawer still shows up when you click the icon (which is hard to see but still there), whereas the toolbar background disappears for some reason.

**Comment by Garbee** [comment]
It is losing the background color since the toolbar's main node has no height. Which is where the background is applied. Adding `flex-shrink:0;` in this case fixes the issue forcing the toolbar to not shrink in the flexbox area. This is due to the custom "demo" container code, wherever that is coming from.

Looks to me like this is all due to user-land code issues with flexbox. Not a problem in the library.

**Comment by torstahl** [comment]
code pen was created from this example 
https://material-components-web.appspot.com/drawer/persistent-drawer.html
So you can reproduce it in the developer console when you copy multiple times the h1 tag to get a scrollbar.

**Comment by Garbee** [comment]
So we need a `demo-toolbar` class to add the flex shrink to it.

**Comment by abhiomkar** [comment]
Closing this bug as obsolete.
