### ISSUE TITLE
Investigate adding custom elements demo

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#14]
Add a demo illustrating how to wrap MDL's v2 architecture into a custom element.

> Copied from https://github.com/google/material-design-lite/issues/4799

**Comment by jonboj** [comment]
An example of mdc web wrapped with dart custom elements v0 (so fare v1 is unavailable in dart sdk).

mdcdalight - a polymer inspired dart lib for wrapping of Material Design Components web with custom elements(v0) : https://github.com/jonboj/mdcdalight

A demo/tutorial app : https://github.com/jonboj/daflight 
hosted build : https://tid4sport.com/daflight/web (support only web components v0, so sorry Safari is unsupported so fare).

More info in the readmes and details in overview doc https://github.com/jonboj/mdcdalight/blob/master/doc/overview.md

Feedback pro/con, opinions are welcome.

**Comment by romulocintra** [comment]
Hi would like to ear little more about this topic , if there any plan  to have MDC custom elements development , i saw you are using in some places css custom properties ,that helps me a lot in my "Port" of MDC to stenciljs and web components. 

is a very early WIP : 

https://github.com/o-rango/orango-material-design

**Comment by jonathanperis** [comment]
It would be wonderful if Material Components were already delivered as standard with Custom Elements!

**Comment by kfranqueiro** [comment]
I think this is now within the scope of https://github.com/material-components/material-components-web-components, which is wrapping MDC Web for web components using LitElement.
