### ISSUE TITLE
[Docs][Drawer][Permanent] Out of date

### ISSUE THREAD

**Issue by cheng93** [material-components/material-components-web#1416]
Hello

I believe the docs for this are out of date.

The example given in the doc has a class `mdc-permanent-drawer__content` which doesn't seem to be in the scss.

The demos looks like they use `flex`, which isn't present in the docs.

**Comment by cheng93** [comment]
I also think the drawer package should require a dependency to `@material/list`

**Comment by Garbee** [comment]
The drawer doesn't necessarily need to contain a material list container. So the list dependency isn't a problem.
