### ISSUE TITLE
Light theme within dark theme?

### ISSUE THREAD

**Issue by trollderius** [material-components/material-components-web#1425]
Would it be reasonable to define in this library some kind of `.mdc-theme-light` equivalent to the 'default theme' if for example you want to display a **light theme** container within a **dark theme**?

The point is that you can do it in the opposite way (dark theme within default)

**Comment by kfranqueiro** [comment]
We've been gradually doing a lot of work in the area of theming lately across components. Our current thinking is that the current "dark mode" support is actually somewhat awkward, and that we should ultimately aim to make it simple to redefine variables for either a light or a dark theme, without necessarily nesting one inside the other.

Out of curiosity, do you have a use case that involves nesting dark within light or vice versa?

**Comment by kfranqueiro** [comment]
Given no further response, and given that we're investigating the possibility of removing dark-within-light support in favor of improved theme customization, we're closing this issue.

We're currently in the middle of improving the ability to customize theming for each component; once that's completed across the board, please do let us know if you encounter difficulties or limitations in customizing MDC Web for your projects. Thanks!
