### ISSUE TITLE
MDCTextfieldFoundation has no public API to handle programmatic changes to the input value

### ISSUE THREAD

**Issue by gjdev** [material-components/material-components-web#1430]
In a form it sometimes required to programmatically change the value of a textfield user input (e.g. after some other interaction in the form). Currently the MDCTextfieldFoundation only listens to UI changes of the wrapped input element. After a programmatic change of the input value, there is no way to inform the foundation that the input has a new value. Effectively, label(-float), error, and helptext styles/content will not be updated after such changes.

This could be solved in two ways:
1. Give MDCTextfieldFoundation a method to inform it that that input.value was changed by code, e.g. MDCTextfieldFoundation.updateAfterValueWrite(), or:
2. Add a registerValueWriteHandler() to the adapter, which integration code can call to inform the foundation of programmatic changes to the input.value.

**Comment by kfranqueiro** [comment]
I believe this is the same issue as #822 (which has a PR), or it's at least highly related, so we should probably discuss there if there are additional concerns.
