### ISSUE TITLE
Missing Textfield label primary color application on focus

### ISSUE THREAD

**Issue by marioavs** [material-components/material-components-web#1435]
### What MDC-Web Version are you using?

> 0.23.0

### What are the steps to reproduce the bug?

> 1. Run the demo server (it is also present in the demo site https://material-components-web.appspot.com/textfield.html)
> 2. Go to localhost:8080/textfield.html
> 3. Check the Dark Theme option for the "Full Functionality JS Component" (second Textfield component). This step is only needed to make more evident the label coloring.
> 4. Tab-focus on the "Full Functionality JS Component" (second Textfield component)
> 5. Observe the label color

### What is the expected behavior?

> The label should be displayed with primary color for focused textfield components

### What is the actual behavior?

> The label is displayed with the normal / idle color as if it would be a non focused textfield component

### Any other information you believe would be useful?

> It looks like the following is needed and has been removed from packages/mdc-textfield/mdc-textfield.scss, for the `mdc-textfield--focused` class:
`@include mdc-theme-prop(color, primary);`

**Comment by reddysridhar53** [comment]
Can i take it up?

**Comment by dscalzi** [comment]
Still an issue on 0.25.0.

**Comment by moog16** [comment]
Will fix as a result of https://github.com/material-components/material-components-web/issues/1526
