### ISSUE TITLE
Toolbar Menu Icon not working

### ISSUE THREAD

**Issue by devdlx** [material-components/material-components-web#1439]
Hello, I had an issue that I encountered. The toolbar menu icon didn't have any css applied due to a change in the name of the css selector

*- Old -*
mdc-toolbar__icon--menu

*- New -*
mdc-toolbar__menu-icon

This page shows the old name in the example
https://material.io/components/web/catalog/toolbar/

While this page implements the new name
https://material-components-web.appspot.com/toolbar/index.html
Hello, I had an issue that I encountered. The toolbar menu icon didn't have any css applied due to a change in the name of the css selector

*- Old -*
mdc-toolbar__icon--menu

*- New -*
mdc-toolbar__menu-icon

This page shows the old name in the example
https://material.io/components/web/catalog/toolbar/

While this page implements the new name
https://material-components-web.appspot.com/toolbar/index.html

*- Old -*
mdc-toolbar__icon--menu

*- New -*
mdc-toolbar__menu-icon

This page shows the old name in the example
https://material.io/components/web/catalog/toolbar/

While this page implements the new name
https://material-components-web.appspot.com/toolbar/index.html

**Comment by kfranqueiro** [comment]
Sorry for the confusion. Our documentation is first updated on GitHub, and there is often a delay before those updates get pushed to material.io.  The content on material.io is now updated and reflects the new class name.

When in doubt, please also check the documentation as it appears in GitHub, e.g. https://github.com/material-components/material-components-web/tree/master/packages/mdc-toolbar#readme. Thanks!
