### ISSUE TITLE
Use create-react-app for the React framework example

### ISSUE THREAD

**Issue by kripod** [material-components/material-components-web#144]
I would like to suggest using [create-react-app](https://github.com/facebookincubator/create-react-app) for the React framework example in order to make its set-up and maintenance easier.

**Comment by amsheehan** [comment]
I tend to agree with you. The rest of the team are away on holiday but we will circle the wagons around this when everyone is back.

Thanks for filing the issue!

**Comment by kripod** [comment]
@amsheehan No problem, I refactored the example 😉

**Comment by amsheehan** [comment]
Nice!
