### ISSUE TITLE
Snackbar incorrect rendering with border-box

### ISSUE THREAD

**Issue by eligao** [material-components/material-components-web#1440]
### What MDC-Web Version are you using?

0.23
(as on https://material-components-web.appspot.com, but I'm not sure since 0.23 was just released)

### What browser(s) is this bug affecting?

Chrome 62

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36`

### What OS are you using?

- Windows 10 RS3  10.0.16299.19
- Android 7.1.2

### What are the steps to reproduce the bug?

1. Open https://material-components-web.appspot.com/snackbar.html
2. In the inspector, switch the device size emulator to a phone, e.g. iPhone 6. Or simply hook up an Android phone in the remote inspector.
3. In the inspector, add the following custom css:
```css
* {
    box-sizing: border-box;
}
```
3. Click "SHOW" to show a snackbar.

### What is the expected behavior?

A snackbar shows up, filling the whole width of the screen.
(I have changed to the dark theme to make it more clear)

![material-components-web appspot com_snackbar html iphone 6 3](https://user-images.githubusercontent.com/2323992/31700230-8acf5f22-b3fa-11e7-9fe4-c51bb747ef98.png)

### What is the actual behavior?

A snackbar shows up, leaving its right side a margin.

![material-components-web appspot com_snackbar html iphone 6 2](https://user-images.githubusercontent.com/2323992/31700223-7e1b0510-b3fa-11e7-93c8-9bd5b722efc1.png)

### Any other information you believe would be useful?

It seems the Snackbar component ( as well as some other components) are designed with `box-sizing: content-box;` in mind. 
However, in the case when `box-sizing: border-box;` is set globally ( which happens very often ), the box-sizing of the Snackbar gets overwritten easily.
Adding this css seems to address this problem, but can it be done more elegantly?
```css
.mdc-snackbar {
  box-sizing: content-box;
}
```

**Comment by kfranqueiro** [comment]
Thanks for pointing this out. At minimum we should probably look at ensuring that all components are explicit about which box model their styles assume. At best maybe we can switch things to border-box if it makes sense (but we'd still want to explicitly do that on each component's styles).

**Comment by kfranqueiro** [comment]
Just realized a few minutes ago that you already created a PR to resolve this. Thanks! Meanwhile I entered #1455 to cover the broader scope of this type of problem.
