### ISSUE TITLE
Is there anyway to use material web components SCSS in only html project without webpack or others?

### ISSUE THREAD

**Issue by hlaporthein** [material-components/material-components-web#1441]
I am now creating html project using sass and client requested to use material.io web component. My sass is working fine. I included material.io component through node_modeules folder. But when I tried to access material-components-web.scss like below code

```
    //style.scss file
    @import 'layout';
    @import 'typo';
    @import 'image';
    @import 'overwrite';
    @import "~material-components-web";
```

I got this error message in style.css file.

```
    /*
    Error: File to import not found or unreadable: ~material-components-web.
           Load paths:
             /Users/kenvsi/www/static/mycondo/assets/sass
             /Applications/Koala.app/Contents/Resources/app.nw/rubygems/gems/compass-core-1.0.1/stylesheets
             Compass::SpriteImporter
            on line 5 of /Users/kenvsi/www/static/mycondo/assets/sass/style.scss
    
    1: @import 'layout';
    2: @import 'typo';
    3: @import 'image';
    4: @import 'overwrite';
    5: @import "~material-components-web";
```

My question is that I would like to assess all material scss components, variable and function to my custom scss file without webpack. Is there any ways to access those material scss options in html project?

**Comment by nboliver** [comment]
You can try importing it using the relative path, like this:
```
@import "../../../node_modules/material-components-web/dist/material-components-web";```

**Comment by hlaporthein** [comment]
Hi @nboliver ,  That would import only css not scss. I need to access scss and I could use default variables & functions from the component.

**Comment by matsp** [comment]
In the root directory of the package you can find the big SCSS file:

```SCSS
@import "~material-components-web/material-components-web";
````

**Comment by kfranqueiro** [comment]
AFAIK, `~` in imports is a feature specific to webpack (or available as a [standalone custom importer](https://github.com/matthewdavidson/node-sass-tilde-importer)), but the original question here pertains to loading MDC Web's sass _without_ webpack.

It should be feasible to do the following...

```scss
@import 'material-components-web/material-components-web';
```

...as long as you also incorporate your `node_modules` folder in your include path passed to node-sass, [as noted in our README](https://github.com/material-components/material-components-web#css):

```
node-sass yourfile.scss --include-path=node_modules
```

(This assumes you're running the command from the folder containing `node_modules`; revise as necessary.)

**Comment by JamesVanWaza** [comment]
@matsp @kfranqueiro 
> In the root directory of the package you can find the big SCSS file:
> 
> ```css-scss
> @import "~material-components-web/material-components-web";
> ```


The issue is recurring, and in the `material-components-web` folder there is no 

```
@material folder 
```

See Screenshot Attached 

<img width="1870" alt="Screen Shot 2020-07-13 at 3 25 59 PM" src="https://user-images.githubusercontent.com/4000076/87344872-298c3780-c51d-11ea-8399-8ff5f3282136.png">

**Comment by asyncLiz** [comment]
The `@material/*` folders are sibling folders of `material-components-web/` in your `node_modules/`

Please see https://github.com/webpack-contrib/sass-loader/issues/804 and https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020 for workarounds when using `@import`.

Our recommendation would be to switch to `@use material-components-web/material-components-web;` to avoid any `@import`/`@use` sass-loader issues.

**Comment by JamesVanWaza** [comment]
@asyncLiz says, 
<img width="977" alt="Screen Shot 2020-07-13 at 4 27 50 PM" src="https://user-images.githubusercontent.com/4000076/87350403-cce14a80-c525-11ea-8d67-34d48a6f5173.png">

Is it possible to show, how you have set it up in your `style.scss` file?

**Comment by asyncLiz** [comment]
Can you try the workaround suggested in https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020?

Notably, do not use the `~` when importing the Sass and set `webpackImporter: false`. Additionally, make sure your sass-loader is set up to include `node_modules` in its `includePaths` and that you're using the `sass` implementation instead of `node-sass`.
