### ISSUE TITLE
Button with .mdc-button--accent is using primary color to render background color

### ISSUE THREAD

**Issue by tom10271** [material-components/material-components-web#1443]
### What MDC-Web Version are you using?
v0.23.0

### What browser(s) is this bug affecting?
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### What OS are you using?
macOS Sierra 10.12.6 (16G29)

### What are the steps to reproduce the bug?
https://codepen.io/anon/pen/RLEJBp

### What is the expected behavior?
That button should have pink color, which is accent's one

### What is the actual behavior?
It uses primary one

**Comment by Garbee** [comment]
This is expected, the accent modifiers were removed. Ref #1332 on the discussion stemming from that change.
