### ISSUE TITLE
Add events to simple menu / select components

### ISSUE THREAD

**Issue by nboliver** [material-components/material-components-web#1451]
Since there's already the `MDCSelect:change` event, it could be useful to emit `open` and `close` events on these components so that handlers can be easily bound. I tried several workarounds to implement this, but couldn't come up with anything workable. Open to suggestions.

**Comment by kfranqueiro** [comment]
Can you explain your use case for this? Native selects don't really emit open/close events either, only `change`, so we're currently aiming to be consistent with that.

FWIW, `MDCSelect` is closed specifically in response to `MDCSimpleMenu:select` and `MDCSimpleMenu:cancel`, and it's opened in response to click and spacebar keydown.

**Comment by nboliver** [comment]
Right, that's fair WRT native selects. The use case could be something like updating the visual appearance of surrounding content when a select is open. But that can be achieved using a combination of mouse/keyboard and MDCSimpleMenu events, so I'll go ahead and close this.
