### ISSUE TITLE
Vertically Aligning a Grid

### ISSUE THREAD

**Issue by tvvignesh** [material-components/material-components-web#1460]
Tried getting an element (Testing) centered on the screen using grid.

I am currently using the following markup. If I remove height:100vh from the inner grid height it stops working. (top and bottom grid get 0px height) and thus the middle grid is pushed to top of the screen.

Currently, what I am doing here seems to be a hack since I  am guessing it should work without explicity specifying height.

**This code is placed inside a div with 100vh height and thus the grid is given full viewport.**

```
<div class="mdc-layout-grid mdc-typography">
  <div class="mdc-layout-grid__inner" style="height:100vh">
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--align-top"></div>
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--align-middle">
      <div align="center">
        <h1 class="mdc-typography--display2">Testing</h1>
      </div>
    </div>
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--align-bottom"></div>
  </div>
  </div>
```

**Comment by kfranqueiro** [comment]
This seems like it might be a problem specific to your use-case; the alignment classes seem to be applying the styles that they should be out-of-the-box, at least conceptually. Admittedly we don't have a good example of this in the demo page, though.

Would you be able to provide a CodePen so we can see the issue in context? (You can start by forking [this template](https://codepen.io/traviskaufman/pen/pNQmRp) if you want.)

**Comment by tvvignesh** [comment]
@kfranqueiro Added a codepen here: https://codepen.io/anon/pen/pWmBWm

It shows the content top aligned. Just add height:100vh to inner container as I mentioned above, and you will see it working correctly.

**Comment by lynnjepsen** [comment]
This is not an intended use case for layout grid. Layout grid is designed to support multiple columns, and each cell should have a height greater than 0px.

If you're just trying to center an element on a screen, check out these tricks: https://css-tricks.com/centering-css-complete-guide/
