### ISSUE TITLE
iOS UIWebView fixed-lastrow toolbar not updating until scrolling stops

### ISSUE THREAD

**Issue by mjwwit** [material-components/material-components-web#1467]
### What MDC-Web Version are you using?
0.23.0

### What browser(s) is this bug affecting?
iOS Safari 11 UIWebView.

### What OS are you using?
iOS 11.0.3

### What are the steps to reproduce the bug?
1. Add an `mdc-toolbar` with classes `mdc-toolbar--fixed` and `mdc-toolbar--fixed-lastrow-only` to a page displayed inside a UIWebView in an iOS app (like when using Cordova/Phonegap)
2. Add enough content to overflow the screen.
3. Start scrolling.

### What is the expected behavior?
The toolbar position updates as you scroll.

### What is the actual behavior?
The toolbar position won't update until you stop scrolling.

### Suggested fix
Currently, the `mdc-toolbar--fixed-lastrow-only` adds a scroll listener to keep track of the element's `scrollTop` attribute so it can transform (y translation) the toolbar (which has `position: fixed`). On most browsers, this causes the toolbar to scroll with the page up to a certain point (the last row).
This is the exact same behavior offered by `position: sticky` ([specs](https://www.w3.org/TR/css-position-3/#sticky-pos)). Not only does `position: sticky` fix the issues in iOS UIWebView, it also drastically improves performance across all browsers.
`position: sticky` Is supported by all major browsers except IE11, so a workaround will be needed for IE.

**Comment by kfranqueiro** [comment]
Out of curiosity, do you know if this also happens with the other flexible toolbar types, and whether they can all be fixed similarly? A CodePen or PR (even if for the sake of demonstration) would also be helpful, if you're up for it.

Thanks!

**Comment by mjwwit** [comment]
I'm not sure if it can fix the other flexible toolbar types as well, but I'll fool around a bit to see if I can make it work.

A CodePen would work in every browser except Safari, which destroys fixed and sticky positioning on elements inside an iframe (and CodePen displays pens inside iframes). I would've included a CodePen to demo the issue if it was possible.
I will make one to demo the functionality in other browsers though.

**Comment by kfranqueiro** [comment]
Thanks for your efforts!

RE the other flexible toolbar types, I guess my primary concern is that we don't cause any issues in one by fixing the other, even if we do target one specific type here.

**Comment by mjwwit** [comment]
I made a CodePen demonstrating `position: sticky` as a replacement for the `fixed--lastrow-only` logic. I may also be able to use it for the waterfall flexible toolbar as well as the waterfall flexible toolbar with fixed last row. I'll make pens for those too and share them here when I'm satisfied.

**Comment by lynnjepsen** [comment]
Unfortunately, because `position: sticky` does not work with IE, and we have to support IE, we cannot use `position: sticky`

We don't currently have a way of serving different CSS or JavaScript depending on browser feature detection...and we would need that kind of framework before we could use something like `position: sticky`.
