### ISSUE TITLE
Ripple enhancement

### ISSUE THREAD

**Issue by rontav** [material-components/material-components-web#147]
**Feature Request**

Demo: [my implementation of material button](https://966a1d6a-eae0-48c0-bbde-9bbf772c7073.sbook.io/?selectedKind=Button&selectedStory=Required%20%26%20not%20required&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

I think the button (and other components) should support having multiple ripples active at the same time. Some could argue that this could distract the user, but I think it is a cool small visual detail.

Also, we should implement the focus state of the ripple.
![image](https://cloud.githubusercontent.com/assets/5609659/21498062/ee7ce5d2-cc31-11e6-9970-9401f9d1b909.png)

And an opinion: the ripple (in the material design guidelines) is way too fast. I think the animation should be slower to allow the user to see the effect in all its greatness.

**Comment by sgomes** [comment]
Thanks, @rontav! We have plans to add ripples to buttons very soon (see #20).

As for supporting multiple ripples, I believe that was a design trade-off designed to keep DOM overhead to a minimum; with our approach we can rely on `::before` and `::after` alone to implement the (single) ripple, whereas we'd need more DOM nodes for multiple ones. I'll let @traviskaufman speak more to that, though, as he's more familiar with that code.

Regarding the ripple speed, the MD spec isn't a super-strict thing; each application definitely has freedom in customising it to its needs, ripple speed included :) As a library, though (and an official one, at that), we have to be a bit more conservative in staying close to the spec; any tweaks should be done by the end developer building an application, not the library author, in my opinion.

**Comment by traviskaufman** [comment]
@sgomes pretty much nailed everything. The only thing I can add is that regarding the ripple focus state, this is something that we discussed with design internally, and they preferred our more simpler focus method. We are also working closely with design to continuously improve the UX of the ripple on the web platform.
