### ISSUE TITLE
A heart inside FAB shows the left on iOS.

### ISSUE THREAD

**Issue by GitHub30** [material-components/material-components-web#148]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

Unknown

### What browser(s) is this bug affecting?

Safari on iOS and Chrome on iOS

### What OS are you using?

iOS 10.2

### What are the steps to reproduce the bug?

1. Navigate to https://material-components-web.appspot.com/fab.html
2. Observe the result

### What is the expected behavior?

A heart inside FAB shows the center.

### What is the actual behavior?

The heart inside FAB shows the left.

_Safari on iOS_
![img_0860](https://cloud.githubusercontent.com/assets/12811398/21505002/bf37c3b2-cca6-11e6-961c-a3be9e4f171f.PNG)

_Chrome on iOS_
![img_0861](https://cloud.githubusercontent.com/assets/12811398/21505006/c611e8e8-cca6-11e6-87f8-b783e7c5f394.PNG)

### Any other information you believe would be useful?

I don't know.

**Comment by amsheehan** [comment]
Would you mind copying a code snippet of your implementation? This was a known issue and should be fixed in the latest version of MDC Web.

**Comment by GitHub30** [comment]
yeah. Thank you for replying. I guess I'd better fix it.

**Comment by amsheehan** [comment]
@traviskaufman looks like this is a stale version of the demos. Closing this as the issue was already fixed in #132
