### ISSUE TITLE
Slidable drawer doesn't close if swiped less than 50% and quickly

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1482]
### What MDC-Web Version are you using?

> 0.23.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> All OS

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/drawer/temporary-drawer.html
> 2. Open the drawer
> 3. Swipe the drawer till it's closed less than 50%

### What is the expected behavior?

> The drawer should open back if it has been swiped slowly. But it should close if it's swiped quickly even if it's closed less than 50%

### What is the actual behavior?

> The drawer re-opens even if the drawer is swiped quickly (https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/slidable/foundation.js#L201)

### Any other information you believe would be useful?

> We should implement a specific time and if the swipe takes less time than the specified then close the drawer. It can be done with touchstart `new Date().getTime()` and touchend `new Date().getTime()` then substract the second from the first and compare with the specified time.

**Comment by abhiomkar** [comment]
Closing this bug as obsolete.
