### ISSUE TITLE
Dialog Button Size Incorrect

### ISSUE THREAD

**Issue by MeyerUX** [material-components/material-components-web#1483]
**What MDC-Web Version are you using?**
Online dialog example: https://material-components-web.appspot.com/dialog.html 

**What browser(s) is this bug affecting?**
All

**What are the steps to reproduce the bug?**
1. Review link: https://material-components-web.appspot.com/dialog.html 
2. Inspect dialog buttons
3. .mdc-button is using min-width: 88px;

**What is the expected behavior?**
Dialog buttons have a min-width: 64px; See Material Design documentation for "Button width and padding" https://material.io/guidelines/components/dialogs.html#dialogs-specs 

![screen shot 2017-10-25 at 8 19 49 am](https://user-images.githubusercontent.com/13976381/32008022-07bc6aa6-b960-11e7-8d6c-4a940074ffbf.png)

**Comment by touficbatache** [comment]
You're right! I think the changes should be on the dialog side and not on the button one:

- [ ] Add a `min-width: 64px;` to the `mdc-dialog__footer__button` class.

Feel free to submit a PR to fix this issue. Thank you!

**Comment by kfranqueiro** [comment]
Thanks for reporting (and thanks Toufic for the PR already). I'm checking with design just to make sure this is indeed intentional first.

**Comment by MeyerUX** [comment]
Awesome! Thanks @touficbatache & @kfranqueiro

**Comment by touficbatache** [comment]
No problem! Happy to help :smiley:
