### ISSUE TITLE
Lists have incorrect padding

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1488]
### What MDC-Web Version are you using?

> 0.23.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> All OS

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/list.html
> 2. Take a look at the lists padding

### What is the expected behavior?

> Lists should have a top and bottom padding of 8px , except for lists with subheaders, which have their own padding. https://material.io/guidelines/components/lists.html#lists-specs

### What is the actual behavior?

> Lists have only a top padding of 8px

### Any other information you believe would be useful?

> I'll submit a PR if needed :smiley:

**Comment by lynnjepsen** [comment]
Looks like a bug, and a PR would be great!

Is this the same as #1489? Would you create a PR to fix both?

**Comment by touficbatache** [comment]
@lynnjepsen It is :sweat_smile: That's why I closed the other one :smiley:

**Comment by touficbatache** [comment]
@lynnjepsen I just submitted #1523 to fix this but should I change the padding (now at `0 $mdc-list-side-padding`) of the list group too?
