### ISSUE TITLE
Lists in drawers have incorrect padding

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1489]
First, I decided to separate this issue from #1488 because the fix is more related to the drawer and is different than the other one.

### What MDC-Web Version are you using?

> 0.23.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> All OS

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/drawer/temporary-drawer.html
> 2. Open the drawer
> 3. Take a look at the list top and bottom padding

### What is the expected behavior?

> [According to the guidelines](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-specs), the list should have a 8px padding at the top and bottom of every list grouping. One exception is at the top of a list with a subheader, because subheaders contain their own padding.

### What is the actual behavior?

> The list in the drawer has a top and bottom padding of 0.

### Any other information you believe would be useful?

> I think we should create a class (`mdc-list-drawer`) that adds a top and bottom padding of 8px. Take a look at the [Permanent Drawer below toolbar](http://material-components-web.appspot.com/drawer/permanent-drawer-below-toolbar.html), the list is too close to the toolbar and it doesn't look good.

**Comment by lynnjepsen** [comment]
Looks like it could be the same fix as #1488, but waiting for confirmation
