### ISSUE TITLE
Dialog footer does not push to bottom when height is manually set

### ISSUE THREAD

**Issue by djensen47** [material-components/material-components-web#1491]
Maybe this is a bug or works as intended. To me, it seems a bit wrong to overwrite css to make this work as I need it to.

### What MDC-Web Version are you using?

0.22.0

### What browser(s) is this bug affecting?

All browsers

### What are the steps to reproduce the bug?

1. Create a dialog box.
2. For the "mdc-dialog__surface" div, set height to 100%

### What is the expected behavior?

The footer button bar appears at the bottom of the dialog regardless the height of the overall dialog.

### What is the actual behavior?

The footer appears directly under the body.

### Any other information you believe would be useful?

As a workaround I set the following on `mdc-dialog__footer`
```
position: absolute;
bottom: 0;
right: 0;
```

The problem with this approach is that it breaks RTL/LTR.

**Comment by touficbatache** [comment]
Thanks for reporting, I'm not sure if it's a bug but I did some research and found out that the problem can be fixed by simply adding a `flex: 1` to the `mdc-dialog__body` class and it doesn't break RTL/LTR.

**Comment by Garbee** [comment]
What you're describing is a full screen dialog which is not yet implemented. Ref #1464 for more on that. So, this case seems perfectly fine as it is to need provide custom CSS to get the expected functionality.

**Comment by djensen47** [comment]
Uh, except that it's not because it's very developer unfriendly (I assume most devs are not willing to track things down into GitHub and src like we all do). So you have to happen to know that `flex: 1` is the solution. Otherwise, you try just making the div bigger, it doesn't work, so you muck around, get mad, and just do whatever to make it work.

Other frameworks have dialog's that act properly if sized manually. Why should this amazing library be the exception? 😁

Also, yes, I happen to want a full screen dialog but only for mobile. But even on desktop, the dialog is giant W—I—D—E so I need to be able to adjust the dimensions in all directions.

Plus, if the solution is as simple as `flex: 1`, you can make the change and bam! you now have fullscreen dialogs too. 😉

Wherever the outcome, great stuff here.

**Comment by touficbatache** [comment]
@djensen47 Yes, I think creating the full-screen dialog is as easy as adding a `flex: 1` and making the div `height: 100vh`. In the meanwhile, try this workaround till the full-screen dialog gets released.

**Comment by lynnjepsen** [comment]
This is the same issue as #1464.

We're sorry this is not developer friendly, but we don't have the resources to fix this immediately. It appears the original MDC Dialog was written without taking into account the full screen version of a dialog. However, we are now focusing on improvements to other parts of the MDC Web library, and have not prioritized circling back to dialog.

**Comment by djensen47** [comment]
@lynnjepsen Would you accept a pull request for the fix? I'm fairly certain it's a 1-2 lines of code to change it.

**Comment by touficbatache** [comment]
No, I don't think so. If the issue was closed, it's certainly for a reason.
The full-screen dialog will be released soon. Till then, you can do the
changes in your custom css file so it fits better your project.

**Comment by djensen47** [comment]
😕
