### ISSUE TITLE
(mdc-auto-init) Could not find constructor in registry for MDCTabBarScroller

### ISSUE THREAD

**Issue by roncapat** [material-components/material-components-web#1494]
MDCTabBarScroller constructor seems to not be registered in MDCAutoInit: when using it, the error message in the title is displayed.

**Comment by touficbatache** [comment]
There's no MDCTabBarScroller in MDCAutoInit, you have to add a `data-mdc-auto-init` attribute with `MDCTabBar` to the root element (nav with class `mdc-tab-bar`). Hope this helps you.

**Comment by Red0head** [comment]
The Tabs itself working by adding `data-mdc-auto-init` attribute with `MDCTabBar` to the root element. But then the `mdc-tab-bar-scroller__indicator` are hidden and not working. Is there a solution or should we reopen the issue?
