### ISSUE TITLE
mdc-simple-menu: disabled menu items not taken into account when focusing

### ISSUE THREAD

**Issue by gjdev** [material-components/material-components-web#1495]
### What MDC-Web Version are you using?

0.23.0

### What browser(s) is this bug affecting?

All browsers

### What OS are you using?

NA

### What are the steps to reproduce the bug?

1. Go to the following codepen: https://codepen.io/gjdev/pen/QOLYEZ
2. Click the "reveal menu" button.
3. The first menu element now gets focus (this is not visible because the element is disabled, but can be checked via developer tools)
4. Use the arrow-keys to focus other menu elements. All disabled menu elements will get focus if you key to them (again, not visible because of the styling for disbled menu items).

### What is the expected behavior?

Disabled menu items are not focusable.

> Please describe what the component/code should be doing that it's not.

The component ignores the disabled state when focusing elements, but correctly uses it for everything else. How to disable a menu item is also documented in the readme. Therefore, it's only logical to take the disabled state into account for focus as well.

### What is the actual behavior?

Disabled menu items can be focused (even though you can't see it due to the styling). This leads to a confusing UI experience.

**Comment by gjdev** [comment]
There is an additional issue, also related to how the disabled state is handled: when clicking a disabled menu-item, the menu is closed. But neither notifySelected() nor notifyCancel() is called. In this case notifyCancel() should be called, because the menu is closed, without a menu-item being selected.

**Comment by touficbatache** [comment]
This looks like a bug, thanks for reporting!

**Comment by lynnjepsen** [comment]
It sounds like the bug is that MDC Menu lets users focus on elements, but without giving any visual indication of the focus. 

Generally in MDC Web we do not let users focus on elements that are disabled (at least, thats how MDC Button seems to work on Chrome). I think we should remove the ability to focus on disabled menu items.

**Comment by gjdev** [comment]
There are two (related bugs):

1. User can focus disabled menu items, which should not be possible
2. Mouse/pointer clicks on a disabled menu item close the menu without calling notifyCancel().

**Comment by kfranqueiro** [comment]
FYI I believe that the issue of clicking a disabled item dismissing the menu has been resolved due to #1648. The issue of focusable disabled items still exists.
