### ISSUE TITLE
No required option on Checkbox, Select, or Radio

### ISSUE THREAD

**Issue by mellogarrett** [material-components/material-components-web#1497]
## Feature Request
Add `required` option to Checkbox, Dropdown Select, and Radio components, just like TextField has.

**Comment by anton-kachurin** [comment]
AFAIK, the spec doesn't have `required` option for selection controls (Checkbox, Radio, Switch):
https://material.io/guidelines/components/selection-controls.html

As for Select, there is already an issue for this #291 marked as "in tracker".

**Comment by lynnjepsen** [comment]
You can add `required` to Checkbox and Radio:

https://codepen.io/anon/pen/vWNWxx

And we're working on adding it to Select

Check the #291.

**Comment by QJan84** [comment]
> And we're working on adding it to Select

Will the `required ` attribute for Select be implemented soon? 
Or is there a workaround?
