### ISSUE TITLE
Implement "Persistent" Side Nav Component

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#15]
Spec reference: https://www.google.com/design/spec/patterns/navigation-drawer.html

"Persistent" drawers are the ones that remain on the page yet collapse into miniature drawers when not being used.

> Copied from https://github.com/google/material-design-lite/issues/4754

**Comment by vtolstov** [comment]
does anybody already started this component?

**Comment by traviskaufman** [comment]
@vtolstov no one has, but I believe that @sgomes was planning on eventually completing it. I'd sync with him before beginning work.

**Comment by sgomes** [comment]
@vtolstov Yes, persistent drawers are definitely in the plans! Current estimates point to mid-April, but it could happen before then.
