### ISSUE TITLE
MDCCheckbox, javascript console warning in IE

### ISSUE THREAD

**Issue by anton-kachurin** [material-components/material-components-web#1504]
### What MDC-Web Version are you using?

0.23.0

### What browser(s) is this bug affecting?

Internet Explorer 11, Edge

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Open the page in IE: https://material-components-web.appspot.com/checkbox.html

There will be multiple errors there that read:
```
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
```

### Any other information you believe would be useful?

The errors are caused by this element:
```
<path class="mdc-checkbox__checkmark__path"
      fill="none"
      stroke="white"
      d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
```

**Comment by lynnjepsen** [comment]
Seems like a bug, just need to close the path element. Do you want to submit a PR?

**Comment by lynnjepsen** [comment]
I gave poor guidance on this bug. The self-closing element is valid HTML, and the <path></path> is actually NOT valid (despite IE complaining).

Theres some more info here: https://stackoverflow.com/questions/24299969/closing-svg-tags-explicit-or-self-closing/31120364#31120364

We need to add a caveat to the README for MDC Checkbox. It should explain to our users that is necessary on IE to avoid the console warnings.

**Comment by kfranqueiro** [comment]
I'm going to be super-pedantic here... IE complains because this is "invalid HTML", but it's completely valid XML/SVG, hence the whole confusion. :)

**Comment by touficbatache** [comment]
@kfranqueiro That's correct, I submitted #1533 to add a notice in the
README.
