### ISSUE TITLE
Textfield fullwidth placeholder text disappears on focus instead of on keydown

### ISSUE THREAD

**Issue by djensen47** [material-components/material-components-web#1505]
According to the Material design spec, "Placeholder text can be displayed in an empty text field until input is entered." Also, "As the user types into the text field, input text replaces any placeholder text."

When there is a fullwidth textfield with a placeholder, it currently clears the placeholder on focus. The expected result is that the placeholder stays until the use starts typing input.

**Comment by dessant** [comment]
I can confirm this behavior. It seems to be a regression, the placeholder stays visible on focus with textfield 0.4.1.

**Comment by lynnjepsen** [comment]
Looks like a bug! Thanks for filing.

For posterity, here is a codepen reproducing the issue:
https://codepen.io/anon/pen/KydoyJ

**Comment by djensen47** [comment]
I found the issue. The wrong color is being assigned to :focus::placeholder

here:
https://github.com/material-components/material-components-web/commit/45c6cf68aad9a0985b1ca0b4ad81ed466298809f#diff-0d82c2a11524792f13f48f99ef46fd4cL69

and here
https://github.com/material-components/material-components-web/commit/45c6cf68aad9a0985b1ca0b4ad81ed466298809f#diff-0d82c2a11524792f13f48f99ef46fd4cL86

Then take a look at https://github.com/material-components/material-components-web/blob/251338e5812461df6fa717c40b68b5d21e291806/packages/mdc-textfield/_variables.scss#L35

Those values are light text on a light background and dark text on a dark background.

---
The previous values are still around. For instance, the **light** theme used to use ` rgba(black, .54)`:
https://github.com/material-components/material-components-web/blob/57581edc4f643e39c0bcfffa95bab4ffde68b865/packages/mdc-theme/_variables.scss#L132

And the **dark** theme used to use `rgba(white, .7)`
https://github.com/material-components/material-components-web/blob/57581edc4f643e39c0bcfffa95bab4ffde68b865/packages/mdc-theme/_variables.scss#L138

**Comment by djensen47** [comment]
@lynnjepsen I can submit a PR.

I'm not sure what @amsheehan was intending to do but my _guess_ is that those colors should be swapped.

 ```
$mdc-textfield-light-placeholder: rgba(black, .38);
$mdc-textfield-dark-placeholder: rgba(white, .3);
```

Or the values used in the :focus::placeholder should be swapped.

Thoughts?

**Comment by djensen47** [comment]
I generally like to follow the guideline of asking before making a PR.  😄 

Or should I just submit a PR and discuss the fix in the PR? 

(still waiting on any sort of response, thanks)

**Comment by appsforartists** [comment]
There are two components in the full-width section [of the demo](https://material-components-web.appspot.com/textfield.html).  The text area has the `upgraded` classes and a label that moves above the form control when text is entered.  The text field does not.  I'm guessing someone forgot to connect the JS controller to the text field.

**Comment by djensen47** [comment]
Actually it's as simple as I laid out. Focus causes the placeholder to
change to a color that can't be seen: white text on white background, black
text on a dark background.

I verified this behavior in the browser code inspector as well as in the
mdc codebase.

What you mention might _also_ be a bug but a different one.

**Comment by djensen47** [comment]
I have a work around in place that works on my system. I changed the color of `:hover::focus` and it works. This is essentially the fix I have proposed.

It's a simple fix and I'm still willing to pitch in with a PR but still haven't heard from the team on this so I'm stuck. If the team says, "no we'll take care of it," that's cool too. I'd just like to know one way or another.
