### ISSUE TITLE
Webpack Dependency Malfunction

### ISSUE THREAD

**Issue by xinxiao** [material-components/material-components-web#1509]
Using version 0.24.0 with webpack would result following error

@include mdc-ripple-surface;
          ^
      No mixin named mdc-ripple-surface

Can someone help me with this?

**Comment by kfranqueiro** [comment]
A couple of preliminary questions:

* Have you successfully used earlier versions of MDC Web in the same setup, or is this your first time trying it?
* Is your `node_modules` directory is present in Sass's include paths?

**Comment by xinxiao** [comment]
Yes. Everything works perfectly when I was still using 0.23.0 this afternoon. Here is my config for sass loader

 56     test: /\.(css|scss|sass)$/,
 57         use: [
 58                { loader: 'style-loader' },
 59                { loader: 'css-loader' },
 60                {
 61                  loader: 'sass-loader',
 62                  options: {
 63                    includePaths: ['node_modules']
 64                  }
 65                }
 66              ]

**Comment by xinxiao** [comment]
And my custom scss has the dependency handling part looks like this

```sass
@import "@material/typography/mdc-typography";
@import "@material/toolbar/mdc-toolbar";
@import "@material/button/mdc-button";
@import "@material/list/mdc-list";
```

**Comment by xinxiao** [comment]
@kfranqueiro Hi Kenneth, I have had the problem solved. As your team updating the ripple mixing effects, I had some dependencies left out as previous version in the package. After updating all the modules, the problem is solved. Please make a note to have people updating all material packages if any particular module is to be updated to 0.24.0. Thank you!
