### ISSUE TITLE
Snackbar button has no left padding

### ISSUE THREAD

**Issue by dessant** [material-components/material-components-web#1510]
### What is the expected behavior?

The snackbar button should have a left padding which follows the specs.

Mobile: 24dp
![screenshot from 2017-10-31 03-49-42](https://user-images.githubusercontent.com/7513068/32203988-51026f38-bdef-11e7-9a65-7cfdb70dfb96.png)

Tablet/desktop: 48dp
![screenshot from 2017-10-31 03-51-37](https://user-images.githubusercontent.com/7513068/32203991-5cd188d0-bdef-11e7-8c9d-001ac7444c4c.png)

### What is the actual behavior?

The snackbar button has no left padding.
![screenshot from 2017-10-31 03-36-20](https://user-images.githubusercontent.com/7513068/32204023-926762bc-bdef-11e7-99c7-05e8958fe01c.png)

**Comment by lynnjepsen** [comment]
Looks like a bug! Thanks for filing. Would you like to submit a PR for it?
