### ISSUE TITLE
MDC-Select adapter recommended implementation 

### ISSUE THREAD

**Issue by asiop** [material-components/material-components-web#1516]
I think that a better solution than what suggested in the docs might be be this - this would return the coordinates relative to a relatively positioned element, and so would work well  also when the element is situated in dialog box:

    function computeBoundingRect() {
        return {
            top: component.rootNode.offsetTop,
            left: component.rootNode.offsetLeft
        }
    }

**Comment by lynnjepsen** [comment]
Are you having issues with an MDC Select within an MDC Dialog? Could you provide a codepen?

**Comment by asiop** [comment]
No issue with the source, it works as expected, the issue is in the adapter documentation of the select component. 

What is suggested there would not work well if the element was placed in a relative positioned div like within a dialog box, I suggested an alternative function.

**Comment by asiop** [comment]
here:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-select

Instead of the text "The easiest way to achieve this is by calling getBoundingClientRect() on the root element." I'd write, "The easiest way to achieve this is by returning an object with the top property set to the  offsetTop of the root element and the left property with the offsetLeft of the root element". Less intuitive but works in more cases, could save an average developer (like myself) about an hour :)

**Comment by kfranqueiro** [comment]
This is potentially more than just a documentation issue, though, since that suggestion in the documentation matches the implementation in the DOM adapter included in the OOTB MDC Select component. This is why we figured perhaps you saw this manifest as a bug.

**Comment by asiop** [comment]
Makes sense, perhaps it is a real bug then. I haven't seen it in the code, I debugged someone else's react adapter when I found it. However setting codepen with react sample presently is a bit of a learning curve for me.

**Comment by kfranqueiro** [comment]
I'm definitely curious to see it reproduced; we use `position: fixed` on the select's menu, which _should_ make it relative to the body, which in turn should mean that `getBoundingClientRect` should be the correct solution, and I'd be concerned that relying on `offsetTop` and `offsetLeft` could actually break cases.

Here's a (maybe-too-trivial?) case where I tried to repro the problem but couldn't: https://codepen.io/kfranqueiro/pen/rYxyLx

**Comment by asiop** [comment]
I'm not sure what's the difference between your example and this fork I made with a dialog component.

https://codepen.io/anon/pen/xPZdZj?editors=1010

In your example the coordinates of the menu are calculated from the top left corner, and on mine they are relative to the dialog surface.

**Comment by kfranqueiro** [comment]
Huh. I wonder if it has to do with select's menu and the dialog both being `position: fixed` then.

**Comment by izakfilmalter** [comment]
It has to do with the `transform`. Find out more here: https://developer.mozilla.org/en-US/docs/Web/CSS/transform

Basically `transform` resets the stacking context of it's children. So `position: fixed` is relative to a parent with a `transform`.
