### ISSUE TITLE
@material/typography SCSS mdc-typography-style mixin not existent

### ISSUE THREAD

**Issue by sk22** [material-components/material-components-web#152]
## issue
According to @material/typography's [README.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-typography/README.md), there's a mixin named `mdc-typography-style`. However it does not exist in [_mixins.scss](https://github.com/material-components/material-components-web/blob/master/packages/mdc-typography/_mixins.scss). But there is a mixin named `mdc-typography` on [line 28](https://github.com/material-components/material-components-web/blob/master/packages/mdc-typography/_mixins.scss#L28).

## reproduction
1. create new folder
2. `yarn init`
3. `yarn add --dev node_sass@4.1.1`
4. `yarn add @material/typography@0.1.0`
5. create a styles.scss

```scss
@import "@material/typography/mdc-typography";

p {
  @include mdc-typography-style(headline);
}
```

6. watch it fail: `node_modules\.bin\node-sass --include-path node_modules styles.scss > styles.css`

```json
{
  "status": 1,
  "file": "C:/Users/samuel/Code/school/tinf/sem03/proj01/test/styles.scss",
  "line": 4,
  "column": 12,
  "message": "no mixin named mdc-typography-style\n\nBacktrace:\n\tstyles.scss:4",
  "formatted": "Error: no mixin named mdc-typography-style\n\n       Backtrace:\n       \tstyles.scss:4\n        on line 4 of styles.scss\n>>   @include mdc-typography-style(headline);\n   -----------^\n"
}
```

7. change styles.scss

```scss
@import "@material/typography/mdc-typography";

p {
  @include mdc-typography(headline);
}
```

8. watch it work: `node_modules\.bin\node-sass --include-path node_modules styles.scss > styles.css`

## possible fix
Due to this, I'd either change `mdc-typography-style` to `mdc-typography` in the README, or change the `_mixins.scss` (which would break existing includes.)

## workaround
Using `mdc-typography` instead of `mdc-typography-style` in the own scss files.

**Comment by sgomes** [comment]
Thank you for the thorough bug report, @sk22! It does appear that the documentation is wrong on this one; we changed the mixin name without updating the docs.
