### ISSUE TITLE
framework integration criteria (vuejs)

### ISSUE THREAD

**Issue by stasson** [material-components/material-components-web#1521]
Hello MDC Team

I have been working on this vuejs integration project: [vue-mdc-adapter](https://stasson.github.io/vue-mdc-adapter) for the last 6 month. I must say I have been very impressed by the work you guys do. I think my project has reached a point where it may be worth sharing. 

vue-mdc-adapter is using the foundation aproach. Goal is to use Vue's reactivity system wherever It make sense, and keep the markup/apis as simple and as close as possible to MDC. For now I have been mostly focused on figuring out the right vue patterns and get a first working implementation of each component. I guess next comes api refining and a big validation phase. if the project takes off, I'll have to take care of the perf as well.  

There are a couple of integration tricks and issues I found while integrating. I guess I'll gather my notes and share it with you. Are github issues the preferred way to send you some feedback ?

Also today I'm wondering If I should do a PR and add my library to your list of integrations: I definitely need some feedback on the api's  and it may help me find people who'd contribute... I went through the [criteria](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md) and I'm not sure about the following statement: 
> - Serve components in an à-la-carte delivery model  

As of today I have only one package. people can cherry pick es6 components using webpack/rollup, but I didn't create one npm package per component. Do I need to do so to meet the criteria ? 

thxs for your feedback.

**Comment by lynnjepsen** [comment]
Go ahead and start a PR, and you'll get some Vue experts from our community to comment on your PR. We can work through the "a la carte" part with the Vue experts as well.

**Comment by anlexN** [comment]
i don’t want to use any framework integration or wrapper!
[How to use material-components-web?](https://forum.vuejs.org/t/how-to-use-material-components-web/78469)
