### ISSUE TITLE
Help with customizing mdc-theme colors

### ISSUE THREAD

**Issue by Frame1910** [material-components/material-components-web#1527]
I could just use some help with changing the default theme colors to custom colors. I am new to the theming part of MDC.

For some reason, with whatever method I use, I cannot change my themes to my own colors.
I have tried `:root`
`:root {
    --mdc-theme-primary: #4e0087;
    --mdc-theme-secondary: #fff;
    --mdc-theme-background: #000;
}`
I have tried SASS 
`$mdc-theme-primary: #9c27b0; // Purple 500
$mdc-theme-secondary: #ffab40; // Orange A200
$mdc-theme-background: #fff; // White`

And i have tried SASS mixins
`body {
    --mdc-theme-primary: #9c27b0;
}`

[Palm-Paradise-Web.zip](https://github.com/material-components/material-components-web/files/1436439/Palm-Paradise-Web.zip)

I just can't figure it out, any help would be much appreciated to a budding web designer :)

**Comment by touficbatache** [comment]
Hey @Frame1910, to fix this just put the `<link href="styling.css" rel="stylesheet">` tag after the `<link rel="stylesheet" href="node_modules/material-components-web/dist/material-components-web.css">` one, not before it. Then, you can use 
```
:root {
    --mdc-theme-primary: #9c27b0;
    --mdc-theme-secondary: #ffab40;
    --mdc-theme-background: #fff;
}
```

**Comment by touficbatache** [comment]
And yes, forgot to mention, you can remove the @import from your `styling.css` file.

**Comment by Frame1910** [comment]
And on a seperate note, a couple other components from MDC don't seem to
work for me either, it's probably the same problem of referencing... But
it's menus and dropdown inputs that also do not work, I'll get more info on
it and maybe make a new issue on it if that's the case. Mdc's components
just look so clean and pleasing to all my clients and they want to use
them, but they don't work for me.

**Comment by touficbatache** [comment]
You can read the README for every component so you know how it works. If
you're still struggling, there is [a demo page](
http://material-components-web.appspot.com) where you can see all the
components in action. If you need more help, feel free to reply here.

**Comment by Frame1910** [comment]
Ok so I tried what you said and.. it worked. Hooray! Thanks for the help.
I'll get back to you about the other components, I have looked at the usage
instructions and did everything to the letter, but like I said it might be
a load order issue like the other one.

**Comment by thebrightestday** [comment]
There are rules how to use CSS.
This solution from @touficbatacheis basically a cascading rule. Maybe you should read this first:
https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance
