### ISSUE TITLE
Initial value of linear progress component

### ISSUE THREAD

**Issue by corneschouten** [material-components/material-components-web#1528]
### What MDC-Web Version are you using?

> 0.24.0

### What browser(s) is this bug affecting?

> All

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

> https://codepen.io/corneschouten/pen/RjWOay
> The solution is already applied in the CSS area of the codepen.

### What is the expected behavior?

> Start the linear progress with an initial value of 0%. 
> This could be easily achieved by adding the following css:
> `.mdc-linear-progress__primary-bar { transform: scaleX(0); }`

### What is the actual behavior?

> The linear progress starts with an initial value of 100% .

**Comment by lynnjepsen** [comment]
The initial value should of linear progress should definitely be 0%. Thanks for filing!
