### ISSUE TITLE
Linear Progress resets bar width when `determinate` is set to `false`

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#1531]
### What MDC-Web Version are you using?

> 0.24.0

### What browser(s) is this bug affecting?

> All

### What OS are you using?

> All

### What are the steps to reproduce the bug?

> 1. View the [Linear Progress demo page](http://material-components-web.appspot.com/linear-progress.html)
> 2. Run this snippet in the dev tools console:
>     ```js
>     var pb = mdc.linearProgress.MDCLinearProgress.attachTo(
>       document.querySelectorAll('.mdc-linear-progress')[1]);
>     pb.progress = .5;
>     pb.determinate = false;
>     pb.determinate = true;
>     ```
> 3. Observe the width of the progress bar

### What is the expected behavior?

> `.mdc-linear-progress__primary-bar` should have `transform: scaleX(0.5)` (50% width).

### What is the actual behavior?

> `.mdc-linear-progress__primary-bar` has `transform: scaleX(1)` (100% width).

### Any other information you believe would be useful?

I believe this is due to the foundation:

```js
  setDeterminate(isDeterminate) {
    this.determinate_ = isDeterminate;
    if (this.determinate_) {
      this.adapter_.removeClass(cssClasses.INDETERMINATE_CLASS);
    } else {
      this.adapter_.addClass(cssClasses.INDETERMINATE_CLASS);
      this.setScale_(this.adapter_.getPrimaryBar(), 1);
      this.setScale_(this.adapter_.getBuffer(), 1);
    }
  }
```

When `determinate` is set to `true`, we should restore the scale value from the `progress` property.

We should also explicitly store the value of `progress` separately from scale, and expose getters for all the properties that we currently have setters for. It seems odd to have setters but no getters.

**Comment by lynnjepsen** [comment]
setting a text field to the indeterminate state should reset the value to 0%. So this looks like a bug
