### ISSUE TITLE
Add z-index to temporary drawer

### ISSUE THREAD

**Issue by sk22** [material-components/material-components-web#154]
By default, the temporary drawer does not have a z-index. This allows e.g. buttons underneath the drawer to be visible above.

As an example, in the Vue.js framework example the z-index is set by hand: https://github.com/material-components/material-components-web/blob/master/framework-examples/vue/src/App.vue#L8

I think the temporary drawer should by default have a higher z-index than anything else, at least I don't see why it shouldn't.

**Comment by vitaliy-bobrov** [comment]
Also it'll be great to store all z-index values with sass/css variables, to keep track on them and control from one place.

**Comment by traviskaufman** [comment]
Thanks for opening this. Temporary drawers should definitely have a z-index. Marking as a bug.

**Comment by amsheehan** [comment]
Alright, @traviskaufman and I bounced a few ideas that were spawned from this issue regarding handling z-index for MDC Web. I will preface this by saying there's nothing out of control with how we currently use z-index in the code base, so both of these options are presented with the purpose of stimulating conversation around how we may handle this in the future.

**1: Create a Z-Index package to govern z-index across MDC Web**

In this scenario, we use sass lists as a way to declare stacking order for components. In the component's scss file, we would use the index of that package in its list to assign z-index. eg:

_mdc-stack-order/_variables.scss_
```
$stack-order: card, drawer, dialog-box;
```

_mdc-whatever/component.scss_
```
@import @material/mdc-stack-order/variables

.mdc-card {
  z-index: index($stack-order, card);
}

.mdc-drawer {
  z-index: index($stack-order, drawer);
}

.mdc-dialog {
  z-index: index($stack-order, dialog-box);
}
```

Pros: This allows us to control the z-indices (?) of all of our packages in one central location using sass lists and `index()`

Cons: Adds another package, currently there is nothing in the code base or planned work that is sufficiently complex enough to warrant such measures.


**2: Extend MDC Elevation to include a mixin that returns z-index values based on elevation**

This is pretty straight forward, we would have a list of elevations that a mixin would use to return a z-index based on the predefined order from that list. In other words there's a many:1 mapping of elevations to stacking orders.

Pros: Extends elevation, makes sense to base stacking on elevation

Cons: Nothing in the code base really warrants this yet. Some components may not have elevation, but should still be stacked higher than others, like the temp drawer.
