### ISSUE TITLE
[Bug]  Internal module import/export error (lacking export)

### ISSUE THREAD

**Issue by chewzerita** [material-components/material-components-web#155]
### What MDC-Web Version are you using?

0.1.1

### What browser(s) is this bug affecting?

Electron 1.4.13, unrelated to issue.

### What OS are you using?

Arch Linux, kernel release: 4.8.13-1-ARCH

### What are the steps to reproduce the bug?

I'm using rollup to bundle everything into one ECMAScript module
You don't need to recreate the bug to see why it doesn't work

1. [setup rollup](https://code.lengstorf.com/learn-rollup-js/), install: postcss plugin (probably optional), material-compontents-web
2. In JS `import * as mdc from "material-components-web";`
3. `node_modules/@material/drawer/temporary/constants.js` doesn't export `numbers` as imported by `node_modules/@material/drawer/temporary/foundation.js`

### What is the expected behavior?

I expect all the imports and exports of the inner modules to be fulfilled.

### What is the actual behavior?

The `@material/drawer/temporary/constants.js` doesn't export `numbers` a constant that `@material/drawer/temporary/foundation.js` trys to import from it

>Error: 'numbers' is not exported by node_modules/@material/drawer/temporary/constants.js (imported by node_modules/@material/drawer/temporary/foundation.js).

**Comment by sgomes** [comment]
@chewzerita Good catch! It looks like there are no number constants being exported, but the foundation still tries to import them.
