### ISSUE TITLE
MDCTextfieldFoundation public method "setValid" isn't documented

### ISSUE THREAD

**Issue by anton-kachurin** [material-components/material-components-web#1550]
The `setValid` method is mentioned in the "MDCTextfield API" section:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#mdctextfieldvalid

But it also needs some description in the "foundation API" section:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#the-full-foundation-api

**Comment by lynnjepsen** [comment]
Looks like a bug! We're adding some documentations in #1543
