### ISSUE TITLE
MDCTextfield, mdc-textfield__label--shake isn't unit tested

### ISSUE THREAD

**Issue by anton-kachurin** [material-components/material-components-web#1551]
### What MDC-Web Version are you using?

0.24.0

--------------------------------------------------

Having some formal tests for Textfield label's shaking (`LABEL_SHAKE` as it's referred to in `constants.js`) would help a lot while adding features/fixing bugs in MDCTextfield.

**Comment by lynnjepsen** [comment]
We should have some more test coverage around LABEL_SHAKE, especially around focus/blur. And around the validity (valid/invalid + custom/default validity test cases). Would you like to create a PR?

**Comment by anton-kachurin** [comment]
I would love to help but I'm unfamiliar with this feature. Would you suggest some specific testcases?

Such as:
- If using default validity, the class must be added to the component when switching from focused to unfocused if the validity test fails
- If using default validity, the class must not be added to the component when switching from focused to unfocused if the validity test doesn't fail
- If using custom validity...
- etc
