### ISSUE TITLE
Update MDC Text field to use mdc-states-color

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1558]
Use the mdc-states-color mixin created in #1556

MDC Text field already uses mdc-ripple-color mixin:
https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/mdc-textfield.scss#L167

this should be replaced with the new mdc-states-color mixin, with any relevant opacity tweaks.

**Comment by kfranqueiro** [comment]
Implemented in #1677
