### ISSUE TITLE
Update MDC Icon Toggle to use mdc-states-color

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1561]
Use the mdc-states-color mixin created in #1556

MDC Icon Toggle already uses mdc-ripple-color mixin:
https://github.com/material-components/material-components-web/blob/master/packages/mdc-icon-toggle/mdc-icon-toggle.scss#L41

this should be replaced with the new mdc-states-color mixin, with any relevant opacity tweaks.

**Comment by kfranqueiro** [comment]
We should also migrate the demo styles to scss and use `mdc-states-color` there to apply the correct opacity styles for the varying-color demo cases.

**Comment by kfranqueiro** [comment]
Implemented in #1685
