### ISSUE TITLE
Update MDC Fab to use mdc-states-color

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1562]
Use the mdc-states-color mixin created in #1556

MDC Fab already uses mdc-ripple-color mixin:
https://github.com/material-components/material-components-web/blob/master/packages/mdc-fab/_mixins.scss#L30

this should be replaced with the new mdc-states-color mixin, with any relevant opacity tweaks.

**Comment by kfranqueiro** [comment]
Implemented in #1669.
