### ISSUE TITLE
Persistent Drawer cuts off menu items on small height screens

### ISSUE THREAD

**Issue by anton-kachurin** [material-components/material-components-web#1578]
### What MDC-Web Version are you using?

0.24.0

### What browser(s) is this bug affecting?

All (tested on Chrome, Firefox, Edge)

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. https://material-components-web.appspot.com/drawer/persistent-drawer.html
2. Open the drawer.
3. Reduce the height of your browser's window.

### What is the expected behavior?

A scroll bar should appear allowing to see all menu items.

### What is the actual behavior?

Some of the menu items are invisible.

**Comment by amsheehan** [comment]
We'll have to reach out to design on this one. Obviously not allowing the user to access these menu items is an oversight, we just need to nail down if we want the drawer to scroll on its own, or to scroll the whole page, letting the height of the content in the drawer dictate the minimum height of the rest of the page.

**Comment by MSbitani** [comment]
I just came across this issue. I believe you also need to set `touch-action: pan-y` in the same file to support touch input.

**Comment by abhiomkar** [comment]
Closing this as obsolete.
