### ISSUE TITLE
How to use MDC with VueJs?

### ISSUE THREAD

**Issue by Yapryntsev** [material-components/material-components-web#1579]
I have some problem with understanding how exactly use MDC in Vue component.
For example, I have result file `app.js` where I connect MDC

    window.mdc = require('material-components-web')

and then I register the component

    Vue.component(
      'social-auth',
      require('./blocks/social-auth/social-auth.vue')
    );

So, for example, in this component I want to use `mdc-menus`, what i should do next?

**Comment by MishUshakov** [comment]
Consider using this adapter https://github.com/stasson/vue-mdc-adapter

**Comment by Yapryntsev** [comment]
@MishUshakov Thank you so much. That's what I need.

**Comment by anlexN** [comment]
i don’t want to use any framework integration or wrapper!
[How to use material-components-web?](https://forum.vuejs.org/t/how-to-use-material-components-web/78469)
