### ISSUE TITLE
 Error: (mdc-auto-init) Could not find constructor in registry for MDCTextField

### ISSUE THREAD

**Issue by ALMaclaine** [material-components/material-components-web#1582]
### What MDC-Web Version are you using?
I can't find it, it's not in package.json, but since the last update on 11/9.

### What browser(s) is this bug affecting?
At least chrome, firefox and safari.

### What OS are you using?
macOs Sierra

### What are the steps to reproduce the bug?
I'm not 100% sure, I think having `data-mdc-auto-init="MDCTextField"` and trying to call autoinit().

### What is the expected behavior?
No error I presume.

### What is the actual behavior?
It is throwing an error when `data-mdc-auto-init="MDCTextField"` is used.

```
material-components-web.js:2401 Uncaught Error: (mdc-auto-init) Could not find constructor in registry for MDCTextField
    at Object.mdcAutoInit (material-components-web.js:2401)
    at test.html:16
```

### Any other information you believe would be useful?
The code that generated this error was from the repo, it's in the Quick Start in the readme 

https://github.com/material-components/material-components-web/#quick-start

and again in the component folder readme:

https://github.com/material-components/material-components-web/tree/master/packages/mdc-auto-init

And throughout the material.io page:

https://material.io/components/web/docs/getting-started/

Thanks.

**Comment by anton-kachurin** [comment]
Please try updating your cloned repo, worked for me.

Alternatively, use `data-mdc-auto-init="MDCTextfield"` in your HTML, but keep in mind that this will break soon.

`MDCTextfield` (lower-case "field") is the current release
`MDCTextField` (upper-case "Field") is the master branch

#1485 which is a breaking change was merged into master and updated all documentation on GitHub. 
https://material.io/components/web/docs/getting-started/ still refers to the current release version 0.24.0 and the example from it should work fine. 

Note that examples on GitHub read `data-mdc-auto-init="MDCTextField"` while the ones on material.io read `data-mdc-auto-init="MDCTextfield"`.

**Comment by mikegleasonjr** [comment]
Also pay attention the CSS classes changed too...

**Comment by jeffsmithsailing** [comment]
My forms blew up yesterday and I just discovered this issue this morning. I investigated using MDCTextfield syntax but found it was already set to that. Here is what my form looks like now. 
![floatinglabeldefect](https://user-images.githubusercontent.com/6164965/32797323-4a6a1ad0-c926-11e7-8b0f-d19fcd8af4a0.PNG)


Dreamweaver is throwing the same error referenced above.
![js issue](https://user-images.githubusercontent.com/6164965/32797260-0729aec0-c926-11e7-859f-b7e563efcf49.PNG)

**Comment by MYoung25** [comment]
#1587 @DjSloth's reply worked for me:
```
instead of latest:
https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css

<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
get the previous version :
https://unpkg.com/material-components-web@0.24.0/dist/material-components-web.min.css

<script src="https://unpkg.com/material-components-web@0.24.0/dist/material-components-web.min.js"></script>
they broke the class interface(spelling of the class) from
window.mdc.textfield.MDCTextfield to window.mdc.textfield.MDCTextField
```

**Comment by jeffsmithsailing** [comment]
Thanks @MYoung25  - that helped with the layout but the floating label animation is still broken. The labels do not rotate up. And the Select no longer displays its list...
![floatingnotfloating](https://user-images.githubusercontent.com/6164965/32801762-d8462464-c932-11e7-8b74-04682efc3aaf.PNG)

**Comment by kfranqueiro** [comment]
This is most likely related to renaming text field, which is in the 0.25.0 release. Listed in breaking changes:

> **text-field:** CSS class name "mdc-textfield" is changed to "mdc-text-field", JS objects name "MDCTextfield" is changed to "MDCTextField", .scss file names "mdc-textfield.scss" is changed to "mdc-text-field.scss", global namespace "mdc.textfield" is changed to "mdc.textField". Note that the package name is unchanged.

I would suspect that the lack of floating labels may also be related to a similar javascript error. Can you check if there is still an error in your console, or create a [codepen](https://codepen.io/traviskaufman/pen/pNQmRp) demonstrating the issue? Thanks!

**Comment by jeffsmithsailing** [comment]
@kfranqueiro here is the link to the pen. I have a form with a bunch of floating label text fields that worked perfectly Friday and was broken Monday. See the screen shot above. I went back to release 24 as called out above and the format was fixed but the field still does not animate. when you type into the field you overwrite the label :-(

https://codepen.io/jeffreysmithixd/pen/RjjRoN
