### ISSUE TITLE
Split up the "variants" CSS classes in text field into private mixins

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1599]
Part of our effort to split text field to reduce merge conflicts and generally improve the readability of text field code.

Should include:
* mdc-text-field--textarea
* mdc-text-field--full-width
* mdc-text-field--box
* mdc-text-field--leading-icon
* mdc-text-field--trailing-icon

**Comment by bonniezhou** [comment]
Resolved by #1862, #1885, #1899, #1942, #1964, #1988, #2050, #2051, #2053, #2054, #2055, #2057, #2068, #2071.
