### ISSUE TITLE
Update outlined text field to handle leading and trailing icon

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1602]
Update outlined text field to handle leading and trailing icon. This is a CSS update. (I don't think there are any JS involved here....)

**Comment by kfranqueiro** [comment]
FYI there is some JS involved in emitting an event when the leading/trailing icon is interacted with. It is currently handled from a listener at the root of the component.

https://github.com/material-components/material-components-web/blob/b12c5769f1bd1cd44c59644009a004b74a075b70/packages/mdc-textfield/foundation.js#L147
