### ISSUE TITLE
Notification when snackbar closes?

### ISSUE THREAD

**Issue by robcaldecott** [material-components/material-components-web#1603]
Is there any way to know when an mdc-snackbar has closed (because the timeout expired)? I am using this component in a React application and need to handle state updates when the snackbar is no longer visible but I cannot find a reliable way to do this other than a separate timer which seems a bit delicate. 

Ideally we would be able to listen for a special event triggered when the mdc-snackbar closes, in the same way as we do for the mdc-dialog comoponent, e.g.:

```js
this.MDCComponent = new MDCSnackbar(myDOMElement);
this.MDCComponent.listen("MDCSnackbar:close", myCloseHandler);
```

If there is a way to coerce the component into doing this with some adapter magic then that would be great but I could not see anything obvious in the docs.

**Comment by kfranqueiro** [comment]
Snackbar doesn't currently emit any events, but this sounds like a reasonable request. Would you be interested in working on a pull request for this?

There are a number of other components which you can look at for reference on how we handle emitting custom events. mdc-icon-toggle's `notifyChange` might be an easy one to look at as an example.
