### ISSUE TITLE
Remove events from persistent drawer

### ISSUE THREAD

**Issue by Rickyfs** [material-components/material-components-web#1614]
I want to add some extra features into mdc-persistent-drawer however there is events like pointerup, pointerdown, click, pointermove. These are completely useless and I cant find way to remove them. Tried to unbind, .off, override but no luck.

**Comment by kmmbvnr** [comment]
Yep, I have to remove click listener also.

I guess Pointer/Scroll events disabling added in order to stop main page content from scrolling.
Have no idea, why disabling clicks are required.

```
var persistentDrawer = new drawer.MDCPersistentDrawer(...)
var drawer = persistentDrawer._root_.querySelector('nav')
drawer_.removeEventListener('click', persistentDrawer.foundation_.drawerClickHandler_)
```

**Comment by amsheehan** [comment]
@Rickyfs why do you have to remove these event handlers?

**Comment by Rickyfs** [comment]
I want to customize drawer with various elements and for example if I want to add fancier list then elemenets in list wont be clickable (gray background on mousedown...)

**Comment by bonniezhou** [comment]
We will be removing the `drawerClickHandler_` which currently stops propagation of the click event. This is being done in #1138, similar discussion on #1004.
