### ISSUE TITLE
Superfluous "-" in Documentation, i.e., .mdc-text-field vs mdc-textfield

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#1616]
At: https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield

> `mdc.textField.MDCTextField.attachTo(document.querySelector('.mdc-text-field'));`

should be

> `mdc.textField.MDCTextField.attachTo(document.querySelector('.mdc-textfield'));`

I'm [truly enjoying myself](https://www.youtube.com/watch?v=w2D4iCzRW7E).

**Comment by rhroyston** [comment]
Here too:
(all thru the page)
https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md

**Comment by RobJacobs** [comment]
mdc -textfield was refactored to mdc-text-field under PR #1485

**Comment by rhroyston** [comment]
That little extra dash is almost as bad as a space character. 👍

**Comment by amsheehan** [comment]
As @RobJacobs mentioned, we did a large refactor of MDC Text Field. 

We did this because the other platforms in MDC refer to MDC Text Field, not MDC Textfield (like we were). Also, upon further inspection, we could not find many other popular frameworks or libraries that did not use TextField, Text Field, text-field, or text_field.

**Comment by rhroyston** [comment]
Got it. People might copy/paste code and catching that extra dash might take them hours; like playing Where's Waldo. Just sayin re the documentation, especially the "Getting Started" section. It's difficult to see that -.

**Comment by rhroyston** [comment]
The usage of MDC-Web is made far more complicated than it should be bcs of the extra "-". Is it "textfield" or "text-field"? This leads to time wasted troubleshooting a "-". See the upgraded class spelling too...

![image](https://user-images.githubusercontent.com/12751611/33139701-aff541ce-cf73-11e7-9e07-31aaf3e80b3b.png)

**Comment by rhroyston** [comment]
Wait, OK so it's `mdc-text-field` and NOT `mdc-textfield`... Ok so don't you need to update the package name to be `mdc-text-field`?
