### ISSUE TITLE
Dynamically Populated Input Element Re-Positioning on Value Clear

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#1617]
[Here's the codepen](https://codepen.io/rhroyston/pen/MOrMWb).

Notice how the textfield re-positions itself after dynamically/programatically clearing the field, whether disabled or not.  

Also, the smooth (CSS transition I asssume) seems to die on clearing the input value and removing the mdc classes programatically.

I hope this issue isn't nit picky but it just seems like the display could be flexboxed out such that the UI would not shift on clearing the input.

**Comment by amsheehan** [comment]
It looks like you're removing `mdc-text-field--upgraded`. Commenting out that line fixed the issue in the Codepen.

**Comment by rhroyston** [comment]
Thanks. OK. I guess I thought one was supposed to remove the `upgraded` class on clearing the input.
