### ISSUE TITLE
Error: material-components-web.min.js:38 Uncaught TypeError: Cannot read property 'querySelector' of null     at e.value (material-components-web.min.js:38)     at e.t (material-components-web.min.js:6)     at new e (material-components-web.min.js:38)     at index.html:146

### ISSUE THREAD

**Issue by jeffsmithsailing** [material-components/material-components-web#1618]
### What MDC-Web Version are you using?
"latest" 0.25.0 via <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script> 
> Please be specific, e.g. _major.minor.patch_

### What browser(s) is this bug affecting?
Doing my debugging in Chrome. Will test in others when I get this issue fixed.
> Please include the browser version. A user-agent string is also quite helpful.
Version 61.0.3163.100 (Official Build) (64-bit)

### What OS are you using?
Windows 10
> Please include the OS version.
10.0.15063 Build 15063
### What are the steps to reproduce the bug?
I am attempting to create a prototype of the MDC-Web tab control using the code at https://material.io/components/web/catalog/tabs/#script. Specifically, I am trying to create a tab bar with icons and text labels.

![image](https://user-images.githubusercontent.com/6164965/33037196-98a494fa-cde5-11e7-982f-d16a4f87e779.png)

The page loads and the tabs are presented, but only the active tab is enabled. The other tabs do not respond. I will create a CodePen illustrating the issue. 

![image](https://user-images.githubusercontent.com/6164965/33037153-7d4ee53e-cde5-11e7-893b-6cda5cdbe407.png)

At http://material-components-web.appspot.com/tabs.html#nearby I found that the syntax for the JS src is <script src="/assets/material-components-web.js"></script> in contrast to <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>  which is in the demo site. The sample for Icon & Text Labels works perfectly although the sample immediately below [CSS-only icon & text labels] is not working and is displaying the same behavior as my prototype.
![image](https://user-images.githubusercontent.com/6164965/33037101-5050ac5c-cde5-11e7-8096-aad830d3d200.png)

I believe the problem is related to the new version of the CSS (0.25.0) released last week.

Here is the CodePen illustrating the problem:
https://codepen.io/jeffreysmithixd/pen/yPvKmP

### What is the expected behavior?
The sample code on the demo site works and I can create a functioning prototype of the tab control.

> Please describe what the component/code should be doing that it's not.
The active tab is in focus and the other tabs cannot be selected.

### Any other information you believe would be useful?
Hopefully this is not a duplicate - I searched but found older instances of issues with the querySelector error that were closed.

**Comment by amsheehan** [comment]
It looks like there are a few errors in the Codepen. If you notice, there's a red icon with an exclamation point. Clicking that should reveal the errors in the pen.

Please clean those up and let us know if the issue still exists.

**Comment by jeffsmithsailing** [comment]
I moved the autoinit over to the HTML pane. The remaining JS is from the MDC-Web site. That is what is not working.
