### ISSUE TITLE
Drawer Component detaching event handlers for embedded links

### ISSUE THREAD

**Issue by jonhue** [material-components/material-components-web#1619]
### What MDC-Web Version are you using?

0.24.0

### What browser(s) is this bug affecting?

Chrome (Version 62.0.3202.94 (Official Build) (64-bit))

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

-> https://codepen.io/anon/pen/wPyxNG

### What is the expected behavior?

Opening a link which is embedded in the drawer 'remotely' should work as well as it does if it lives outside of it.

### What is the actual behavior?

Links inside the drawer with `data-remote="true"` don't work as expected, whereas a regular link outside of the component works well.

**Comment by amsheehan** [comment]
Though not the focus of this issue, there is another [Github issue](https://github.com/material-components/material-components-web/issues/579) that mentions a library called [Turbolinks](https://github.com/turbolinks/turbolinks) (I'm not a RoR expert, forgive me) that has the same issue.

@jamesmfriedman appears to have a solution. Lets continue the conversation on this issue

**Comment by jamesmfriedman** [comment]
@amsheehan Yeah, racked my brain against this one for a while. Monkey patch to the rescue.

https://github.com/jamesmfriedman/rmwc/blob/master/src/Base/withMDCDrawer.js#L36

**Comment by kfranqueiro** [comment]
This should be resolved now that the `stopPropagation` has been refactored out via 3e173e1ddc3bff5c7c9c2d794eeb36a9354ec98c (based on #1138).

**Comment by jonhue** [comment]
@kfranqueiro Great news!
