### ISSUE TITLE
Scroll disable not working in full-featured mdc-select

### ISSUE THREAD

**Issue by monstasat** [material-components/material-components-web#1633]
### What MDC-Web Version are you using?

0.25.0

### What browser(s) is this bug affecting?

Firefox 57.0

### What OS are you using?

Fedora 26

### What are the steps to reproduce the bug?

1. Add full-featured mdc-select to page
2. Open it by clicking on select
3. Scroll the page - menu will move away from parent element

### What is the expected behavior?

Page scroll should be disabled while select is opened (it seems that this function is implemented in foundation, but it is not working neither in my web page, nor in mdc-select demo page) or menu position should be updated

### What is the actual behavior?

Menu moves away from parent while scrolling

**Comment by Garbee** [comment]
The scroll fix was added a few days ago. It hasn't been deployed in a package version yet.

**Comment by monstasat** [comment]
Thanks! Closing

**Comment by KeerthiThirumani** [comment]
@Garbee Could you let us know if this bug is fixed, if yes the version in which it is part of.  I am using @material/select but still see the issue.
