### ISSUE TITLE
display2 has not the exact correct font size

### ISSUE THREAD

**Issue by Sanjo** [material-components/material-components-web#1638]
The fonts-size should be `2.8125rem` instead of `2.813rem` to result in `45px` with `1rem = 16px`. The bug exists in version v0.25.0. The incorrect value is [located here](https://github.com/material-components/material-components-web/blob/v0.25.0/packages/mdc-typography/_variables.scss#L52).

**Comment by bonniezhou** [comment]
Nice catch! Feel free to submit a pull request with the correct value.
