### ISSUE TITLE
mdc-fab background mdc-theme-secondary

### ISSUE THREAD

**Issue by webiflex** [material-components/material-components-web#1642]
https://stackoverflow.com/questions/47460547/mdc-fab-background-mdc-theme-secondary
I raised the above but no answers as yet , not sure if an error. I also have this demo https://codepen.io/webiflex/pen/rYKaNm

Have the following in my Head tag

```
<style>
:root {
--mdc-theme-primary: #64ba69;
--mdc-theme--primary-light: #96ed98;
--mdc-theme--primary-dark: #31893d;
--mdc-theme--secondary: #e55100;
--mdc-theme--secondary-light: #ff833a;
--mdc-theme--secondary-dark: #ab1a00;
}
</style>
```
I can see that primary works for below with computed results background-color: rgb(100, 186, 105); = #64ba69

```
.mdc-button--raised:not(:disabled), .mdc-button--unelevated:not(:disabled) {
background-color: var(--mdc-theme-primary, #3f51b5);
}
```
But secondary does not work for below mdc-fab as get computed results background-color:rgb(255, 64, 129); = #ff4081

```
.mdc-fab {
background-color: var(--mdc-theme-secondary, #ff4081);
}
```
Not sure why ?

**Comment by acdvorak** [comment]
It looks like there are two issues:

1. Your CodePen uses a very old version of MDC-Web (`0.8.0`) that only supports \
    `--mdc-theme-accent`, but not `--mdc-theme-secondary`. \
    (`accent` was renamed to `secondary` a few releases ago.) \
    Updating your CodePen to the latest version of MDC-Web (currently `0.25.0`) should fix that.
2. You have an extra dash in some of the theme property names. \
    E.g.:
    `--mdc-theme--secondary`
    _should be:_
    `--mdc-theme-secondary`

I [forked](https://codepen.io/acdvorak/pen/GOXmoV) your CodePen and made the changes I just described, and it seems to work fine for me 🙂 

Closing this issue for now - feel free to reopen if you think there's a bug in MDC-Web. Thanks!
