### ISSUE TITLE
Add support in List for text-based end details

### ISSUE THREAD

**Issue by grosmar** [material-components/material-components-web#1644]
As described here https://material.io/guidelines/components/lists.html#lists-content (check image on the right side)
There should be a possibility for adding not only icon, but also text-based end-detail for list items.

At this moment as the width of the `.mdc-list-item__end-detail` set to 24px it's not possible without overriding the property to add for example timestamp content here.

**Comment by bonniezhou** [comment]
Thanks for pointing this out! Feel free to submit a pull request with these changes:

- [ ] Update `mdc-list.scss` with a new CSS class `mdc-list-item__text-detail` and styling
- [ ] Add an example of an `mdc-list-item__text-detail` element in a `mdc-list-item` element to the `mdc-list` demo
- [ ] Update `mdc-list` README.md documenting usage and code example
