### ISSUE TITLE
Integrate with Stencil.js

### ISSUE THREAD

**Issue by CorporateDrone** [material-components/material-components-web#1647]
The Ionic team has created a web component compiler, called [Stencil.js](https://stenciljs.com/) to create framework agnostic web components. 

Please consider providing integration for Stencil. We would like to use MDC-web with Stencil.js.

**Comment by Garbee** [comment]
Integrating with 3rd party frameworks and libraries is up to the community to build. The MCW project aims to provide the foundational styles and a vanilla javascript setup for components that can be implemented into 3rd party systems. It does not however provide fully supported integrations itself.

**Comment by bonniezhou** [comment]
What @Garbee said. [Here](https://github.com/material-components/material-components-web) is a list of JS libraries that integrate with MDC Web, feel free to write one for Stencil.js following the [criteria](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md) and submit a pull request to add it!
