### ISSUE TITLE
Missing Y scrolling for persistent drawer and touch screens

### ISSUE THREAD

**Issue by marioavs** [material-components/material-components-web#1656]
### What MDC-Web Version are you using?

> 0.26.0

### What browser(s) is this bug affecting?

> All, touch screen

### What OS are you using?

> Linux, Android, Windows

### What are the steps to reproduce the bug?

> 1. Run the demo server (it is also present in the demo site https://material-components-web.appspot.com/drawer/persistent-drawer.html)
> 2. Go to localhost:8080/drawer/persistent-drawer.html
> 3. Add some vertical content to make scrolling available, for example inside main tag: `<div id="extra-tall-content" class="mdc-elevation--z2" style="height: 200vh">&nbsp;</div>`
> 4. Try to scroll in Y direction using the main area and also the drawer area

### What is the expected behavior?

> The page should scroll in Y direction also when touching the screen on the left area over the drawer.

### What is the actual behavior?

> Scroll in Y direction is disabled over the drawer area. Scrolling is only working on the main area.

### Any other information you believe would be useful?
> The solution is to change mdc-persistent-drawer__drawer class, from touch-action: none, to touch-action: pan-y.
> It is easy to override in CSS but it would be better if the drawer has already vertical panning gestures enabled.

**Comment by bonniezhou** [comment]
Looks like a bug, feel free to submit a pull request! 
Note that the navigation drawer and the main page area should each scroll independently. Adding `overflow: auto` to the drawer should fix it.

**Comment by marioavs** [comment]
@bonniezhou after enabling scrolling, issues with touch events are more easy to spot. The issues are related to cancelled touch events and they also affect the temporary drawer.
I am including touch events fix in the PR.

**Comment by abhiomkar** [comment]
Closing this as obsolete.
