### ISSUE TITLE
Style tag 'will-change' causing button hover latency

### ISSUE THREAD

**Issue by cha1225** [material-components/material-components-web#1665]
Can someone explain to me what the 'will-change' tag does in the .mdc-button--raised style class? 
![screenshot from 2017-11-30 11-52-37](https://user-images.githubusercontent.com/12099690/33443343-59b5bb9c-d5c5-11e7-8b66-5186af2498c7.png)

If it's enabled, there's some latency with the hovering animation:
![test2](https://user-images.githubusercontent.com/12099690/33443385-7062bbf6-d5c5-11e7-8170-d0adf1b3bebd.gif)

If it's disabled, it reacts a lot better: 
![test](https://user-images.githubusercontent.com/12099690/33443410-8021a660-d5c5-11e7-979e-51a492816655.gif)

**Comment by kfranqueiro** [comment]
`will-change` is intended to notify the browser ahead of time of properties that are expected to change. It appears that currently `box-shadow` is overriding the `opacity, transform` style set up by MDC Ripple styles on raised buttons.

I set up a [codepen](https://codepen.io/kfranqueiro/pen/WXLQmZ) to attempt to play with some different options to see what performs better, but it's hard for me to notice a difference on my end (whereas it seems clearly more pronounced on yours). Could you give this codepen a try, and also let us know what browsers / OS you're experiencing this on?

**Comment by cha1225** [comment]
If you scale the codepen you sent me to render 400 buttons, on our end, the raised buttons won't even highlight, but the two patched ones are delayed in their highlighting (which is better). From my point of view, it seems like the two patched cases actually help. 

I'm currently using chrome: 61.0.3163.79 and running Ubuntu 16.04.

**Comment by kfranqueiro** [comment]
As it turns out, I ended up accidentally resolving this while working on [a commit](https://github.com/material-components/material-components-web/commit/935644939d09fafe051ceb48581b959c46c53829#diff-0c58b7e5172d52034fc499ce49f7e1bcR66) for MDC States. The `will-change` styles applied for ripple surfaces will no longer collide and get overridden by the one applied by MDC Elevation.
