### ISSUE TITLE
MDC Simple menu does not open if clicked immediately after closing

### ISSUE THREAD

**Issue by apuchenkin** [material-components/material-components-web#1679]
### What MDC-Web Version are you using?

latest

### What browser(s) is this bug affecting?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. Go to any of:

- https://material-components-web.appspot.com/simple-menu.html
- https://material-components-web.appspot.com/select.html

2. Click on menu/select to open menu
3. Select one of the menu items
4. Immediately after menu is closed click again in order to open menu
5. Observe tht menu is not open, despite that button is visible and clickable.

### What is the expected behavior?

Seconadry (open while menu is closing) click cancels closing animation, and initiates menu opening,
Alternative is that button is disabled until animation is completed.

### What is the actual behavior?

Secondary click ignored

### Any other information you believe would be useful?

This issue causes problems with automated selenium tests.

**Comment by amsheehan** [comment]
Pending a merge of #1691, this can be closed
