### ISSUE TITLE
mdc-typography has subheading1 and subheading2. Spec only has subheading.

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#168]
The `mdc-typography` module seems to include both a `subheading1` and a `subheading2` style, even though the MD spec only specific `subheading`.

The documentation also doesn't reflect this, mentioning only `subheading`.

**Comment by Sanjo** [comment]
The material spec mentions subheading1 and subheading2 in the [Line Height section](https://material.io/guidelines/style/typography.html#typography-line-height). I have noticed that it specifies subheading1 to have a font-size of 16sp instead of 14sp.

**Comment by williamernest** [comment]
Closed due to no longer being relevant.
