### ISSUE TITLE
@material/linear-progress docs are out of date

### ISSUE THREAD

**Issue by tyronedougherty** [material-components/material-components-web#1680]
On `0.25.0` of `@material/linear-progress`, the [foundation class docs](https://github.com/material-components/material-components-web/blob/master/packages/mdc-linear-progress/README.md#using-the-foundation-class) specify the implementation of an adapter method named `setTransform` like so:

```
setTransform(el: Element, value: string) => void
```

This adapter method no longer exists, and has instead been replaced with a method called `setStyle` with a definition like so:

```
setStyle(el: Element, styleProperty: string, value: number) => void
```

The docs need to be updated to reflect this, took me a while to figure out why my implementation wasn't working 😕

Cheers

**Comment by bonniezhou** [comment]
Thanks for catching this! Feel free to submit a PR with the `setStyle` signature replacing the outdated `setTransform` signature in the `README.md` for linear progress.
