### ISSUE TITLE
[Question] The new Google Flights material design looks stunning!

### ISSUE THREAD

**Issue by leesiongchan** [material-components/material-components-web#1681]
The new Google Flights material design is insanely beautiful and fluent. Especially the destination and date picker. Is this project going to update its components to be like that?

**Comment by bonniezhou** [comment]
Hi @leesiongchan, in short the answer is no. The type of text field, date picker, and other components you see on Google Flights are really specific to their use case. 
However our designers are constantly working on improving the Material Design component guidelines, and MDC Web will continue to be updated to reflect that.
