### ISSUE TITLE
Respect BEM when outputting the base stylesheet

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#1687]
Previously, I believe the specificity was warranted because of some other demo pages outside of the MDC Web catalog page. Since this is no longer the case, I think we should change it back to the demo selector.

Instead of `.mdc-radio.demo-radio--custom {}`, use `.demo-radio--custom {}`

Also if we're trying to use BEM here, we are using it incorrectly. For there to be a modifier class, we need a block or element to modify.

For instance, in `demos/radio.html` we have elements with:

`class="mdc-radio demo-radio--custom"`

This should read: `class="mdc-radio demo-radio demo-radio--custom"` to adhere to BEM style.

**Comment by bonniezhou** [comment]
To the first point, yes we should be using only the demo selector in CSS.
To the second point, we decided that for just the demo pages, better readability is more important than strict adherence to BEM style.

**Comment by lynnjepsen** [comment]
See #1733 for an example on how to fix the Sass mixins and demo pages. This PR is for checkbox only

**Comment by moog16** [comment]
I will also remove the <style> tags from all the demo files and place into the .scss files. I think @acdvorak mentioned wanting to do that in #1730.
