### ISSUE TITLE
Build a new variant of MDC Select, which allows for the drop down to be "exposed"

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1689]
We will create a new "MDC Exposed Select", whose drop down has a different behavior than the regular MDC Select. MDC Select positions the menu such that the selected element within the menu appears directly above the select box.

Exposed Select will display the drop down directly beneath the select box.

**Comment by mellogarrett** [comment]
Will this resolve the ongoing positioning issues that the current Select component has?

**Comment by lynnjepsen** [comment]
@mellogarrett I think #1688 will help with that more. But we plan on re-using that functionality to create an `mdc-select--exposed` variant

**Comment by kmmbvnr** [comment]
Would "Exposed Select" solve #879 ?

**Comment by lynnjepsen** [comment]
I think #2399 is what everyone is looking for. 

I'm closing this bug because our designers think that all new selects should either use the native select, or display the drop down directly beneath the select box.

For now we're only building the native select (#2399). 

Once we figure out how to display a drop down beneath a text field...and provide all the interaction behavior of a native select (arrow keys, typeahead, etc)...then we will file the issue and build that component.

**Comment by djensen47** [comment]
Sorry to be blunt, but in the meantime, native select looks like garbage.

**Comment by djensen47** [comment]
Why can't there be two components? A native select component and the existing component?
