### ISSUE TITLE
$mdc-theme-primary, accent, background only accepts hex colors

### ISSUE THREAD

**Issue by desvandev** [material-components/material-components-web#169]
At the moment "theme variables" only accept hex values. Can we change it to accept rgb colors so we can use for example the MD(**L**) [list of colors](https://github.com/google/material-design-lite/blob/mdl-1.x/src/_color-definitions.scss).
😃

**Comment by Garbee** [comment]
What is happening when you use an RGB value instead? All color formats should work fine. 

The RGB colors can be converted to hex losslessly. So the full recommended pallet will still work just fine.

**Comment by desvandev** [comment]
You are totally right. The problem was MDL _palette.scss had "!important" rule in the variables :rofl: 
My bad.

**Comment by Garbee** [comment]
MDL or MCW? They are now two different projects and MDL does have some limitations.

**Comment by sgomes** [comment]
Closing this, as it seems to be either be a non-issue, or related to the wrong project.

**Comment by desvandev** [comment]
@Garbee as I said in my first post, I was unsing mdL full color palette classes since mCW doesn't have one (yet). Anyway, this wasn't an issue. Thank you!
