### ISSUE TITLE
Add Hover, Focus, and Pressed states to MDC Card

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1709]
MDC Cards should be clickable, and should use our states subsystem to show hover, focus, and pressed states

**Comment by kfranqueiro** [comment]
Is this something that should happen for _all_ cards, or should it be either opt-in or opt-out? (e.g. I'm planning to add an opt-out class for mdc-list-item when I cover lists.)

**Comment by lynnjepsen** [comment]
As discussed in sprint planning, it will be optional. An opt-in.
