### ISSUE TITLE
Bug: mdc-textfield's root `index.js` file does not export the foundations or default implementations of its sub-components

### ISSUE THREAD

**Issue by tbrisbane** [material-components/material-components-web#1714]
Currently (as of `v0.26.0`), `mdc-textfield`'s root `index.js` file does not export any of the following:

- `MDCTextFieldBottomLine`
- `MDCTextFieldBottomLineFoundation`
- `MDCTextFieldHelperText`
- `MDCTextFieldHelperTextFoundation`

Imports for these symbols were added to the root `index.js` as part of #1684, however they were not subsequently exported.

By not exporting these symbols from the root `index.js`, we provide no way for consumers to access them from `dist/mdc.textfield.js` bundle. Consumers are instead forced to access them via their ES6 modules, which can be problematic for some (see #929).

**Comment by tyronedougherty** [comment]
+1 on this
