### ISSUE TITLE
MDC Select limitation: None of the ripple/state styles work for CSS-only selects

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1726]
CSS-only MDC Select puts ripple/states styles on a native select. Native selects do not get `::before` or `::after` pseudo-elements, which means most of those styles don't have any effect.

Solving this would require either rethinking the DOM structure, or seeing if we can get away with attaching the ripple to the root element instead (as mentioned in #1725).

**Comment by lynnjepsen** [comment]
Closing as obsolete because CSS only version is removed with #2116
