### ISSUE TITLE
MDC Select limitation: Focus state doesn't work for CSS-only selects

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1727]
In MDC Select's DOM structure, the element that receives focus is not the element that ripple/states styles are hooked up to. The element that receives focus is _above_ the ripple surface element, which means `:focus-within` won't work either.

Solving this would require either rethinking the DOM structure, or seeing if we can get away with attaching the ripple to the root element instead (as mentioned in #1725).

This is sort of overshadowed by #1726 anyway, but this issue would still exist even if that were fixed.

**Comment by lynnjepsen** [comment]
Closing as obsolete because CSS only version is removed with #2116
