### ISSUE TITLE
Easy integration for people who don't use SASS

### ISSUE THREAD

**Issue by appsforartists** [material-components/material-components-web#173]
I'd love to use Material Components in my own work, but introducing SASS is too much overhead (as is importing and maintaining third party code in a repo).

It would be lovely if using Material Components was as simple as adding the appropriate tags to your header.  Have you considered hosting on a CDN:

```html
<link 
  rel = "stylesheet" 
  href = "https://ajax.googleapis.com/ajax/libs/material-components-web/1.0.0/material-components-web.css"
>
```

**Comment by traviskaufman** [comment]
Hey @appsforartists,

You can serve MDC-Web over a CDN using [unpkg](https://unpkg.com/#/), which proxies to npm to fetch the appropriate files.

```html
<link 
    rel="stylesheet"
    href="unpkg.com/material-components-web@latest/dist/material-components-web.css"
>
```

As for a more elaborate CDN setup, we are still figuring out exactly where and how we want to host built versions of MDC-Web besides npm, and don't want to do anything pre-emptive before we have that figured out. However, using `unpkg` should work for your use case.

**Comment by appsforartists** [comment]
Ha - you're the one who told me to open this. 😝
