### ISSUE TITLE
Correct "mdc-list-item__secondary-text" class on mdc-list package README.

### ISSUE THREAD

**Issue by kevinarrieta** [material-components/material-components-web#1734]
It seems this class is no longer working, I had to find this class on the demo "mdc-list-item__text__secondary" to get the secondary text properly styled.

I'm using version 0.26.0

**Comment by amsheehan** [comment]
Would you mind providing a Codepen demonstrating that behavior? [Here is a template with the latest version of MDC Web loaded](https://codepen.io/traviskaufman/pen/pNQmRp). Also make sure you're using the latest version. We just released, and I believe all instances of that selector have been renamed to `mdc-list-item__secondary-text`

**Comment by corneschouten** [comment]
The CHANGELOG contains an incorrect example of the secondary text class:

> - **list:** The `mdc-list-item__text__secondary` class was renamed to `mdc-list-item__text-secondary` to follow BEM conventions. See the BEM FAQ for more details.

It should be `mdc-list-item__secondary-text` instead of `mdc-list-item__text-secondary` like @amsheehan  mentioned.

**Comment by simono** [comment]
@corneschouten I fixed this in #1754

**Comment by kevinarrieta** [comment]
Everything looks fine for me now, I wasn't using the latest version.
