### ISSUE TITLE
Tooltip css-only approach

### ISSUE THREAD

**Issue by MishUshakov** [material-components/material-components-web#1741]
Hey, guys, I created a very small and handy CSS-only tooltip, for using with data attribute

Codepen: https://codepen.io/mishushakov/pen/OzLxvV

### What is the expected behavior?

Tooltips will be supported with CSS and Adapter approaches

### What is the actual behavior?

No tooltips are supported yet :(

Thank you!

**Comment by j-o-d-o** [comment]
Sadly the CSS only approach does not work well with mdc-ripple :(

https://codepen.io/j-o-d-o/pen/XVrzjy

**Comment by MishUshakov** [comment]
@j-o-d-o Hey! It is just a showcase, of a **possible** implementation, not the finished implementation itself

**Comment by amsheehan** [comment]
Unfortunately this approach with hijack the pseudo elements that  we use for ripples :(

We do appreciate the suggestion though, thanks for the good work. I'm going to close this issue, but if you'd like to contribute anything down the line, please don't hesitate to make a pull request or checkout our [Pivotal Tracker](https://www.pivotaltracker.com/n/projects/1664011) to see which components we plan on working on.

**Comment by Garbee** [comment]
Also for proper accessibility tooltips basically require JavaScript to work. Doing them in a CSS only manner leaves them in-accessible which isn't something that we'd want in the library. We experimented with this very early on and decided against a css-only implementation of them.

**Comment by MishUshakov** [comment]
@Garbee, since they are still in the DOM and the display property doesn't change, are they still pronounced by screen readers? Thank you.

**Comment by Garbee** [comment]
Yes, the data is in the DOM. No that doesn't mean it will be read by a screen reader. Attributes are ignored unless they are ones specifically to tell accessibility technology to read something.
