### ISSUE TITLE
Normal temporary drawer with toolbar space shows horizontal line when page scrolls

### ISSUE THREAD

**Issue by pgbross** [material-components/material-components-web#1742]
### What MDC-Web Version are you using?

> v0.26.0

### What browser(s) is this bug affecting?

> Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

### What OS are you using?

> Fedora 27

### What are the steps to reproduce the bug?

> 1. Create a simple page with normal toolbar and temporary drawer.
> 2. Add a mdc-temporary-drawer__toolbar-spacer
> 3. Make sure there is sufficient content on the page to cause vertical scrolling.
> 4. Shrink the window so it needs to scroll.
> 5. Scroll page and see 1px horizontal grey line
>
> See [Codepen example](https://codepen.io/pgbross/pen/VyZEaG)

### What is the expected behavior?

> On scrolling there should be no "bleeding" from the closed drawer.

### What is the actual behavior?

>The `mdc-temporary-drawer__toolbar-spacer` has a 1px bottom border that appears when the page is scrolled vertically.

### Any other information you believe would be useful?
This appears to from the `border-bottom: 1px solid rgba(0,0,0,.12);`. If this is removed the problem does not manifest itself, but I have not done a detailed check to see if that 1px height is needed.

**Comment by moog16** [comment]
On line 14 you have `<div class="mdc-temporary-drawer__toolbar-spacer"></div>`, which is the line that is appearing. If you remove that line this will fix your issue.

Also in our newer versions of mdc-toolbar. The toolbar is position: fixed, not relative. If the toolbar is position fixed, you would never see the outline.

**Comment by pgbross** [comment]
The `mdc-temporary-drawer__toolbar-spacer` is required as per your documentation in the section `headers and toolbar spacers` to get the drawer to open below the toolbar.

So I am not sure what you are suggesting to replace it with if removing it is the only way to avoid the 1px artefact when scrolling is needed.

**Comment by moog16** [comment]
We actually place the toolbar-spacer inside the mdc-drawer__drawer element as per this doc: https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer#headers-and-toolbar-spacers.

It is also optional so it is not required.
