### ISSUE TITLE
List class selector specificity increase

### ISSUE THREAD

**Issue by draoncc** [material-components/material-components-web#1748]
Since 0.27.0, the specificity of some list related class selector has increased with unnecessary nesting, breaking low-specificity style overrides.

Previously: `.mdc-list-group__subheader`, `.mdc-list-item__start-detail`

Now: `.mdc-list-group .mdc-list-group__subheader`, `.mdc-list .mdc-list-item__start-detail`

There appears to be no reason to warrant this specificity increase. Could this be reverted?

**Comment by lynnjepsen** [comment]
Yes. Definitely a bug. We're working to fix this for all components. Sorry for the inconvenience.

#1733 represents the fix for MDC Checkbox. You could submit a similar PR for list if you want?
