### ISSUE TITLE
Buttons need `text-decoration: none`

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#177]
`mdc-button` should set `text-decoration: none`, so that button styles can be used in anchor tags.

**Comment by amsheehan** [comment]
Is text-decoration the only rule that needs to change? Perhaps we should also set rules for 
`link`, and `visited`, as well. The other states seem to already be covered in `mdc-button`

**Comment by Garbee** [comment]
What would `:visited` change? I don't think there is anything to that one using anchors as buttons as the colors are already set on everything by default as I recall.

**Comment by amsheehan** [comment]
In implementing this, @sgomes' original assertion of setting `text-decoration: none` is sufficient to achieve the desired outcome.
