### ISSUE TITLE
Keeping Docs up to date

### ISSUE THREAD

**Issue by jamesmfriedman** [material-components/material-components-web#1780]
Sorry in advance for the open ended issue!

I've built the RMWC React wrapper for this library and I'm having a hard time keeping up with changes because the docs are consistently out of date with the working examples. My current process for updating RMWC to the next MWC version is like so:

- Read the changelog
- Go read through the docs of the changed features
- implement changes
- get bugs filed because I implemented the doc version
- open the working examples and see that the docs were wrong
- dig through the source code to be absolutely sure...

Is there anyway we could close this gap? Maybe there could bel a requirement before a PR gets merged in that the associated docs are updated. It seems to happen pretty consistently. Loving using the lib, just wish I could trust the docs on it :).

#1680 
#1416 
#757

**Comment by matsp** [comment]
@jamesmfriedman I'm trying to solve this problem by using the versions tags in the future, so I will just see the changes of that. Ran into the same issues as you the last release ;-)

**Comment by lynnjepsen** [comment]
Hey @jamesmfriedman 
You're totally right. We've been doing a lot of changes lately, and ramping up new people on the team. We've been prioritized building new features ahead of documenting changes.

But its time we circled back to our support system for READMEs and our demo site. I think the best way to ensure we always update our READMEs when we update any breaking changes, is to have consistent formatting across all READMEs.

I'm wondering what you think of our README standards:
https://github.com/material-components/material-components-web/blob/master/docs/code/readme_standards.md
https://github.com/material-components/material-components-web/blob/master/docs/code/readme_template.md

There is also #1788 as an example for how we bring MDCTextField's README into consistency with our README standards.

We're still working on how to standardize our demo pages better. We'll try and remember to share that once we have more information.

**Comment by asyncLiz** [comment]
Closing since this issue is a bit out of date. We're working on standardizing our Material design docs, so that should hopefully help with doc-related issues in the future.
