### ISSUE TITLE
@material/radio README Adapter Documentation Missing Methods

### ISSUE THREAD

**Issue by Kerrick** [material-components/material-components-web#179]
In [README.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-radio/README.md) for [`@material/radio`](https://github.com/material-components/material-components-web/tree/master/packages/mdc-radio), there is no mention of [`addClass` and `removeClass`](https://github.com/material-components/material-components-web/blob/master/packages/mdc-radio/index.js#L86-L87) in the "Using the Foundation Class" section, even though those adapter methods are used by the foundation class.

**Comment by traviskaufman** [comment]
Thanks for reporting @Kerrick!

**Comment by traviskaufman** [comment]
Closed via #181
