### ISSUE TITLE
Add demo of list with checkbox selection controls; remove native multiselect

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1792]
We currently have a multiselect demo in the [Select demo page](http://material-components-web.appspot.com/select.html). However, this demo doesn't really sync up with anything in particular in the Material Guidelines, and moreover, styling native selects is notoriously difficult and inconsistent in terms of what different browsers allow/prevent (see #1751 and #1781 for examples).

Instead, we should implement a demo of selection controls within a MDC List (e.g. the example seen [here in the guidelines](https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls)), then decommission the multiselect example (and preferably remove its inconsistently-successful-across-browser styles to reduce MDC Select's payload).

Note that #1591 was previously reported involving checkboxes inside lists, so we may need to deal with that first if it hasn't been fully remedied by recent updates to MDC List styles.

**Comment by lynnjepsen** [comment]
Closing with PR #2066
