### ISSUE TITLE
Implementation Simplification Idea Re data-mdc-auto-init

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#1797]
Bravo re the mdc-web package. You guys nailed it. Simple. I really love mdc-web. Thank you.

My feature request / idea: Instead of requiring developers to write, for example, `data-mdc-auto-init="MDCIconToggle"` why not simply `data-mdc-auto-init=true`. This simplifies implementation, i.e., one does not need to know or look up the component name. Seems like your mdc-web script could have a `switch` based on `this.classList.contains` to identify what should be initialized when that `dataset` is seen.

...Just an idea.

**Comment by acdvorak** [comment]
Thanks for the suggestion and kind words 🙂 

I agree that `data-mdc-auto-init=true` would be quicker and easier to write, but there are a few edge cases that would make it problematic to implement in MDC Web.

If this is something you really need, you could always write your own auto-init wrapper 🙂
