### ISSUE TITLE
Strategy for site showcase requests

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#18]
In ~~V1~~MDL, we had the concept of [user-submissions](https://github.com/google/material-design-lite/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20showcase) for inclusion on https://getmdl.io/showcase/index.html, but only got around to highlighting a few of the Google properties that shipped with MDL support. 

As submissions tend to be of varying quality, I might suggest that we move to just including user submissions in a wiki page that can be referenced but doesn't necessarily appear on the site. Thoughts, @sgomes? 

> Copied from https://github.com/google/material-design-lite/issues/4734

**Comment by amsheehan** [comment]
@traviskaufman @sgomes I like the way D3 curates their list. Would allow us a vetting process.
