### ISSUE TITLE
MDC Select's scaleX logic is currently unused/overridden

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#1802]
MDC Select contains code to set `transform-origin` for the purposes of applying a `scaleX` transform to the bottom-line element, but it is currently overridden by the `scaleY` transform in the focused and open states anyway. This means that the JS logic to determine the `transform-origin` is just wasting resources at the moment.

We should either figure out a way for these transforms to coexist, or remove the excess JS logic that ultimately isn't doing anything.

**Comment by lynnjepsen** [comment]
See #1981 for how we plan on adding the bottom line to MDCSelect...now that we've removed the scaleX logic
