### ISSUE TITLE
Bottom line during hover - Outlined Text Field

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#1817]
### What MDC-Web Version are you using?

> latest

### What browser(s) is this bug affecting?

> Chrome, probably all

### What OS are you using?

> macOS Sierra

### What are the steps to reproduce the bug?

1. Run the demo server
1. Add `mdc-theme--dark` as a class to the outline text field wrapper element. This will allow you to see the issue more clearly
1. Hover the cursor over the text field

### What is the expected behavior?

The cursor should change, but nothing else

### What is the actual behavior?

A bottom line gets added

### Any other information you believe would be useful?
![dark-theme-textfield](https://user-images.githubusercontent.com/1578263/34268819-2369cf9c-e650-11e7-88ac-ecd68224873d.png)

**Comment by simono** [comment]
@amsheehan I've added a fix in #1828

**Comment by acdvorak** [comment]
It looks like this is only an issue in dark mode, which we're going to be removing very soon (you can just use our theme mixins or customize the value of `$mdc-theme-primary` and `$mdc-theme-background` instead).

Closing this issue for now; if it's still a problem in light mode, we can reopen it.
