### ISSUE TITLE
[Toolbar] SVG Icons have wrong color

### ISSUE THREAD

**Issue by MichaelTamm** [material-components/material-components-web#1821]
When I use SVG icons in a MDC toolbar (instead of the material-icon font based icons, which the MDC Toolbar demos use), the icons are always black, but should be white (or rather: `--mdc-theme-text-primary-on-primary`).

This [CodePen](https://codepen.io/MichaelTamm/pen/OzRXwZ) demonstrates the issue.

The reason is, that in the file `mdc-toolbar.scss` you only style the `color` property, but for SVG icons the `fill` property must be styled.

If you agree, that adding styling for the `fill` property (in order to support SVG icons) would be a worthy addition to the project, I would like to provide a pull request.

### What MDC-Web Version are you using?

@material/toolbar 0.27.0

### What browser(s) is this bug affecting?

all

**Comment by MichaelTamm** [comment]
Ping

**Comment by acdvorak** [comment]
Thanks for filing this issue!

It sounds like we just need to add something like `fill: currentColor`.

PRs welcome!

**Comment by MichaelTamm** [comment]
Ping
