### ISSUE TITLE
Different warning color values between stroke and helper text for outline text field

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#1822]
### What MDC-Web Version are you using?

Latest Master

### What browser(s) is this bug affecting?

Chrome, all

### What OS are you using?

macOS Sierra

### What are the steps to reproduce the bug?

1. Fire up dev server
1. Turn on Outline Text Field's dark mode
1. F stuff up in the input

### What is the expected behavior?

Red in the outline should match red in the helper text

### What is the actual behavior?

They are different reds.

### Any other information you believe would be useful?
![screen shot 2017-12-21 at 2 57 54 pm](https://user-images.githubusercontent.com/1578263/34272710-5c96b7da-e65f-11e7-8414-7dc1c97d4a4d.png)

**Comment by simono** [comment]
@amsheehan I've added a fix in #1827 that fixes this.

**Comment by acdvorak** [comment]
It looks like this is only an issue in dark mode, which we're going to be removing very soon (you can just use our theme mixins or customize the value of $mdc-theme-primary and $mdc-theme-background instead).

Closing this issue for now; if it's still a problem in light mode, we can reopen it.
