### ISSUE TITLE
event for MDCDialog closed?

### ISSUE THREAD

**Issue by mreinstein** [material-components/material-components-web#1830]
looking at the code for the MDC Dialog I don't see any way to trap that the dialog has gone from open to closed state. For example, clicking outside the dialog causes it to close, but none of the accept or cancel button events fire.

I'd really rather not have ugly polling hacks or need to register special tap/click handlers for detecting when clicking outside the dialog element. Is there an event I don't know about to handle this, or a way to force the dialog to require clicking an accept/cancel button to close?

**Comment by j-o-d-o** [comment]
Hmm, that is wired. I think if the dialog closes and the user didn't NOT click accept, the cancel event will fire. At least in this short codepen: https://codepen.io/j-o-d-o/pen/XVrzjy?editors=1010

**Comment by mreinstein** [comment]
@j-o-d-o you're right! That definitely works. I thought I tried that, but I'm thinking I must have had some application level error in my code. Sorry for wasting your time, and thanks for the help!
