### ISSUE TITLE
Full Width, Full Functionality Text Field is misaligned

### ISSUE THREAD

**Issue by sidot3291** [material-components/material-components-web#1836]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

0.27.0

### What browser(s) is this bug affecting?

Chrome

### What are the steps to reproduce the bug?

Inspect and add mdc-text-field--fullwidth to the full functionality demo:
<img width="799" alt="screen shot 2017-12-26 at 2 36 31 pm" src="https://user-images.githubusercontent.com/614945/34363588-5d3cae48-ea4b-11e7-9836-9a52d8c48b15.png">
https://material-components-web.appspot.com/text-field.html

### What is the expected behavior?

Width changes to full width

### What is the actual behavior?

Height changes, bottom borderline gets lighter when not focused, input is not correctly aligned vertically

**Comment by acdvorak** [comment]
The [text-field README](https://github.com/material-components/material-components-web/blob/5a19695523cf96e068a844cc762df9400d97554a/packages/mdc-textfield/README.md#full-width) seems to indicate that this is not possible:

> NOTE: Do not use mdc-text-field__label within mdc-text-field--fullwidth. Labels should not be included as part of the DOM structure of a full width text field.
