### ISSUE TITLE
Missing Temporary Drawer Link on Catalog

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#1837]
### What MDC-Web Version are you using?

0.27.0

### What browser(s) is this bug affecting?

All

### What OS are you using?

OSX 10.12.6

### What are the steps to reproduce the bug?

1. Follow [link](https://material.io/components/web/catalog/drawers/ )

### What is the expected behavior?

There should be a link to temp drawer similar to permanent drawer (and others)

### What is the actual behavior?

Notice no temporary drawer link

### Any other information you believe would be useful?

Originally mentioned in Discord chat

**Comment by jschoch** [comment]
the docs don't seem to match the demo for temporary drawer

**Comment by joachim-ifergan** [comment]
I temporary fixed it with :     
<aside class="mdc-drawer mdc-persistent-drawer mdc-drawer--persistent">
      <nav class="mdc-drawer__drawer mdc-persistent-drawer__drawer">

**Comment by abhiomkar** [comment]
Closing as obsolete.
