### ISSUE TITLE
ETA on TypeScript's type definitions? :)

### ISSUE THREAD

**Issue by eyalsk** [material-components/material-components-web#1840]
Just a quick question and sorry if this is the wrong place to ask this but I read the following in the docs:

> We plan on creating Type Definitions for our adapters in the future so that TypeScript users can validate that their interface conforms correctly to the adapter's specification.

I wonder whether there's any ETA on this or progress made as I'm currently investigating technologies for a new website and I really like the philosophy behind MDC-Web and it would be really awesome to have type definitions, it wouldn't be a blocker for me though.

**Comment by acdvorak** [comment]
I wish we could provide an ETA, but unfortunately we only have enough bandwidth to add Closure annotations (which Google uses internally) right now 🙁 

That said, anyone from the community is more than welcome to create and maintain a set of definitions in [DefinitelyTyped](http://definitelytyped.org/) 🙂

**Comment by eyalsk** [comment]
@acdvorak I'll see what I can do about that once I'll start, thank you. :)

**Comment by BrentDouglas** [comment]
@acdvorak The DefinitelyTyped folk just merged https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23179 which should resolve this issue. The types are based on v0.26.0 but should be a good starting point for anyone wanting to update them to the current version. I skimmed 0.29 and not much looked different.

**Comment by pspeter3** [comment]
@BrentDouglas do you believe it would be possible to automate this process at all? It seems like the documentation has up to date information and could be converted

**Comment by CiriousJoker** [comment]
How can this be closed when the DefinitelyTyped definition is (by definition pretty much) always behind the schedule?

**Comment by eyalsk** [comment]
@CiriousJoker, @pspeter3 I've reopened the issue.

**Comment by fjorgemota** [comment]
I think this can be closed now that #4225 is closed too (and all the built packages have correct type definitions AND `type` field on package.json), right?

**Comment by kfranqueiro** [comment]
Yup, that's correct. Thanks for pointing it out!
