### ISSUE TITLE
Toolbar height is wrong when width is between 735px and 960px

### ISSUE THREAD

**Issue by ocavue** [material-components/material-components-web#1841]
### What MDC-Web Version are you using?

v0.27.0

### What browser(s) is this bug affecting?

chrome 63.0

### What OS are you using?

macOS 10.13.2 High Sierra

### What are the steps to reproduce the bug?

1. open this URL: http://material-components-web.appspot.com/toolbar/default-toolbar.html which is hosted by google 
2. adjust window's width, from minimum to maximum

### What is the expected behavior?

| width of browser (px) | height of toolbar (px) |
| --- | --- | 
| 0~600 | 56 |
| 600~∞ | 64 |

### What is the actual behavior?

| width of browser (px) | height of toolbar (px) |
| --- | --- | 
| 0~600 | 56 |
| 600~735 | 64 |
| **735~960** | **56** (should be 64) |
| 960~∞ | 64 |

### Any other information you believe would be useful?

I found this bug from [here](http://material-components-web.appspot.com/drawer/permanent-drawer-below-toolbar.html), which is another demo page hosted by Google. I can find some gap between toolbar and drawer at some width.

<img width="799" alt="screen shot" src="https://user-images.githubusercontent.com/24715727/34455480-eb99fca0-edba-11e7-9a72-0b36e672c3fc.png">

**Comment by acdvorak** [comment]
Yep, that's a bug! Added it to our internal issue tracker.

Thanks for taking the time to report this, and for using the GitHub issue template and including an annotated screenshot - it saves us a lot of time and we really appreciate it 😀

**Comment by kfranqueiro** [comment]
I think I noticed this today as well, and I suspect it's due to a [media query in our toolbar code](https://github.com/material-components/material-components-web/blob/4402dd5041613fe551ae66a9262428712bba9a1c/packages/mdc-toolbar/mdc-toolbar.scss#L45) that restricts based on max-width but also on landscape orientation.

**Comment by englishextra** [comment]
> Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
> Windows 10 1511  10586.104 64-bit 

![screen shot 2018-04-03 at 15 24 19](https://user-images.githubusercontent.com/537127/38249221-a2651da2-3753-11e8-8d74-1c3e6778d678.png)
![screen shot 2018-04-03 at 15 24 45](https://user-images.githubusercontent.com/537127/38249223-a28d2658-3753-11e8-8b25-5e5a0213ca55.png)
![screen shot 2018-04-03 at 15 25 10](https://user-images.githubusercontent.com/537127/38249224-a2b2c250-3753-11e8-85a6-dbfa5467b2fb.png)
![screen shot 2018-04-03 at 15 25 28](https://user-images.githubusercontent.com/537127/38249225-a2d63adc-3753-11e8-84dd-0c789dc6d6f6.png)

**Comment by abhiomkar** [comment]
Toolbar is now removed from MDC Web.

Please use Top App Bar instead: https://material-components.github.io/material-components-web-catalog/#/component/top-app-bar

Closing this bug as obsolete.

Thanks!
