### ISSUE TITLE
MDC Toolbar and unexpected/strange behavior from 600px up to 960px wide

### ISSUE THREAD

**Issue by jan-johansson-mr** [material-components/material-components-web#1842]
Hi,

I'd like to issue a strange behavior with the mdc-toolbar. I noticed it with my app, but when checking the behavior on [material design mdc waterfall toolbar](https://material-components-web.appspot.com/toolbar/waterfall-toolbar.html), I see the same behavior.

So this issue has the same MDC-Web Version as the material design (the link above) has. My solution uses the 0.27.0 version (of '@material/toolbar' and 'material-components-web', from npm repository).

I see this behavior on Chrome (Version 63.0.3239.108 64 bits), I have not tested on other browsers. I'm running on Linux (4.14.9-1-ARCH).

If you follow the [link](https://material-components-web.appspot.com/toolbar/waterfall-toolbar.html) I entered above, then make sure to make the view small so you can scroll the content (to see the toolbar behavior).

If the toolbar is smaller than 600px wide, then the toolbar has the expected behavior (it raises while the content scrolls). When the view hits 600px wide (refresh the page before scrolling the text), then the toolbar does not raise any more (the toolbar has 585x56px at 600px wide view). The behavior remains the same until the view hits 960px wide (the toolbar has 945x64px at this point). Now the behavior goes back to expected again (it raises while the content scrolls).

Make sure to refresh the page when hitting these marks, otherwise if you start with say a width of 500px and then put the width to 650px, and scroll the page, then you will see no change and think that the behavior is as expected (the toolbar raises when scrolling content).

To test, simply start with say width 500px and scroll content. Then put somewhere between 600px to 960px, refresh page and scroll content. Then put somewhere above 960px, refresh, and scroll content.

Thanks

**Comment by acdvorak** [comment]
Thanks for reporting this issue!

Could you possibly include a screenshot? This will help us triage it more quickly. Thanks!

**Comment by kfranqueiro** [comment]
Hm... This might be describing the same thing as #2245?

**Comment by kfranqueiro** [comment]
I'm going to close this, since #2245 has more specific info and screenshots and we're pretty certain both of these refer to the same issue.
