### ISSUE TITLE
Style standard Select to match standard Text Field (move variant into --box)

### ISSUE THREAD

**Issue by djensen47** [material-components/material-components-web#1843]
Text field boxes are optional for text fields. According to the spec, the mdc-select component is a form of text field:  "Other components such as dropdown menus and pickers can be nested in text fields to make input easier."  https://material.io/guidelines/components/text-fields.html#text-fields-input-types

**Observed behavior:**
The current documented behavior for mdc-select is that it is always inside of a text field box.

**Expected behavior:**
A text field box should be optional for mdc-select

---
Please forgive me if this issue has already been raised. I searched through the issue but didn't find anything relevant but there still might be.  Also, I didn't read through the code to see if there is an undocumented feature.

**Comment by MeyerUX** [comment]
Agree with @djensen47. Not having the box as optional is a killer. Expected outcome according to the Material guidelines is to have the box option to match regular text field boxes, and a non-box option to match regular text fields.
