### ISSUE TITLE
How to change button ripple color as custom primary color? 

### ISSUE THREAD

**Issue by ljcucc** [material-components/material-components-web#1887]
I using this code to change my button ripple color as my custom primary color, but it doesn't change button ripple color which is default blue.
```
:root,.mdc-button{
  --mdc-theme-primary: #795548;
}
```

**Comment by acdvorak** [comment]
That should work - do you have a [CodePen](http://codepen.io/traviskaufman/pen/pNQmRp) we can take a look at?

**Comment by ljcucc** [comment]
After @acdvorak you give me the codepen playground which to test my code and I found maybe my MDC verison is too old (cause I downloaded it), so that makes errors like this. thanks!
