### ISSUE TITLE
How to add/remove tabs after MDCTabBar has been initialized

### ISSUE THREAD

**Issue by developerdizzle** [material-components/material-components-web#1891]
Looking for guidance about this.  I see in https://github.com/material-components/material-components-web/blob/master/packages/mdc-tabs/tab-bar/index.js#L52 that `MDCTab`s are automatically instantiated and initialized by `MDCTabBar`, but I don't see how they're destroyed.  Is `destroy`ing and re-instantiating `MDCTabBar` the best way to accomplish this when tabs are added or removed?

**Comment by acdvorak** [comment]
Unfortunately, we don't support dynamically adding and removing tabs (it's not in the spec, so we haven't implemented it).

I'm guessing you would need to `destroy` each individual tab (accessed via the `tabs` property on an `MDCTabBar` instance), and then `destroy` the `MDCTabBar` and create a new one. I haven't tried it, though, so I can't say for sure.

**Comment by agnel** [comment]
I was building a small application (a pdf viewer). I wanted to use the TabScroller for this.

> Unfortunately, we don't support dynamically adding and removing tabs (it's not in the spec, so we haven't implemented it).
> 
> I'm guessing you would need to `destroy` each individual tab (accessed via the `tabs` property on an `MDCTabBar` instance), and then `destroy` the `MDCTabBar` and create a new one. I haven't tried it, though, so I can't say for sure.

I did it using @acdvorak's idea. Instead of destroying individual tab, I just used the `destroy` method on `MDCTabBar` after injecting the DOM for new tab. Then I initialized the `MDCTabBar` again.

PS: Sorry for my english, I hope you understand what I meant.

**Comment by jjstanton** [comment]
@agnel Would you mind sharing the code you used to solve this? 
I am also struggling with this.

**Comment by agnel** [comment]
> @agnel Would you mind sharing the code you used to solve this?
> I am also struggling with this.

Hi @jjstanton, I had worked on this issue almost a year ago, when I was building the app. The app was built using Marionette.js. Right now, I'm working on a different stack altogether. I can look back at the app source code, and respond in sometime.

**Comment by agnel** [comment]
Here it is... @jjstanton. What you need are the methods related to Tab and TabBar. Hope this helps.

`
VBR.Controllers.TabsController = Marionette.Object.extend({

    initialize: function(options) {
        self = this;
        this.mainController = options.mainController;
        this._paths = [];
        this._tabs = [];
        this._tabContents = [];

        // by default, set it false
        // we will track this so that we don't assign listener for every initializeTabBar
        this.tabBarListenerAttached = false;

        this.initializeScroller();

        ipcRenderer.on('file-open', (event, result) => {
            this._propagateClick();
            this.openFile(result.filePaths);
        });

        Mousetrap.bind('mod+w', self.closeTab.bind(self));
        Mousetrap.bind('mod+tab', self.nextTab.bind(this));
        Mousetrap.bind('mod+shift+tab', self.prevTab.bind(this));
    },

    openFile: function(filePaths) {
        _.each(filePaths, this._addTab.bind(this));
    },

    initializeScroller: function() {
        if (!this.tabBar) {
            this.tabScroller = new VBR.Views.Item.TabScroller();
            this.mainController.layout.ui.contentContainer.append(this.tabScroller.render().$el);
        }
        this.initializeTabBar();
    },
    
    initializeTabBar: function(){
        self = this;
        this.tabBar = new mdc.tabBar.MDCTabBar(this.tabScroller.el);
        // this.tabBar.listen('MDCTabBar:activated', function(event) {
            //     self.handleTabActivation(event);
            // });

        if(!this.tabBarListenerAttached) {
            this.tabBar.listen('MDCTabBar:activated', this.handleTabActivation.bind(this));
            this.tabBarListenerAttached = true;
        }

        this.toggleBg(this._tabs.length == 0);
    },

    handleTabActivation: function(event) {
        this.prevTab = this.currentTab;
        this.currentTab = this._tabs[event.detail.index]; // set currentTab to the one currently activated tab
        this.tabBar.foundation_.adapter_.focusTabAtIndex(event.detail.index);

        this.currentTabContent.toggle(); // deactivates the prev one which in this variable currently.
        this.currentTabContent = this._tabContents[event.detail.index]; // set the current tab to show from the currently activated tab
        this.currentTabContent.show(); // this is will display it as it would be hidden.
        VBR.updateTitle(this._paths[event.detail.index]);
    },

    // unlisten the event and destroy tab bar.
    destroyTabBar: function(params) {
        this.tabBar.unlisten('MDCTabBar:activated');
        this.tabBar.destroy();
    },

    reinitializeTabBar: function() {
        this.destroyTabBar();
        this.initializeTabBar();
    },

    toggleBg: function(flag) {
        flag ? this.mainController.layout.ui.bgContainer.show() : this.mainController.layout.ui.bgContainer.hide();
    },

    _addTab: function(pathName) {
        if (this._paths.indexOf(pathName) >= 0) {
            
            if(this.currentTab.options.pathName != pathName) {
                this.currentTab.deactivate();
                this.currentTabContent.hide();
            }

            this.tabBar.scrollIntoView(this._paths.indexOf(pathName));
            this.tabBar.foundation_.adapter_.activateTabAtIndex(this._paths.indexOf(pathName));
            return;
        } else {

            if(this.currentTab) {
                this.currentTab.deactivate();
                if(this.currentTabContent) {
                    this.currentTabContent.hide();
                }
                this.prevTab = this.currentTab;
                this.currentTab = null;
            }

            this.destroyTabBar();

            this._paths.push(pathName);

            this.currentTab = new VBR.Views.Item.Tab({pathName: pathName, tabsController: this});
            this._tabs.push(this.currentTab);

            this.currentTabContent = new VBR.Views.Item.TabContent({pathName: pathName, tabsController: this});
            this._tabContents.push(this.currentTabContent);

            this.tabScroller.$el.find('#scroll-content').append(this.currentTab.render().$el);
            this.tabScroller.$el.find('.file-tabs-content-container').append(this.currentTabContent.render().$el);
            
            this.initializeTabBar();
        }
        VBR.updateTitle(pathName);
    },

    removeTab: function(tabIndex) {
        this._paths.splice(tabIndex, 1);
        this._tabs.splice(tabIndex, 1);
        this.tabBar.tabList_[tabIndex].root_.remove(); // this removes the DOM element for tab
        
        this._tabContents[tabIndex].$el.remove(); // this removes the DOM element for tab content
        this._tabContents.splice(tabIndex, 1); // this removes the tab element from our array
        this.tabBar.tabList_.splice(tabIndex, 1);

        this.prevTabIndex = this._tabs.indexOf(this.prevTab);

        // this.prevTabIndex == -1 means prevTab doesn't exists
        // because it was already removed, so set prevTabIndex = currentTabIndex - 1
        this.prevTabIndex = this.prevTabIndex == -1 ? tabIndex - 1 : this.prevTabIndex;
        
        if(this.tabBar.tabList_.length >= 1) {
            var newTabIndex = (tabIndex == 0 && this.prevTabIndex == -1) ? tabIndex : this.prevTabIndex;
            this.currentTab = this._tabs[newTabIndex];
            this.currentTabContent = this._tabContents[newTabIndex];
            this.currentTab.activate();
            this.currentTabContent.show(); // this is will display it as it would be hidden.
            VBR.updateTitle(this._paths[newTabIndex]);
        } else {
            this.currentTab = null;
            this.currentTabContent = null;
            this.toggleBg(true);
            VBR.updateTitle();
        }
    },

    closeTab: function() {
        if(this.tabBar) {
            if(this.tabBar.tabList_.length >= 1) {
                var currentTabIndex = this._paths.indexOf(this.currentTab.options.pathName);
                this.removeTab(currentTabIndex);
            }
        }
    },

    nextTab: function(event) {
        if(this.tabBar) {
            if(this.tabBar.tabList_.length > 1) {
                var tabIndex = this._paths.indexOf(this.currentTab.options.pathName);
                this.prevTab = this.currentTab

                if (tabIndex < (this._tabs.length - 1)) {
                    var nextTabIndex = (tabIndex + 1);
                    
                    this.currentTab.deactivate();
                    this.currentTabContent.hide();

                    this.currentTab = this._tabs[nextTabIndex];
                    this.currentTabContent = this._tabContents[nextTabIndex];
                    
                    this.tabBar.scrollIntoView(nextTabIndex);
                    this.tabBar.foundation_.adapter_.activateTabAtIndex(nextTabIndex);
                    this.currentTabContent.show();
                } else {
                    return;
                }
            }
        }
    },

    prevTab: function(event) {
        if(this.tabBar) {
            if(this.tabBar.tabList_.length > 1) {
                var tabIndex = this._paths.indexOf(this.currentTab.options.pathName);
                this.prevTab = this.currentTab

                if (tabIndex > 0) {
                    // here nextTabIndex means the index of the prev tab to switch to.
                    var nextTabIndex = (tabIndex - 1);
                    
                    this.currentTab.deactivate();
                    this.currentTabContent.hide();

                    this.currentTab = this._tabs[nextTabIndex];
                    this.currentTabContent = this._tabContents[nextTabIndex];
                    
                    this.tabBar.scrollIntoView(nextTabIndex);
                    this.tabBar.foundation_.adapter_.activateTabAtIndex(nextTabIndex);
                    this.currentTabContent.show();
                } else {
                    return;
                }
            }
        }
    },

    _propagateClick: function() {
        window.dispatchEvent(new Event('mousedown'));
    }
})
`

**Comment by jjstanton** [comment]
Thank you @agnel! I'm sure it will help someone, if not me.
