### ISSUE TITLE
Outlined Text Field + Leading Icon Bug

### ISSUE THREAD

**Issue by robcaldecott** [material-components/material-components-web#1908]
Using an outlined text field with a leading icon, the floating label position is incorrect. This can be demonstrated using a simple React project.

https://github.com/robcaldecott/mdc-textfield

Clone the project, npm/yarn install and then npm/yarn start. Start typing in the text field.

### What MDC-Web Version are you using?

0.28.0

### What browser(s) is this bug affecting?

Chrome, Firefox and Edge

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

The following component shows the issue. Start typing to float the label and it ends up in the wrong position.

```js
class TextField extends React.Component {
  componentDidMount() {
    this.MDCComponent = new MDCTextField(this.textField);
  }

  render() {
    return (
      <label
        className="mdc-typography mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon"
        ref={textField => {
          this.textField = textField;
        }}
      >
        <i className="material-icons mdc-text-field__icon" tabIndex="0">
          event
        </i>
        <input type="text" id="tf-outlined" className="mdc-text-field__input" />
        <span className="mdc-text-field__label">Hint Text</span>
        <div className="mdc-text-field__outline">
          <svg>
            <path className="mdc-text-field__outline-path" />
          </svg>
        </div>
        <div className="mdc-text-field__idle-outline" />
      </label>
    );
  }
}
```

### What is the expected behavior?

The label should position correctly.

### What is the actual behavior?

The label is too far to the right and overlaps the outline border.

![Screen capture](https://lh3.googleusercontent.com/LsZfEU-pQ81zkBaMWECCApVpPgQEYgcdnw206LMBfgw-63ceGlM6TsAQZTOMY_-eJtlIl4nljUhX-YDBS3Lx=w3840-h1835)

https://drive.google.com/open?id=1tAZFr5Ho-F2t7dmsmbSDas8y0z8en80N

### Any other information you believe would be useful?

Link to a repo that shows the issue:

https://github.com/robcaldecott/mdc-textfield

**Comment by acdvorak** [comment]
Does #1858 solve this for you?

**Comment by acdvorak** [comment]
I'm assuming #1858 solves this; if not, feel free to reopen 🙂

**Comment by robcaldecott** [comment]
@acdvorak Still a problem with 0.29.0.

**Comment by robcaldecott** [comment]
@acdvorak Please can you reopen this? I have updated my sample.

https://github.com/robcaldecott/mdc-textfield

**Comment by bwobrien** [comment]
I noticed this working on my project too. I have a simple fix.
