### ISSUE TITLE
Textarea label shake position is incorrect for invalid fields

### ISSUE THREAD

**Issue by ruwaroshan** [material-components/material-components-web#1923]
### What MDC-Web Version are you using?

> 0.28.0

### What browser(s) is this bug affecting?

> All (Tested on Chome, Firefox, Mac Safari)

### What are the steps to reproduce the bug?

> 1. Create a mdc textarea as below.
```
<div class="mdc-text-field mdc-text-field--textarea">
  <textarea id="textarea" class="mdc-text-field__input" rows="8" cols="40"></textarea>
  <label for="textarea" class="mdc-text-field__label">Textarea Label</label>
</div>
```

> 2. Add html5 validation (**minlength="8"**).
```
<div class="mdc-text-field mdc-text-field--textarea">
  <textarea id="textarea" class="mdc-text-field__input" rows="8" cols="40" minlength="8"></textarea>
  <label for="textarea" class="mdc-text-field__label">Textarea Label</label>
</div>
```
> 3. Type fewer than 8 characters in textrea and tap outside. 
> 4. Invalid label will shake, but its position is incorrect.

### What is the expected behavior?

> Textarea label should be visible when invalid.

### What is the actual behavior?

> When textarea gets invalid, label position will not behave as expected.

Video: https://drive.google.com/open?id=1C_9bdYC9rnCMtWdcxAuouWiKv1MQu3ld

**Comment by acdvorak** [comment]
This might be fixed by #1882
