### ISSUE TITLE
Broken link in docs/team/README.md

### ISSUE THREAD

**Issue by chaficnajjar** [material-components/material-components-web#1929]
In the [current docs/team/README.md](https://github.com/material-components/material-components-web/blob/673a84d53554a5fc6fa28a635364d712ccb4bbcf/docs/team/README.md), the link "write design docs" is broken. The incorrect URL was introduced here: https://github.com/material-components/material-components-web/pull/1222/commits/afb682195ea0d8549c81f2a4200700fa62f1d254#diff-fa96be5fbabd1e1a0f6828b09621363aR5. It's not clear what the correct URL is and googling didn't help.

**Comment by acdvorak** [comment]
Thanks for filing this issue! I created PR #1929 to remove the broken link.
