### ISSUE TITLE
Wrong padding in horizontal blocks in cards

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#193]
Via @Kerrick:

> This only applies the bottom padding to the media-item in the last _card_, rather than the last > _media-item_ in the card. Is that desired? It certainly looks a bit strange.
>
> ![mdcdemo_and_feat_cards___horizontal_blocks____4685__ _material-components_material-components-web_6a39e35](https://cloud.githubusercontent.com/assets/552093/22082500/a2816bfe-dd8d-11e6-9b1e-a545fe49b35c.png)

**Comment by Kerrick** [comment]
I'm learning a lot about the library while implementing [the ember adapter](https://github.com/secondstreet/ember-material-components-web) :)

**Comment by amsheehan** [comment]
It's looking awesome! Keep up those issues coming!

**Comment by amsheehan** [comment]
According to the [spec](https://material.io/guidelines/components/cards.html#cards-content-blocks), bottom padding shouldn't exist on the media item for card layouts closest to this particular implementation. Take a look at the fifth and sixth examples from the bottom.

The conversation #4685 referenced above is scss that governs the last example on the [demo page](http://material-components-web.appspot.com/card.html) and is certainly causing your layout to behave the way it is, but the correct outcome will be that none of the media items will have bottom padding for the layout referenced in this issue.

I would suggest taking a look at [lists](https://material.io/guidelines/components/lists.html) for this specific use case, it looks like that would better serve the layout you're trying to achieve. [source](https://material.io/guidelines/components/cards.html#cards-usage)

@traviskaufman @sgomes thoughts?

**Comment by Kerrick** [comment]
> I would suggest taking a look at lists for this specific use case, it looks like that would better serve the layout you're trying to achieve. source

@amsheehan I definitely wasn't trying to achieve a certain layout by using multiple cards in that screenshot, I was just putting a bunch of example cards on a demo page. 👍

**Comment by amsheehan** [comment]
@Kerrick Right on. Definitely a good catch.
