### ISSUE TITLE
If there is a long content in MDC select box options, it flow beyond the mdc-layout-grid (Should have max width).

### ISSUE THREAD

**Issue by ruwaroshan** [material-components/material-components-web#1937]
### What MDC-Web Version are you using?

> 0.28.0

### What browser(s) is this bug affecting?

> All browsers and devices.

### What are the steps to reproduce the bug?

> 1. Add 2 column MDC Layout Grid.
```
<div class="mdc-layout-grid">
  <div class="mdc-layout-grid__inner">
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6">
    </div>
    <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6">
    </div>
  </div>
</div>
```
> 2. Implement MDC Select box.
```
<div class="mdc-layout-grid">
	<div class="mdc-layout-grid__inner">
		<div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6">
			---- Select Box ----
		</div>
		<div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6">
			---- Select Box ----
		</div>
	</div>
</div>
```
 
> 3. Add long content to option as follow.
```
<li class="mdc-list-item" role="option" tabindex="0">
        Bread, Cereal, Rice, Pasta, Milk, Yogurt, Cheese, Vegetables, Fruit, Meat, Poultry, Fish, Dry Beans, Eggs, and Nuts
</li>
```
> 3. Now Select boxes get overlap as below.

![select overlap](https://user-images.githubusercontent.com/12517126/34809142-1f24f5f0-f6b9-11e7-8b86-8b75304e50eb.png)

### What is the expected behavior?

> Select box should have max value or it should flow within the **mdc-layout-grid**.

### What is the actual behavior?

> When there is a long content in option, select box flow beyond the **mdc-layout-grid**.

**Comment by kmmbvnr** [comment]
I have to fix that with the craziest patch

```javascript
class MDCSelect extends mdc.select.MDCSelect {
  getDefaultFoundation() {
    let foundation = super.getDefaultFoundation();
    let superSetMenuStyle = foundation.setMenuStylesForOpenAtIndex_;

    foundation.resize = function() {
      /* no action here */
    };

    foundation.setMenuStylesForOpenAtIndex_ = function(index) {
      superSetMenuStyle.call(foundation, index);

      const rect = foundation.adapter_.computeBoundingRect();
      foundation.adapter_.setMenuElStyle('width', `${rect.width}px`);
    };

    return foundation;
  }
}
```

**Comment by acdvorak** [comment]
Thanks for filing this issue!

I _think_ the fix should be as simple as:

```css
.mdc-select {
  max-width: 100%;
}
```

Does that work for you? It seemed to do the trick in this [CodePen](https://codepen.io/acdvorak/pen/EoLbeG).

We should probably do this in MDC Web so clients don't have to add it themselves.

If that doesn't work for some reason, another option would be to create a modifier class (e.g., `mdc-select--max-width`) that instructs the foundation's `resize()` method to prevent the select from being wider than its parent (or something along those lines).

**Comment by kmmbvnr** [comment]
@acdvorak - this doesn't fix popup width.

**Comment by englishextra** [comment]
@acdvorak Does anyone know when that's gonna be fixed, or any other ideas?

```css
.mdc-select {
  max-width: 100%;
}
```
won't work
