### ISSUE TITLE
Snackbar requires 2 taps to trigger action on Safari on iPhone

### ISSUE THREAD

**Issue by taneliang** [material-components/material-components-web#1938]
### What MDC-Web Version are you using?

0.28.0 (latest)

### What browser(s) is this bug affecting?

Mobile Safari on all iPhones in portrait, and iPhone 4 and 5 sized iPhones in landscape. Probably affects all versions >= iOS 7, but can be reproduced on the latest: Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0 Mobile/15C202 Safari/604.1

### What OS are you using?

iOS 11.2.2

### What are the steps to reproduce the bug?

1. In Mobile Safari on an iPhone, go to https://material-components-web.appspot.com/snackbar.html
2. Scroll up until the "Show" buttons are visible. Ensure that Safari's bottom toolbar is hidden
3. Tap any of the "Show" buttons
4. Tap "Undo".

### What is the expected behavior?

The action is triggered and the snackbar is dismissed.

### What is the actual behavior?

Safari's toolbar is shown and the action is not triggered. A second tap of Undo is required to trigger the expected behaviour.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

Unfortunately, what you're seeing is native browser behavior, and there's probably nothing we can do about it 🙁 

Safari displays the bottom toolbar whenever you tap near the bottom of the page, regardless of whether there's a snackbar there or not, and I strongly suspect there's no sane way to detect and/or prevent that behavior.

That said, if you (or someone else in the community) find a clever way to prevent Safari from showing the toolbar, feel free to reopen this issue and we'll investigate!
