### ISSUE TITLE
How can I set text-field value with Javascript?

### ISSUE THREAD

**Issue by ljcucc** [material-components/material-components-web#1958]
I can't find any method call "`setValue`" inside `MDCTextFieldFoundation` object after I create it
``` javascript
new mdc.textField.MDCTextFieldFoundation(mdc.textField.MDCTextField.attachTo(document.querySelector("#username")))
```
how could I call setValue from this object like the documents said. https://material.io/components/web/catalog/input-controls/text-field/

Cause I want to set text field value with Javascript, but it doesn't work at all:
```html
<div id="username" class="mdc-text-field" style="width:100%;">
    <input type="text" id="username-input" class="mdc-text-field__input" aria-controls="username-help">
    <label for="username-input" class="mdc-text-field__label">Display name</label>
    <div class="mdc-text-field__bottom-line"></div>
</div>
```
```javascript
//+jQuery
$("#username-input").val(user.name)
//or maybe this way
var username = new mdc.textField.MDCTextFieldFoundation(mdc.textField.MDCTextField.attachTo(document.querySelector("#username")))
username.setValue(user.name)
```
how could I do?

**Comment by ljcucc** [comment]
should I using this code or there's have other better ways?
```javascript
document.querySelector("#username").querySelector("label").classList.add("mdc-text-field__label--float-above")
```

**Comment by acdvorak** [comment]
It looks like you're trying to instantiate the _foundation_ class.

Instead, you should create a new `MDCTextField` 🙂 

From the [text-field demo page][demo] ([source][]):

[demo]: https://material-components-web.appspot.com/text-field.html
[source]: https://github.com/material-components/material-components-web/blob/31aa2888b28cd95add6a8fd92ce20aed7c9c17c2/demos/text-field.html#L194-L195

```
var el = document.querySelector('#username');
var tf = mdc.textField.MDCTextField(el);
tf.value = 'foo';
```

**Comment by ljcucc** [comment]
Thanks @acdvorak

**Comment by pmaclot** [comment]
@ljcucc, to call the methods, you must go through the property foundation

`import {MDCTextFieldHelperText} from '@material/textfield/helper-text';

const helperText = new MDCTextFieldHelperText(document.querySelector('.mdc-text-field-helper-text'))
helperText.foundation.setValidity(true);
helperText.foundation.setContent("Username is required");`

**Comment by pmaclot** [comment]
@ljcucc, to call the methods, you must go through the property foundation


```
import {MDCTextFieldHelperText} from '@material/textfield/helper-text';

const helperText = new MDCTextFieldHelperText(document.querySelector('.mdc-text-field-helper-text'))
helperText.foundation.setValidity(true);
helperText.foundation.setContent("Username is required");
```

**Comment by kfranqueiro** [comment]
You should never need to invoke foundation APIs directly just to use our components. Foundations should only need to be used directly if you're making a library that wraps our components for another environment/framework.

You should also not have a reason to instantiate the helper-text subcomponent directly (to address @pmaclot's particular example, though the original issue was only asking about setting value). The MDCTextField component already instantiates this for you, and exposes a `helperTextContent` property setter for updating its text.

If you ever find a case where you're finding yourself needing to invoke foundation APIs directly, please raise an issue - maybe it's just that there's a component API we should expose (or one already exists).
