### ISSUE TITLE
Investigate making slidable drawer open when swiping from the left side of the screen

### ISSUE THREAD

**Issue by jonhue** [material-components/material-components-web#1976]
The current implementation of the temporary drawer element allows users to close it by swiping to the left. However it does not recognize attempts to open the drawer by swiping from the left edge of the screen to the middle.

All native Android apps I've come across that use the drawer element have this functionality.

From a UX perspective this also appears to be very smart. It simplifies opening the drawer with just one hand and provides great feedback to the user for his action.

The current implementation of gestures on the temporary drawer element feels incomplete as it implements the closing but not the opening gesture.

Are there any plans to support this gesture in the near future?

**Comment by acdvorak** [comment]
Thanks for filing this issue!

I totally get where you're coming from, and I agree that our current behavior is inconsistent.

I would _love_ to implement this feature, but I suspect it would be very difficult to do correctly.

In JS, at the time we receive a `touch` event, it's really hard to know if the user _actually_ wants to open the nav drawer, or if they're trying to do something else (or another piece of software _thinks_ they're trying to do something else).

What's more, even if we somehow manage to determine the user's intent, _preventing_ the browser (or other frameworks on the page) from performing its default behavior ranges from _difficult_ to _literally impossible_, depending on the browser or framework (I'm looking at you, Edge and IE 11 💩 ).

As a result, getting the UX right - even in common use cases - is tricky, time-consuming, and hard to test programmatically.

Coincidentally, I recently spent several weeks working on a toy drag-and-drop prototype, and it convinced me that fighting with browser's native gestures is a long, painful, and ultimately losing battle; in most cases, it's probably not worth the massive investment of time and effort required to get it right.

Just a few examples of the landmines I ran into:

1. Swiping from the left side of the screen to the right to go back in the tab's browsing history
2. Full-bleed carousels (e.g., [Google Search](https://www.google.com/search?q=congress) on mobile)
3. Text selection
4. Force Touch

Much as I would love to implement this, I'm not sure when (if ever) we would have the bandwidth.

But if someone from the community wants to send us a bullet-proof PR, we're more than happy to review it 😄

**Comment by jonhue** [comment]
I totally agree with you saying that implementing this feature without thinking about potential consequences to UX can lead to some loopholes of unwanted behavior.

However, expanding on the idea of potential/eventual UX bugs, they should really be the implementors and not the framework developers concern. As you pointed out correctly, the prediction of and adoption  to environments a framework or library could be used in is a merely impossible task.

A possible way to integrate a feature that could potentially break UX in apps is to make it optional (perhaps with a class) and thus raise awareness of the developer implementing the feature.

**Comment by moog16** [comment]
Closing issue for new MDC Drawer issues https://github.com/material-components/material-components-web/issues/2903.
