### ISSUE TITLE
Textfield initialize with evaluation of input.value

### ISSUE THREAD

**Issue by miguel-orange** [material-components/material-components-web#198]
In regards to MDCTextfieldFoundation init(). I could see utility in having `LABEL_FLOAT_ABOVE` when input.value is pre-populated. Such as an edit scenario, data is retrieved, and input field is pre-populated. In current state, label overlaps value, and they are both unreadable.
```javascript
init() {
   // ...
   const input = this.getNativeInput_();

   if (input.value) {
      this.adapter_.addClassFromLabel(LABEL_FLOAT_ABOVE);
    }
}
```

**Comment by traviskaufman** [comment]
Hey @miguel-orange,

I imagine this is an issue you're experience when generating HTML server-side and getting an incorrect first render? If that's the issue, have you looked at our docs on [pre-filled text fields](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#pre-filled-text-fields)? It provides a strategy for dealing with this case.

Even if we were to add that logic, it wouldn't take hold until the JS was loaded and initialized, so you still may get a FOUC.

**Comment by traviskaufman** [comment]
Closing; potential workaround outlined above.
