### ISSUE TITLE
Changing all directory import statements to explicitly import index.js

### ISSUE THREAD

**Issue by jpray** [material-components/material-components-web#1991]
Hi, I love this project!  Would you all consider accepting a PR that changed all directory import statements from `import './foo'` to `import './foo/index.js'`?  I know node and webpack support the current style but other module loaders like systemjs don't.  Thanks for considering this.

**Comment by bonniezhou** [comment]
MDC Web only intends to support the formats listed in [importing-js.md](https://github.com/material-components/material-components-web/blob/master/docs/importing-js.md).
However we encourage you to ask SystemJS to add support for the `import './foo'` syntax!

**Comment by jpray** [comment]
Bummer, I mean, the syntax is still ES2015.  The issue is just that having /index.js be implicit isn't part of any standard loader spec that I know of.  So a module loader that sticks strictly to a standard like whatwg loader can't support this... and this makes since because it would be bad for a browser to make multiple calls to the server seeing if foo.js or foo/index.js existed.  

It wouldn't be a breaking change.  I'd include tests in the PR. :)

**Comment by bonniezhou** [comment]
Ok...you've convinced us. :) However we still think that the `import {...} from 'path/to/index'` (without the `.js` extension) makes most sense, as per http://2ality.com/2014/09/es6-modules-final.html. Adding @kfranqueiro and @acdvorak to this thread in case they want to speak more on it.

Feel free to submit a pull request that:
- [ ] changes all directory imports from `import './foo'` to `import './foo/index'`

**Comment by jpray** [comment]
Sweet!  I'm fine with omitting the '.js' part.  I've submitted https://github.com/material-components/material-components-web/pull/2111 for this issue.
