### ISSUE TITLE
@material/icon-toggle README Adapter API Documentation Has Mis-Named Methods

### ISSUE THREAD

**Issue by Kerrick** [material-components/material-components-web#200]
In [README.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-icon-toggle/README.md) for [`@material/icon-toggle`](https://github.com/material-components/material-components-web/tree/master/packages/mdc-toggle), there is no mention of [`MDCIconToggleFoundation.toggle(isDisabled: boolean) => void`](https://github.com/material-components/material-components-web/blob/master/packages/mdc-icon-toggle/README.md#mdcicontogglefoundationtoggleisdisabled-boolean--void) in the "Full foundation API" section, seems to be mis-named. I believe it should be `MDCIconToggleFoundation.setDisabled(isDisabled: boolean => void` as it is used [here](https://github.com/material-components/material-components-web/blob/master/packages/mdc-icon-toggle/foundation.js#L146).

**Comment by traviskaufman** [comment]
It looks like we mislabeled `setDisabled` to `toggle`. Sorry about that 😅 will submit a PR with a fix.

**Comment by Kerrick** [comment]
No problem, thanks! I don't have a CLA signed yet so I couldn't just submit a PR.

**Comment by traviskaufman** [comment]
No problem; thanks for reporting the issue nonetheless!
