### ISSUE TITLE
Moving "will-change" to ripple surface causes side effects on mdc-button on chrome mobile.

### ISSUE THREAD

**Issue by theenoahmason** [material-components/material-components-web#2027]
##Bug

### What MDC Web Version are you using?

0.28

### What browser(s) is this bug affecting?

chrome 63.0.3239.111

### What OS are you using?

Android 7.0.0

### What are the steps to reproduce the bug?

> Problem is not happening on your button demo pages, but it is happening on 2 seperate react projects I am working on.

Make a simple button component in react with mdc-button class. 

Instantiate ripples as new MDCRipple(el). on componentDidMount(). Save instance of ripple to state. Destroy ripple on componentWillUnmount().

add 20 buttons on a page.

visit page in chrome.

### What is the expected behavior?

buttons with ripples should work without paint side effects on the page, even with a lot of buttons on the page.

### What is the actual behavior?

buttons with ripples work if there is only one or two, but when there are many, paint side effects happen all around the button, sometimes the button does not appear visually at all.

### Any other information you believe would be useful?

In 0.28 you moved will-change from :before and :after to the ripple surface. Removing will-change from the button surface fixes all issues with no side effects whatsoever, even with dozens of buttons on the page.

**Comment by bonniezhou** [comment]
Could you provide a Codepen of the issue?
Adding @kfranqueiro who's been working with this directly.

**Comment by theenoahmason** [comment]
Sure, I'll get on that tonight.

**Comment by theenoahmason** [comment]
I can't reproduce this. I'm going to close this issue as this seems to be my problem, not yours.
