### ISSUE TITLE
Strange mdc-toolbar__icon alignment with specific ligatures

### ISSUE THREAD

**Issue by jamesmfriedman** [material-components/material-components-web#2028]
### What MDC Web Version are you using?

> 28

### What browser(s) is this bug affecting?

> Chrome

### What OS are you using?

> Mac OS

### What are the steps to reproduce the bug?

Using the Toolbar Component, create an icon with more_vertical or more_horizontal
```html
<header class="mdc-toolbar mdc-toolbar--flexible-space-maximized">
  <div class=" mdc-toolbar__row">
    <section class=" mdc-toolbar__section mdc-toolbar__section--align-start">
      <i class="material-icons  mdc-toolbar__menu-icon ">arrow_back</i>
      <div class=" mdc-toolbar__title">Standard</div>
    </section>
    <section class=" mdc-toolbar__section mdc-toolbar__section--align-end">
      <a class="material-icons  mdc-toolbar__icon ">more_horizontal</a>
      <a class="material-icons  mdc-toolbar__icon ">search</a>
    </section>
  </div>
</header>
```

### What is the expected behavior?
Here are the results of a very very strange bug. Possibly something wrong with material-icons? The only difference here is the icon being used. more_vertical and more_horizontal result in excessive whitespace. The size of the element can be fixed with max-width, but the character is still misaligned.

![image](https://user-images.githubusercontent.com/975256/35231532-16a56890-ff67-11e7-8f9c-06e83baa54c8.png)

### Any other information you believe would be useful?

The issue appears to be related to flex-box and these specific ligatures. A tentative fix...

```css
.mdc-toolbar__icon {
  max-width: 1.5rem;
  display: block;
}
```
![image](https://user-images.githubusercontent.com/975256/35231858-e2e9fff6-ff67-11e7-9c64-15dc70e968cd.png)

**Comment by bonniezhou** [comment]
Looks like a bug, thanks! We'll let the Icons team know and circle back.

**Comment by bonniezhou** [comment]
It turns out that the names of the icons are `more_horiz` (not `more_horizontal`) and `more_vert` (not `more_vertical`). Updating the names should fix the spacing issue.

**Comment by jamesmfriedman** [comment]
Wow, thats incredibly embarrassing! Good catch, thats pretty funny mistake.
