### ISSUE TITLE
label issue with textfield

### ISSUE THREAD

**Issue by Whiteseeker** [material-components/material-components-web#203]
When using the full-width multiline textfield with javascript enable, the label is missplaced (once you clicked on it to get focus and enter the text, it's missplaced).

For context this is the code I used to repro the issue:
```
<div id="story_content" class="mdc-textfield mdc-textfield--multiline mdc-textfield--fullwidth">
    <textarea id="story_area" class="mdc-textfield__input" rows="8" cols="40"></textarea>
    <label for="story_area" class="mdc-textfield__label">Content</label>
</div>
```

and later on I initialise it like:
`new mdc.textfield.MDCTextfield(document.querySelector('#story_content'));`

**Comment by sgomes** [comment]
Thanks, @Whiteseeker!

Codepen here: http://codepen.io/anon/pen/BpZKLB

Looks like it might have been fixed already, but I'm not sure about the position the label is moving to. @traviskaufman Does this look right?

**Comment by traviskaufman** [comment]
Hey @Whiteseeker,

It looks like you're using the wrong DOM here for full-width text fields. The correct DOM can be found at https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#full-width, specifically the second div in that example:

```html
<div class="mdc-textfield mdc-textfield--multiline mdc-textfield--fullwidth">
  <textarea class="mdc-textfield__input"
            placeholder="Full-Width multiline textfield"
            rows="8" cols="40"
            aria-label="Full-Width multiline textfield"></textarea>
</div>
```

Here is a corrected pen: http://codepen.io/traviskaufman/pen/PWjzbW

Hope that helps.
