### ISSUE TITLE
Project status update?

### ISSUE THREAD

**Issue by djensen47** [material-components/material-components-web#2030]
I think this is a great project, a great community, and it produces high quality code but it feels like it's in a constant state of refactor getting further (not closer) from a beta release. If you look at the change log, each release seems to have more breaking changes than anything else. I do also understand the breaking changes are making things better.

**Would it be possible to get a higher level status of the project to understand what is going on?**

I realize mdc web is pre-beta but it's been that way for a _very_ long time plus it is really, really difficult to keep up when the basics (like buttons and fields) break every 2-4 weeks. If we had one of the project leads explain the high level goals and/or a high level roadmap, I think it would help. Dates are not as important as understanding what "done" looks like for version 1.0.0 and I currently feel like "done" isn't visible to the community. I took a look at Pivotal Tracker, and I can see awesome progress but I can't see the direction.

Again, kudos, great project, great work, just want to know where it's all going. Thanks ... and sorry, my engineering manager "dark side" really wanted to come out and say something. 😉

**Comment by djensen47** [comment]
To use a cliche, I'm having trouble seeing the forest through the trees. 😃

**Comment by lynnjepsen** [comment]
> but it feels like it's in a constant state of refactor getting further (not closer) from a beta release

This is true. We've put our beta release on hold in order to focus on implementing the changes being made to the Material guidelines—so keep an eye out for these changes on our official [Material guidelines](https://material.io/guidelines). 

I can't say much more about "done" is yet...but stay tuned by following the [Material Design blog], or follow @materialdesign on Twitter.

**Comment by djensen47** [comment]
Thanks!
