### ISSUE TITLE
Offsetting columns

### ISSUE THREAD

**Issue by dirago** [material-components/material-components-web#2040]
### What MDC Web Version are you using?

> layout-grid@0.24.0

### Question

Hello there,

Is there a system of offset like in Bootstrap (sorry) which allow us to push columns ?

My problem is that assuming I have 12 columns, I have to put 2 elements which are sized by 4 columns as follows: X O O O O X X O O O O X where the Xs have to be empty spaces, I have not found my answer in the doc ;/

Thanks in advance :)

**Comment by TangSteven** [comment]
Yes there indeed is a column system in MDC's layout-grid, it uses this format: `mdc-layout-grid__cell--span-<NUMBER_OF_COLUMNS>`.

The documentation for this is here: https://material.io/components/web/catalog/layout-grid/#mdc-layout-grid__cell--span-number_of_columns

An example:
```html
<div class="mdc-layout-grid__inner">
  <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1"></div>
  <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-4"></div>
  <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2"></div>
  <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-4"></div>
  <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1"></div>
</div>
```
<img width="590" alt="capture" src="https://user-images.githubusercontent.com/18170455/35370664-6c2c837a-014c-11e8-8cc7-4c7c143679f6.PNG">

**Comment by dirago** [comment]
I was using this at the beginning but I thought it is kind of dirty but it works !

I just found a solution with `grid-column-start` ([doc](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-start))

My first div: `grid-column-start: 2`
The second one: `grid-column-start: 8`

**Comment by dirago** [comment]
Feel free to close this issue or if someone wants to discuss of both solutions, I'm open!

**Comment by bonniezhou** [comment]
@TangSteven's solution is the one that uses MDC Web.
But if the `grid-column-start` solution works for you then that's great!

**Comment by jacobfederer** [comment]
Both above solutions don't work for me. My problem is that you cannot set a zero span for the offset columns on certain devices. I'm currently trying to achieve the following:

Layout on desktop:
X X X O O O O O O X X X
X X X O O O O O O X X X

Layout on mobile:
O O O O
O O O O

**Comment by rikvdk** [comment]
To hide the offset columns on mobile you could also add a modifier class to hide it on mobile:

    @include mdc-layout-grid-media-query_(phone) {
      .mdc-layout-grid__cell--hide-phone {
        display: none;
      }
    }
