### ISSUE TITLE
Issues with state transitions for mdc-checkbox

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2047]
There are several related issues:

1. Checked -> Unchecked animation is incorrect for JS-enabled checkboxes. The mark abruptly disappears, and then the container color abruptly changes. CSS-only checkboxes are fine.
2. The animations that occur while transitioning between states have incorrect start/end colors if the checkbox has custom unmarked and/or marked colors.
3. Foundation doesn't correctly handle a situation where the checkbox is initially checked or indeterminate and is then unchecked. It applies the wrong animation.

Possible culprits:

1. The `mdc-checkbox-mark-animation-keyframes` mixin assumes that the `from`/`to` colors are always the default `$mdc-checkbox-border-color`. If the user customizes the stroke color, that assumption no longer holds.
2. The foundation class constructor initializes `this.currentCheckState_ = strings.TRANSITION_STATE_INIT`. This fails when the initial state is `checked` or `indeterminate`. Instead, it should initialize to `this.determineCheckState_(this.getNativeControl_())`.

**Comment by patrickrodee** [comment]
1. Fixed in #2122 
2. Still working - not sure if still a problem
3. Still working
