### ISSUE TITLE
Modular Design Question: TabBarScroller and TabBar

### ISSUE THREAD

**Issue by jamesmfriedman** [material-components/material-components-web#2067]
Currently, TabBarScroller will auto-init any TabBar that's a child of it when its constructor is called. I can completely understand why this would be nice and convenient in a plain JS / HTML context.

For RMWC (React) and other component based frameworks, this situation gets a little more complicated. Basically, we had to jump through hoops to pass around the instance of the TabBar that was created by the scroller and it resulted in a lot of weird patterns that only apply in this one specific case.

It would have been helpful to have been able to tell the Scroller to NOT init the TabBar, but I'm not sure if the Scroller actually needs the TabBar instance.

Feel free to close this with a won't fix, but figured I'd bring it up just to check.

**Comment by theenoahmason** [comment]
@jamesmfriedman I just dealt with this last night. I am also working on a set of react components, I am assuming you were using your already built tab bar component inside of your scroller.

What I did instead, was include the markup for the outermost tab bar inside the scroller., what this means is that you wrap your Tabs in TabBarScroller **or** TabBar, not both.

**Comment by jamesmfriedman** [comment]
I feel like an idiot that I didn’t think of that. Definitely took the long way around that one. Going to refactor for the next release!

**Comment by theenoahmason** [comment]
Boom!

**Comment by jamesmfriedman** [comment]
Well it seemed like it could have been that easy, but there are still a fair amount of inconsistencies to account for. I still have my original question since it does seem to be a unique pattern to the tab bar
