### ISSUE TITLE
Consider relocating Ripple utils.

### ISSUE THREAD

**Issue by bwobrien** [material-components/material-components-web#2075]
Most of the methods in Ripple are not specific to Ripple, but are general CSS helper methods. I've found them useful to use in my project, but it's somewhat odd having code depend on Ripple that doesn't actually have a Ripple. It'd be nice to move these to a more central, shared location.

**Comment by kfranqueiro** [comment]
See #1104

**Comment by bwobrien** [comment]
Sorry, I should have done a better issue search. Thanks!
