### ISSUE TITLE
Text-Field fullwidth input missing padding

### ISSUE THREAD

**Issue by j-o-d-o** [material-components/material-components-web#2087]
## Bug
Text-Field has no padding on <input/> element when mdc-text-field--fullwidth class is used.

### What MDC Web Version are you using?
0.29.0

### What browser(s) is this bug affecting?
all

### What are the steps to reproduce the bug?
https://codepen.io/j-o-d-o/pen/zppEdL

### What is the expected behavior?
Input should have padding (left). 

### What is the actual behavior
When fullwidth is used, the input has no padding.

**Comment by bonniezhou** [comment]
Thanks for filing this issue!
The box and outlined styles aren't meant to be used with full-width text fields, #2107 updates the README with this.

**Comment by j-o-d-o** [comment]
Ah okay, I thought just labels shouldn't be used with full-width. Sorry.
