### ISSUE TITLE
Incorrect changelog generation

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#209]
Automatic changelog generation isn't taking into account previous releases, and incorrectly generates a cumulative changelog of every change since the first release.

**Comment by BBosman** [comment]
I did some investigating and these are my findings:

`conventional-changelog` uses `git-semver-tags` to execute `git log --decorate --no-color` and parses the response with the regex `/tag:\s*(.+?)[,\)]/gi` to generate a list of tags on the repository. This results in the following list of tags:
- @material-components-web@0.3.0
- @material/typography@0.1.1
- @material/theme@0.1.1
- @material/textfield@0.2.0
- @material/snackbar@0.1.2
- @material/select@0.2.0
- [Many more which have been clipped for brevity]
- v0.1.1
- v0.1.0

It will then pass these through `semver.valid`, resulting in this list:
- v0.1.1
- v0.1.0

The others are considered invalid semver.

As you can see, it will consider `0.1.1` the last released version and will therefore generate a `CHANGELOG.MD` from that version on.

Easiest solution would be to also tag a semver compliant `v0.x.x` when tagging the `@material-components-web@0.x.x` one.

**Comment by traviskaufman** [comment]
@BBosman I like that suggestion of tagging an overall semver tag; it's probably a good practice for the repo anyway.
