### ISSUE TITLE
Tab styles do not update when [de]/activating tab via MDCTab API

### ISSUE THREAD

**Issue by TimeBandit** [material-components/material-components-web#2090]
### What MDC Web Version are you using?
material/tabs ^0.28.0

### What browser(s) is this bug affecting?
Version 64.0.3282.119 (Official Build) (64-bit)

### What OS are you using?
ubuntu 16.04 LTS

### What are the steps to reproduce the bug?
![material-components-tab-issue](https://user-images.githubusercontent.com/2059850/35390738-5d421626-01d4-11e8-818c-b531cf040896.gif)

1. I am creating an app skeleton where tab selection dynamically loads content . The url path and header titles are also modified as per the selected tab.
2. A listener has been bound to window for the `popstate` event. This is fired each time the browser `back`/`forward` buttons are clicked.
3. The correct tab should be activated on each `popstate` firing.
4. As per the graphic; what is seen is that the highlighted bottom border is moved to the correct tab but the shading remains on the last tab that was manually clicked.
5. What seems to be happening is that the element `.mdc-tab.mdc-ripple-upgraded::before, .mdc-tab.mdc-ripple-upgraded::after` remains tied to the previous tab that was mouse clicked but is also referenced by the newly activated(via the API) tab.

These are the key snippets:
```
// import the component
import {
    MDCTabBar,
    MDCTabBarFoundation
} from '@material/tabs';

// activate the correct tab
function activateCorrectTab(newActiveTabIndex) {

    const oldActiveTabIndex = tabMenus.mobile.activeTabIndex;
    const vals = {
        old: oldActiveTabIndex,
        new: newActiveTabIndex
    }
    console.table(vals);

    // deactivate previous tab
    tabMenus.mobile.tabs[oldActiveTabIndex].isActive = false;
    // activate new tab
    tabMenus.mobile.activeTabIndex = newActiveTabIndex;
}

// add the event listener for the popstate event
window.addEventListener("popstate", function (event) {
    event.preventDefault();

    crossroads.parse(document.location.pathname);
    // which tab to activate
    const tabs = tabMenus.mobile.tabs;
    // console.log(tabs);

    const activeTabPosition = tabs.findIndex((child) => {
        return child.root_.getAttribute("href") === document.location.pathname;
    })
    activateCorrectTab(activeTabPosition)
    // set the title
    const newTitle = tabs[activeTabPosition].root_.dataset.name
    document.querySelector('.mdc-toolbar__title').innerHTML = newTitle;

});
```
and the HTML
```
.mdc-toolbar__row
	.mdc-toolbar__section
		section.menubar
			nav.mdc-tab-bar.mdc-tab-bar--indicator-accent.menubar__mobile(role='tablist')
				a.mdc-tab.mdc-tab--with-icon-and-text.mdc-tab--active(href='/search' data-name="Search")
					i.material-icons.mdc-tab__icon(aria-hidden='true') search
				a.mdc-tab.mdc-tab--with-icon-and-text(href='/favourites' data-name="Favourite")
					i.material-icons.mdc-tab__icon(aria-hidden='true') favorite
				a.mdc-tab.mdc-tab--with-icon-and-text(href='/inbox' data-name="Inbox")
					i.material-icons.mdc-tab__icon(aria-hidden='true') inbox
				a.mdc-tab.mdc-tab--with-icon-and-text(href='/checkout' data-name="Checkout")
					i.material-icons.mdc-tab__icon(aria-hidden='true') shopping_basket
				span.mdc-tab-bar__indicator
```

**Comment by bonniezhou** [comment]
This is actually working as intended, since the shading reflects the tab that has browser focus, not the tab that's active. 
But I agree that the user experience is kind of weird, so we recommend clearing focus upon browser `back`/`forward`.
