### ISSUE TITLE
Instantiating a component with its ID

### ISSUE THREAD

**Issue by gaspaonrocks** [material-components/material-components-web#2091]
## Question

I was wondering if it is planned to add a method in the components to set them by their id through
```javascript
let drawer = new mdc.drawer.MDCPersistentDrawer(document.querySelector('#mySpecificId'));
document.querySelector('#mySpecificButton').addEventListener('click', () => drawer.open = true);
```
I've looked through the sources and it doesn't seem like it's possible at all...

**Comment by Garbee** [comment]
Looks like what you're wanting is [documented as being possible](https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer#manual-instantiation) however, it doesn't seem to be implemented this way any longer code-wise. So the docs seem to need updating.

You should be able to call `attachTo` however to get what you desire.

`let drawer = mdc.drawer.MDCPersistentDrawer.attachTo(document.querySelector('#mySpecificId'));`

**Comment by bonniezhou** [comment]
Hey @gaspaonrocks, I'm not quite sure what you mean by setting components by their ID. To clarify, there are two ways that you can instantiate a component.

1. If you don't care about keeping the instance of the component: `mdc.drawer.MDCPersistentDrawer.attachTo(document.querySelector('#mySpecificId'));`
2. If you want to be able to access the component (in this case, `drawer`) later:
`let drawer = new MDCPersistentDrawer(document.querySelector('#mySpecificId'));`

The above two methods are documented [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer#automatic-instantiation), as Garbee mentioned.
Does this answer your question?

**Comment by gaspaonrocks** [comment]
Hey @bonniezhou,

By that I mean that you can target actions on a component by using `.querySelector()` and a `.myClass` selector. Since querySelector can point to an element by id or other attributes as the [doc](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) states, you just have to use a '#' instead of a dot '.'

After looking in the source code, when passing an argument to a component constructor, it looks through its classList, but it never mentions ids or attributes...

```javascript
return new MDCTemporaryDrawerFoundation({
      addClass: (className) => this.root_.classList.add(className),
      removeClass: (className) => this.root_.classList.remove(className),
      hasClass: (className) => this.root_.classList.contains(className),
      addBodyClass: (className) => document.body.classList.add(className),
      removeBodyClass: (className) => document.body.classList.remove(className),
      eventTargetHasClass: (target, className) => target.classList.contains(className),
```
Also, when trying to use querySelector with an id, i got an error about classList being null, hence my question.

I must add that I haven't tried the attachTo method yet so I'll give it a spin, but it didn't seem like it could help me at the moment.

**Comment by bonniezhou** [comment]
You can use any kind of element selector (class, ID, etc.) you choose to instantiate your component. When you instantiate a component on an element, then the root of that component _is_ the element. 
For example, when you have an element with the ID `mySpecificId` and you create a new `MDCPersistentDrawer` on it, e.g.
```
let element = document.querySelector('#mySpecificId');
let drawer = new mdc.drawer.MDCPersistentDrawer(element);
```
then `drawer.root_` is equal to `document.querySelector('#mySpecificId')`.

If `classList` is null, that implies your selector doesn't exist. The two lines you wrote in your original issue is the correct way of instantiating a component using an ID selector, given that the element with the ID `mySpecificId` exists.

We recommend taking a look at the [getting started guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) to further understand how components are instantiated on elements.

**Comment by gaspaonrocks** [comment]
Hmm... looks like it might be because i'm using React... 

you can see in this [StackBlitz](https://stackblitz.com/edit/react-y8iiwf) that querySelector doesn't work with class or id...

Foundation constructor on the other hand works, so it looks like I need to rework my react components

I'm closing this issue.
