### ISSUE TITLE
Determine common method of focus handling

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#21]
e.g., focus trapping, input modality, etc. Essentially a common library of functionality for handling focus across all our components.

> Copied from https://github.com/google/material-design-lite/issues/4582

**Comment by traviskaufman** [comment]
@sgomes do we still want to work on this or can we close it?

**Comment by sgomes** [comment]
Let's close it for now. I don't think as much opportunity for code reused has presented itself as we expected.
