### ISSUE TITLE
Add ripple integration to checkboxes in framework examples

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#211]
Once we land #206, we need to update all of the framework examples which use checkbox to integrate ripples into it. This involves:

* building a ripple component for that framework
* integrating the ripple component into the checkboxes

- [x] React
- [ ] Angular2
- [ ] VueJS
- [ ] Aurelia

**Comment by traviskaufman** [comment]
@petejohanson @Thanood Any chance you'd be interested in working on the VueJS and Angular components to this issue, respectively? :)

**Comment by petejohanson** [comment]
@traviskaufman I would prefer not to have duplicate work between petejohanson/vue-mdc and the framework examples, at this point. It's on my list to implement for checkboxes/radio buttons in vue-mdc, once I complete that work, I will see if it can easily be brought in here for reference.

**Comment by tranrate** [comment]
@traviskaufman I am working on tranrate/aurelia-mdc. I've got checkboxes working but not yet got #206 and ripples working with checkboxes. As soon as I've got an initial version of aurelia-mdc I can bring it here for reference if that helps. @Thanood used the "Simple Approach" wrapping components. Aurelia-mdc will use foundations and adapters. Do you want to stick with the "Simple Approach" for your examples?

**Comment by traviskaufman** [comment]
@tranrate awesome! 

Since the Simple Approach method is the one used throughout our demos, if you do switch to the Foundations / Adapters approach I'd probably ask you to widen the scope of work to convert the demo entirely. Alternatively, you could remove the other components and just display the checkbox using that pattern. But it would indeed be strange to mix the two together, since users may not know what the best approach for Aurelia would be.

**Comment by tranrate** [comment]
@traviskaufman Once I've got the existing components working, I am probably going to convert your demo entirely as that will be a good initial test that everything works. For your examples it would be best to stick with the Simple Approach and then put links to projects like aurelia-mdc for people who don't want to reinvent the wheel. I will try and make time to check @Thanood's examples and see if they need much amendment to work with ripples.
