### ISSUE TITLE
Tab icons are the wrong color when using .mdc-theme--dark

### ISSUE THREAD

**Issue by theenoahmason** [material-components/material-components-web#2110]
### What MDC Web Version are you using?

0.28

### What browser(s) is this bug affecting?

Should be all, This is a CSS issue. checked on chrome, edge and firefox.

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

See your current demos of `mdc-tab-bar`, and click the button marked `Toggle Dark Theme`.

### What is the expected behavior?

tab icons should invert their color when the tab bar is a child of an element with `.mdc-theme--dark`.

![tabbarcolorfix](https://user-images.githubusercontent.com/15953314/35463084-eaf5b016-02bc-11e8-9fbb-a99093531ca1.gif)

### What is the actual behavior?

tab icons stay in their light context when the tab bar is a child of an element with `.mdc-theme--dark`.

![tabbarcolor](https://user-images.githubusercontent.com/15953314/35463091-f47f4ed0-02bc-11e8-821f-f68072cdc914.gif)

### Any other information you believe would be useful?

You are currently using:
```
.mdc-tab .mdc-tab__icon {
    color: rgba(0, 0, 0, 0.54);
    color: var(--mdc-theme-text-secondary-on-light, rgba(0, 0, 0, 0.54));
}
```

hover state:
```
.mdc-tab:hover .mdc-tab__icon {
    color: rgba(0, 0, 0, 0.87);
    color: var(--mdc-theme-text-primary-on-light, rgba(0, 0, 0, 0.87));
}
```

active state:
```
.mdc-tab--active .mdc-tab__icon {
    color: rgba(0, 0, 0, 0.87);
    color: var(--mdc-theme-text-primary-on-light, rgba(0, 0, 0, 0.87));
}
```

![tabbarcolor](https://user-images.githubusercontent.com/15953314/35463091-f47f4ed0-02bc-11e8-821f-f68072cdc914.gif)

## Solution

I am sure this is just an oversight, but your SASS should compile to the following in a dark context:

```
.mdc-theme--dark .mdc-tab .mdc-tab__icon {
    color: rgba(255, 255, 255, 0.7);
    color: var(--mdc-theme-text-secondary-on-dark, rgba(255, 255, 255, 0.7));
}
```

hover state:
```
.mdc-theme--dark .mdc-tab:hover .mdc-tab__icon {
    color: white;
    color: var(--mdc-theme-text-primary-on-dark, white);
}
```

active state:
```
.mdc-theme--dark .mdc-tab--active .mdc-tab__icon {
    color: white;
    color: var(--mdc-theme-text-primary-on-dark, white);
}
```
## A more efficient solution

Since the dark styles are already applied to the tab, and since the icon element will always be a child; just remove the current styles altogether, and allow the icon to inherit the color from it's tab. 

For example, I have remedied this in a project by adding the following alone (removing the above styles would remove the need for this, obviously):
```
.mdc-tab:hover .mdc-tab__icon, 
.mdc-tab--active .mdc-tab__icon, 
.mdc-tab .mdc-tab__icon {
	color: inherit;
}
```

![tabbarcolorfix](https://user-images.githubusercontent.com/15953314/35463084-eaf5b016-02bc-11e8-9fbb-a99093531ca1.gif)

**Comment by moog16** [comment]
Closing since we are removing dark theme (https://github.com/material-components/material-components-web/issues/2117#issuecomment-361767067)
