### ISSUE TITLE
CSS only tab indicator has a positioning bug, and is the wrong color when using .mdc-theme--dark

### ISSUE THREAD

**Issue by theenoahmason** [material-components/material-components-web#2117]
### What MDC Web Version are you using?

0.28

### What browser(s) is this bug affecting?

Should be all, this is a CSS issue, checked in chrome, edge and firefox.

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Visit the tab demos. 
**Positioning:** bug found in all CSS Only tabs. 
**Color:** bug found in all CSS Only tabs when using .mdc-theme--dark.

### What is the expected behavior?

**Positioning:** CSS Only tab indicator should reach the bottom of the tab, and should be centered.
**Color:** CSS Only tab indicator should invert it's color when using `.mdc-theme--dark`.

### What is the actual behavior?

**Positioning:** CSS Only tab indicator is 2px away from the bottom of the tab, and is aligned left.
**Color:** CSS Only tab indicator stays in it's light context when using `.mdc-theme--dark`

## Positioning

The CSS only tabs have the indicator **inside** the tab (`.mdc-tab__indicator`), whereas the JS tabs have their indicator **outside** the tab, in the tab bar itself (`.mdc-tab-bar__indicator`). 

Both, however, have a rule of `bottom: 2px`. This means that the tab indicator shows up a few pixels higher than the tab bar indicator, and is a few px too close to the tab text. The indicator is also 4px short, presumably so that the hover state and the active state don't touch as stated by `width: calc(100% - 4px);`. This means the indicator isn't centered.

![poscapture 10](https://user-images.githubusercontent.com/15953314/35464746-aa1bbdde-02c5-11e8-9589-cc3796bed363.png)

### Solution

Only the JS tab bar indicator needs the 2px bottom nudge, the CSS only tab indicator should sit at `bottom: 0;`. 

Also, Nudging the indicator 2px to the left splits the 4px "shortening" of the tab bar in half, and centers the indicator; while still leaving space between it, and the next one.

```
.mdc-tab__indicator {
    bottom: 0;
    left: 2px;
}
```

![poscapturefix 23](https://user-images.githubusercontent.com/15953314/35464762-b1c1d672-02c5-11e8-9e3f-fa3d20e749cb.png)

## Color

Like the icon in [#2110](https://github.com/material-components/material-components-web/issues/2110), The color of the CSS Only indicator is wrong when using `.mdc-theme--dark`.

Again, probably an oversight, but you are currently using the following for the light context, which handles both the tab indicator, and the tab bar indicator:
```
.mdc-tab-bar__indicator, 
.mdc-tab__indicator {
    background-color: rgba(0, 0, 0, 0.87);
    background-color: var(--mdc-theme-text-primary-on-light, rgba(0, 0, 0, 0.87));
}
```

However, for the dark context, you are only inverting the JS tab bar indicator:
```
.mdc-tab-bar--theme-dark .mdc-tab-bar__indicator, 
.mdc-theme--dark .mdc-tab-bar__indicator {
    background-color: white;
    background-color: var(--mdc-theme-text-primary-on-dark, white);
}
```

### Solution

Just add `.mdc-tab__indicator` appropriately to the SASS that compiles the above block. It is also worth noting here that the hover state of `.mdc-tab__indicator` is handled by a plain `opacity` rule, so this fix will also apply for the hover state.

Employing both fixes:

![tabindcolorfix](https://user-images.githubusercontent.com/15953314/35464618-d517e09a-02c4-11e8-9e8d-fd35523efce8.gif)

**Comment by moog16** [comment]
@theenoahmason you're right. `.mdc-tab__indicator` element should sit on the bottom of the tab, and does look better centered. I will make those changes. However, we are in the process of removing dark theme in favor of sass mixins (please see comments from https://github.com/material-components/material-components-web/pull/2106). 

As of today we removed it from tabs as well: https://github.com/material-components/material-components-web/pull/2105.
