### ISSUE TITLE
Investigate navigating tabs using left / right swipes

### ISSUE THREAD

**Issue by gedw99** [material-components/material-components-web#2119]
the library is getting very strong, and we are using this on a few projects on mobile, web and desktop.
One thing that would be great for user cognitive load is swipable tab navigation.

At the moment a user has to navigate by pressing on each tab, but Material Design allows swiping on the Tab's contents left or right to force a navigation.

It is a sensible move to implement this ?
If would mean event bubbling issues ?

**Comment by jamesmfriedman** [comment]
+1 would love this feature

**Comment by theenoahmason** [comment]
+10 (as I recall, MDL had this feature)

**Comment by carlabalbontin** [comment]
+1

**Comment by gedw99** [comment]
Ah never gonna happen. Only native GUI shall pass through thou gates :)

**Comment by theenoahmason** [comment]
@gedw99 Are you all still waiting for this? Just use Flickity by Metafizzy/Desandro. 

Problem solved.

**Comment by gedw99** [comment]
Is this what you mean ?

https://flickity.metafizzy.co/

It has a Commercial license !!!!  I did not know that github has become an
Advertorial site ....... :)

**Comment by theenoahmason** [comment]
@gedw99 it is open source, if you are using it for a commercial project there is a license. Don't use it if you think your application isn't worth it. 

Also your ellipsis is too long. 3 dots will suffice.

**Comment by gedw99** [comment]
Your worth it !

**Comment by theenoahmason** [comment]
@gedw99 "You're"
