### ISSUE TITLE
Multi-line text field box - feature request

### ISSUE THREAD

**Issue by TravisFolck** [material-components/material-components-web#2135]
We are using Material Design's [Multi-line text field box](https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes) in our designs. This is currently not available in MDC Web. What is the timeline for this component to be included? 

![ezgif-5-38379beb9f](https://user-images.githubusercontent.com/10664290/35575339-bf3b7112-05a1-11e8-9d68-92f2858fd172.gif)

**Comment by acdvorak** [comment]
At the moment, we don't have any specific timeline for adding this feature to MDC Web. We would certainly like to, but we have a lot of competing priorities and limited developer bandwidth 😕 

In the meantime, you can try a third party library (see below) if you're willing to live with the limitation that we currently only support the _outlined_ variant of multi-line text fields (i.e., `<textarea>` elements), **not** the _box_ variant shown in your (very helpful!) screenshot.

I haven't used it, but [Jack Moore's autosize lib](http://www.jacklmoore.com/autosize/) seems like it should do what you want
(`npm install autosize`).

Or, if you feel like doing more work, you can try the [jQuery autoSize plugin](https://github.com/acdvorak/jquery.autosize) I wrote a few years ago. It shouldn't be _too_ hard to fork the source and remove the jQuery/Underscore dependencies. Here's a [CodePen example](https://codepen.io/acdvorak/pen/zRzPXV) of it with `mdc-text-field--textarea`.

Sorry we don't have a better answer! 🙁
