### ISSUE TITLE
Text Field Box Bottom Line

### ISSUE THREAD

**Issue by TravisFolck** [material-components/material-components-web#2136]
### What MDC Web Version are you using?
0.29

### What are the steps to reproduce the bug?
There are two issues:

MDC Web shows the text field box bottom line to be 1px/1dp for idle state. Material Design states that the [bottom line should be 2 pixels (2dp) for idle state](https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes).

Also, per Material Design, the bottom corner radius should be 4px/4dp for text field box bottom line. It the corner radius is only applied to the top left and right corners. Can the 4px/dp radius also be applied to the bottom corners of the text field and line?

> **Bottom line**
> Thickness: 2dp
> Masked by rounded corners of rectangle

![image](https://user-images.githubusercontent.com/10664290/35576612-0f8d047a-05a5-11e8-9c46-a340f80b82d9.png)

**Comment by bonniezhou** [comment]
Hey @TravisFolck, thanks for the question! We're experimenting with various aspects of the Material Design System including the text field component. We're not yet certain if these changes are a good idea, but when we're ready the Material guidelines will be updated with all the details.
