### ISSUE TITLE
Drawer page handling

### ISSUE THREAD

**Issue by vorcigernix** [material-components/material-components-web#214]
It would be great to have mechanism similar to iron-pages in polymer. Implementing "SPA" like behaviour would require much less effort and page transitions would remain consistent with Material guidelines. I would prefer to have something like "pages" component with some class similar to mdc-permanent-drawer--selected indicating selected page.

**Comment by traviskaufman** [comment]
It seems like you're looking for API functionality that includes navigation management and page transitions. Unfortunately this is outside the scope of what MDC-Web provides, which is simply UI components. Any business-logic-like functionality would have to be used through another library.

That being said, it is totally possible to use iron-pages with MDC-Web. You simply wrap your page content within `<iron-pages>` and add event listeners to the drawer links which call the `iron-pages` API to select an appropriate page.
