### ISSUE TITLE
Bug: MDC Textfield / Icon / Tab Index changed to 0 by disabled call

### ISSUE THREAD

**Issue by MrChriZ** [material-components/material-components-web#2156]
### What MDC Web Version are you using?

Latest - 0.29.0

### What browser(s) is this bug affecting?

All

### What are the steps to reproduce the bug?

See codepen here:
https://codepen.io/MrChriZ/pen/MQwVrz

1. In demo insert text focus on textfield, then press tab.  Text focus moves away from the textfield as expected.
2.  Uncomment out the line:
myTextField.disabled=false;
3. Repeat text focus test.  This time the icon will be focused.

### What is the expected behavior?
The icon's tabindex is left alone/restored to it's original value allowing focus to move away from the textfield.

> Please describe what the component/code should be doing that it's not.
The icon's tabindex is left alone/restored to it's original value

### What is the actual behavior?
Dspite the fact that the icon is created with tabindex -1 the tabindex is being changed to 0 by the textfield/icon js. 
This occurs in textfield/icon/foundation.js javascript which changes the tabindex to 0 when disabled is set to false.

**Comment by bonniezhou** [comment]
Yup, this is a bug.

Feel free to submit a pull request that
- [ ] creates a private `enabledTabIndex_` field in `MDCTextFieldIconFoundation`
- [ ] remembers the value of `tabindex` before the icon is disabled, and restores it after the icon is reenabled
- [ ] adds a test

**Comment by MrChriZ** [comment]
I'm working on implementing this fix.  Is it reasonable to also set the icon tabindex to -1 if no tab index is specified?  

Technically the icon could be an info button... but most of the time I'd imagine it's more likely just a visual aid?

**Comment by MrChriZ** [comment]
Ignore my previous comment.
Is there a reason that in the demos the textfields are setup with a tabindex of 0?

**Comment by kfranqueiro** [comment]
Thanks for working on this. Some other changes were causing this branch to conflict with master now, so rather than force you to deal with that, I applied a similar solution against master in #2600.

**Comment by kfranqueiro** [comment]
Whoops, meant to leave my previous comment on the first PR.
