### ISSUE TITLE
Select: When menu is open, selecting another form field results in select being focused

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#2159]
### What MDC Web Version are you using?
0.29.0

### What browser(s) is this bug affecting?

Chrome Version 64.0.3282.119 (Official Build) (64-bit)

### What OS are you using?

Ubuntu 

### What are the steps to reproduce the bug?

1. Click a select to open the menu. 
2. While the menu is open, click into a text-field component. 
3. Notice focus go to the text-field, then immediately jump back to the select. 

### What is the expected behavior?

I would think the intended behavior is to focus on the text field component that was clicked. It could also be argued that the click off the menu should close the menu, but if that is the case, the click on the text field should not start the label float above animation. 

### What is the actual behavior?

The text field component receives focus, which starts the label floating animation. Then focus is returned to the select component, causing the label to return to it's original position. 

### Codepen
https://codepen.io/williamernest/pen/ddYdaa

**Comment by bonniezhou** [comment]
Added to tracker.

When the menu closes, we should check if there's a newly focused element (e.g., because the user clicked on a different focusable element outside the menu). If so, we shouldn't steal focus.

**Comment by williamernest** [comment]
Closing since this has been resolved with the new `menu-surface` component.
