### ISSUE TITLE
[bug] Select Field Max Width Should factor label

### ISSUE THREAD

**Issue by mgr34** [material-components/material-components-web#2166]
### What MDC Web Version are you using?

0.29.0

### What browser(s) is this bug affecting?

Chromium 63.0.3239.132 
Firefox 58

(all?)

### What OS are you using?
Linux (archlinux)

### What are the steps to reproduce the bug?

Set a label whose text length is greater than the largest text length of the menu/select options. The drop down arrow will overlay the label.

### What is the expected behavior?

That `maxTextLength` is the length of the largest piece of text. This sets the surface width. 

This should also measure label width?

### What is the actual behavior?

upon  initialization `resize()` is called. It looks at the select options and determines a max width which is set to the select surface. However, it does not factor in label size. 

For example if you have a label titled Page List. Whose text content is 1...10 max width would be derived from 10. This places the drop down icon over of the label. To be specific the `background-image`  set on `.mdc-select` overlays the label text. 

I believe this is because the label is longer than the text looked at to determine width.

### codepen (demo)

https://codepen.io/anon/pen/qxbmWm

**Comment by kfranqueiro** [comment]
Thanks for the report! I believe this is the same issue reported in #1835, which we already have tracked, so I'm going to close this one.

**Comment by mgr34** [comment]
Sure looks to be a dupe of #1835 to me as well. Sorry I overlooked that.
