### ISSUE TITLE
[bug] MDC-Select in css transform parent

### ISSUE THREAD

**Issue by RobertSmits** [material-components/material-components-web#2182]
There exists a problem in the MDCSelect that, when placed within a parent element with the `transform` css property, the menu gets positioned wrongly.
In [this pen](https://codepen.io/RobertSmits/pen/OQMGym) I used a select inside a dialog, but the dialog can be anything with the `transform` property.

The issue here is that the menu has `position: fixed` and gets calculated relative to the viewport.
But a `fixed` element gets positioned relative to the viewport or, for some absurd reason, relative to the nearest parent with a `transform` set to it.

**Comment by kfranqueiro** [comment]
Thanks for the report! This looks like the same issue as #719 which we already have tracked, so I'm closing this one.
