### ISSUE TITLE
More information on breaking changes

### ISSUE THREAD

**Issue by j-o-d-o** [material-components/material-components-web#2196]
So this might come off as whining, but would it be possible to add a little bit more information to the PRs? Especially when it is about breaking changes. Like, what's the reasoning, are there more to come in the future that are similar, etc. 

Just as an example, the latest removing of the cssOnly select the PR message is: 
> Remove css only version of select.

Just a little more information (like @kfranqueiro added later in the discussion as a response) would be nice to have : )

**Comment by kfranqueiro** [comment]
I agree we need to improve our habits as it pertains to explaining PRs (and sometimes also issues we enter ourselves). I think a lot of times we get caught up in sending something out that the team already may have some context on, then immediately hurrying on to working on the next thing, but that's bound to leave the wider community in the dark.

Our commit messages and changelog notes do kind of need to be kept brief, but we should still be able to include more info in PR descriptions.

Thanks for submitting this as a reminder. This has been nagging at the back of my mind too, and we talked about this a bit as a team today. For starters, I'll try to remind/encourage people to expand on issue/PR descriptions for major changes.

**Comment by leocaseiro** [comment]
In addition to that, wouldn't [SEM](https://semver.org/) version make our life easier?

I'm not sure what type of pattern for releases the team is using.
Something like 0.x.x. removing lot's of APIs, selectors and even themes(dark) are being removed. I understand this is an early project, so it should have beta/rc or similar in that case?

Using semantic version releases helps especially who are using Continuous Integration, as some releases have `npm install` or `npm update` that break style and sometimes scripts.

PS: I was going to open an issue, but I believe this one would be more appropriate.

Thanks in advance.
