### ISSUE TITLE
Toolbar: Items are not centered on non-webkit browser

### ISSUE THREAD

**Issue by jfily** [material-components/material-components-web#2199]
The problem occurs when the height of the toolbar is 64px

FF
![image](https://user-images.githubusercontent.com/10220170/35874803-c083584c-0b6d-11e8-852d-642edeaffd80.png)

Edge
![image](https://user-images.githubusercontent.com/10220170/35874818-cc08d1a6-0b6d-11e8-8adb-4fa02fd2696f.png)

Chrome
![image](https://user-images.githubusercontent.com/10220170/35874848-dedd17ec-0b6d-11e8-8580-0bf356554eda.png)

**Comment by kfranqueiro** [comment]
I think this is the same as #1296?

**Comment by jfily** [comment]
My bad, didn't see.
