### ISSUE TITLE
Select: Flash of unstyled content (FOUC) 

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#2202]
### What MDC Web Version are you using?

0.30.0

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

Ubuntu 16.x

### What are the steps to reproduce the bug?

Click the link
https://codepen.io/williamernest/pen/PQGjOL

### What is the expected behavior?

Before the javascript loads, a select should look like a select. 

### What is the actual behavior?

The select is condensed into a small space until the Javscript loads.

**Comment by kfranqueiro** [comment]
I'm not sure whether it's realistic to completely eliminate this flash, but Andy was at least pondering whether it'd be possible to get it to initially size based on the initial label/content.

**Comment by williamernest** [comment]
Resolved due to changing the `mdc-select` element to use the native select.
