### ISSUE TITLE
Ripple effect is not visile if it was initialized first with display:none

### ISSUE THREAD

**Issue by grosmar** [material-components/material-components-web#2207]
### What MDC Web Version are you using?
0.30.0

### What browser(s) is this bug affecting?
Chrome

### What OS are you using?
Windows

### What are the steps to reproduce the bug?
1. Render any component that should have a ripple effect with display:none (for example List or Button)
2. Change to display:block (or whatever visible
3. Click on the element to see the ripple effect

### What is the expected behavior?
It should have a proper visible ripple effect on it.

### What is the actual behavior?
Ripple effect is not visible, because it still uses the wrong computed layout because of display:none

### Any other information you believe would be useful?
I think it should be calculated right just before it gets rendered. Yes, manually you can update with layout(), but in the reactive framework that I use it's really hard and not nice, to reach some subchildren imperatively and tell it to layout().

**Comment by kfranqueiro** [comment]
Thanks for raising this issue.

AFAIK the original intent was to encourage `layout` as infrequently as possible, and also as early as possible to reduce any likelihood of jank when the user actually interacts with the component.

I can understand if there are some contexts in which reaching the individual ripple components to call `layout` could be problematic. We could stand to take another look at how it would perform if we simply call `layout` when the interaction happens.

If you happen to have an example illustrating where this is problematic, that could also be helpful.

**Comment by grosmar** [comment]
Thanks for looking into it.

IMO reading the sizes at the time of the click is not so expensive, and even more because it's not an automatic event, that happens for some system changes, but a user interaction, that is really rare (compare for example to some scroll events), I see no point of saving on the resource in this case.

Simple example:
Sometimes you want to render your view in advance, not only when it becomes active, so you will let it there with display:none, and only change it when you actually need.
