### ISSUE TITLE
@material/menu README Adapter Documentation Missing Methods

### ISSUE THREAD

**Issue by Kerrick** [material-components/material-components-web#221]
In [README.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/README.md) for [`@material/menu`](https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu), there is no mention of [`open`, `close`, and `isOpen`](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/foundation.js#L364-L394) in the "Using the Foundation Class" section, even though those adapter methods are provided by the foundation class.

**Comment by traviskaufman** [comment]
Definitely an oversight, thanks for filing!
