### ISSUE TITLE
aria role not allowed on aside (dialog) element (per w3c validator)

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#2226]
You guys notice this? I've tried `alertdialog`, `alert dialog`, `alert`, and `dialog` - they all fail to validate. Appears that the `aside` element doesn't allow it?

[Here's the actual w3c response](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmaterial-components-web.appspot.com%2Fdialog.html)

(note: same thing on the [mdc-tab](https://validator.w3.org/nu/?doc=http%3A%2F%2Fmaterial-components-web.appspot.com%2Ftabs.html). the role `tablist` won't validate. Several errors on the demo pages all araound. I'm not trying to be a smarta$$. My pages have errors too, but I'm going back and trying to clear them all up. ....just trying to help!)

![image](https://user-images.githubusercontent.com/12751611/36064814-94459664-0e56-11e8-815a-0287a1f610dc.png)

**Comment by kfranqueiro** [comment]
Thanks for pointing this out. We'll have to look into the effect of this and possible alternatives.

**Comment by kontrollanten** [comment]
Just change the element to `section` should be safe? https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L304

**Comment by abhiomkar** [comment]
Seems like MDCDialog no longer use `<aside>` tag for dialog. closing this.
