### ISSUE TITLE
Alignment between textfields and selects are off

### ISSUE THREAD

**Issue by rsouthgate** [material-components/material-components-web#2227]
### What MDC Web Version are you using?
0.29.0

### What browser(s) is this bug affecting?
All

### What OS are you using?
Mac OS

### What are the steps to reproduce the bug?
https://codepen.io/anon/pen/aqWoRP

Take a look at the codepen. The underline should be visually aligned vertically, but is not.

**Comment by kfranqueiro** [comment]
Thanks for reporting. Still reproduces in 0.30.0.
