### ISSUE TITLE
mdc-card: `@material/icon-toggle/mixins` not found

### ISSUE THREAD

**Issue by jhonnymoreira** [material-components/material-components-web#2231]
### Description
In Webpack workflow, when trying to transpile any `.scss` file which has `@import '@material/card/mdc-card';` as part of the content, throws an error complaining of missing `@material/icon-toggle/mixins` file.

### MDC Card version
0.30.0

### What OS are you using?
Ubuntu 17.10

### What are the steps to reproduce the error?
1. Clone this repository (it has all the files needed to reproduce the error): https://github.com/jhonnymoreira/mdc-card-reproducible-error
1. `yarn install`
1. `yarn build`

### What is the expected behavior?
Transpiling any `.scss` with the line `@import '@material/card/mdc-card';` as part of the content should be successful and not throw errors.

### What is the actual behavior?
It doesn't transpile the `.scss` file and throws an error because it isn't possible to import `@material/icon-toggle/mixins` file.

### Any other information you believe would be useful?

<details>
<summary>Click to expand the detailed error</summary>

```
yarn run v1.3.2
$ webpack --config webpack.config.js
Hash: 8b19350b55686699e4da
Version: webpack 3.11.0
Time: 409ms
 Asset     Size  Chunks             Chunk Names
app.js  4.17 kB       0  [emitted]  app
   [0] multi ./src/app.js ./src/app.scss 40 bytes {0} [built]
   [1] ./src/app.js 20 bytes {0} [built]
   [2] ./src/app.scss 1.48 kB {0} [built] [failed] [1 error]

ERROR in ./src/app.scss
Module build failed:
@import "@material/icon-toggle/mixins";
^
      File to import not found or unreadable: @material/icon-toggle/mixins.
Parent style sheet: ./node_modules/@material/card/mdc-card.scss
      in node_modules/@material/card/mdc-card.scss (line 18, column 1)
 @ multi ./src/app.js ./src/app.scss

ERROR in ./src/app.scss
Module build failed: ModuleBuildError: Module build failed:
@import "@material/icon-toggle/mixins";
^
      File to import not found or unreadable: @material/icon-toggle/mixins.
Parent style sheet: ./node_modules/@material/card/mdc-card.scss
      in node_modules/@material/card/mdc-card.scss (line 18, column 1)
    at runLoaders (/path/to/mdc-card-reproducible-error/node_modules/webpack/lib/NormalModule.js:195:19)
    at /path/to/mdc-card-reproducible-error/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /path/to/mdc-card-reproducible-error/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/path/to/mdc-card-reproducible-error/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/path/to/mdc-card-reproducible-error/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/path/to/mdc-card-reproducible-error/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/path/to/mdc-card-reproducible-error/node_modules/async/dist/async.js:958:16)
    at options.error (/path/to/mdc-card-reproducible-error/node_modules/node-sass/lib/index.js:294:32)
 @ ./src/app.scss
 @ multi ./src/app.js ./src/app.scss
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js??ref--0-2!src/app.scss:
       [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js??ref--0-2!./src/app.scss 301 bytes {0} [built] [failed] [1 error]

    ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js??ref--0-2!./src/app.scss
    Module build failed:
    @import "@material/icon-toggle/mixins";
    ^
          File to import not found or unreadable: @material/icon-toggle/mixins.
    Parent style sheet: ./node_modules/@material/card/mdc-card.scss
          in node_modules/@material/card/mdc-card.scss (line 18, column 1)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

**Comment by jhonnymoreira** [comment]
For what I could understand (and a few tests), to fix this is necessary to add `@material/icon-toggle` as part of the `@material/card` dependencies.

If this is a valid error, I'm willing to submit a pull request fixing it.

**Comment by acdvorak** [comment]
Yikes! Thanks for bringing this to our attention, @jhonnymoreira!

The `@material/icon-toggle/mixins` import isn't even being used, so I'm not sure why it got added.

Created PR #2234 to fix this (and add a missing dep in `package.json`... yeesh!).

Thanks again! 😀

**Comment by acdvorak** [comment]
(Also, bless your heart for using `<details><summary>` for the console output! 😄 )

**Comment by jhonnymoreira** [comment]
@acdvorak Thanks for both quick response and fix! <3

And you're welcome for the `<details><summary>` hahahahaha It wouldn't be fair to just throw the output hahahaha
