### ISSUE TITLE
Bug - Select-Component with reselected index: Missing mdc-select__label--float-above on label

### ISSUE THREAD

**Issue by mdunisch** [material-components/material-components-web#2232]
SELECT-Menu

Bug: If I generate the HTML with a pre-selected value, the label is shown wrong:
![bildschirmfoto 2018-02-12 um 10 44 38](https://user-images.githubusercontent.com/5655305/36090735-cf12753c-0fe1-11e8-8d43-bfd142116ac4.png) 
As soon as the user open the select and close it again the label is shown corrent.

Here is an jsfiddle with the HTML / JS from https://material.io/components/web/catalog/input-controls/select-menus/:
https://jsfiddle.net/6dv7v4f4/ 

As a quick workaround I generate the HTML with .mdc-select__label--float-above on label if there is a  preselected value.

**Comment by kfranqueiro** [comment]
I believe this issue is the same as #1810, and was addressed in JS and in the docs (to prevent FOUC) in #2125. It will be fixed in the next release.
