### ISSUE TITLE
Deprecation warnings when compiling with the sass Ruby gem (3.5.5)

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#2239]
We might want to look into resolving these, hopefully before it ends up affecting people.

```
DEPRECATION WARNING on line 24 of .../@material/layout-grid/_mixins.scss:
The result of `0px != 0` will be `true` in future releases of Sass.
Unitless numbers will no longer be equal to the same numbers with units.

DEPRECATION WARNING on line 27 of .../@material/linear-progress/_mixins.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes:

  unquote("#{$color-value-for-css}")

DEPRECATION WARNING on line 61 of .../@material/textfield/label/_mixins.scss:
The result of `0% == 0` will be `false` in future releases of Sass.
Unitless numbers will no longer be equal to the same numbers with units.
```

**Comment by acdvorak** [comment]
### Comparison operators

Interestingly, although `0px != 0` and `0% == 0` return `false`, less-than and greater-than operators still work like they did before (as of `dart-sass 1.14.2`):

```
$ echo '@debug (0 == 0px)' | sass --stdin
false

$ echo '@debug (0 < 1px)' | sass --stdin
true

$ echo '@debug (1 > 0px)' | sass --stdin
true
```

### Specifying units

Some comparisons can probably be rewritten to specify units.

E.g., this could be `$min != 0px` (or `$min > 0`):

https://github.com/material-components/material-components-web/blob/92eed058f3e2eb77b6b81d99b506890556efc7a9/packages/mdc-layout-grid/_mixins.scss#L23-L31

https://github.com/material-components/material-components-web/blob/92eed058f3e2eb77b6b81d99b506890556efc7a9/packages/mdc-layout-grid/_variables.scss#L21-L25

### Ignoring units

Other comparisons need to support multiple units:

https://github.com/material-components/material-components-web/blob/92eed058f3e2eb77b6b81d99b506890556efc7a9/packages/mdc-floating-label/_mixins.scss#L57-L69

In these cases, we could strip out the units and compare them to unitless zero:

```scss
/// Remove the unit of a length
/// @param {Number} $number - Number to remove unit from
/// @return {Number} - Unitless number
@function strip-unit($number) {
  @if type-of($number) == 'number' and not unitless($number) {
    @return $number / ($number * 0 + 1);
  }

  @return $number;
}

@debug strip-unit(0px) == 0;
```

https://css-tricks.com/snippets/sass/strip-unit-function/
