### ISSUE TITLE
Typography Headings Not Responsive (or Semantic)

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#2240]
`mdc-typography--display4` class is not responsive and clips on mobile devices. Check it yourself by viewing browser dev tools responsive view on [your demo page](https://material-components-web.appspot.com/typography.html).

Possible Fix:

- Use CSS `vmin` to size the header elements.
- Stick with `h1` - `h6` to maintain the semantics of the headers (per [W3C § 4.3.6](https://www.w3.org/TR/html52/sections.html#the-h1-h2-h3-h4-h5-and-h6-elements). The h1, h2, h3, h4, h5, and h6 elements). These levels are used as ranking for assistive technologies.

I'm using `<meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" />` to supress horizontal scroll on mobile devices. I reckon there are many of us using this (not 100% sure if this has anything to do with the overflow getting hidden or not)

![image](https://user-images.githubusercontent.com/12751611/36126087-981f861a-101c-11e8-9a59-cf3fc47653f9.png)

![image](https://user-images.githubusercontent.com/12751611/36126166-f1653ad0-101c-11e8-8b66-f154db6fbdac.png)

**Comment by kfranqueiro** [comment]
This issue touches on two topics, and I talked to someone on the fonts team about both.

### Should the typography scale be directly tied to heading hierarchy?

In the context of MDC Web's typography demo page in particular, the demo page _does_ use h1-h4 for headline, title, subheading 2, and subheading 1, which have a stronger implication of hierarchy and are more likely to be used together. On the other hand, the Display 1-4 classes in particular have no direct correlation to placement in a hierarchy.

Meanwhile, given that there are 8 typography scale classes that could be applicable to headings, and only 6 heading levels, it's impossible to demonstrate using all of them at the same time on the demo page in a single hierarchy. Therefore, the demo page demonstrates it where it makes the most sense to.

In general, heading hierarchy is more about what makes sense based on your content, and there isn't always a singular "right answer" for which typography scale classes map to which headings.

### Can/should these typography styles scale with the width of the page?

The typography scale is currently intentionally defined using `rem` units, and changing to `vw` would change the system's behavior drastically, as the scale would no longer be consistent and predictable across different viewport sizes on desktop, tablet, and mobile.

Additionally, keep in mind that each class in the typography scale carries more than just font-size; it also defines line-height, font-weight, letter-spacing, and (optionally) margin. It's important that all of these be adjusted in unison, and at the very least, font-weight in particular would not be possible to scale based on viewport dimensions.

If you want to use a larger typography scale class on larger screens, your best bet would likely be to use media queries with min/max-width to decide which typography styles to use, e.g.:

```scss
.my-heading {
  @include mdc-typography(display4);
}

@media (max-width: 600px) {
  .my-heading {
    @include mdc-typography(display3);
  }
}
```

In the future, variable fonts might provide additional options for us to look into, but browser support isn't there yet.

**Comment by rhroyston** [comment]
Got it. Thanks for feedback. I imagine Google has invested a huge amount of resources to this and there must be a huge reason to _not_ align with the web standard regarding headings, i.e. having the "1" indicate lowest priority rather than highest.

![image](https://user-images.githubusercontent.com/12751611/36707996-79b02f70-1b36-11e8-894e-4df419f519fa.png)
