### ISSUE TITLE
Checkboxes aren't dark-background aware

### ISSUE THREAD

**Issue by dpraul** [material-components/material-components-web#2248]
### What MDC Web Version are you using?

v0.30.0

### What browser(s) is this bug affecting?

Chrome 64.0.3282.167 64-bit

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. Add `$mdc-theme-background: #333` (or any dark value) to `demos/common.scss`
2. Run the dev server
3. Visit localhost:8080/checkbox.html
4. Observe black checkboxes

### What is the expected behavior?

Checkboxes becomes a light color on dark background

### What is the actual behavior?

Checkboxes are hard-coded to use dark colors.

**Comment by kfranqueiro** [comment]
FYI I'm tagging these simply to reflect that you already provided PRs. Thanks!

**Comment by moog16** [comment]
@drpaul this no longer seems to be an issue. The implementation of the new color subsystem https://github.com/material-components/material-components-web/issues/2481, I believe solved this issue. Will close this and the related PR.
