### ISSUE TITLE
Tab indicators aren't dark-background aware

### ISSUE THREAD

**Issue by dpraul** [material-components/material-components-web#2250]
### What MDC Web Version are you using?

v0.30.0

### What browser(s) is this bug affecting?

Chrome 64.0.3282.167 64-bit

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. Add `$mdc-theme-background: #333` (or any dark value) to `demos/common.scss`
2. Run the dev server
3. Visit localhost:8080/tabs.html
4. Observe black tab indicator

### What is the expected behavior?

Indicator becomes a light color on dark background.

### What is the actual behavior?

Indicators are hard-coded to use dark colors.

**Comment by asyncLiz** [comment]
This issue is a bit outdated, but you can follow #5253 for dark theme support
