### ISSUE TITLE
Unable to add custom SVG icons to buttons.

### ISSUE THREAD

**Issue by nullsmegh** [material-components/material-components-web#2257]
Is there a specific api to add them or it is not supported, since I've thoroughly checked the documentation and couldn't find any. Like having svg icons

**Comment by kfranqueiro** [comment]
MDC Button supports an [icon element](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button#adding-icon), but it's currently optimized for use with the Material Icons font. I just tested it with an SVG instead, and it doesn't align properly.

This seems like something we should investigate supporting along with the icon font.

**Comment by kfranqueiro** [comment]
Fixed with #2352.
