### ISSUE TITLE
Material Icons are not being rendered on Safari 8 in iOS 8.1 (i.e iPhone 4s)

### ISSUE THREAD

**Issue by Arwany** [material-components/material-components-web#226]
### What MDC-Web Version are you using?

ALL Versions

### What browser(s) is this bug affecting?

Safari on iOS 8.1

### What OS are you using?

iOS 8.1 on iPhone 4s

### What are the steps to reproduce the bug?

Just open the page, no material icons are being rendered.

### What is the expected behavior?

To see icons not text.

### What is the actual behavior?

I am getting texts in place of icons.

### Any other information you believe would be useful?
<img width="330" alt="screen shot 2017-01-30 at 13 47 44" src="https://cloud.githubusercontent.com/assets/559250/22423630/d24837d2-e6f2-11e6-8240-f5fbcec5bcf0.png">
Just an example of the problem.

**Comment by Arwany** [comment]
<img width="330" alt="screen shot 2017-01-30 at 13 47 44" src="https://cloud.githubusercontent.com/assets/559250/22423630/d24837d2-e6f2-11e6-8240-f5fbcec5bcf0.png">
Just an example of the problem.

**Comment by traviskaufman** [comment]
This is happening because we use ligatures for our icon fonts, which Safari <9.1 doesn't support. TBH, we've discussed switching away from ligatures in the past, so we should just use this as an opportunity to do so. However, we also _technically_ don't support Safari 8, since our policy is to support the last two major versions of every browser, which is 9 and 10. Our README currently doesn't reflect this, so we need to update that as well.

Work involved:

- [ ] Switch demos to use codepoints rather than ligatures
- [ ] Modify all component READMEs which use icon fonts to use codepoints instead of ligatures

**Comment by shyndman** [comment]
Looks like Safari 5+ supports ligatures through `text-rendering: optimizeLegibility`. I tested on desktop Safari 8 and confirmed that the icons render. I'm not sure whether this extends to mobile Safari, but I'd be surprised if it didn't.

@Arwany, could you visit [material.io/icons](https://material.io/icons) and confirm that icons are not rendering? If they don't, I'll keep digging.

**Comment by shyndman** [comment]
Caniuse suggests Mobile Safari 8 should work as far back as 4.3:
http://caniuse.com/#feat=kerning-pairs-ligatures

**Comment by Arwany** [comment]
<img width="322" alt="screen shot 2017-02-07 at 18 36 11" src="https://cloud.githubusercontent.com/assets/559250/22703397/52604532-ed64-11e6-8a92-ee57ba852299.png">

@shyndman  It doesn't look any different.

**Comment by shyndman** [comment]
It doesn't look as if your browser is downloading any web fonts. The header (where it says "ICONS") should be styled in Roboto Mono, but isn't. Any idea why that might be?

**Comment by Arwany** [comment]
I have no idea, but this is the same results I get on the actual iPhone 4s with Safari 8 as well.

**Comment by shyndman** [comment]
Thanks for trying that. I'm grabbing a simulator so I can repro.

**Comment by shyndman** [comment]
I've reproduced. Looks like the server is sending back woff2s instead of woff. Can I get the user agent of the physical device you're using?

**Comment by shyndman** [comment]
Here's why I ask. Turns out the iOS 8.1 simulator has [a bug](http://stackoverflow.com/questions/26200760/ios8-simulator-user-agent) where it mis-reports the OS as being v10.12.2. This version is used to determine what font format to send to the browser. I don't believe that real live iPhones are affected in the same way.

**Comment by Arwany** [comment]
This is the website from a iPhone 4s, which also confirms the issue on real iPhones.
![6856224e-a0d7-48b1-8de2-744f801f36cf](https://cloud.githubusercontent.com/assets/559250/22772379/a2c2027a-ee9c-11e6-90d7-b65f1257d6dc.jpg)

**Comment by Arwany** [comment]
Here is the User Agent as well: 

Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1

**Comment by shyndman** [comment]
Thanks @Arwany. I'll take a look.

**Comment by BBosman** [comment]
Just for reference, browsing to [material.io/icons](https://material.io/icons) on an iPhone 4 running iOS 7.1.2. does show the icons.

![foto](https://cloud.githubusercontent.com/assets/5115488/22966213/802423dc-f361-11e6-8441-355acfa6b276.PNG)

**Comment by carloscasal** [comment]
Has this been solved? :)

**Comment by evaleirasclapps** [comment]
Was this solved?

**Comment by waaronking** [comment]
We're experiencing the same problem in iOS and Safari

**Comment by jasonvillalon** [comment]
not working on my end safari 11.1.2, its just showing letters

**Comment by kfw9257** [comment]
We're experiencing the same issue

**Comment by Wouter8** [comment]
Still open after a year?

**Comment by jeremiahlachica** [comment]
This solution worked for me:
https://stackoverflow.com/questions/36044052/materialize-css-icons-doesnt-show-up-in-safari-browser

**Comment by acdvorak** [comment]
Thanks for the feedback, everyone!

We only support [browser versions `N` and `N-1`](https://github.com/material-components/material-components-web/blob/ccadc6c/docs/supported-browsers.md), so Safari 8 is no longer supported by MDC.
I'm not able to reproduce this in iOS 11 or 12 (physical device or simulator).

If you're still seeing it in a supported browser, feel to reopen, and **please include the following**:

1. Which component(s) exhibit the problem (e.g., `mdc-button`, `mdc-icon-button`, `mdc-top-app-bar`, `mdc-textfield`, or "everything with a `material-icons` class")
2. A public URL to verify and troubleshoot (e.g., [Catalog](https://material-components.github.io/material-components-web-catalog/#/component/icon-button), [CodePen](https://codepen.io/abhiomkar/pen/gQWarJ), [screenshot test](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/01/31/14_51_47_538/spec/index.html))

Thanks! 😀

**Comment by JonCatmull** [comment]
Hi,  @acdvorak 

I'm getting this Safari desktop in Version 12.0.3 (14606.4.5) I'm running macOS 10.14.3

The icon font is not rendering and then pushing my button content off the screen.
![screenshot 2019-02-28 at 12 14 10](https://user-images.githubusercontent.com/9530500/53565945-c893d780-3b52-11e9-8aa5-fa05ed289e86.png)

**Comment by JonCatmull** [comment]
Ok seems adding `font-feature-settings: 'liga'` to .material-icons class fixes it.

**Comment by javierpal** [comment]
already put this thing font-feature-settings: 'liga'; in the .material-icons class, but still does not work.

**Comment by shekhaua** [comment]
> I've reproduced. Looks like the server is sending back woff2s instead of woff. 

I was facing the same issue on iOS 13.3 (simulator). 
Placing the url("../fonts/MaterialIcons-Regular.woff") format('woff') 
before 
url("../fonts/MaterialIcons-Regular.woff2") format('woff2')  in font declaration fixed the issue:

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url("../fonts/MaterialIcons-Regular.eot"); /* For IE6-8 */
  src: local('Material Icons'),
      local('MaterialIcons-Regular'),
      url("../fonts/MaterialIcons-Regular.woff") format('woff'), < -----
      url("../fonts/MaterialIcons-Regular.woff2") format('woff2'), <-----
      url("../fonts/MaterialIcons-Regular.ttf") format('truetype');
}

**Comment by mzamayias** [comment]
I'm facing the same issue on Big Sur (with the M1 chip). Is this the correct place to post this? Any ideas if I should make another post elsewhere about it? Here are some examples:
<img width="1792" alt="Screen Shot 2021-05-04 at 21 44 29" src="https://user-images.githubusercontent.com/29067825/117053814-18b5e800-ad22-11eb-8f13-f839a8715bf9.png">
<img width="1792" alt="Screen Shot 2021-05-04 at 21 44 56" src="https://user-images.githubusercontent.com/29067825/117053835-1f445f80-ad22-11eb-816b-2a377fd44f67.png">
<img width="1792" alt="Screen Shot 2021-05-04 at 21 45 05" src="https://user-images.githubusercontent.com/29067825/117053844-223f5000-ad22-11eb-8f5c-ce80e74ae09b.png">
