### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by aaronhudon** [material-components/material-components-web#2261]
Given the rapid change to MDC-Web, would it be feasible for the documentation site to serve up **versioned** documentation?  Referring back to a specific version of documentation would help those that are using this package.

e.g. https://material.io/components/web/docs/0.28/

**Comment by moog16** [comment]
@aaronhudon is what you're referring to the (spec)[https://material.io/guidelines/components/]? I don't believe the spec has updated in some time. If what you are referring to are the docs on specific components like the README.md for button, could you use our tagging system? e.g. https://github.com/material-components/material-components-web/tree/v0.27.0/packages/mdc-button

**Comment by aaronhudon** [comment]
@moog16 yes, this works, thanks!  Ideally I was looking for a versioned view of documentation and demo of https://material.io/components/web/catalog/ I'm assuming this is not possible, so I'll go with your suggestion.
