### ISSUE TITLE
Investigate why Select sets menu to position: fixed

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#2264]
(Split from #2246)

MDC Menu sets the opened menu to `position: absolute`, but for some reason MDC Select sets `position: fixed`, and off the top of my head I'm not sure if there's a reason for that to be necessary. (Maybe there was once, but not anymore?)

**Comment by dpraul** [comment]
Playing around with this one, using `position: absolute` removes the need for a lot of the positioning logic, which resolves #719 - and I imagine resolves other use-cases where nested `mdc-select` elements don't work properly with the current positioning logic.

**Comment by williamernest** [comment]
Will be resolved when we remove the MDC-Menu from the MDC-Select component with #2399

**Comment by kfranqueiro** [comment]
As Will mentioned, this is now obsolete with #2399 resolved.
