### ISSUE TITLE
Slider error if min is greater than default max value of 100

### ISSUE THREAD

**Issue by entone** [material-components/material-components-web#2269]
If the minimum value for your slider is greater than 100, the MDCComponent throws `Error: Cannot set min to be greater than the slider's maximum value`.

I tried updating the logic to always set the max value first here https://github.com/prateekbh/preact-material-components/blob/master/Slider/Slider.jsx#L49

But that didn't seem to fix it. Not sure what's going on.

**Comment by none23** [comment]
I also experience this issue with https://github.com/jamesmfriedman/rmwc

**Comment by entone** [comment]
I was able to work around the bug by using smaller values and providing a
multiplier for displaying and storing the value.

**Comment by moog16** [comment]
@entone, interesting that it appears in both React and Preact implementations of MDC. Would you be able to provide a [Codepen](https://codepen.io/traviskaufman/pen/pNQmRp) for us to replicate your work just using https://github.com/material-components/material-components-web/tree/master/packages/mdc-slider.

**Comment by vervallsweg** [comment]
@moog16 Sorry I don't have the time to setup a Codepen now. However also with pure mdc you can easily reproduce this bug.

Add a standard slider to your DOM:
`<div class="mdc-slider mdc-slider--discrete" data-mdc-auto-init="MDCSlider" tabindex="0" role="slider" aria-valuemin="200" aria-valuemax="600" aria-valuenow="200" data-step="10" aria-label="Select Value"><div class="mdc-slider__track-container"><div class="mdc-slider__track"></div></div><div class="mdc-slider__thumb-container"><div class="mdc-slider__pin"><span class="mdc-slider__pin-value-marker"></span></div><svg class="mdc-slider__thumb" width="21" height="21"><circle cx="10.5" cy="10.5" r="7.875"></circle></svg><div class="mdc-slider__focus-ring"></div></div></div>`

Run auto init:
`window.mdc.autoInit();`

Check your console:
`Uncaught Error: Cannot set min to be greater than the slider's maximum value
    at MDCSliderFoundation.setMin (material-components-web.js:13482)
    at MDCSlider.set (material-components-web.js:13110)
    at MDCSlider.initialSyncWithDOM (material-components-web.js:13055)
    at MDCSlider.MDCComponent (material-components-web.js:259)
    at new MDCSlider (material-components-web.js:12929)`

If you replace your values with ` aria-valuemin="20" aria-valuemax="60" aria-valuenow="20" ` and run auto init again, results in no error.

Working on workaround like @entone first, maybe I'll add a Codepen after that.

**Comment by moog16** [comment]
@vervallsweg Thanks for writing that all up for me. I created a [Codepen](https://codepen.io/moog16/pen/zRMezG?editors=1010) that indeed does have the error you mentioned.

**Comment by kkimdev** [comment]
The problem is that initialSyncWithDom function sets this.min first and setMin function asserts the value is less than this.max_, which the default value is 100 initially.

- https://github.com/material-components/material-components-web/blob/1c324dbb9b13aaab2aaf5a8074a0f70018d4e92c/packages/mdc-slider/index.js#L180
- https://github.com/material-components/material-components-web/blob/1c324dbb9b13aaab2aaf5a8074a0f70018d4e92c/packages/mdc-slider/foundation.js#L226

@traviskaufman
