### ISSUE TITLE
Bug: Tabs with mdc-toolbar - Safari wrong height

### ISSUE THREAD

**Issue by mdunisch** [material-components/material-components-web#2272]
When i use mdc-toolbar with Tabs the tabs are at the wrong position (heigher) on Safari.
See with your example Site http://material-components-web.appspot.com/tabs.html:
 
![bildschirmfoto 2018-02-19 um 09 15 04](https://user-images.githubusercontent.com/5655305/36368062-d7f54fd4-1555-11e8-8ca9-3d776f01b710.png)

(Chrome 64 on the left, Safari 11 right)

As far as I know this is a Safari-only problem, looks good on IE / Egde and FF.

**Comment by moog16** [comment]
@mdunisch I can confirm that this is an issue on Safari. I noticed that with display: table-cell (what our tabs are), Safari doesn't always respect min-height. I haven't been able to isolate the issue, but I created a (Codepen)[https://codepen.io/moog16/pen/QQrEWr] with my work so far (not proving issue). 

I will open a bug.

**Comment by kfranqueiro** [comment]
I've just tested and confirmed that this is no longer an issue with the new MDC Tab Bar component and its subcomponents (MDC Tab, MDC Tab Indicator).
