### ISSUE TITLE
MDCSelect's options do not display

### ISSUE THREAD

**Issue by FirebertNY** [material-components/material-components-web#2275]
When copying the HTML from the select's documentation page and putting it into a page, clicking the select does not display the menu options. I'm uncertain if I'm using the component incorrectly or if there's an actual bug.

### What MDC Web Version are you using?

0.30.0

### What browser(s) is this bug affecting?

Chrome, Firefox, IE

### What OS are you using?

Win 7

### What are the steps to reproduce the bug?

Take a look at this codepen: https://codepen.io/anon/pen/YeaOXv
I've simply copied the HTML from the select example in the documentation and set the width on it. Clicking the select does not display the menu.

### What is the expected behavior?

Clicking the select opens the menu showing all of the options.

### What is the actual behavior?

Clicking the select does not open the menu.

**Comment by mdunisch** [comment]
The documentation is really patchy here:
You can't use
`new MDCSelect` when you include the hole js-package (this syntax is only if you import each component with import-syntax)

To make this work just use 
``new mdc.select.MDCSelec`` instead.

See updated codepen: https://codepen.io/anon/pen/yvjMja

**Comment by FirebertNY** [comment]
That fixed it, thank you. I agree the docs should be updated to be more clear about this.

**Comment by kfranqueiro** [comment]
It looks like we're missing a link to "Importing the JS Component" the way we have in e.g. [text field](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#mdctextfield).

I suspect our MDC Select readme eventually needs more tweaking to bring it in line with other more recently updated readmes, but at the very least we could add that line below the script example (in fact we could probably replace the note about UMD bundle with this line instead).
