### ISSUE TITLE
Select with pre-selected option doesn't float label (redux)

### ISSUE THREAD

**Issue by dpraul** [material-components/material-components-web#2282]
#1810 shows its face again, as #2125 appears to have been accidentally regressed by #2244 (see https://github.com/material-components/material-components-web/pull/2244/files#diff-cb9f9b1a189b68df18866209b4dd1cdfL156).

**Comment by acdvorak** [comment]
Thanks for filing this issue and providing so much context! It's very helpful and allows us to fix issues faster, so we greatly appreciate it! 😁
