### ISSUE TITLE
mdc-menu inside mdc-list - cutting menu items

### ISSUE THREAD

**Issue by GilVieira** [material-components/material-components-web#2288]
What MDC Web Version are you using?
0.30.0

What browser(s) is this bug affecting?
All

What OS are you using?
Windows

What are the steps to reproduce the bug?

I would like to put an icon to open a menu in each item in my list, but when opening the menu it stays inside the container of the item not being visible the menu options. Is there a way to make the menu in the list items?

![img](https://user-images.githubusercontent.com/9217130/36506946-e735151e-1736-11e8-8d9c-63d6ecd8480d.PNG)

Tks

**Comment by moog16** [comment]
@GilVieira Are you saying you want a menu inside each of your list items? I can check with design, but I do not think that is advised. What is your use case? Why do you need so many mini-menus?

I think the problem you are running into is that all .mdc-list-item elements have `overflow:hidden` properties. You can override it if you see it necessary.

**Comment by GilVieira** [comment]
Hi @moog16 , maybe I'm using mdc-list for the wrong purpose, I'd like to have a list of movies and in each list item a button (icon) that opens a menu with some actions (edit, remove, etc). I have tried to change overflow, but it ends up breaking other parts of the list, maybe I use grid lists (mdc-grid-list) to get the expected result. Thank you for your help.

![img1](https://user-images.githubusercontent.com/9217130/36532148-b672646e-179e-11e8-9fce-664ca33ea548.JPG)

**Comment by domolicious** [comment]
Unless I am missing something, the usecase in terms of Material Design guidelines is called a contextual menu. I am too looking to implement this. I just upgraded from 0.22 and it broke this feature.

Setting `overflow: visible` helps display the menu in my case. But the menu has visible scrollbars and the ripple effect is ginormous. I also experimented with the mdc-menu-anchor without luck. If it still is possible to implement a contextual menu inside a list out of the box it would be great with an updated README.

Another solution to having a menu nested inside every list item could be a single menu with an anchor that you would set every time before you open it.

**Comment by fjfeijoo** [comment]
I have the same issue with contextual menus. I'm using one menu per row and the menu displays inside the row.

Any workaround I could try?

Thanks.

**Comment by bencorke** [comment]
+1

**Comment by FanrayMedia** [comment]
@moog16 I encountered the same issue. Here is a use case that shows what I'm trying to get at, it is from the post list in the Admin Console of WordPress

![2018-04-19_1503_001](https://user-images.githubusercontent.com/633119/39020809-f78a7e44-43e2-11e8-810a-4b7040d8fd1e.png)

When you click on the button a menu shows up

![2018-04-19_1503](https://user-images.githubusercontent.com/633119/39020817-fc8b5526-43e2-11e8-86e5-d44a8a8a6737.png)

**Comment by moog16** [comment]
@FanrayMedia we're actually working on a solution for this issue right now. cc @williamernest for more info.

**Comment by jeffclemens** [comment]
Thank you @moog16 and @williamernest .  I look forward to the solution as I have the same issue.

**Comment by cdock1029** [comment]
**Gmail:** menu anchors on every item when hovering

<img width="395" alt="screen shot 2018-05-01 at 12 47 09 am" src="https://user-images.githubusercontent.com/802586/39461540-740cc9f0-4cd9-11e8-87e3-b62b81890a47.png">

**Comment by matatablack** [comment]
+1
Here is the comment i made showing similar problem:
https://github.com/google/material-design-lite/issues/5180#issuecomment-401808145

**Comment by iteratelance** [comment]
I know this issue is closed but but I'm experiencing the same issue with version 7.0.0 on web
https://unpkg.com/material-components-web@7.0.0/dist/material-components-web.min.css

Has this issue regressed?
<img width="538" alt="Screen Shot 2020-10-19 at 9 41 36 PM" src="https://user-images.githubusercontent.com/792408/96466104-f233d200-1253-11eb-9ad9-f2e78c67c181.png">

I would expect the menu do show above all other li elements.
