### ISSUE TITLE
Grid span 0 have no effect

### ISSUE THREAD

**Issue by andriytyurnikov** [material-components/material-components-web#2293]
### What MDC Web Version are you using?
0.30.0

### What browser(s) is this bug affecting?
Chrome 64

### What OS are you using?
OS X High Sierra 10.13.3

### What are the steps to reproduce the bug?
https://codepen.io/andriytyurnikov/pen/aqKrYK

### What is the expected behavior?
Invisible cell
Cell with size 0 should not be visible

### What is the actual behavior?
Visible cell

### Any other information you believe would be useful?
Yeah, developing real apps based on tools - seriously helps developing tools.

**Comment by moog16** [comment]
@andriytyurnikov  thanks for opening this issue, but this is a duplicate of #2293. Going to close and track in that issue.

**Comment by kfranqueiro** [comment]
I think there was a typo in our previous comment when we closed this... the original issue, which is being tracked, is #2270.
