### ISSUE TITLE
Unable to set Select value via JS

### ISSUE THREAD

**Issue by umbidel** [material-components/material-components-web#2298]
**What MDC Web Version are you using?**

0.30.0

**What browser(s) is this bug affecting?**

Firefox Quantum 58.0.2 (64-bit)

**What OS are you using?**

Mac OS Sierra 10.12.6

**What are the steps to reproduce the bug?**

https://codepen.io/umbidel/pen/ZrjePW

**What is the expected behavior?**

The third option is selected

**What is the actual behavior?**

Nothing happens

**Comment by moog16** [comment]
@umbidel thanks for making the Codepen...it makes it a lot easier to help you and everyone else.

I took a look and you aren't initializing the select component. Your Codepen JS code should look more like:

```
var boatSelect=document.querySelector("#boatSizeSelect");
var boatSelectInit = new mdc.select.MDCSelect(boatSelect);

function setOption() { ... }
```

Hope this helps
