### ISSUE TITLE
Distribution css files are bloated

### ISSUE THREAD

**Issue by arc4nis8** [material-components/material-components-web#2307]
### What MDC Web Version are you using?

0.31.0

### What browser(s) is this bug affecting?

All browsers

### What OS are you using?

Windows

### What are the steps to reproduce the bug?

The .css distribution files that come with installing MDC web through npm are bloated. 

`material-components-web.css` ---> 377kB
`material-components-web.min.css` ---> 219kB

When I compile the material-components-web.scss with node-sass I get:

`material-components-web.css` ---> 284kB
`material-components-web.min.css` ---> 168kB

As far as I can see, my compiled files work just as good as the original distribution files, so I don't understand where is the catch? Are the distribution .css files bloated or am I missing something in my compiled files?

**Comment by moog16** [comment]
@arc4nis8 Our css goes through the autoprefixer, which adds prefixes for all the browsers we aim to support. So to answer your question, that is where the "bloat" is coming from. You may/may not need this depending on which browsers you aim to support.
