### ISSUE TITLE
missing invalid styles on select

### ISSUE THREAD

**Issue by getriebesand** [material-components/material-components-web#2308]
### What MDC Web Version are you using?

0.30.0

### What browser(s) is this bug affecting?

all

### What OS are you using?

Ubuntu

### Issue

invalid styles like on text fields are missing
there is an closed issue but i can't find the styles.
https://github.com/material-components/material-components-web/issues/291

**Comment by moog16** [comment]
We originally thought that selects could not be invalid, since the end user selects an option which can't be invalid, and did not think about the case when a form marks it as required. I will close this issue and reopen #291.
