### ISSUE TITLE
Pass MDCSelect Value to Form?

### ISSUE THREAD

**Issue by QJan84** [material-components/material-components-web#2313]
Hello,

how can I pass the value from 'mdc-select__selected-text' to PHP $_POST?
Do I have to create an extra 'hidden input' here and store the value via js?
So I have it when sending the form in the $ _Post variable?

**Comment by hebbet** [comment]
see #2221

**Comment by moog16** [comment]
In the interim until we resolve #2221, it is easiest to just create a hidden input and update the value when a user interacts/changes the MDC-Select. We realize this isn't ideal, but in order to submit via Post there must be a corresponding HTML form input in the DOM.

**Comment by moog16** [comment]
Closing this issue and will track in #2221
