### ISSUE TITLE
Theme : SASS light and dark variants are incorrect

### ISSUE THREAD

**Issue by aaronhudon** [material-components/material-components-web#2316]
The documentation for theme states:

> MDC Theme also exposes light and dark variants of the primary and secondary colors. By default, these values are computed by lightening and darkening the main primary/secondary colors in Sass...

### What MDC Web Version are you using?

0.31.0

### What are the steps to reproduce the bug?

Using the demo site's "yellow (primary) as an example', where:
mdc-theme-primary is defined as `ffeb3b`
mdc-theme-primary-light is calculated as `fff282`
https://material-components-web.appspot.com/theme/index.html?theme=yellow

Using the official material.io color tool for the same primary color, it calculates mdc-theme-primary-light as `ffff72`
https://material.io/color/#!/?view.left=0&view.right=0&primary.color=ffeb3b

An example I am personally working on uses mdc-theme-primary as `material-color-blue-grey-600`, the SASS calculates the primary light as `b37eff` (almost a purple), whereby the material.io color tool calculates the primary light as `819ca9`

**Comment by moog16** [comment]
@aaronhudon we don't follow the material.io tool in our sass mixins, but instead try to estimate them. Ours is a much simpler calculation and are just a +/- percentage change of the baseline color. You should, however be able to override the sass variables as necessary. Closing issue as we will not match the color tool.
