### ISSUE TITLE
Persistent Drawer issue when page scroll.

### ISSUE THREAD

**Issue by ruwaroshan** [material-components/material-components-web#2318]
### What MDC Web Version are you using?

> 0.31.0

### What browser(s) is this bug affecting?

> All Browsers

### What are the steps to reproduce the bug?

> 1. Open persistent drawer demo. ( https://material-components-web.appspot.com/drawer/persistent-drawer.html ).
> 2. Add more content to right side content area till browser scroll bar appear.
> 3. Scroll the page.
> 4. Drawer is scrolling and height of the left panel will not maintaining with the screen height.
![image](https://user-images.githubusercontent.com/12517126/36781742-d6c2ddc2-1c9c-11e8-95d6-1a65b7db5dc0.png)
![image](https://user-images.githubusercontent.com/12517126/36781908-42c39296-1c9d-11e8-9e60-feb6c1a3ff89.png)

>
> It can be fix by giving "position: fixed" styled to "mdc-drawer__drawer".

### What is the expected behavior?

> Drawer could not be scroll.

### What is the actual behavior?

> Drawer is scrolling and height will not maintaining.

**Comment by moog16** [comment]
Checked with design and yes the drawer should not scroll. In fact all drawers should behave this way. The content and the drawer should be 2 independent scroll areas.

**Comment by abhiomkar** [comment]
Closing this as obsolete.

This issue is not reproducible in new Drawer version.
