### ISSUE TITLE
Using mdc-menu-anchor in the mdc-toolbar__icon

### ISSUE THREAD

**Issue by NadjibBELLOUNDJA** [material-components/material-components-web#2319]
## Bugs

I would like to use a `<div class="mdc-menu-anchor"></div>` inside a `<div class="mdc-toolbar__icon"></div>`, likeso

```html
<div class="mdc-toolbar__icon">
    <div class="mdc-menu-anchor">
        <a href="myLink">
            <i class="material-icons">&#xE7F4;</i>
        </a>
        <div class="mdc-simple-menu">
            <ul class="mdc-simple-menu__items mdc-list" role="menu" aria-hidden="true">
                ...
            </ul>
         </div>
    </div>
</div>
```

The markup of `<div class="mdc-toolbar__icon">` specifies that the element with the class mdc-toolbar__icon, should contain a anchor tag element (recommended way), likeso

```html
<div class="mdc-toolbar__icon">
    <a></a>
</div>
```

Is there a risk that the styling will break if I put a `<div class="mdc-menu-anchor">` inside the `<div class="mdc-toolbar__icon">`, instead of having an anchor element directly (what I want to do), likeso

```html
<div class="mdc-toolbar__icon">
    <div class="mdc-menu-anchor">
        <a></a>
    </div>
</div>
```

To make things clearer, my real need is to have a dropdown `mdc-simple-menu` position itself right under the `<a>` icon, and not under the toolbar containing the <a>.
So if there are other alternative solutions to do this instead of placing a `mdc-menu-anchor` inside the `mdc-toolbar__icon`, I am open to these suggestions. I could not find an example meeting my needs in the documentation.

### What MDC Web Version are you using?

0.28

**Comment by moog16** [comment]
@NadjibBELLOUNDJA I believe what you are looking for already exists in our demo pages. Please see https://material-components-web.appspot.com/toolbar/index.html. Specifically: https://material-components-web.appspot.com/toolbar/menu-toolbar.html.

We have a menu in a toolbar with the <a /> tag contained within. Also the mdc-menu-anchor should wrap the entire menu as shown in our demo pages.
