### ISSUE TITLE
mdc-tab overlays mdc-menu in multi-row mdc-toolbar

### ISSUE THREAD

**Issue by abraham** [material-components/material-components-web#2321]
### What MDC Web Version are you using?

> 0.31.0

### What browser(s) is this bug affecting?

- Chrome: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.88 Safari/537.36
- Firefox: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
- Safari: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6

### What OS are you using?

macOS 10.13.3

### What are the steps to reproduce the bug?

1. Create a mdc-toolbar with two rows
2. Put a mdc-menu in the top row
3. Put a mdc-tab-bar in the second row
4. Open the menu

The mdc-tabs hoover state will overlay the shown menu.

You can see the behavior in this [CodePen](https://codepen.io/abrahamwilliams/pen/gvqYbg).

![screen shot 2018-02-28 at 10 55 30](https://user-images.githubusercontent.com/3341/36806445-a5835316-1c85-11e8-89b1-216eae005afc.png)

### What is the expected behavior?

The menu is expected to not have the mdc-tab overlay it.

### What is the actual behavior?

The mdc-tab is in front of the mdc-menu and you can't click on the menu item behind the mdc-tab.

### Any other information you believe would be useful?

Removing `display: flex` from `.mdc-toolbar__row` resolves the issue.

**Comment by williamernest** [comment]
Closing since this issue was resolved with the new `mdc-menu` and the new `mdc-menu-surface`. 

https://codepen.io/williamernest/pen/XPjWLg?editors=1000
