### ISSUE TITLE
Two READMEs writing to same docsite location

### ISSUE THREAD

**Issue by shyndman** [material-components/material-components-web#2322]
Can someone take a look at this?
`material-components-web/packages/mdc-select/label/README.md` and
`material-components-web/packages/mdc-select/README.md` both attempting to write to `/catalog/input-controls/select-menus/`

**Comment by shyndman** [comment]
Thanks Ken!

**Comment by kfranqueiro** [comment]
Sure, sorry about that slipping through. I gave the team a PSA about avoiding it in the future.
