### ISSUE TITLE
Reset MDC-Select?

### ISSUE THREAD

**Issue by QJan84** [material-components/material-components-web#2328]
I have two selects that are interdependent.
The content of the second select depends on the selection of the first select.
If I choose another option from the first select than before, the second select must be emptied.

In short, how can I reset a select?

**Comment by williamernest** [comment]
@QJan84 You can clear the select by setting the `selectedIndex` to -1. Right now, there's a bug where you also have to clear the label float above class, but that will be fixed with the next release. 

Codepen
https://codepen.io/williamernest/pen/LQaENr
