### ISSUE TITLE
Documentation issue when installing individual components.

### ISSUE THREAD

**Issue by ruwaroshan** [material-components/material-components-web#2333]
I was going to use mdc select for my website and I have imported specific CSS file as follow without importing all.
@import "@material/select/mdc-select";

But it didn't looks as in the demo.

then I had to import below files as well which are not included with the required file list.
- @import "@material/menu/mdc-menu";
- @import "@material/list/mdc-list";

Better to mention it on the document in proper way.

**Comment by patrickrodee** [comment]
Thanks for submitting the issue. We have a brief indented note about [using `mdc-select` as a standalone component](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#using-the-full-fidelity-js-component) in the docs but it's clearly not obvious enough.

We're opened a [help-wanted issue to resolve this](https://github.com/material-components/material-components-web/issues/2342) that you're more than welcome to address.

Thanks!
