### ISSUE TITLE
element stays focused

### ISSUE THREAD

**Issue by 3hson** [material-components/material-components-web#2337]
when I click on an element it stays focused 

![styasfocused](https://user-images.githubusercontent.com/36244081/36936510-cd657628-1f1b-11e8-8c43-7b0d96096bbe.gif)

it happens in all browsers. is this a normal behavior?
how can I change it?

**Comment by patrickrodee** [comment]
Thanks for submitting the issue. That focus-state is indeed normal browser behavior. The obvious focus-state is included for accessibility and users who interact with websites without a keyboard and mouse. There's a [great guide about the importance of focus that you can read here](https://developers.google.com/web/fundamentals/accessibility/focus/#experiencing_focus).

Thanks!
