### ISSUE TITLE
Icon at the end of the button

### ISSUE THREAD

**Issue by pshe94** [material-components/material-components-web#2339]
### What MDC Web Version are you using?

> 0.31.0

### What browser(s) is this bug affecting?

> Chrome 65.0.3325.106

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

> Create a button.
> Add icon after the text in a button.
>
> Example: [CodePen](https://codepen.io/pshe94/pen/MQRzrR)

### What is the expected behavior?

> Icon margin should have change, if it is placed as last element inside of a button. 

### What is the actual behavior?

> Icon margin doesn't change, leaving empty space after an icon.

### Any other information you believe would be useful?

This can be easily fixed by wrapping text inside of a button in `span` tag, and replacing:
```
margin-right: 8px;
``` 
inside of `mdc-button__icon_` mixin with:
```
&:first-child {
    margin-right: 8px;
}

&:last-child {
    margin-left: 8px;
}
```
I'm not just sure if placing icon as the last element in a button is in accordance with the [Material Design guidelines](https://material.io/guidelines/components/buttons.html).

**Comment by patrickrodee** [comment]
Thanks for submitting the issue. We'll discuss this with the Material designers to see if they have a use-case for this and get back to you.

Thanks!
