### ISSUE TITLE
Is there any way to add a new action to mdc-dialog, except accept and cancel?

### ISSUE THREAD

**Issue by wzjing** [material-components/material-components-web#2340]
## Can I add a new action to mdc-dialog footer use current api?

I mean something like this:

```html
<footer class="mdc-dialog__footer">
    <button class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel" type="button">Cancel</button>
    <button class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--refuse" type="button">Refuse</button>
    <button class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--accept" type="button">Accept</button>
</footer>
<scrpts type="text/javascript">
    dialog.listen('MDCDialog:refuse', function() {
        console.log('refuse clicked')
    })
</scripts>
```

How could I add this custom `refuse` action to mdc-dialog?

**Comment by patrickrodee** [comment]
Thanks for submitting the issue. We need to look more into how we can support multiple actions inside a dialog footer.

Would you mind providing some use-cases for having multiple options inside a dialog? I'm curious how three different states would work. How is "refuse" different than "cancel"? Would selecting "refuse" trigger different behavior than just selecting "cancel"?

Thanks!

**Comment by wzjing** [comment]
I'm dealing with somthing like this: A dashboard can deal *order cancel requests*. In this condition, I need both refuse and agree operation which will change the *order* state. 

![mdc-dialog](http://i67.tinypic.com/2aaat94.png)

The second design in the picture above, I attach them to `mdc-cancel` and `mdc-accept` action. Sometime we don't want to deal this order now, we just want close the dialog and deal it later. But when I close this dialog, it will trigger the `mdc-cancel` action which already attached to a refuse operation. Here is another question:

- If I can't add new actions, can I close the dialog without trigger `mdc-cancel` action?

**Comment by patrickrodee** [comment]
Thanks for explaining your use case. Those mocks are quite helpful.

We're going to discuss with our designers about this use case. In the mean time, try adding your own event listeners to the "Refuse" button. Another possibility is to make the "Refuse" option into a checkbox in the dialog.

Thanks!
