### ISSUE TITLE
Update mdc-select docs to include required standalone dependencies

### ISSUE THREAD

**Issue by patrickrodee** [material-components/material-components-web#2342]
Update the select docs section about the [full-fidelity component](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#using-the-full-fidelity-js-component) to include a heading about importing required components and a code block showing how to import `mdc-list` and `mdc-menu`.

The heading should read as follows:

#### Using `mdc-select` as a standalone component

The code block should contain the following lines:

```scss
@import "@material/mdc-list/mdc-list";
@import "@material/mdc-menu/mdc-menu";
@import "@material/mdc-select/mdc-select";
```

Reported in #2333

**Comment by mgiuffrida** [comment]
In particular, I didn't realize that import order matters.

**Comment by ruwaroshan** [comment]
Thanks @patrickrodee ,
I have changed the import order and now it is working fine.

**Comment by kfranqueiro** [comment]
This is now obsolete, as MDC Select now makes use of a native select element to take advantage of native keyboard behavior and integrate with forms.  MDC Menu and MDC List styles will no longer be needed for MDC Select.
