### ISSUE TITLE
Drawer demos: Add the class to the parent  as was defined on line 115

### ISSUE THREAD

**Issue by rubenmendoza** [material-components/material-components-web#2357]
add:
el.classList.add(activatedClass);
remove:
event.target.classList.add(activatedClass);

https://github.com/material-components/material-components-web/blob/cc50c6df9a590832e7547f7a190044f30e333e78/demos/drawer/permanent-drawer-above-toolbar.html#L191

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. Given that you've managed to track the issue down to a single line and have suggested a legitimate fix, I'm going to make this a help-wanted issue.

Feel free to open a PR resolving this. We're always happy to get community bug fixes!

Thanks!

**Comment by kfranqueiro** [comment]
I'd add that this issue exists in each of the 4 drawer demos, not just the one identified in this issue.

It definitely is an issue though (to repro, click one of the list items' icons directly rather than just the text), so thanks for spotting it!

**Comment by englishextra** [comment]
I have to add that in a few recent days something went wrong with the CSS
look how ugly the hamburger button sticks to the title in drawer demo
```html
<div class="mdc-toolbar__row">
				<section class="mdc-toolbar__section mdc-toolbar__section--align-start">
					<button class="demo-menu material-icons mdc-toolbar__menu-icon">menu</button>
					<span class="mdc-toolbar__title catalog-title">Temporary Drawer</span>
				</section>
			</div>
```
https://material-components-web.appspot.com/drawer/temporary-drawer.html

**Comment by kfranqueiro** [comment]
@englishextra whoa, yeah, that shouldn't have happened. Would you mind reporting that as a separate issue though?

**Comment by englishextra** [comment]
@kfranqueiro https://github.com/material-components/material-components-web/issues/2371

**Comment by kfranqueiro** [comment]
Hey, thanks for poking this issue. We removed the `demos/drawer` folder in favor of screenshot test pages we created under `test/screenshot/spec/mdc-drawer`, and MDC Drawer now automatically maintains activated state via MDC List, so this issue is now obsolete. We missed it when we merged the new drawer code.

Sorry for the confusion!

**Comment by thdk** [comment]
@kfranqueiro alright! You're welcome! :)
