### ISSUE TITLE
mdc-text-field disabled attribute deleted by MDC-Web library

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#2363]
Using JS `.setAttribute("disabled", "disabled");` to disable a textbox behaves in a non-standard way. The `disabled` attribute on the `input` element is not applied. Instead, a class `mdc-text-field--disabled` is added to the `input`s parent. ...what is happening to the `disabled` attribute? 

One should be able to detect `disabled` by referencing the `input`.disabled.

ALSO: You can tab into a disabled text-input...?

![capture](https://user-images.githubusercontent.com/12751611/37127290-bfc4a332-223a-11e8-8621-e8b925706fa3.JPG)

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. It's difficult to tell from just the description where exactly the problem could be occurring.

Could you please update this issue with a Codepen that reproduces it?

Thanks!

**Comment by rhroyston** [comment]
Here you go. Please mail the t-shirt, hat, and stickers to 18432 Lake Iris Ave Baton Rouge LA 70817 :-)

https://codepen.io/rhroyston/pen/ZxEyqa

**Comment by rhroyston** [comment]
Here it is:  https://codepen.io/rhroyston/pen/ZxEyqa

...Am I doing something wrong?

**Comment by rhroyston** [comment]
My bad, I was setting the MDC-Library to disable the inputs but `myInput.disabled` failed to set the disabled attribute. Using `.setAttribute("disabled", "disabled");` fixed it.

SORRY!

https://codepen.io/rhroyston/pen/ZxEyqa

**Comment by patrickrodee** [comment]
No worries! I'd *strongly* suggest using the component `disabled` property to modify the disabled state of the text field. It'll ensure that any other business logic gets executed.

You can [read more about the Textfield component API here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#mdctextfield).
