### ISSUE TITLE
dynamic text box insertion inside dialog not working

### ISSUE THREAD

**Issue by joshongit** [material-components/material-components-web#2364]
**  I have posted this in mdl group. Since its upgrading to material component raising it here.   Same issue persist in material component web too ** 

Trying to include text box on demand inside dialog which is not working properly.   

Text box's own css animations like  highlighting on focus, floating label are not working properly. Please check the below code pen for example.

https://codepen.io/anon/pen/xYvjBE   ( click on the dynamic box  & static box to see the difference)

Please suggest some solution or it is an expected behavior?

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. From looking at the Codepen you supplied, it seems you're using Material Design Lite (MDL). While this project indeed grew out of MDL, this is a completely separate project with no interoperability or relation to MDL. I'm going to close this issue.

I'd suggest updating your demo with our components. If the same problem is present, feel free to open a new issue. We're happy to help resolve issues with our project!

Thanks!

**Comment by joshongit** [comment]
Yes Patrick this issue exits even with material component web.  I have tried it in my local system after that only raised it here.  You can try it your own mentioned like in that codepen example (though its for mdl, same implementation for material component web will reproduce the issue ) 

Thanks.
