### ISSUE TITLE
Changing theme-variables with SASS only works for some components

### ISSUE THREAD

**Issue by SVAR7BERG** [material-components/material-components-web#2365]
Example:

> $mdc-theme-primary: #1A3E5D;
> $mdc-button-height: 1337px;
> 
> @import "@material/toolbar/mdc-toolbar";
> @import "@material/button/mdc-button";

The new Toolbar-color is being applied, but the new button height isn't.

Am I missing anything?

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. I'm curious why you're setting button height via the SASS variable instead adding a class and setting the height there.

Could you provide some detail about your use case?

Thanks!

**Comment by SVAR7BERG** [comment]
Thanks for replying :)

Was actually just an example, the goal would be to have a constantly changed button-height (as an example) throughout the whole application.

**Comment by patrickrodee** [comment]
Happy to help!

If that's your goal, I'd suggest adding a class to all buttons and modifying the height that way.

We could expose hundreds of variables for customizing everything globally, but that becomes a slippery slope of maintainability. The classes may require more work up front but when you encounter that one weird case where you need a button to *not* be that global height, the class method will have proved its value.

I'm going to close this for now. Feel free to submit other issues if you encounter any bugs.
