### ISSUE TITLE
mdc-menu--open out of place on mdc-dialog

### ISSUE THREAD

**Issue by rubenmendoza** [material-components/material-components-web#2369]
Hello Team,

Using an mdc-select component on a dialog will render the list out of place. I have created this pen to reproduce the issue:

[https://codepen.io/linear/pen/YazeQx](https://codepen.io/linear/pen/YazeQx)

Thanks,

**Comment by patrickrodee** [comment]
Thanks for submitting an issue.

This is a duplicate of #719 so I'm going to close it.
