### ISSUE TITLE
mdc-card: Consider centering background image

### ISSUE THREAD

**Issue by pshe94** [material-components/material-components-web#2370]
As in title, consider using `background-position: center` for background of `mdc-card__media`. Right now, if container is set to have aspect ratio of 16:9, and background image has aspect ratio of 3:4, bottom part of the background is invisible. I think setting position to center as default would be optimal solution for most cases, so if needed, image will be centered and cut evenly from the sides.
[Here is an example.](https://codepen.io/pshe94/pen/vRYjXE)

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. Given that you've tracked down the issue to a single line and have a working example, I've marked this as help wanted.

You're more than welcome to submit a PR resolving this. We're always happy to get bug fixes from the community!

Thanks!
