### ISSUE TITLE
mdc-chips: Choice chip set doesn't work properly if one of the chips has 'mdc-chip--selected' class added manually

### ISSUE THREAD

**Issue by pshe94** [material-components/material-components-web#2374]
### What MDC Web Version are you using?

> 0.32.0

### What browser(s) is this bug affecting?

> Google Chrome 65.0.3325.125

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

> 1. Create choice chip-set and add to one of the chips class `mdc-chip--selected`.
> 2. Select chip that isn't selected from the beginning.
> 3. Observe the chip that has been selected manually with class.
>
> [Example](https://codepen.io/pshe94/pen/KowWPW)

### What is the expected behavior?

> The chip that has been selected from the beginning should be deselected, if other chip has been selected.

### What is the actual behavior?

> The chip that has been selected from the beginning stays selected, so there are 2 chips selected at the same time.

### Any other information you believe would be useful?

> Deselecting the selected chip (the one that has `mdc-chip--selected` class added at the beginning) by clicking on it, and then selecting another chip, restores selection to the one that has been deselected.

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. We've added this to our internal tracker and will work on resolving it.
