### ISSUE TITLE
MDC layout grid with MDC card issue when Persistent Drawer open

### ISSUE THREAD

**Issue by ruwaroshan** [material-components/material-components-web#2379]
### What MDC Web Version are you using?

> 0.31.0

### What browser(s) is this bug affecting?

> In iPad landscape view. Can be generate on all browsers 1024 resolution.

### What are the steps to reproduce the bug?

> 1. Use persistent drawer template.
> 2. Create 3 column layout grid.
```
<div class="mdc-layout-grid">
  <div class="mdc-layout-grid__inner">
    <div class="mdc-layout-grid__cell"></div>
    <div class="mdc-layout-grid__cell"></div>
    <div class="mdc-layout-grid__cell"></div>
  </div>
</div>
```
> 3. Inside the cell, create another layout grid as follow.
```
<div class="mdc-layout-grid__cell mdc-card">
	<div class="widget-header">Header</div>
	<div class="mdc-layout-grid">
		<div class="mdc-layout-grid__inner">
			<div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
				Description goes like this
			</div>
		</div>
	</div>
</div>
```

> 4. Open the drawer.

![image](https://user-images.githubusercontent.com/12517126/37267853-c8c5450c-25e8-11e8-889f-726f3069998d.png)

> 5. Previously (In material version 0.26.0) it was handled by giving overflow hidden to .mdc-card. In new version it has been removed.

![image](https://user-images.githubusercontent.com/12517126/37267992-8db0dfa2-25e9-11e8-966a-a89f6534182f.png)

### What is the expected behavior?

> Content within MDC grid layout + MDC card should need to handle properly.

### What is the actual behavior?

> When using MDC grid layout + MDC card, inside content are overflowing.

**Comment by patrickrodee** [comment]
Thanks for submitting an issue.

Have you tried using a discrete `mdc-card` div instead of adding the card class to the `grid__cell` element? Both those classes are container elements and shouldn't be combined.

Try updating to the following:

```html
<div class="mdc-layout-grid__cell">
  <div class=" mdc-card">
    <div class="widget-header">Header</div>
    <div class="mdc-layout-grid">
      <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12">
          Description goes like this
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by ruwaroshan** [comment]
I have tried as in above example and it does not fix the issue.

**Comment by patrickrodee** [comment]
I see. I'm sorry you're still encountering issues.

Could you share a [Codepen](http://codepen.io/traviskaufman/pen/pNQmRp) that recreates the issue? It'll help us diagnose the problem better.

**Comment by ruwaroshan** [comment]
Here is the [Codepen](https://codepen.io/anon/pen/VXjBGe) and check it on Firefox 1024 resolution.

![image](https://user-images.githubusercontent.com/12517126/37637218-70f65c5e-2c2c-11e8-8b69-dfdfd79f4269.png)

**Comment by patrickrodee** [comment]
I see. That's definitely not right!

I've added this to our tracker to resolve. We'll update this issue as we work on it.

Thanks!

**Comment by Nomeyho** [comment]
I get the same issue. Any update?

From my tests:
- it is independent of the drawer
- it occurs when cards are used as cell content

**Comment by abhiomkar** [comment]
Closing this issue as obsolete.
