### ISSUE TITLE
Improving developer.md

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#238]
I think we could improve [developer.md](https://github.com/material-components/material-components-web/blob/master/docs/developer.md) to better serve its purpose. 

To give a little bit context of the document, it is under `docs/` and there are 2 direct links: one from [README.md](https://github.com/material-components/material-components-web/blob/master/README.md) at index level and another from [authoring-components.md](https://github.com/material-components/material-components-web/blob/master/docs/authoring-components.md) says "If you are brand new to the project, we recommend starting with our general [developer documentation](https://github.com/material-components/material-components-web/blob/master/docs/developer.md)." 

As it states, it is a quick overview for history and scope of the project, component architecture and what tools we use to build, test, manage the system. But given its position and content, I do have this question in mind:

**Who is our target reader for this doc?** 
It is the second link right after `quickstart`, which kind of states its importance among all the docs. But my question is who is a typical reader of the doc? The word `developer` could mean in this case users of mdc-web or contributors of mdc-web. But its content seems not very helpful for users, nor clear enough for developers to be involved in the project.

Maybe there are a few ways we can improve it:

- The overview part is pretty useful to know the scope of the project, so maybe we could merge `developer.md` with `docs/README.md` instead of hiding it under a separate doc.
- If we are targeting all developers and let them have a overview of the project, we could split the structure of this doc into **overview** - **If you are mdc-user** - **If you want use mdc with frameworks** - **If you want to contribute** and make it to be the directory of useful resource links.
- If it is targeting specific group of the above user, the content could also be more concentrated toward what they need.

This is not something urgent that we need to do but I think it will be overall helpful to make our documentation more helpful to all developers. Let me know your thoughts, thanks!

**Comment by traviskaufman** [comment]
Agreed with the points above. Let's put the overview section into `docs/README.md`, and take the rest of the sections and simply link to their relevant docs in a table of contents within `docs/README.md`.

**Comment by moog16** [comment]
We don't have developer.md readme. Closing.
