### ISSUE TITLE
Bug in examples of `authoring-components.md`

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#239]
The first example in `authoring-components.md` seems not working.

```
class RedblueTogglePrototype {
  get toggled() {
    return this.root.getAttribute('aria-pressed') === 'true';
  }

  set toggled(toggled) {
    this.toggle(toggled);
  }
....
  toggle(isToggled = undefined) {
    ...
    const toggled = wasToggledExplicitlySet ? isToggled : !this.toggled_;
    ...
  }
}
```

In this example, the attribute is named `toggled` but in the `toggled` method we are retrieving `this.toggled_` and it is always `undefined`. I ran this in the vanilla browser environment and that's the case. However, if it need some trick to make it work, we may specify that in the doc.

**Comment by traviskaufman** [comment]
Whoops! That should be `this.toggled`.

**Comment by yeelan0319** [comment]
Resolved!
