### ISSUE TITLE
Label in TextArea should be full width, and not show any TextArea text above the label

### ISSUE THREAD

**Issue by sfdexter** [material-components/material-components-web#2392]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?
0.32.0 

### What browser(s) is this bug affecting?
Chome
> Please include the browser version. A user-agent string is also quite helpful.
Chrome  64.0.3282.186

### What OS are you using?
OS X

### What are the steps to reproduce the bug?
1) Navigate to demos page : https://material-components-web.appspot.com/text-field.html
2) Scroll down to "TextArea"
3) Enter "8" and then [Enter] 10 times

### What is the expected behavior?
Should not be able to see any characters behind the Text Area Label

> Please describe what the component/code should be doing that it's not.

### What is the actual behavior?

Can see a little bit of one of the "8"s above "Textarea Label"

**Comment by kfranqueiro** [comment]
I checked with Alex and the reason for this is that we adjusted the label as much as we could without risking it overlapping (and "eating away at") the borders of the textarea at various zoom levels.

**Comment by patrickrodee** [comment]
Good to know, thanks Ken. I'll discuss with the designers and see what they have to say about this.

**Comment by williamernest** [comment]
Design guidance is that the label should be full width and not show any text at the top. Add to tracker.
