### ISSUE TITLE
How to dangerouslySetInnerHTML for Textfiled helpText ?

### ISSUE THREAD

**Issue by dipakchandranp** [material-components/material-components-web#2394]
I am using [`Textfiled`][1] component with an `html string` as `help text` getting following `warning` in the browser console:
```
    Warning: Failed prop type: Invalid prop `helptext` of type `object` supplied to `t`, expected `string`.
        in t (created by DetailsForm)
        in DetailsForm (created by Unknown)
        in div (created by Unknown)
        in form (created by Unknown)
        in dialog (created by Unknown)
        in Unknown
```

This is how I am using `Textfiled` component: 
```
        <Textfield
           name="bill"
           floatingLabel="Total bill"
           disabled={this.state.isDisabled}
           helptext={helpTextBill}
           helptextPersistent
           value={this.state.bill}
        />
```
Where the value of `helpTextBill` is:
```
    helpTextBill = (<span>For details visit <a href="/url-path/"> here </a></span>) 
```
This is just warning, but would like know how to handle and resolve this. 

  [1]: https://react-mdc.github.io/#/textfield

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. I'm going to discuss with our designers about what content should be allowed in a textfield help text element.

Thanks!

**Comment by dipakchandranp** [comment]
@patrickrodee  Thanks.
As of now I resolved this issue by creating an custom component using the `TextField` to have `helptext`.

**Comment by williamernest** [comment]
@dipakchandranp Thanks for filing this issue, and I'm glad you found a solution. The component uses `innerText` to set the text value of the helper text element and for security reasons (XSS specifically), we've decided to not change it to  `innerHTML`. 

However, you can still change the helper text content using javascript by querying for the element and using either `innerHTML` or `appendChild`.

**Comment by dipakchandranp** [comment]
@williamernest Thank you for the details.
