### ISSUE TITLE
Fix padding on buttons

### ISSUE THREAD

**Issue by aprigogin** [material-components/material-components-web#2400]
Currently horizontal padding on buttons is not customizable, that needs to change.

**Comment by lynnjepsen** [comment]
After much discussion

- [ ] The icon-less text button (not contained) needs 8px padding on each side (currently it is 16px)
- [ ] The contained button with an icon should have 12px padding to the left of the icon, 8px padding between the icon and the text, and 16px padding to the right of the text (right now it is 16px, 8ish, 16px)
- [ ] The contained button with an icon should handle RTL by flipping the icon to the right side, and all appropriate padding should also flip
- [ ] The text button with an icon needs an audit for its padding (not sure if it should be closer to the icon-less text button, or closer to the contained button with an icon)
- [ ] The text button with an icon should also handle RTL 

Follow up PRs might add a Sass mixin to customize the horizontal padding...but we'll do the above items first
