### ISSUE TITLE
Theme switcher menu icon in theme demo is offset

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#2411]
### What MDC Web Version are you using?

0.32.0

### What browser(s) is this bug affecting?

Chrome (presumably also others)

### What OS are you using?

> OS X

### What are the steps to reproduce the bug?

Go to http://material-components-web.appspot.com/theme/index.html and look at the top right

### What is the expected behavior?

The theme switcher icon should be centered in the toolbar

### What is the actual behavior?

Interestingly, the states/ripple effects for the icon seem like they're in the right place but the icon isn't...

![image](https://user-images.githubusercontent.com/398379/37480842-9fa4eb1c-2856-11e8-9373-4584303c2a3b.png)

### Any other information you believe would be useful?

I wonder if this was triggered by toolbar padding fixes?

**Comment by patrickrodee** [comment]
Sounds like it's time for some border-box setting!

**Comment by kfranqueiro** [comment]
Presumably related to #2373.

**Comment by williamernest** [comment]
This issue is related to #2373 which is in the tracker.
