### ISSUE TITLE
Tab Bar initialization throws error when tab bar element with ID does not exist in HTML

### ISSUE THREAD

**Issue by bellizio** [material-components/material-components-web#2418]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

0.30.0

### What browser(s) is this bug affecting?

Chrome, Firefox, Safari

### What OS are you using?

Mac OS 10.13.3

### What are the steps to reproduce the bug?

1. Run the following code pen: https://codepen.io/anon/pen/rdMBej?editors=1010
2. View the browser's console (refresh the page if necessary)
3. Observe the following error: `Uncaught TypeError: Cannot read property 'querySelector' of null`

**Note**: The error displayed in the console varies slightly by browser, but it is essentially the same. The one noted above is from Chrome.

### What is the expected behavior?

The tab bar initialization code should not throw an error if the tab bar element with ID is not in the HTML.

### What is the actual behavior?

The tab bar initialization code throws an error in the console when document.querySelector returns null or undefined for the tab bar element.

### Any other information you believe would be useful?
I have only observed this issue with tab bar initialization, but it's possible the issue exists with other components' initialization. In my case (a common one), I'm loading a main app.js script file for my application. The app.js file is loaded on the main home route and includes the tab bar init code, but the tab bar element exists on another route. Therefore, since the tab bar element is not on the page when the init code runs for the first time, an error is thrown.

**Comment by williamernest** [comment]
Thanks for raising this issue. From our standpoint, the library should throw an error if the required DOM structure doesn't exist when it's initialized. It sounds like you're using a modern framework (Angular/React) and trying to initialize the TabBar component too early. 

Can you delay initializing the TabBar until after your content is rendered?

**Comment by bellizio** [comment]
@williamernest In my case, I'm using the library with a node express app. And given that the tab bar markup lives on a route that the user navigates to via a link/button, a timeout won't work.

What I did to work around this issue was the following:
```
var myTabBar = document.querySelector('#my-tab-bar');

if (myTabBar) {
  var myTabBarInit = new mdc.tabs.MDCTabBar(myTabBar);
  
  // additional tab bar code
}
```

**Comment by williamernest** [comment]
@bellizio I'm not fully understanding how your rendering your page. Are you using a dynamic templating library of some kind? 

If the user is navigating to different route, the TabBar should be initialized after the user navigates.

**Comment by bellizio** [comment]
@williamernest it's an express app, so I'm using the express router for routing and handlebars for templating. Each route has its own view partial associated with it like with most modern web frameworks. I'm loading a single `app.js` file the for the entire app on the client side, and it contains the MDC init code.

The scenario is as follows:
- user navigates to home route (e.g `localhost:4000`)
  - `app.js` is loaded -> no tab bar present in view -> error thrown
- user navigates to route with tab bar (e.g. `localhost:4000/route-with-tabs`)
  - `app.js` is loaded -> tab bar present in view -> no error

**Comment by williamernest** [comment]
@bellizio Most modern front end frameworks wait until after the partial has been rendered before executing the Controller/Component for that particular view. They also capture navigation within an application and route the user to the new view partial and then execute the corresponding code after that view has been rendered. 

I believe this can also be done with Handlebars by putting the javascript in your `route-with-tabs` view. You could also attempt to do this using a Handlebars helper.

I think your solution is the only one that will work if you're using the same `app.js` for multiple pages and you have to keep a reference to the tabBar object after you initialize.

**Comment by bellizio** [comment]
@williamernest regardless of the framework or tech stack, would it not be a good idea to have the MDC library code check if an element is null or undefined before initializing it?

I'm open to helping contribute and make the change via a PR if there is support for it. Although, I have not yet looked at the source code.

**Comment by williamernest** [comment]
@bellizio We make the assumption that the element passed to us is a valid element. Any null/undefined checking should be done prior to initializing the component.
