### ISSUE TITLE
mdc-text-field in mdc-menu doesn't accept spaces

### ISSUE THREAD

**Issue by abraham** [material-components/material-components-web#2422]
### What MDC Web Version are you using?

0.32.0

### What browser(s) is this bug affecting?

- Chrome 66.0.3359.33 (Official Build) beta (64-bit)
- Safari 11.0.3 (13604.5.6)
- Firefox 59.0.1 (64-bit)

### What OS are you using?

macOS 10.13.3 (17D102)

### What are the steps to reproduce the bug?

1. Place `mdc-text-field` in a `mdc-menu`.
2. Open menu and select text-field.
3. Enter `a b c` with spaces.
4. Observe that the 

[Demo codepen](https://codepen.io/abrahamwilliams/pen/ZxpOKo?editors=1010)

### What is the expected behavior?

Spaces should not be prevented from being entered and the value of the text-field should be `a b c`

### What is the actual behavior?

Entered spaces are ignored and the value of the text-field is `abc`

**Comment by williamernest** [comment]
Thanks for filing this issue. Can you elaborate on some use cases where you would want to use a text field in a menu instead of using a dialog? The material guidance states that menus should be used to display a list of choices and not a list of inputs.

**Comment by williamernest** [comment]
Issue closed due to no response. According to the material spec, menus are used to display a list of choices and are not designed to accept input.

**Comment by apoterenko** [comment]
This is workaround works well

```
  public componentDidMount(): void {
    super.componentDidMount();
    ...

    const originalHandleKeyboardDownFn = this.mdc.foundation_.handleKeyboardDown_;
    this.mdc.foundation_.handleKeyboardDown_ = function() {
      if (self.preventKeyboardDownHandling) {
        return false;
      }
      return originalHandleKeyboardDownFn.apply(this, arguments);
    };
  }

...

  private onInputFocus(): void {
    this.preventKeyboardDownHandling = true;
  }

  private onInputBlur(): void {
    this.preventKeyboardDownHandling = false;
  }
}
```
