### ISSUE TITLE
Optionally set typography font-family var for headings separate than content

### ISSUE THREAD

**Issue by benjaminapetersen** [material-components/material-components-web#2427]
For many projects, it is common to have a display font separate from content, such as a sans-serif for headings & a serif for copy.  It would be useful if `$mdc-typography-font-family` in `@material/typography/_variables.scss` was split into two variables, one for headings && one for copy. The default out-of-the-box behavior could still be set to ` Roboto, sans-serif !default;` & conform to spec, but it would also allow consumers of the library to minimally integrate their brand into a project that will otherwise conform to material design.

Thanks for considering!

**Comment by williamernest** [comment]
Thanks for raising this issue. We currently don't have any plans to implement a way to split the typography into different fonts. It seems like you could easily implement this using your own class. 

```
.demo-class {
      font-family: Arial, Helvetica, sans-serif;
}
```
and
```
<h1 class="mdc-typography--display3 demo-class">Hello World</h1>
```

or you could override all the typography header styles with the new font-family.

**Comment by benjaminapetersen** [comment]
Right, but then you are adding a class simply to take away styles, which tends to be a CSS code smell. ☹️ 

The `mdc-typography--*` classes are quite long, adding an additional class to undo what has been done, vs being able to control via a SASS variable, is rather unfortunate.

**Comment by kfranqueiro** [comment]
FYI, we've received new design guidance which suggests allowing font-family to be customized per-level in the typography scale, as opposed to the current behavior where font-family is only set once in typography's base styles.

See #2465.

**Comment by benjaminapetersen** [comment]
+1 that would be a great improvement.
