### ISSUE TITLE
mdc-ripple: Different color of ripple and component content

### ISSUE THREAD

**Issue by pshe94** [material-components/material-components-web#2429]
Let's say we have icon toggle colored to black (both icon and ripple). 
When ripple and the icon have the same color, then everything is alright. But, if I would like to change color of the icon to white, but leave the ripple color black, then, when icon-toggle is pressed, white icon will be covered by black ripple, which makes it look weird. 

[Example here](https://codepen.io/pshe94/pen/VXmzKe)

Setting `z-index: 1` for the content of the component fixes that issue, but this problem doesn't apply for all components (like card).
So, my question is: Is using different colors for ripple and component content in accordance with guidelines, and if yes, can this problem be addressed?

**Comment by williamernest** [comment]
Thanks for filing the issue. The design guidelines are that the ripple color matches the ink color of the component. If you need to change the ripple color you can use the `mdc-states` mixin (example from our button demo https://github.com/material-components/material-components-web/blob/670c349417ef7922aac37f1c8cd1682f93b41794/demos/button.scss#L51 )
