### ISSUE TITLE
Add user-select: none; to buttons and FABs

### ISSUE THREAD

**Issue by jecisc** [material-components/material-components-web#243]
I tried the demo [here](https://material-components-web.appspot.com/button.html). In the "buttons" section there is a div like button. It's possible to select the text of this button. (At least on Firefox 51 on OSX El Captain)

Maybe it would be good to set the `user-select` property of the buttons to none to avoid this. I am not sure this is wanted but I think it would be nice.

**Comment by traviskaufman** [comment]
Seems reasonable, would be good for consistency.
