### ISSUE TITLE
Typography Display 4 is huge (unusable?)

### ISSUE THREAD

**Issue by benjaminapetersen** [material-components/material-components-web#2430]
So is:

```
.mdc-typography--display4 {
    font-size: 7rem;
}
```
really correct via spec? The text is HUGE. Referencing [Typography Guidelines](https://material.io/guidelines/style/typography.html), low on the page there is some pretty large text, but it is in an image, not in actual use on the page itself.  It seems that a font size this large is not terribly usable.

**Comment by williamernest** [comment]
Thanks for filing this issue. Yes, the typography styles match the spec. There is a range of styles provided based on various use cases.
