### ISSUE TITLE
FAB Speed dial "fling" actions

### ISSUE THREAD

**Issue by griest024** [material-components/material-components-web#2432]
Do you have any plans to implement the fling actions for the speedial style FAB? For reference, here are some demonstrations from the material spec:

https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B8v7jImPsDi-ZFR3dGtLUjZad1U/components-buttons-fab-transition-speeddial-01.webm

https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B8v7jImPsDi-ajh6QTBYN05YVDg/components-buttons-fab-transition-speeddial-02.webm

**Comment by williamernest** [comment]
Thanks for the question. We're working on a roadmap for the rest of the components in the spec. We'll post a link in the main readme when we publish it.
