### ISSUE TITLE
mdc-checkbox__checkmark fails on dynamic creation of mdc-checkbox

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#2435]
Here's the codepen: https://codepen.io/rhroyston/pen/NYdrdG

![image](https://user-images.githubusercontent.com/12751611/37619501-aefa2594-2b87-11e8-8548-e352f59bb95e.png)

**Comment by williamernest** [comment]
@rhroyston Dynamically creating SVG elements with Javascript is tricky. It requires you to create the svg elements using the namespace with `createElementNS()`. 

Example 
```
  var productCheckboxSvg = doc.createElementNS("http://www.w3.org/2000/svg", "svg");
  var productCheckboxPath = doc.createElementNS("http://www.w3.org/2000/svg", "path");
```

https://codepen.io/williamernest/pen/zWNZwe
