### ISSUE TITLE
How to trigger MDCSelect:change?

### ISSUE THREAD

**Issue by QJan84** [material-components/material-components-web#2445]
Hello!

How can I trigger all functions in an MDCSelect:change?
  
```
  const select = new mdc.select.MDCSelect(el);
 
  // Independent function executed - now trigger MDCSelect:change
  inputTyping(el, select);

  select.listen('MDCSelect:change', () => {
   function a() {  // stuff }
   function b() {  // stuff }
   function c() {  // stuff }
  }
```

**Comment by williamernest** [comment]
You can dispatch your own event on an element using 
`el.dispatchEvent(new Event('MDCSelect:change'));`
Based on your previous post, I would suggest you store the listen function in a variable and just call it directly instead of trying  to trigger our events.
