### ISSUE TITLE
MDC Dialog with textfield crashes Microsoft Edge on action button click

### ISSUE THREAD

**Issue by seb-ster** [material-components/material-components-web#2446]
### What MDC Web Version are you using?

0.33.0

### What browser(s) is this bug affecting?

Microsoft Edge 41.16299.248.0

### What OS are you using?

Windows 10 Home (64bit)
Version 1709
Build 16299.309

### What are the steps to reproduce the bug?
Using following HTML:
```
<html class="mdc-typography">
  <head>
    <title>MDC Textfield in Dialog test</title>
</head>
  <body>
    <aside class="mdc-dialog" id="mdc-dialog-default" role="alertdialog">
      <div class="mdc-dialog__surface">
        <header class="mdc-dialog__header">
          <h2 class="mdc-dialog__header__title">
            The Dialog
          </h2>
        </header>
        <section class="mdc-dialog__body">
          <div>some text field</div>
          <div>
            <input type="text">
          </div>
        </section>
        <footer class="mdc-dialog__footer">
          <button class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel" type="button">Cancel</button>
          <button type="button">Accept</button>
        </footer>
      </div>
      <div class="mdc-dialog__backdrop"></div>
    </aside>

    <main style="display: flex;flex-flow: column;height: 100vh">
        <section class="mdc-dialog__body">
          <div>some text field</div>
          <div>
            <input type="text">
          </div>
        </section>
        <section>
          <button class="mdc-button" type="button">Cancel</button>
          <button type="button">Accept</button>
        </section>
    </main>
  </body>
 </html>
```

And this JS:
```
import '@material/dialog/mdc-dialog.scss'
import {MDCDialog} from '@material/dialog';

var dialog = new MDCDialog(document.querySelector('#mdc-dialog-default'));

dialog.listen('MDCDialog:accept', function() {
  console.log('accepted');
})

dialog.listen('MDCDialog:cancel', function() {
  console.log('canceled');
})

dialog.show();

```

Try closing the Dialog via the action buttons and by clicking outside it.
Both with an empty textfield or textfield with content.
Try this also on the textfield and buttons on the underlying page.

### What is the expected behavior?

Expect normal closure of Dialog and a message in the console, corresponding to the pressed button (if any).

### What is the actual behavior?

Expected behavior on with an empty textfield or on the underlying page.
However if the textfield has content, browser freezes shortly, then reloads the page.
After multiple tries, Edge complains that the script on the page has a problem.
There is no console output.

### Any other information you believe would be useful?
Using Webpack 3.11.0. No Babel or other Loaders/Transpilers.
This only happens in Edge. No problems in IE, Chrome and FF.
In the above HTML and script I reduced the code and components to the minimum neccesary to reproduce the problem.

**Comment by williamernest** [comment]
@seb-ster Thanks for filing this issue! Is this related/same as #2241 ?

**Comment by seb-ster** [comment]
Edge behavior is the same. Although in my case this realy hinges on the Dialog component, as it seems to work normaly when outside of a Dialog. Edge also crashes when one closes the Dialog programatically with the `MDCDialog.close()` method

My Windows Event log:
```

Faulting application name: MicrosoftEdgeCP.exe, version: 11.0.16299.309, time stamp: 0x5a9791fa
Faulting module name: edgehtml.dll, version: 11.0.16299.309, time stamp: 0x4ad775d4
Exception code: 0xc0000005
Fault offset: 0x000000000044e470
Faulting process ID: 0x4088
Faulting application start time: 0x01d3c13e5c4ac72d
Faulting application path: C:\WINDOWS\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe
Faulting module path: C:\WINDOWS\SYSTEM32\edgehtml.dll
Report ID: ba0e3ec7-7f77-4b0a-8f5d-e530623849de
Faulting package full name: Microsoft.MicrosoftEdge_41.16299.248.0_neutral__8wekyb3d8bbwe
Faulting package-relative application ID: ContentProcess

Log Name:      Application
Source:        Application Error
Date:          21/03/2018 22:17:22
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      klein
Description:
Faulting application name: MicrosoftEdgeCP.exe, version: 11.0.16299.309, time stamp: 0x5a9791fa
Faulting module name: edgehtml.dll, version: 11.0.16299.309, time stamp: 0x4ad775d4
Exception code: 0xc0000005
Fault offset: 0x000000000044e470
Faulting process ID: 0x4088
Faulting application start time: 0x01d3c13e5c4ac72d
Faulting application path: C:\WINDOWS\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdgeCP.exe
Faulting module path: C:\WINDOWS\SYSTEM32\edgehtml.dll
Report ID: ba0e3ec7-7f77-4b0a-8f5d-e530623849de
Faulting package full name: Microsoft.MicrosoftEdge_41.16299.248.0_neutral__8wekyb3d8bbwe
Faulting package-relative application ID: ContentProcess
```

**Comment by williamernest** [comment]
Thanks for the extra information. I'm going to close this issue as a duplicate, and we'll continue to track this issue through the one already in our tracker.

**Comment by seb-ster** [comment]
Just some extra info.
I tried to get the specific JS line where the crash happens.
I filled the textfield, and then paused JS execution in the Debugger before pressing one of the buttons.
Then i went through the code step-by-step.
Et voila, no crash. 
The console outputs the associated 'cancelled' or 'accepted' message and the Dialog closes as expected.
