### ISSUE TITLE
Icon Toggle Documentation

### ISSUE THREAD

**Issue by iddan** [material-components/material-components-web#2448]
Icon Toggle assumptions should be documented:

### Aria Features effecting behaviour
 - aria-pressed
 - aria-disabled

### Aria Features effected by JS and should get defaults
 - aria-label

**Comment by williamernest** [comment]
Thanks for filing this issue. We've labeled this as `help-wanted` since it's pretty straightforward to add this to the docs. Feel free to submit a PR if you'd like.

**Comment by thdk** [comment]
Icon Toggle is deprecated. Should be done now in Icon Button(?)

Two useful links for information about aria attributes in general:

[Aria](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)
[Handling state with aria-pressed attribute ](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Mobile_accessibility_checklist#Handling_State)
