### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by deviousasti** [material-components/material-components-web#2451]
I've noticed that every two releases or so, there are breaking changes which completely break different parts of the application, and I'm having a bunch of commits simply labeled 'Fix mdc breaking <component>' every time I update. MDC doesn't follow semantic versioning, so I (or build tools) can't tell whether this is a bugfix release or a major one until it's upgraded and the actual pages are viewed.

Can this library be used (as of now) for production? 
Or should I wait until a milestone release?

**Comment by williamernest** [comment]
Thanks for raising this issue. The MDC Web library is ready for production use, but the API is not stable. We're working closely with the team to build out new functionality, and we still consider ourselves in an alpha stage of development. 

As we get closer to a full release, we'll evaluate our versioning process to ensure we're conveying the appropriate level of stability with our platform and API's.

**Comment by deviousasti** [comment]
That’s good to know.

I thought I’d make an issue just in case someone is facing this exact same problem 
of their UI breaking in a few places after upgrading.

Thanks.

Sent from Mail for Windows 10
