### ISSUE TITLE
Tab scroller arrows shouldn't be visible when tabs initially fit the the screen

### ISSUE THREAD

**Issue by yguedidi** [material-components/material-components-web#2456]
### What MDC Web Version are you using?

0.28

### What browser(s) is this bug affecting?

all

### What OS are you using?

Ubuntu 17.10

### What are the steps to reproduce the bug?

Look at the Tab Bar with Scroller on https://material-components-web.appspot.com/tabs.html with a browser view width of 1470px.

### What is the expected behavior?

The 9 tabs fits in the screen widthout the scroll arrows, they shouldn't be there.

### What is the actual behavior?

The scroll arrows are visible, which leads to a weird behavior with the last tab: it's the only one in the second page while it was possible to display it in the first page if arrows were not there

**Comment by williamernest** [comment]
@yguedidi Thanks for reporting this issue. We're currently working on another release of Tabs, so we'll incorporate this feedback into the design of the new component.
