### ISSUE TITLE
Tabs should be expended to take the full width when they fit in the screen width

### ISSUE THREAD

**Issue by yguedidi** [material-components/material-components-web#2457]
### What MDC Web Version are you using?

0.28

### What browser(s) is this bug affecting?

all

### What OS are you using?

Ubuntu 17.10

### What are the steps to reproduce the bug?

Simply use two tabs with a short label

### What is the expected behavior?

The tabs should take the full width of the screen, especially on mobile.

### What is the actual behavior?

The two tabs are centered

**Comment by williamernest** [comment]
@yguedidi Thanks for the feedback. We're currently working on another release of the Tab component, that will be flex-box based. It should cover this use case, and expand to fill the container if desired.
