### ISSUE TITLE
Add font-family to mdc-typography-styles variable

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2465]
Add font-family to mdc-typography-styles variable. This means dropping font-family from `mdc-typography-base` mixin...and renaming that mixin to `mdc-font-smoothing` mixin.

**Comment by kfranqueiro** [comment]
We need to figure out and document how users are expected to obtain a base font style for general text now.

If we remove the font-family from the base mixin, the only way to get a font-family is to apply one of the typography scale classes... and all of those (including body1 and body2) modify font size as well, which would presumably cause significant visual changes for many users.

Should there be a typography scale entry that leaves font-size at default to account for this? How do we make "default font" easy?

**Comment by acdvorak** [comment]
Closing in favor of #2466
