### ISSUE TITLE
Update mdc-typography-styles to match new guidance

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2466]
Add the following styles to mdc-typography-styles:
- [ ] Headline 1-6
- [ ] Subtitle 1 & 2
- [ ] Overline

And remove the following styles from mdc-typography-styles:
- [ ] Display 1-4
- [ ] Headline
- [ ] Title
- [ ] Subheading 1 & 2

Then update all references to `mdc-typography` across all components so that no components references a deleted style.

**Comment by rhroyston** [comment]
I would recommend honoring the legacy class names so as to support backward compatability. For example, `.mdc-simple-menu` was recently changed to `.mdc-menu` which broke alot of stuff on my site after upgrading MDC-web. 

I imagine that something like below would be fitting:

```
if(document.querySelectorAll(".new-classname" !== undefined || document.querySelectorAll(".new-classname" > 0)){
  //try and do do new thing
} else {
  //try and do old thing
}
```

**Comment by acdvorak** [comment]
This issue replaces #2465
