### ISSUE TITLE
Textfield - add password redaction/trailing icon on line

### ISSUE THREAD

**Issue by davidreher** [material-components/material-components-web#2468]
I am trying to implement a password redaction as outlined in https://material.io/guidelines/components/text-fields.html#text-fields-input-types:
![password redaction](https://user-images.githubusercontent.com/3942764/37961080-a05fc814-31b7-11e8-84bf-447b6d27352a.png)

I tried using the [trailing icon](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield/icon#trailing-icon) from the docs, but the `mdc-line-ripple` is not expanding under the icon. Instead the `mdc-line-ripple` stops right before the icon ...

**Comment by williamernest** [comment]
@davidreher Thanks for filing this issue. Have you added the `mdc-text-field--with-trailing-icon` class to the text field element? You also may have to adjust the the `bottom` value since it's not being used with a `-box` or `--outlined` text field class. 

https://codepen.io/williamernest/pen/MVOzpG

Let me know if this fixes your issue!

**Comment by davidreher** [comment]
@williamernest thanks for the codepen, I forgot to add `mdc-text-field--with-trailing-icon` to the `mdc-text-field` :disappointed_relieved:

**Comment by davidreher** [comment]
Isn't it an issue, that the input has a `padding-left`?
<img width="207" alt="bildschirmfoto 2018-03-28 um 08 00 48" src="https://user-images.githubusercontent.com/3942764/38011563-2bd3d754-325e-11e8-9aaf-7a1759da380d.png">

I can of course simply overwrite it, as I do with `bottom` value on the icon ...

**Comment by williamernest** [comment]
We haven't officially built out a class for the normal text field to have an icon, so we're using a class that was designed to be used with the `--box` variant. For now, I would say override it and once we built a `--with-trailing-icon` variant for the normal text field it'll be fixed.
