### ISSUE TITLE
Package mdc-top-app-bar Actions

### ISSUE THREAD

**Issue by PEM-FR** [material-components/material-components-web#2478]
Hello mdc web team,

First, I'd like to thank you for your amazing work.
I hope this issue will make sense, I have read the guidelines, but I am still not too sure of how to present things here.

I was wondering about two things regarding the top-app-bar component : 
1. Would it be possible to use <i></i> tag for the icon rather than putting it directly in the <a></a> ?
2. Would it be possible to add a label to actions?

I understand that icons stands well for applications (mostly due to screen sizes), but for a desktop website we might want to add some labels as well.
The a representing a link to something, it could/should be agnostic to the representation used for the user (be it a text or an image or both). It describes the role of the link, its destination, its target, and this, independently of what is in the tag, be it an img, an i, a span, etc. So IF it was possible to either use it as you do at the moment OR make it more explicit with an i and span, that would be awesome.

Thus, implementing the idea above, we could have something along these lines :
```html
<header class="mdc-top-app-bar">
  <div class="mdc-top-app-bar__row">
    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
      <a href="#" class="material-icons mdc-top-app-bar__navigation-icon">menu</a>
      <span class="mdc-top-app-bar__title">Title</span>
    </section>
    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">
      <!-- An action with icon and label -->
      <a href="#" class="mdc-top-app-bar__action-item" aria-label="Download"><i class="material-icons" alt="Download">file_download</i><span class="mdc-top-app-bar__action-label" >Download</span></a>
      <!-- An action with icon and without label, current way -->
      <a href="#" class="material-icons mdc-top-app-bar__action-item material-icons" aria-label="Print this page" alt="Print this page">print</a>
      <!-- An action with icon and without label, explicit way -->
      <a href="#" class="material-icons mdc-top-app-bar__action-item" aria-label="Print this page"><i class="material-icons" alt="Print this page">print</i></a>
      <!-- An action without icon, with label only -->
      <a href="#" class="material-icons mdc-top-app-bar__action-item" aria-label="Bookmark this page"><span class="mdc-top-app-bar__action-label">Bookmark</span></a>
    </section>
  </div>
</header>
```
Of course, the label could be optional. If present, it should be aligned with the icon.
I sincerely apologize if this issue does not follow your expected format, also please forgive my poor english as it is not my mothertongue and I am afraid it is very lacking.

Thank you again for your amazing work, I really enjoy working with mdc-web. If I could add a little bit of feedback : I would love it if all components shared the same approach of structure != representation != design.
For example : A link is a structure describing it's intent, it has a representation that might be an image, an icon, a text... and it's design could be a background colour, a foreground colour, a specific size, etc.

Best regards

**Comment by williamernest** [comment]
@PEM-FR Thanks for this questions. We haven't seen any design guidance about allowing for labels under action items in the top app bar, so I've tagged this as `needs-design-guidance` so I can get a chance to ask the designers about this use case.

**Comment by PEM-FR** [comment]
Thank you very much ! I really feel that sometimes a text is more helpful than an icon, having both being even better as it allows a user to understand very fast what the icon means. Once understood, the user can memorize the icon and use the image as a visual shortcut.
Having a wide screen with plenty of space could allow this while smaller sized screens would just use the icon plus "title" for pointer capable browsers and just the icon for touch devices.
If possible, I just don't want users to "click" on an icon just to know what is behind.
Of course, it should be optional, to allow devs to offer the best experience depending on their users and contexts.
In any case, thank you very much for your effort!

**Comment by williamernest** [comment]
@PEM-FR Does using tabs fit your use case? Tabs have a variation where you have an icon above a label, which seems to be exactly what you're looking for. The example on this page is using the `toolbar`, but the `top-app-bar` should work with a similar implementation. 

https://material-components-web.appspot.com/tabs.html

**Comment by PEM-FR** [comment]
@williamernest it's visually close but the intent is a bit different I guess.
First, tabs are, more or less, meant to be used for "already loaded content" and switching views / viewport to a specific content. Kind of like an anchor to scroll to a specific place in a page.
Which is not what I want to do. My Action buttons are links to other pages.
That is enforced, in mdc, by the fact that tabs are subject to swiping. 
So, overall, I feel that, eventhough it is visually close to what I want, it does not really work in practice.

I might want tabs in my main content area or as submenues in a single page application approach, but not for traditional top-bar menues.

In any case, I thank you for your idea, which I considered but cannot use I am afraid.

**Comment by williamernest** [comment]
@PEM-FR I discussed this with design and it's not something we should support in our current component. The overall recommendation was to use a tooltip to give the user more text information if needed.
