### ISSUE TITLE
Add new surface and on-surface variables to mdc-theme

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2482]
`mdc-theme-surface` and `mdc-theme-on-surface` are global variable clients can set to a hex value before importing any MD Web components. Various MD Web components will look to mdc-theme-surface and mdc-theme-on-surface for color, e.g. cards and chips.

We will demonstrate this `mdc-theme-surface` with a new dark theme for "shrine" on the theme catalog page.

**Comment by acdvorak** [comment]
- [ ] Automatically calculate `on-surface` as `#ffffff` or `#000000`
