### ISSUE TITLE
Customize the color of the chip icons separately from the text label

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2484]
Still deciding if --leading-icon and --trailing-icon should be the same color...or if we should also allow clients to customize them separately

**Comment by mgr34** [comment]
Perhaps a separate issue, but I believe the SASS mixin `mdc-chip-fill-color-accessible` should decorate the `--[leading|trailing]-icon`.  For example if you were to call `mdc-chip-fill-color-accessible(navy)` the chip text color will appropriately become `var(--mdc-theme-text-primary-on-dark,white)` But the icons will not be accessible. Their color contrast is to low.
