### ISSUE TITLE
documentation issue: mdc-toolbar-ratio-to-extend-flexible

### ISSUE THREAD

**Issue by MrChriZ** [material-components/material-components-web#2485]
Minor documentation issue
This page :https://github.com/material-components/material-components-web/tree/master/packages/mdc-toolbar

In the section **Custom height of flexible space**:
```

<style>
  #my-flexible-header {
    --mdc-toolbar-ratio-to-extend-flexible: 3;
  }
</style>
<header class="mdc-toolbar mdc-toolbar--flexible">
  <div class="mdc-toolbar__row">
    ...
  </div>
</header>

```
However   #my-flexible-header is not an ID that appears to be used.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

I believe we just need to add `id="my-flexible-header"` in the README:

```html
<header class="mdc-toolbar mdc-toolbar--flexible" id="my-flexible-header">
```

(FYI, `mdc-toolbar` is being deprecated in favor of `mdc-top-app-bar`.)

**Comment by palnes** [comment]
@acdvorak Is there more documentation about the deprecation of `mdc-toolbar`?

**Comment by robbyrice** [comment]
@palnes I think this should help out. [mdc-toolbar documentation page](https://github.com/material-components/material-components-web/tree/master/packages/mdc-toolbar)

**Comment by asyncLiz** [comment]
Closing since mdc-toolbar doesn't exist anymore.
