### ISSUE TITLE
Clicking textfield label must focus textfield

### ISSUE THREAD

**Issue by apoterenko** [material-components/material-components-web#2488]
## Bugs

This is a bug.
I am using v33 and this issue is reproduced for me

### What MDC Web Version are you using?

0.33.0

### What browser(s) is this bug affecting?

Chrome 65
Microsoft Edge 41

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. https://material-components-web.appspot.com/text-field.html
2. Need to remove a "for" attribute
`<label class="mdc-floating-label">Text Field</label>`
3. Need to click a field label

### What is the expected behavior?

Clicking textfield label must focus textfield

### What is the actual behavior?

No reaction

![mdc_issue](https://user-images.githubusercontent.com/12325691/38119423-52aa5944-33ca-11e8-8afa-772feaa7bebb.png)

**Comment by williamernest** [comment]
The label element retains it's native HTML behavior of selecting the specified element by ID when using the `for` attribute. The MDC Web library has taken that stance that we shouldn't be changing/duplicating native behavior when possible. 

One way of getting around this if you can't use the `for` element (if you must remove the form attribute), is to add 
```
.mdc-floating-label {
  pointer-events: none;
}
```

**Comment by apoterenko** [comment]
Thank you!!
