### ISSUE TITLE
`material-components-web` v0.34.0 missing `@material/tab@^0.34.0` dependency,

### ISSUE THREAD

**Issue by pgbross** [material-components/material-components-web#2498]
Latest release, `material-components-web` v0.34.0 appears to be missing `@material/tab@^0.34.0` dependency in the npm registry.

```
npm i material-components-web@0.34.0
```
throws error

```
npm ERR! code E404
npm ERR! 404 Not Found: @material/tab@^0.34.0

```

**Comment by kfranqueiro** [comment]
Sorry for the turbulence, and thanks for reporting. Looks like we inadvertently added a dependency to `material-components-web` on a package that still has `private: true`. I've informed the appropriate team members so we can figure out which way we want to resolve this and cut a patch release.

**Comment by kfranqueiro** [comment]
0.34.1 is now released, which installs successfully.
