### ISSUE TITLE
Temporary Drawer Doesn't Cover Buttons

### ISSUE THREAD

**Issue by Zunawe** [material-components/material-components-web#250]
MDC-Web Version 0.3.0

Tested on:
- Chrome (56.0.2924.87)
- Firefox (51.0.1)
OS: Ubuntu 16.04 (4.4.0-59-generic)

On any page that uses a temporary drawer, add any button with the mdl-button class or mdl-fab class in a location that will be underneath the drawer when it opens. For example, in the temporary-drawer.html demo:
```
<main class="demo-main">
      <h1 class="mdc-typography--display1">Temporary Drawer</h1>
      <p class="mdc-typography--body1">Click the menu icon above to open.</p>

      <button class="mdc-button">Cool Button</button>
</main>
```
The drawer should cover the button as it does with other components, but the button is drawn over the drawer.
This is not an issue with classless buttons. I haven't played around a ton with variations on buttons, but it looks like anything mdl-button or mdl-fab causes it.

**Comment by Garbee** [comment]
Duplicate on #154 it appears to me. Have you tried with the code in master?

**Comment by Zunawe** [comment]
I was using the material-components-web package in the master branch which I just downloaded for the first time earlier today.

**Comment by traviskaufman** [comment]
Hey @Zunawe,

I just tried to repro your issue on http://material-components-web.appspot.com/drawer/temporary-drawer.html (using material-components-web@0.4.0) and it looks like it is indeed covered by the drawer.

Can you verify that this is still happening with the latest version of the code?

**Comment by traviskaufman** [comment]
![repro-vid](https://cloud.githubusercontent.com/assets/1185269/22700489/e0f7a542-ed28-11e6-9448-c9cc8827bfde.gif)

**Comment by Zunawe** [comment]
An update to v0.4.0 did fix it. Sorry for the confusion.
