### ISSUE TITLE
Fab: SVG/Img icons display very large within the FAB

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#2502]
Using an SVG or IMG with a FAB results in a very large icon filling the FAB. 

![image](https://user-images.githubusercontent.com/34519388/38283715-7237302a-376c-11e8-861b-93e41dfb6a21.png)

The FAB should allow for elements other than `a`/`span`/`i` to display icons. This can easily be done by adding the following to the existing `mdc-fab__icon` class. 
```
.mdc-fab__icon {
...
    width: 24px;
    height: 24px;
    margin: auto;
    fill: currentColor;
}
``` 
Which results in: 
![image](https://user-images.githubusercontent.com/34519388/38283724-826b749c-376c-11e8-8f94-3d4421555864.png)

**Comment by acdvorak** [comment]
We might want to create a mixin to customize the icon dimensions.

E.g.:

```scss
@mixin mdc-fab-icon-size($width, $height: $width) {
  ...
}

.mdc-fab__icon {
  @include mdc-fab-icon-size(24px);
}
```

**Comment by williamernest** [comment]
Should the mixin also adjust the `font-size`?
