### ISSUE TITLE
TextField label positioned incorrect in Dialog when making use of SSR

### ISSUE THREAD

**Issue by trentin** [material-components/material-components-web#2511]
Since upgrading from @material/textfield@0.31.0 to @material/textfield@0.34.0 the label is positioned to the right of the input when used in a Dialog on an SSR project

<img width="883" alt="dialog" src="https://user-images.githubusercontent.com/975213/38335275-29c7d5e8-38a1-11e8-8491-26c09199ac35.png">

**Comment by acdvorak** [comment]
Thanks for filing this issue!

Can you reproduce it in a [CodePen](https://codepen.io/traviskaufman/pen/pNQmRp)? Or does it only happen when you use server-side rendering?

What kind of SSR are you using?

**Comment by trentin** [comment]
@acdvorak  Apologies we have tracked down the issues, it seems the dev server was caching the previous version of the css. Once we fixed this issue the problem resolved. 

Thanks for the quick response

**Comment by acdvorak** [comment]
Yay! Glad to hear it was a simple fix :smile:
