### ISSUE TITLE
select: Not floating label using keyboard

### ISSUE THREAD

**Issue by trimox** [material-components/material-components-web#2515]
### What MDC Web Version are you using?

v0.34.1

### What browser(s) is this bug affecting?

Chrome latest

### What are the steps to reproduce the bug?

Open https://material-components-web.appspot.com/select.html
Choose a Select, and attempt to select an item using keyboard.

![select](https://user-images.githubusercontent.com/11887843/38363403-8a8e5e78-38a2-11e8-90df-c3f34e01a670.gif)

**Comment by acdvorak** [comment]
Thanks for filing this issue!

It looks like we might need to float the label on the `focus` event.
