### ISSUE TITLE
MDC Select floating label issue

### ISSUE THREAD

**Issue by jvalst** [material-components/material-components-web#2524]
When using the new 0.34.1 release of the MDC Select, there are some changes in this component. In the documentation, there is a section about the pre-selected values and handling the floating label.

When I'm adding the class 'mdc-select__label--float-above', it won't stay on the label when I'm creating the "new MDCSelect(this.element)" in Javascript. The label title is set, and the selected binding in the HTML select is working correct as well. The only thing, is that I can't get the floating label above the label. Here is my code:

```
<template class="mdc-select">
	<select class="mdc-select__native-control">
	  <option value="" selected.bind="!selected"></option>
	  <option value.bind="item[key]" repeat.for="item of data" selected.bind="item[key] === selected">
		${item[value]}
	  </option>
	</select>
	${selected}
	<div class="mdc-select__label mdc-select__label--float-above">${label}</div>
	<div class="mdc-select__bottom-line"></div>
</template>
```

In the Javascript:

`this.myMdcSelect = new MDCSelect(this.element);`

When clicking on an item in the select, the label goes floating.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

Could you possibly:

1. Create a [CodePen](https://codepen.io/acdvorak/pen/WzLqYZ?editors=1010#0) that demonstrates the problem
2. Attach a screenshot or video of the behavior you're seeing

Is the `new MDCSelect` getting instantiated before or after the `<select>` has been rendered to the DOM?

E.g., what does this print:

```js
console.log('value:', this.element.value);
console.log('selectedIndex:', this.element.selectedIndex);
this.myMdcSelect = new MDCSelect(this.element);
```

**Comment by acdvorak** [comment]
It sounds like `select` is working as intended 🙂 

If you have an empty initial value, we automatically un-float the label during `initialSyncWithDOM()`.

The `mdc-select__label--float-above` class is only used to avoid a [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) during server-side rendering, when you know ahead of time that the dropdown will have a pre-selected value (i.e., one of the `option` elements will have a `selected` attribute).
