### ISSUE TITLE
Backward Compatibility Policy or Guidelines?

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#2528]
Is there a policy or guideline followed regarding backward compatibility? If not, is this something that the MDC -Web project could implement?

I have had to recode my HTML more than twice, e.g. `mdc-simple-menu` and `mdc-text-field__label`. Is there any reason that the library cannot resolve the old classnames to the new classnames? Seems like your JavaScript could throw a console _warning_ for _x_ number of revisions before the entire web application fails.

...just an idea.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

We don't have a policy on backward compatibility yet, but we've discussed it internally and are working on a longer-term strategy for maintenance and support.

We realize breaking changes suck, and we apologize for all the churn. However, MDC Web is still in version 0.x (alpha), which means [things can change and break at any time](https://semver.org/#spec-item-4).

If the frequency of breaking changes is too high, you can lock into a specific version of the library and upgrade whenever you're ready.

Thanks again for the feedback!
