### ISSUE TITLE
How to employ Extract Text plugin (or extract CSS any other way)?

### ISSUE THREAD

**Issue by codeshark1** [material-components/material-components-web#2531]
Hi everyone, I'm trying to figure out how the rules section of webpack.config.js can be changed in order for ExtractText to work. Their suggestion is to use this code:
```
    rules: [
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      }
    ]
```

The rules from your Getting Started guide look like this
```
    rules: [
      {
        test: /\.scss$/,

        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'bundle.css'
            },
          },
          { loader: 'extract-loader' },
          { loader: 'css-loader' },
          { 
            loader: 'sass-loader',
              options: {
                importer: function(url, prev) {
                  if(url.indexOf('@material') === 0) {
                    var filePath = url.split('@material')[1];
                    var nodeModulePath = `./node_modules/@material/${filePath}`;
                    return { file: require('path').resolve(nodeModulePath) };
                  }
                  return { file: url };
                }
              }
          },
        ]
      }
    ]
```

**Comment by acdvorak** [comment]
Hi there!

The Extract Text plugin is only needed if you're trying to output multiple `.css` files from a single Webpack bundle.

If your Webpack bundle outputs a single CSS file (e.g., `bundle.css`), then `file-loader` should be sufficient.

In fact, under the hood, `extract-text-webpack-plugin` is creating a separate child bundle for every CSS file.

From [The new CSS workflow (step 1)](https://medium.com/webpack/the-new-css-workflow-step-1-79583bd107d7):

> The current workflow for separate CSS files involves the extract-text-webpack-plugin, which is a big hack that executes the result of the css-loader and creates a CSS file out of it. To execute it, it builds a child bundle which contains only the current module targeting node.js and evaluate it.

Does that answer your question?

**Comment by codeshark1** [comment]
Excuse me for I probably should have mentioned it right away, but I want to serve the bundle.css file directly, not via JS. Your current proposed setup doesn't create a physical CSS in the project directory, and as far as I'm aware this is OK for development but not so much for production. So I read somewhere that I need Extract Text to do that.
Anyway I tried doing this 
```
          {
            loader: 'file-loader',
            options: {
              name: 'bundle.css',
              outputPath: 'css/',
              useRelativePath: process.env.NODE_ENV === "production"
            }
```
And even though I don't have any errors on "npm start", bundle.css still not being created anywhere in the project directory.

**Comment by acdvorak** [comment]
Ahh, I think I see the issue 🙂 

The `npm start` command runs `webpack-dev-server`, which stores all output files in-memory. It doesn't write anything to disk.

If you want to write the output files to disk, you need to use the `webpack` binary instead of `webpack-dev-server`.

Update your `package.json` to something like this:

```json
{
  "scripts": {
    "build": "webpack --output-path=./out --progress",
    "start": "webpack-dev-server",
    "watch": "webpack --output-path=./out --progress --watch"
  }
}
```

Then run `npm run build` or `npm run watch` in the terminal.

The `build` and `watch` commands will _not_ start a Web server; they only write the output files to disk.

Does that work for you?
