### ISSUE TITLE
Feature request: Card toolbar

### ISSUE THREAD

**Issue by aexvir** [material-components/material-components-web#2532]
Plain toolbars are nice, but when the content of a page is meant to be more minimalistic I often find that wrapping it into a card makes it way better. Card toolbars allow wrapping content in cards in a more integrated way than regular toolbars.

Any plans on implementing this?

![card-toolbar](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bx4BSt6jniD7bW1TYXlMT0JxUWM/layout-structure-toolbars4.png)

**Comment by acdvorak** [comment]
Hi there!

We're not currently planning to implement a card toolbar, but we'll keep your request in mind as we prioritize future work.

Thanks!! 😀
