### ISSUE TITLE
jspm_packages/npm/@material/menu@0.1.2/simple.js

### ISSUE THREAD

**Issue by fernandogmar** [material-components/material-components-web#255]
### What MDC-Web Version are you using?

0.3.0

### What are the steps to reproduce the bug?

I am using jspm version 0.17.0-beta.36, I don't really know if it is a bug related to jspm
I am including MDCSelect:

```

  import {select as mdcSelect} from 'material-components-web';
  const { MDCSelect } = mdcSelect;

```

Just loading the page.... you can see the error on the console:

### What is the actual behavior?
I got this error on the console
http://localhost:8080/jspm_packages/npm/@material/menu@0.1.2/simple.js 404 (Not Found)

### What is the expected behavior?
That it loads dependencies without errors ;)

### Any other information you believe would be useful?
Searching on the code I found this file ` @material/menu@0.1.2/index.js` that does the next export:
```
export {MDCSimpleMenu, MDCSimpleMenuFoundation} from './simple';
```
It looks like that package.json defines main as index.js, and simple is a folder...
I looks like jspm translates it to the wrong path above... instead of: http://localhost:8080/jspm_packages/npm/@material/menu@0.1.2/simple/index.js

**Comment by traviskaufman** [comment]
Hey @fernandogmar 

This looks more like a JSPM configuration issue rather than an MDC-Web-specific one. It looks like JSPM isn't resolving package paths in the correct way, so I'd probably check your configuration or follow up with JSPM team regarding the issue. You could also try asking this on StackOverflow and see if that could help!

**Comment by fernandogmar** [comment]
I have already reported it on jspm repository:
https://github.com/jspm/jspm-cli/issues/2238

meanwhile it would be helpful any clue/woraround I can use ;)

Thanks!

**Comment by maverix** [comment]
changing the components to use explicit references
i.e.  from './simple' to './simple/index'
would mean popular loaders like jspm/system.js will just work.

Would you be interested in a PR for this?
