### ISSUE TITLE
Is MCW being used in production by Google?

### ISSUE THREAD

**Issue by carlosagsmendes** [material-components/material-components-web#2555]
Are there any public sites where we can see it working?

Thanks in advance

**Comment by acdvorak** [comment]
Hi there!

The official [Material Components](https://material.io/components) website uses it (see the footer at the bottom of the page, which reads: "[Made with Material Components for the web](https://material.io/components/web)")

Within Google, an increasing number of products and teams are incorporating our components 🙂 

Please don't hesitate to [file a GitHub issue](https://github.com/material-components/material-components-web/issues/new) if you run into any problems with the library. Thanks!
