### ISSUE TITLE
select Need to diversify

### ISSUE THREAD

**Issue by Zhongxiangyun** [material-components/material-components-web#2566]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Feature Requests
1.下拉框是一种常用的组件，但是提供的样式不怎么友好，能否美化一下
2.下拉框能否加入模糊搜索的功能，eg：当用户需要在几百条数据中下拉选择时，是否可以支持模糊搜索呢？
end，thank you！

**Comment by patrickrodee** [comment]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

Feature Requests
1. The drop-down box is a common component, but the provided style is not very friendly and can beautify
2. Whether the drop-down box can add the function of fuzzy search, eg: When the user needs to select from several hundred data, can it support fuzzy search?
End,thank you!

**Comment by acdvorak** [comment]
### English

Thanks for filing this issue!

1. See #2552 😄 
2. We probably won't add "fuzzy search". Everyone has a different idea of what "fuzzy" means, which makes it difficult to create a single API that gives clients the flexibility they need while still being simple and easy to use.

Thanks again!

### Chinese

感谢您提交此问题！

1. 见 #2552 😄
2. 我们可能不会添加“模糊搜索”。 每个人都对“模糊”意味着什么有不同的看法，这使得创建单一的API很难，它为客户提供了所需的灵活性，同时仍然简单易用。

再次感谢！
