### ISSUE TITLE
Floating label and placeholder overlap each other

### ISSUE THREAD

**Issue by habelMarottipuzha** [material-components/material-components-web#2588]
If we add form-field of type date, we will get the floating label overlapped with placeholder.
code like
<input type='date' className="mdc-textfield__input" {...restProps} />

Full fiddle http://jsfiddle.net/jyc5jgg2/

![material-bug](https://user-images.githubusercontent.com/14868947/38927102-580c540c-4322-11e8-97f3-fc37685f7406.png)

**Comment by williamernest** [comment]
@habelMarottipuzha The jsfiddle you linked is using version 0.19.0 of the MDC library. Can you update the version and reproduce? We're currently on version v0.34.1, and I believe this issue has been resolved already.

**Comment by habelMarottipuzha** [comment]
Sorry that I didn't check the version in jsfiddle. But Its still there with v0.34.1. I noted this in preact-material-components which uses v0.33.0. Then I add resolution for mdc with v0.34.1 and I got the same issue. 
This is the code I tried in [material-components-web demo](https://github.com/material-components/material-components-web/blob/master/demos/text-field.html).(Screen shot provided earlier)
>        <div class="mdc-text-field">
>           <input class="mdc-text-field__input" type="date" id="input">
>           <label for="input" class="mdc-floating-label">Input Label</label>
>           <div class="mdc-line-ripple"></div>
>         </div>

Is there something I miss?

**Comment by acdvorak** [comment]
Unfortunately we can only support `type="text"` and `type="password"` for now.

We'll consider adding more input types in the future.

Thanks!

**Comment by olfek** [comment]
Please re-open this, moving back to `MDL` for now then.

**Comment by kfranqueiro** [comment]
Have you tried this and found it to not work? I'm pretty sure it has since been improved to work with several other input types including number and date...

**Comment by olfek** [comment]
Yes I have tried it, at the time of writing my previous comment, using the latest version.

Visually, its fine, and is what I expect, but behaviourally, as pointed out in this issue, it is not. The entered input overlaps the label, and the label does not animate out of the way as it does for the password field for example.

**Comment by abhiomkar** [comment]
I'm not able to reproduce this issue with `email` type on latest version (`v1.0.0`). Please see this updated example on [jsfiddle](http://jsfiddle.net/wdpaurq9/8/).

**Comment by olfek** [comment]
[See this jsfiddle](http://jsfiddle.net/zf28tapc/4/)

**Comment by abhiomkar** [comment]
@olfek You'll need to instantiate the component before using it.

```
for (const el of document.querySelectorAll('.mdc-text-field')) {
  new mdc.textField.MDCTextField.attachTo(el);
}
```

See updated [jsfiddle](http://jsfiddle.net/word7t2n/1/).

**Comment by olfek** [comment]
@abhiomkar Ah okay, thanks, this was missing from the docs, it only mentions a similar thing for ripples.
