### ISSUE TITLE
Dialog affecting action bar when opened

### ISSUE THREAD

**Issue by Honest-Objections** [material-components/material-components-web#2592]
After changing from the distribution CSS to ```@import material-components-web/material-components-web``` in SASS, when I open the dialog component, the action bar shrinks in size, returning to normal after closing the dialog and focusing on an element within. 

This didn't happen before and I've hacked around it by removing ```flex``` from the action-bar parent, but I don't like using absolutes. 

Any ideas what may cause this?

*What MDC Web Version are you using?* 
0.34.1

*What browser(s) is this bug affecting?*
Google Chrome

*Please include the browser version.*
65.0.3325.181 (Official Build) (64-bit)

*What OS are you using?*
OSX

### What are the steps to reproduce the bug?

Layout:

```
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Styles -->
    <link href="{{ asset('css/material.css') }}" rel="stylesheet">
</head>
<body>

  <div class="app-container">

    <!-- Navigation Draw -->
    <aside class="navigation-draw mdc-drawer mdc-drawer--persistent mdc-drawer--open">
        <nav class="mdc-drawer__drawer">
          <div class="mdc-drawer__toolbar-spacer">
            <p class="mdc-typography--subheading1">{{ Auth::user()->email }}</p>
          </div>
          <div class="mdc-list-group">
            <nav class="mdc-list">
            <!-- Navigation Items -->
            </nav>
          </div>
        </nav>
      </aside>

    <!-- Main Content -->
    <div id="app">

      <!-- Toolbar -->
      <header id="topAppBar" class="mdc-top-app-bar">
        <div class="mdc-top-app-bar__row">
          <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <a href="#" class="material-icons mdc-top-app-bar__navigation-icon">menu</a>
            <span class="mdc-top-app-bar__title">@yield('title')</span>
          </section>
        </div>
      </header>

      <!-- Content -->
      @yield('content')

    </div>

  </div>

  <!-- Dialog -->
  <div class="dialog">@yield('dialog')</div>

  <!-- Scripts -->
  <script src="{{ asset('js/app.js') }}"></script>
  <script src="{{ asset('js/material.js') }}"></script>
  <script src="{{ asset('modules/material-design/material-components-web.js') }}"></script>
</body>
</html>
```
Sass:
```
.app-container {
  display: flex;

  height: 100%;
  width: 100%;

  .navigation-draw {
    position: relative;

    .navigation-draw-bottom {
      position: absolute;
      width: 100%;
      bottom: 0;
    }
  }

#app { 
    display: inline-flex; 
    flex-grow: 1; 
    flex-direction: column; 
    height: 100%;

    .container {
      margin: 16px;
      position: relative;
      flex: 1;
    }
  }
}
```

### What is the expected behavior?
The action bar remains the same size

### What is the actual behavior?
Action bar shrinks each time the dialog is opened, returning to normal once focusing on element within ```#app```

**Comment by williamernest** [comment]
@Honest-Objections Thanks for filing this issue. Can you elaborate on what is exactly shrinking? I've tried to duplicate this using our native components and am having trouble showing this behavior. 

Here's a codepen I started, feel free to fork it if needed. 
https://codepen.io/williamernest/pen/jxOjgv

**Comment by Honest-Objections** [comment]
Thanks for setting the pen up, I've tried to create it there and then again locally, but the behaviour no longer happens, must have just been a weird quirk. 

Appreciate the help
