### ISSUE TITLE
MDC Drawer width

### ISSUE THREAD

**Issue by danfascia** [material-components/material-components-web#2603]
Why is an MDC drawer a fixed 240px width regardless of device?

It seems crazy that it's so small on an XL desktop screen and it puts me off using the component in favour of my own push drawer.

If I override the fixed px width with a percentage in the SCSS does that work for all of the animation calculations?

**Comment by bonniezhou** [comment]
Thanks for bringing this up! Our designers agree that the size of MDC Drawer should be customizable. 

Simply overriding the width in the root element won't cut it because width is calculated and handled in many places. We'll need to add a Sass mixin that handles this. Added to tracker.

**Comment by danfascia** [comment]
Yes, I brought this up after trying to override the width and finding that it was very difficult because as you mention it is hard coded in several places.

A SASS variable / mixin would be ideal and would allow me to use percentage based widths for larger screens. The mixin should ideally allow use in media queries for this purpose.
