### ISSUE TITLE
request(MDCPersistentDrawer): Option to disable escape keydown handler

### ISSUE THREAD

**Issue by ricardobrandao** [material-components/material-components-web#2608]
## Feature Requests

Add option to disable (or override) the escape keydown handler. As of now, a document keydown handler is being added in the [MDCSlidableDrawerFoundation](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/slidable/foundation.js#L61) that closes the drawer when the escape key is pressed.

Currently, if a persistent drawer and a dialog are open, when the user tries to close the dialog by pressing the escape key, both the dialog and the drawer will be closed. 

### What MDC Web Version are you using?

> 0.34.1

### What is the expected behavior?

> Clicking the escape key should not close the drawer.

### What is the actual behavior?

> Clicking the escape key (anywhere) closes the drawer.

### Any other information you believe would be useful?

You can check the demo in this [codepen](https://codepen.io/ricardobrandao/full/MGwOmE/). In order to reproduce follow the following steps: 

1. open the drawer
2. open the dialog
3. press the escape key

**Comment by bonniezhou** [comment]
Thanks for filing this bug!

Pressing the escape key in this case should only close the dialog, not the drawer. The handler should be moved from the shared `MDCSlidableDrawerFoundation` to `MDCPersistentDrawerFoundation`. Added the bug to our tracker.

**Comment by ricardobrandao** [comment]
That's really helpful! Thank you 😃

**Comment by MHM5000** [comment]
Any updates?

**Comment by abhiomkar** [comment]
This is fixed in latest version, drawer will be closed only when it receives key event from Drawer's child element.
