### ISSUE TITLE
person_pin in demo is different from the download - download is more rectangular

### ISSUE THREAD

**Issue by huug** [material-components/material-components-web#2609]
## Bugs

Person icon on [demo page](https://material.io/icons/) is different from the download

Demo page:
<img width="912" alt="screenshot 2018-04-20 20 57 34" src="https://user-images.githubusercontent.com/220135/39068714-859e7d5c-44dd-11e8-8206-cba72849e905.png">

Downloaded icon:
![ic_person_pin_black_48dp_2x](https://user-images.githubusercontent.com/220135/39068669-5a3eaf2e-44dd-11e8-8706-3bfbdc97e21b.png)

**Comment by bonniezhou** [comment]
Thanks for letting us know!
We've alerted the Icons team of this.

**Comment by bonniezhou** [comment]
Looks like it's fixed!
