### ISSUE TITLE
Invalid operand to 'in': Object expected

### ISSUE THREAD

**Issue by toinkiie** [material-components/material-components-web#2626]
### What MDC Web Version are you using?

https://unpkg.com/material-components-web@latest/dist/material-components-web.js or 

"@material/tabs": "^0.34.1",

### What browser(s) is this bug affecting?

IE10

### What OS are you using?

WINDOWS 10

### What are the steps to reproduce the bug?

Steps:
1. use https://unpkg.com/material-components-web@latest/dist/material-components-web.js
2. open in localhost.
3. check IE 10 console.
4. Invalid operand to 'in': Object expected is shown then tab scroller is not working.

### What is the expected behavior?
It should load scroller tab.

### What is the actual behavior?

it is not instantiated due to error Invalid operand to 'in': Object expected in 
MDCRipple @ initialSyncWithDOM {
 this.unbounded = 'mdcRippleIsUnbounded' in this.root_.dataset;
}

**Comment by robcaldecott** [comment]
I think IE11 is supported but not versions earlier than this.

**Comment by bonniezhou** [comment]
@robcaldecott is correct, MDC Web supports only the latest version of IE which is IE11. Sorry!

(The issue is that IE10 elements don't have the `dataset` property.)

**Comment by toinkiie** [comment]
@robcaldecott @bonniezhou thanks for pointing out the datase support, this fallback code solves the problem https://gist.github.com/brettz9/4093766#file_html5_dataset.js
