### ISSUE TITLE
Link from demo back to documentation

### ISSUE THREAD

**Issue by MrChriZ** [material-components/material-components-web#2627]
Could links be added from the demo areas back to the documentation for the associated content?
For example from
https://material-components-web.appspot.com/text-field.html

to

https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield

There's a back button but it simply takes you to the full demo area.

**Comment by bonniezhou** [comment]
Yes! We're in the process of revamping our demo catalog and it will include links back to the documentation. Once it's ready all of our READMEs will link to the updated catalog. Stay tuned!
