### ISSUE TITLE
An error may occor when compiling scss with ruby

### ISSUE THREAD

**Issue by YuoMamoru** [material-components/material-components-web#2636]
### What MDC Web Version are you using?

v0.35.0
It does not occur in v0.34.1.

### What browser(s) is this bug affecting?

It occors when compiling scss

### What OS are you using?

Linux (Ubuntu)

### What are the steps to reproduce the bug?

It occurs when running rails in a test environment.

### Any other information you believe would be useful?

The error occors on line 136 of `select/mdc-select.scss`.
`mdc-select-dd-arrow-svg-bg_` mixin take two arguments: `fill-hex-number` and `opacity`.
But a color including alpha channel is given to this mixin as first argument.

**Comment by williamernest** [comment]
@YuoMamoru Thanks for filing this issue. We can't reproduce this using Ruby sass v3.5.5. Can you tell us what version of ruby sass you're using? We'd like to ensure our hotfix is addressing the issue before we merge and release.
