### ISSUE TITLE
mdc-grid-list sass error

### ISSUE THREAD

**Issue by codedbypaul** [material-components/material-components-web#2644]
### What MDC Web Version are you using?

0.35.0

### What browser(s) is this bug affecting?

N/A

### What OS are you using?

N/A

### What are the steps to reproduce the bug?

Compile the Sass file for mdc-grid-list

### What is the expected behavior?

File compiles with no errors.

### What is the actual behavior?

Fails to compile with error message:
```
Error: node_modules/@material/theme/_mixins.scss
Error: Invalid style: 'text-primary-on-primary'. Choose one of: primary, secondary, background, surface, on-primary, on-secondary, on-surface, text-primary-on-background, text-secondary-on-background, text-hint-on-background, text-disabled-on-background, text-icon-on-background, text-primary-on-light, text-secondary-on-light, text-hint-on-light, text-disabled-on-light, text-icon-on-light, text-primary-on-dark, text-secondary-on-dark, text-hint-on-dark, text-disabled-on-dark, text-icon-on-dark
on line 93 of node_modules/@material/theme/_mixins.scss
>> @error "Invalid style: '#{$style}#. Choose one of: #{map-keys($mdc-theme
```

### Any other information you believe would be useful?

Appears to be caused by line 120 of mdc-grid-list.scss

**Comment by williamernest** [comment]
@codedbypaul In `v0.35.0` we removed the `text-primary-on-primary` color and replaced it with `on-primary`. It appears your project may be using the `v0.35.0` theme with an older version of the `grid-list`, which would cause this error. Clearing your `node_modules` folder and reinstalling may help.
