### ISSUE TITLE
scss import failing for top app bar

### ISSUE THREAD

**Issue by cluelessjoe** [material-components/material-components-web#2655]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What MDC Web Version are you using?

```"@material/button": "^0.34.1",```
```"@material/drawer": "^0.35.0",```
```"@material/ripple": "^0.34.1",```
```"@material/top-app-bar": "^0.35.0",```

### What browser(s) is this bug affecting?

npm start issue

### What OS are you using?

ubuntu 16.04

### What are the steps to reproduce the bug?

[I followed the getting started page](https://material.io/components/web/docs/getting-started/) and all was fine until I tried to add the scss for [MDC Top App Bar](https://material.io/components/web/catalog/top-app-bar/) by adding this line in app.scss: 
```@import "@material/top-app-bar/mdc-top-app-bar";```
then do ```npm start``` 
The whole code is accessible on [github](https://github.com/cluelessjoe/mdcWebPlayground).

### What is the expected behavior?

I should get the scss in.

### What is the actual behavior?

```npm start``` fails with:
>    ERROR in ./app.scss
>     Module build failed: 
>           @error "Invalid style: '#{$style}'. Choose one of: #{map-keys($mdc-theme-property-values)}";
>          ^
>           Invalid style: 'on-primary'. Choose one of: primary, secondary, background, text-primary-on-primary, text-secondary-on-primary, text-hint-on-primary, text-disabled-on-primary, text-icon-on-primary, text-primary-on-secondary, text-secondary-on-secondary, text-hint-on-secondary, text-disabled-on-secondary, text-icon-on-secondary, text-primary-on-background, text-secondary-on-background, text-hint-on-background, text-disabled-on-background, text-icon-on-background, text-primary-on-light, text-secondary-on-light, text-hint-on-light, text-disabled-on-light, text-icon-on-light, text-primary-on-dark, text-secondary-on-dark, text-hint-on-dark, text-disabled-on-dark, text-icon-on-dark
>           in /home/jpa/Sandbox/mdcWebPlayground/node_modules/@material/theme/_mixins.scss (line 33, column 7)
>      @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.scss
>

**Comment by williamernest** [comment]
@cluelessjoe We've been seeing some problems when two dependencies use different versions of a common package. `top-app-bar@0.35.0` depends on `theme@0.35.0` but `button@0.34.1` depends on `theme@0.34.1` which is the `theme that you're using (based on the error message). 

Can you update your `button` and `ripple` packages to use `0.35.0` and see if that fixes your issue?

**Comment by cluelessjoe** [comment]
Hi @williamernest 

You're right, this fixes the issue, thanks a lot :) 

Sorry for the delay in answering: I tried to find a way in npm to use a variable for version numbers, to avoid copy/pasting the common version, but I didn't find anything. Did I miss something?

Thanks again!
