### ISSUE TITLE
Request for "mdc-icon-button"

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2673]
Can we pull the "navigation icon" and "action item" out of mdc-top-app-bar and into it's own "mdc-icon-button" component?

Having a button which triggers an unbounded ripple is useful on it's own.

**Comment by williamernest** [comment]
Should this be it's own package? It sounds like it should just be added as a variant to the current `mdc-button`

**Comment by kfranqueiro** [comment]
It wouldn't really have any styles in common with button, though, I suppose?

I am worried about naming this clearly to avoid confusion with an actual icon-only MDC Button if that also becomes a thing, though.

I am wondering whether this warrants being its own component or if it's overkill, if all it's ostensibly doing is applying ink color + states and adding a set padding.

**Comment by williamernest** [comment]
The entire package is ~40 lines of scss. It seems like it's just a variant of `button` with an unbounded ripple. 

https://gist.github.com/williamernest/d852281e711f4f10bd2ef255cc518885

**Comment by bonniezhou** [comment]
Looks like it'll stand as variant of `button`, i.e. `mdc-button--icon`.
(We've also decided that `mdc-button--icon__icon` is not awkward at all.)

Added to tracker.

**Comment by williamernest** [comment]
We're condensing this and `icon-toggle` into their own `mdc-icon-button` package. The icon button had ripple conflicts with button.
