### ISSUE TITLE
Explain better how to use specific components...

### ISSUE THREAD

**Issue by sixro** [material-components/material-components-web#2679]
Hi, not an issue per se, but a feedback.
I used getmdl.io in the past and I was really impressed by the productivity I had... in just one evening I was able to create a draft website.
With this version I started to have some issues.
The last issue is with card (but it is just an example).
I was trying to add a card checking the demo. At the beginning, it seems simple as getmdl.io
Unfortunately the cards were not appearing like the demo and investigating the demo I found so many css customization with those "demo_" styles that it was basically impossible to understand what it is doing only on that specific card component.

My 2 cents.

**Comment by bonniezhou** [comment]
Hi, thanks for the feedback!

We're currently working on building a new demos catalog that will be a lot simpler than the current one. Specifically for the Card component, we'll include an example of the very baseline Card that you get out-of-the-box with no customization.
In the future we also plan on adding code snippets to our new catalog right next to each demo, which is something that the current catalog doesn't include at all.

Our READMEs and documentation will link to our new catalog once it's ready. Stay tuned!

**Comment by sixro** [comment]
Thanks @bonniezhou, I really appreciate your answer
Cheers
