### ISSUE TITLE
Card: Icon ripples are initialized with wrong size if material-icons font loads after scripts

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#2702]
### What MDC Web Version are you using?

v0.35.x

### What browser(s) is this bug affecting?

All, but easiest to repro with Chrome with dev tools open and cache disabled

### What OS are you using?

Any

### What are the steps to reproduce the bug?

Reproducible on https://material-components.github.io/material-components-web-catalog/#/component/card as of catalog repo commit de6efb64f80464ba332fcae4fc5af9e202d1df36, but I intend to implement a workaround, so you'd need to clone the repo and rewind to that commit and run `npm start` locally to reproduce.

I suspect it's not reproducible on the main repo's card demo page because of our logic that waits before instantiating components.

### What is the expected behavior?

All ripples for card action icons are the correct size.

![image](https://user-images.githubusercontent.com/398379/39633197-4adf9b76-4f85-11e8-8ad4-1ed2d98f7765.png)

### What is the actual behavior?

Ripples are incorrectly sized, presumably based on the size of the text in each element prior to the Material Icons font loading.

![image](https://user-images.githubusercontent.com/398379/39633069-eb5cbf80-4f84-11e8-8774-eed00cb8a658.png)

### Any other information you believe would be useful?

Icon Toggle and Top App Bar set their elements' size in CSS, which prevents this issue. Maybe we should do the same for Card action icons?

I'm also wondering if a similar issue exists

**Comment by bonniezhou** [comment]
This should be fixed along with #2673 and update Cards to use `mdc-button--icon`, since that will set the element's width/height will in CSS.
Adding to tracker to update Cards once #2673 is resolved.

**Comment by williamernest** [comment]
Resolved with #2748
