### ISSUE TITLE
input 框回显时，出现重影

### ISSUE THREAD

**Issue by Zhongxiangyun** [material-components/material-components-web#2708]
虽然我很想截图来展示这个问题，但是这里不支持图片上传，So只能用文字描述了。
当input框在回显时，input里面的值和span的值重合了，这样的用户体验非常不好，希望能修复这个问题，再次感谢！（是pc版出现的这个问题，Material2.0）

代码如下：
`<label _ngcontent-c3="" class="mdc-textfield mdc-textfield--upgraded">
                <input _ngcontent-c3="" class="mdc-textfield__input ng-untouched ng-pristine ng-valid" type="text">
                <span _ngcontent-c3="" class="mdc-textfield__label">电话号码</span>
            </label>`

**Comment by williamernest** [comment]
Google translate: 
Although I'm eager to take a screenshot to show this problem, there is no support for uploading pictures. So can only be described in text.
When the input box is echoed, the values ​​in the input and the values ​​in the span are coincident. This kind of user experience is very bad. I hope to fix this problem. Thanks again! (This is a problem with the pc version, Material 2.0)

code show as below:

**Comment by williamernest** [comment]
@Zhongxiangyun You can upload a screenshot by pasting them from the clipboard or using the "Attach files ..." link at the bottom of the comment field. 

What version of mdc are you using? Can you provide a codepen using the [template](https://codepen.io/williamernest/pen/deyxyp) ?

**Comment by Zhongxiangyun** [comment]
首先很感谢翻译先生帮忙翻译了。
下面是一个图片展示的链接地址：[效果图](https://www.jianshu.com/p/275f91b71204)

**Comment by williamernest** [comment]
First of all, I am very grateful to Translator for helping translate.
Here is a picture showing the link address: renderings

@Zhongxiangyun It looks like the text field hasn't been initialized in the first picture. To have the label float before initializing the component, you can add the `mdc-textfield__label--float-above` class to the `mdc-textfield__label` element. 
```
<div _ngcontent-c3="" class="mdc-textfield mdc-textfield--upgraded"> 
  <input _ngcontent-c3="" class="mdc-textfield__input ng-untouched ng-pristine ng-valid" type="text"> 
  <label _ngcontent-c3="" class="mdc-textfield__label mdc-textfield__label--float-above">电话号码</label> 
</div>
```
