### ISSUE TITLE
Material design Treeview component

### ISSUE THREAD

**Issue by jay8t6** [material-components/material-components-web#2709]
I think a treeview component with selection like the one below would be a really useful element.

http://gijgo.com/tree/demos/material-design-treeview-checkbox

**Comment by bonniezhou** [comment]
Hi @jay8t6, unfortunately this component isn't in the works and there's no plan for it on the roadmap.
We can confirm this decision with our designers and let you know the reason behind it.

**Comment by jay8t6** [comment]
@marioavs They look great from the first look. I will look at it more later. Nice work! @bonniezhou you may wanna check it out as well. These could be harvested into the material component library,
