### ISSUE TITLE
Retroactively tag releases with semver compliant tag

### ISSUE THREAD

**Issue by BBosman** [material-components/material-components-web#271]
As mentioned in #209, there were some issues with the repository not having semver compliant tags, which resulted in incorrect changelog creation. With the 0.4.0 release this was fixed by adding a `v0.4.0` tag.

Would it be possible to retroactively do the same with previous versions?

```bash
git tag v0.2.0 -m "Material Components for the web release v0.2.0" 18565a2755d4f3e4700bece5d4349f9f1f852cf6
git tag v0.3.0 -m "Material Components for the web release v0.3.0" 41d66f5bcb637adceabb3b49bdf340f4c9df988b
git push --tags
```

**Comment by traviskaufman** [comment]
Done!
