### ISSUE TITLE
Usage from CDN

### ISSUE THREAD

**Issue by Marcellllll** [material-components/material-components-web#2710]
Hi,

It would be great if you could add a bit more documentation about how to use material-components-web downloaded via CDN, especially individual components. I have just started to use it, and managed to get the packages via unpkg.com, but afterwards there are still many questions on how to actually use the components.

Is there an example on how to use individual components after downloading just the .min.css and .min.js somewhere, like for example for MdcTextField ? 
(right now I am stuck on how to do the window.mdc.autoInit() without needing to download the entire 300Kb JS package)

**Comment by williamernest** [comment]
@Marcellllll Here's a [codepen](https://codepen.io/williamernest/pen/vjevqN?editors=1010) using just those two packages. I'm not sure why there's a `default` parameter, and I'll follow up with the team during Issue Triage to ensure we log the issue. 

When using `autoInit` as a standalone package, you have to provide a mapping of which objects are mapped to which constructors using the `register` function. 
https://github.com/material-components/material-components-web/tree/master/packages/mdc-auto-init#registering-components

**Comment by Marcellllll** [comment]
Hi William,

Thanks a lot !!! This helps me forward quite a bit. It would be great if you would also have an example of how to use the theming and the colors when using vanilla JavaScript and a CDN.

And is there a way to attach a ripple to all buttons ? (when I attach it to a class only the first item of this class gets the ripple)

**Comment by williamernest** [comment]
@Marcellllll We plan on building out better documentation on how to use everything from a CDN. The best and easiest way to update the colors is by using sass mixins.

Here's a [codepen](https://codepen.io/williamernest/pen/MGGQZo?editors=1010) showing how to initialize the ripple on buttons using autoInit. If you're using js, you can query for the mdc-button class and iterate through the elements instantiating a ripple on each. 
```
document.querySelectorAll('.mdc-button').forEach((element) => { 
   new mdc.ripple.MDCRipple(element);
});
```

**Comment by devxpy** [comment]
I personally liked the Automatic Instantiation in [docs](https://material.io/develop/web/docs/importing-js/).

Syntax : 
`mdc.foo.MDCFoo.attachTo(document.querySelector('.mdc-foo'));` 

Examples: 
```
mdc.textField.MDCTextField.attachTo(document.querySelector('.mdc-text-field'));
mdc.ripple.MDCRipple.attachTo(document.querySelector('.mdc-button'));
```

You can even see all the elements that need JS Instantiation using 
`console.log(mdc);`

**Comment by andrewmiller1** [comment]
Thank you so much. I just spent several hours trying to get ripple to work. All I needed was to see that example

**Comment by rehanium** [comment]
How can I resize material buttons? I can only increase the width of button using css but height property is not working on button.

**Comment by asyncLiz** [comment]
Closing this issue since it's a bit old and our [Getting Started](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) guide shows how to load from CDN.

@rehanium you need to use the Sass [height mixin](https://github.com/material-components/material-components-web/blob/master/packages/mdc-button/_mixins.scss#L326) to adjust the button's height. If you're trying to achieve density make the button smaller, use the [density](https://github.com/material-components/material-components-web/blob/master/packages/mdc-button/_mixins.scss#L286) mixin.
