### ISSUE TITLE
MDCTextFieldFoundation.handleValidationAttributeMutation_ should be public

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#2716]
### What MDC Web Version are you using?

> 0.35.1

### What browser(s) is this bug affecting?

> all browsers

### What OS are you using?

> Mac OSx 10.13.3

### What are the steps to reproduce the bug?

`TextField.foundation.handleValidationAttributeMutation_` needs to be public. All other event handlers are public, which makes it easy to use from a framework like React.

**Comment by lynnjepsen** [comment]
All handleXEvent methods on foundations should be public. This makes it possible for other frameworks to wrap our components.
