### ISSUE TITLE
Top App Bar doesn't initialize without a navigation icon

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#2721]
If you don't have a navigation icon, the top app bar fails to instantiate. The permanent drawer example is a good use case for having a top app bar without a menu/navigation icon.

**Comment by Download** [comment]
The [Drawer examples](https://material-components-web.appspot.com/drawer/index.html) contain a top app bar without an action item, but on closer examination it turns out this is the old mdc-toolbar component.
