### ISSUE TITLE
material.io icons no numeric character references.

### ISSUE THREAD

**Issue by john-fenton** [material-components/material-components-web#2730]
material.io icon sheet no longer shows numeric character references for icons - only displays ligatures in the "IE9 and below" section.

https://material.io/tools/icons/?icon=check_box&style=baseline

```
<!--For modern browsers-->

<i class="material-icons">
check_box
</i>

<!-- For IE9 or below. -->

<i class="material-icons">
check_box
</i>
```

Please fix and also supply an interim reference sheet.

**Comment by bonniezhou** [comment]
Thanks for filing this bug! We've pointed it out to the Icons team and they're working on updating it.

**Comment by john-fenton** [comment]
@bonniezhou Is there a method for calculating numeric character references from ligatures for MD? I have a project due next week and need these fixed for IE9 support.

**Comment by GibbySteier** [comment]
@john-fenton 
In the mean time, I was able to view the numeric references by installing the font onto my machine and using software to view it.

IOS machines have Font Book as a default app to view fonts.
Window machines have Character Map installed as a font viewer too.

Hope that helps.

**Comment by john-fenton** [comment]
There is also a resource here which maps most of the values as well (some are missing, but most are there). 
https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

**Comment by seanwuapps** [comment]
+1

**Comment by kfranqueiro** [comment]
FYI, I received word from the icons team that they're looking to resolve this within the next few weeks.

Sorry for the delay, and thanks to those who posted alternatives.

**Comment by astalegale** [comment]
is there a problem resolution date?

**Comment by kfranqueiro** [comment]
Apologies for the prolonged delay; this is still on the icons team's own issue tracker, but there is no definite target resolution date due to resource limitations.

At this point, I'm going to close this issue since it doesn't fall under the purview of MDC Web, and also since MDC Web only targets IE 11. For the time being, if you need support for older versions of IE, please use one of the workarounds mentioned earlier in this thread.
