### ISSUE TITLE
Changelog generation misses commits

### ISSUE THREAD

**Issue by gjdev** [material-components/material-components-web#2732]
The changelog of this project does not include the following commits, even though they made it into a release:

* 9a9a8905dd07e8ef6559c3e67637993ab4ce2d5c
* 9938d31abc8edd97f88f3b4f11b2de12521e9579

This is probably because they use "refactor" is label, which is not recognized?

Anyway, these commits should be in the changelog for the 0.35 release. (By the way: They also contain breaking changes which are not labeled as such in the commit message)

**Comment by williamernest** [comment]
@gjdev Thanks for filing this issue. We've added it to the changelog.
