### ISSUE TITLE
Switch halo stay on until I clic again

### ISSUE THREAD

**Issue by jecisc** [material-components/material-components-web#275]
### What MDC-Web Version are you using?

Branch master, commit 1097e6fcf9d68bd2527dd22654dd62419b00049a

### What browser(s) is this bug affecting?

At least Firefox 51.0.1 64bits

### What OS are you using?

Windows 7 Professional N

### What are the steps to reproduce the bug?

I tried the demo here: https://material-components-web.appspot.com/switch.html

When I click on a switch an halo appears but vanish only on the next click.

See: http://puu.sh/tSYcj/46454c757a.png

**Comment by roshangautam** [comment]
Radial reaction is only required in mobile devices. Check this out:

https://material.io/guidelines/components/selection-controls.html#selection-controls-switch

all the way in the bottom.

![screen shot 2017-02-09 at 9 06 47 am](https://cloud.githubusercontent.com/assets/978347/22788970/35535580-eea7-11e6-8049-6e4bfb5e9baf.png)

**Comment by amsheehan** [comment]
@roshangautam Though the spec does indeed specify that behavior, MDC Switch at this time is CSS only. The current behavior was discussed with design and signed off on. 

That said, since the behavior was brought up we will circle the wagons and discuss possible changes to docs, spec, or the component itself.

**Comment by amsheehan** [comment]
@jecisc The behavior described is actually spec compliant.

When the switch is focused, there will be a focus ring around it. When the focus is lost, the ring disappears.

**Comment by amsheehan** [comment]
Closing since this is technically in-spec

**Comment by Garbee** [comment]
Beyond being specified this is also a major accessibility issue on desktops. So without having a way to detect mobile-specific access it would be a hindrance to users to not have the focus ring for focus state.

The spec is saying "mouse access" however, we still need to think about keyboard navigators and their needs. This is an area where a11y comes before the hardline spec statements.
