### ISSUE TITLE
TopAppBar elements overflow when Drawer is open

### ISSUE THREAD

**Issue by mlicciardi** [material-components/material-components-web#2750]
## Bugs

TopAppBar (fixed) right elements overflow when Drawer (permanent and persist) is open

### What MDC Web Version are you using?

I suppose it's v0.35.1 since I tested the bug on [Material Components Web Catalog](https://material-components.github.io/material-components-web-catalog)

### What browser(s) is this bug affecting?

Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Firefox 59.0.2 (64-bit)

### What OS are you using?

macOS High Sierra Varsion 10.13.4 (17E202)

### What are the steps to reproduce the bug?

1. Go to mdc-drawer [Permanent Demo](https://material-components.github.io/material-components-web-catalog/#/component/drawer/permanent) or 
[Persistent Demo](https://material-components.github.io/material-components-web-catalog/#/component/drawer/persistent)
2. Inspect the `mdc-top-app-bar__row` DOM element
3. Add a `--align-end` section after `--align-start` section with something inside (I used an icon and gave to the section a gradient background to highlight the issue, code attached below)
4. Try to trigger the drawer collapse/expand. As you can see the `mdc-top-app-bar__row` overflow and you lose the `align-end` sections'content

DOM element I attached after `--align-start` section
`<section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" style="
    background: #000000;
    background: -moz-linear-gradient(left,  #000000 0%, #000000 50%, #ff0000 100%);
    background: -webkit-linear-gradient(left,  #000000 0%,#000000 50%,#ff0000 100%);
    background: linear-gradient(to right,  #000000 0%,#000000 50%,#ff0000 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#000000', endColorstr='#ff0000',GradientType=1 );
"><button class="material-icons mdc-top-app-bar__navigation-icon mdc-ripple-upgraded--unbounded mdc-ripple-upgraded" style="--mdc-ripple-fg-size:28.8px; --mdc-ripple-fg-scale:1.66667; --mdc-ripple-left:10px; --mdc-ripple-top:10px;">accessible_forward</button></section>`

### What is the expected behavior?

I expect that the after `--align-end` section's content doesn't get lost

### What is the actual behavior?

`--align-end` section's content get lost due the overflow

### Any other information you believe would be useful?

mdc-drawer (collapsed)
![mdc-drawer collapsed](https://user-images.githubusercontent.com/3432448/40184749-e7e01672-59e8-11e8-997e-46e9ce6b40a0.png)

mdc-drawer--open
![mdc-drawer--open](https://user-images.githubusercontent.com/3432448/40184756-eaa1fa38-59e8-11e8-8cb7-cdf4e7fb81a1.png)

Gif
![may-17-2018 15-11-31](https://user-images.githubusercontent.com/3432448/40184767-f2030a06-59e8-11e8-9ab9-9dd9ffcdc1b8.gif)

**Comment by bonniezhou** [comment]
Hi, thanks for the feedback!

We're looking at making the drawer/top app bar integration more seamless. We'll get back to you once we confirm the behaviour with our designers. Adding this to our tracker.

**Comment by abhiomkar** [comment]
Fixed in #3417
