### ISSUE TITLE
Adding disabled to css only select makes it disappear

### ISSUE THREAD

**Issue by deap82** [material-components/material-components-web#276]
### What MDC-Web Version are you using?

Recreated in code pen, so current version at
https://unpkg.com/material-components-web@latest/dist/material-components-web.css

### What browser(s) is this bug affecting?
Tested in Chrome and Edge

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
Add disabled attribute to a select.mdc-select element.
See code pen: http://codepen.io/deap82/pen/oBPGRJ?editors=1000

### What is the expected behavior?
A disabled select element.

### What is the actual behavior?
The select element goes completely invisible.

**Comment by Garbee** [comment]
Looks to me like the dark theme modifiers being generated are causing this. Once I uncheck them in the Elements panel, things look right.

**Comment by traviskaufman** [comment]
Definitely a bug. Thanks for filing!
