### ISSUE TITLE
Support disabling the horizontal viewport auto-alignment feature of an mdc-menu-surface

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2772]

**Comment by williamernest** [comment]
I don't believe this will be an issue when integrating the new menu into the new select. The auto positioning logic is designed to flip the anchored corners when anchoring to the "end" of an element if there isn't enough room in the viewport for the menu at the end of the anchor. 

It does not change alignment of the menu when anchored using a "start" corner, so should not be an issue integrating the new menu with the new select.
