### ISSUE TITLE
Using components with build tools other than Webpack

### ISSUE THREAD

**Issue by o-t-w** [material-components/material-components-web#2775]
I am using NPM scripts as a build too. Do material components only work with Webpack?
I am getting the error `File to import not found or unreadable: @material/animation/variables`

In package.json I have 
```  
"scripts": {
    "sass": "node-sass  --output-style compressed -o dist/styles.css src/styles.scss"
  },
```
In terminal I ran `$ npm install @material/textfield`

In my styles.scss file I have `@import "../node_modules/@material/textfield/mdc-text-field";`

**Comment by Karikatest** [comment]
I was able to successfully use MDC with Rollupjs and could compile sass to css, the only problem i encountered was compiling the javascript files with babel from rollupjs

**Comment by kfranqueiro** [comment]
You should be able to address the Sass error by adding `--include-paths=node_modules`. We do the same in our [Getting Started Guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#step-2-include-css-for-a-component) (which uses Webpack, but the `sass-loader` options apply directly to the Sass preprocessor).

**Comment by o-t-w** [comment]
I tried 

` "sass": "node-sass --include-paths=node_modules --output-style compressed -o dist/styles.css src/styles.scss"
`
but am getting the same error message 😿

**Comment by kfranqueiro** [comment]
Apologies... I had a typo in my previous comment. The option is `--include-path` with no s.

**Comment by kfranqueiro** [comment]
I'm going to close this since I'm pretty sure `--include-path=node_modules` resolves it. I just tested it successfully with 0.35.2 on a SCSS file containing `@import "@material/textfield/mdc-text-field";`.

**Comment by johannes247** [comment]
I am experiencing the same problem.
Althought I'm trying to `@import '@material/textfield/mdc-text-field'` and it doesn't seem to locate 
`@material/animation/variables`..

I tried going directly into the folder where the `variables.scss` is located but they seem to start with an `_`. so that file name under textfield folder is actually `_variables.scss`.
