### ISSUE TITLE
Sass fails to compile when the component library is imported

### ISSUE THREAD

**Issue by grulex** [material-components/material-components-web#278]
When I try to import the entire freshly installed library into a new project:

`@import 'material-components-web/material-components-web';`

I get the following Sass compilation error:

`Invalid CSS after "...-penumbra-color": expected ";", was ","`
`on line 34 of /www/libraries/node_modules/@material/elevation/_mixins.scss`
`from line 19 of /www/libraries/node_modules/@material/button/mdc-button.scss`
`from line 18 of /www/libraries/node_modules/material-components-web/material-components-web.scss`

When I comment out these lines, compilation succeeds.

`#{$mdc-elevation-property}:`
`#{map-get($mdc-elevation-umbra-map, $z-value)} $mdc-elevation-umbra-color,`
`#{map-get($mdc-elevation-penumbra-map, $z-value)} $mdc-elevation-penumbra-color,`
`#{map-get($mdc-elevation-ambient-map, $z-value)} $mdc-elevation-ambient-color;`

This is obviously not a solution, but it probably means the issue is related to this code.

I have the latest version of MDC-Web (0.4.0) and Sass (3.4.23).

**Comment by traviskaufman** [comment]
I was able to put together a repro of this error using Sass v3.4.21 - http://www.sassmeister.com/gist/088ea8e72c8ce5cf0d1e737bba98f420

This error also happens using Sass v3.3.x - http://www.sassmeister.com/gist/41aa6afa0e1d70187d9630e594028656

However, it compiles correct using Sass v4 alpha - http://www.sassmeister.com/gist/1bcd1ed795806f5a4c3d4f8c8e1c2edc

It also compiles correctly using LibSass - http://www.sassmeister.com/gist/58078f6fec315da378886c31956d6748

Thus, it looks like this is an issue with Ruby-sass. I've filed https://github.com/sass/sass/issues/2241 for it.

**Comment by fabiolnm** [comment]
@traviskaufman 

as stated here: https://github.com/sass/sass/issues/2241#issuecomment-279068652 the problem can be fixed by removing unnecessary interpolation:

```
#{$mdc-elevation-property}:
  map-get($mdc-elevation-umbra-map, $z-value) $mdc-elevation-umbra-color,
  map-get($mdc-elevation-penumbra-map, $z-value) $mdc-elevation-penumbra-color,
  map-get($mdc-elevation-ambient-map, $z-value) $mdc-elevation-ambient-color;
```

**Comment by fabiolnm** [comment]
Nevermind, compilation succeeds but elevation won't work. Anyway, I realized it's only needed to comment out one of three lines, for instance:

```
  #{$mdc-elevation-property}:
    #{map-get($mdc-elevation-umbra-map, $z-value)} $mdc-elevation-umbra-color,
    #{map-get($mdc-elevation-penumbra-map, $z-value)} $mdc-elevation-penumbra-color;
```

will compile and work. 

Knowing $mdc-elevation-property is defined in ```elevation/_variables```:
```
$mdc-elevation-property: box-shadow !default;
```

And reading bow shadow documentation at https://www.w3schools.com/cssref/css3_pr_box-shadow.asp, I understood these ```map-get``` args are ```h-shadow``` and ```v-shadow``` definitions, being the third argument the cause of the bug.

Is that correct?
