### ISSUE TITLE
mdc-text-field's helper text is too far from text field

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2783]
The spec shows 16px from bottom of text field to baseline of helper text:
https://material.io/design/components/text-fields.html#spec
![image](https://user-images.githubusercontent.com/4703432/40330744-c4715d3c-5d02-11e8-9372-b4f2f183f2e5.png)

But our `mdc-text-field` looks like this:
![image](https://user-images.githubusercontent.com/4703432/40330764-d37da448-5d02-11e8-86c9-11e61ac4dbc1.png)

**Comment by clshortfuse** [comment]
You can give this a try.

```
.mdc-text-field:not(:last-child) {
  margin-bottom: 0;
}

.mdc-text-field-helper-text::before {
  content: "";
  display: inline-block;
  vertical-align: baseline;
  margin-top: 1rem;
```

The first ruleset removes the bottom margin of the text-field if it's not the last item.
The second gives a `1rem` (`16sp`) top margin based on the font baseline.

**Comment by lynnjepsen** [comment]
Thanks @clshortfuse , I think you're proposal is pretty similar to what we want to do in #3038 . I think #3038 will create a new mdc-typography mixin we can use (outputting this ::before code) within mdc-text-field.
