### ISSUE TITLE
File to import not found or unreadable: @material/elevation/mixins

### ISSUE THREAD

**Issue by thiagovilla** [material-components/material-components-web#2800]
### What MDC Web Version are you using?

@material/top-app-bar 0.35.2

### What browser(s) is this bug affecting?

Chrome 66.0.3359.181

### What OS are you using?

Windows 10 Pro x64 on HP Pavilion g4

### What are the steps to reproduce the bug?

1. Install `parcel` globally with `npm i -g parcel`
2. Create test folder `mkdir test && cd test`
3. Create minimal `package.json`:

```json
{
  "devDependencies": {}
}
```

4. Install `@material/top-app-bar` with `npm i --save-dev @material/top-app-bar`
5. Create HTML, SCSS & JS according to [Material.io > Develop > Web > Top App Bar](https://material.io/develop/web/components/top-app-bar/) - see [codepen](https://codepen.io/thiagovilla/pen/JvqaKj)

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MDC Top App Bar Test</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" media="screen" href="./main.scss" />
  <script src="./main.js"></script>
</head>
<body>
  <header class="mdc-top-app-bar">
    <div class="mdc-top-app-bar__row">
      <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
        <a href="#" class="material-icons mdc-top-app-bar__navigation-icon">menu</a>
        <span class="mdc-top-app-bar__title">Title</span>
      </section>
    </div>
  </header>
</body>
</html>
```
```js
import { MDCTopAppBar } from '@material/top-app-bar/index'

MDCTopAppBar(document.querySelector('.mdc-top-app-bar'))
```
```scss
@import "@material/top-app-bar/mdc-top-app-bar";
```

6. Run `parcel index.html`
7. Get error `File to import not found or unreadable: @material/elevation/mixins`

### What is the expected behavior?

I opened this [same issue on Parcel's repo](https://github.com/parcel-bundler/parcel/issues/1416), but we concluded it's a bug in MDC Web.

### What is the actual behavior?

The bundler is unable to load the mixins:

```bash
PS C:\apps\test> parcel index.html
Server running at http://localhost:1234
×  C:\apps\test\main.scss: File to import not found or unreadable: @material/elevation/mixins.
    at options.error (C:\apps\test\node_modules\node-sass\lib\index.js:291:26)
```

### Any other information you believe would be useful?

Didn't try setting this up with `webpack`

**Comment by kfranqueiro** [comment]
Are you able to configure parcel to pass `--include-path=node_modules` to node-sass? This is a thing we document in our Getting Started guide when configuring for webpack.

**Comment by kfranqueiro** [comment]
It seems like it should be possible to configure `includePaths` in node-sass for Parcel via a `.sassrc` or `.sassrc.js` file, judging by these lines of code: https://github.com/parcel-bundler/parcel/blob/master/src/assets/SASSAsset.js#L25-L27

Although I see a closed bug where people are still reporting issues with this: https://github.com/parcel-bundler/parcel/issues/383

At any rate, it's worth a try, and I don't think there's anything we can do to help this on the MDC Web side. I'm going to close this as you mentioned.
