### ISSUE TITLE
webpack.config.js typo on material.io > dev > web > docs > getting started

### ISSUE THREAD

**Issue by thiagovilla** [material-components/material-components-web#2801]
![image](https://user-images.githubusercontent.com/22099217/40493641-827c1bbc-5f49-11e8-8633-82a5dcb60d2e.png)

Shouldn't `loaders` be `rules`?

Link: https://material.io/develop/web/docs/getting-started/

PS: the on-page feedback balloon isn't working!

**Comment by kfranqueiro** [comment]
Huh. I'm not sure how that got there; from what I'm reading online, it's actually syntax from Webpack 1.

I think you're right; would you like to file a PR?

Also, RE the feedback balloon, is it not showing a dialog at all for you? Or is the dialog not submitting? It does seem like at the very least, the screenshot capture isn't working on the docs pages for some reason, so I'll file a bug about that, but if you can provide more details on the behavior you observed, that'll help too.

**Comment by abhiomkar** [comment]
This seems to be fixed. Closing.
