### ISSUE TITLE
mdc-text-field doesn't play nicely with Chrome autofill

### ISSUE THREAD

**Issue by nfriend** [material-components/material-components-web#2802]
### What MDC Web Version are you using?

0.35.2

### What browser(s) is this bug affecting?

Chrome Version 66.0.3359.181 (Official Build) (64-bit)

User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36`

### What OS are you using?

Windows 10 Pro, Version 10.0.15063 Build 15063

### What are the steps to reproduce the bug?

Build a form that includes a [`mdc-text-field`](https://material.io/develop/web/components/input-controls/text-field/).  Submit the form using Chrome.  Open the form again, and enter the same information, allowing Chrome to autofill the form values.

### What is the expected behavior?

The autofill style should not obscure the text field control.

### What is the actual behavior?

The yellow autofill background that is applied to the controls obscures the outline and the floating text label.  Here is a screenshot demonstrating this behavior:

![image](https://user-images.githubusercontent.com/1638631/40493301-d04b94ae-5f48-11e8-81a0-0fddb5d0d98f.png)

For reference, here is what the form looks like without the autofill styling applied:

![image](https://user-images.githubusercontent.com/1638631/40493311-db0b31a6-5f48-11e8-948b-985d8c0c8acf.png)

**Comment by kfranqueiro** [comment]
I think at one point we also observed some funny behavior where it affected the floating label size or position. Not sure yet how much control we have over the autofill behavior, but we definitely want to track this.

**Comment by AreaInsights** [comment]
Can it be fixed with .mdc-text-field__input:-webkit-autofill { //override }?
I tried this but could not get it working.

**Comment by mnd-dsgn** [comment]
This works for me:

```
input {
  -webkit-box-shadow: 0 0 0 30px white inset !important;
}
```

**Comment by nfriend** [comment]
@mnd-dsgn - That CSS snippet does remove the yellow background, but it also breaks the overall appearance of the control.  Here's a non-autofilled input element without your CSS snippet applied:

![image](https://user-images.githubusercontent.com/1638631/42654244-64fa4d7c-85ee-11e8-8a41-d3af7fd620f0.png)

And here's what it looks like after adding your CSS rule:

![image](https://user-images.githubusercontent.com/1638631/42654286-81e57420-85ee-11e8-983c-a931b2cb4fa2.png)

**Comment by aminNazarii** [comment]
@nfriend this is useful article
[https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/](url)

**Comment by davwheat** [comment]
I get the following result.

![image](https://user-images.githubusercontent.com/7406822/45372255-6ff07280-b5e4-11e8-9406-9a522cd13eac.png)

**Comment by oste** [comment]
thanks for the link @aminNazarii ... in the comments there are a couple of good solutions.

The first screen shot is a fix with this css

```
.mdc-floating-label {
    z-index: 1;
}

input:focus {
  outline: none;
}

input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus {
  background-clip: content-box;
}
```

without the z-index on .mdc-floating-label you get the second screenshot so that's important.

The third screenshot uses this other solution

```
@-webkit-keyframes autofill {
    to {
        background: transparent;
    }
}

input:-webkit-autofill {
    -webkit-animation-name: autofill;
    -webkit-animation-fill-mode: both;
}
```

Take your pick! leaning towards leaving a bit of the yellow as an indicator. Maybe the MCW team can incorporate either of these? Or maybe just add the z-index @kfranqueiro 

![autofill-input-fixed](https://user-images.githubusercontent.com/350275/46884248-6eec7400-ce22-11e8-94f2-3df7a50bfba2.jpg)
![autofill-input-z-index](https://user-images.githubusercontent.com/350275/46884249-6eec7400-ce22-11e8-92cf-7202dfd9c27f.jpg)
![autofill-transparent](https://user-images.githubusercontent.com/350275/46884250-6f850a80-ce22-11e8-8a19-df6e10cefe51.jpg)

**Comment by oste** [comment]
note: I think the first screenshot would probably be best without the white padding. Leaving the yellow indicator that chrome is autofilling seems like a good choice but that white padding is a bit off aesthetically.

**Comment by huajianjiang** [comment]
> note: I think the first screenshot would probably be best without the white padding. Leaving the yellow indicator that chrome is autofilling seems like a good choice but that white padding is a bit off aesthetically.



> thanks for the link @aminNazarii ... in the comments there are a couple of good solutions.
> 
> The first screen shot is a fix with this css
> 
> ```
> .mdc-floating-label {
>     z-index: 1;
> }
> 
> input:focus {
>   outline: none;
> }
> 
> input:-webkit-autofill,
> input:-webkit-autofill:hover,
> input:-webkit-autofill:focus {
>   background-clip: content-box;
> }
> ```
> without the z-index on .mdc-floating-label you get the second screenshot so that's important.
> 
> The third screenshot uses this other solution
> 
> ```
> @-webkit-keyframes autofill {
>     to {
>         background: transparent;
>     }
> }
> 
> input:-webkit-autofill {
>     -webkit-animation-name: autofill;
>     -webkit-animation-fill-mode: both;
> }
> ```
> Take your pick! leaning towards leaving a bit of the yellow as an indicator. Maybe the MCW team can incorporate either of these? Or maybe just add the z-index @kfranqueiro
> 
> 1st screenshot
> ![autofill-input-fixed](https://user-images.githubusercontent.com/350275/46884248-6eec7400-ce22-11e8-94f2-3df7a50bfba2.jpg)
> 
> 2nd screenshot with z-index issue
> ![autofill-input-z-index](https://user-images.githubusercontent.com/350275/46884249-6eec7400-ce22-11e8-92cf-7202dfd9c27f.jpg)
> 
> 3rd screenshot using keyframe
> ![autofill-transparent](https://user-images.githubusercontent.com/350275/46884250-6f850a80-ce22-11e8-8a19-df6e10cefe51.jpg)

Unluckly! It does not work.

**Comment by neoGeneva** [comment]
I had a quick attempt at fixing this based on what @oste suggested, and setting the z-index of the input to auto solves the issue for me in Chrome 71.0.3578.98 (64-bit)

I'm also using MDC 0.42.0, so I think that might be a factor in why this works, I think that inputs z-index is more important in 0.35.2?

```css
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus {
    z-index: auto !important;
}
```

Results:

![image](https://user-images.githubusercontent.com/804724/49933809-897dbf00-ff31-11e8-846d-36024f7b34a2.png)

**Comment by markboisvert** [comment]
This fixed it for me:

```css
.mdc-floating-label, .mdc-notched-outline {
    z-index: 1;
}
