### ISSUE TITLE
Incorrect ripple effect on filter chip with no leading icon

### ISSUE THREAD

**Issue by EstebanG23** [material-components/material-components-web#2812]
## Bugs

The filter chip with no leading icon has incorrect ripple when clicked. Instead of starting the ripple where clicked the ripple center is always in the same spot.

### What MDC Web Version are you using?

> 0.35.2

### What browser(s) is this bug affecting?

> All

### What OS are you using?

> Mac OS

### What are the steps to reproduce the bug?

> 1. Run the demo server
> 2. Go to localhost:8080/chips.html
> 3. Click on a Filter chip with no leading icon 
> 4. Observe the component's behavior
> 5. Helps to see if you set animations to 10%

### What is the expected behavior?

> The ripple should start where the mouse is clicked on the chip. 

### What is the actual behavior?

> The ripple effect is starting in the same spot and not where the chip is clicked.

### Any other information you believe would be useful?

Incorrect behavior
![bad-chip](https://user-images.githubusercontent.com/18471209/40509924-de58fb98-5f4f-11e8-9936-8dff27cbc11b.gif)

Correct behavior
![correct-ripple](https://user-images.githubusercontent.com/18471209/40509960-fd1a7278-5f4f-11e8-870a-72e86bed7dff.gif)

**Comment by moog16** [comment]
Confirmed this is still an issue with https://codepen.io/moog16/pen/MxqbRY. This was brought up in https://github.com/material-components/material-components-web-react/issues/301#issuecomment-472713788
