### ISSUE TITLE
background-image in body::after "appears" within text-fields

### ISSUE THREAD

**Issue by seekr** [material-components/material-components-web#2817]
## Bugs

Having a background-image in body::after, said image "appears" within text-fields:
![image](https://user-images.githubusercontent.com/2786460/40519237-042ef288-5f95-11e8-8058-c033f6e272ff.png)

### What MDC Web Version are you using?

0.35.2

### What browser(s) is this bug affecting?

Chrome 62.0.3202.94, firefox, safari

### What OS are you using?

MacOS High Sierra

**Comment by kfranqueiro** [comment]
Interesting... can you demonstrate this in a [codepen](https://codepen.io/williamernest/pen/deyxyp)?

**Comment by seekr** [comment]
@kfranqueiro here is a codepen: https://codepen.io/seekr/pen/vrBRVQ

**Comment by kfranqueiro** [comment]
Your nested selectors result in your `::after` styles applying to `body ::after`, which will match any `::after` pseudo-element that is a direct or indirect descendant of `body`. This ends up applying to any MDC Web components that use MDC Ripple, which uses `::before` and `::after` for states and ripple styles.

If you change your inner selector to `&::after`, it will evaluate to `body::after` and only apply to the pseudo-element directly within the `body` element, which is probably what you want.

(h/t @abhiomkar for pointing this out while we looked at it.)

**Comment by seekr** [comment]
Absolutely right, sorry for being thick!
