### ISSUE TITLE
[Dialog] uses legecy Typography

### ISSUE THREAD

**Issue by yezhi780625** [material-components/material-components-web#2820]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Dialog uses legacy ` @material/typography ` which is incompatible with other material components web.

### What MDC Web Version are you using?

0.35.2

**Comment by david-j-davis** [comment]
I'm also getting a similar error when building the dialog:

Error: Invalid style specified! Choose one of display4, display3, display2, display1, headline, title, subheading2, subheading1, body2, body1, caption, button
        on line 29 of node_modules/@material/typography/_mixins.scss, in mixin `mdc-typography`
        from line 86 of node_modules/@material/dialog/mdc-dialog.scss

**Comment by kfranqueiro** [comment]
Yeah, that's the error that occurs as a result of this. Manually also installing `@material/typography@0.35` should resolve the error.

We've merged the PR to fix the dependency, so this error won't occur in our next release.
