### ISSUE TITLE
Certain elements show through the Temporary Drawer when it is open

### ISSUE THREAD

**Issue by robbyrice** [material-components/material-components-web#2822]
This issue has existed for a while and I was hoping that the latest release would address it. Since this wasn't the case I figured I would open this issue. I've enjoyed working with MDC for the Web and I want to thank the team for all the effort they put into it.

### What MDC Web Version are you using?

https://unpkg.com/material-components-web@latest

### What browser(s) is this bug affecting?

All

### What OS are you using?

Linux Ubuntu 16.04

### What are the steps to reproduce the bug?

Add a Temporary Drawer with a Text-field and Button in the main content of the page.

By going to this CodePen https://codepen.io/anon/pen/qYzPZR?editors=1011 you can see this problem.

### What is the expected behavior?

The Temporary Drawer should be elevated above all components on the page.

### What is the actual behavior?

When the Temporary Drawer is open, Text-field and Button elements (and possibly others) appear above the drawer. This can prevent clicking on elements in the drawer. I'm not sure if it's a problem with my markup, but I'm not inclined to think so because I pretty much copied and pasted most of the markup from the demo pages.

**Comment by cubetastic33** [comment]
Yup, I also had the same issue with a fixed top-app-bar. If I add a top-app-bar and a button, and scroll down, the button would appear above the app bar, just like it is doing with the temporary drawer. Until they fix it, you could use the `z-index` CSS attribute and set it to a higher number. I found that `z-index: 2` seemed to be pretty good for the top app bar, but you should probably set a bigger number for the temporary drawer.

**Comment by williamernest** [comment]
@robbyrice @cubetastic33 Thanks for filing this issue and including a codepen. This issue will be resolved in the next release. For now, you can move the navigation drawer outside of the header and it will work as expected. 
Here's the updated codepen: https://codepen.io/williamernest/pen/qYeBmK?editors=1111

You can also add `z-index` onto the `top-app-bar` element using your own class to fix this problem as well. 

Here's another codepen: https://codepen.io/williamernest/pen/aGebwq?editors=1111

**Comment by kelostrada** [comment]
Thanks for the fix!
I just wanted to note, that when you add mdc-menu to top-app-bar then similar issue happens. Images from image-list are over the menu items (menu should hide everything below it)

Example: https://imgur.com/a/r3EyWa9

Your fix seems to fix this problem too however.
By the way, can you point me to a direction how to use master branch in npm of `@material/top-app-bar`?
