### ISSUE TITLE
Implement Speed Dial Component

### ISSUE THREAD

**Issue by TangSteven** [material-components/material-components-web#283]
Spec reference: [https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions)

"The floating action button can fling out related actions upon press. The button should remain on screen after the menu is invoked. Tapping in the same spot should either activate the most commonly used action or close the open menu."

**Comment by traviskaufman** [comment]
We originally omitted this because we want to push people towards using the FAB->Menu behavior instead (#35), but a lot of users asked for this, and it's a pattern in the spec, so we can definitely implement it.

**Comment by TangSteven** [comment]
A good reference of this is in Google's Inbox.
https://inbox.google.com/

**Comment by vitaly-zdanevich** [comment]
Why this closed if not implemented?

**Comment by leocaseiro** [comment]
I'm sorry, but why is this issue closed?

**Comment by leocaseiro** [comment]
I thought that FAB->Menu behaviour was not authorized by the Material Specs: 

> Put overflow actions in the overflow menu in toolbars, not in floating action buttons.

![screen shot 2018-02-21 at 3 57 31 pm](https://user-images.githubusercontent.com/940070/36463760-f6f95f9e-171f-11e8-92b5-3a716796fe0a.png)

**Comment by jwillmer** [comment]
@lynnmercier can u comment please on why you closed this?
