### ISSUE TITLE
Slider not working with CDN

### ISSUE THREAD

**Issue by mgoulao** [material-components/material-components-web#2833]
I have tried to use MDC with the unpkg CDN but the Slider doesn't work properly.

### What MDC Web Version are you using?

0.34.1

### What browser(s) is this bug affecting?

Any browser

### What OS are you using?

Windows 10 - 1803

### What are the steps to reproduce the bug?

1. Go to [https://codepen.io/mgoulao/pen/gzVLOG](https://codepen.io/mgoulao/pen/gzVLOG)
2. Use the mouse to change slider value

### What is the expected behavior?

It should work like the [Demos](https://material-components.github.io/material-components-web-catalog/#/component/slider).

**Comment by williamernest** [comment]
@mgoulao You have to initialize it with javascript. 
https://codepen.io/williamernest/pen/pVMRGP

**Comment by mgoulao** [comment]
Thanks. If I change the width of the slider it doesn't work well. I have updated the Codepen to show the problem [https://codepen.io/mgoulao/pen/gzVLOG](https://codepen.io/mgoulao/pen/gzVLOG)

**Comment by williamernest** [comment]
Call `slider.layout();` after you change the layout 

From the docs 
```
Recomputes the dimensions and re-lays out the component. This should be called if the dimensions of the slider itself or any of its parent elements change programmatically (it is called automatically on resize).
```
