### ISSUE TITLE
File to import not found or unreadable: @material/elevation/mixins.

### ISSUE THREAD

**Issue by bifunctor** [material-components/material-components-web#2834]
Hi all 
I've got the following error by using Top App Bar.

### What MDC Web Version are you using?
`"@material/top-app-bar": "^0.35.2",`

### What OS are you using?

> Ubuntu 18.04.

### What are the steps to reproduce the bug?
I included the Top App Bar into my SCSS file as following:

`@import "@material/top-app-bar/mdc-top-app-bar.scss";`  

After compiling I've got the following error message:
```
ERROR in ./src/index.scss
Module build failed:
@import "@material/elevation/mixins";
^
      File to import not found or unreadable: @material/elevation/mixins.
      in /home/developer/Desktop/reason-react/cockpit/node_modules/@material/top-app-bar/mdc-top-app-bar.scss (line 17, column 1)
 @ ./src/index.js 7:0-23
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./src/index.js
```
My webpack 4 setting for SASS is:   
```
        test: /\.s?[ac]ss$/,
        use: [
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true,
              includePaths: glob
                .sync('packages/*/node_modules')
                .map(d => path.join(__dirname, d))
            }
          }
        ]
      },
```

### What is the expected behavior?
Using Top Bar App without any error.

Thanks

**Comment by bifunctor** [comment]
I've got the solution:  
`includePaths: ['node_modules', 'node_modules/@material/*'] .map((d) => path.join(__dirname, d))`   

On the main page https://github.com/material-components/material-components-web, it says: 

> You also need to configure sass-loader to understand the @material imports used by MDC Web. Update your webpack.config.js by changing { loader: 'sass-loader' } to:
> 
> ```
> {
>   loader: 'sass-loader',
>   options: {
>     includePaths: ['./node_modules']
>   }
> }
> ```

Please adjust it. 

Thanks

**Comment by kfranqueiro** [comment]
Since we haven't heard back and weren't able to reproduce this, I'm going to close this issue. If you can point to a reduced case where it's consistently reproducible, we'd be happy to look into a resolution.

**Comment by Mr-Zer0** [comment]
I am facing the same issue. Is there any proper solution for that?
