### ISSUE TITLE
mdc-layout-grid naming devices

### ISSUE THREAD

**Issue by kvdheuvel** [material-components/material-components-web#2836]
### What MDC Web Version are you using?
0.35.2
### What browser(s) is this bug affecting?
Chrome
### What OS are you using?
Windows 10
### What are the steps to reproduce the bug?
- create an grid with the classes `mdc-layout-grid__cell--span-1`.
- add an extra class for devices (desktop, tablet & mobile), like how it's mentioned in [the documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-layout-grid)
- desktop and tablet work like expected, but mobile does not.

the classname `mdc-layout-grid__cell--span-1-mobile` doesn't work because it should be `mdc-layout-grid__cell--span-1-phone`
### What is the expected behavior?
I expected that the class `mdc-layout-grid__cell--span-1-mobile` would have worked. That being said, `mdc-layout-grid__cell--span-1-phone` works, so it's problem is within the naming of the classes.
### What is the actual behavior?
`mdc-layout-grid__cell--span-1-mobile` won't work because it is the wrong classname
### Any other information you believe would be useful?
No extra information, just the documentation should be edited

**Comment by kfranqueiro** [comment]
Thanks for pointing this out. It looks like we refer to "phone" everywhere except this one place in the documentation. Would you like to open a PR to make this edit?
