### ISSUE TITLE
Drawer - list group subheader labels

### ISSUE THREAD

**Issue by im-n1** [material-components/material-components-web#2839]
Since MD has no nested levels of navigation I'm trying to squeeze next "level" into drawer itself. However I'm missing this label right under the divider.

I guess you guys will manage the ticket flow and hopefully incorporate this small feature.

![image](https://user-images.githubusercontent.com/198654/40683368-b1e72894-638e-11e8-8aa0-e9b8afdeb13e.png)

**Comment by kfranqueiro** [comment]
Hey, thanks for opening this issue.

The Drawer package in MDC Web is definitely not 100% up to date with the new guidelines just yet - we're in the middle of speccing out the work for that right now.

Currently, the closest equivalent would probably be to use the `mdc-list-group` and `mdc-list-group__subheader` classes with some additional styling:

```html
<div class="mdc-list-group">
  <ul class="mdc-list demo-list">
    <li class="mdc-list-item">Inbox</li>
    ...
  </ul>
  <hr class="mdc-list-divider">
  <h3 class="mdc-list-group__subheader">List 2</h3>
  <ul class="mdc-list demo-list">
    <li class="mdc-list-item">Family</li>
    ...
  </ul>
</div>
```

I'll track this for the time being so we don't lose sight of it, but we may eventually create a new task that encompasses this.
