### ISSUE TITLE
mdc-list should support a single aria-selected item

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2851]
- [x] Add a JavaScript API to initialize a "single select list" differently from a "default list"
- [x] If the list item has focus, and the user hits Enter or Space, then `MDCList` will add `aria-selected=true` to that list item.
- [x] If the user tabs out of a list, but one list item has `aria-selected=true`, then tabbing back into the list should move the focus immediately to the selected list item

**Comment by williamernest** [comment]
Resolved with #2970
