### ISSUE TITLE
issues with top app bar

### ISSUE THREAD

**Issue by akshaybabloo** [material-components/material-components-web#2863]
I was trying out the top app bar and saw that there seems to be a gap on the left side and top of the bar, is this something intentional? I have used the code from the example (both prebuilt and the compiled), both of them had the same output.

### What MDC Web Version are you using?

I am using `0.35.0`

### What browser(s) is this bug affecting?

FireFox 60 and Chrome 67

### What OS are you using?

Windows 10 1803

### What are the steps to reproduce the bug?

https://codepen.io/akshaybabloo/pen/JZYvMN

### What is the expected behavior?

The bar seems to have a gap on the left and top side of the screen.

### What is the actual behavior?

The bar should streatch all the way to left and top.

**Comment by dagema1** [comment]
I think this is because your browser is setting some kind of margin on the body element.
If that's the case you have to set your body margin to 0
Something like

body{
margin:0;
}

**Comment by akshaybabloo** [comment]
I can understand if it was one browser but two? Also, I just checked same issues with Edge browser.

**Comment by akshaybabloo** [comment]
Should I be using `normalise` with this?

**Comment by robbyrice** [comment]
@akshaybabloo yes, using normalize.css will fix this problem. If you enable it in your codepen example you will see the gaps go away.

**Comment by akshaybabloo** [comment]
True. Thanks, @robbyrice.

**Comment by robbyrice** [comment]
Glad to help!
