### ISSUE TITLE
Document use of Image List with a LTR Masonry solution; consider renaming classes/mixins

### ISSUE THREAD

**Issue by dessant** [material-components/material-components-web#2865]
It appears the images are laid out vertically, from top to bottom. This may not be the most common or expected stacking order, and the design guidelines seem to imply that the order is ltr or rtl.

https://material.io/design/components/image-lists.html#types

**Comment by theenoahmason** [comment]
Agreed. This is not a masonry layout, it is a traditional newspaper column based layout. CSS columns works much better for textual content than it does for displaying lists of this kind.

**Comment by kfranqueiro** [comment]
Thanks for raising this issue.

The design guidelines don't seem to explicitly indicate one way or the other, but I talked to our designer on the image list component and she said that the implication was indeed supposed to be LTR or RTL.

The advantage of the current approach is that MDC Image List requires only minimal CSS, with no JS, and serves its purpose in cases where it occupies a set region and the order of images doesn't matter. Additionally, there are already existing, mature, standalone JavaScript implementations for LTR masonry, so creating our own JS implementation seemed like it would be misplaced effort.

I could see potentially investigating the idea of documenting how to integrate a third-party JS masonry implementation to adhere to Material's style guidelines, in addition to providing our CSS-only solution. Does that sound reasonable?

**Comment by dessant** [comment]
Regarding the CSS-only solution, I believe components in this library should either adhere to the current Material Design spec, or they should be removed.

**Comment by williamernest** [comment]
@dessant Can you point out where you saw that in the spec? I've gone over the spec a couple of times and can't find anything indicating the direction.

**Comment by dessant** [comment]
I agree that there is no need to rewrite an existing masonry implementation, though an [existing library](https://github.com/desandro/masonry) could be imported and set up according to the spec, and provided as a component with the usual features one expects to find in MDC components.

**Comment by dessant** [comment]
@williamernest it's not stated explicitly in the spec, but horizontal ordering is considered to be the correct implementation by the designer of this component, so it's a matter of mentioning this in the guidelines to avoid these implementation mistakes.

**Comment by theenoahmason** [comment]
Masonry Layouts and column layouts are not the same thing. They are night and day. You dont look at a newspaper and say "wow those are some sweet masonry paragraphs." That is because they are in a traditional column based layout. Columns are not masonry. Masonry MEANS horizontal. Columns MEAN vertical. Just call modifier "--columns" instead of "--masonry" 

I have used MDC web with Masonry, Isotope, and Packery (all by metafizzy/desandro) and they work perfectly fine.

**Comment by kfranqueiro** [comment]
I'm going to track this RE including guidance (and potentially tailoring the styles we provide) for use with a third-party masonry library, probably Masonry.

RE renaming masonry to columns, we'd have to figure out something that makes sense in the context of the mixin to set the number of columns as well - `mdc-image-list-columns-columns` (vs. the current `mdc-image-list-masonry-columns`) would sound confusing.

Thanks for the feedback, everyone.

**Comment by theenoahmason** [comment]
@kfranqueiro

No more confusing than `.mdc-drawer__drawer` but point taken.

Perhaps a better modifier would be `--pack` or `--packed-vertical`.

Reguarding using image lists with Metafizzy's Masonry, I've done it several times and would be glad to post what I did here in vanilla JS as soon as I am back in front of the computer.

**Comment by theenoahmason** [comment]
## Using MDC Web Image Lists with Masonry

**Working reduced test case on codepen:**
https://codepen.io/theenoahmason/pen/NzbqjB

**HTML**

```html
<ul class="mdc-image-list mdc-image-list--masonry-js">
	<li class="mdc-image-list__item">
		<img 
		class="mdc-image-list__image" 
		src="..."
		/>
		<div class="mdc-image-list__supporting">
			<span class="mdc-image-list__label">...</span>
		</div>
	</li>
	...
</div>
```

**Sass**

```sass
.mdc-image-list { 
	&--masonry-js &__item {
		// width: calc((100% / $column-count) - (($gutterpx * ($column-count - 1)) / $column-count));
		width: calc((100% / 6) - ((16px * 5) / 6));
		// margin-bottom: $gutterpx;
		margin: 0 0 16px;
	}
}
```

**JavaScript**
```js
const imageListElement = document.querySelector('.mdc-image-list--masonry-js');
// init on imagesLoaded to ensure calculations are done properly. 
imagesLoaded(imageListElement, () => {
	new Masonry(imageListElement, {
		// use the list item selector as the column width.
		columnWidth: '.mdc-image-list__item',
		// only apply masonry to the list item selector.
		itemSelector: '.mdc-image-list__item', 
		// ensure widths are calculated by percentages.
		percentPosition: true, 
		// ensure this is the same as the sass gutter. 
		// this could also always be set by a `data-masonry-gutter` attribute.
		gutter: 16, 
	});
});
```

### Notes:
* Initializes masonry on `imagesLoaded` (also by metafizzy/desandro) to ensure calculations are correct.
* Provides a new calculation of column sizes (not that dissimilar from the `image-list-standard-columns` mixin calculation).
* The gutter in Sass should correspond exactly to the gutter provided to the Masonry script.
* The `margin-bottom` of `.mdc-image-list__item` should match the gutter.
* Gutter is at 16px to match spec.

**Comment by theenoahmason** [comment]
@kfranqueiro It's also worth noting here that CSS Column layout as used in masonry image lists as it currently stands will only work if the tiles are in multiples of the column count. This ensures that there are never horizontal rows with uneven amount of tiles. 

This is simply not feasible to use as is IMO.

**Comment by allan-chen** [comment]
Closing in favor of newer #6548 for tracking
