### ISSUE TITLE
New `mdc-drawer--modal`

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2875]
- [x] New `mdc-drawer-scrim-fill-color` Sass mixin
- [x] New HTML structure for this variant, including `mdc-drawer__scrim`
- [x] New `MDCModalDrawerFoundation` which extends `MDCDismissibleDrawerFoundation`
- [x] Documentation notes that `mdc-drawer--modal` cannot be used with `mdc-drawer--rail`

**Comment by kfranqueiro** [comment]
Note that the modal drawer should also trap focus. We can split that to its own task if it seems labor-intensive, but also see how MDC Dialog uses focus-trap.
