### ISSUE TITLE
includePaths configuration doesn't support nested node_modules cases

### ISSUE THREAD

**Issue by Slemma** [material-components/material-components-web#2882]
TextField.scss
`@import "~@material/textfield/mdc-text-field";`

TextField.js
```
import "./TextField.scss";
import {MDCTextField} from '@material/textfield';
```

npm run build =>

> ERROR in ./TextField.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js??ref--5-3!./Client/1. Core/MDC/TextField/TextField.scss)
> Module build failed:
> undefined
>             ^
>       No mixin named mdc-rtl-reflexive
>       in ....\node_modules\@material\textfield\_mixins.scss (line 498, column 14)

**Comment by kfranqueiro** [comment]
Can you check what version of `@material/textfield` and `@material/rtl` you have installed? Both were bumped to 0.36.0, and textfield depends on a feature added to rtl in 0.36.0.

**Comment by efstajas** [comment]
Same issue with top app bar: 

`ERROR in ./styles_global/styles_import.sass (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js??ref--4-2!./styles_global/styles_import.sass)
Module build failed: 
  @include mdc-rtl-reflexive(border-bottom-left-radius, 0, border-bottom-right-radius, $border-radius);
          ^
      No mixin named mdc-rtl-reflexive
      in /Users/jason/Documents/GitHub/transition/front/node_modules/@material/top-app-bar/_mixins.scss (line 49, column 12)
 @ ./styles_global/styles_import.sass 2:14-135
 @ ./index.js`

**Comment by efstajas** [comment]
Issue resolved after updating all my other material component dependencies to the newest version. Not sure which one fixed it.

**Comment by kfranqueiro** [comment]
I did some prototyping a couple of nights ago on how to possibly implement a Sass importer to accommodate these situations, and came up with [this](https://gist.github.com/kfranqueiro/b4d091ddb030cf117fe493df3a7897d5).

This might be useful if you run into this situation again. I'm going to track this to see about adding a section to our Getting Started guide to incorporate this.

**Comment by captainhurst** [comment]
I was able to resolve this issue by manually installing` @material/rtl`. After the mixin was available I was able to build normally.
