### ISSUE TITLE
Is there any way to build documention of other languages?

### ISSUE THREAD

**Issue by dwb1994** [material-components/material-components-web#2884]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What browser(s) is this bug affecting?

>  66.0.3359.181

### What OS are you using?

> macOS Sierra 10.12.6

### What is the expected behavior?

> I'd like to translate the [doc site](https://material.io/) into Chinese. Does the documention have an international solution?

**Comment by amsheehan** [comment]
Hello!

I18n is one of the initiatives of the material.io team moving forward. We are still in the discussion phase right now, so there is no timeline yet.

**Comment by dwb1994** [comment]
@amsheehan looking forward to I18n

**Comment by kfranqueiro** [comment]
I'm going to close this since currently there is work outside of MDC Web which needs to be performed before we can determine how to pursue this within the repository for the source of translations. We can open more focused tasks once the material.io team has infrastructure in place to support it.
