### ISSUE TITLE
[BUG] with the material components with shape on the main demo button

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#2886]
## Bugs

This is a bug with the website.

https://material-components.github.io/material-components-web-catalog/#/component/shape
<img width="573" alt="screen shot 2018-06-06 at 7 31 23 pm" src="https://user-images.githubusercontent.com/26075792/41023542-d82cff0a-69c0-11e8-8811-a09fb43d6ac6.png">

### What MDC Web Version are you using?

The website

### What browser(s) is this bug affecting?

Google Chrome
Version 67.0.3396.62 (Official Build) (64-bit)

### What OS are you using?

MacOS 10.13.5

### What are the steps to reproduce the bug?

Just look at the website. its an issue with the shape of the main demo button

### What is the expected behavior?

On the right side there shouldnt be and extra bit

### What is the actual behavior?

On the right side of the main demo button there is an extra bit that sticks out

**Comment by kfranqueiro** [comment]
Thanks for reporting. This happens inconsistently on Chrome, depending on the size and position of elements.

I'm hopeful that it's resolvable by slightly elongating the masking elements, we just need to make sure they're still positioned properly (and make sure we don't cause unforeseen issues in any other browsers).

**Comment by kfranqueiro** [comment]
This is now obsolete, as v0.40.0 has removed the angled corner DOM/mixins to focus exclusively on systematizing rounded corners purely via CSS.
