### ISSUE TITLE
how to implement it in for IE9, IE9 support.

### ISSUE THREAD

**Issue by anirugu** [material-components/material-components-web#2888]
I am looking for using it in IE9, does it support IE9.  if it doesn't support ie9 which framework can be used as alternative.

Thanks

**Comment by robbyrice** [comment]
The answer to your question about IE9 support can be found on the main README.md of this repository https://github.com/material-components/material-components-web#browser-support where it clearly states that only the latest 2 versions of each browser are officially supported.

As to the question about which framework to use to support IE9, I'll let other who are more knowledgeable in that area chime in.

**Comment by anirugu** [comment]
yes, got it, it's support IE11+, I tried yesterday in IE9, nothing was showing in lower than 10.

**Comment by kfranqueiro** [comment]
I can't find any Material libraries that explicitly support IE 9. The closest I know of is MDL (getmdl.io) which states that it degrades for IE 9, but MDL is no longer updated, as MDC Web supersedes it and continues to receive updates for new Material Design guidelines.

Moreover, IE 9 is far beyond its own support end-of-life (January 2016); the only version that MS itself claims to support is IE 11. Between that and the lack of features and presence of frustrating quirks, older versions are not recommended for use and not a priority to support.
