### ISSUE TITLE
Drawer Component that material.io/design website uses?

### ISSUE THREAD

**Issue by devxpy** [material-components/material-components-web#2896]
![image](https://user-images.githubusercontent.com/19492893/41109821-8b2b623e-6a95-11e8-84a8-be2f11b94d7c.png)

https://material.io/design/components/app-bars-bottom.html

Where can I find this component?

I'm not sure whether this is the right place, but since the official website uses the component, I figure you guys might have it.

**Comment by williamernest** [comment]
@devxpy The material.io site isn't using our navigation drawer component because it's not complete yet. Here's our roadmap of when components will be available. 

https://github.com/material-components/material-components/blob/develop/ROADMAP.md

**Comment by devxpy** [comment]
Ok, thanks for pointing me in the right direction.
