### ISSUE TITLE
Transition missing for web, or is it available somewhere on the site. 

### ISSUE THREAD

**Issue by anirugu** [material-components/material-components-web#2908]
I have made a page when someone click on image, a form show and next > part 2 shown  > next > part 3 shown.

I am looking for some kind of transition (like android does, I am not sure if material.io provide it).  So it would help me to transition from one form to the another.

I am searching material.io but I am not sure how these thing works. I am using javascript and css from unpkg.com

I am interested to see the demo part of https://material.io/develop/web/components/animation/ (which is not on the site). 

Someone can check and help me how I can implement transition on my own pages.

Thanks

**Comment by kfranqueiro** [comment]
Hello, and thanks for raising this question!

The MDC Animation package primarily exposes Sass constants and utilities for recommended animation easing functions, which essentially distills down to [a few variables](https://github.com/material-components/material-components-web/blob/v0.36.0/packages/mdc-animation/_variables.scss#L17-L20) based on the [easing guidelines](https://material.io/design/motion/speed.html#easing). (If you're using CSS from unpkg, you'd have to repeat these `cubic-bezier` values verbatim.)

Other components throughout MDC Web reuse these variables for various specific animations. As a result, it's difficult to construct a meaningful standalone page for MDC Animation alone.

For the specific purpose of page transitions, you could do something akin to what our catalog does, which transitions `opacity` between `0` and `1` and transitions `transform` between `translateY(15px)` and `translateY(0)`. The catalog uses a [React library](https://github.com/reactjs/react-transition-group) to add classes for the transition, but the styles can be found [here](https://github.com/material-components/material-components-web-catalog/blob/d9dfd179a49b2b9c8bc8598fdf8cb149693103f0/src/styles/ComponentPage.scss#L53-L72).
