### ISSUE TITLE
Add invalid styles to mdc-select

### ISSUE THREAD

**Issue by liabru** [material-components/material-components-web#291]
### What MDC-Web Version are you using?

0.2.0

### What browser(s) is this bug affecting?

All browsers, but most visible in Safari.

### What OS are you using?

OSX

### What are the steps to reproduce the bug?

1. Create an mdc-select component in a form.
1. Add a default option with no value.
1. Add some more options with values.
1. Add the `required` attribute to the select.
1. In the browser, change from the default option.
1. Change back to the default option.

The `mdc-select` component does not apply a class such as `mdc-select--invalid` nor does it appear to exist in the source code. This should also happen when the form is submitted in an invalid state.

### What is the expected behavior?

This should work the same as it already does for `mdc-textfield`, expected to automatically apply and remove a class such as `mdc-select--invalid` when the select changes validation state.

### What is the actual behavior?

No class is applied and in Safari there is no visual indication that the field is invalid.

**Comment by traviskaufman** [comment]
Good catch. I don't believe that there is any UX anywhere within the spec regarding invalid selects, so we'll need to coordinate with our design team on this.

**Comment by traviskaufman** [comment]
Design guidance on this is to _make the underline for the select red when invalid_, same color as for textfields. If this is too subtle, we can also mess around with making the text red and seeing what design says.

**Comment by traviskaufman** [comment]
Work to be done:

- [ ] Add `mdc-select--invalid` style
- [ ] Add `:invalid` style (for native control)
- [ ] Document these styles
- [ ] Document that we do not provide custom validity functions for JS select, only styles

**Comment by creativenoobie** [comment]
I see @lynnjepsen have closed this issue recently but I am not sure about updates.
I'm using unpkg.com for the stylesheet and css and it's not working.

**Comment by djensen47** [comment]
@lynnjepsen I went through the code in material-components-web/packages/mdc-select/ and, unless I'm missing something, this has _not_ been implemented. I also didn't see any references to this in any of the CHANGELOG.md notes.

Please re-open. Thanks!

**Comment by moog16** [comment]
Reopening...referenced [here](https://github.com/material-components/material-components-web/issues/2308#issuecomment-369763278)

**Comment by djensen47** [comment]
Thank you.

**Comment by jvalst** [comment]
I'm missing the required style on a selectbox as well. By default the selectbox get's a label, but no value. The selectbox should also get a required just like the textfields etc.

**Comment by JoshMayberry** [comment]
It would be great if this had a `foundation.styleValidity` method like `MDCTextfield` components do.
