### ISSUE TITLE
Top App Bar rendered with blank space above

### ISSUE THREAD

**Issue by thiagovilla** [material-components/material-components-web#2910]
### What MDC Web Version are you using?

`@latest` MDC Web from `unpkg` on Jun 8, 2018 (`0.36.0`)

### What browser(s) is this bug affecting?

Chrome 66.0.3359.181

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

### What OS are you using?

Windows 10 x64

### What are the steps to reproduce the bug?

Create `topappbar.html` HTML file:

PS: using `cdn` because this is an MDC prototyping lab (minimal setup).

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MDC Lab - Top App Bar</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
  <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" />
  <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
  <header class="mdc-top-app-bar">
    <div class="mdc-top-app-bar__row">
      <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
        <a href="#" class="material-icons mdc-top-app-bar__navigation-icon">menu</a>
        <span class="mdc-top-app-bar__title">Title</span>
      </section>
    </div>
  </header>
  <p style="height: 3000px;"></p>
  <script>
    mdc.topAppBar.MDCTopAppBar.attachTo(document.querySelector('.mdc-top-app-bar'))
  </script>
</body>
</html>
```

Run `topappbar.html` on Chrome.

Blank space on top of Top App Bar component (vanishes on scrolling):

![topappbar](https://user-images.githubusercontent.com/22099217/41160691-d984dea8-6b06-11e8-8e7c-2e37d1725396.gif)

### What is the expected behavior?

Top App Bar rendered *without* blank space.

### What is the actual behavior?

See GIF above.

### Any other information you believe would be useful?

Tried to disable `normalize.css` and set `<body style="margin: 0; padding: 0;">` but got the same behavior.

**Comment by berenddeboer** [comment]
Did you add the "mdc-top-app-bar--fixed-adjust" class? See docs.

**Comment by williamernest** [comment]
@thiagovilla Thanks for filing this issue. The first problem I noticed is the `body` tag of some browsers adds their own `margin` to the body, so you'll have to override those or use normalize. The space above the top app bar is from margin collapsing with the `p` element and the top app bar having their margin collapsed into one element and it's rendered above the top app bar. 

The best way around this is to put your `p` element inside of a div and use the `mdc-top-app-bar--fixed-adjust` class to offset it so it doesn't appear underneath the top app bar. 

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MDC Lab - Top App Bar</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
  <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" />
  <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
  <header class="mdc-top-app-bar">
    <div class="mdc-top-app-bar__row">
      <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
        <a href="#" class="material-icons mdc-top-app-bar__navigation-icon">menu</a>
        <span class="mdc-top-app-bar__title">Title</span>
      </section>
    </div>
  </header>
  <div class="mdc-top-app-bar--fixed-adjust" style="height: 3000px;">
    <p>ABAADSG</p>
  </div>
  <script>
    mdc.topAppBar.MDCTopAppBar.attachTo(document.querySelector('.mdc-top-app-bar'))
  </script>
</body>
</html>
```
