### ISSUE TITLE
MDCSnackbarFoundation has a hide event, but no onDismissed callback

### ISSUE THREAD

**Issue by veonua** [material-components/material-components-web#2916]
There is no user-defined callback to handle snackbar dismiss.

For comparison, Android has [`Snackbar.Callback`](https://developer.android.com/reference/android/support/design/widget/Snackbar.Callback).

### What MDC Web Version are you using?

0.34.0

### What are the steps to reproduce the bug?

in docs

```js
const dataObj = {
  message: messageInput.value,
  actionText: 'Undo',
  actionHandler: function() {
    console.log('my cool function');
  }
};
```

### What is the expected behavior?

```js
const dataObj = {
  // ...
  dismissHandler: function(reason:int) {
    if (reason == DISMISS_EVENT_CONSECUTIVE) {
       console.log('dismissed');
    }
  } 
};
```

### What is the actual behavior?

Right now it is not possible to respond to snackbar dismissing.

**Comment by kfranqueiro** [comment]
Are you looking for the [`MDCSnackbar:hide` event](https://github.com/material-components/material-components-web/tree/master/packages/mdc-snackbar#handling-events)?

Though you raise an interesting point in that we might want to examine exposing the action handler consistently to the show and hide events.

**Comment by veonua** [comment]
as far as I understand .hide is the global event and im my case it is
handled by Vue wrapper, I'm looking for function per message to be cohirent
with actionHandler.

actually I already implrmeted it, it it pretty trivial. but I'm pretty bad
in JS to make official PR.

**Comment by kfranqueiro** [comment]
I'm going to track this so we can investigate the current balance of APIs.

I can see where action and dismiss could be considered complements to each other, but I'm also unsure why snackbar was originally implemented with show/hide as DOM events on the snackbar element, while `actionHandler` is a passed-in callback; this seems inconsistent - i.e., why aren't they all callbacks? Or why couldn't we simply emit a `MDCSnackbar:action` event, too? I'd ideally like to expose an API that is consistent, but still satisfies use cases easily.

It would be helpful to know specifically what your usage flow looks like with snackbar - e.g. how are you reusing snackbar instances, and how diverse are the action / dismiss handlers?

**Comment by veonua** [comment]
currently I'm using it in "item will be removed" snack. On dismiss event
app sends remove call to the model , undo button just resets the view
