### ISSUE TITLE
Drawer Toolbar Spacer for Dense Top App Bar

### ISSUE THREAD

**Issue by kixortillan** [material-components/material-components-web#2941]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

> "material-components-web": "^0.36.0",

### What browser(s) is this bug affecting?

> All major browsers, Chrome, Firefox, Safari, etc

### What OS are you using?

> Ubuntu 16.04

### What are the steps to reproduce the bug?

> This is not a bug in component behavior but just a missed CSS since Top App Bar is new? Here is a screenshot to have better visualization. I cannot see a class appropriate for this in documentation nor scanning the complete css file of material web components.

![image](https://user-images.githubusercontent.com/7253957/41452898-69beb292-70a6-11e8-9a34-2728a577628f.png)

> I can fix this easily on my side but just want to inform you guys. My suggestion is having a new class for this? I don't know. Thanks for making these css components :-)

### What is the expected behavior?

> Drawer Toolbar Spacer is not the same height as the dense Top App Bar. 

### What is the actual behavior?

> Drawer Toolbar Spacer should be same height as the dense Top App Bar.

**Comment by kfranqueiro** [comment]
Thanks for pointing this out. We're currently working on new styles/components for Navigation Drawer, so I've tracked this so we take it into account.

**Comment by abhiomkar** [comment]
Starting from `v0.39.0` `mdc-drawer__toolbar-spacer` is removed from drawer. Drawer now has `mdc-drawer__header` section which includes title & subtitle. 

Alternatively you can use `$mdc-top-app-bar-dense-row-height` variable to add extra space from top to match with dense top app bar height. Hope this helps!
