### ISSUE TITLE
Drawer and Menu should explicitly document the need to import mdc-list scss

### ISSUE THREAD

**Issue by bifunctor** [material-components/material-components-web#2953]
Hi all 
I am trying to use drawer and it seems it doesn't work. You can find the project as attached.  
I would be very happy, if someone could tell me, what am I doing wrong.  

Thanks
[error.zip](https://github.com/material-components/material-components-web/files/2112823/error.zip)

**Comment by kfranqueiro** [comment]
This is from #2866, right? Sorry I didn't get around to testing the zip until today. (I was actually confused for a moment when I saw #2866 closed.)

I think what's actually missing from your setup is that you also need `@material/list`:

1. Run `npm install @material/list`
2. Add `@import "@material/list/mdc-list";` to your `index.scss`

You'll probably also want to include an element with the `mdc-drawer__toolbar-spacer` class (before your `mdc-list-group` element inside the drawer) to make the drawer items line up below the top app bar.

**Comment by bifunctor** [comment]
I will check and let you know. 

Thanks

**Comment by bifunctor** [comment]
Hi @kfranqueiro 
Now it works as expected. Thanks a lot.
Can you please mention on the website https://material.io/develop/web/components/drawers/ that the list have to be installed too? It would be nice for beginners.

Thanks

**Comment by kfranqueiro** [comment]
You're right, this should be mentioned in the docs. I'm going to open this so we can track that task.

**Comment by williamernest** [comment]
Reopening this issue so it can be tracked for doc updates.

**Comment by kfranqueiro** [comment]
This is being handled within updates to MDC Menu and MDC Drawer for 0.39.0. The update to Menu's docs is already in master, and the update to Drawer's docs will be merged into its feature branch soon.
