### ISSUE TITLE
Problems when more than one <select>

### ISSUE THREAD

**Issue by carlabalbontin** [material-components/material-components-web#2961]
When having more than one mdc-select only the first one works properly.
The others have problems with the label when an option is selected.

https://codepen.io/carlabalbontin/pen/XYZWMM

### What MDC Web Version are you using?

0.35.00

### What browser(s) is this bug affecting?

All

### What OS are you using?

macOS High Sierra version 10.13.3

### What are the steps to reproduce the bug?

Just adding more than one select-menu.

You can see the problem here:
https://codepen.io/carlabalbontin/pen/XYZWMM

### What is the expected behavior?

They should all work like the first select-menu.

### What is the actual behavior?

The second and third select-menu don't work properly. Mainly, the label doesn't change position or style when an option is selected

**Comment by kfranqueiro** [comment]
Your code isn't instantiating the 2nd or 3rd select; it's only ever accessing the first.

You can replace the JS in that codepen with the following:

```js
[].forEach.call(document.querySelectorAll('.mdc-select'), function(el) {
  const select = new mdc.select.MDCSelect(el);
});
```

**Comment by carlabalbontin** [comment]
Thanks!!

**Comment by carlabalbontin** [comment]
Thanks! it works with the unpkg.com links I used in codepen, but when working with npm, I get the following error:

`Uncaught ReferenceError: mdc is not defined
    at bundle.js:9015
    at NodeList.forEach (<anonymous>)
    at Object.<anonymous> (bundle.js:9014)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:306)
    at __webpack_require__ (bundle.js:20)
    at _typeof (bundle.js:63)
    at bundle.js:66`

**Comment by carlabalbontin** [comment]
Thanks! Works Perfectly!
