### ISSUE TITLE
Textfield — Styles for input text are not right.

### ISSUE THREAD

**Issue by juancabrera** [material-components/material-components-web#2962]
### What MDC Web Version are you using?

latest (textfield version `0.36.1`)

### What browser(s) is this bug affecting?

Seems to happen on all browsers, I tested it in:
- Chrome `Version 67.0.3396.62 (Official Build) (64-bit)`
- Safari `Version 11.0.3 (13604.5.6)`
- Firefox `59.0.2 (64-bit)`

### What OS are you using?
macOS High Sierra `10.13.3 (17D47)`

### What are the steps to reproduce the bug?

1. Go to this codepen: https://codepen.io/anon/pen/BVYQqO
2. Enter `name@email.com` on email field
3. Enter any password in the password field.
4. Observe that the styles are not the right ones.

### What is the expected behavior?

It should look like this (as per guidelines):
![screen shot 2018-06-19 at 4 25 22 pm](https://user-images.githubusercontent.com/355253/41622375-622ed13a-73dd-11e8-96ea-8185aaf40d33.png)

### What is the actual behavior?

But it's looking like this (see that the password field is also not looking right) :
![screen shot 2018-06-19 at 4 26 03 pm](https://user-images.githubusercontent.com/355253/41622414-79984e28-73dd-11e8-8e6f-9b1e4254f5c7.png)

**Comment by williamernest** [comment]
@juancabrera It works correctly if you're not using the fullwidth variant. The fullwidth variant isn't designed to be used with a floating label, and it should be used with a placeholder instead.

https://codepen.io/williamernest/pen/XYZRQX
