### ISSUE TITLE
MDC list divider in context of list menu does not follow the Material spec

### ISSUE THREAD

**Issue by Wolfr** [material-components/material-components-web#2969]
## Bugs

The spec states that list dividers in the context of a menu have a margin of 8px on top and bottom.

https://material.io/design/components/menus.html#specs

Proposed fix, change `.mdc-list-divider` to `.mdc-menu-divider`, since the behavior differs from regular list items.

````
.mdc-menu-divider {
  margin: 8px 0;
  ...
}
`````

### What MDC Web Version are you using?

0.36.0

### What browser(s) is this bug affecting?

All.

### What OS are you using?

macOS

**Comment by asyncLiz** [comment]
[This is fixed](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/_mixins.scss#L57) in the current version, closing.
