### ISSUE TITLE
Architecture: Make Next MDC-Web Release Web-y-er

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#297]
> our goal is to have a single UI library that can be used across the web. In order for this to be successful, we have to be able to integrate nicely with the myriad of frameworks

The integration to the myriad is via the lowest common denominator across [the Web](https://en.wikipedia.org/wiki/World_Wide_Web) which is HTML, CSS, and ECMA/JS.  It really boils down to sticking with those 3.  Web, not web.

> these components enable a reliable development workflow

What is a development workflow? I just need the basic `elements` in my UI - buttons, selects, checkboxes, inputs, dialogs, calendar pickers, accordions, etc.  Seems like I should be able to do simple `classList.addClass('mdl-checkbox`);`, for example.

**Comment by traviskaufman** [comment]
If you're interested in finding out the motivation behind why we've made the decision we've made for MDC-Web, I encourage to read our [architecture doc](../blob/master/docs/architecture.md). If you have specific concerns or issues regarding MDC-Web, please feel free to open them, but do bear in mind our [guidelines for filing an issue](https://github.com/material-components/material-components-web/blob/master/.github/ISSUE_TEMPLATE.md). Thanks.
