### ISSUE TITLE
Text field error state does not change as soon as input becomes valid

### ISSUE THREAD

**Issue by devvercer** [material-components/material-components-web#2988]
### What MDC Web Version are you using?
0.36.1

### What browser(s) is this bug affecting?
Chrome 66

### What OS are you using?
OS X

### What are the steps to reproduce the bug?

When a text field contains invalid input, the error state does not change until blur.

e.g. I have a text input with a pattern and maxlength.  When I enter invalid input and press tab then the lable and line change to red.

### What is the expected behavior?

I expected the label and line to change to red as soon as I typed an invalid input.  The text field documentation says that it uses HTML5 :invalid to provide validity styling.

https://material.io/develop/web/components/input-controls/text-field/

> Please describe what the component/code should be doing that it's not.

Perhaps it should use the :user-invalid HTML5 pseudo class to show red when I change the input to be invalid.

**Comment by moog16** [comment]
@devvercer we believe that not using :invalid was a conscious decision, because of the case where a user starts to type with a validation pattern will immediately be invalid. We will investigate if this still holds true or not.

**Comment by devvercer** [comment]
I believe that :user-invalid works to only show as invalid when the user
has modified the input to be invalid.

I actually use MDC with amp-html framework (for both amp and non-amp pages)
and it adds a class name "user-invalid" which I am currently using with a
sibling selector to show a error state.

**Comment by abhiomkar** [comment]
@devvercer Thanks for reporting this issue. I agree with @moog16 that not using `:invalid` was a conscious decision because of mentioned reason. The text-field doc where it mentions that it uses `:invalid` is outdated. I'll update the docs soon.

We sent this feedback to our designers for guidance on default behaviour of error state for text fields. Alternatively, I believe you can also use `set / get valid()` APIs to manually remove error state on input change.

**Comment by devvercer** [comment]
This holds for :invalid but not for :user-invalid.

Actually I am using MDC with the AMP framework - even on non-amp pages -
and it adds a class "user-invalid" as a polyfill
<https://www.ampproject.org/docs/reference/components/amp-form#:user-invalid/:user-valid>
which
I use to change the error styling of the MDC fields.  As soon as a user
types an invalid character (e.g. a letter in a phone number field) the
field turns red and the validation message shows. I find this much more
helpful to the user.  To accomplish this with MDC I needed to move the
validation messages to be siblings of the input element so I could write
sibling CSS selectors.

**Comment by abhiomkar** [comment]
Thanks for referencing `:user-invalid` spec. We've already added this issue to our tracker and we'll update here as soon as we've feedback from our designers.

**Comment by abhiomkar** [comment]
Using `setValid` API no longer ignores input validation by default. It can now be used to enable / disable error state on text field.

Here is an [example](https://github.com/material-components/material-components-web/blob/d4c230f30fc0a4b0318e8468d6c459fbb2af1cee/demos/text-field.html#L745) where text field removes the error state as soon invalid input is resolved.
