### ISSUE TITLE
TextField input layout breaks with box-sizing: border-box

### ISSUE THREAD

**Issue by jrajav** [material-components/material-components-web#2992]
### What MDC Web Version are you using?

0.36.1

### What browser(s) is this bug affecting?

Google Chrome 67

### What OS are you using?

Mac OS 10.13

### What are the steps to reproduce the bug?

Apply `box-sizing: border-box;` to the `<input>` element of a TextField - this is commonly done as a part of a reset style over all elements (for better absolute sizing in responsive layouts), e.g.:

```
* {
  box-sizing: border-box;
}
```

### What is the expected behavior?

The component lays out and appears normally.

### What is the actual behavior?

The component renders incorrectly due to the padding + height calculation:

<img width="227" alt="screen shot 2018-06-24 at 00 07 15" src="https://user-images.githubusercontent.com/2074135/41816144-9c93b67a-7742-11e8-9f58-bec966827146.png">

### Codepen

https://codepen.io/jrajav/pen/mKKKVN

**Comment by moog16** [comment]
This is actually already an issue https://github.com/material-components/material-components-web/issues/1455. We plan on getting all components to be border-box compatible. Thanks for opening the issue, but I'm going to close it since this is a duplicate.
