### ISSUE TITLE
Sticky navbar settings

### ISSUE THREAD

**Issue by champolot** [material-components/material-components-web#2999]
Guys is it possible to modify the settings of sticky nav bar in the latest material file? I'm trying to modify the setpoint in jquery to change it's background color. But it seems that it doesn't follow the jquery code. 
thanks for the help!

**Comment by moog16** [comment]
Are you talking about the fixed top app bar component? Which settings specifically are you trying to modify and what do you mean by setpoint? Also are you using a jQuery wrapper of our code? We do not write our components in jQuery.

Our styles for our components are built around Sass. If you want to change background color please use `mdc-top-app-bar-fill-color($color)` documented [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-top-app-bar#sass-mixins).

**Comment by champolot** [comment]
Yeah, you got it right. Everything's fine now. I did an alternatives. thanks for the help. GODBLESS
