### ISSUE TITLE
Investigate making Circular Progress Indicator Component

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#30]
Spec reference: https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

> Copied from https://github.com/google/material-design-lite/issues/4488

**Comment by TonySpegel** [comment]
Any progress regarding this? It's been 10 months already, what's stopping the team from realizing this feature?

**Comment by sgomes** [comment]
Sorry, @TonySpegel, I no longer work on this project. The team has a [Pivotal Tracker](https://www.pivotaltracker.com/n/projects/1664011) set up if you want to take a look at what they're working on, and when the feature you're interested in is coming up.

**Comment by TonySpegel** [comment]
@sgomes that's helpful I'll check that out :)

**Comment by MarioPeters** [comment]
https://docs.google.com/document/d/1o5lhOBykuZAgQC9mYGiouwpLFhY8I2TLBilSAplZOJ4/edit?usp=sharing

I started to develop the circular progress with single color. I use a SVG Tag in the HTML Markup. I don't know, if this is allowed or is it only allowed to use div Tags?

**Comment by danieldeppe** [comment]
Is there an update on this component?
Will MarioPeters proposal be reviewed?

The [Pivotal Tracker](https://www.pivotaltracker.com/n/projects/1664011) ticket does not seem to mention the investigation process.

**Comment by AndryHTC** [comment]
Some news about the @MarioPeters proposal?

**Comment by JVRibeiro** [comment]
The SVG version looks so smooth.

**Comment by jamesmfriedman** [comment]
If you're using React, here is an implementation that plays with MDC web. https://jamesmfriedman.github.io/rmwc/circular-progress

**Comment by jvalst** [comment]
Still not available as component next to linear progress?

**Comment by jimblackler** [comment]
Any progress on this at all?

**Comment by aluminick** [comment]
Any progress?

**Comment by makuc** [comment]
Still nothing? It's been years!

**Comment by TonySpegel** [comment]
@makuc I wouldn't count on any progress here. I am also not sure who this project is intended for and what purpose it fulfills. For the Web, there are already some Solutions such as Angular Material, or just WordPress Themes. Why would anyone use this? It's lacking Components, is missing Framework Integrations etc etc

**Comment by makuc** [comment]
@TonySpegel I guess. But I like how these components leave a nice structure in the DOM, instead of populating pretty much everything with various crap (spamming _span_, for instance) all over the place when using components...

I also really liked the `top-app-bar` from here, which can't be found so nicely in Angular Material, and the Menu Surface, which gives more freedom (though I guess I can force AM's mat-menu through nefarious means to behave in a similar way). I guess there are pros and cons for both...

**Comment by condinoaljoseph** [comment]
any news?

**Comment by allan-chen** [comment]
This is already available. Feel free to check out https://www.npmjs.com/package/@material/circular-progress or the webcomponent version (our downstream repo) [here](https://mwc-demos.glitch.me/)

**Comment by devwhatoplay** [comment]
@allan-chen  Thanks how about react component for this?
