### ISSUE TITLE
Floating label overlap when browser pre-fills text

### ISSUE THREAD

**Issue by liabru** [material-components/material-components-web#300]
### What MDC-Web Version are you using?

0.2.0

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

OSX

### What are the steps to reproduce the bug?

1. Go to the [mdc-textfield demo](http://material-components-web.appspot.com/textfield.html)
1. Type any text into the `Multi-line Textfields` example such that the label moves into position
1. Click outside of the multi-line textfield to blur it
1. Press the browser back button
1. Press the browser forward button
1. Observe that the browser has filled the `Multi-line Textfield` automatically with the text you typed before. Because of this the label is now overlapping the textfield content.

### What is the expected behavior?

1. The field should detect any browser pre-filled values and move the floating label

### What is the actual behavior?

1. The floating label overlaps the textfield content

### Any other information you believe would be useful?

There is already a section in the readme on [prefilled text](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#pre-filled-text-fields) which suggests adding the `mdc-textfield__label--float-above` class, but I feel this should be automatically handled by the component as it is a common case because the browser will pre-fill forms when navigating.

**Comment by traviskaufman** [comment]
Good catch! Definitely a bug.
