### ISSUE TITLE
Material Textfield for non-NodeJS apps...

### ISSUE THREAD

**Issue by AJ-Creations** [material-components/material-components-web#3000]
I use Material Design 2 with my non-nodeJS app. I need to use the material textfield (Outlined With Leading Icon) in my HTML project. You shows plain JavaScript codes for components and does not shows it for some. Please tell me, how do I add that component in my HTML project?

**Comment by moog16** [comment]
@AJ-Creations regardless of using webpack or another build tool, all our components work the same as the demo pages.

If you would like to import MDC Web without npm, you can use the CDN documented here: https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#quick-start. If you have an index.html file you can have a script tag like so:

```
<script src='https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js'></script>
```

**Comment by kfranqueiro** [comment]
We have [centralized documentation](https://github.com/material-components/material-components-web/blob/master/docs/importing-js.md) explaining different ways to import or reference MDC Web's JavaScript, which is linked from the documentation for Text Field.

The `import` syntax is specific to consuming our ES2015 sources and transpiling yourself (e.g. as detailed in the [getting started guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md)), but you can use global syntax if you are consuming our modules prebuilt, whether through your own toolchain or via unpkg as Matt indicated. (In the latter case you can alternatively use the AMD syntax if you use an AMD module loader and configure it to find the MDC Web packages.)

Note that our getting started guide assumes use of node and NPM to obtain and build JS and CSS, but you can use the final built resources with any server.
