### ISSUE TITLE
What is the correct way of making custom component styles for own brand?

### ISSUE THREAD

**Issue by jimbojetlag** [material-components/material-components-web#3004]
The readme file recommends creating a custom button like this:

```sass
@import "@material/button/mdc-button";

.foo-button {
  @include mdc-button-ink-color(teal);
  @include mdc-states(teal);
}
```

```html
<button class="foo-button mdc-button">
  Button
</button>
```

My question is, why should we still have `mdc-*` classes when making a custom brand? That is, if we are making frontend for a brand called `foo`, why cannot we do this?:

```sass
@import "@material/button/mdc-button";

.foo-button {
  @include mdc.button;
  @include mdc-button-ink-color(teal);
  @include mdc-states(teal);
}
```

```html
<button class="foo-button">
  Button
</button>
```

**Comment by moog16** [comment]
@jimbojetlag we also had this idea, but realized it would be a large breaking change for everyone. Our thoughts are as follows: Importing `@material/button/mdc-button` would include mixins that you could use to create custom classes like you have above. If another developer wanted to use the baseline it would force them to declare all classes with the appropriate mixin like so:

```
.mdc-button {
}
```

**Comment by jimbojetlag** [comment]
@moog16 the question was meant for applications built with mdc, and _not_ the mdc framework itself.

My point is, is it safe to use the approach explained in the original post, so that the application markup only uses brand specific css classes `foo-*`?

**Comment by kfranqueiro** [comment]
I believe Matt was indeed speaking from the perspective of applications using MDC Web, but I'll attempt to clarify.

We recommend adding custom classes for your own customizations for the sake of clarity in your own code. It's technically feasible to customize directly on e.g. `.mdc-button`, but customizing on e.g. `.foo-button` instead makes it immediately clear which styles are coming from MDC Web, vs. which styles are coming from your own customizations.

MDC Web emits baseline styles using the `mdc-*` classes. Omitting those classes would lose those styles. MDC Web's Sass mixins operate under the assumption that the baseline styles are already in place, and only override what they need to.

The baseline styles are emitted in the interest of ease of use. These could theoretically be exposed via mixins, but that could become more complex to use depending on the granularity at which mixins are exposed, especially when you get into complex components with subcomponents and variants, such as Text Field. Additionally, if we were to stop emitting baseline styles, you would get nothing out of the box without using Sass, whereas right now the baseline is fully usable without setting up a build toolchain.

It's also worth noting that some of MDC Web's JavaScript components also add/remove or examine `mdc-*` classes to reflect component state or determine what variant of a component is being used, so the `mdc-*` classes are important from a functional perspective as well.

**Comment by kfranqueiro** [comment]
Given no further response, I'm going to close this, in hopes that I've answered the original questions. Let us know if you have further questions. Thanks!
