### ISSUE TITLE
Building ES2015/JS with Gulp & Babel instead of Webpack

### ISSUE THREAD

**Issue by iamdann** [material-components/material-components-web#3005]
Hey!

Currently facing the following challenge: I'm trying to build ES2015 in a multi-module application with each module using it's own assets. The asset manager of my application loads certain assets based on the current page and applies its own custom filters to modify the CSS before it is send to the client. Hence the reason I can't make use of Webpack properly.  

My directory structure: 
```
.
+-- app
|    +-- modules
|        +--backend
|            +--js
|            +--es2015
|            +--sass
|            +--css
|        +--frontend
|            +--js
|            +--es2015
|            +--sass
|            +--css
+-- public
|    +--node_modules
|    +--js
|    +--es2015
|    +--sass
|    +--css
|    +--composer.json
|    +--gulpfile.json
``` 
I use gulp tasks to build assets across my whole application, the below tasks I use to transpile SASS which works like a charm!
_Note: I only use MDC on the backend of my application._ 

```
gulp.task('app-sass', function(){
    return gulp.src('sass/**/*.scss')
        .pipe(plumber())
        .pipe(sass())
        .pipe(gulp.dest('css'));
});

gulp.task('backend-sass', function(){
    return gulp.src('../app/modules/backend/sass/**/*.scss')
        .pipe(plumber())
        .pipe(sass({
            includePaths: glob.sync(
                path.join(__dirname, './node_modules/@material')
            ).map((dir) => path.dirname(dir))
        }))
        .pipe(gulp.dest('../app/modules/backend/css'));
});

gulp.task('frontend-sass', function(){
    return gulp.src('../app/modules/frontend/sass/**/*.scss')
        .pipe(plumber())
        .pipe(sass())
        .pipe(gulp.dest('../app/modules/frontend/css'));
});
```

But for some reason I can't figure out how to build ES2015 in the same way as shown above. I use the following task to transpile only the ES2015 in the `app/modules/backend/es2015` directory. 

```
gulp.task('backend-es2015', function(){
    return gulp.src('../app/modules/backend/es2015/**/*.js')
        .pipe(plumber())
        .pipe(babel({
            presets: ['babel-preset-es2015'].map(require.resolve)
        }))
        .pipe(gulp.dest('../app/modules/backend/js'))
});
```

The above successfully transpiles, but doesn't have the expected output: 
```
'use strict';

var _textfield = require('../../../../../public/node_modules/@material/textfield');

var textField = new _textfield.MDCTextField(document.querySelector('.mdc-text-field'));
```

Which obviously caused errors. Any help or ideas here? 

_Sorry if this is not the right place to post this.._

**Comment by moog16** [comment]
This is difficult to diagnose without a sample project. Could you supply a sample repo? I see in your 'backend-es2015' task that your source is `../app/modules/backend/es2015/**/*.js`. Shouldn't that be pointing to your node_modules directory?

**Comment by williamernest** [comment]
Close due to inactivity. Feel free to comment if you still need additional help.
