### ISSUE TITLE
Ripple does not grow/shrink from hover to pressed for Slider Spec

### ISSUE THREAD

**Issue by EstebanG23** [material-components/material-components-web#3006]
Follows #2978
Spec shows hover being 34px wide ripple and 48px wide pressed states. Adding a mixin to ripple could potentially help with this.

**Comment by bonniezhou** [comment]
Updates from the design: the ripple should remain the same size across all states. In a continuous slider, focus state will be shown by increase the size of the thumb from 12px to 20px. In a discrete slider, it will be shown by activating the value label. This is implemented in #3115 and #3307.
