### ISSUE TITLE
How to have dark instances of components

### ISSUE THREAD

**Issue by RhysyG** [material-components/material-components-web#3008]
Hi there,

In previous version of MDC, there was a class called mdc-theme--dark which you could add to the parent to change particular instances, like Tabs or a select in the toolbar. There was even component specific dark classes like mdc-tab-bar--theme-dark.

What is the recommended method of a accomplishing this in v0.36.0?

I can see there are accessible mixins so I can change a select with a new class, is this the correct way?

```
.custom-select {
	@include mdc-select-ink-color(white);
	@include mdc-select-label-color(white);
	@include mdc-select-focused-label-color(white);
	@include mdc-select-bottom-line-color(white)
	@include mdc-select-focused-bottom-line-color(white);
	@include mdc-select-hover-bottom-line-color(white)
}
```

Thanks.

### What MDC Web Version are you using?

v0.36.0

### What browser(s) is this bug affecting?

Chrome Version 67.0.3396.87 (Official Build) (64-bit)

### What OS are you using?

Mac OS High Sierra Version 67.0.3396.87 (Official Build) (64-bit)

### What are the steps to reproduce the bug?

> 1. Include MDC Select in Top App Bar

**Comment by moog16** [comment]
Currently the way in which you described how to achieve dark theme is the way to do it. We do plan on supporting dark theme later in Q4 of this year as described by the [Roadmap](https://github.com/material-components/material-components/blob/develop/ROADMAP.md#r19-r20-r21---forecast-for-september-november).
