### ISSUE TITLE
Text fields input mask

### ISSUE THREAD

**Issue by bifunctor** [material-components/material-components-web#3010]
Hi all 

How can I define on [Text fields](https://material.io/design/components/text-fields.html) an input mask.  For example https://www.xaprb.com/html-input-mask/. 

Thanks

**Comment by moog16** [comment]
@bifunctor you can use the `pattern` attribute on an `<input>` tag to ensure that the correct characters are entered. Please see this documentation under `Attributes` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input. Let use know if that helps.
