### ISSUE TITLE
Link to Web Tutorials is Broken - 404

### ISSUE THREAD

**Issue by co-category** [material-components/material-components-web#3018]
Getting a 404 when hitting this URL

https://material.io/mio-collections/developer-tutorials/#web/

**Comment by NajeraP95** [comment]
are you looking for https://material.io/collections/developer-tutorials/#web ?

**Comment by kfranqueiro** [comment]
Thanks for pointing this out. We've reported this to the material.io site team which has their own tracker, so I'm going to close this here.

FYI, material.io has feedback links at the bottom of most pages where you can report issues like this. (If you don't see it at the bottom of the page, also check the navigation drawer.)
