### ISSUE TITLE
Typography: Remove line-height from typography

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#3021]
Remove `line-height` from our typography package. If a component uses `line-height` for text alignment, we should move the `line-height` value into that component or refactor the component to not depend on `line-height` for alignment.

**Comment by lynnjepsen** [comment]
We probably cannot do this until we finish #3038 , and update all components to use the `:before` baseline alignment technique.

**Comment by abhiomkar** [comment]
`mdc-typography()` mixin now supports `$exclude-props` param that can be used to exclude line-height when necessary.
