### ISSUE TITLE
Select component wont work in React context

### ISSUE THREAD

**Issue by BartJanvanAssen** [material-components/material-components-web#3030]
I just tried out this package using the selectbox (which is not yet in the react wrap lib of MDC), but keeps on failing... Can anyone get me a bit further? JavaScript is working, the only issue lies at the scss stuff

Reproduction repo: https://github.com/BartJanvanAssen/issue-MDC-select
branch: master
steps to take: 
1. npm run start see build working without styles on the select box.
2. uncomment the style import in: App.scss (@import "@material/select/mdc-select";)
3. build fails to load several sub packages + result is no style applied.

Lookin forward to this working :)

**Comment by williamernest** [comment]
@BartJanvanAssen Have you checked out the react getting started guide for modifying your create react app to work with our sass ? Step 2 details how to set up Sass when using CRA. 

https://github.com/material-components/material-components-web-react/blob/master/docs/getting-started.md

**Comment by kfranqueiro** [comment]
I would add that we are hoping to wrap MDC Select within the MDC React repository relatively soon (see tentative schedule in the MDC React [roadmap](https://github.com/material-components/material-components-web-react/blob/master/ROADMAP.md)).

Meanwhile, has Will's comment helped you get further?

**Comment by kfranqueiro** [comment]
Given no further comments, I'm going to go ahead and close this issue.
