### ISSUE TITLE
Using MDC with ReactJS

### ISSUE THREAD

**Issue by priyesh-diukar** [material-components/material-components-web#3033]
Hello,

I am thinking of using mdc as a base for our product development. Thing is lot of our recent code has react components in it. I want to understand how complex it can be to use MDC with react.
OR
Can i just use an extended framework like [material-components-web-react](https://github.com/material-components/material-components-web-react).
Any form of input will be highly appreciated.
Thanks

**Comment by williamernest** [comment]
@priyesh-diukar Feel free to use our [React](https://github.com/material-components/material-components-web-react) components. You can also wrap our core components in React without too much trouble. You can checkout our [Catalog](https://github.com/material-components/material-components-web-catalog) repo for some examples.
