### ISSUE TITLE
Top App Bar does not show action items on the right hand side

### ISSUE THREAD

**Issue by bifunctor** [material-components/material-components-web#3034]
Hi all 

I am using [Top App Bar](https://material.io/develop/web/components/top-app-bar/) as following:   

```
    <header class="mdc-top-app-bar">
      <div class="mdc-top-app-bar__row">
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
          <a href="#" class="mdc-top-app-bar__navigation-icon">
            <i class="fas fa-align-justify"></i>
          </a>
          <span class="mdc-top-app-bar__title">Title</span>
        </section>
        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">
          <a href="#" class="mdc-top-app-bar__navigation-icon">
            <i class="fab fa-adn"></i>
          </a>
        </section>
      </div>
    </header>
```  

as result I've got: 

![2018-07-05_15-02-50](https://user-images.githubusercontent.com/34632165/42325067-6161e3c0-8065-11e8-8dcc-9281755edc77.png)

as you can see on the picture, the icon  `<i class="fab fa-adn"></i>` on the right hand side is missing. 

The project files is on https://github.com/bifunctor/mderror. 

Thanks

**Comment by williamernest** [comment]
@bifunctor Thanks for filing this issue. The top app bar is at 100% width and when pushed over from the drawer the icons end up outside of the viewport. This is being tracked in #2750 .

**Comment by bifunctor** [comment]
Awesome. Thanks a lot.
