### ISSUE TITLE
New Drawer RTL has Top App Bar notch in Linux for scrollbar

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#3043]
I believe this is a Chrome/Linux bug. I reproduced in a [Codepen](https://codepen.io/anon/pen/PagjVx). Notice the top right notch where the scrollbar exists in LTR. 

Filed this issue with Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=860816

**Comment by kfranqueiro** [comment]
@moog16 can you try reproducing what you originally saw in drawer, against MDC Drawer in 0.39.0? I just tested the Drawer demos in RTL in Chrome on Windows (which also shows the issue in your codepen) and didn't seem to notice an issue.

**Comment by moog16** [comment]
@kfranqueiro confirmed - codepen is still broken, but drawer does not show that effect. Closing
