### ISSUE TITLE
System-itize the shape foundation (just like for color and typography)

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#3046]
[Material Foundation](https://material.io/design/foundation-overview/#addition) talks about how color and typography can be customized at a global level, so that all Material Components inherit that global customization. We implemented this in color with mdc-theme global Sass variables. We also implemented this in typography with mdc-typography global Sass variables. Now we want to implement a new set of global Sass variables for customizing shape of all components.

Note that there may be some future work done in MDC Web around shapes, but see #3045 for more details

**Comment by acdvorak** [comment]
Superseded by #3176 and #3175
