### ISSUE TITLE
Select menu shows wired triangle

### ISSUE THREAD

**Issue by bifunctor** [material-components/material-components-web#3055]
Hi all 
I am trying to use https://material-components.github.io/material-components-web-catalog/#/component/select and as output I've got: 

![screenshot from 2018-07-11 20-44-18](https://user-images.githubusercontent.com/34632165/42592880-3d5a25ba-854b-11e8-8614-9ad7c02a2e4a.png)

You can find the example here: 
https://github.com/bifunctor/mderror

Thanks

**Comment by williamernest** [comment]
@bifunctor  I added the following loader config to your repo and it ended up working for me. 
```js
          {
            loader: "postcss-loader",
            options: {
              plugins: () => [autoprefixer({
                'browsers': ['> 1%', 'last 2 versions']
              })],
            }
          }
```

This should be enough to unblock you, but I think there's still some investigation as to why this happens sometimes and not others.

**Comment by bifunctor** [comment]
Thanks a lot.
