### ISSUE TITLE
Put all new tabs catalog content in a subdirectory

### ISSUE THREAD

**Issue by patrickrodee** [material-components/material-components-web#3056]
>The paths for each of these components should probably live under a subdirectory rather than having multiple top-level tab things in the site navigation. Maybe something to consider when we finish off with tab bar.
Maybe we could move the existing tabs to tabs/tabs-legacy or something, assuming we're not going to remove its docs from the site immediately.

https://github.com/material-components/material-components-web/pull/2577#discussion_r197528927

>+1 to having a catalog/tabs category
You can do that in a follow up PR for all the tabs stuff if you want
But I think we should remove the old tabs immediately

https://github.com/material-components/material-components-web/pull/2577#discussion_r200723160

(Clarification: this is simply referring to the paths specified in the front-matter at the top of the READMEs)

**Comment by kfranqueiro** [comment]
This task should also include moving or de-listing the original mdc-tabs from site navigation, to make room for new tabs to have a top-level entry with child entries.

**Comment by kfranqueiro** [comment]
Closing this since it's fixed on the branch that will be merged into master once the new tabs components are complete.
