### ISSUE TITLE
Slider: Update handlers to be initialized and destroyed within the component

### ISSUE THREAD

**Issue by EstebanG23** [material-components/material-components-web#3061]
Remove the [de]registerHandler methods from the adapter
Register all handlers in the index.js/component
Remove the private proxy handlers from the foundation
Update the handlers to have improved business logic that ensures the only do work if necessary
Replace all dynamic handler registrations with some Boolean flags.
Update tests to reflect changes

Follows #2977

**Comment by asyncLiz** [comment]
@EstebanG23 is this still needed?

**Comment by EstebanG23** [comment]
Out of date issue.
