### ISSUE TITLE
Top App Bar: any way to show/hide or slideDown/slideUp ?

### ISSUE THREAD

**Issue by ginlime** [material-components/material-components-web#3063]
### What MDC Web Version are you using?

0.37.0

### What browser(s) is this bug affecting?

Chrome 67.0.3396.99 64bit

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

### What OS are you using?

Windows 7 Professional Service Pack 1

## I ask...
Please tell me the way to show/hide or slideDown/slideUp Top App Bar at any time I want.
Not on scrolling or not on resizing.
I could not find any method for doing so.

**Comment by abhiomkar** [comment]
@ginlime You can manually add / remove a class name on Top App Bar's root element to show or hide.

Here is an example on [codepen](https://codepen.io/abhiomkar/pen/QBEyGX).

**Comment by ginlime** [comment]
@abhiomkar Thanks a lot!
