### ISSUE TITLE
How to use this with angular 6?

### ISSUE THREAD

**Issue by bono95zg** [material-components/material-components-web#3065]
I cant get this to work (I'm new to angular). I installed it and installed sass and imported min.css and min.js (in angular.json). Now I put 

.button {
  @include mdc-ripple-surface;
  @include mdc-ripple-radius-bounded;
  @include mdc-states;
}

and get error: "No mixin named mdc-ripple-surface". How do I make it work? Should I import something in app module?

**Comment by williamernest** [comment]
@bono95zg Here's an example repo showing how to use the MDC Web components in Angular. 
https://github.com/williamernest/mdc-web-angular-example

You may want to consider using an already wrapped library such as Angular MDC.
https://github.com/trimox/angular-mdc-web

This comment explains the initial Angular setup required. 
https://github.com/material-components/material-components-web/issues/3036#issuecomment-403130482

**Comment by bono95zg** [comment]
ty
