### ISSUE TITLE
TextField does not respect CSS var --mdc-theme-primary

### ISSUE THREAD

**Issue by kennylevinsen** [material-components/material-components-web#3066]
TextField no longer respects --mdc-theme-primary.

Specifically, `.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label` no longer references the CSS variable, and instead use the default purple primary color directly.

### What MDC Web Version are you using?

Bug first occurred in 0.35.0, and persists in 0.37.0.

Last working version was 0.34.1

### What browser(s) is this bug affecting?

Tested in Chrome

### What OS are you using?

Fedora 28

### What are the steps to reproduce the bug?

0.34.1 (working) codepen: https://codepen.io/anon/pen/oMjBPq
0.35.0 (not working) codepen: https://codepen.io/anon/pen/rrOjbm
0.37.0 (not working) codepen: https://codepen.io/anon/pen/vaNgMQ

### What is the expected behavior?

That the primary color is observed like in 0.34.1.

### What is the actual behavior?

The default primary purple color is observed from 0.35.0 and onwards.

### Any other information you believe would be useful?

444f14fc8aa70ebdd0e4a4d5b6d6d1779fe31ad3 looks suspicious, but I have not bisected my way between the releases.

**Comment by kennylevinsen** [comment]
This is likely due to not being able to apply the .87 alpha channel to CSS var that already contains a color.

A solution to this could be to specify the color in a different way:

```css
:root {
    --mdc-theme-primary: 240, 240, 240; /* arbitrary color */
}

.something {
    color: rgba(var(--mdc-theme-primary), .87);
}
```

**Comment by TANJX** [comment]
I have the same issue too; I overrode the original property

**Comment by abhiomkar** [comment]
@kennylevinsen Thanks for filing this issue.

`mdc-theme-prop` mixin currently only supports colors with no alpha value on theme property values (primary, secondary, on-surface etc). But, Text field component has alpha values mixed with the baseline colors which passed onto `mdc-theme-prop` that renders only color style directly without using CSS variables.

Added this to our tracker to make changes to out theme component to support using CSS variables.

**Comment by kvdheuvel** [comment]
This bug is still visible in 0.41.0.

We fixed this locally by setting the color using the mdc theme props:
`.mdc-text-field--focused {
	&:not(.mdc-text-field--disabled) {
		.mdc-floating-label {
			color: $mdc-theme-primary;
			color: var(--mdc-theme-primary, $mdc-theme-primary);
		}
	}
}`

This problem is also visible with the mdc-select labels and ripple, we have used te following to adjust that part:
`mdc-select--focused {
		&:not(.mdc-select--disabled) {
			.mdc-floating-label {
				color: $mdc-theme-primary;
				color: var(--mdc-theme-primary, $mdc-theme-primary);
			}
			.mdc-line-ripple {
				background-color: $mdc-theme-primary;
				background-color: var(--mdc-theme-primary, $mdc-theme-primary);
			}
		}
	}`

Within the mdc-select we can also see that the mdc-select__dropdown-icon does nog change it's colors because it is set with an svg as background. Maybe this should be changed to use an icon (material-icons) so we can change it's color based on the theming.

**Comment by acdvorak** [comment]
Superseded by #4431.
