### ISSUE TITLE
Unable to host page built with MDC on Heroku

### ISSUE THREAD

**Issue by jakcharvat** [material-components/material-components-web#3079]
Hello all,

I am new to using Material Components Web and have just recently finished building my first web page with MDC web. My project is set up the way it is described in the [Getting Started guide on material.io](https://material.io/develop/web/docs/getting-started/). I got my Heroku set up according to the [Heroku Getting Started guide](https://devcenter.heroku.com/articles/getting-started-with-nodejs). My app is deployed and webpack builds successfully, however, it doesn't go live on Heroku as I am unable to find a way to bind webpack to the dynamic port and I always receive `Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`. 

I would greatly appreciate any suggestions. My project is available [here](https://github.com/jakcharvat/centrelineGenerator). I have tried many different approaches, and haven't been able to come to anything that would work. 

Thank you for any help in advance.

**Comment by abhiomkar** [comment]
Congratulations on building your first web page on MDC Web!

I wouldn't run webpack dev server directly on Heroku server. I would suggest to deploy your project as static webpage after your project is built using webpack. It is much faster and in-expensive to serve static files than running a dev server. Hope this helps.

Also, Procfile seems to be missing from your project.

**Comment by kfranqueiro** [comment]
IIUC, Heroku defines a `$PORT` environment variable which references the port it exposes. If that's the case, you should be able to update the `start` script in `package.json` to `webpack-dev-server --port $PORT`.

However, Abhinay is correct in that the preferred approach would be to build production assets so you can host them on any HTTP server; you shouldn't need to use `webpack-dev-server` for a final deployment.

I logged #3113 to cover this in our getting started guide, as I suspect multiple users have been confused by this.

**Comment by jakcharvat** [comment]
Thank you for the replies @abhiomkar and @kfranqueiro. I'll go ahead and build the static JS and CSS, and deploy that. Just wondering, is there an easier way than building the web page and copying the code from the dev console into new files?

**Comment by abhiomkar** [comment]
I'm not sure if I understand your question completely. What do you mean by dev console? As Ken mentioned, the issue filed to update getting started docs may clarify some of your questions.

**Comment by jakcharvat** [comment]
By dev console I mean the CTRL+Shift+I or f12 panel in a web browser. Basically, my question was how can I build the static webpage?

**Comment by jakcharvat** [comment]
@abhiomkar By dev console I mean the CTRL+Shift+I or f12 panel in a web browser. Basically, my question was how can I build the static webpage?
