### ISSUE TITLE
Shapes not being applied

### ISSUE THREAD

**Issue by jvbraganca** [material-components/material-components-web#3081]
### What MDC Web Version are you using?

"@material/shape": "^0.35.0"

### What browser(s) is this bug affecting?

Google Chrome 67.0.3396.99

### What OS are you using?

Windows 10 Version 1803 (OS Build 17134.165)

### What are the steps to reproduce the bug?

Followed the first steps listed on material.io and on the repository on GitHub, then tried to reproduce the example listed on https://material.io/develop/web/components/shape/ (Running npm start)

Screenshot:
http://prntscr.com/k6vatz

https://codepen.io/jvbraganca/pen/wxMXVy

### What is the expected behavior?

The shape on corners appears.

### What is the actual behavior?

Shapes not applied

**Comment by kfranqueiro** [comment]
I reproduced your example and it turns out that all you're missing is an import for `@material-shape/mdc-shape`. Add that to your `app.scss` and the example should then work.

I realized this should be indicated in the README, so I'll send a PR shortly to update it.
