### ISSUE TITLE
Buttons and input fields appear over/through toolbar

### ISSUE THREAD

**Issue by alltom** [material-components/material-components-web#315]
### What MDC-Web Version are you using?

23a0a1235e259dd2f520a9cec5e01200e2ec370b

### What browser(s) is this bug affecting?

Chrome 58.0.3013.3 (Official Build) dev (64-bit)

### What OS are you using?

macOS Sierra 10.12.3 (16D32)

### What are the steps to reproduce the bug?

1. Add a fixed toolbar by copying the demo.
2. Add mdc-buttons, mdc-textfields, etc to the body.
3. Scroll.

### What is the expected behavior?

The toolbar occludes the buttons and text fields.

### What is the actual behavior?

They show through:

![toolbar z-index](https://cloud.githubusercontent.com/assets/1678/23142311/31908c98-f770-11e6-96e4-766878c810bc.gif)

But regular text does not.

**Comment by Garbee** [comment]
We need a z-index on the toolbar. For some reason elements are being layered up that shouldn't (clearly) be.

**Comment by traviskaufman** [comment]
Thanks for reporting! Looks like relatively-positioned elements are showing up on top of a fixed-position toolbar _shrugs_.

**Comment by alltom** [comment]
Thank you. :)
