### ISSUE TITLE
Getting started guide build failed

### ISSUE THREAD

**Issue by eksea** [material-components/material-components-web#3169]
## Bugs

I got the error below when i follow the getting started guide.
ERROR in ./app.scss
    Module build failed: C:\Users\Jack\myworkspace\github\material-components-web-codelabs\mdc\app.scss:1
    exports = module.exports = require("./node_modules/_css-loader@0.28.11@css-loader/lib/css-base.js")(false);
                                                                                                       ^

    TypeError: require(...) is not a function
        at C:\Users\Jack\myworkspace\github\material-components-web-codelabs\mdc\app.scss:1:100
        at ContextifyScript.Script.runInContext (vm.js:59:29)
        at ContextifyScript.Script.runInNewContext (vm.js:65:15)
        at Object.extractLoader (C:\Users\Jack\myworkspace\github\material-components-web-codelabs\mdc\node_modules\_extract-loader@1.0.2@extract-loader\lib\extractLoader.js:88:12)
     @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://localhost:8081 ./app.scss

### What MDC Web Version are you using?

> It's not the bug of MDC, but the bug of the doc.

**Comment by abhiomkar** [comment]
This seems to be related to [issue #50](https://github.com/material-components/material-components-web-codelabs/issues/50) filed in codelabs. Closing this one.
