### ISSUE TITLE
Integrate shape system API with components

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#3176]
Integrate shape system APIs with below components first:

- [x] Buttons (#3547)
- [x] Cards (#3547)
- [ ] Extended FAB (#3552)
- [x] Chips (#3547)

We should ultimately aim to replace any corner-radius mixins with shape mixins, which additionally includes the following components;

- [x] Dialog (#3552)
- [x] Drawer (item) (#3547)
- [x] Image List (#3547)
- [x] List (item) (#3547)
- [x] Menu Surface (#3552)
- [x] Notched Outline (#3552)
- [x] Select (#3552)
- [x] Text Field (#3552)
- [x] Top App Bar (Short) (#3552)

**Comment by kfranqueiro** [comment]
Resolved via #3547 and #3552.
