### ISSUE TITLE
Infrastructure: Organize screen test specs in container, viewport, and layout.

### ISSUE THREAD

**Issue by hastebrot** [material-components/material-components-web#3183]
@acdvorak First off all: great work in the screenshot test infrastructure!

I wondered if the class names of the specs can be improved. I found `test-grid` a bit confusing since `test-cell` itself used a grid pattern.

So, I propose to use `test-container`, `test-viewport`, and `test-layout` instead.

Current naming:

~~~html
<body class="test-body mdc-typography">
  <main class="test-main test-main--mobile-viewport">
    <div class="test-grid">
      <div class="test-cell test-cell--button">
~~~

Proposed naming:

~~~html
<body class="test-container mdc-typography">
  <main class="test-viewport test-viewport--mobile">
    <div class="test-layout test-layout--flow">
      <div class="test-cell test-cell--button">
~~~

What do you think?

**Comment by acdvorak** [comment]
Hey @hastebrot, thanks for the kind words! 😄 

I totally agree that the existing names are confusing, and I like your proposed names much better.

If you want to send me a PR, I'd be happy to review it! Or I can do it if you prefer.

OOC, how did you come across the screenshot tests, and how are you using them? Do you run them on the MDC Web repo, or are you planning to fork them and run them on your own code? Just trying to understand your use case better 🙂 

Thanks!

**Comment by hastebrot** [comment]
>how did you come across the screenshot tests, and how are you using them?

@acdvorak Sorry for the late reply.

I just browsed the repository. I always liked the idea of screenshot tests since I found fifoci (a screenshot test tool used by the dolphin emulator for gamecube and wii) several years ago.

A month ago I've created html test fixtures inspired by those in this repository and quickly wrote a screen test tool. It uses puppeteer and only runs locally, i.e. the snapshot images are in our repository. We'll probably abondon our test tool and switch to yours, because we want to test on more browsers than chrome and need a more fault resistent test tool (we have no test retries and such). I think it is also possible to provide start parameters to use a custom remote storage for the reports and images.

This weekend I've optimized some parts of my test tool. Instead of 53.28s it now only takes 8.56s (best of three runs). I wanted to share some insights, because your screenshot test tool at least also uses the jimp image library.

**Capture:** It now uses puppeteer-cluster [0] and runs the capture within separate browser processes. It uses the new `defaultViewport` option introduced in puppeteer 1.7.0. Before this option existed we had to call some internal functions of chrome to reset the device pixel ratio (macOS retina displays have 2.0x) and the viewport (code below for reference).

**Compare:** Instead of jimp's `autocrop()` function it now uses puppeteer and requests the rectangle of `<main>` via `getBoundingClientRect()`. It then provides the rectangle bounds as `clip` parameter to puppeteer's `screenshot()`. Instead of `Jimp.parse()` it now uses `sharp(imageBuffer)`. Sharp [1] allows faster reading and writing of PNG image buffers than `pngjs`. We directly use pixelmatch on the raw sharp image buffers.

~~~js
async function clearDeviceMetrics(page: puppeteer.Page) {
  // https://github.com/GoogleChrome/puppeteer/issues/2372
  // @ts-ignore
  const client = page._client

  await client.send("Emulation.clearDeviceMetricsOverride")
}

async function resizeWindowBounds(browser: puppeteer.Browser, bounds) {
  // https://github.com/GoogleChrome/puppeteer/issues/1183
  // @ts-ignore
  const connection = browser._connection

  // find a tab window id.
  const targets = await connection.send("Target.getTargets")
  const { targetId } = targets.targetInfos[0]
  const { windowId } = await connection.send("Browser.getWindowForTarget", {
    targetId
  })

  // resize the browser.
  await connection.send("Browser.setWindowBounds", {
    bounds,
    windowId
  })
}
~~~

[0] https://github.com/thomasdondorf/puppeteer-cluster
[1] https://github.com/lovell/sharp

**Comment by hastebrot** [comment]
Here's the code I used to compare the performance of jimp and sharp. When `snapshot.png` and `golden.png` have a lot of differences the duration increases (I think pixelmatch slows it down). In the code I compare `snapshot.png` with `snapshot.png`. Jimp 0.3.3 recently introduced a way to directly provide a raw buffer, but it only worked for me with PNG buffer and not with sharp raw buffer.

~~~js
const fs = require("fs")
const path = require("path")
const jimp = require("jimp")
const sharp = require("sharp")
const png = require("pngjs").PNG
const pixelmatch = require("pixelmatch")

;(async () => {
  const diffImagePath = "diff.png"
  const imagePath1 = "snapshot.png"
  // const imagePath2 = "golden.png"
  const imagePath2 = imagePath1

  const iterations = 50
  for (let index = 0; index < iterations; index += 1) {
    await sharpDiff(imagePath1, imagePath2, diffImagePath)
    // await jimpDiff(imagePath1, imagePath2, diffImagePath)
  }
})()

export async function sharpDiff(imagePath1, imagePath2, diffImagePath) {
  const s = sharp(imagePath1)
  const s1 = sharp(imagePath2)
  const m = await s.metadata()
  const b = await s.raw().toBuffer()
  const b1 = await s1.raw().toBuffer()

  const d = new png({ width: m.width, height: m.height })
  const p = pixelmatch(b, b1, d.data, m.width, m.height, { threshold: 0.01 })
  // d.pack().pipe(fs.createWriteStream(fd))

  const d1 = sharp(d.data, {
    raw: { width: m.width, height: m.height, channels: 4 }
  })
  await d1.toFile(diffImagePath)
}

export async function jimpDiff(imagePath1, imagePath2, diffImagePath) {
  const i = await jimp.read(imagePath1)
  const i1 = await jimp.read(imagePath2)
  const { image: d, percent: p } = jimp.diff(i, i1, 0.01)
  await d.write(diffImagePath)

  // new jimp({ data: b.data, width: m.width, height: m.height }, (err, image) => {
  //   console.log(err, image)
  // })
}
~~~

**Comment by acdvorak** [comment]
@hastebrot Nice! I'll look into migrating from Jimp to Sharp. Thanks for the tip!

I would love to eventually move our screenshot testing infrastructure to its own repo and npm package, but I'm not sure when I'll have time to do that.

Are you planning to just copy/paste our code into your project? If so, let me know what you end up needing to change, so I can make our code more generic and reusable too.

Thanks! 😀

**Comment by acdvorak** [comment]
Unfortunately it looks like we can't use Sharp because it depends on zlib `1.2.9`.\
Travis CI runs Ubuntu 14.04 Trusty, which only supports zlib `1.2.8`.

https://travis-ci.com/material-components/material-components-web/jobs/147061679

```
Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found
(required by /home/travis/build/material-components/material-components-web/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
```

From [#3598](https://github.com/material-components/material-components-web/pull/3598/commits/46b38b99bd3c70f36723298c1e04e6302def5731)
