### ISSUE TITLE
Improve branch coverage

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#319]
Our branch coverage is getting close to the 95% lower limit in some browsers: 

```
=============================== Coverage summary ===============================
Statements   : 98.22% ( 1379/1404 )
Branches     : 95.29% ( 506/531 )
Functions    : 98.02% ( 642/655 )
Lines        : 98.19% ( 1354/1379 )
================================================================================
```

We should proactively add some tests to existing code.

**Comment by amsheehan** [comment]
Seems like this would be a nice to have, but might be worth looking at: https://coveralls.io

**Comment by traviskaufman** [comment]
@amsheehan looks like [CodeCov is recommended over coveralls](https://www.slant.co/versus/7928/7929/~coveralls_vs_codecov) ? but open to either

**Comment by amsheehan** [comment]
heh nice! I have actually never seen that site before.
