### ISSUE TITLE
Avoid running tests when unnecessary

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3190]
The screenshot testing infrastructure includes logic to skip uploading/testing/diffing altogether if no files changed that warrant it.

We should do something similar for our other test scripts that are invoked by CI:

* [ ] Only run lint if .js or .css is changed
* [ ] Only run unit tests when .js is changed
* [ ] Only run closure tests when .js is changed
* [ ] Only run site-generator test when .md is changed

It should be possible to do this in a way that doesn't rely on git credentials (and is thus usable for forks as well as core PRs), by using `git diff <PR target>...<PR branch>` and scanning the list of files that changed. If we reuse simple-git (which the screenshot tests and the cherry-picking script for patch releases both use already), it looks like it'd be possible to use its `diffSummary` API which returns an object with a `files` array.

**Comment by moog16** [comment]
Closing since we have it implemented in the file `travis-env-vars`.
