### ISSUE TITLE
Incorrect class name used for mdc-toolbar-fixed-adjust

### ISSUE THREAD

**Issue by zeromalist** [material-components/material-components-web#320]
### What MDC-Web Version are you using?

v0.5.0

### What browser(s) is this bug affecting?

Every.

### What OS are you using?

4.9.9-1-ARCH

### What are the steps to reproduce the bug?

Follow the [fixed toolbar documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-toolbar#fixed-toolbars).

### What is the expected behavior?

Add top margin to the siblings of the fixed toolbar.

### What is the actual behavior?

No added margin caused by two typos in the documentation.

### Any other information you believe would be useful?

I can quickly provide a pull request to fix this.

**Comment by traviskaufman** [comment]
This actually seems like it's a bug in our toolbar code. That class _should_ be `mdc-toolbar-fixed-adjust`, since the `__` modifier is reserved for children of the MDC-Toolbar component (e.g. `mdc-toolbar__section`). We should be able to make a hotfix patch release for this today.

**Comment by zeromalist** [comment]
Provided a PR #321 .

**Comment by Hardtack** [comment]
It seems that you did not update CSS file before publishing mdc-toolbar@0.1.1

SCSS file's class name was updated, but CSS file was not. 😢

``` shell
$ cat node_modules/@material/toolbar/package.json | ack version
  "version": "0.1.1"

$ cat node_modules/@material/toolbar/dist/mdc.toolbar.css | ack mdc-toolbar
.mdc-toolbar {
    .mdc-toolbar {
  .mdc-toolbar__section {
    .mdc-toolbar__section--align-start {
    .mdc-toolbar__section--align-end {
    .mdc-toolbar__section .mdc-toolbar__title {
.mdc-toolbar--fixed {
.mdc-toolbar__fixed-adjust {
    .mdc-toolbar__fixed-adjust {

$ cat node_modules/@material/toolbar/mdc-toolbar.scss | ack mdc-toolbar
$mdc-toolbar-height: 64px;
$mdc-toolbar-mobile-height: 56px;
$mdc-toolbar-padding: 24px 16px;
$mdc-toolbar-mobile-padding: 16px;
$mdc-toolbar-mobile-breakpoint: 599px;
.mdc-toolbar {
  height: $mdc-toolbar-height;
  padding: $mdc-toolbar-padding;
  @media (max-width: $mdc-toolbar-mobile-breakpoint) {
    height: $mdc-toolbar-mobile-height;
    padding: $mdc-toolbar-mobile-padding;
    .mdc-toolbar__title {
.mdc-toolbar--fixed {
.mdc-toolbar-fixed-adjust {
  margin-top: $mdc-toolbar-height;
    margin-top: $mdc-toolbar-mobile-height;
```
