### ISSUE TITLE
Select box without label misses hover and focus state

### ISSUE THREAD

**Issue by pfecht** [material-components/material-components-web#3230]
### What MDC Web Version are you using?

@material/select 0.37.1

### What browser(s) is this bug affecting?

All

### What are the steps to reproduce the bug?

* Create an outlined select box without a label
* Hover over or focus the element

https://codepen.io/pfecht/pen/djzVLX

### What is the expected behavior?

The expected behavior would be a user feedback like a blue border color.

### What is the actual behavior?

No hover or focus state

### Any other information you believe would be useful?

* Outlined selects with label have a blue and bold border.
* The notched outline does not calculate the SVG path if no label is provided.
* For textfields, the hover and focus state results in a blue color. This behavior is implemented in the text field package. Why not a blue border and why not generalize this behavior in the notched-outline package?

**Comment by abhiomkar** [comment]
Thanks @pfecht for filing this issue. I've added this to our tracker to make label optional so the select outline would still be highlighted on focus.
