### ISSUE TITLE
Looping through a group buttons to add a ripple to each with querySelectorAll

### ISSUE THREAD

**Issue by mustafa-x** [material-components/material-components-web#3236]
I have a few buttons on screen and would like to add a ripple effect to them all by doing something like

```
rippleElements = document.querySelectorAll('.foo-button')
mdc.ripple.MDCRipple.attachTo(rippleElements);
```

But sadly this doesn;t work and I am forced to do;

```
var step;
var button; 
for (step = 0; step < 4; step++) {
  button = ".button"+step;
  mdc.ripple.MDCRipple.attachTo(document.querySelector(button));
}

```

Can we add querySelectorAll, here is a working example on codepen https://codepen.io/mustafa-x/pen/XBaway

**Comment by williamernest** [comment]
Can you query for all the mdc-buttons ? 

```[].slice.call(document.querySelectorAll('.mdc-button')).forEach((ele) => mdc.ripple.MDCRipple.attachTo(ele));
```
https://codepen.io/anon/pen/rrzXRp

**Comment by mustafa-x** [comment]
ooo that is sweet 👍

**Comment by williamernest** [comment]
@mustafa-x Iterating is going to be faster. You can also choose to use the auto-init package by adding the `data-mdc-auto-init="MDCRipple"` property onto each div and then calling `mdc.autoInit()`.

https://codepen.io/williamernest/pen/jpGRMN
https://github.com/material-components/material-components-web/tree/master/packages/mdc-auto-init

**Comment by acdvorak** [comment]
Closing this issue for now. Feel free to reopen if you're still having trouble! 😀

**Comment by mediamichael** [comment]
Another way to write the querySelectorAll:
`const allIconBtns = document.querySelectorAll('.mdc-icon-button');
allIconBtns.forEach(function(icon) {
  new MDCRipple(icon);
});`
