### ISSUE TITLE
Some confusion with Configuring a Sass Importer for Nested node_modules

### ISSUE THREAD

**Issue by fifn2** [material-components/material-components-web#3246]
### Some confusion with [Configuring a Sass Importer for Nested node_modules](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md)
Hey,
I'm working on the getting started section of the documentation. I finished steps 1 and 2 of the Getting Started section of the documentation.  I don't see the materially designed button. I tried making a new file in my project directory called importer.js, and it contains
```javascript
const path = require('path');

function tryResolve_(url, sourceFilename) {
  // Put require.resolve in a try/catch to avoid node-sass failing with cryptic libsass errors
  // when the importer throws
  try {
    return require.resolve(url, {paths: [path.dirname(sourceFilename)]});
  } catch (e) {
    return '';
  }
}

function tryResolveScss(url, sourceFilename) {
  // Support omission of .scss and leading _
  const normalizedUrl = url.endsWith('.scss') ? url : `${url}.scss`;
  return tryResolve_(normalizedUrl, sourceFilename) ||
    tryResolve_(path.join(path.dirname(normalizedUrl), `_${path.basename(normalizedUrl)}`),
      sourceFilename);
}

function materialImporter(url, prev) {
  if (url.startsWith('@material')) {
    const resolved = tryResolveScss(url, prev);
    return {file: resolved || url};
  }
  return {file: url};
}
```
I modified the webpack.config.js file so that it contained
```javascript
const autoprefixer = require('autoprefixer');
module.exports = [{
  entry: './app.scss',
  output: {
    // This is necessary for webpack to compile
    // But we never use style-bundle.js
    filename: 'style-bundle.js',
  },
  module: {
    rules: [{
      test: /\.scss$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: 'bundle.css',
          },
        },
        { loader: 'extract-loader' },
        { loader: 'css-loader' },
        { loader: 'postcss-loader',
  options: {
     plugins: () => [autoprefixer()]
  }
},
{
loader: 'sass-loader',
options: {
importer: materialImporter
},
}
      ]
    }]
  },
}];
```
When I tried to execute `npm start`, I got a long error, so I tried replacing `materialImporter` with `'importer.js'` (with ''s) and `importer.js`. I also tried
```javascript
const autoprefixer = require('autoprefixer');
module.exports = [{
  entry: './app.scss',
  output: {
    // This is necessary for webpack to compile
    // But we never use style-bundle.js
    filename: 'style-bundle.js',
  },
  module: {
    rules: [{
      test: /\.scss$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: 'bundle.css',
          },
        },
        { loader: 'extract-loader' },
        { loader: 'css-loader' },
        { loader: 'postcss-loader',
  options: {
     plugins: () => [autoprefixer()]
  }
},
{
loader: 'sass-loader',
options: {
importer: materialImporter
includePaths: ['./node_modules']
},
}
      ]
    }]
  },
}];
```
and
```javascript
const autoprefixer = require('autoprefixer');
module.exports = [{
  entry: './app.scss',
  output: {
    // This is necessary for webpack to compile
    // But we never use style-bundle.js
    filename: 'style-bundle.js',
  },
  module: {
    rules: [{
      test: /\.scss$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            name: 'bundle.css',
          },
        },
        { loader: 'extract-loader' },
        { loader: 'css-loader' },
        { loader: 'postcss-loader',
  options: {
     plugins: () => [autoprefixer()]
  }
},
{
loader: 'sass-loader',
options: {
importer: materialImporter
},
options: {
includePaths: ['./node_modules']
}
}
      ]
    }]
  },
}];
```
Is this an issue that can be solved by renaming the file to materialImporter?
Thanks,
Finn

**Comment by kfranqueiro** [comment]
The way the Getting Started guide was written assumes the functions for the importer are defined within `webpack.config.js` itself for simplicity's sake.

If you want to define the importer function in its own file, you'll need to treat it like any other module - export the function from the separate module, and `require` that module within `webpack.config.js`.

At the bottom of `importer.js`:

```js
module.exports = materialImporter;
```

At the top of `webpack.config.js`:

```js
const materialImporter = require('./importer');
```

Also note that in most common cases, simply defining `includePaths` is sufficient - I'd only go the `importer` route if that's not working for you.

**Comment by fifn2** [comment]
That is working, thank you! I wonder why I `includePaths` didn't work. Am I supposed to somehow `require` the paths at the top?
Thanks!

**Comment by kfranqueiro** [comment]
`includePaths` should simply be a one-liner that doesn't require any other additional JS or imports.

I'm not sure what specific error you got, but `includePaths` can fail to work if `npm` installed Material packages in a nested structure for some reason due to conflicting version dependencies. In the ideal case where you're installing the all-in-one `material-components-web` package or otherwise the latest version of all MDC packages you're using, npm should be able to install everything flat under the top-level `node_modules` folder in your project, but if there are version conflicts it will need to install some transitive dependencies under nested `node_modules`, which is what the importer tries to resolve by reusing node's import resolution logic.

Anyway, since you've sorted it out, I'm going to go ahead and close this.

**Comment by JoeCodeswell** [comment]
It would be a time saver to incorporate this clarification in the Getting Started guide doc. 
I spent a bit of time on this myself today.
Thanks.
Love and peace,
Joe

**Comment by kfranqueiro** [comment]
When you say incorporate this clarification, do you mean clarifying that the [appendix](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#appendix-configuring-a-sass-importer-for-nested-node_modules) code assumes that the importer is implemented within `webpack.config.js`?

**Comment by JoeCodeswell** [comment]
Yes, Kenneth. Thanks.
Love and peace,
Joe

**Comment by dieseld23** [comment]
@googlebot I signed it!
