### ISSUE TITLE
Enhancement: Change SCSS include syntax to support the latest webpack sass-loader

### ISSUE THREAD

**Issue by blowery** [material-components/material-components-web#3253]
The current sass files include their dependencies the [standard sass way](https://sass-lang.com/guide#topic-5), minus the file extension. That works just fine for most sass libraries, but in webpack@4 it [doesn't work well](https://github.com/webpack-contrib/sass-loader/issues/556).

The latest sass loader uses webpack's module resolution algorithm, and as a result, when you have a scss file and a js file with the same name, it will prefer the JS over the SCSS and the import breaks.

The workaround is to always include scss files _with the extension_ so there's no ambiguity about which file to process. `@import 'foo'` becomes `@import 'foo.scss'`.

I'll try to add a simple repro soon, but I'm currently on a train. 🚋

**Comment by blowery** [comment]
OK, I worked up a repro repo at https://github.com/blowery/importing-material-css

However, I think I was wrong. I got things working without modifying the SCSS imports inside of the published material packages. So, yay? Yay.

There were two ways to make it work, as shown in https://github.com/blowery/importing-material-css/tree/using-resolve-extensions and https://github.com/blowery/importing-material-css/tree/using-extensions-on-import

First, they need to set up the `sass-loader` as shown in the existing material docs, with an `options: { includePaths: [ 'node_modules' ] }` set.

If the client wants to include sass files _with_ extension, nothing further is necessary. Just `import '@material/button/mdc-button.scss` and they're done. 

If the client wants to include sass files _without_ specifying the extension, like `import '@material/button/mdc-button'`, they have to [add `.scss` to the array of extensions](https://github.com/blowery/importing-material-css/blob/using-resolve-extensions/webpack.config.js#L13) to check when resolving modules in the webpack config.

So I don't think anything is necessary from material's end. Maybe a doc update for webpack 4, but that's it.

**Comment by kfranqueiro** [comment]
@blowery would MDC Web's own cross-package imports still cause this issue if the extensions array isn't set up properly? It might still be a good idea for us to update our imports to be explicit if it increases compatibility.

**Comment by blowery** [comment]
@kfranqueiro it occurs to me that Dojo already did this, but I digress. ;)

Resolution appears to work out without the extensions array. It seems like once you're inside a sass file, different rules apply, but ... maybe not? Resolution inside sass-loader is a bit exciting.

https://github.com/webpack-contrib/sass-loader/issues/296 and https://github.com/webpack-contrib/sass-loader/pull/307 shed some light on what's going on. The end of 296 especially.
