### ISSUE TITLE
List - handleClick method is missing from foundation

### ISSUE THREAD

**Issue by codedbypaul** [material-components/material-components-web#3257]
### What MDC Web Version are you using?

0.37.1

### What browser(s) is this bug affecting?

All

### What OS are you using?

CentOS 7

### What are the steps to reproduce the bug?

`npm i --save @material/list`
Create a component using the list foundation.

### What is the expected behavior?

Should initialise with no errors.

### What is the actual behavior?

the handleClick method is missing from mdc-list foundation.

**Comment by codedbypaul** [comment]
The README.md doesn't mention it either.

**Comment by williamernest** [comment]
@codedbypaul Thanks for filing this issue. The `handleClick` method wasn't added until after the `0.37.1` release as part of the single selection feature in #2970 . It should be released now as a part of `0.38.0`
