### ISSUE TITLE
Element "div" inside element "button" in MDC Tab

### ISSUE THREAD

**Issue by monstasat** [material-components/material-components-web#3301]
In 'Basic usage' section of MDC Tab documentation page there is the following HTML markup for the component:
```<button class="mdc-tab" role="tab" aria-selected="false" tabindex="-1">
  <div class="mdc-tab__content">
    <span class="mdc-tab__icon">heart</span>
    <span class="mdc-tab__text-label">Favorites</span>
  </div>
  <span class="mdc-tab-indicator">
    <span class="mdc-tab-indicator__content mdc-tab-indicator__content--underline"></span>
  </span>
  <div class="mdc-tab__ripple"></div>
</button>
```

But according to W3C, element “div” not allowed as child of element “button”

**Comment by kfranqueiro** [comment]
Thanks for pointing this out.

It looks like this is largely a documentation bug - in practice, we've typically used `span`s for the elements that are currently expressed as `div`s inside the `button` elements. I'll send a PR in a few minutes to fix this.

**Comment by ThomasOrlita** [comment]
This still seems not to be fixed, see https://material.io/develop/web/components/buttons/

```
<button class="mdc-button">
  <div class="mdc-button__ripple"></div>
  <span class="mdc-button__label">Button</span>
</button>
```
