### ISSUE TITLE
MDC Tab doesn't deregister click handler

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#3316]
In the `init` method in the mdc-tab/foundation.js, the click handler is registered, however I don't see a deregister call.

```  
  init() {
    this.adapter_.registerEventHandler('click', this.handleClick_);
  }
```

**Comment by kfranqueiro** [comment]
This should probably be tackled along with migrating Tab and Tab Indicator's event registrations to their components.

**Comment by acdvorak** [comment]
We could conceivably deregister event listeners automatically in the base `MDCComponent` class.
