### ISSUE TITLE
Dialog open animation broken for v0.38.1

### ISSUE THREAD

**Issue by trimox** [material-components/material-components-web#3345]
### What MDC Web Version are you using?

v0.38.1

### What browser(s) is this bug affecting?

All

### What are the steps to reproduce the bug?

Open a dialog

### What is the expected behavior?

![dialog-with-animation](https://user-images.githubusercontent.com/11887843/44088437-16bb1d5a-9f91-11e8-9556-027e57ea1058.gif)

### What is the actual behavior?

![dialog-no-animation](https://user-images.githubusercontent.com/11887843/44088377-e4cdaf7e-9f90-11e8-919e-cf385775f420.gif)

### Any other information you believe would be useful?

`MDCDialogFoundation.numbers.DIALOG_ANIMATION_TIME_MS` is undefined.
https://github.com/material-components/material-components-web/blob/4cc16d9938ba43315b6970256e0b8cad8b481656/packages/mdc-dialog/foundation.js#L86

**Comment by kfranqueiro** [comment]
Thanks for catching this and sorry for the trouble! Looks like something slipped through on review. I'll send another PR and cut another bugfix release.

**Comment by trimox** [comment]
@kfranqueiro Not a prob! Glad to help, and thank you for the quick PR!
