### ISSUE TITLE
Switch component missing required javascript files

### ISSUE THREAD

**Issue by endigo9740** [material-components/material-components-web#3348]
### What MDC Web Version are you using?

"@material/switch": "^0.36.1",

### What browser(s) is this bug affecting?

Safari - Version 11.1.2 (13605.3.8)
Mobile Safari - (same as OS version?)
Mobile Chrome (iOS) - 68.0.3440.83
Mobile Chrome (Android) -(Only some devices, sorry I don't have specific versions. Works for me on Android Pie running latest version)

### What OS are you using?

Mac OSX High Sierra - 10.13.6 (17G65)
iOS version 11.4.1

### What are the steps to reproduce the bug?

1. Following instructions here: https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch
2. Run: npm install @material/switch
3. Follow steps for "JavaScript Instantiation", however NO javascript files are present with this node module package
5. See screenshot below:

<img width="231" alt="screen shot 2018-08-14 at 11 11 17 am" src="https://user-images.githubusercontent.com/1509726/44104062-7b611814-9fb3-11e8-9d30-3744b77dd7ba.png">

### Any other information you believe would be useful?

I've tried removing and reinstalling the package.

The switch works as intended on some browsers (Chrome for Mac OSX), however on others it does not (Android/iOS Chrome, Mobile Safari, etc). Console log fires if attached to the click state, however the switch does not visually change. It remains in it's original visual position (on/off) at the time of loading.

The switch DOES visually update/animate when tapped on the demo page here, so I think this missing Javascript may be the culprit:

https://material-components.github.io/material-components-web-catalog/#/component/switch

**Comment by williamernest** [comment]
@endigo9740 Thanks for filing this issue. It looks like you're looking at the latest documentation (master), but you have an older version of switch installed locally. You can either upgrade switch to >`0.38.0` (when the JS was added), or check out the documentation for the [`v0.36.1`](https://github.com/material-components/material-components-web/tree/v0.36.1/packages/mdc-switch) tag.

**Comment by kfranqueiro** [comment]
I'm closing this since I believe @williamernest has answered the question. To clarify, Switch did not have any JS logic prior to v0.38.0, at which point its DOM structure was changed and JS was added to better align with the Material Design spec and also improve accessibility.
