### ISSUE TITLE
@material/menu-surface not found on npmjs

### ISSUE THREAD

**Issue by BrutalPRO** [material-components/material-components-web#3356]
Can't install the package. 
His not found on npmjs:
https://www.npmjs.com/package/@material/menu-surface

```
$ npm install @material/menu-surface
npm ERR! code E404
npm ERR! 404 Not Found: @material/menu-surface@latest
```

**Comment by williamernest** [comment]
@BrutalPRO Thanks for filing this issue. `menu-surface` hasn't been released to npm yet. It will be released on August 27th as part of our Breaking Change release.
