### ISSUE TITLE
Input not display correctly since 0.39.0-0

### ISSUE THREAD

**Issue by alexandrestein** [material-components/material-components-web#3381]
### What MDC Web Version are you using?

0.39.0-0

### What browser(s) is this bug affecting?

With Chromium and Firefox

### What OS are you using?

up-to-date Arch Linux

### What are the steps to reproduce the bug?

Setup a basic text-field with the version 0.39.0-0 and click on it.

### What is the expected behavior?

![capture d ecran de 2018-08-17 18-00-08](https://user-images.githubusercontent.com/5431025/44277094-d84c6e00-a249-11e8-94e8-8e653e514b17.png)
[codepen.io](https://codepen.io/alexandreStein/pen/oMKpQV)

### What is the actual behavior?

![capture d ecran de 2018-08-17 17-59-41](https://user-images.githubusercontent.com/5431025/44277066-c5399e00-a249-11e8-8912-b75022f6c7db.png)

[codepen.io](https://codepen.io/alexandreStein/pen/WKVdLR)

**Comment by kfranqueiro** [comment]
Thanks for pointing this out.

We're making a few changes to Text Field in the next release, including [making the filled ("box") variant the default](https://github.com/material-components/material-components-web/pull/2859) to better align with the spec. We're still preparing to land that change, but other style fixes have already gone in, which haven't taken into account the current default styling, which will be removed. This issue will be obsolete once #2859 lands this week.
