### ISSUE TITLE
Document restricting Tab Indicator to full tab vs. content

### ISSUE THREAD

**Issue by toprawa** [material-components/material-components-web#3384]
As of version 0.38.0 mdc-tabs is deprecated. Now the tabs with icons above labels and indicators restricted to content.

How can I adjust the width of the indicator underline to the selected tab when i use tabs with icons above labels.

Thanks.

**Comment by kfranqueiro** [comment]
I answered on StackOverflow: https://stackoverflow.com/a/51967974/237950

However, I think this is something that isn't currently pointed out in our docs, so I'm going to track this to address that.

**Comment by toprawa** [comment]
Perfect, thanks
