### ISSUE TITLE
Annotate mdc-menu for closure

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#339]

**Comment by traviskaufman** [comment]
cc @bogusred

**Comment by bogusred** [comment]
@traviskaufman @lynnjepsen According to the [closure style guide](https://google.github.io/styleguide/jsguide.html#features-classes-getters-and-setters), the compiler doesn't have great support for ES6 getters/setters. As part of this task, would you like me to change the getters/setters to regular methods?

**Comment by lynnjepsen** [comment]
Hmm I'm not sure...It says "limited support", and we're not doing anything too crazy. Can we leave them as getters/setters for now? And if the compiler actually does start doing odd things we can revisit? 

My reasoning is I don't really want to spend extra work on something that might not even be a problem. Especially if it takes us _away_ from an ES6 best practice.

**Comment by bogusred** [comment]
Sgtm 👍
