### ISSUE TITLE
Documentation mistake.

### ISSUE THREAD

**Issue by BesoKakulia** [material-components/material-components-web#3415]
It seems a mistake in select's documentation 
![issue](https://user-images.githubusercontent.com/26166174/44583980-75625600-a7b8-11e8-89dd-8e71cdcc2c26.png)

**Comment by davwheat** [comment]
What's the problem though? If you don't explain it, we can't help.

**Comment by BesoKakulia** [comment]
It is shown on screen shot, a mixin which is defined for radius is explained as radius color mixin, that is wrong. I could not left feedback so decided to write here.
