### ISSUE TITLE
Provide a API to prevent menu auto closed after selecting menu items

### ISSUE THREAD

**Issue by foisonocean** [material-components/material-components-web#3420]
## Feature Requests

It would be wonderful if there is an API to prevent menu auto closed after selecting menu items.

**Comment by williamernest** [comment]
Thanks for filing this issue. We recently moved the `mdc-menu` positioning logic into it's own pacakge `mdc-menu-surface` so it can be reused by developers to build their own menu-like components. The menu component by default will close, but by implementing your own `mdc-menu-surface` with a `mdc-list` inside you should be able to customize the closing/opening behavior.
