### ISSUE TITLE
Version 0.39.0 broke input styling

### ISSUE THREAD

**Issue by WebTechnolog** [material-components/material-components-web#3429]
### What MDC Web Version are you using?
0.39.0

### What browser(s) is this bug affecting?
All

### What OS are you using?
All

### What are the steps to reproduce the bug?

1. Update from 0.38.0 to 0.39.0
2. Watch inputs change their styles

0.38.0 - https://stackblitz.com/edit/js-btf2e4?file=index.html
0.39.0 - https://stackblitz.com/edit/js-mzprca?file=index.html

### What is the expected behavior?

Inputs preserve styling

### What is the actual behavior?

Inputs styling changed

**Comment by williamernest** [comment]
@WebTechnolog Thanks for filing this issue. This was a known change. The default style without a box was deprecated a few releases ago and was finally removed with version 0.39.0.

**Comment by WebTechnolog** [comment]
@williamernest ok. Then please update the docs and demos. They are confusing. Demos especially, as there's nothing said about deprecation.
https://material-components.github.io/material-components-web-catalog/#/component/text-field
