### ISSUE TITLE
mdc-menu-surface scss lexical error 

### ISSUE THREAD

**Issue by rubysamurai** [material-components/material-components-web#3438]
Version: **v0.39.0** 
Component: **mdc-menu-surface**

Bug: Scss part of mdc-menu-surface can't be compiled with scss and postcss-cssnext

```
Module build failed: Error: Lexical error on line 1. Unrecognized text.
100vw - $mdc-menu-surface-mi
```

This is caused by these lines: [L41](https://github.com/material-components/material-components-web/blob/13fd1fa6c41820cd432554bec061e88f8434a873/packages/mdc-menu-surface/mdc-menu-surface.scss#L41) [L42](https://github.com/material-components/material-components-web/blob/13fd1fa6c41820cd432554bec061e88f8434a873/packages/mdc-menu-surface/mdc-menu-surface.scss#L42)

```scss
max-width: calc(100vw - $mdc-menu-surface-min-distance-from-edge);
max-height: calc(100vh - $mdc-menu-surface-min-distance-from-edge);
```

The fix is to interpolate variables inside calc() like this:

```scss
max-width: calc(100vw - #{$mdc-menu-surface-min-distance-from-edge});
max-height: calc(100vh - #{$mdc-menu-surface-min-distance-from-edge});
```

I also would like to point out that interpolation was always used in all previous components (for example [here](https://github.com/material-components/material-components-web/blob/2cf84876fec45a0c8d31eff2ec47d48b11c8fdac/packages/mdc-ripple/_mixins.scss#L185) and [here](https://github.com/material-components/material-components-web/blob/2cf84876fec45a0c8d31eff2ec47d48b11c8fdac/packages/mdc-floating-label/_mixins.scss#L38)) and I really don't see a reason to stop following this pattern.

**Comment by williamernest** [comment]
@rubysamurai Thanks for filing this issue. It should be fixed shortly.
