### ISSUE TITLE
Changing theme colours with javaScript

### ISSUE THREAD

**Issue by jakcharvat** [material-components/material-components-web#3439]
Hello, 
I am wondering if there is any way to change the theme colours dynamically using JS. I have the theme colours defined in the SCSS file using the `$mdc-theme-primary`,  `$mdc-theme-on-primary`, `$mdc-theme-secondary`, `$mdc-theme-on-secondary`, `$mdc-theme-surface`, `$mdc-theme-on-surface`, `$mdc-theme-background`, `$mdc-theme-on-background` variables, and would like to be able to change them with JS. Is this possible, and if so, could someone please help me doing so? 
Thank you very much.

**Comment by williamernest** [comment]
@jakcharvat Thanks for filing this issue. You can change some of the theme colors by using css variables described in our [theming guide](https://github.com/material-components/material-components-web/blob/master/docs/theming.md). It currently doesn't work for all colors but it may be enough to resolve your issue. 

If you need to use a completely different theme, we suggest compiling that ahead of time and downloading the new theme when needed.
