### ISSUE TITLE
Some primary colours are not set with variables in CSS

### ISSUE THREAD

**Issue by Bloemendaal** [material-components/material-components-web#3441]
## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

0.39.0

### What browser(s) is this bug affecting?

Chrome 68 (latest)

### What OS are you using?

Windows 10 Home

### In short
Please add variables to the following classes to have them match the primary colour in my project.
Thanks in advance, I love this project, keep up the great work :)

### What is the expected behavior?
`.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label {
    color: rgba(98,0,238,0.87);
    color: var(--mdc-theme-primary, #6200ee);
}`

`.mdc-drawer .mdc-list-item--activated {
    color: rgba(98,0,238,0.87);
    color: var(--mdc-theme-primary, #6200ee);
}`

`.mdc-drawer .mdc-list-item--activated .mdc-list-item__graphic {
    color: #6200ee;
    color: var(--mdc-theme-primary, #6200ee);
}`

### What is the actual behavior?
`.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label {
    color: rgba(98,0,238,0.87);
}`

`.mdc-drawer .mdc-list-item--activated {
    color: rgba(98,0,238,0.87);
}`

`.mdc-drawer .mdc-list-item--activated .mdc-list-item__graphic {
    color: #6200ee;
}`

**Comment by williamernest** [comment]
@Bloemendaal Thanks for filing this issue. This is already being tracked in #3066. In order to closely match spec, we ended up breaking css variable support for some of our components and are investigating how we can resolve the issue.

**Comment by williamernest** [comment]
Closing this issue since it's already being tracked.
