### ISSUE TITLE
Error when importing the material/dialog component

### ISSUE THREAD

**Issue by mkay581** [material-components/material-components-web#3444]
### What MDC Web Version are you using?

 0.39.0

### What browser(s) is this bug affecting?

I am using Chrome on a Linux machine (Ubuntu). User agent string is

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36`

### What OS are you using?

Ubuntu 18.04.1 LTS

### What are the steps to reproduce the bug?

I am attempting to use the `@material/dialog` component without a build step by `import`ing the `dist/mdc.dialog.js` file and getting an error in the console. Here is the codepen URL: https://codepen.io/mkay581/pen/dqXQEj

### What is the expected behavior?

`import` the dialog component successfully

### What is the actual behavior?

Get the following error:

`Uncaught SyntaxError: The requested module 'https://unpkg.com/@material/dialog@0.39.0/dist/mdc.dialog.js' does not provide an export named 'MDCDialog'`

**Comment by williamernest** [comment]
@mkay581 Thanks for filing this issue. We don't support using `import` syntax without a build step involved. In order to use the `dist/*.js` files, simply import them using a `script` tag. I've updated your codepen as an example. 

https://codepen.io/williamernest/pen/JaJMLG

**Comment by mkay581** [comment]
Thanks @williamernest. Is this repo opposed to supporting native browser `import`s at all in the future? It suspect that it would turn off consumers by not supporting this use case. Since it looks like webpack is being used to bundle the components, it wouldn't take much to update it to export the appropriate classes. Would a PR be acceptable?

**Comment by williamernest** [comment]
@mkay581 It may be something we consider in the future, but it doesn't have the backwards compatibility that we expect. Since it's not supported in IE11, it's probably something we won't implement.
