### ISSUE TITLE
MDC-Select required issue v0.34.1 > 0.38.0

### ISSUE THREAD

**Issue by jvalst** [material-components/material-components-web#3461]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What MDC Web Version are you using?

0.38.0

### What browser(s) is this bug affecting?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Back in 0.34.1 there was an asterix showing on the required select labels. Now after updating to 0.38.0, no asterix is shown anymore. Also the invalid style is not documented anymore? What is the reason for this?

### What is the expected behavior?

MDC Select should show an asterix on required selects. Also an invalid state should be shown when there is no value selected.

### What is the actual behavior?

Required select shows nothing

**Comment by williamernest** [comment]
@jvalst Thanks for filing this issue. We have this issue already tracked in #291 and we are actively working on rebuilding the select to match all the states/variants of the text field. We're hoping to have a relaunch of the component with both a native and enhanced menu in our R41 release at the end of October.

**Comment by jvalst** [comment]
Ah thanks, then we have to wait for October. Thanks ;)
