### ISSUE TITLE
Modal Drawer scroll issue

### ISSUE THREAD

**Issue by elliot-labs** [material-components/material-components-web#3465]
## Bugs

When the user scrolls down to the bottom of a Modal drawer, the bottom items are cut off by the height of the header if one is implemented in the app.
Removing the header corrects the issue but is undesirable.

Link to live code that has issue:
https://material-components.github.io/material-components-web-catalog/#/component/drawer

![Normal vs bugged behavour](https://user-images.githubusercontent.com/5030490/44785161-fb3a2480-ab5d-11e8-830e-2b006f236273.png)

![Workaround](https://user-images.githubusercontent.com/5030490/44785314-77cd0300-ab5e-11e8-99c2-0e8014f28abc.png)

### What MDC Web Version are you using?

> 0.39.0

### What browser(s) is this bug affecting?

> Chrome, IE and Edge.

### What OS are you using?

> Windows 10 RS4 x64 Enterprise

### What are the steps to reproduce the bug?

Open the modal drawer that has a header and content that is longer than the bottom of the page.
Scroll down and you will notice that the bottom items are cut off by the size of the header.

Link to live code that has issue (as of now at version 0.39.0):
https://material-components.github.io/material-components-web-catalog/#/component/drawer

### What is the expected behavior?

> The user scrolls to the bottom of the drawer menu and interacts with all items properly.

### What is the actual behavior?

> The user scrolls to the bottom of the list but is unable to see part, one or more of the menu items at the bottom.

### Any other information you believe would be useful?

You can workaround the issue by removing the header content and the list scrolls as expected.

**Comment by kfranqueiro** [comment]
Thanks for reporting this. I think this corresponds to PR #3431.

**Comment by elliot-labs** [comment]
Thanks for the update.
Can't wait for the bug fix to be published :)
