### ISSUE TITLE
MDC TextField / Select - UI outline disappear while loading dynamic content

### ISSUE THREAD

**Issue by ronzilca** [material-components/material-components-web#3467]
### What MDC Web Version are you using?
0.38.0

### What browser(s) is this bug affecting?
Google Chrome 68.0.3440.106 (Official Build) (64-bit)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

### What OS are you using?
macOS Sierra 10.12.6

### What are the steps to reproduce the bug?
https://codepen.io/anon/pen/RYGJga

Well, its hard to demonstrate the bug with codepen, but there is 2 cases that we found:
1. while loading kind of custom modal, like date-picker with overlay.
2. while loading dynamic content with ajax which cause overflow of the body tag (scrolling).

### What is the expected behavior?
The outline shouldn't be affected by this behavior.

### What is the actual behavior?
Part of the outline is disappear, in one case the entire outline has gone. 
![untitled-1](https://user-images.githubusercontent.com/2135285/44789912-87703a00-aba6-11e8-89cd-f8f31fc53bff.jpg)

If I'll click this field again - the outline is back to normal.

### Any other information you believe would be useful?
Our use case is internal dashboard, tested also on Windows OS, but everyone here work with Google Chrome.

**Comment by williamernest** [comment]
@ronzilca Thanks for filing this issue. This can happen sometimes when the text field is added/removed/changed on the page after it has been instantiated. In this case, you can call `.layout()` when you need to to have the svg recalculated. Let me know if that fixes your problem.
