### ISSUE TITLE
MDCIconButton Visual imperfection

### ISSUE THREAD

**Issue by CiriousJoker** [material-components/material-components-web#3483]
This is in no way more important than probably any of the other 300 issues, but I didn't want it to get lost.

Here's a screenshot taken from the official demo (reproducable in the latest version on my dev server):
https://i.imgur.com/GYbYey4.png

The rightmost pixels are missing (it should be antialiased like the left side).
Same for the bottom pixels.

**Comment by williamernest** [comment]
@CiriousJoker Thanks for filing this issue. This issue is already being tracked in #2431 so I'll close this issue.
