### ISSUE TITLE
Radio controls as switches - no longer possible?

### ISSUE THREAD

**Issue by GusRuss89** [material-components/material-components-web#3484]
I maintain the WordPress plugin "[Material Design for Contact Form 7](https://wordpress.org/plugins/material-design-for-contact-form-7/)".

I know it's not good UX, but I have historically let my users turn radio controls into switches, because the switch control worked with either radio or checkbox inputs.

I'm updating the packages for the first time in a while, and noticed that the radio switches no longer work - they look right initially, but they don't turn off when another radio is selected.

Is this intended or is it a bug? If a bug, I'd be happy to create a codepen or codesandbox repro. If intended, fair enough I suppose, I will just need to figure out how to deal with users who have already turned radio buttons into switches.

**Comment by williamernest** [comment]
@GusRuss89 Thanks for filing this issue. It looks like that was an unintended behavior of the previous switch and we have no plans to implement this feature.
