### ISSUE TITLE
Item wrapper in lists ends up in an endless loop

### ISSUE THREAD

**Issue by pfecht** [material-components/material-components-web#3487]
### What MDC Web Version are you using?

@material/menu 0.39.0
@material/list 0.39.0

### What browser(s) is this bug affecting?

All

### What are the steps to reproduce the bug?

Sometimes it's necessary to have a wrapper element around a list item (in my case to wrap it in a custom element). However, a wrapper element breaks the menu on click and ends up in an endless loop.

1. Create a menu with list, list item and a wrapper element around the list item.
2. Click on the list item

See: https://codepen.io/pfecht/pen/djzVLX

### What is the expected behavior?

Menu closes and everything is fine.

### What is the actual behavior?

Tab is frozen, application breaks and browser has to be forced quitted (probably an endless loop).

### Any other information you believe would be useful?

Probably something to start with https://github.com/material-components/material-components-web/blob/master/packages/mdc-list/index.js#L99

**Comment by williamernest** [comment]
@pfecht Thanks for filing this issue. We've fixed the bug and will run a new release shortly.

**Comment by williamernest** [comment]
@pfecht Your issue should be fixed in version `v0.39.1`. Let me know if you continue to have any issues.
