### ISSUE TITLE
mdc-select doesn't resize to accomodate selected-text text longer than list-item text

### ISSUE THREAD

**Issue by wc-matteo** [material-components/material-components-web#349]
### What MDC-Web Version are you using?

@material/select 0.2.2

### What browser(s) is this bug affecting?

Chrome 56.0.2924.87

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Set `mdc-select__selected-text` to a text longer than the longest `mdc-list-item` text.

### What is the expected behavior?

The select is as large as the `mdc-select__selected-text` text.

### What is the actual behavior?

The select is as large as the largest `mdc-list-item` text.

**Comment by traviskaufman** [comment]
Doesn't look like there's enough information here for us to verify the bug. Would you mind either giving us concrete steps to reproduce or putting up a codepen with a repro?

**Comment by wc-matteo** [comment]
@traviskaufman taken straight from your demos:

http://codepen.io/anon/pen/bqGzNK

if you add `d` to `c`, you can then see `ab`; otherwise only `a` is visible.

**Comment by traviskaufman** [comment]
Your problem here is that `ab` is only put in the selected text but not specified as a list option. I [forked your pen](http://codepen.io/traviskaufman/pen/KWpeOY?editors=1010) and changed it so that `ab` is also a list option and it works as expected.

If you're looking for something more like a "default option", you can use a `mdc-list-item` element with `aria-disabled="true"`

**Comment by wc-matteo** [comment]
Gotcha.

What about the example in _Using the full-fidelity JS component_ [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#using-the-full-fidelity-js-component)?

**Comment by traviskaufman** [comment]
...whoops! That def needs to be corrected. Tracking in #362 nice catch!

**Comment by mellogarrett** [comment]
Adding a disabled list-item is not ideal.

When using the JS component, it seems like `resize` should also take into account the `hintText` when calculating width of the element 
https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/foundation.js#L178
