### ISSUE TITLE
Change select--box to be the new default 

### ISSUE THREAD

**Issue by iczman** [material-components/material-components-web#3495]
With text-field defaulting to the box variant (#2859), should we also make the same change to select?

**Comment by Nerg4l** [comment]
The box style will be the default one.

Here is a quote from the [README.md of MDC Select](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select)

> The existing default select style will be changed in an upcoming release. The Material spec indicates that the default style will be the filled variant (currently referred to as the box variant). This will become the default style. Continuing to add the `mdc-select--box` class to the select will result in no change.

**Comment by iczman** [comment]
Understood, thanks for confirming!
