### ISSUE TITLE
Implement "FAB-Single Sheet Menu" component

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#35]
- Spec reference: https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions
- Motion video mock: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B8v7jImPsDi-d09QRUZzVUdMSFk/components-buttons-fab-transition_card_01.webm
- [ ] Implement Proper transitions between FAB and Single Sheet Menu
- [ ] Add correct Keyboard A11y

There are internal motion mocks for these transitions that I can get when it comes time to implement.

> Copied from https://github.com/google/material-design-lite/issues/4483

**Comment by Sayene** [comment]
why is it closed? is 'fab-menu' / 'speed dial' component in the beta roadmap?
