### ISSUE TITLE
MDCRipple: Context menu causes ripple to remain activated

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#3524]
Steps to reproduce:
1. Long press on a button when in chrome touch mode. 
2. Click Esc when the menu appears. 
3. Click Tab to focus the next element. 
Notice that the button stays dark while focus has moved to other elements. The button element retains the `:hover` psuedo-class (See [Note](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover)) but it also has the `FG_ACTIVATION` class that causes it be a darker color and more noticeable.

I was able to get the button to return to almost normal (still has the `:hover` state), by removing the activation class and resetting the activate state in the `handleBlur` function.

```
  handleBlur() {
    requestAnimationFrame(() => {
      this.adapter_.removeClass(MDCRippleFoundation.cssClasses.BG_FOCUSED);
      this.adapter_.removeClass(MDCRippleFoundation.cssClasses.FG_ACTIVATION);
      this.resetActivationState_();
    });
  }
```

**Comment by kfranqueiro** [comment]
This is also reproducible simply by right-clicking on desktop (which opens the context menu just like long-press on mobile does). I think the stuck hover state on mobile might be unavoidable, but we ought to be able to resolve the stuck activation related to context menus either via the above change, or possibly via the contextmenu event (but it might be odd for activation to clear while the menu is still open).

I had thought we might have tracked this already but I can't find an existing issue about this, so I'll track this one.
