### ISSUE TITLE
MDCTextField: outlined disabled ink color

### ISSUE THREAD

**Issue by stevegeek** [material-components/material-components-web#3526]
Hi all,
 
I think the color of the text in a disabled outlined text field is set as the placeholder text rather than disabled text ink.

`https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/_mixins.scss#L240`

To replicate go to: https://material-components-web.appspot.com/text-field.html , to the `Outlined Text Field` , fill in some text, then select `Disabled`.

Is this the intended behaviour?

### What MDC Web Version are you using?

`@material/textfield : 0.38.0`

### What is the expected behavior?

The outlined text field disabled text color should be the same as non-outlined textfield disabled color

### What is the actual behavior?

The disabled field text color comes from the placeholder text color

`https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/_mixins.scss#L240`

**Comment by williamernest** [comment]
@stevegeek Thanks for filing this issue. We'll add it to our tracker.
