### ISSUE TITLE
MDCRipple: long press and hiding element causes a crash

### ISSUE THREAD

**Issue by robcaldecottvelo** [material-components/material-components-web#3527]
I am using the popular `rmwc` library which ships with MDC 0.39.1. If you have a ripple-enabled button/FAB and long-press it with the mouse (so you get a full ripple) and then immediately hide the element then `mdc.ripple.js` will crash when trying to remove a class from a `root_` that has already been destroyed.

Here is a codesandbox:

https://codesandbox.io/s/3rpo0829q6

The code that shows the problem:

```js
class App extends React.Component {
  state = { show: true };

  render() {
    return (
      <React.Fragment>
        <p>Long click on the button below (so you get a full ripple)</p>
        {this.state.show && (
          <Button
            raised
            onClick={() => {
              this.setState({ show: false });
            }}
          >
            Long click me
          </Button>
        )}
      </React.Fragment>
    );
  }
}
```

The crash occurs in this MDC code (mdc.ripple.js)

```js
removeClass: function removeClass(className) {
  return instance.root_.classList.remove(className);
}
```

**Comment by kfranqueiro** [comment]
This looks like https://github.com/material-components/material-components-web/issues/2460 except for _deactivation_ rather than activation. I think this should be straightforward to fix.

**Comment by jamesmfriedman** [comment]
@kfranqueiro updated sandbox for the issue.

I broke the other one because of my movement to separate packages.
https://codesandbox.io/s/qzwm42p1vw
