### ISSUE TITLE
Dark text on light backgrounds (typo?)

### ISSUE THREAD

**Issue by web2033** [material-components/material-components-web#3534]
Which is right?

![2018-09-07_223815](https://user-images.githubusercontent.com/11320080/45239718-e0e71000-b2ee-11e8-84dd-032fe7f68a4d.jpg)

Source: https://material.io/design/color/text-legibility.html#text-backgrounds

**Comment by web2033** [comment]
The same below

![2018-09-07_223815](https://user-images.githubusercontent.com/11320080/45240043-f6106e80-b2ef-11e8-8db0-520e36bf11ca.jpg)

**Comment by williamernest** [comment]
@web2033 Thanks for filing this issue. We notified the material.io team about the mistake.
