### ISSUE TITLE
MDC Tab Indicator Vertical

### ISSUE THREAD

**Issue by MarcosRakesh** [material-components/material-components-web#3537]
### What MDC Web Version are you using?
Latest
### What browser(s) is this bug affecting?
Latest
### What OS are you using?
Windows 10 (Last Build)
### What are the steps to reproduce the bug?
N/A
### What is the expected behavior?
`mdc-tab-indicator` should have an option for vertical indicator. Can be used on vertical tabs, `mdc-list` to indicate selected item or other places where design require.
### What is the actual behavior?
`mdc-tab-indicator` can't be used vertical and shouldn't be limited only to horizontal.
### Any other information you believe would be useful?
Something like in this image:
![MDC-Tab-Indicator](https://i.imgur.com/z31ekRj.png)
Any workaround to get working on vertical?

**Comment by williamernest** [comment]
@MarcosRakesh Thanks for asking this. I have reserved time to ask our design team if this is a use case we should support. I'll update this issue when I get a response.

**Comment by williamernest** [comment]
@MarcosRakesh Thanks for your patience. We talked it over with our design team and this isn't a feature we'll be adding to the line indicator. The guidance from design was that tabs that are arranged in a vertical list should use a drawer (or list).

**Comment by aleksandr-guryanov** [comment]
![image](https://user-images.githubusercontent.com/5307826/71347334-f3409800-258b-11ea-92e7-9d941cc1b155.png)
How to do the same?
