### ISSUE TITLE
Installing the same version of MDC after some time breaks the project.

### ISSUE THREAD

**Issue by amrittb** [material-components/material-components-web#3538]
I know this is currently in 0.x release so there are breaking changes every now and then. But, when I try to install the same version of MDC after a couple of weeks in another machine, it breaks the project with unexpected errors. What can be done to solve this?

**Comment by williamernest** [comment]
@amrittb That doesn't sound right. Are you using a lock file to ensure you're getting the exact same version of each dependency? Can you elaborate on how you're using/installing the components and how you're installing them on the other machine (including node/npm versions) ?

**Comment by williamernest** [comment]
Closing this issue due to no response. Feel free to update it if you still need help.
