### ISSUE TITLE
expandable chip - request for code example

### ISSUE THREAD

**Issue by mhebrard** [material-components/material-components-web#3539]
On Material.io, under Design / Chip / Input chip
There is a section 

> Expandable
> Input chips can expand to show more information or options.

with a video of the behavior.
Is there any example code of that feature ?
(I am particularly interested by a web implementation.)

**Comment by williamernest** [comment]
@mhebrard Thanks for filing this issue. We don't have that functionality available within the MDC Web library yet. You could probably match that behavior using animations and a menu-surface, but this isn't something we've been able to build yet.
