### ISSUE TITLE
TextField outlined variant overflow problem

### ISSUE THREAD

**Issue by robbyrice** [material-components/material-components-web#3549]
This issue only applies to the outlined variant of the TextField component as far as I can tell. It seems that the ::before and ::after pseudo elements are being used for the outline of the text field in some capacity. Their width is set to 200%, but I'm not to sure why. This results in any element that is positioned to the of the text field being pushed over significantly. It also results in a horizontal scrollbar if the text field is positioned close to the right edge of the screen or if its size is set to 100%. I've found that setting the the ::before and ::after elements to `width: auto;` solves this problem but I'm not sure if that has any other side affects.

### What MDC Web Version are you using?

0.39.3

### What browser(s) is this bug affecting?

All

### What OS are you using?

All

### What are the steps to reproduce the bug?

I've created a [CodePen](https://codepen.io/robbyrice/pen/XPEvva) with a normal text field and an outlined text field that shows the problem. If you uncomment the `width: auto;` CSS rule then you will see the horizontal scrollbar disappears.

### What is the expected behavior?

Adding `width: 100%;` to an outlined TextField component should NOT produce a horizontal scrollbar.

### What is the actual behavior?

Adding `width: 100%;` to an outlined TextField component produces a horizontal scrollbar on the page.

**Comment by williamernest** [comment]
@robbyrice Thanks for filing/finding this issue. We need the `:before` and `:after` elements for the states, which are added to the `mdc-text-field` (even though they don't show on the outlined variant) . You can fix this by simply placing the textfield in a parent element and setting `overflow: hidden` on that parent. 

https://codepen.io/williamernest/pen/WgJzWK

**Comment by robbyrice** [comment]
@williamernest thanks for the response. I had tried setting `overflow: hidden` on the `mdc-text-field` element itself and found that didn't work. I didn't think to try on a parent element :). Your suggestion worked as expected and fixed my issue.
I am a little curious as to the need for such a wide surface for states. I've seen issues and PRs go by referring to states but haven't looked into it. Would you be able to provide a quick explanation?
