### ISSUE TITLE
How about IE9/IE10?

### ISSUE THREAD

**Issue by xunjianxiang** [material-components/material-components-web#355]
Can i use it in IE9/IE10?
Just use the css file.

**Comment by traviskaufman** [comment]
Unfortunately, we cannot invest the development time and effort into maintaining components for browsers less than two major versions ago. Specifically, for browsers like IE9 which don't support / have limited support for things like flexbox and calc() - which we rely heavily on - the cost of supporting those browsers is too high. 

Most of our css-only solutions for components _should_ work in IE10, although we only test against IE11.
