### ISSUE TITLE
MDC Select - Options cannot be seen and down arrow color stays black on dark theme

### ISSUE THREAD

**Issue by JPlow85** [material-components/material-components-web#3550]
### What MDC Web Version are you using?

v0.39.0-0

### What browser(s) is this bug affecting?

Vivaldi, Chrome, Edge

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. Run the demo server
2. Go to http://localhost:8081/theme/index.html?theme=dark (note 8080 on most machines)
3. Observe the mdc-select component's behavior when opened

### What is the expected behavior?

1. The down arrow should be white (with opacity applied) due to dark background
2. The user should be able to read all options associated with select. The text color needs to be set back to black or the select background needs to be set to theme color.

### What is the actual behavior?

1. Down arrow continues to use black.
2. User cannot see the select options as they are the same color as the select background.

### Images

![image](https://user-images.githubusercontent.com/18597960/45451207-3d4f8400-b68f-11e8-9c88-c943ad4f5070.png)

**Comment by williamernest** [comment]
@JPlow85 Thanks for filing this issue. We have a PR to fix this behavior ready so it should be fixed by the next release.
