### ISSUE TITLE
Screenshot test CI task hanging/killed while comparing against master

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3555]
We're seeing PRs consistently fail the screenshot test task, and when looking at the logs, the last thing logged is always "Comparing 461 screenshots to master", but then nothing happens, the process gets killed, and exits with 137 (which IIUC is 128 + 9 signifying that something sent SIGKILL).

I'm going to try commenting out the compare-vs.-master logic for now, but it'd be nice to figure out why this is suddenly happening very often.

**Comment by acdvorak** [comment]
I bet this is a concurrency issue. Comparing 461 images in parallel is probably causing OOMs and/or lock contention.

I'll see if I can compare the images in batches of 50 at a time.
