### ISSUE TITLE
Slider not initializing properly with display: none

### ISSUE THREAD

**Issue by dominik-korsa** [material-components/material-components-web#3557]
When trying to init the slider while the container is `display: none` it isn't displayed and doesn't behave correctly. I have to init it after changing it to display: block. 
Hope that will help and sorry for the minimal description. I'll try to submit more info when I have time.

**Comment by williamernest** [comment]
@dominik-korsa Thanks for filing this issue. The mdc-slider components has a `.layout()` method that should be called after switching to `display: block` if instantiated when when `display: none`.
