### ISSUE TITLE
[App Top Bar] Toolbar Icon is hidden when showing [Dismissible Drawer]

### ISSUE THREAD

**Issue by euclid1990** [material-components/material-components-web#3563]
## Bugs

[App Top Bar] End Icon is hidden when trigger show [Dismissible Drawer]

### What MDC Web Version are you using?

v0.39.0

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

MacOS

### What are the steps to reproduce the bug?

Please see this video:
https://gyazo.com/91bd3586ba621164117f5b0814670340

### What is the expected behavior?

Icon in Topbar is Hide

```js
<section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">
    <router-link to="/sign-out" class="material-icons mdc-top-app-bar__action-item" aria-label="Sign out" alt="Sign out">exit_to_app</router-link>
</section>
```

### What is the actual behavior?

Please show icon in Topbar when App Drawer show up.

## Cause of bug

```
<header class="mdc-top-app-bar">
  <div class="mdc-top-app-bar__row" id="app-bar" data-mdc-auto-init="MDCTopAppBar">
    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
      <button class="material-icons mdc-top-app-bar__navigation-icon mdc-ripple-upgraded--unbounded mdc-ripple-upgraded">menu</button>
      <span class="mdc-top-app-bar__title">App</span>
    </section>
    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">
      <router-link to="/sign-out" class="material-icons mdc-top-app-bar__action-item" aria-label="Sign out" alt="Sign out">exit_to_app</router-link>
    </section>
  </div>
</header>
```
I think this problem is due to section toolbar have attribute ` justify-content: flex-end;`
![image](https://user-images.githubusercontent.com/5584709/45524110-f1b7ea00-b7f6-11e8-9e69-3f6a04732659.png)
And when Drawer is showing, `header` width still 100%, and section toolbar is hidden.
https://gyazo.com/c0b74ea2cebe0c3b29736afbb087e081

**Comment by williamernest** [comment]
@euclid1990 Can you check that your DOM structure looks like the example listed in the mdc-drawer readme? We added a class to be used for the content/top app bar that would adjust the width of the top app bar to accommodate a drawer. 

https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer#usage-with-top-app-bar

**Comment by williamernest** [comment]
@euclid1990 I don't think `app-bar` class is going to help but you may need `mdc-drawer-app-content` around the top app bar and main conntent area of your page. The drawer looks for that element to adjust the width when animating open.

**Comment by euclid1990** [comment]
@williamernest I have already add this class `mdc-drawer-app-content` in content before you suggested add `app-bar`.
anw, it work fine ! see here: https://gyazo.com/43ead9a74a2c23b87d24bc3a0323aee4
