### ISSUE TITLE
Dismissible MDCDrawer should be closed by default; isn't working per documentation

### ISSUE THREAD

**Issue by tjb1982** [material-components/material-components-web#3569]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

> 0.39.3

### What browser(s) is this bug affecting?

> Chromium Version 69.0.3497.81 (Official Build) Arch Linux (64-bit)

### What OS are you using?

> Linux 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux

### What are the steps to reproduce the bug?

I'm following the basic dismissible example [here](https://material.io/develop/web/components/drawers/#usage-with-top-app-bar) working using "native" web components with shadow DOM, etc., (importing the styles into my HTMLElement using modules via webpack). The tutorial says that the dismissible drawer should be closed by default, but it's visible for me. Chromium tells me the display rule for `.mdc-drawer--dismissible` is `none`, but it's being overrided by `.mdc-drawer` as `flex`.

### What is the expected behavior?

> CSS class `.mdc-drawer--dismissible` should be closed by default

### What is the actual behavior?

> `.mdc-drawer--dismissible` is not closed by default

**Comment by williamernest** [comment]
@tjb1982 Thanks for filing this issue. The drawer does initialize closed, and the `mdc-drawer--dismissible` class is included after the `mdc-drawer` so it sounds like a build issue or your styles are being included in the incorrect order (`mdc-drawer` might be included after `mdc-drawer--dismissible`) 

If you can provide a reproducible example we could help you troubleshoot.

**Comment by williamernest** [comment]
Closing this issue due to no response. Feel free to leave more information if you still need assistance.
