### ISSUE TITLE
Emit events for open/close drawer actions

### ISSUE THREAD

**Issue by deviousasti** [material-components/material-components-web#357]
I noticed that the event pattern is implemented in `MDCComponent`.
Is there a plan for components to emit events?

For example,
`MDCTemporaryDrawer` could emit an open/close event - this would allow quick integrations without implementing the foundation adapters, and wiring up event handlers is certainly easier.

I was implementing mdc bindings for Knockout - and I have to subclass the `MDCTemporaryDrawerFoundation` just to get access to `open`/`close` in a non-hackish way.

**Comment by traviskaufman** [comment]
We do emit events for components such as [menus](https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu#handling-selection-events) and [selects](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#using-the-full-fidelity-js-component)

For things like `open`/`close`, we usually attach CSS classes to them, since that's how we represent the UI state of our components. What were you looking to do in particular with `open`/`close` such that you need to subclass the foundation and override the methods?

**Comment by deviousasti** [comment]
I was integrating mdc with Knockout –
A boolean observable was bound to the state of the drawer.
Changing the observable in the viewmodel would open/close the drawer.
This works perfectly.
 
However, when the user closed the drawer manually, there was no easy way of knowing
when the drawer was closed so as to update the observable to false.
This led to an inconsistent state for the view model where the user had closed the drawer, but the
viewmodel believes that it is still open.
 
There are other viewmodels observing the drawer state – so that it can ‘resume’ when the drawer is closed.
To get it to work, I had to go the foundation route; however, if there were open/close events,
a lot of boilerplate could have been avoided.

**Comment by traviskaufman** [comment]
I tried working around this with a vanilla JS drawer, and I also ran into issues. I also tried using a foundation and ran into lots of boilerplate and issues as well. After revisiting this, I feel that the drawer could definitely benefit from these events, especially given that there are multiple ways to close a drawer. We also have similar events for when  a menu is selected or cancelled.

Aside: I'm going to create a follow-up issue to revisit the Temporary Drawer adapter API as I ran into some issues when trying to implement a KO binding with it.

**Comment by traviskaufman** [comment]
To be clear, the work I believe needs to be done here includes:

- Adding a `notifyOpen() => void` method to the drawer's adapter API, which is called when a drawer is open
- Adding a `notifyClose() => void` method to the drawer's adapter API, which is called when a drawer is closed. Note that this may need to take touch dragging into account.
- Have the component broadcast a `MDCTemporaryDrawer:open` event as its `notifyOpen()` adapter implementation
- Have the component broadcast a `MDCTemporaryDrawer:close` event as its `notifyClose()` adapter implementation

**Comment by deviousasti** [comment]
On reviewing the class structure, I find there not a clearly demarcated separation of concerns between the foundation implementation and the component classes.

This is what the class structure looks like now:

```
    class MDCComponent {
        constructor(root: HTMLElement, foundation?: MDCFoundation, ...args);
        private foundation_: MDCFoundation;
        initialize();
        destroy();
        getDefaultFoundation(): MDCFoundation;
    }

    class MDCFoundation {
        constructor(adapter);
        destroy();
        static defaultAdapter; //not implemented 
    }
    namespace drawer {

        class MDCTemporaryDrawer extends MDCComponent {
            open: boolean;
        }

        class MDCTemporaryDrawerFoundation extends MDCFoundation {
            open();
            close();
        }
    }

```

It's not possible to really subclass the foundation class to achieve intended behavior.
The hard work of implementing the boilerplate foundation methods is done in `getDefaultFoundation()` - however this is an instance method. You are required to create an instance of `MDCTemporaryDrawer` to retrieve the default foundation implementation, but components don't have default constructors - and calling the constructor causes the component to be initialized and bound to the element. Additionally, the default foundation refers to the attached element property on the component in a closure - it looks like a circular reference. 

I know this is under heavy development - I hope I'm not being too hard on you guys.

**Comment by traviskaufman** [comment]
No this is good feedback; it's exactly the type of thing we're looking for while developing this library :)

**Comment by anton-kachurin** [comment]
If nobody is working on this issue at the moment, can I give it a shot? Currently writing a Knockout library based on MDC-Web, and don't want to use hacks for this component.

**Comment by traviskaufman** [comment]
@anton-kachurin go for it! Assigned the issue to myself and updating it in tracker.

**Comment by traviskaufman** [comment]
@anton-kachurin Are you still interested in working on this? Anything we can help with?

**Comment by daegren** [comment]
@traviskaufman I was going to take a look at implementing this, should be very similar to the implementation of `notifyAccept` and `notifyCancel` on the drawer component.

**Comment by anton-kachurin** [comment]
@traviskaufman Sorry about this. I was really busy recently. I'll start it today.
