### ISSUE TITLE
Setting .value on MDCSelect (auto-init) does not trigger change listeners.

### ISSUE THREAD

**Issue by moorage** [material-components/material-components-web#3577]
## Summary

I have a `<select>` field whose parent has ` data-mdc-auto-init="MDCSelect"`.  When I call `selectEl.parentElement.MDCSelect.value = 'newvalue'`, the change listeners do not get called, even though the selected option displayed changes visually.  When I use the mouse to change the value to `newvalue`, the change listeners *do* get fired. 

Code pen: https://codepen.io/moorage/pen/vzVaqw

### What MDC Web Version are you using?

`material-components-web@0.39.3`, specifically https://unpkg.com/material-components-web@0.39.3/dist/material-components-web.min.js

### What browser(s) is this bug affecting?

Chrome
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36`

### What OS are you using?

Mac OS 10.13.6

### What are the steps to reproduce the bug?

Code pen: https://codepen.io/moorage/pen/vzVaqw

HTML:
```html
<div class="mdc-select mdc-select--outlined" id="my-select-MDCSelect" data-mdc-auto-init="MDCSelect">
  <select name="my_select" id="my-select" class="mdc-select__native-control">
    <option value="false" selected>
    No
    </option>
    <option value="true">
    Yes
    </option>
  </select>
  <label class="mdc-floating-label">Test</label>
  <div class="mdc-notched-outline">
    <svg>
      <path class="mdc-notched-outline__path"></path>
    </svg>
  </div>
  <div class="mdc-notched-outline__idle"></div>
</div>
```
Handler:
```js
window.mdc.autoInit();
document.getElementById("my-select").parentElement.MDCSelect.listen("change", function(ev) {
  alert(document.getElementById("my-select").MDCSelect.value);
});
```
Change value via javascript:
```js
document.getElementById("my-select").parentElement.MDCSelect.value = "true";
```
The above does not call the change listener function.

### What is the expected behavior?

Either `document.getElementById("my-select").parentElement.MDCSelect.value = "true"` should trigger the change listeners.

Alternatively, I'd love to trigger the change listeners being called myself.

### What is the actual behavior?

No change listener called.

**Comment by williamernest** [comment]
@moorage Thanks for filing this issue. The native select does not emit change events when the value is changed programmatically, which is what our component is replicating. You can however emit your own change event after programmatically changing the select by emitting an event using either a native event or using our `.emit` API. 

https://codepen.io/williamernest/pen/mGQqqz

**Comment by moorage** [comment]
Great!

**Comment by brycekirk** [comment]
Just want to note that if your data-value is a number, you need to convert it to a string, so:
```
select.value = 1 // This won't work
select.value = '1' // This will work
select.emit('change');
```
