### ISSUE TITLE
[Question] Top app bar tabs

### ISSUE THREAD

**Issue by uiii** [material-components/material-components-web#3589]
Hi, in material design docs there is lot of examples of tabs inside top app bar:
![](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1uV0Rzc2Q2RzWEz9vguOME1SoCQofEmld%2Ftabs-usage-01.png)

I tried this but have a problem with the colors: https://codepen.io/rustemgareev/pen/eyKjyG

Could you give me an example how to achieve this? Thanks

**Comment by abhiomkar** [comment]
@uiii Thanks for filing issue.

If you're using sass, this'll require a new mixin - `mdc-tab-accessible-fill-color` in MDC Tab component that can be used to blend with top app bar. I'll update our tracker to add this.

I forked your codepen and added some style customizations to achieve above result. Here is my updated [codepen](https://codepen.io/abhiomkar/pen/PdvrzP?editors=1100) for example.

**Comment by abhiomkar** [comment]
I'm closing this one. Issue #3633 for tracking on the FR.
