### ISSUE TITLE
MDCTypography: Please include line height specs

### ISSUE THREAD

**Issue by bananatranada** [material-components/material-components-web#3590]
`Regardless of pt / sp size, a text’s baseline must sit on the 4dp grid. Line-height must be a value divisible by 4 to maintain the grid.`

`A text’s line height is proportional to its type size.`

These are the only specs that are on the material [website](https://material.io/design/typography/understanding-typography.html). 

Could you guys provide more specific guidelines for Roboto? I'm honestly just curious what each line height should be for each header, subtitle, button, etc. Currently I'm using multiplying it by 1.4 and getting the nearest value that is divisible by 4.

Thanks

**Comment by havesomeleeway** [comment]
Not sure if this attempts to solve your concern, but have you tried using the inspector tool on the demo site for typography? You will be able to check out the line heights for Header, Subtitle, etc.

https://material-components.github.io/material-components-web-catalog/#/component/typography

![image](https://user-images.githubusercontent.com/25948209/46411861-6b385d80-c74f-11e8-9ab3-8b675360ee81.png)

**Comment by williamernest** [comment]
Sorry for the delay on this issue. I talked with the designer who manages our typogrpahy subsystem and they indicated that the line-height is not something that is (or should be) standardized across all typography sizes. In some instances, it might make sense to have line-height be 1.5* the font-size (for example, when reading an article) but in other instances you could want to have a more dense layout (such as on a card). Our components include line-height to be used within the components but you should override the line-height to make sense for your specific content and use case.
