### ISSUE TITLE
Textarea demo should not include ripple

### ISSUE THREAD

**Issue by iczman** [material-components/material-components-web#3604]
### What MDC Web Version are you using?

0.39.3

### What browser(s) is this bug affecting?

Chrome 69.0.3497.100

### What OS are you using?

macOS

### What are the steps to reproduce the bug?

Go to https://material-components.github.io/material-components-web-catalog/#/component/text-field and inspect the textarea element

![textarea with ripple](https://i.imgur.com/eqNvy2y.png)

### What is the expected behavior?

`mdc-line-ripple` not be added to textarea.

### What is the actual behavior?

`mdc-line-ripple` added to textarea. I couldn't find anywhere in the spec that specifically disallows this, but I doubt this is by design given other variants of textarea on the same page don't have ripple. Plus the ripple will overlay with a slight offset on top of the textarea outline making it look kind of awkward.

**Comment by williamernest** [comment]
@iczman Thanks for filing this issue. I filed an issue on our catalog repo for this. 

https://github.com/material-components/material-components-web-catalog/issues/204
