### ISSUE TITLE
MDC-Web Dialog Content Section Should Be Content Div

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#3620]
W3C validator makes it clear that every HTML5 `<section>` element shall have a `header`. Since the `MDCDialog`'s `mdc-dialog__title` is defined, guiding users to use a `<section>` element for `mdc-dialog__content` leads to violating W3C spec, e.g. it is intuitive that the "title" is where the "header" element goes. See https://github.com/material-components/material-components-web/tree/master/packages/mdc-dialog

FIX:
Change the `<section>` element to a `<div>` element.

**Comment by kfranqueiro** [comment]
Thanks for pointing this out! I'm working on a PR to fix both of the issues you reported before we release.
