### ISSUE TITLE
MDC Dialog. show is not a function.

### ISSUE THREAD

**Issue by CarlosV89** [material-components/material-components-web#3638]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

@latest

### What browser(s) is this bug affecting?

Latest Chrome

### What OS are you using?

Lubuntu 18.01

### What are the steps to reproduce the bug?

Use Dialog Component as per Documentation

### What is the expected behavior?

Dialog Works

### What is the actual behavior?

Dialog doesnt work, throws an error saying that there is no function `show` in the new MDCDialog element

### Any other information you believe would be useful?

Scoping down to version `0.39.3` fixes the issue and the Dialog component works as expected

**Comment by kfranqueiro** [comment]
The 0.40.0 documentation hasn't yet been mirrored to material.io, so what you're seeing there is still 0.39.3's documentation. We have a ticket out to the site team to get that updated.

For brand-new releases, I'd highly suggest viewing the documentation via the tag on github, e.g. https://github.com/material-components/material-components-web/tree/v0.40.0/packages/mdc-dialog#mdcdialogfoundation in this case.

Sorry for the inconvenience.

**Comment by CarlosV89** [comment]
Thank you for the BLAZING fast response!!!!
