### ISSUE TITLE
Show() does not work for MDCDialog

### ISSUE THREAD

**Issue by JoeLorenzoMontano** [material-components/material-components-web#3642]
### What MDC Web Version are you using?

"https://unpkg.com/material-components-web@latest/dist/material-components-web.js"

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.

> 2. Go to https://wine-app-1537404006467.firebaseapp.com/
> 3. Attempt to open a dialog via clicking on the filter bar at the top. View output using dev tools

### What is the expected behavior?

Previously this opened the dialog

### What is the actual behavior?

Error and nothing opens

**Comment by kfranqueiro** [comment]
The 0.40.0 documentation hasn't yet been mirrored to material.io, so what you're seeing there is still 0.39.3's documentation. We have a ticket out to the site team to get that updated.

For brand-new releases, I'd highly suggest viewing the documentation via the tag on github, e.g. https://github.com/material-components/material-components-web/tree/v0.40.0/packages/mdc-dialog#mdcdialogfoundation in this case.

Sorry for the inconvenience.
