### ISSUE TITLE
[Feature request] Add a new type, or change the current version of the dismissible draw.

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#3677]
I think there should be 2 types of dismissible draws. The current one, when opened, takes up the entire left side of the screen, where as in the material guidelines there is also a version where it takes up the entire left side of the screen, apart from the top app bar.
Either that or maybe have the current version of the dismissible draws changed to be more inline with the material guidelines by not moving the top app bar out of the way.

Guideline link with requested version (also if you scroll down to visibility part under the standard draw section): https://material.io/design/components/navigation-drawer.html#standard-drawer

Examples:

Current version (running off the current documentation for dismissible draws with top app bars on my own test page):

<img width="414" alt="screen shot 2018-09-29 at 10 58 28 am" src="https://user-images.githubusercontent.com/26075792/46237107-a4cb3a80-c3d6-11e8-9079-d38de9d64c5c.png">
<img width="572" alt="screen shot 2018-09-29 at 10 50 39 am" src="https://user-images.githubusercontent.com/26075792/46236978-b7913f80-c3d5-11e8-80ae-30389e750ae8.png">

Requested version (image from the material guidelines linked above):

<img width="770" alt="screen shot 2018-09-29 at 10 49 38 am" src="https://user-images.githubusercontent.com/26075792/46236995-ca0b7900-c3d5-11e8-8c2c-4430c5c3838b.png">

**Comment by abhiomkar** [comment]
This is dismissible drawer with different layout.

I made a [codepen](https://codepen.io/abhiomkar/pen/qJdNQj?editors=1100) to show this example. Our [catalog](https://github.com/material-components/material-components-web-catalog/blob/master/src/ComponentSidebar.js) page itself uses this [layout](https://material-components.github.io/material-components-web-catalog/#/component/button) to render drawer inside top app bar's content.

**Comment by CyborgSemon** [comment]
The layout link you have goes to the MDC button page?

**Comment by abhiomkar** [comment]
Yes, I wanted give a reference to catalog page which renders dismissible drawer under Top App Bar.

![image](https://user-images.githubusercontent.com/47312/46318307-0987c000-c5a4-11e8-9a5a-0c1ebf757bde.png)

**Comment by CyborgSemon** [comment]
ohhh i see now. thanks!

**Comment by CyborgSemon** [comment]
@abhiomkar I have used that codepen example and I cant get the dismissible draw to actually dismiss. What javascript would I use to actually make the drawer open and close?

**Comment by CyborgSemon** [comment]
also, there is an issue with doing the drawer this way. it seems that if you want to use a grid inside the mdc-drawer-app-content, then it doesn't full up the whole space. If you replace all the lorem ispum with this code into the codepen that you sent earlier above, then the grid doesnt full up the entire space.

```html
<div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">this</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">is</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">cool</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">this</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">is</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">cool</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">this</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">is</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">cool</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">this</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">is</div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-1">cool</div>
    </div>
</div>
```

What it shows for me:

<img width="1440" alt="screen shot 2018-10-04 at 11 46 17 pm" src="https://user-images.githubusercontent.com/26075792/46469393-b6c23880-c82f-11e8-9307-8feb6d7c62c4.png">

Where as it should look like this: (image on the original dismissible draw as it is the only one that works with the layout grid)

<img width="1440" alt="screen shot 2018-10-04 at 11 50 56 pm" src="https://user-images.githubusercontent.com/26075792/46469637-7a430c80-c830-11e8-94e2-5b595f507f28.png">


exactly the same grid code, but on the original one, it actually fulls up the page.
