### ISSUE TITLE
MDC Menu: Update Menu & List docs for disabled item state.

### ISSUE THREAD

**Issue by adrianschmidt** [material-components/material-components-web#3679]
## Bugs

It seems like the possibility to disabled menu-items was lost in the 0.39.0 rebuild of mdc-menu? The documentation for how to disable a menu-item has been removed, and following the old documentation does not disable the menu-item when using a later version of MDC Web.

The changelog does not cover this as a breaking change (nor in any other way), which makes me suspect that either the removal of this feature was accidental, or the feature still exists, but the new way to access it has not been documented.

### What MDC Web Version are you using?

0.40.0

### What browser(s) is this bug affecting?

Chrome 69.0.3497.92 (Official Build) (64-bit)
UA-string: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36`

### What OS are you using?

macOS 10.13.6 ("High Sierra")

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.
>
> 1. Run the demo server
> 2. Go to localhost:8080/textfield.html
> 3. Tab-focus on the first text field
> 4. Observe the component's behavior
>
> We also have a [template on CodePen](https://codepen.io/williamernest/pen/deyxyp) which we encourage you to use to create a reproduction of
> the issue. The less time it takes for us to reproduce the issue, the less time it takes to verify and
> fix it!

I tried using the CodePen linked to above, but it didn't work correctly, even with the supplied example. And since this is more of a report of a potentially removed feature than a bug appearing in a specific circumstance, I won't put too much time into trying to reproduce it on CodePen, unless you believe that doing so would be helpful in this specific case.

### What is the expected behavior?

There should be a way to disable specific menu-items in an otherwise enabled menu.

### What is the actual behavior?

Following the documentation for MDCMenu <0.39.0 does not disable the menu-item when using MDCMenu >=0.39.0, and there is no new documentation on how this can be achieved in another way.

### Any other information you believe would be useful?

I can't think of anything right now, but just ask and I'll be happy to do what I can to deliver.

**Comment by abhiomkar** [comment]
Thanks for reporting this issue.

MDC List which is used inside menu needs to support disabled state. I added this feature request to our tracker.

**Comment by williamernest** [comment]
@adrianschmidt You can use the `mdc-list-item--disabled` class to your Menu List items to enable the disabled state of an individual list item.

**Comment by adrianschmidt** [comment]
> @adrianschmidt You can use the `mdc-list-item--disabled` class to your Menu List items to enable the disabled state of an individual list item.

Thanks! That worked, for both mouse and keyboard control (and visually of course). Then the issue is just that this solution has do be documented.
