### ISSUE TITLE
CSS Custom Properties should be enabled in Edge >=16

### ISSUE THREAD

**Issue by dfreedm** [material-components/material-components-web#3685]
As noted in https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_mixins.scss#L28-L29, MDC styles currently disable CSS Custom Properties for Edge due to [a bug in Edge 15 with psuedo elements](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12414257/) . 

However, this bug was fixed in Edge 16, and to my knowledge there are no remaining CSS Custom Property issues in Edge.

Given that you would probably like to select whether to enable CSS Custom Properties via `@supports`, I think another `@supports` for something in [this table from CanIUse](https://caniuse.com/#compare=edge+15,edge+16&compare_cats=CSS) would be sufficient to enable CSS Custom Properties for Edge 16+.

Looks like CSS Grid, or viewport units are easy ones to use with `@supports`.

**Comment by azakus** [comment]
Here's an example rule using CSS grid to detect between IE 11, Edge 15, and Edge 16+:
https://glitch.com/edit/#!/orange-sleet?path=index.html:23:0

**Comment by abhiomkar** [comment]
Thanks @azakus for bringing this to our notice. Added this to icebox to track it.

**Comment by asyncLiz** [comment]
Custom properties are enabled in Edge now, closing this issue
