### ISSUE TITLE
[Help Wanted] How to get a card to expand with an animation?

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#3687]
Is there anyway to get cards to expand with an animation when content is changed or added to them? I have an ajax file that is called when a button is clicked to change the content inside a card, and currently it just changes the size of the card instantly without smoothly changing the size of it to fit the new content.

**Comment by abhiomkar** [comment]
This issue seems like out of scope of MDC Web. MDC Card component is not opinionated about the animation. I'm sure there are many external resources which helps you achieve this. 

You might find this [video](https://www.youtube.com/watch?v=P2glQ0fz7DM) helpful to get started.
