### ISSUE TITLE
[Help wanted] How to instantiate Switch to toggle on/off

### ISSUE THREAD

**Issue by havesomeleeway** [material-components/material-components-web#3688]
### What MDC Web Version are you using?
0.40

### What is the expected behavior?

> Please describe what the component/code should be doing that it's not.

The switch should be able to toggle on/off as seen on:
 https://material-components.github.io/material-components-web-catalog/#/component/switch

### What is the actual behavior?

> Please describe what the component/code is actually doing that's different from what it should be
doing.

I followed the steps as listed on: 
https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch

Used the basic HTML Structure

```html
<div class="mdc-switch">
  <div class="mdc-switch__track"></div>
  <div class="mdc-switch__thumb-underlay">
    <div class="mdc-switch__thumb">
        <input type="checkbox" id="basic-switch" class="mdc-switch__native-control" role="switch">
    </div>
  </div>
</div>
<label for="basic-switch">off/on</label>
```
Imported the style:
```css
@import "@material/switch/mdc-switch";
```
Instantiated the JS
```js
import {MDCSwitch} from '@material/switch';

const switchControl = new MDCSwitch(document.querySelector('.mdc-switch'));
```

However, I am unable to toggle on/off for my switch. I notice that the constant is declared in the javascript but nothing is done to the variable. Am I missing something?

Here is what my switch looks like, without the ability for me to toggle the on/off
![image](https://user-images.githubusercontent.com/25948209/46347643-e54ce180-c67e-11e8-8584-48c2e61e977a.png)

**Comment by kfranqueiro** [comment]
Do you see any errors in your browser's dev tools console? This works for me: https://gist.github.com/kfranqueiro/d8046605ed5372e65abac4c03da444d4

**Comment by havesomeleeway** [comment]
I don't know what came over me to not check the console first. Deleted some junky js that was causing the bug. Works now. Thanks @kfranqueiro. Much appreciated!
