### ISSUE TITLE
bundle.js throws an error when a constant variable is not found and wont load any other JS underneath it

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#3694]
## Bugs

When I have a page that uses some of the imported JS, but not all of it, it will throw an error at the first const variable that it comes across and not load any of the JS underneath it. For example, If I have a main page with a top app bar, drawer, lists and no text inputs, and I have declared the constant for for the text inputs before the constant for the drawer, then the draw wont work on the main page because it throws an error because it cant find any text inputs. However, when I have a contact page that uses all of the listed constants above, and it has text inputs, then everything is fine and the drawer works normally.

### What MDC Web Version are you using?

> 0.40

### What browser(s) is this bug affecting?

> Chrome: 69.0.3497.100 (Official Build) (64-bit)
>
>(Haven't tried any others)

### What OS are you using?

> MacOS 10.14

### What is the expected behavior?

> If the constant variable is not found, then it should be ignored and the code should just move on 

### What is the actual behavior?

> If the constant variable is not found, it throws an error in the console and doesn't load any other JS constants underneath it

### Any other information you believe would be useful?

This is the error that it throws at me when I open the page that doesn't have any text fields:

<img width="543" alt="screen shot 2018-10-03 at 11 17 24 pm" src="https://user-images.githubusercontent.com/26075792/46404722-85c80200-c762-11e8-8fd8-c742959e122d.png">

But when the exact same page has a text field, the error doesn't show up.

This is the text field that I'm using. (Basic HTML structure from the [documentation](https://material.io/develop/web/components/input-controls/text-field/))

```html
<div class="mdc-text-field">
  <input type="text" id="my-text-field" class="mdc-text-field__input">
  <label class="mdc-floating-label" for="my-text-field">Hint text</label>
  <div class="mdc-line-ripple"></div>
</div>
```

And this is the structure that I have my app.js file

```js
import {MDCTextField} from '@material/textfield';
const textField = new MDCTextField(document.querySelector('.mdc-text-field'));

import {MDCList} from "@material/list";
const list = MDCList.attachTo(document.querySelector('.mdc-list'));
list.wrapFocus = true;

import {MDCDrawer} from "@material/drawer";
const drawer = MDCDrawer.attachTo(document.querySelector('.mdc-drawer'));

import {MDCTopAppBar} from "@material/top-app-bar";
const topAppBar = MDCTopAppBar.attachTo(document.getElementById('app-bar'));
topAppBar.setScrollTarget(document.getElementById('main-content'));
topAppBar.listen('MDCTopAppBar:nav', () => {
    drawer.open = !drawer.open;
});
```

The main reason for this being an issue, is if I am having a site that on one page has text inputs, but no drawer, and on another page has a drawer but no text inputs, then no matter what order I put the text inputs and drawer constants in the app.js file, on one of the pages it will break entirely.

I guessing this would also be an issue with other components that use JS as well if they are used on one page but not on another. but I have not tested that yet.

**Comment by abhiomkar** [comment]
That's because `document.querySelector('.mdc-text-field')` returns `null` when it can't find the element text field element on the page. You need to check for the existence of this element before instantiating text field.

Here is one way to do it.

```
[].forEach.call(document.querySelectorAll('.mdc-text-field'), function(textFieldEl) {
  MDCTextField.attachTo(textFieldEl);
});

```

**Comment by CyborgSemon** [comment]
Ahhhhhh. Awesome thank you! I think it would be a good idea to include something like this into the importing JS documentation.
Thanks again!

**Comment by asyncLiz** [comment]
Closing this since it was answered
