### ISSUE TITLE
drawer foundation.opened and foundation.closed should be private

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#3695]
Vanilla component does not use `foundation.opened` or `foundation.closed`. These should be private methods.

**Comment by abhiomkar** [comment]
Did you mean `opened()` and `closed()` methods in Dismissible Drawer Foundation? These are marked with `@protected` visibility for Modal Drawer Foundation.

**Comment by moog16** [comment]
missed that! Thanks :)
