### ISSUE TITLE
Material Theme Editor Not working in Sketch 52.1

### ISSUE THREAD

**Issue by sogen** [material-components/material-components-web#3704]
### What MDC Web Version are you using?

sketch plugin: Material Theme Editor 1.6.206738809

### What browser(s) is this bug affecting?

app: Sketch 52.1

### What OS are you using?

OSX High Sierra

### What are the steps to reproduce the bug?

1.- Run New Theme
2.- Select one of the pre-made templates
3.- Click Save

### What is the expected behavior?

4.- File is saved

### What is the actual behavior?

File is not saved.
Can't go past this step.

**Comment by kfranqueiro** [comment]
Thanks for the report. This repository isn't related to the Material Theme Editor, but based on comments I've seen in the Material Components discord, this has been experienced both externally and internally and is now being tracked by the appropriate team.
