### ISSUE TITLE
npm start failed  The react-scripts package provided by Create React App requires a dependency: "babel-loader": "8.0.4" following steps doesnt work

### ISSUE THREAD

**Issue by SemihKoc** [material-components/material-components-web#3712]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

> Please be specific, e.g. _major.minor.patch_

### What browser(s) is this bug affecting?

> Please include the browser version. A user-agent string is also quite helpful.

### What OS are you using?

> Please include the OS version.

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.
>
> 1. Run the demo server
> 2. Go to localhost:8080/textfield.html
> 3. Tab-focus on the first text field
> 4. Observe the component's behavior
>
> We also have a [template on CodePen](https://codepen.io/williamernest/pen/deyxyp) which we encourage you to use to create a reproduction of
> the issue. The less time it takes for us to reproduce the issue, the less time it takes to verify and
> fix it!

### What is the expected behavior?

> Please describe what the component/code should be doing that it's not.

### What is the actual behavior?

> Please describe what the component/code is actually doing that's different from what it should be
doing.

## Feature Requests

> If you're interested in requesting a new component or proposing UX changes to an existing
> component, please read our [Component Request Policy](https://github.com/material-components/material-components/blob/develop/COMPONENTS_REQUEST_POLICY.md) before opening an issue.

If you have an idea for a new feature, we'd love to hear about it! Please provide enough
information regarding the feature such that we'll be able to evaluate the appropriateness and
feasibility of your request. Try to be as specific as possible regarding your motivation, use-case,
and potential API or affects on other APIs (where applicable). The more detailed your proposal is,
the easier it will be for us to understand and evaluate it. [This Meta.SE answer](http://meta.stackexchange.com/a/259196) also contains great general guidelines for writing
feature requests.

If you'd like to work on a component, please ensure that you *submit an Engineering Outline before
submitting a pull request*. You can read more about this in our [contributing docs](https://github.com/material-components/material-components-web/blob/master/CONTRIBUTING.md#building-components).

MDC Web is still under active development. You can see our current progress on [master](https://github.com/material-components/material-components-web/tree/master) as well as an overview of our [architecture and practices](https://github.com/material-components/material-components-web/blob/master/docs/code).

Our team prioritizes responding to as many engineering and user experience questions as possible. We do not support responses to questions outside of these areas at this time.

**Comment by SemihKoc** [comment]
Thanks for the response @CyborgSemon That install line gives me the same error "npm install --save-dev babel-core@6 babel-loader@7 babel-preset-es2015 babel-plugin-transform-object-assign"

**Comment by SemihKoc** [comment]
im gonna try with getting started guide

**Comment by CyborgSemon** [comment]
Try going over the entire getting started guide in a new folder. if you have already installed babel in the folder that you ran the install command then it wont work.
So yeah. try in a new folder.

**Comment by acdvorak** [comment]
If you're using React, you may want to give [MDC React](https://github.com/material-components/material-components-web-react) a try 😀

Otherwise, I would suggest creating a small git repo that demonstrates the problem, and we'll be happy to take a look.

Thanks!

**Comment by acdvorak** [comment]
@moog16 is investigating this in https://github.com/material-components/material-components-web-react/issues/326

**Comment by prashanth-sams** [comment]
@SemihKoc you have to create a file `.env.local` and put this `SKIP_PREFLIGHT_CHECK=true` for the fix

**Comment by eTechist** [comment]
> @SemihKoc you have to create a file `.env.local` and put this `SKIP_PREFLIGHT_CHECK=true` for the fix
> [follow](https://devopsqa.wordpress.com/)

Then you won't encounter other issues, That will permanently disable the messages

**Comment by prashanth-sams** [comment]
> > @SemihKoc you have to create a file `.env.local` and put this `SKIP_PREFLIGHT_CHECK=true` for the fix
> > [follow](https://devopsqa.wordpress.com/)
> 
> Then you won't encounter other issues, That will permanently disable the messages

Do we have any special fix use-case to avoid this?

**Comment by ramomex1** [comment]
i dont know but yesterday all was working great and today i just run my app and i get that error . i already reinstall node, but its the same prob
