### ISSUE TITLE
Text Field README: Add note about calling .layout() on initially hidden elements

### ISSUE THREAD

**Issue by yellow1912** [material-components/material-components-web#3715]
## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?
0.40.40
https://unpkg.com/material-components-web@0.40.0/dist/material-components-web.min.js

### What browser(s) is this bug affecting?
Google Chrome 

69.0.3497.100 (Official Build) (64-bit)

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Put the inputs inside a parent with display:none (for example a tab)
Run autoInit()
Toggle the tab and the inputs inside are not properly rendered

### What is the expected behavior?

Inputs should be properly rendered

![image](https://user-images.githubusercontent.com/374134/46599217-e2377280-cb10-11e8-889f-b73500d30898.png)

### What is the actual behavior?

The inputs are rendered incompletely like this:

![image](https://user-images.githubusercontent.com/374134/46599046-5a516880-cb10-11e8-832e-3c1c52147684.png)

### Any other information you believe would be useful?

I think it may somewhat relate to this:
https://github.com/angular/material2/issues/3346

**Comment by acdvorak** [comment]
Thanks for filing this issue!

It sounds like you just need to call the `.layout()` method on your `MDCTextField` instance after the tab becomes visible.

We should probably add this to the [Text Field README](https://github.com/material-components/material-components-web/tree/7c5dc90/packages/mdc-textfield#mdctextfield-properties-and-methods).

**Comment by yellow1912** [comment]
Thank you, you are right, calling that method fixes the issue.
