### ISSUE TITLE
Please add sign_in sign_up sign_out icons in material icons

### ISSUE THREAD

**Issue by AJ-Creations** [material-components/material-components-web#3719]
User icons, sign_in icon, sign_up icon and sign_icon are very important for both web and other applications. Please include those icons in material icons section.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

I believe you can [submit a feature request to material-design-icons](https://github.com/google/material-design-icons/issues/new).

I'll check with the Icons team to see if there's anywhere else to file feedback.

**Comment by acdvorak** [comment]
Confirmed that [icons repo](https://github.com/google/material-design-icons/issues/new) is the correct place to file requests.

Closing this issue as it does not pertain to MDC Web.

Thanks!
