### ISSUE TITLE
2FA prevents publishing to npm

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#3720]
### Problem

Publishing packages to NPM fails if the user has two-factor authentication enabled on their NPM account:

```
lerna info publish Publishing packages to npm...
lerna ERR! publish Retrying failed publish: @material/animation
lerna ERR! publish Retrying failed publish: @material/animation
lerna ERR! publish Retrying failed publish: @material/animation
lerna ERR! publish Retrying failed publish: @material/animation
lerna ERR! publish Ran out of retries while publishing @material/animation Error: Command failed: npm publish --tag latest
lerna ERR! publish npm ERR! publish Failed PUT 401
lerna ERR! publish npm ERR! code E401
lerna ERR! publish npm ERR! 404 You must provide a one-time pass. : @material/animation
```

The "official" workaround is to set a `NPM_CONFIG_OTP` env var, but that only works if you have a small number of packages.

Publishing ~10 or more packages takes longer than the 30 second OTP timeout, which causes the first few packages to be uploaded successfully whereas the remainder fail.

At that point, you have to manually check every package on npmjs.com and see if it was updated or not, and run `npm publish` on any packages that failed.

See Lerna issues [#1137](https://github.com/lerna/lerna/issues/1137) and [#1091](https://github.com/lerna/lerna/issues/1091) for more information.

### Solution

We should:

* Add instructions on how to temporarily disable and subsequently re-enable 2FA in \
    [`release-process.md`](https://github.com/material-components/material-components-web/blob/5b1348cee8302f12d552e8612d911a202be49ad5/docs/open_source/release-process.md)
* Check for 2FA in [`pre-release.sh`](https://github.com/material-components/material-components-web/blob/5b1348cee8302f12d552e8612d911a202be49ad5/scripts/pre-release.sh#L33-L39)

There's also a small typo in `release-process.md`: `npm deploy` should be `npm run deploy`.

**Comment by kfranqueiro** [comment]
Since you ran into this on the last release, can you describe what kind of failure occurs? Like, is this something we can actually support? Are there any issues in lerna about it?

**Comment by acdvorak** [comment]
Updated issue description 🙂
