### ISSUE TITLE
Textfield w/ float label gives the border a blur/shadow

### ISSUE THREAD

**Issue by aprigogin** [material-components/material-components-web#3721]
See bottom border rendering.

![image](https://user-images.githubusercontent.com/398379/46689442-d8c01000-cbcd-11e8-9ee9-8b3fde2e73b9.png)

**Comment by acdvorak** [comment]
This is probably due to SVG subpixel antialiasing 🙁

We eventually want to move away from SVG anyway, because it requires a `.layout()` call whenever the element is shown/hidden or its dimensions change. This would also allow us to reuse the outline with Select.
