### ISSUE TITLE
Border (right) is not displayed for some elements

### ISSUE THREAD

**Issue by yellow1912** [material-components/material-components-web#3736]
## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?
0.40.40
https://unpkg.com/material-components-web@0.40.0/dist/material-components-web.min.js

### What browser(s) is this bug affecting?
Google Chrome 

69.0.3497.100 (Official Build) (64-bit)

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

The right border for the text input elements are sometimes not shown. If I click on the specific input to trigger the focus event then the border is properly rendered again.

More information:
1. The site is using bootstrap 4 latest stable version
2. The site is using Angular 1.x, the content is rendered via directive, the inputs are autoInit after the view is rendered

### What is the expected behavior?

Inputs should be properly rendered

### What is the actual behavior?

The inputs are rendered incompletely like this:

![image](https://user-images.githubusercontent.com/374134/46782501-a5f25500-cd50-11e8-8071-03af25f68b96.png)

**Comment by kfranqueiro** [comment]
This sounds like possibly another issue requiring a `layout()` call akin to #3715. Is your text field being instantiated while hidden, or is its size changing after it's instantiated?

The reason focusing renders the border is it causes `notchOutline` to be called, which is the same method that `layout()` will call.

If you need further assistance, can you provide a [codepen](https://codepen.io/williamernest/pen/deyxyp)?

**Comment by yellow1912** [comment]
You are right, adding a delay with timeout fixed that. There seems to be no reliable way to detect that ALL directives have been rendered with angular 1 yet I think, so I will live with the timeout for now.
