### ISSUE TITLE
List expand and collapse states

### ISSUE THREAD

**Issue by jasonsturges** [material-components/material-components-web#3738]
Within [Material Design Lite](https://getmdl.io/), I liked the collapsible capability in menu lists, such as found in the [mega footer](https://getmdl.io/components/index.html#layout-section):

![footer](https://user-images.githubusercontent.com/1213591/46816505-bb608280-cd42-11e8-80f2-5093c3d8d625.gif)

```html
    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Features</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">About</a></li>
        <li><a href="#">Terms</a></li>
        <li><a href="#">Partners</a></li>
        <li><a href="#">Updates</a></li>
      </ul>
    </div>
```

[MDC Lists](https://material.io/develop/web/components/lists/) don't seem to incorporate this, nor [Menus](https://material.io/develop/web/components/menus/).

Material Design spec includes expand and  collapse collapse for lists
https://material.io/design/components/lists.html#types

![image](https://user-images.githubusercontent.com/1213591/46817239-5efe6280-cd44-11e8-80e8-399be93ad856.png)

Does Material Components Web have similar functionality that I'm missing, or intention to incorporate?

**Comment by acdvorak** [comment]
Thanks for filing this issue!

Unfortunately we are not planning to implement this on Web.

An earlier version of the Material Design Guidelines included [Expansion Panels](https://material.io/archive/guidelines/components/expansion-panels.html), which have similar functionality, but they were later dropped. See https://github.com/material-components/material-components-web/pull/2020#issuecomment-401488493 for more info.

**Comment by vzaidman** [comment]
@acdvorak not planning to implement at all?
can i contribute this functionality to lists?

**Comment by anatolibarski** [comment]
how this is not planned? this is one of the major features of MD... I'm quite frustrated

**Comment by anatolibarski** [comment]
> Thanks for filing this issue!
> 
> Unfortunately we are not planning to implement this on Web.
> 
> An earlier version of the Material Design Guidelines included [Expansion Panels](https://material.io/archive/guidelines/components/expansion-panels.html), which have similar functionality, but they were later dropped. See [#2020 (comment)](https://github.com/material-components/material-components-web/pull/2020#issuecomment-401488493) for more info.

But List expand/collapse state are specified. You are not planning to implement the spec?

**Comment by danielbarela** [comment]
Yeah, wait, why are you not going to implement the spec for the list expand and collapse? @acdvorak

**Comment by moog16** [comment]
@danielbarela at the time it wasn't a priority for the design team. We also have internal clients that have other needs that we as a team have not met yet. Like any team we must prioritize, and this feature did not make the cut.

**Comment by BlkPingu** [comment]
You have Collapsibles on the Material.io website. Are they part of MDC? 

https://material.io/components/cards/#usage or any subpage for the specific components, really

<img width="860" alt="Screenshot 2020-02-05 at 16 48 04" src="https://user-images.githubusercontent.com/28692167/73858555-e07edb80-4838-11ea-8739-f53319ac115f.png">

<img width="866" alt="Screenshot 2020-02-05 at 16 48 09" src="https://user-images.githubusercontent.com/28692167/73858571-e70d5300-4838-11ea-9326-afc43805ff18.png">
