### ISSUE TITLE
Side Sheet: Migrate Sass from mdc-drawer to mdc-side-sheet and make reusable

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3739]
* [x] Copy content over from mdc-drawer to mdc-side-sheet package, updating for `mdc-side-sheet` base class
* [x] Exclude mixins that only make sense for drawer (i.e. side sheet will only have border-color, shape-radius, width, surface-fill-color, ink-color, fill-color-accessible, scrim-fill-color, z-index)
* [x] Update width and shape mixins to take an optional side parameter
  * Side parameter should be phrased as `leading` and `trailing` to indicate being RTL agnostic
* [x] Remove parts that are drawer-specific (e.g. list styles)
* [x] Expose all remaining styles via mixins (parameterized by side where necessary, defaulting to trailing side), then invoke them within `mdc-side-sheet.scss`

Drawer will be updated to reuse these new mixins in a separate task.

**Comment by abhiomkar** [comment]
Closing this issue as obsolete.
