### ISSUE TITLE
Side Sheet: Migrate JS from mdc-drawer to mdc-side-sheet and make reusable

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3741]
* [x] Copy JS files from `mdc-drawer` to `mdc-sidesheet` and rename classes
* [x] Update constants to use `mdc-side-sheet` as the base name of classes
* [x] Remove list logic from `MDCSideSheet` class
* [ ] Create common helper for returning adapter implementation, to be used by `MDCSideSheet` and `MDCDrawer`
  * This would at least need a parameter to distinguish the prefix for the opened and closed events for each component
  * This probably makes sense to be a separate util function; it seems unlikely to be able to easily extend one component class from the other without overriding a bunch of code in the parent anyway

**Comment by abhiomkar** [comment]
Closing this issue as obsolete.
