### ISSUE TITLE
Drawer: Update MDCDrawer component to reuse mdc-side-sheet foundations

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3743]
* Best-case scenario: Directly use mdc-side-sheet foundations with no changes necessary
* Worse-case scenario: Update MDCDismissibleDrawerFoundation to extend MDCDismissibleSideSheetFoundation; MDCModalDrawerFoundation will presumably continue to extend MDCDismissibleDrawerFoundation

**Comment by abhiomkar** [comment]
Closing this issue as obsolete.
