### ISSUE TITLE
Uncaught ReferenceError: MDCTopAppBar is not defined

### ISSUE THREAD

**Issue by henriquehbr** [material-components/material-components-web#3746]
## Bugs

`Uncaught ReferenceError: MDCTopAppBar is not defined`
[Codepen](https://codepen.io/vivekmarakana/pen/Vpxrdq)

### What MDC Web Version are you using?

> 0.40.1

### What browser(s) is this bug affecting?

> Chrome 69

### What OS are you using?

> Windows 7

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.
>
> 1. Include MDC JS and CSS (from unpkg)
> 2. Add drawer html
> 3. Instanteate drawer JS component
> 4. The JS error appear on the console

### What is the expected behavior?

> The drawer should open/close whenever the user click on the menu button
> **IMPORTANT: I can't use node, neither npm**

### What is the actual behavior?

> The top app bar is displayed, but i can't open/close the drawer by clicking on the menu button

**Comment by thdk** [comment]
@henriquehbr, can you update the codepen with the code you are using to load the material design javascript library for the top-app-bar and how you initialize it?

**Comment by henriquehbr** [comment]
Solved it using the automatic instantiation method!

`drawer = mdc.drawer.MDCDrawer.attachTo(document.querySelector(".mdc-drawer"));`

> Just a few MDC components have this on their documentation, for example, [the snackbar](https://github.com/material-components/material-components-web/tree/master/packages/mdc-snackbar), this code must be referenced on the documentation of every MDC component
