### ISSUE TITLE
Material design web MDCTab:interacted event not emitting

### ISSUE THREAD

**Issue by TheInvoker** [material-components/material-components-web#3754]
I'm using this

https://material.io/develop/web/components/tabs/tab-bar/

To make a tab bar

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>

    <div class="mdc-tab-bar" role="tablist">
        <div class="mdc-tab-scroller">
            <div class="mdc-tab-scroller__scroll-area">
                <div class="mdc-tab-scroller__scroll-content">

                    <button class="mdc-tab mdc-tab--active" role="tab" aria-selected="true" tabindex="0">
                        <span class="mdc-tab__content">
                            <span class="mdc-tab__icon material-icons" aria-hidden="true">title</span>
                            <span class="mdc-tab__text-label">Name</span>
                        </span>
                        <span class="mdc-tab-indicator mdc-tab-indicator--active">
                            <span class="mdc-tab-indicator__content mdc-tab-indicator__content--underline"></span>
                        </span>
                        <span class="mdc-tab__ripple"></span>
                    </button>
                    <button class="mdc-tab" role="tab" aria-selected="true" tabindex="0">
                        <span class="mdc-tab__content">
                            <span class="mdc-tab__icon material-icons" aria-hidden="true">style</span>
                            <span class="mdc-tab__text-label">Tags</span>
                        </span>
                        <span class="mdc-tab-indicator">
                            <span class="mdc-tab-indicator__content mdc-tab-indicator__content--underline"></span>
                        </span>
                        <span class="mdc-tab__ripple"></span>
                    </button>
                    <button class="mdc-tab" role="tab" aria-selected="true" tabindex="0">
                        <span class="mdc-tab__content">
                            <span class="mdc-tab__icon material-icons" aria-hidden="true">favorite</span>
                            <span class="mdc-tab__text-label">Status</span>
                        </span>
                        <span class="mdc-tab-indicator">
                            <span class="mdc-tab-indicator__content mdc-tab-indicator__content--underline"></span>
                        </span>
                        <span class="mdc-tab__ripple"></span>
                    </button>
                    <button class="mdc-tab" role="tab" aria-selected="true" tabindex="0">
                        <span class="mdc-tab__content">
                            <span class="mdc-tab__icon material-icons" aria-hidden="true">warning</span>
                            <span class="mdc-tab__text-label">Restriction</span>
                        </span>
                        <span class="mdc-tab-indicator">
                            <span class="mdc-tab-indicator__content mdc-tab-indicator__content--underline"></span>
                        </span>
                        <span class="mdc-tab__ripple"></span>
                    </button>
                    <button class="mdc-tab" role="tab" aria-selected="true" tabindex="0">
                        <span class="mdc-tab__content">
                            <span class="mdc-tab__icon material-icons" aria-hidden="true">keyboard_arrow_right</span>
                            <span class="mdc-tab__text-label">Other</span>
                        </span>
                        <span class="mdc-tab-indicator">
                            <span class="mdc-tab-indicator__content mdc-tab-indicator__content--underline"></span>
                        </span>
                        <span class="mdc-tab__ripple"></span>
                    </button>

                </div>
            </div>
        </div>
    </div>

and this JS

        const tabBar = mdc.tabBar.MDCTabBar.attachTo(document.querySelector('.mdc-tab-bar'));
        tabBar.listen('MDCTab:interacted', function (event) {
            alert(1);
        });
        document.querySelectorAll('.mdc-tab-bar button')[3].click();
        //tabBar.activateTab(3);

Invoking the click works (via code or manually with mouse), and emits the event and alerts 1. However I would rather use the activateTab function, but it only makes the tab active, but not not emit the event.

Does anyone know what's wrong here?

Thanks

**Comment by acdvorak** [comment]
Thanks for filing this issue!

It sounds like you want the [`MDCTabBar:activated` event](https://github.com/material-components/material-components-web/tree/ebb3d6f7952456c9bc57ce9537a08d7cd85bc5b1/packages/mdc-tab-bar#mdctabbar-properties-and-methods). It fires when a tab is clicked or activated programmatically with `activateTab()`.

Does that solve your use case?

**Comment by TheInvoker** [comment]
yes, thanks

**Comment by acdvorak** [comment]
Woo hoo! 😄
