### ISSUE TITLE
[Help wanted / possible feature request]

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#3758]
Is it possible to have a list button that sticks on the bottom of the mdc-drawer__content class? If it is not possible, could I request that it is added as a class name for the list item like mdc-list-item-bottom?

<img width="281" alt="screen shot 2018-10-15 at 3 28 39 pm" src="https://user-images.githubusercontent.com/26075792/46926850-03f3a500-d08f-11e8-82ea-6ead9191dbac.png">

Currently I'm achieving this by just adding top: 450px; to the button. This works, but it doesn't work on different sized screens or if the browser size is different. So requesting this functionality to work natively. 
Thanks :)

**Comment by MishUshakov** [comment]
Hey, you could just make a new container element and give it position: absolute and bottom: 0. It will stick it to the bottom of your drawer

**Comment by CyborgSemon** [comment]
Yeah i tried that before but for some odd reason it cuts off half of the button

<img width="259" alt="screen shot 2018-10-15 at 10 36 24 pm" src="https://user-images.githubusercontent.com/26075792/46942904-da586f00-d0ca-11e8-8d8b-d64c0f274505.png">

I have no idea why it does this. So I guess it could be considered a bug.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

The [Navigation Drawer guidelines](https://material.io/design/components/navigation-drawer.html) don't explicitly mention it, but a number of Google apps seem to do it (e.g., Google Docs  on iOS).

This worked for me: https://codepen.io/acdvorak/pen/pxdKrj

**Comment by CyborgSemon** [comment]
Awesome that worked great! Thanks

**Comment by CyborgSemon** [comment]
Reopening this issue as I have noticed an issue with the way that you did it @acdvorak .

Though your solution does get the drawer button in the correct position, it doesn't set the `mdc-list-item--activated` class when it is clicked. Im assuming that it is because it is outside of the `mdc-drawer__content` class. 
My example here uses the same layout as what you used in your code pen.

![drawer_bug](https://user-images.githubusercontent.com/26075792/47079035-09084e00-d261-11e8-90ab-f062745edbca.gif)

The expected result is that when the bottom button is clicked that the `mdc-list-item--activated` is applied as it is applied to the top 3 buttons.
Thanks

**Comment by marcusmoqvist** [comment]
This may work?
https://codepen.io/anon/pen/EdQobM?editors=1100

**Comment by CyborgSemon** [comment]
Awesome that worked great @marcusmoqvist!
Thanks!
