### ISSUE TITLE
Error in Toolbar docs class name

### ISSUE THREAD

**Issue by neclepsio** [material-components/material-components-web#378]
The docs say: "When using `mdc-toolbar--fixed`, you can add the `mdc-toolbar-fixed-adjust` helper class to the toolbar's adjacent sibling element..."

The name of the class is `mdc-toolbar__fixed-adjust`.

**Comment by Garbee** [comment]
Duplicate of #320 perhaps?

**Comment by neclepsio** [comment]
Yes. I just searched in open issues.
