### ISSUE TITLE
Integrate with CodeCov / Coveralls

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#380]
Along the lines of #319, it would be nice to have more visibility into how every PR affects our coverage. [CodeCov](https://codecov.io/) and [Coveralls](https://coveralls.io/) are two popular options for this, and should be able to be integrated with our codebase relatively painlessly. I personally like CodeCov because it comments on PRs for you, but would be open to Coveralls as well if a compelling case can be made for it.

**Comment by Garbee** [comment]
+1 to codecov. Mozilla uses it for their new DevTools Debugger that is on Github (and soon for the rest of the DevTools once that move is made) and I use it on a few things I've been doing recently. It is fantastically simple and a great interface to the data.
