### ISSUE TITLE
mdc-simple-menu firing "cancel" event when setting "open"?

### ISSUE THREAD

**Issue by kminehart** [material-components/material-components-web#386]
### What MDC-Web Version are you using?

> `0.5.0

### What browser(s) is this bug affecting?

> Firefox 52.0, Chrome
### What OS are you using?

> Linux w/ kernel 4.9.11-1

### What are the steps to reproduce the bug?

1.  Click on the button that says "click me".
2.  Click on the button again.  Notice in the console that the "cancel" event will continue to fire, but the menu will be hidden.

This isn't exactly what's happening to be but it's related.

http://codepen.io/anon/pen/QpGOMp

### What is the expected behavior?

> Ideally clicking the button again wouldn't do anything, but the switch should toggle (and it does).

### What is the actual behavior?

> Clicking on the button again closes the menu, and then prevents it from being open again; each subsequent click will fire the "close" event.

### Any other information you believe would be useful?

Here's why this is a problem for me:

![screenshot](https://cloud.githubusercontent.com/assets/5140827/23678127/745715d6-0348-11e7-9ef3-3b0551510dda.png)

![screenshot](https://cloud.githubusercontent.com/assets/5140827/23678145/872f678a-0348-11e7-9afc-7cac34a15f77.png)

After toggling, clicking the "settings" button again does nothing, but the "cancel" event continues to fire.

![screenshot](https://cloud.githubusercontent.com/assets/5140827/23678162/950bdc3a-0348-11e7-88b6-d7ccb5ad9498.png)

I'm not entirely sure if I'm doing this right.  I'll try creating a component using the foundation class rather than using the menu-simple built in object and report back.

**Comment by kminehart** [comment]
So I've implemented the component in React.

it needs some cleanup but the functionality is there, and that seemed to fix my issue.

### Menu
```
import React, {PropTypes} from 'react';
import {MDCSimpleMenu, MDCSimpleMenuFoundation} from '@material/menu';
import MenuItem from '../MenuItem';
import {Set as ImmutableSet, Map as ImmutableMap} from 'immutable';
import {getTransformPropertyName} from '@material/menu/util';

const OPENFROMS = {
  "top-left": "mdc-simple-menu--open-from-top-left",
  "top-right": "mdc-simple-menu--open-from-top-right",
  "bottom-left": "mdc-simple-menu--open-from-bottom-left",
  "bottom-right": "mdc-simple-menu--open-from-bottom-right",
}
class Menu extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      classes: new ImmutableSet(),
    };

    this.foundation = new MDCSimpleMenuFoundation({
      addClass: (className) => {
        this.setState(prevState => ({
          classes: prevState.classes.add(className),
        }));
      },
      removeClass: (className) => {
        this.setState(prevState => ({
          classes: prevState.classes.remove(className),
        }));
      },
      hasClass: (className) => {
        if(!this.refs.menu) return;
        return this.refs.menu.classList.contains(className);
      },
      hasNecessaryDom: () => {
        return !!this.refs.menu;
      },
      getInnerDimensions: () => {
        return {
          width: this.refs.menuItemsContainer.offsetWidth,
          height: this.refs.menuItemsContainer.offsetHeight,
        };
      },
      hasAnchor: () => {
        return this.refs.menu.parentElement && this.refs.menu.parentElement.classList.contains('mdc-menu-anchor');
      },
      getAnchorDimensions: () => {
        return this.refs.menu.parentElement.getBoundingClientRect()
      },
      getWindowDimensions: () => {
         return {width: window.innerWidth, height: window.innerHeight};
      },
      setScale: (x, y) => {
        if(!this.refs.menu) return;
        this.refs.menu.style[getTransformPropertyName(window)] = `scale(${x}, ${y})`;
      },
      setInnerScale: (x, y) => {
        if(!this.refs.menuItemsContainer) return;
        this.refs.menuItemsContainer.style[getTransformPropertyName(window)] = `scale(${x}, ${y})`;
      },
      getNumberOfItems: () => {
        if(!this.props.items) return;
        return this.props.items.length;
      },
      registerInteractionHandler: (type, handler) => {
        if(!this.refs.menu) return;
        this.refs.menu.addEventListener(type, handler);
      },
      deregisterInteractionHandler: (type, handler) => {
        if(!this.refs.menu) return;
        this.refs.menu.removeEventListener(type, handler);
      },
      registerDocumentClickHandler: (handler) => {
        document.addEventListener('click', handler);
      },
      deregisterDocumentClickHandler: (handler) => {
        document.removeEventListener('click', handler);
      },
      setTransitionDelayForItemAtIndex: (index, value) => {
        // todo
        return;
      },
      getIndexForEventTarget: (target) => {
        if(!this.props.items) return;
        return this.props.items.indexOf(target);
      },
      notifySelected: (evtData) => {
        let evt = new CustomEvent('MDCSimpleMenu:selected', {
          detail: {
            index: evtData.index,
            item: this.items[evtData.index],
          },
        });
        this.refs.menu.dispatchEvent(evt);
      },
      notifyCancel: () => {
        let evt = new CustomEvent('MDCSimpleMenu:cancel');
        this.refs.menu.dispatchEvent(evt);
        this.props.onClose();
      },
      saveFocus: () => {
      },
      restoreFocus: () => {
      },
      isFocused: () => {
      },
      focus: () => {
      },
      getFocusedItemIndex: () => {
      },
      focusItemAtIndex: (index) => {
      },
      isRtl: () => {
      },
      setTransformOrigin: (origin) => {
        this.refs.menu.style[`${getTransformPropertyName(window)}-origin`] = origin;
      },
      setPosition: (position) => {
        if(!this.refs.menu) return;
        this.refs.menu.style.left = 'left' in position ? position.left : null;
        this.refs.menu.style.right = 'right' in position ? position.right : null;
        this.refs.menu.style.top = 'top' in position ? position.top : null;
        this.refs.menu.style.bottom = 'bottom' in position ? position.bottom : null;
      },
      getAccurateTime: () => {
        return window.performance.now();
      },
    });
  }

  componentDidUpdate() {
    if(this.props.open && !this.foundation.isOpen()) this.foundation.open();
  }
  componentDidMount() {
    this.foundation.init();
    console.log(this.refs.menu);
  }
  componentWillUnmount() {
    this.foundation.destroy();
  }
  render() {
    return(
      <div className={`mdc-simple-menu ${OPENFROMS[this.props.openFrom]} ${this.props.className || ''} ${this.state.classes.toJS().join(' ')}`}
           ref="menu">
        <ul
          className='mdc-simple-menu__items mdc-list'
          role='menu'
          ref='menuItemsContainer'>
            {this.props.items.map((item, key) =>
              <MenuItem key={key} label={item.label} icon={item.icon} input={item.input} onClick={item.onClick} />
            )}
        </ul>
      </div>
    )
  }
}

Menu.defaultProps = {
  openFrom: "top-right",
  items: [],
  onClose: () => {},
  preventClose: false,
  open: false,
};

Menu.propTypes = {
  preventClose: PropTypes.bool,
  openFrom: PropTypes.oneOf([
    "top-right",
    "top-left",
    "bottom-right",
    "bottom-left",
  ]),
  items: PropTypes.array.isRequired,
  onClose: PropTypes.func,
  open: PropTypes.bool.isRequired,
};

export default Menu;
```
### MenuItem

```
import React, {PropTypes} from 'react';
import {ripple} from 'material-components-web';

class MenuItem extends React.Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
  }

  render() {
    return(
      <li className={`mdc-list-item ${this.props.className || ''}`}
        role='menuitem'
        onClick={this.props.onClick}>
        {
          this.props.icon
          ?
          <i className="mdc-list-item__start-detail material-icons" aria-hidden="true">{this.props.icon}</i>
          :
          null
        }
        {this.props.label}
        {
          this.props.input
          ?
          <i className="mdc-list-item__end-detail">{this.props.input}</i>
          :
          null
        }
      </li>
    )
  }
}

MenuItem.defaultProps = {
  onClick: () => {},
};

MenuItem.propTypes = {
  label: PropTypes.string.isRequired,
  icon: PropTypes.string,
  input: PropTypes.node,
};

export default MenuItem;
```

That being said, I know that my implementation in the above example is kind of wonky but i tried to make something that was accurate for my issue.  Hopefully this helps someone; is the behaviour shown in the codepen a non-issue?

**Comment by traviskaufman** [comment]
Hey @kminehart,

Thanks for filing. These seems to be happening because [in our event handling code](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/foundation.js#L72-L74), we do not call `stopPropagation()` on the event objects. The solution here would be:

- [ ] Ensure that `evt.stopPropagation()` is called within each of our `handle*` methods
- [ ] Write unit tests to ensure that this behavior is happening

We'd gladly accept a PR from you with these changes if you were willing to make them! 😄

**Comment by kminehart** [comment]
Sounds easy enough; I can give it a shot.

**Comment by kminehart** [comment]
I thought it'd be easy!  I'm not entirely sure how to get the unit tests set up.  Do I check to make sure that the cancel event isn't fired whenever the open event is?

**Comment by traviskaufman** [comment]
Hey @kminehart,

> I'm not entirely sure how to get the unit tests set up

You'll want to add the tests to [test/unit/mdc-menu/simple.foundation.test.js](https://github.com/material-components/material-components-web/blob/master/test/unit/mdc-menu/simple.foundation.test.js).

> Do I check to make sure that the cancel event isn't fired whenever the open event is?

I would actually make sure that `stopPropagation` is called on the passed in `evt` object to the handler.

Notice in that file we [import a function called captureHandlers](https://github.com/material-components/material-components-web/blob/master/test/unit/mdc-menu/simple.foundation.test.js#L20). This is defined in [test/unit/helpers/foundation](https://github.com/material-components/material-components-web/blob/master/test/unit/helpers/foundation.js#L36-L53), and its purpose is to facilitate testing event handling logic within foundations through adapters that use `registerInteractionHandler`-like methods that accept an event type and a handler, e.g. [like MDCSimpleMenuFoundation](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/foundation.js#L105-L107).

Using captureHandlers, along with [testdouble](https://github.com/material-components/material-components-web/blob/master/docs/authoring-components.md#verify-adapters-via-testdouble) to mock out an event object with `preventDefault` on it, and verify that it was called. Here's an example for the click handler:

```js
test('on click calls stopPropagation() on the event object', () => {
  const {foundation, mockAdapter} = setupTest();
  const handlers = captureHandlers(mockAdapter, 'registerInteractionHandler');
  // Prevent rogue timers from being created
  const clock = lolex.install();
  const fakeEvt = {
    target: {},
    preventDefault: td.func('evt.preventDefault'),
  };
  td.when(mockAdapter.getIndexForEventTarget(target)).thenReturn(-1);

  foundation.init();
  handlers.click(fakeEvt);
  td.verify(fakeEvt.preventDefault());

  clock.uninstall();
});
```

You could probably just modify https://github.com/material-components/material-components-web/blob/master/test/unit/mdc-menu/simple.foundation.test.js#L303, and do the same for `keyup`.

Also note that you may have to modify some of the tests that call `handlers.click({target})` to pass it `preventDefault` as well, otherwise you may get errors saying that the code tried to call a function that wasn't defined. 

Feel free to jump on our discord channel if you're still stuck and I can help you on there! https://discordapp.com/channels/259087343246508035/278684671179489281

**Comment by traviskaufman** [comment]
Hey @kminehart,

Just checking in here. Let us know if you're still interested in submitting a PR for this! Also feel free to reach out with any questions / comments regarding the implementation :)

**Comment by kfranqueiro** [comment]
This is most likely obsolete since the Menu component has since been refactored. Feel free to comment if this is still reproducible with current MDCMenu.
