### ISSUE TITLE
Mark variables as "!default" in components?

### ISSUE THREAD

**Issue by mikegleasonjr** [material-components/material-components-web#391]
For example in `mdc-toolbar.scss` some variables are defined:

```
$mdc-toolbar-height: 64px;
$mdc-toolbar-mobile-height: 56px;
$mdc-toolbar-padding: 24px 16px;
$mdc-toolbar-mobile-padding: 16px;
```

I can't overwrite them in userland like I can with the theme:

```
$mdc-theme-primary: #3f51b5 !default; /* Indigo 500 */
$mdc-theme-accent: #ff4081 !default; /* Pink A200 */
$mdc-theme-background: #fff !default; /* White */
```

I know we should follow the spec but I would like to overwrite them anyway. I don't know what you guys think?

**Comment by Garbee** [comment]
Looks like a duplicate of #348. @yeelan0319 explains there [why it isn't allowed](https://github.com/material-components/material-components-web/issues/348#issuecomment-282109399).

**Comment by mikegleasonjr** [comment]
Alright thanks.

**Comment by thomasklein** [comment]
Hi! First of all, thanks for this project and all the effort you put into it. You guys are amazing! 

A question: I don't fully understand the reasoning. Following this approach the theming is limited to a few variables. E.g. it is impossible for me to customize `$mdc-elevation-umbra-color`. One can call it rigid but in in the above case (and similar) I see it as inflexible. In the worst case something breaks or looks weird. My reaction would then be: back to default and diving deeper.
