### ISSUE TITLE
Slider: missing native input element

### ISSUE THREAD

**Issue by Rainrider** [material-components/material-components-web#3917]
First and foremost thank you very much for the work and dedication you're putting into this, much appreciated!

I noticed that MDCSlider is the only input component missing "a link" to the native input control it is modeled after: `<input type="range">`. This makes it unusable for forms out of the box unlike other input components - specifically form submission does not include its set value and form reset does not reset the slider to its initial value.

Is there a design or architectural reason for the current implementation?

**Comment by Rainrider** [comment]
> In the interim, you should be able to synchronize with a hidden input in response to the MDCSlider:change event.

This is what I currently do.

Thank you for the response, I'll track the feat/slider branch then.

**Comment by asyncLiz** [comment]
@bonniezhou what do you think of this issue having looked at a hidden input for select? Is this something we want for slider too, or do we want to suggest manually syncing to a hidden input when used in forms?

**Comment by bonniezhou** [comment]
Yeah I think we should add a hidden input element for slider for the same reason we wanted to in select.

**Comment by adrianschmidt** [comment]
If I understand the feature request correctly, this was fixed in MDC v9.0.0, in #6623.

**Comment by joyzhong** [comment]
Yes, thanks! The slider now has a backing `<input type="range">`, so closing as fixed.
