### ISSUE TITLE
Screenshot test marks diffs as "success" in GitHub status checks

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#3932]
E.g., commit 9bbb0740dd645d3c5014081742ab26be975e4d02 on #3924:

![image](https://user-images.githubusercontent.com/409245/47063002-32a47500-d18e-11e8-9603-08b4ecb0f579.png)

This appears to be caused by a typo:

https://github.com/material-components/material-components-web/blob/75cf88c5607aae69817133dca9277ff46da8870b/test/screenshot/infra/lib/status-notifier.js#L268-L270

The above needs to be changed to `state = GitHubApi.PullRequestState.FAILURE`.

**Comment by kfranqueiro** [comment]
Is this maybe the actual cause of #3806?

**Comment by acdvorak** [comment]
I think they're separate issues.

In #3932 (this issue), the GitHub status description correctly says "12 screenshots differed" (which matches the report), but incorrectly displays a green "success" checkmark due to a typo.

In #3806 (other issue), the GitHub status description incorrectly says "All 560 screenshots match", which doesn't jive with the report.
