### ISSUE TITLE
MDCNotchedOutline: Notch is too far forward when the component border-radius is set too high

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#3936]
Refs: #3158 

The fix for #3158 moves the label towards the center to be inside the notch in the notched outline. After talking with design it looks like the notch (and label) should move closer to the start (with the label moving towards the center a small amount so it ends up completely off the curve of the corner). The goal is to keep the label, input text and helper text as closely aligned as possible.

**Comment by kfranqueiro** [comment]
Fixed in #3929
