### ISSUE TITLE
Side Sheet: Parameterize dismissible escape key closing behavior

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#3938]
From https://github.com/material-components/material-components-web/pull/3924#discussion_r226101061:

> Drawers should do this by default but side sheets should not (they may contain child controls that do something on escape).

https://github.com/material-components/material-components-web/blob/2b104a67c3e23d700607f56e4c64f9eb1b097784/packages/mdc-side-sheet/dismissible/foundation.js#L147-L154

**Comment by bonniezhou** [comment]
Closing this as obsolete.
