### ISSUE TITLE
Floating labels not working when setting value of input field via vue.js v-model 2 way binding

### ISSUE THREAD

**Issue by TheInvoker** [material-components/material-components-web#3939]
I am using latest vue.js to do a 2-way binding with input to data object like

    <input type="text" v-model="value"/>   <---- floating label text input in MDC

    data {
        value : ""
    }

this means if I type in the field, it updates data.value and if I change data.value, it updates it in the field.
However the issue is when I update the data.value, when it was previously empty string. It does not trigger the floating label, and the label just overlaps the text.

**Comment by williamernest** [comment]
@TheInvoker Can you provide a codepen or a stackblitz showing the issue?  It's easier for us to provide assistance when we can see the code and investigate exactly why something is/isn't happening. 

I believe this is due to not using the component/foundation to set the value (which handles floating/unfloating the label as necessary).

**Comment by TheInvoker** [comment]
Here is a code pen

[https://codepen.io/anon/pen/qJovEr](url)

and yes it looks like setting the value on the input directly doesn't work with the component/foundation, but it is what vue.js requires. Is there a way to get this to work?

**Comment by williamernest** [comment]
`setValue` does not exist on the component, just on the foundation. You should set value using assignment. 

```
      value: function(new_val, old_val) {
        this.mdc_text.value = this.value;
      }
```
https://codepen.io/williamernest/pen/LgdoLG

**Comment by TheInvoker** [comment]
thanks, that worked

**Comment by acdvorak** [comment]
Glad to hear it! 😀
