### ISSUE TITLE
React example should clarify that it is CSS only

### ISSUE THREAD

**Issue by ianchanning** [material-components/material-components-web#394]
## Bugs

The React example checkbox doesn't clear the ripple. See below screenshots in Firefox and Chrome.

Having seen the [demos][2] - I assume this is because it is using the CSS only version. Viewing the demos shows the difference between the CSS only ripple (which stays until losing focus) and the JavaScript ripple which disappears immediately.

### What MDC-Web Version are you using?

v0.6.0, React v15.4.1.

### What browser(s) is this bug affecting?

Firefox v51.0.1 64-bit. Also tested on Chromium v56.0.2924.87 Fedora Project (64-bit)

### What OS are you using?

Ubuntu 16.04 (Vagrant VM running on top of Fedora 25).

### What are the steps to reproduce the bug?

1. Install and run the example
```bash
git clone git@github.com:material-components/material-components-web.git
cd material-components-web/framework-examples/react/
npm install
npm run
```
2. In the browser http://localhost:3000
3. Tick the checkbox

### What is the expected behavior?

The ripple should disappear. The most immediate example I can give you is from the [Material UI Checkbox][1], or otherwise run the demos. The ripple spreads out and disappears after clicking the checkbox.

### What is the actual behavior?

The ripple spreads out and stays there. 

Firefox screenshot:

![screenshot from 2017-03-11 16-42-43](https://cloud.githubusercontent.com/assets/233318/23826988/828a3f98-06a9-11e7-9886-1fbcb27b92ca.png)

Chromium screenshot:

![screenshot from 2017-03-11 16-44-48](https://cloud.githubusercontent.com/assets/233318/23826994/91ae2c28-06a9-11e7-97c0-9f41fcb03ae3.png)

### Any other information you believe would be useful?

The code is running on an Ubuntu VM - but I'm viewing the examples in browser on the host OS which is Fedora.

  [1]: http://www.material-ui.com/#/components/checkbox
  [2]: https://github.com/material-components/material-components-web/blob/master/demos/checkbox.html

**Comment by kminehart** [comment]
This is happening to me too on Arch Linux and Firefox 52.0, with the example anyways.

However, this does not happen with my implementation here (which I basically copied from the original, to be completely honest).

The only difference I can see between the one in my app, which works flawlessly, and the one in the example is that I bind the "checked" value to a property.

Basically, I handle the click event of the entire row (being in a table), and just set use the checkbox like so:

```
<CheckBox checked={this.props.selected} onClick={null} />
```

and the ripple seems to work perfectly here.

**Comment by amsheehan** [comment]
I believe this is actually the focus ring [specified here](https://material.io/guidelines/components/selection-controls.html#selection-controls-checkbox)

If you click outside of the checkbox, does the ring disappear? That is the expected behavior, and the behavior I see when I run the example locally.

**Comment by kminehart** [comment]
@amsheehan it does disappear indeed.

So maybe I'm actually not using the component correctly in my application 😅

**Comment by amsheehan** [comment]
@kminehart Sometimes the best solution is a remolding of expectations! 😄

**Comment by ianchanning** [comment]
@amsheehan Ah - then perhaps it's the Javascript that is incorrect! With the Javascript the ripple disappears, but as you correctly point out the checkbox is still focussed.

**Comment by amsheehan** [comment]
Iiiiiiiinteresting. I will bring this up with the team. Reopening.

**Comment by Garbee** [comment]
Looks like a bug in the react example to me. iirc from speaking with @traviskaufman before about Ripples, they should disappear (no matter how much I don't like it for a11y) when touched/clicked. Then when *keyboard* triggers are used on desktop is when they should persist.

The regular JS checkbox is working as I'd expect with what we currently have to work with. The React example simply seems wrong.

**Comment by ianchanning** [comment]
@Garbee I wouldn't say it's the react example - I witnessed the same behaviour in the CSS demo. My assumption was because the react example was using CSS.

I'm flip flopping in my opinions here - and agreeing with you @Garbee . Looking at a comparison with buttons, after you click a button it doesn't end up in the focussed state (see the screenshot below and also the video on the [Buttons page][1]), it goes back to the normal state even though it still has focus.

![image](https://cloud.githubusercontent.com/assets/233318/23968385/cc9ced26-09c2-11e7-8922-4f20388261c7.png)

Also comparing to [Material UI's implementation of buttons][2] the 'focussed' action only happens with keyboard.

But of course this conflicts with the HTML standards meaning that you end up with the HTML 'focus' overlapping an 'unfocussed' button:

![image](https://cloud.githubusercontent.com/assets/233318/23968885/da6d3aee-09c4-11e7-86ff-4b53bdac73c0.png)

So I'd say you've got:

Clears the ripple / focus after click:
1. MDC-Web JS checkbox
1. Material UI checkbox
1. Material guidelines [buttons][1]

Doesn't clear the ripple / focus:
1. MDC-Web CSS / react example
1. HTML 

So the MDC-Web CSS is inconsistent and poor old HTML is going to be lonely.

  [1]: https://material.io/guidelines/components/buttons.html#buttons-raised-buttons
  [2]: https://material-ui-1dab0.firebaseapp.com/#/component-demos/buttons

**Comment by traviskaufman** [comment]
@ianchanning @kminehart I can't seem to reproduce this issue.

What may be happening is that the builds of Firefox/Chromium you're using don't support CSS custom properties (although according to Can I Use, they should). Could you go to http://material-components-web.appspot.com/ripple.html and verify that you do _not_ see this?

<img width="1438" alt="screen shot 2017-03-16 at 12 18 31" src="https://cloud.githubusercontent.com/assets/1185269/24006629/bfd46648-0a42-11e7-93da-63740edaba80.png">

If you do see this, we're clearly going to have to change that message ;)

**Comment by ianchanning** [comment]
@traviskaufman I have this in FF v52 in Windows - all the buttons keep their 'focussed' state after clicking in the CSS which agrees with @Garbee suggests. I don't get your red error message but I do get the following after clicking on the 'heart' button:

![image](https://cloud.githubusercontent.com/assets/233318/24007163/15548078-0a6e-11e7-8a74-2b3f44754729.png)

**Comment by traviskaufman** [comment]
Hmm, so that makes sense for the "- css only" version, but for the normal version you should see the ripple disappear after you interact with it. 

I'm going to try reproing the original issue on FF on Linux next week and see what happens.

**Comment by ianchanning** [comment]
The ripples do disappear for JavaScript. It's the CSS only where they don't.

I only opened this issue because of the difference between the JavaScript and the CSS. 

I think this issue can be closed, because the difference is by design.

**Comment by ianchanning** [comment]
Perhaps I should re-write the React demo to use JavaScript?

**Comment by anton-kachurin** [comment]
The demo is totally working after updating dependencies to the newest version

@ianchanning I created a pull request for this, but if you want to do it manually:
```shell
cd material-components-web/framework-examples/react/
npm i -g npm-check-updates
ncu -u & npm i
```
