### ISSUE TITLE
Side Sheet: Dismissible should set focus after opening

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#3940]
From https://github.com/material-components/material-components-web/pull/3924#discussion_r226101953:

https://github.com/material-components/material-components-web/blob/2b104a67c3e23d700607f56e4c64f9eb1b097784/packages/mdc-side-sheet/dismissible/foundation.js#L175

> We probably do still want to focus something within the dismissible side sheet when it opens...but we'd probably have to just look for the first focusable thing within it. I forget if we've already implemented or used something like that somewhere else in our repo? Otherwise we could probably use [`tabbable`](https://www.npmjs.com/package/tabbable) ([`focus-trap`](https://www.npmjs.com/package/focus-trap)'s dependency) for it, but might want to delegate that to a `util` function as well.

Dialog briefly had a `util` function for this in #3413, but it was removed because [`focus-trap`](https://www.npmjs.com/package/focus-trap) already provides the same functionality (via its dependency on [`tabbable`](https://www.npmjs.com/package/tabbable)):

https://github.com/material-components/material-components-web/blob/a62f7431d8d1426438dfeb34e0aba27179d0a61e/packages/mdc-dialog/util.js#L46-L104

#### Tasks:

* [ ] Rename `focusActiveNavigationItem()` to something more generic (e.g., `focusContent()`)
* [ ] Create a `util` function to find the first focusable element (probably using [`tabbable`](https://www.npmjs.com/package/tabbable))

**Comment by bonniezhou** [comment]
Closing this as obsolete.
