### ISSUE TITLE
Textfield doesn't look right with full width class and outline doesn't work either

### ISSUE THREAD

**Issue by TheInvoker** [material-components/material-components-web#3943]
For textfield with leading icon, I want to make it full width, but I notice, the text value slightly overlaps with the floating label

https://codepen.io/anon/pen/EdLPKE

then when I add the outline modifier, the floating label rises too high and there is no border.

Plus the text overlaps the icon...

**Comment by TheInvoker** [comment]
but then the background is gray, and when I put it next to a text area field, it looks weird.

**Comment by williamernest** [comment]
We currently have no plans to add a leading/trailing icons, a floating label or the outlined variant to the full width text field.

**Comment by acdvorak** [comment]
Closing this issue as we are not planning to implement this.
