### ISSUE TITLE
Card dark theme not working properly

### ISSUE THREAD

**Issue by srinathh** [material-components/material-components-web#397]
### What MDC-Web Version are you using?
0.6.0

### What browser(s) is this bug affecting?
Google Chrome Version 57.0.2987.98 (64-bit)
```
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Mobile Safari/537.36
```
### What OS are you using?
Ubuntu 14.04

### What are the steps to reproduce the bug?
Use the card component with the dark theme using the demo code directly taken from the [Card readme](https://github.com/material-components/material-components-web/tree/master/packages/mdc-card). 

[Codepen demo](http://codepen.io/anon/pen/ryzQzB) demonstrates the issue.

### What is the expected behavior?
See a card with title and subtitle with a dark background and light colored text.

### What is the actual behavior?
The card background does not become white, so the title/sub-title which correctly become white are invisible.

**Comment by anton-kachurin** [comment]
As I understand, all have to do is to define background color in your CSS. Please take a look at the [modified pen](http://codepen.io/anton-kachurin/pen/mWMaGg).

It's probably worth adding to the readme that "mdc-button--theme-dark" should be used on buttons when "mdc-card--theme-dark" applied to the card.

**Comment by srinathh** [comment]
hmm... ok now i get it. 

I think it a dark background should be pre-defined in the default component CSS. The implication of the docs is that is that just applying the class makes it work. Moreover, the white color for text is already pre-defined and the text magically turns white on applying the theme but the background doesn't turn dark. This is inconsistent behavior in the component. 

If there's a good reason to not set the background in default CSS, then the documentation should  probably explicitly call out that the text will become white but background will not unless explicitly set.

**Comment by traviskaufman** [comment]
Hey @srinathh ,

There are a few issues with making a pre-defined dark theme background for components. One issue is that the theme itself simply consists of one universal background color. E.g., we don't differentiate between a regular background color and a "dark theme" background color. 

Furthermore, not all components that make use of dark theme applications make use of a background color. For example, `mdc-textfield` makes use of dark theme application but does not define a background color (for the entire component itself).

Therefore I'm hesitant to fragment background into light and dark theme.

I do, however, feel that you're right in that we need to make the intended use of dark theme classes clearer. _mdc-theme's dark theme classes should be used when certain sections or treatments of the page use a darker color as its background, where our default colors we use would not make sense_. An example of this is precisely what's shown in @anton-kachurin's pen. Another example would be if your app allows switching between different color schemes, such as what's done on [Google Fonts](https://fonts.google.com):

<img width="1173" alt="screen shot 2017-03-16 at 14 17 32" src="https://cloud.githubusercontent.com/assets/1185269/24012147/5db2b878-0a53-11e7-85ab-2fa02f9fa4ce.png">

vs.

<img width="1171" alt="screen shot 2017-03-16 at 14 18 11" src="https://cloud.githubusercontent.com/assets/1185269/24012172/6ed24f74-0a53-11e7-80fa-bf062edccd88.png">

I'm going to submit a PR to make this a bit clearer in our theming documentation.
