### ISSUE TITLE
Snackbar action handler text not appearing

### ISSUE THREAD

**Issue by ganeshaprabhu** [material-components/material-components-web#3981]
### What MDC Web Version are you using?

0.35

### What browser(s) is this bug affecting?

* Chrome 69.0.3497
* IE 11
* Firefox

### What OS are you using?

* Windows 10
* Windows 8

### What are the steps to reproduce the bug?

1. Go to the [snackbar demo page](https://material-components.github.io/material-components-web-catalog/#/component/snackbar)
2. Click "show snackbar" button and click action handler text
3. Click "show start aligned" button and click action handler text
4. Again click the "show snackbar" button

### What is the expected behavior?

The action handler text should be visible near the snackbar.

### What is the actual behavior?

Snackbar behavior is not correct on consecutive instances.

The action handler text is disappeared and there is no way to close the snackbar before it automatically fades away.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

I was able to reproduce it, but not reliably. Is it timing-specific?

Could you possibly capture a video of the steps you took to reproduce the bug?

Here's a screenshot:

![image](https://user-images.githubusercontent.com/409245/47521093-e2d94400-d846-11e8-9b26-58329f03fe59.png)

**Comment by vuchastyi** [comment]
Got into the same problem, here's the video: [link](https://download.let-lang.org/temp/snackbar_bug.mov).

**Comment by acdvorak** [comment]
Thanks for the video capture, @vuchastyi!

Converted to animated GIF:

![snackbar_bug](https://user-images.githubusercontent.com/409245/48031371-d7b8ca80-e108-11e8-8014-3dcca2ca8620.gif)
