### ISSUE TITLE
mdc-icon-buttons ::before position not updated when width changes (updates after click)

### ISSUE THREAD

**Issue by BugsNash** [material-components/material-components-web#3984]
## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

> Please be specific, e.g. _major.minor.patch_

https://unpkg.com/material-components-web@0.40.1/dist/material-components-web.min.css
https://unpkg.com/material-components-web@0.40.1/dist/material-components-web.min.js

### What browser(s) is this bug affecting?

> Please include the browser version. A user-agent string is also quite helpful.

Google Chrome | 70.0.3538.67 (Official Build) (64-bit)
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36

Also happens on ChromeOS on chrome version 71.0.3542

### What OS are you using?

> Please include the OS version.

Linux and ChromeOS

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.
>
> 1. Run the demo server
> 2. Go to localhost:8080/textfield.html
> 3. Tab-focus on the first text field
> 4. Observe the component's behavior
>
> We also have a [template on CodePen](https://codepen.io/williamernest/pen/deyxyp) which we encourage you to use to create a reproduction of
> the issue. The less time it takes for us to reproduce the issue, the less time it takes to verify and
> fix it!

issue demo: https://jsfiddle.net/BugsNash/yuhwxg8z/26/

1) Create a mdc-button
2) Note the position of the button's ::before styling on focus (do this by hovering or tabbing to the mdc-button, not by clicking)
3) Change the width of the mdc-button
4) Again, note the position of the button's ::before styling on focus by hovering or tabbing to the mdc-button. The position has not changed to match its parent
5) Click on the mdc-button
6) Note that the positoin of the ::before styling has now updated to match its parent.

### What is the expected behavior?

> Please describe what the component/code should be doing that it's not.

position of the ::before element should update when the mdc-button width changes

### What is the actual behavior?

position of the ::before element doesn't update until the mdc-button is clicked on

> Please describe what the component/code is actually doing that's different from what it should be
doing.

### Any other information you believe would be useful?

This seems to be caused by the css var --mdc-ripple-left (set on #mdc-button::before's 'left' property) not being updated until click.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

It sounds like you need to call `.layout()` on the `MDCRipple` instance:

https://jsfiddle.net/385yrgbs/

```js
const ripple = mdc.ripple.MDCRipple.attachTo(document.getElementById('mdc-button'));
ripple.unbounded = true;

document.getElementById('toggle-button').addEventListener('click', () => {
  document.getElementById('mdc-button').classList.toggle('hide');
  ripple.layout();
});
```

Does that solve your issue?

**Comment by BugsNash** [comment]
It certainly works on the min repro as you've linked. Is this working as intended? Still seems like a bug to me. It seems like the ripple should automatically relayout when its parent does. It will be a pain in a large app to keep a reference to all the ripples and call layout() on them whenever the UI changs (and is not an intuitive thing to do).

**Comment by BugsNash** [comment]
Not as much as a pain as I initially thought - I've been able to handle relaying out all the ripples in my app simply by putting a ResizeObserver on the elements that the ripples belong to. 

Still seems like it should be automatic though?

**Comment by kfranqueiro** [comment]
Yes, this is working as designed. MDCRipple hooks up a window resize handler to call `layout` when the entire viewport size changes, but it doesn't go beyond what's natively supported across our [supported browsers](https://github.com/material-components/material-components-web#browser-support).

ResizeObserver is in draft and only available in Chrome, and MDC Web avoids assuming the presence of features that would require the use of polyfills.
