### ISSUE TITLE
Outlined Text Field: shape-radius doesn't factor in Leading Icon

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3987]
### What MDC Web Version are you using?

0.40.x

### What browser(s) is this bug affecting?

All

### What are the steps to reproduce the bug?

Edit the `baseline-leading-icon.html` screenshot test page, adding the `test-shaped-text-field--outline` class to each `mdc-text-field--outlined` element.

### What is the expected behavior?

Floating label should align with the notched outline properly like it does in the shape-radius tests.

### What is the actual behavior?

The floating-label style for text field with leading icon is overriding the custom shape radius styles.

### Any other information you believe would be useful?

We may be able to factor this into the shape-radius mixin.

The same problem exists in the MDC Select package on the feat/select-new branch (which will be merged for 0.41.0).

**Comment by KNawm** [comment]
Also in the [demo of Textfields](https://material-components.github.io/material-components-web-catalog/#/component/text-field) not one of the three shaped outlined text fields displays the label correctly

![](https://i.imgur.com/FtoNpW3.png)

**Comment by kfranqueiro** [comment]
That has already been fixed in #3929 on master, for #3158. This is somewhat of a follow-up though.
