### ISSUE TITLE
Side Sheet: Either both or neither of app-content and scrim should be shared

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3991]
Currently, the side sheet branch is set up to share the `app-content` element between Drawer and Side Sheet. Meanwhile, the `scrim` element is still unique between the two.

Sharing these elements/classes actually poses a problem, because it will make it difficult to disambiguate the correct styles to apply in cases where there is both a drawer and a side sheet, but one is dismissible while the other is modal.

So we need to either come up with a user-friendly solution for disambiguating the shared classes, or don't share them. Not sharing them is also potentially awkward, since you're going to end up with one element with both `mdc-drawer-app-content` and `mdc-side-sheet-app-content` in the case of using the dismissible variants of both at the same time.

**Comment by bonniezhou** [comment]
Closing this as obsolete since side sheet implementation has been deprioritized.
