### ISSUE TITLE
Importing JS for MDC Select Menu: Documentation Incomplete

### ISSUE THREAD

**Issue by songfarm-david** [material-components/material-components-web#3995]
I am trying to get the JavaScript for [MDC Select Menus](https://material.io/develop/web/components/input-controls/select-menus/) to work but I believe the documentation is incomplete in that it does not reference which JS to import (unlike other documentation, for example, [MDC Radio Buttons](https://material.io/develop/web/components/input-controls/radio-buttons/).

On a whim, I tried doing `import {MDCSelect} from '@material/select';` and then instantiating elements with (as per the docs): 
```
const select = new mdc.select.MDCSelect(document.querySelector('.mdc-select'));
	select.listen('change', () => {
	alert(`Selected option at index ${select.selectedIndex} with value "${select.value}"`);
});
```
but I get `Uncaught ReferenceError: mdc is not defined`. 

So obviously I'm not importing the correct JS or need to import an additional class like an MDC base class, and the documentation conspicuously leaves this out. 

Any help please!

**Comment by Manfredt** [comment]
import {MDCSelect} from '@material/select';

var myselect = new MDCSelect(document.querySelector('.mdc-select'));

**Comment by kfranqueiro** [comment]
Sorry for the confusion here! You were importing the component correctly for ES2015 module syntax, but our documentation was using global namespace syntax instead. Typically we show ES2015 module syntax in our READMEs, so I've sent a PR to fix this.

**Comment by baskuunk** [comment]
[These instructions](https://material.io/develop/web/docs/importing-js/) do not state where to include the snippet. I'm running a NodeJS web server with ExpressJS and serve a simple html document, but I cannot access the dynamic features for which you need to import JS.

I don't understand in what file to import the JS component:
- in a script loaded in the html file?
