### ISSUE TITLE
FAB text disappears from exit/entrance animation

### ISSUE THREAD

**Issue by abraham** [material-components/material-components-web#3996]
### What MDC Web Version are you using?

`0.40.1`

### What browser(s) is this bug affecting?

`Google Chrome 70.0.3538.77 (Official Build) beta (64-bit)`

### What OS are you using?

`Ubuntu 18.10`

### What are the steps to reproduce the bug?

1. Go to [codepen](https://codepen.io/abraham/pen/aRPrPw)
1. Click the "create" FAB
1. FAB exits
1. Wait for dialog to complete animating
1. Click on "no" or "yes" on dialog
1. FAB enters without text

### What is the expected behavior?

When the FAB enters I expect the "create" text to be visible.

### What is the actual behavior?

FAB text disappears.

### Any other information you believe would be useful?

Does not seem to happen in `Firefox 63.0 (64-bit)`

Closing the dialog by clicking next it instead of a button doesn't seem to cause the issue.

![screenshot from 2018-10-25 21-36-40](https://user-images.githubusercontent.com/3341/47541217-185d4c00-d89e-11e8-9a4b-031f224fa1f5.png)

**Comment by kfranqueiro** [comment]
Thanks for reporting this. The enter/exit transitions were created a long time before the extended FAB variant was added, and it's likely we never tested the two together.

**Comment by nicrizzo** [comment]
Workaround: changing scale(0) to scale(0.00001) in .mdc-fab--exited fixes the problem for me. https://codepen.io/nicrizzo/pen/OYQWZb

**Comment by abraham** [comment]
This doesn't seem to be an issue anymore. 

https://codepen.io/abraham/pen/BayjVmK?editors=1010#0
