### ISSUE TITLE
Working examples ?

### ISSUE THREAD

**Issue by Marcellllll** [material-components/material-components-web#4001]
Hi,

Are there any working examples that are possible to copy in order to make sure things work and then start adapting ? Not just pieces of code, but an actual working page. (I tried for example https://material-components.github.io/material-components-web-catalog/#/component/drawer/modal, but I cannot get the proper HTML)

Especially for the mdc-drawer as a modal ? 

Kind regards,
Marcel

**Comment by williamernest** [comment]
@Marcellllll You can checkout our screenshot test pages that we include in our repo. I posted the link to the example you're asking for but feel free to look for others. The javascript is loaded via the `../fixture.js` and the sass is loaded via the `../fixture.scss` file. 

https://github.com/material-components/material-components-web/blob/master/test/screenshot/spec/mdc-drawer/classes/modal.html

**Comment by Marcellllll** [comment]
Hi Will,

 

Thanks a lot ! 

 

Based on this I will look up other components when I get to them, this should help a lot.

 

Kind regards,

 

Marcel

**Comment by kfranqueiro** [comment]
I'm going to close this since it sounds like it's resolved.

FWIW, we're hoping to provide more helpful/sourceable live examples in the future, but the idea is currently pending planning for 2019.

**Comment by Marcellllll** [comment]
Hi Kenneth,

 

Thank you, that would be great. 

 

Including new components has been quite a frustrating experience so far having to experiment how things should probably be, whereas with a few good examples it would have taken only a few minutes (for example for the tab-bar it would be great to have had a complete example with active and inactive tabs and content).

 

Kind regards,

 

Marcel
