### ISSUE TITLE
mdc.drawer modal not opening : mdc-drawer--closing

### ISSUE THREAD

**Issue by Marcellllll** [material-components/material-components-web#4002]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

I am using the example provided here in GitHub for the Modal Drawer, but the drawer never really opens. It turns out there is a class 'mdc-drawer--closing' which is preventing the drawer from being shown completely (there is just a little piece of it on the left side of the screen)

### What MDC Web Version are you using?

@material/drawer@0.40.1

### What browser(s) is this bug affecting?

Encountered this with Chrome

### What OS are you using?

Ubuntu 16.04

### What are the steps to reproduce the bug?

Copy the code from the examples. I tried to find an actual working site with accessible HTML to copy, but couldn't find any, so used the code of the example for Modal Drawer in https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer.

### What is the expected behavior?

The drawer should show properly.

### What is the actual behavior?

Only a few mm of the drawer are shown, the rest is invisible due to this class 'mdc-drawer--closing'

### Any other information you believe would be useful?

I have found it quite frustrating to work with MDC so far. It would be nice to have actual working complete examples which you can copy-paste.

**Comment by kfranqueiro** [comment]
Without seeing an example codepen, I can't really figure how the `--closing` modifier class would get stuck.

The following codepen is just the HTML from the docs along with the JS instantiation code for dismissible and modal drawer (plus a style to remove the default margin so the drawer is properly flush with the viewport sides):

https://codepen.io/kfranqueiro/pen/PygrQy

**Comment by Marcellllll** [comment]
Hi Kenneth,

 

Thanks a lot !  I checked out the codepen and it seems to work ok. 

 

I will try and see whether there is any difference with what I did. Maybe the issues is with the style. (I don’t know how to do codepens yet, but will have to figure out how to make them when I have some time in case of future issues)

 

Kind regards,

Marcel

**Comment by MikeGoesTo11** [comment]
If you're using the example as a template, check your `topAppBar` listener and make sure `drawer.open = true` (I believe the example shows `drawer.open = !drawer.open`).

**Comment by kfranqueiro** [comment]
I'm going to close this since it sounds like it's been resolved.

RE `drawer.open = !drawer.open`, this is primarily to support the dismissible (non-modal) variant, where you can use the menu icon button to toggle the dismissible drawer open or closed. Using this logic for modal should be harmless since the only time that button can be used is when the drawer is closed, so pressing the button will always toggle it open. (When it's open, the scrim masks the top app bar and the rest of the page.)
