### ISSUE TITLE
File to import not found or unreadable: @material/animation/functions

### ISSUE THREAD

**Issue by iddan** [material-components/material-components-web#4003]
### What MDC Web Version are you using?

0.40.0

### What browser(s) is this bug affecting?

Any

### What OS are you using?

macOS Mojave

### What are the steps to reproduce the bug?

Try to compile SASS importing from `@material/animation` (e.g. mdc-dialog)

### What is the expected behavior?

To compile.

### What is the actual behavior?

Missing module

### Any other information you believe would be useful?

The names of the files are prefixed with an underscore even though documented they shouldn't

**Comment by iddan** [comment]
Found an open issue https://github.com/material-components/material-components-web/issues/351

**Comment by kfranqueiro** [comment]
Are you configuring Sass' include paths? This is documented in the context of webpack in the [main README](https://github.com/material-components/material-components-web#include-css-for-a-component) and [getting started](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#step-2-include-css-for-a-component) guide.

If you're using node-sass from the command line, the command-line flag is `--include-path`. If you're using dart-sass, it's `--load-path`.

**Comment by iddan** [comment]
Unfortunately I can't set `--include-path` as I'm using CRA 2.

**Comment by kfranqueiro** [comment]
In that case, this is already tracked in #3985 (and also https://github.com/material-components/material-components-web-react/issues/326). Someone posted a react-scripts fork in #3985 which changes the configuration to include `includePaths`.
