### ISSUE TITLE
Snackbars should appear above FABs

### ISSUE THREAD

**Issue by thdk** [material-components/material-components-web#4005]
### What MDC Web Version are you using?
> 0.40.1

### What are the steps to reproduce the bug?
>
> 1. Add a FAB in your project
> 2. Style the fab using the suggested styling from the docs to show it absolute positioned at the bottom right of the screen
> 3. Add a snackbar / toast in your project
> 4. Show the snackbar / toast
>
> See it in action: https://stackblitz.com/edit/typescript-cc1tyz

### What is the expected behavior?

> The snackbar should be displayed above the FAB

### What is the actual behavior?

> The snackbar covers the FAB partially.

### Any other information you believe would be useful?

I know the web component of the material snackbar is still under development, so I might be to early with this issue.

**Comment by kfranqueiro** [comment]
We're actually looking into updating Snackbar this coming month to better match the spec.

While we don't expect to automatically detect the snackbar covering the FAB, we are contemplating adding a mixin allowing to customize the bottom margin of the snackbar when you know the snackbar will end up overlapping a FAB in your layout.
