### ISSUE TITLE
TextField Textarea is always full width

### ISSUE THREAD

**Issue by stevegeek** [material-components/material-components-web#4006]
## Bugs

Please see https://codepen.io/anon/pen/aRxpXL . Note  that no matter how the text area is specified it takes the full width of its container, unlike the Text field. 

The demo https://material-components.github.io/material-components-web-catalog/#/component/text-field seems to indicate that it should be possible to create a text area which is not full width as there is a section for 'full width' versions of the textarea compared to those show above them.

### What MDC Web Version are you using?

0.40.1

### What browser(s) is this bug affecting?

Safari, Chrome

### What are the steps to reproduce the bug?

See the codepen

### What is the expected behavior?

If `mdc-text-field--fullwidth` is not specified, the textarea should size according to say the `rows` attribute, and not take the full width of its container. 

### What is the actual behavior?

The textarea always fills its container.

### Any other information you believe would be useful?

I believe this is because the textarea is defined with `display: flex` and `width: auto` result in this behaviour https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/_mixins.scss#L481

**Comment by kfranqueiro** [comment]
Thanks for reporting this. It does seem like perhaps we should be using `inline-flex` rather than `flex` by default, given that textareas are `inline` or `inline-block` natively. We'll investigate whether this leads to any undesirable effects.
