### ISSUE TITLE
mdc-list-item__graphic font-size to big in mdc-list--avatar-list

### ISSUE THREAD

**Issue by kvdheuvel** [material-components/material-components-web#4007]
### What MDC Web Version are you using?

0.40.1

### What browser(s) is this bug affecting?

- Chrome
- IE
- Edge
- Firefox

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

The font-size of the graphic in an mdc-list--avatar-list is set to 40px which creates an huge icon. This can be seen in the demo page: https://material-components.github.io/material-components-web-catalog/#/component/list

When looking at the design specs https://material.io/design/components/lists.html#types the icon is smaller and is what we expected.

### What is the expected behavior?

An icon with the normal font-size in a mdc-list--avatar-list

### What is the actual behavior?

An icon with a font-size set to 40px

**Comment by touficbatache** [comment]
Right, the `font-size` should be `24px` instead of `40px`.

**Comment by kfranqueiro** [comment]
I traced this back to #3602 which was working on implementing dialog to spec, but I agree that this change within avatar lists' styles directly ends up being problematic. I'll work on a PR to revert that change to list styles and update the dialog screenshot tests accordingly.
