### ISSUE TITLE
How to activate focus on text field?

### ISSUE THREAD

**Issue by TheInvoker** [material-components/material-components-web#4009]
I have this code

        this.mdc_text = mdc.textField.MDCTextField.attachTo(this.$el);
        if (this.autofocus) {
            this.mdc_text.activateFocus();
        }

but the function activateFocus is undefined. How can I focus it?

https://material.io/develop/web/components/input-controls/text-field/

Thanks

**Comment by kfranqueiro** [comment]
`activateFocus` is a method on the foundation, not the component. It looks like we didn't expose a `focus` method on the component to proxy to the native input/textarea for this. I'll send a PR to add it.

**Comment by TheInvoker** [comment]
I ask of this because there's a general issue of trying to focus it, when combining it with vue/vue-router. It seems after switching pages, the focus is lost and can't be enabled with code. The user has to manually click on it to focus it again.

https://github.com/vuejs/vue/issues/8112
https://github.com/vuetifyjs/vuetify/issues/5487
