### ISSUE TITLE
Broken ES imports: declare ES module entry points

### ISSUE THREAD

**Issue by drochgenius** [material-components/material-components-web#4016]
### What MDC Web Version are you using?

`v0.41.0`

### What browser(s) is this bug affecting?

Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
But this issue is not browser-related.

### What OS are you using?

Mac OS X version 10.13.6

### What are the steps to reproduce the bug?

Prior to version MDC v0.41.0, we were relying on the `main` entry point in the `package.json` to resolve the ES module entry point.

As per this commit, `main` now resolves to the UMD bundle: https://github.com/material-components/material-components-web/commit/514f9f894a73999ef9740888944433acc7370669

While I understand that this change was intended, and well justified in most cases, we'd still like to keep the ability to resolve ES module entry points.

## Feature Requests

Although this is not standard yet, I would suggest we add the `module` field in every component  `package.json`, pointing to the ES module entry point of that module.

```javascript
  "main": "dist/mdc.base.js",
  "module": "index.js",
```

Proposal reference: https://github.com/rollup/rollup/wiki/pkg.module

## Additional information

There is already a lot of libraries implementing this, e.g. D3:
https://github.com/d3/d3-array/blob/master/package.json#L24

**Comment by drochgenius** [comment]
Thanks @kfranqueiro , 
I understand your point, although I am in favor of the `module` package field, and hope it gets standardized.

I was able to work around my issue using qualified import links.

```javascript
// before
import { MDCTextField } from '@material/textfield';
// after
import { MDCTextField } from '@material/textfield/index.js';
```

Regards

**Comment by kfranqueiro** [comment]
Ah, sorry for the confusion. We have a note in our changelog and getting started guide about explicitly referencing `index` if you want to work against the ES2015+ source now.
