### ISSUE TITLE
Consider switching from eslint to prettier + lint-staged

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#402]
- https://github.com/prettier/prettier
- https://github.com/prettier/prettier#pre-commit-hook-for-changed-files

Although eslint comes with a google styleguide config, our jsdoc requirements will be satisfied via the closure compiler.

Using this setup seems like a major advantage to me, since it means we never have to worry about JS linting errors again, and our code will be immediately consistent. 

Work to be done would most likely consist of the following:

- [ ] remove our dependency on eslint/eslint-config-google/etc.
- [ ] add dependency for prettier + lint-staged
- [ ] configure husky to run lint-staged on pre-commit _in addition to_ `validate-commit-msg`
- [ ] Use our specified prettier options: `--print-width 120 --single-quote --trailing-comma es5`
- [ ] Remove `fix:*` npm scripts (we don't even use the SCSS fix script any more)
- [ ] Alter `lint:js` rule to fail if prettier needs to make changes to a file (for CI)

Thoughts?

**Comment by amsheehan** [comment]
As a vim user, I am for this so you don't have to keep commenting on my softtab issues. :)

**Comment by amsheehan** [comment]
Since no one seems to have a strong opinion on the existing linting approach, we are closing this issue.
