### ISSUE TITLE
Scaled button font is cropped beyond border

### ISSUE THREAD

**Issue by iczman** [material-components/material-components-web#4023]
### What MDC Web Version are you using?

0.41.0

### What browser(s) is this bug affecting?

Chrome 69

### What OS are you using?

masOS 10.14

### What are the steps to reproduce the bug?

Override the button typography to set the font-size above 36px (fix height of the button)
```scss
$mdc-typography-styles-button: (
  font-size: 48px,
);

@import "@material/button/mdc-button";
```

### What is the expected behavior?

The button height scale appropriately with the font size increase, without cropping the text.

### What is the actual behavior?

Button height stays fixed at 36px, cropping the oversized text.

![image](https://user-images.githubusercontent.com/6440237/47779326-d156d700-dd33-11e8-9e23-685fc60deefc.png)

Note sure if this is related to #1932?

**Comment by kfranqueiro** [comment]
Yeah, #1932 represents this issue across MDC Web's components, and it has to do with how the [design guidance](https://material.io/design/layout/density-resolution.html#pixel-density-on-the-web) instructs to treat units in the spec. This is something that will require discussing and probably prototyping with our designers.

I'm going to close this one as a duplicate.
