### ISSUE TITLE
[Bug Report] MDCDrawer:opened event running twice when opening drawer.

### ISSUE THREAD

**Issue by TheInvoker** [material-components/material-components-web#4024]
### What MDC Web Version are you using?

https://unpkg.com/material-components-web@0.41.0/dist/material-components-web.min.js
https://unpkg.com/material-components-web@0.41.0/dist/material-components-web.min.css

### What browser(s) is this bug affecting?

Chrome 69

### What OS are you using?

Windows 10 latest

### What are the steps to reproduce the bug?

Open the drawer. You will notice 2 alerts.

### What is the expected behavior?

The MDCDrawer:opened event runs once. (only 1 alert)

### What is the actual behavior?

The MDCDrawer:opened event runs twice. (2 alerts)

https://jsfiddle.net/15xjtmzg/

**Comment by abhiomkar** [comment]
Thanks for reporting this issue @TheInvoker 	

I just sent a PR #4027 to fix this.

**Comment by guther** [comment]
Here the problems was not resolved. I'm using "@material/drawer": "^12.0.0",
