### ISSUE TITLE
Enhanced Select dropdown options displays under MDCDialog

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#4025]
### What MDC Web Version are you using?

0.41.0

### What browser(s) is this bug affecting?

- Firefox
- Edge
- Chrome

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

See the [CodePen](https://codepen.io/Darhakexge/pen/rqEbKy)

### What is the expected behavior?

Enhanced Select dropdown options should displays over MDCDialog

### What is the actual behavior?

Enhanced Select dropdown options displays under MDCDialog

**Comment by williamernest** [comment]
Thanks for filing this issue. Until we get this triaged and fixed, you can add `z-index: 8` to the menu surface element to overcome the issue. 

https://codepen.io/williamernest/pen/xyoNga
