### ISSUE TITLE
Inconsistency between design spec and actual implemented css

### ISSUE THREAD

**Issue by havesomeleeway** [material-components/material-components-web#4037]
According to the design specs, a two line list has a height of 64px
![css](https://user-images.githubusercontent.com/25948209/47901067-e1002800-deb9-11e8-8771-bda82a674fbd.png)

https://material.io/design/components/lists.html#specs

However over at the component demo, the list has a height of 72px
![height](https://user-images.githubusercontent.com/25948209/47901121-09882200-deba-11e8-98fd-ab7e072b111e.png)
https://material-components.github.io/material-components-web-catalog/#/component/list

#### Question:
Which one should we be following?

**Comment by abhiomkar** [comment]
Thanks for filing this issue.

So the two line list item with meta and without meta has different heights. Please see [this spec](https://material.io/design/components/lists.html?image=https%3A%2F%2Fstorage.googleapis.com%2Fspec-host-backup%2Fmio-design%252Fassets%252F1-YqqvjVvKr2aWHg6yQ9KOP9yFbk-4o9t%252Flist-spec-doubleline-individual.png#specs) where the two line list item without meta is still 72px.
