### ISSUE TITLE
How to put content in the tabs ?

### ISSUE THREAD

**Issue by Marcellllll** [material-components/material-components-web#4039]
Hi,

Thanks for making these nice components. I have a great looking tab-bar with tabs in it now, but don't see how to put content in the tabs.

Is there some kind of example code somewhere (or a site where you can actually see the HTML) of how to put content in each tab ?

Thanks, and kind regards

**Comment by kfranqueiro** [comment]
We've got an issue tracked for adding this, #3584, which also includes a codepen in the meantime. (It looks like you also just found it.)

For anyone else who finds this first, the codepen is https://codepen.io/kfranqueiro/pen/yxzppj.

I'll close this as a duplicate.
