### ISSUE TITLE
MDC Menu Surface: Terminology for anchor in the class name and documentation

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#4044]
MDC Menu Surface uses "anchor" term in `mdc-menu-surface--anchor` helper class which is different element when compared to anchor name used in `setMenuSurfaceAnchorElement` where anchor here represents the button that toggles menu surface.

**Comment by williamernest** [comment]
They're both the same. The element in the DOM that the menu surface should be anchored to. `setMenuSurfaceAnchorElement` can be any element on the page, not just the button that toggles the surface. It was added so developers could dynamically change the element the menu surface is anchored to. 

The `--anchor` class existed before as a way to indicate which element the menu surface should anchor to when it is first created. 

We may just want to eliminate `--anchor` entirely and force everyone to use `setMenuSurfaceAnchorElement`.

**Comment by abhiomkar** [comment]
Eliminating `--anchor` and just using `setAnchor` API doesn't seem to resolve the [problem](https://codepen.io/abhiomkar/pen/gQYNKL) unless I'm missing something. We might need to document about adding `position: relative` style to anchor element parent.

**Comment by williamernest** [comment]
Yeah, that's confusing. Maybe change it to `--relative` or `--container`?
