### ISSUE TITLE
mdc-layout-grid__cell  width

### ISSUE THREAD

**Issue by broros** [material-components/material-components-web#4047]
why does the default width of ( mdc-layout-grid__cell ) goes to 4? 

since I haven't specified any span amount it should go to auto width, meaning it should take the remaining apace, whatever that may be.

don't you think?

**Comment by kfranqueiro** [comment]
I think this is asking for something similar to #4065. I left a [comment](https://github.com/material-components/material-components-web/issues/4065#issuecomment-437185133) there explaining why this is probably unrealistic within the scope of MDC Layout Grid.
