### ISSUE TITLE
[Layout Grid] How to make a responsive 2 column layout

### ISSUE THREAD

**Issue by gmosx** [material-components/material-components-web#4048]
I would like to create a 2 column responsive layout where each column takes 50% of the width. 
I use the following markup:

```
    <div class="mdc-layout-grid">
        <div class="mdc-layout-grid__inner">
            <div class="mdc-layout-grid__cell--span-6">
            </div>
            <div class="mdc-layout-grid__cell--span-6">
            </div>
        </div>
    </div>
```

This works fine, but when I resize the window, and the `tablet` breakpoint kicks in, the grid gets 8 columns per row, instead of 12, and the `.mdc-layout-grid__cell--span-6` columns leave empty space to the right.

Is there a way to implement my use-case using `mdc-layout-grid` ?

**Comment by robbyrice** [comment]
I think you might be looking for something like this. This will keep the default span of 4 columns for a cell on phone and tablet, but on desktop (any screen size over 1024px if I remember correctly) will switch to 6 columns for each cell. Hope this helps.


```
<div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell
                    mdc-layout-grid__cell--span-6-desktop">
        </div>
        <div class="mdc-layout-grid__cell
                    mdc-layout-grid__cell--span-6-desktop">
        </div>
    </div>
</div>
```

**Comment by gmosx** [comment]
Thank you!
