### ISSUE TITLE
Double click on toggle icon of drawer

### ISSUE THREAD

**Issue by vuchastyi** [material-components/material-components-web#4049]
### What MDC Web Version are you using?

> I don't know what the version currently uses material-components.github.io/material-components-web-catalog. I guess latest.

### What browser(s) is this bug affecting?

> Google Chrome. Version: 70.0.3538.77 (Official Build) (64-bit)
> I guess it will be crashed in any browser.

### What OS are you using?

> Mac OS X El Capitan. Version: 10.11.6 (15G22010)
> I guess it will be crashed in any OS.

### What are the steps to reproduce the bug?

> 1. Open this [link](https://material-components.github.io/material-components-web-catalog/#/component/drawer/modal).
> 2. Double click on icon, which toggles drawer.

### What is the expected behavior?

> Drawer is opened / closed / opened then closed.
> Click again on toggle icon opens drawer.

### What is the actual behavior?

> Drawer crashes, black shadow at left side of screen.
> Click again on toggle icon doesn't opens drawer.

**Comment by kfranqueiro** [comment]
I haven't been able to reproduce this; I tried with Chrome (also 70) + Firefox + Safari on OS X, and Chrome + Firefox + Edge + IE on Windows.

Can you include a screenshot of what the broken state looks like, and also check the developer tools console for errors?

**Comment by vuchastyi** [comment]
Here's example:
![example](https://user-images.githubusercontent.com/19193608/48090305-3bc5b680-e20f-11e8-833a-2b44c901d79b.gif)
No errors in developer console.
I guess you need set something like `isAnimating = true` when drawer is in "animating" state. When animating is completed - set same variable to false value. To prevent unnecessary double clicks.
Also i cannot reproduce it using Windows.

**Comment by abhiomkar** [comment]
Thanks for reporting this issue @vuchastyi !

I tried to change the state of drawer programmatically and I was able to reproduce this issue.

```
drawer.open = true;
drawer.open = false; 
drawer.open = true; 
```

I sent PR #4078 to fix this bug.
