### ISSUE TITLE
Vue framework snackbar example references non-existent TRANS_END_EVENT_NAME string.

### ISSUE THREAD

**Issue by pgbross** [material-components/material-components-web#405]
### What MDC-Web Version are you using?

> 0.6.0

### What browser(s) is this bug affecting?

> Version 58.0.3029.19 beta (64-bit)

### What OS are you using?

> Fedora 25 (Linux p5q 4.9.13-201.fc25.x86_64)

### What Vue version are you using?
> 2.2.4

### What are the steps to reproduce the bug?

> 1. run the vue framework demo server
> 2. go to localhost:8080
> 3. Press the "show snackbar" button twice
> 4. Observe only the first snackbar message is shown

### What is the expected behavior?

> The v-mdc-snackbar component should use the same method that the packages/snackbar/index.js class uses to determine the correct transitionend event name.

### What is the actual behavior?

> The custom v-mdc-snackbar component is referencing a string removed when fixing issue #160, TRANS_END_EVENT_NAME. It should instead be using the method from the mdc-animation package thus:
```
      registerTransitionEndHandler(handler) {
        vm.$refs.root.addEventListener(getCorrectEventName(window, 'transitionend'), handler);
      },
      deregisterTransitionEndHandler(handler) {
        vm.$refs.root.removeEventListener(getCorrectEventName(window, 'transitionend'), handler);
      }
```

### Any other information you believe would be useful?
snackbar/index.js was updated in commit 4206d84b512078186485caf4abe4f47d4ce974fc  Mdc web/remove implicit dom querying (#160) 2017-01-06

**Comment by yeelan0319** [comment]
Thanks @pgbross. Definitely something we looked over and should fix.
I think you already nailed the problem down. Would you like to send out a PR for the fix?

**Comment by pgbross** [comment]
Sure, I will create a PR.
