### ISSUE TITLE
Issue with having text and material icons on the same line in full bleed card action

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4051]
## Bugs

Having an icon and text on the same line with a full bleed card action moves the text down for some reason.

### What MDC Web Version are you using?

> 0.41.0

### What browser(s) is this bug affecting?

> Chrome Version 70.0.3538.77 (Official Build) (64-bit)
> Safari Version 12.0 (14606.1.36.1.9)
> Assuming all others

### What OS are you using?

> MacOS 10.14

### What are the steps to reproduce the bug?

> Have a card with a card action that is set to full bleed.
> Inside the action have one button that goes the full length
> Inside the button have 2 text areas so the first one sticks to the left and the second one sticks to the right
> Add a material icon to the first text area with text inside
>
> Visit [CodePen](https://codepen.io/anon/pen/GwgBqb?editors=1010)

### What is the expected behavior?

> The text stays on the same level as the icon and doesn't move

### What is the actual behavior?

> The text that is next to the icon gets pushed down for some reason.

### Any other information you believe would be useful?

I have tried fixing the issue by adding vertical align to just the text and not the icon.
vertical align center and bottom do nothing.
vertical align top does move the text, but it is still in the wrong place (see image)

<img width="958" alt="screen shot 2018-11-05 at 11 15 55 pm" src="https://user-images.githubusercontent.com/26075792/47992096-d90de580-e150-11e8-9576-1260cadf526e.png">

The second text area is not effected by the icon

**Comment by emri99** [comment]
Hi, not sure it's a bug;

Introducing span break the flex alignment: check your [updated codepen](https://codepen.io/anon/pen/GwgYQX), just added inline style to span with


```scss
display: flex;
align-content: center;
```

**Comment by CyborgSemon** [comment]
Awesome that works great! Thanks!
