### ISSUE TITLE
Textfield in a form moves when data is added to it in Safari

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4052]
## Bugs

After some text has been inputed into a textfield, it moves down when the second one is selected

### What MDC Web Version are you using?

> 0.41.0

### What browser(s) is this bug affecting?

> Only in Safari Version 12.0 (14606.1.36.1.9) so far.

### What OS are you using?

> MacOS 10.14

### What are the steps to reproduce the bug?

> I have no idea how to reproduce it, but the bug happens in [CodePen](https://codepen.io/anon/pen/YRPjdK)

### What is the expected behavior?

> The text fields don't move

### What is the actual behavior?

> The text areas move when data is added into them, then they go back to normal when both of them have data.

### Any other information you believe would be useful?

So far this is only effecting Safari. When both fields get text added to them, then you can remove the text and the bug wont happen again until you reload the page.

Here are some screen shots

<img width="582" alt="screen shot 2018-11-05 at 11 34 38 pm" src="https://user-images.githubusercontent.com/26075792/47993127-926dba80-e153-11e8-8b67-0493e93565a2.png">

<img width="557" alt="screen shot 2018-11-05 at 11 34 45 pm" src="https://user-images.githubusercontent.com/26075792/47993138-98fc3200-e153-11e8-8ba3-1c49f9b1c6ce.png">

<img width="533" alt="screen shot 2018-11-05 at 11 35 12 pm" src="https://user-images.githubusercontent.com/26075792/47993148-a5808a80-e153-11e8-842d-707839e745d2.png">

<img width="538" alt="screen shot 2018-11-05 at 11 34 51 pm" src="https://user-images.githubusercontent.com/26075792/47993141-9ef21300-e153-11e8-801c-c2a13532a594.png">

**Comment by kfranqueiro** [comment]
This is rather odd, since it seems like once the text fields realign they never misalign again.

I'm not sure whether we can resolve this somehow within the component, but if nothing else, putting a `display: flex` container around it appears to work:

```html
    <form class="loginMargin" action="includes/login.php" method="post">
      <div class="loginInputContainer">
        <div class="mdc-text-field textFieldUsername" data-mdc-auto-init="MDCTextField">
          ...
        </div>
        <div class="mdc-text-field" data-mdc-auto-init="MDCTextField">
          ...
        </div>
      </div>
      <div class="button-container">
        ...
      </div>
    </form>
```

```scss
.loginInputContainer {
  display: flex;
}

.textFieldUsername {
  margin-right: 4px;
}
```

**Comment by CyborgSemon** [comment]
Sweet that seems to work great!
Im not sure if something like this will need to have an example in the textfield documentation, but for now i'll close this issue.
Thanks again :)
