### ISSUE TITLE
Evenly distribute grid cells option

### ISSUE THREAD

**Issue by vtJoshuaVanDeren** [material-components/material-components-web#4065]
I think it would be beneficial if when `mdc-layout-grid__cell` is specified, instead of defaulting to `4`, it could dynamically change column width to fill a grid.

For example:
```
<div class="mdc-layout-grid">
  <div class="mdc-layout-grid__inner">
    <p class="mdc-layout-grid__cell">A</p>
    <p class="mdc-layout-grid__cell">B</p>
    <p class="mdc-layout-grid__cell">C</p>
  </div>
</div>
```
Where `A column width = B column width = C column width` and  `A column width + B column width + C column width = [grid width]`.

However, the biggest challenge I could envision with this is if the number of `grid__cell`'s are not a multiple of `[grid width]`. Any thoughts?

**Comment by kfranqueiro** [comment]
In addition to the problem of non-integer quotients, there are a couple of other issues I can think of:

* This behavior would break MDC Layout Grid's breakpoint system, which has different numbers of columns for different viewport width ranges
* I'm not sure it'd be possible to implement this purely in Sass, and it seems heavy-handed to add JS to a layout grid system

So this isn't something we're currently interested in implementing in MDC Layout Grid. This would be more suited to direct use of CSS flexbox or grid.
