### ISSUE TITLE
Chip Demo Does Not Work for Filter Chips mdc-chip-set--filter

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#4067]
[The demo](https://material-components.github.io/material-components-web-catalog/#/component/chips) is not working. 

**Expected behavior**: click on a filter chip to toggle it on/off.

**Actual behavior**: click on a chip does not addon/off indicator (checkmark or background-color).

**Comment by kfranqueiro** [comment]
This is an issue specifically with the catalog, presumably due to a bug in how we're managing React components' lifecycle. I logged it in the catalog repo when I first discovered it: https://github.com/material-components/material-components-web-catalog/issues/176

Closing this as a duplicate.
