### ISSUE TITLE
mdc-select/option: the attribute selected doesn't change

### ISSUE THREAD

**Issue by rubenmendoza** [material-components/material-components-web#4068]
## Bugs

Inspect the demo
![image](https://user-images.githubusercontent.com/3853885/48175506-79862480-e360-11e8-85d5-8706c62677fc.png)

https://material-components.github.io/material-components-web-catalog/#/component/select

### What MDC Web Version are you using?

0.41

### What browser(s) is this bug affecting?

Tested in Chrome

### What are the steps to reproduce the bug?

Select banana from the list.
The inspector will show that the attribute selected doesn't change in the option element.

<div class="mdc-select mdc-ripple-upgraded" style="--mdc-ripple-fg-size:58px; --mdc-ripple-fg-scale:2.10353; --mdc-ripple-fg-translate-start:19.5px, -1.8125px; --mdc-ripple-fg-translate-end:19.5px, -1px;"><i class="mdc-select__dropdown-icon"></i><select id="select-hero" class="mdc-select__native-control">
<option value="" disabled selected></option>
<option value="apple">Apple</option>
<option value="orange">Orange</option>
<option value="banana">Banana</option>
</select>
<label for="select-hero" class="mdc-floating-label mdc-floating-label--float-above">Fruit</label>
<div class="mdc-line-ripple" style="transform-origin: 48.5px center 0px;"></div>
</div>

### What is the expected behavior?
Add selected to the element option.
option value="banana" selected>Banana </option>

### What is the actual behavior?

Attribute selected doesn't change. Is still on the initial selected element
option value="banana">Banana</option>

**Comment by kfranqueiro** [comment]
MDC Select isn't doing anything special or causing any bug here; this is how native selects work. The DOM attribute doesn't change, but the programmatic `selectedIndex` and `value` change.

See [codepen](https://codepen.io/kfranqueiro/pen/pQyEwN?editors=0010).
