### ISSUE TITLE
mdc-top-app-bar position

### ISSUE THREAD

**Issue by Larsklopstra** [material-components/material-components-web#4071]
### What MDC Web Version are you using?

> ^0.41.0

### What browser(s) is this bug affecting?

> All

### What OS are you using?

> Windows 10 Home

### What is the expected behavior?

> The `mdc-top-app-bar component` should be `position: relative` by default.

### What is the actual behavior?

> It appears to be `position: fixed`. The `mdc-top-app-bar--fixed` should take care of that instead.

**Comment by williamernest** [comment]
Thanks for filing this issue. The default top app bar has scrolling behavior that allows the top app bar to scroll out of the screen when scrolling down the page but be the first element to scroll back into view when the user starts to scroll up. This requires `position: fixed` on the `mdc-top-app-bar` element. The `--fixed` class is used as a variant that disables the scrolling behavior.

**Comment by abhiomkar** [comment]
I'm closing this issue since it is intentional to keep the top app bar `fixed` position as per Will's comment.
