### ISSUE TITLE
Material customization app demoed at Chrome Dev Summit 2018 should be made public

### ISSUE THREAD

**Issue by alcfeoh** [material-components/material-components-web#4079]
I saw the demo of an experimental browser app that allows for quick customization of Material colors, sizes, etc. at the Chrome Dev Summit  2018, and outputs SASS or CSS.

It's a great idea and I believe it should be brought to the public. The only alternative I know for this is the Sketch option and it's not as fast and developer friendly. As a dev, I don't want to pay for Sketch for quick tweaks to my Material components CSS. Opening a browser tab to use this tool is frictionless and does not require a designer background, which is great.

Many of my clients would widely adopt that tool as well.

**Comment by abhiomkar** [comment]
Hi @alcfeoh, Thanks for your feedback!

The tool that was showed on CDS 2018 is still experimental and being worked on. Currently it is not available to public. We're looking for ways to have the tool easily maintainable and scalable.

**Comment by alcfeoh** [comment]
Thanks! Please let me know when there's a public URL for it.
