### ISSUE TITLE
Textfield with type="number" overlays label on invalid input

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#408]
When using an MDCTextfield with the `input` type set to `number`, the label doesn't behave correctly when there is an invalid value in the textfield:

![image](https://cloud.githubusercontent.com/assets/409615/24108410/68f61e5c-0d85-11e7-8b24-44239d795179.png)

Steps to reproduce:
1. Load http://codepen.io/anon/pen/ryJzMb?editors=1010
2. Change the textfield value to an invalid value, such as `1..1`
3. Click away from the textfield, so that it loses focus

Expected result:
The label remains floating, above the input text.

Actual result:
The label moves down, in front of the input text.

Tested on: `@material/textfield` version 0.2.3.

**Comment by sgomes** [comment]
*Note:* It may be possible to distinguish between empty values and bad inputs by looking at the `validity` property. Bad input results in `validity.badInput` set to `true`, whereas empty input results in `validity.badInput` set to `false`.

**Comment by trimox** [comment]
@sgomes, @amsheehan,
Would adding the validity argument to `getNativeInput_() `and modifying the check in `deactivateFocus_() `to also check for badInput? 

```
  getNativeInput_() {
    return this.adapter_.getNativeInput() || {
      checkValidity: () => true,
      validity: ValidityState,
      value: '',
      disabled: false,
    };
  }
```
```
  deactivateFocus_() {
    const {FOCUSED, INVALID, LABEL_FLOAT_ABOVE} = MDCTextfieldFoundation.cssClasses;
    const input = this.getNativeInput_();
    const isValid = input.checkValidity();

    this.adapter_.removeClass(FOCUSED);
    if (!input.value && (!input.validity.badInput)) {
      this.adapter_.removeClassFromLabel(LABEL_FLOAT_ABOVE);
      this.receivedUserInput_ = false;
    }
    if (isValid) {
      this.adapter_.removeClass(INVALID);
    } else {
      this.adapter_.addClass(INVALID);
    }
    this.updateHelptextOnDeactivation_(isValid);
  }

```

**Comment by trimox** [comment]
Also, I did research into possibly using [reportValidity()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity), sadly the call is not valid in IE 11.

**Comment by trimox** [comment]
Decided to change tactics on this..
Added a isBadInput check.
```
  isBadInput_() {
    const input = this.getNativeInput_();
    return input.validity ? input.validity.badInput : input.badInput;
  }
```

```
  getNativeInput_() {
    return this.adapter_.getNativeInput() || {
      checkValidity: () => true,
      value: '',
      disabled: false,
      badInput: false,
    };
  }
```

And to check for a bad value with type="number" etc..
```
    if (!input.value && !this.isBadInput_()) {
      this.adapter_.removeClassFromLabel(LABEL_FLOAT_ABOVE);
      this.receivedUserInput_ = false;
    }

```
