### ISSUE TITLE
Dialog put focus on both button in demo example

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#409]
### What MDC-Web Version are you using?

>0.7.0

### What browser(s) is this bug affecting?

> Chrome Version 57.0.2987.98 (64-bit)
> Chrome Canary Version 59.0.3046.0 (Official Build) canary (64-bit)

### What OS are you using?

> macOS 10.12.3 (16D32)

### What are the steps to reproduce the bug?

> 1. run the demo server
> 2. go to localhost:8080/dialog.html
> 3. Click `show dialog` button on the left
> 4. Hit tab (more than 1 time) and then close the dialog (either by click one of the button or escape)
> 5. Click `show scrolling dialog` button on the right
>

### What is the expected behavior?

> Just the `accept` button should trapped focus

### What is the actual behavior?

> Both `decline` and `accept` trapped focus

### Any other information you believe would be useful?

A couple of known fact that may help debug:
- It only happens when the page first load, once you interact with `scrolling dialog`, I am not able to reproduce it.
- It only happens when you interact with `default dialog` then `scrolling dialog`, not visa versa.

**Comment by amsheehan** [comment]
I can reproduce it on my machine as well. Good catch!
