### ISSUE TITLE
Issue with CodePen template

### ISSUE THREAD

**Issue by deap82** [material-components/material-components-web#4092]
I wanted to do some troubleshooting using the CodePen template
at https://codepen.io/williamernest/pen/deyxyp

But it immediataley gives "MDCRipple is not defined" in the console so something seems off with the inclusion of MDC WEB JS components.

Could anyone point me in the right direction?

**Comment by abhiomkar** [comment]
The example in codepen is missing global namespace - `mdc.ripple.`.

Please use this updated [codepen template](https://codepen.io/abhiomkar/pen/wQPvON).
