### ISSUE TITLE
FAB not working when above clickable card / menu

### ISSUE THREAD

**Issue by Marcellllll** [material-components/material-components-web#4093]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What MDC Web Version are you using?

0.41

### What browser(s) is this bug affecting?

Chrome (Version 70.0.3538.77 (Official Build) (64-bit))

#
![fab](https://user-images.githubusercontent.com/39009439/48709323-452a2800-ebec-11e8-91c9-07164ba86c13.jpg)
## What OS are you using?

Ubuntu 16.04

### What are the steps to reproduce the bug?

Create a clickable card with an options menu. Have a FAB at the bottom. Scroll to have the FAB above the cards and try to click on the FAB.

When you click on the FAB it only registers the click on the card/menu below.

### What is the expected behavior?

I would expect that when you click on the FAB it executes the associated action in the FAB, not consider it to be a click on the underlying item.

### What is the actual behavior?

Only a click event for the underlying element is triggered, no click for the FAB.

**Comment by abhiomkar** [comment]
Can you please provide a codepen to demonstrate this issue?

**Comment by Marcellllll** [comment]
Hi Abhiomkar,

Thanks for the reply. Unfortunately I never used codepen, but I will try to figure out how it works and see how to include mdc-web in the codepen.

In fact the problem occurs when dynamically adding new HTML elements via JavaScript. These elements appear on top of the FAB, and capture any click on the FAB.

I have an ugly work-around for it, which updates the z-index of the FAB after adding HTML, which seems to work. 

I will settle for the work-around at the moment and then as soon as I have some time I will try to figure out how to use codepen with mdc-web which would be very useful in the future.

If you prefer I can close the issue for the moment.

**Comment by kfranqueiro** [comment]
FYI, we have a codepen template with MDC Web already loaded (which is included in our issue template): https://codepen.io/williamernest/pen/deyxyp

You can fork that and make changes.

**Comment by williamernest** [comment]
@Marcellllll Thanks for filing this issue. Modifying the z-index to suit your needs to the only way to prevent this. We've chosen to not add z-index to the component to prevent running into issues with other components.
