### ISSUE TITLE
MDCChipSet Filter Chips Does Not Work

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#4095]
[Here's the codepen](https://codepen.io/rhroyston/pen/JeObmg). Can anyone prove me wrong?

The documentation also fails to clearly indicate that multiple chip elements should be placed inside the chipset element. All the documentation says is "...", literally.

**Comment by abhiomkar** [comment]
Hi @rhroyston, I just looked at your codepen example.

The auto init attribute has to be a data attribute:
`mdc-auto-init="MDCChipSet"` => `data-mdc-auto-init="MDCChipSet"`

**Comment by rhroyston** [comment]
alrighty then. ... my bad
