### ISSUE TITLE
MDC List: Checkbox doesn't toggle when rendered inside list item

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#4107]
Steps to reproduce:

1. Place checkbox inside mdc list item.
2. Make sure to add label element that is mapped to checkbox input (using `label`, `for` attribute).
3. Click on the label text, the checkbox is toggled twice.

Reproducible [example on stackblitz](https://stackblitz.com/edit/mdc-list-demo-pbwbq4?file=index.html).

Actual behaviour:

The checkbox should be toggled only once. Works fine when clicked on the area that is not checkbox and label element.

**Comment by williamernest** [comment]
We could potentially fix this quickly by adding `pointer-events: none` to `label, input[type="checkbox"]` elements inside of `mdc-list-item` elements.

**Comment by kfranqueiro** [comment]
Closed via #4055
