### ISSUE TITLE
MDCTextField full width does not support  leading and trailing icons.

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#4108]
### What MDC Web Version are you using?

> 0.41.1

### What browser(s) is this bug affecting?

> All

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

> [See the CodePen](https://codepen.io/Darhakexge/pen/EOEKvw)

### What is the expected behavior?

> The text field should have paddings for leading and trailing icons
> The placeholder must show an ellipsis if overflows

### What is the actual behavior?

> The placeholder overlaps with the icons.

**Comment by williamernest** [comment]
@Darhakexge Thanks for filing this issue. The leading/trailing icons should only be used with the filled or outlined variant of the text field. 

https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#text-field-with-leading-and-trailing-icons

**Comment by Darhakexge** [comment]
Ok, I had not read that detail, but I guess it is still necessary to control the text-overflow in the placeholder.

**Comment by abhiomkar** [comment]
Leading & trailing icons are not supported on full width text field variant as stated in the document.

But you can definitely customize `mdc-text-field__input` based on the use case to apply offset on placeholder.
