### ISSUE TITLE
MDCTextField (Outlined): ChromeOS - styling

### ISSUE THREAD

**Issue by kenopen** [material-components/material-components-web#4109]
### What MDC Web Version are you using?
Latest version being used on Material.io

### What browser(s) is this bug affecting?
Chrome: Version 70.0.3538.110 (Official Build) (32-bit)

### What OS are you using?
ChromeOS (Samsung Chromebook. Notebook Model/MODELO: XE513C24)
Platform: 11021.81.0 (Official Build) stable-channel kevin
Firmware: Google_Kevin.8785.264.0
Channel: Currently on stable

### What are the steps to reproduce the bug?
1. Go to Material.io site text-field for web: https://material-components.github.io/material-components-web-catalog/#/component/text-field
2. Attempt to edit any "Outlined" text field

### What is the expected behavior?
Expected behaviour is for text field to maintain existing background colour and display text (similar to non-outlined text field)

### What is the actual behavior?
Text field colour changes to multi coloured and text cannot be seen/read.

### Any other information you believe would be useful?
View the following video showcasing current issue on device:
https://drive.google.com/file/d/1FDoIciQDM4CBT2xNMVhIsocEzwinZQJ2/view?usp=sharing

**Comment by abhiomkar** [comment]
Thanks for reporting this issue @kenopen!

This seems like issue rendering SVG element on chrome OS browser. We're in the process of replacing SVG with div elements (PR #4035).

This issue should be fixed in upcoming release when we land this PR.

**Comment by kenopen** [comment]
@abhiomkar Thanks... the latest commit resolved this issue.
