### ISSUE TITLE
Left-aligned snackbar appears under drawer

### ISSUE THREAD

**Issue by mantaspet** [material-components/material-components-web#4113]
## Bugs

>When calling show() method on MDCSnackbar with a dismissable drawer present, it appears underneath that drawer.

### What MDC Web Version are you using?

> 0.41.0

### What browser(s) is this bug affecting?

> Version: 70.0.3538.110 (Official Build) (64-bit) (cohort: 70_110_Win)
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

### What OS are you using?

> Windows 10 Home v10.0.17134 Build 17134

### What are the steps to reproduce the bug?

> 1. Open [https://material-components.github.io/material-components-web-catalog/#/component/snackbar](https://material-components.github.io/material-components-web-catalog/#/component/snackbar)
> 2. Press the menu button in the top left to open the drawer
> 3. Press "Show start aligned" button at the bottom of the page (in "Snackbar" section)

### What is the expected behavior?

> The snackbar should appear either to the right of the drawer or keep the same position but be above the drawer. Not sure which one, didn't see it mentioned in the spec

### What is the actual behavior?

> The snackbar appears underneath the drawer

### Any other information you believe would be useful?
> If the correct solution is to display it above the snackbar it gets fixed by adding the "z-index: 1" property on mdc-snackbar div

**Comment by abhiomkar** [comment]
Thanks for reporting this issue.

This is being fixed in PR #4070, the updated z-index would be above drawer. As a workaround you can bump up the z-index value to be more than drawer's z-index which is more than `6`.
