### ISSUE TITLE
MDCTextField - outlined + prefilled value means label overlaps outline

### ISSUE THREAD

**Issue by unionthugface** [material-components/material-components-web#4114]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

If you want to include a prefilled value to a regular (i.e. not outlined) text field, you add the class `mdc-floating-label--float-above` to the label to make sure it floats properly.  When using the outlined text field, this does not help; instead the label overlaps the surrounding box.  A prefilled, outlined text field without the class `mdc-floating-label--float-above` on its label is also messed up, and the label overlaps with the value of the text field instead.

### What MDC Web Version are you using?

0.41.1

### What browser(s) is this bug affecting?

Chrome 70.0.3538.110 64-bit

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Create an outlined MDCTextField with a prefilled value.
Here is a CodePen: https://codepen.io/anon/pen/rQZzEq

### What is the expected behavior?

The expected behavior would be a floating label with a notch removed from the surrounding outline to make room for the label, as shown on the material.io site, like this:

![image](https://user-images.githubusercontent.com/3844505/49103581-95c70400-f230-11e8-9f4b-6e8e06e9676f.png)

### What is the actual behavior?

![image](https://user-images.githubusercontent.com/3844505/49103383-091c4600-f230-11e8-9750-2d35ea3a5b48.png)

![image](https://user-images.githubusercontent.com/3844505/49103457-45e83d00-f230-11e8-86de-f8c553e56227.png)

**Comment by abhiomkar** [comment]
Thanks for pointing to codepen for reproducible step. You'll need to instantiate textfield on the text field root element for notched outline + floating label to work. 

Here is working a [example on codepen](https://codepen.io/kfranqueiro/pen/QJVObP) by @kfranqueiro

**Comment by kfranqueiro** [comment]
Additionally, FYI, we're planning for our next release to include an updated notched outline component with better support for FOUC prevention before JS loads.

**Comment by unionthugface** [comment]
> 
> 
> Thanks for pointing to codepen for reproducible step. You'll need to instantiate textfield on the text field root element for notched outline + floating label to work.
> 
> Here is a working [example on codepen](https://codepen.io/kfranqueiro/pen/QJVObP) by @kfranqueiro

Thank you @abhiomkar .  I am struggling because the docs do not mention `attachTo` anywhere, as per your code example.  Instead they say `new MDCTextField(document.querySelector('.mdc-text-field'));`.  Where does `mdc.textField.MDCTextField` come from?

**Comment by abhiomkar** [comment]
If you use MDC Web via CDN, it registers a global variable `mdc` for easy access to all components, - `mdc.textField.MDCTextField` for example.

Please see our [quick start guide](https://github.com/material-components/material-components-web) for examples.


`new mdc.textField.MDCTextField()` and `mdc.textField.MDCTextField.attachTo()` does the same thing.
