### ISSUE TITLE
Readme seems to have a typo

### ISSUE THREAD

**Issue by JackReis** [material-components/material-components-web#4119]
The Architecture page has the text 

"Foundation has-a Adapter." at https://github.com/material-components/material-components-web/blob/master/docs/code/architecture.md#foundation

**Comment by kfranqueiro** [comment]
"has-a" is referring to the name of a composition relationship: https://en.wikipedia.org/wiki/Has-a

I suppose we could link to that if it would help?

**Comment by williamernest** [comment]
That statement seems out of place and inconsistent with the rest of the section.
