### ISSUE TITLE
Dialog is not centered on screen

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#413]
As per the spec:
"Simple dialogs are displayed centered vertically and horizontally on the screen."

The dialog is not currently displayed vertically centered on screen:

![image](https://cloud.githubusercontent.com/assets/409615/24114276/8845e05a-0d97-11e7-944d-b977351ae472.png)

This seems to be because the `mdc-dialog__surface` is set to `bottom: 50vh`, which positions the bottom of the surface at the vertical centre of the screen, rather than center the entire surface on the screen.

**Possible fix strategies**: Use `bottom: 50vh` with `transform: translateY(50%)`, or use `bottom` with a `calc()`. Removing `bottom: 50vh` also seems to work, but may need cross-browser testing.

**Comment by amsheehan** [comment]
I believe removing `bottom: 50vh` is the correct fix. As I recall it's styled with `justify-content: center` and `align-items: center`
