### ISSUE TITLE
[Feature request] Add support for mutable selections in MDCSelection

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4132]
Feature request to have the ability to allow mutable selections in MDCSelect. like being able to choose more than one option in one select box.

**Comment by williamernest** [comment]
@CyborgSemon Thanks for filing this issue. The native `select` element that allows for multiple selections doesn't allow for a style changes across all browsers so this is not something we would be able to support in our version of the `select` component. As for allowing users to make multiple selections, this is functionality that should be added to the MDCList component shortly.

**Comment by CyborgSemon** [comment]
Oh awesome! Is this something that is already in a milestone?

**Comment by williamernest** [comment]
#4124 should finish implementing this behavior in the MDCList.
