### ISSUE TITLE
[Bug] MDCSlider discrete circle should adapt to the size of the number in it

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4134]
I know this is kind of unreasonable, but the discrete MDCSlider should change the little pop up circle to adapt to the size of the number.

eg:

![image](https://user-images.githubusercontent.com/26075792/49335503-5dba2980-f653-11e8-950f-49985c3ef0f1.png)

I know generally numbers don't go into the 1000's for sliders, but I though I might as well add this to the ice-box as I don't see this being added any time soon as probability a difficult minor change

**Comment by asyncLiz** [comment]
@joyzhong can you verify if this is fixed with the new slider?

**Comment by joyzhong** [comment]
Yes, this is fixed in the new slider (in canary). The value indicator size adapts to the content.
