### ISSUE TITLE
Uncaught Error: mdc-drawer--persistent class required in root element. 

### ISSUE THREAD

**Issue by L200150019** [material-components/material-components-web#4139]
sorry sir i have a error about this . i not using npm . i using CDN in this link 
`<script src="https://unpkg.com/material-components-web@0.36.1/dist/material-components-web.min.js">
`

 

this eror = 

`Uncaught Error: mdc-drawer--persistent class required in root element.

at e.value (material-components-web.min.js:182) at e.t (material-components-web.min.js:6) at new e (material-components-web.min.js:182) at HTMLDocument. (misc.js:13) at l (jquery.min.js:2) at c (jquery.min.js:2)
``

i read the new documentation but its not helped me

`(function($) {
  'use strict';
  $(function() {
    var body = $('body');
    var contentWrapper = $('.content-wrapper');
    var scroller = $('.container-scroller');
    var footer = $('.footer');
    var sidebar = $('.mdc-drawer-menu');

    // Menu Toggle Function
    var drawerEl = document.querySelector('.mdc-persistent-drawer');
    var MDCPersistentDrawer = mdc.drawer.MDCPersistentDrawer;
    var drawer = new MDCPersistentDrawer(drawerEl);
    document.querySelector('.menu-toggler').addEventListener('click', function() {
      drawer.open = !drawer.open;
    });

    //Add active class to nav-link based on url dynamically
    //Active class can be hard coded directly in html file also as required
    var current = location.pathname.split("/").slice(-1)[0].replace(/^\/|\/$/g, '');
    $('.mdc-drawer-item .mdc-drawer-link', sidebar).each(function() {
      var $this = $(this);
      if (current === "") {
        //for root url
        if ($this.attr('href').indexOf("index.html") !== -1) {
          $(this).addClass('active');
          if ($(this).parents('.mdc-expansion-panel').length) {
            $(this).closest('.mdc-expansion-panel').addClass('expanded');
          }
        }
      } else {
        //for other url
        if ($this.attr('href').indexOf(current) !== -1) {
          $(this).addClass('active');
          if ($(this).parents('.mdc-expansion-panel').length) {
            $(this).closest('.mdc-expansion-panel').addClass('expanded');
          }
        }
      }
    })

    $(".mdc-toolbar__menu-icon").on("click", function(){
      $(".body-wrapper .page-wrapper .content-wrapper").toggleClass("drawer-minimized");
    });
  });
})(jQuery);`

https://material.io/components/web/catalog/drawers/

![yhahaha](https://user-images.githubusercontent.com/22300292/49383844-490d8c80-f74c-11e8-9e27-3c8461f3721c.PNG)
`

**Comment by L200150019** [comment]
helppp

**Comment by abhiomkar** [comment]
Seems like you're using older version of drawer.

Please see [this codepen](https://codepen.io/abhiomkar/pen/XywJdo) for sample usage of dismissible drawer using CDN.

**Comment by L200150019** [comment]
Sir , can you help me about the newest code of the sidebar ? This JS is not
work

Pada tanggal Sel, 4 Des 2018 23.22, Abhinay Omkar <notifications@github.com>
menulis:

**Comment by L200150019** [comment]
Thanks you sir

Pada tanggal Rab, 5 Des 2018 11.32, Adhik Mulat <adhik12th@gmail.com>
menulis:
