### ISSUE TITLE
MDCTextField: Update dense variant when complete

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#4142]
The current density spec is not complete and the current implementation of the dense variant of the text field will likely change dramatically. Since the maintenance of the dense variant has been difficult, we have decided to remove the current version of the dense text field until the density spec is completed.

**Comment by aetheric8** [comment]
I would appreciate having dense components to display more information in web applications. Is it possible to reduce the base grid unit anyhow to archive this?
