### ISSUE TITLE
MDC Fab peeking through enhanced select dropdown

### ISSUE THREAD

**Issue by Richienb** [material-components/material-components-web#4150]
### What MDC Web Version are you using?

0.42.0

### What browser(s) is this bug affecting?

All browsers

### What OS are you using?

Windows 10. More specifically:

![Windows Version](https://user-images.githubusercontent.com/29491356/49560674-47c0a780-f978-11e8-897f-d77acb613811.PNG)

### What are the steps to reproduce the bug?

1. Go to [this codepen](https://codepen.io/Richienb/pen/GwbYjE?editors=1100)
2. Click the settings button
3. Open the theme selector selector
4. Decrease the size of the preview window

### What is the expected behavior?

MDC Select drop-down menu should overlap MDC Fab.

### What is the actual behaviour?

MDC Fab peeks through MDC Select drop-down menu.

![The problem](https://user-images.githubusercontent.com/29491356/49560557-d08b1380-f977-11e8-9895-10997270ccdb.png)

**Comment by williamernest** [comment]
Thanks for filing this issue. It looks like this may be a problem with the way you have your components laid out. The Fab is designed to be above all content on the page, so it should display above the `mdc-select` and `mdc-textfield` components. The menu is designed to be above page content and therefore displays above the fab. You could adjust your Fab location or the width when the component transitions to the bottom right.
