### ISSUE TITLE
0.42.0 build error on Invalid radius

### ISSUE THREAD

**Issue by shiorap** [material-components/material-components-web#4158]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?
0.42.0

### What browser(s) is this bug affecting?
n/a

> Please include the browser version. A user-agent string is also quite helpful.

### What OS are you using?

> Please include the OS version.

### What are the steps to reproduce the bug?

- Have Laravel 5.7 installed
- Have configured a react (php artisan preset react)
- Run npm install material-components-web
- Run npm build dev

Here's my package.json
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.18",
        "babel-preset-react": "^6.23.0",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^2.0",
        "lodash": "^4.17.5",
        "popper.js": "^1.12",
        "react": "^16.2.0",
        "react-dom": "^16.2.0"
    },
    "dependencies": {
        "@material/react-button": "^0.7.1",
        "@material/react-card": "^0.7.1",
        "@material/react-checkbox": "^0.7.1",
        "@material/react-layout-grid": "^0.7.1",
        "@material/react-list": "^0.7.1",
        "@material/react-material-icon": "^0.7.1",
        "@material/react-ripple": "^0.7.1",
        "@material/react-select": "^0.7.1",
        "@material/react-text-field": "^0.7.1",
        "ajv": "^6.6.1",
        "imagemin": "^6.0.0",
        "material-components-web": "^0.42.0",
        "node-sass": "^4.10.0",
        "react-router-dom": "^4.3.1",
        "reset-css": "^4.0.1"
    }
}

### What is the expected behavior?

It should build just fine just like the previous version 0.41.1

### What is the actual behavior?

it is throwing error Invalid radius, see below for actual error message.

### Any other information you believe would be useful?

Here's the actual error message:

> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting

 ERROR  Failed to compile with 2 errors                                                                                                                                               9:17:54 AM

 error  in ./resources/sass/app.scss

Module build failed:
undefined
          ^
      Invalid radius: '50%' radius is not supported
      in node_modules\@material\shape\_functions.scss (line 168, column 12)

 @ ./resources/sass/app.scss 4:14-254
 @ multi ./resources/js/app.js ./resources/sass/app.scss

 error  in ./resources/sass/app.scss

Module build failed: ModuleBuildError: Module build failed:
undefined
          ^
      Invalid radius: '50%' radius is not supported
      in node_modules\@material\shape\_functions.scss (line 168, column 12)
    at runLoaders (D:\Wamp64\www\chameleon4\node_modules\webpack\lib\NormalModule.js:195:19)
    at D:\Wamp64\www\chameleon4\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at D:\Wamp64\www\chameleon4\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (D:\Wamp64\www\chameleon4\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (D:\Wamp64\www\chameleon4\node_modules\sass-loader\lib\loader.js:55:13)
    at Object.done [as callback] (D:\Wamp64\www\chameleon4\node_modules\neo-async\async.js:8077:18)
    at options.error (D:\Wamp64\www\chameleon4\node_modules\node-sass\lib\index.js:294:32)

**Comment by williamernest** [comment]
I believe this issue may be caused by using 2 different versions of MDC-Web. The react components at `v0.7.1` are using the components at `v0.41.0`. Since you have also installed the `material-components-web` repo at `v0.42.0` I think some of the files may be clobbering each other. There's an [appendix](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#appendix-configuring-a-sass-importer-for-nested-node_modules) in our getting started that may be able to help. If configuring a custom importer doesn't work, you may want to keep your `material-components-web` repo in sync with the version that the react components use.
