### ISSUE TITLE
Top App Bar needs styling update to allow for nested TabBar

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#4175]
related https://github.com/material-components/material-components-web-react/issues/499

According to some mocks found on material.io (first image on https://material.io/design/components/tabs.html#usage), you can nest tab bar within top app bar. This does not just work out of the box, which means we need to add some SCSS support.

**Comment by kfranqueiro** [comment]
#3633 related?

**Comment by moog16** [comment]
Yes closing! Thanks
