### ISSUE TITLE
mdc-notched-outline does not detect .mdc-floating-label--float-above

### ISSUE THREAD

**Issue by GusRuss89** [material-components/material-components-web#4182]
Unless I'm missing something, you can't currently pre-fill an outlined field, because the notch doesn't open up automatically.

Instantiation of the `MDCNotchedOutline` should detect whether the inner label is floating (by checking for the class), and if so the notch should open.

If I'm missing something, please let me know. I'll be happy to add a PR to improve the docs.

**Comment by williamernest** [comment]
Can you show the markup you're using? The label should be placed inside the notch element inside the notched outline. This forces the notch to render opened until the JS instantiates, and it should render correctly before any JS is loaded. After the JS is loaded, the width of the label is calculated and the notch element width is set accordingly. 

```
<div class="mdc-text-field mdc-text-field--outlined">
  <input type="text" id="tf-outlined" class="mdc-text-field__input">
  <div class="mdc-notched-outline">
    <div class="mdc-notched-outline__leading"></div>
    <div class="mdc-notched-outline__notch">
      <label for="tf-outlined" class="mdc-floating-label">Your Name</label>
    </div>
    <div class="mdc-notched-outline__trailing"></div>
  </div>
</div>
```

**Comment by GusRuss89** [comment]
Thanks @williamernest, my issue was due to the fields being populated after the notch was already instantiated. Once I figured that out it was an easy fix.
