### ISSUE TITLE
MDC Menu selection group checkmark is vertically misaligned in IE

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#4184]
IE only, master / 0.42.0

See https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2018/12/13/21_10_43_629/spec/mdc-menu/classes/menu-selection-group.html.windows_ie_11.png.

Noticed during #4172 testing, but I tested against master before that PR and the same thing happens regardless.

Reproducible via demos/menu.html with `npm run dev`, or the menu-selection-group.html screenshot test page added in #4172.

**Comment by abhiomkar** [comment]
This issue is fixed in #4862
