### ISSUE TITLE
Travis CI truncates screenshot test logs

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#4190]
Travis CI truncates console logs in the UI when they grow beyond 4MB. I'm not sure if there's a line limit, but our jobs frequently surpass 10k lines. I've seen a few jobs get truncated recently (though I didn't think to bookmark them).

Not only does this prevent us from seeing the results of a screenshot test in Travis CI, it also makes the logs unwieldy to view.

A lot of the information being logged was originally added to make debugging easier, but now that screenshot tests are stable, we can probably stop logging things like:

* `GET: https://storage.googleapis.com/...` lines
    
    ![image](https://user-images.githubusercontent.com/409245/50113659-700d9900-01f7-11e9-9e15-cdee3b8223f5.png)

* List of screenshots being compared (potentially keep "added", "removed", and "skipped"?)

    ![image](https://user-images.githubusercontent.com/409245/50113601-49e7f900-01f7-11e9-8a7e-2d2a4944f559.png)

* GCP file uploads
    
    ![image](https://user-images.githubusercontent.com/409245/50113627-5d935f80-01f7-11e9-97cc-62ba9fb0905e.png)

**Comment by kfranqueiro** [comment]
I'd at least leave the _number_ of compared screenshots, esp. since we've seen things time out seemingly when the final comparison against the base branch is happening.

**Comment by abhiomkar** [comment]
Closing this as obsolete. We're considering to move screenshot infra internally.
