### ISSUE TITLE
Dialog jumps to top

### ISSUE THREAD

**Issue by HamburgerJungeJr** [material-components/material-components-web#4197]
### What MDC Web Version are you using?

> 0.42.0
CSS from npm packages, Js from 0.42.0-unpkg-file, see codepen
```
"@material/button": "^0.42.0",
 "@material/card": "^0.42.0",
"@material/checkbox": "^0.42.0",
"@material/dialog": "^0.42.0",
"@material/drawer": "^0.42.0",
"@material/elevation": "^0.41.0",
"@material/fab": "^0.42.0",
"@material/form-field": "^0.42.0",
"@material/layout-grid": "^0.41.0",
"@material/line-ripple": "^0.41.0",
"@material/list": "^0.42.0",
"@material/menu": "^0.42.0",
"@material/menu-surface": "^0.42.0",
"@material/radio": "^0.42.0",
"@material/ripple": "^0.42.0",
"@material/select": "^0.42.0",
"@material/textfield": "^0.42.0",
"@material/theme": "^0.41.0",
"@material/top-app-bar": "^0.42.0",
"@material/typography": "^0.42.0",
```

### What browser(s) is this bug affecting?

> Chrome/Firefox, so I think all browsers
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

### What OS are you using?

> Ubuntu 18.10

### What are the steps to reproduce the bug?
https://codepen.io/hamburgerjungejr/project/full/ZwWPLy

Click on the link at the bottom of the page to open a dialog. the view will jump to the top of the page.
It will stay at the top of the page if you click somewhear outside the dialog and jump bak to the bottom if you click close

### What is the expected behavior?

> The view should not jump to the top and stay at the current scrollposition

### What is the actual behavior?

> The view jumps to the top of the page.

### Any other information you believe would be useful?
Neither adding overflow:hidden or adding scroll-lock-class to body does not scroll to the top of the page.

**Comment by kfranqueiro** [comment]
The jump to top is unrelated to MDC, and is caused by your `a href="#"`, which will jump to the top of the document when the hash is first navigated to. You can avoid this either by using a `<button type="button">` instead, or by listening to click events on the `a` element and calling `event.preventDefault()`, e.g.:

```js
document.getElementById('show-attributions').addEventListener('click', function(event) {
  event.preventDefault();
});
```
