### ISSUE TITLE
SCSS build error: argument must be a number

### ISSUE THREAD

**Issue by th0rgall** [material-components/material-components-web#4207]
**MDC Web version:** 0.42.1
**Browser:** Chromium 61.0.3163.100 in Electron 2.0.16
**OS:** macOS 10.14.2

### Summary

I'm getting the following SCSS error when importing [vue-mdc-adapter](https://github.com/stasson/vue-mdc-adapter) styles in an [electron-vue](https://github.com/SimulatedGREG/electron-vue) project. 
```
    $value: rgba(mdc-theme-prop-value($color), $mdc-drawer-title-ink-opacity);
           ^
        Argument `$alpha` of `rgba($color, $alpha)` must be a number
        in ../node_modules/@material/drawer/_mixins.scss (line 65, column 11)
```
This might have something to do with vue-mdc-adapter or my setup, but the error traces back to material-components-web here.

The issue looks very similar to #1388, though I'm using Vue with instead of React and the erroring value/function is slightly different.

### Reproduction

1. Initialize the [electron-vue](https://github.com/SimulatedGREG/electron-vue) boilerplate:
```
  npm install -g vue-cli
  vue init simulatedgreg/electron-vue my-project
```
 Use default settings without linting and without testing.

2. Install vue-mdc-adapter as in the "Webpack/Rollup" section in their [Getting started guide](https://stasson.github.io/vue-mdc-adapter/#/docs/getting-started).
3. Follow the 'Create your own SASS Theme' section where `material-components-web` is pulled in as a dependency.
   * edit the `sass-loader` configurations in `/.electron-vue/webpack.renderer.config.js/` and  `/.electron-vue/webpack.web.config.js/ to conform to the Getting started guide with a slight change, because the node_modules are one more level up:
   ```
      {
        test: /\.scss$/,
        use: ['vue-style-loader', 'css-loader', {
          loader: 'sass-loader',
          options: {
            sourceMap: false,
            includePaths: [path.resolve(__dirname,'../node_modules')],
          }}]
      },
   ```
   - Import the vue-mdc-adapter (that uses the material-components-web) in a new theme.scss file. It doesn't matter where the scss file is imported then, either in `src/renderer/main.js` as in the Getting started or putting the style content in directly the <style> element at `/src/renderer/App.vue` (demo landing page) Both give the same error.

```
  ERROR in ./src/renderer/App.vue?vue&type=style&index=0&lang=scss& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/lib/loader.js??ref--0-2!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=style&index=0&lang=scss&)
  Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    $value: rgba(mdc-theme-prop-value($color), $mdc-drawer-title-ink-opacity);
           ^
        Argument `$alpha` of `rgba($color, $alpha)` must be a number
        in ../node_modules/@material/drawer/_mixins.scss (line 65, column 11)
   @ ./src/renderer/App.vue?vue&type=style&index=0&lang=scss& (./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/lib/loader.js??ref--0-2!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=style&index=0&lang=scss&) 4:14-288 14:3-18:5 15:22-296
   @ ./src/renderer/App.vue?vue&type=style&index=0&lang=scss&
   @ ./src/renderer/App.vue
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js
```

### I tried
The weird thing (as with #1388) is that it used to work for a few hours when I initially started the project.

I tried re-initializing the project completely. Did not work.

I tried the steps suggested by acdvorak in his comment on the similar issue https://github.com/material-components/material-components-web/issues/1388#issuecomment-334572109

Running `npm outdated` does not list any vue-mdc-adapter or outdated material-components-web parts.

A debug print just before the erroring line gives:
`DEBUG: $color = 'mdc-theme-text-emphasis(high)'`

### Additional info
package.json dependencies:
```
  "dependencies": {
    "material-components-web": "^0.42.1",
    "voc-api": "file:../api",
    "vue": "^2.5.16",
    "vue-electron": "^1.0.6",
    "vue-mdc-adapter": "^0.18.2"
  },
  "devDependencies": {
    "ajv": "^6.5.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^2.1.2",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.1.6",
    "css-loader": "^0.28.11",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^2.0.4",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "electron-builder": "^20.19.2",
    "mini-css-extract-plugin": "0.4.0",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack-cli": "^3.0.8",
    "webpack": "^4.15.1",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3"
  }
```

npm outdated:
```
Package                  Current   Wanted  Latest  Location
babel-loader               7.1.5    7.1.5   8.0.4  quick-adder
css-loader               0.28.11  0.28.11   2.0.2  quick-adder
electron                  2.0.16   2.0.16   4.0.0  quick-adder
electron-debug             1.5.0    1.5.0   2.0.0  quick-adder
file-loader               1.1.11   1.1.11   3.0.1  quick-adder
mini-css-extract-plugin    0.4.0    0.4.0   0.5.0  quick-adder
style-loader              0.21.0   0.21.0  0.23.1  quick-adder
```

**Comment by kfranqueiro** [comment]
It looks like the version of vue-mdc-adapter you're using depends on a significantly older version of MDC Web than the one you're depending on yourself, which could be causing this issue.

If you're unable to sync both versions of MDC Web, you may be able to rely on a Sass importer rather than `includePaths`, so that Sass will look up dependencies under respective nested `node_modules` directories rather than always checking the top-level. The [appendix](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#appendix-configuring-a-sass-importer-for-nested-node_modules) to our getting started guide describes how to configure this.

**Comment by th0rgall** [comment]
Replacing my own installed version of the web-mdc-components with the older 0.38.2 version used by the latest vue-mdc-adapter did indeed resolve the issue. Thank you!
