### ISSUE TITLE
Add 2px border radius to dialogs

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#421]
The spec isn't clear on whether or not dialogs should have 2px rounded corners (like most sheets of material do). The visual examples are conflicting:

![image](https://cloud.githubusercontent.com/assets/409615/24162846/a937ed5c-0e60-11e7-8618-9a19b0e7b095.png)
(2px rounded corners)

![image](https://cloud.githubusercontent.com/assets/409615/24162872/c36bb802-0e60-11e7-894d-7d17951e55dc.png)
(rounded corners on top but not on bottom)

![image](https://cloud.githubusercontent.com/assets/409615/24163002/33f45bc4-0e61-11e7-8fd1-b0b46912feec.png)
(no rounded corners)

We should request design guidance and make the change if the 2px rounded corner is expected.

**Comment by traviskaufman** [comment]
Good catch! Assigned to myself to follow up with the design team.

**Comment by traviskaufman** [comment]
Confirmed with design that there is indeed a `2px` corner radius. It's hard to make out in the mocks.

Marking as `help wanted`. It should be a pretty simple change:

- [ ] Add `border-radius: 2px;` to the [.mdc-dialog__surface rule](https://github.com/material-components/material-components-web/blob/master/packages/mdc-dialog/mdc-dialog.scss#L38)

**Comment by vivekmarakana** [comment]
Hi @traviskaufman, I'm already working on #413 which include changes in MDC Web Dialog and have an open PR. Can I make commit in that branch only with reference to this issue or should I create a separate PR?

**Comment by amsheehan** [comment]
@vivekmarakana Yes that's fine. I reviewed the PR this morning and the changes LGTM. Thanks!
