### ISSUE TITLE
Is there any way to size the checkbox?

### ISSUE THREAD

**Issue by tychenjiajun** [material-components/material-components-web#4210]
## Feature Requests

[Codepen](https://codepen.io/chankcccc/pen/YdQWXm)

I tried sizing checkbox using height, width and padding in CSS but it doesn't work as expected.

And I think checkbox and icon buttons are similar things, they should default have the same size and same colour. Or just replace the checkbox with icon toggle button.

**Comment by williamernest** [comment]
Currently, we don't support resizing the checkbox by setting width/height/padding. Since the touch target of input components is at least 48x48, it was never considered in the original design. We do have plans to explore some standardized ways of allowing more dense layouts.

**Comment by kfranqueiro** [comment]
This is one of a class of issues (such as #2731) that we want to address with designers. No definite ETA as the general topic hasn't quite been kicked off yet.

**Comment by abhiomkar** [comment]
This is fixed in #5016
