### ISSUE TITLE
Import statements violate closure compiler convention

### ISSUE THREAD

**Issue by BrotherJing** [material-components/material-components-web#4211]
I notice from [the docs](https://github.com/material-components/material-components-web/blob/master/docs/closure-compiler.md) that `material-components-web` supports closure compiler's advanced compilation, and listed some conventions there, including _not to use re-exported modules_.

However I found there are many places this convention is not followed, for example, in `mdc-select/foundation.js`:
```javascript
import {MDCFoundation} from '@material/base/index';
//...
class MDCSelectFoundation extends MDCFoundation {
//...
}
```
where `MDCFoundation` is re-exported. In this case, closure compiler will pass, but when you open the browser, nothing is displayed and console says:
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at $$$jscomp$inherits$$$ ( :58)
    at foundation.js:36
```
which points to the code above.

According to the convention guidelines, it should be:
```javascript
import MDCFoundation from '@material/base/foundation';
```

Is supporting closure compiler still a goal for MDC? It will be very helpful if you can fix these import statements since other parts play well with closure compiler. :smiley:

**Comment by abhiomkar** [comment]
Thanks for reporting this issue!

We might need to change import target in few places:

```
mdc-dialog/foundation.js
mdc-grid-list/foundation.js
mdc-linear-progress/foundation.js
mdc-select/foundation.js
mdc-snackbar/foundation.js
```

from `import {MDCFoundation} from '@material/base/index';` to `import {MDCFoundation} from '@material/base/foundation';`.

As mentioned in above documentation page, Yes, it is important for MDC Web to follow closure annotations.

**Comment by abhiomkar** [comment]
Can you share reproducible steps for JavaScript error message that you mentioned?

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
```
