### ISSUE TITLE
Include copyright notice only once in final build file

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#4220]
Currently the `@license` annotation is repeated in compiled & minified file [material-components-web.min.js](https://unpkg.com/material-components-web@0.42.1/dist/material-components-web.min.js). The copyright notice should only be included once per file in minified and un-minified file.

**Comment by cintaccs** [comment]
in the 1.1.1 release it is is around 3000+ lines of repeated strings. 
464KB in release version. 
without the repeated notice the release would be 295 KB
that is probably one of the biggest minification improvements you can get with 1 fix! :-)

**Comment by cintaccs** [comment]
#4580
