### ISSUE TITLE
Event names are incompatible with Angular templates

### ISSUE THREAD

**Issue by DRiFTy17** [material-components/material-components-web#4221]
I have run across a conflict with the event binding syntax in Angular. It appears to be an issue with the colon in the event names. I know this is more of a concern of Angular, but aside from listening and re-emitting the events I figured I would bring it up to you.

> FYI, I am wrapping the MDC components within custom elements, and allowing the events to propagate out so that developers can easily use MDC components as custom elements while still being able to refer to your documentation for usage.

Here is the error from Angular when using the `(MDCSlider:change)="onSliderChange($event)"` syntax:
```
ERROR Error: Unsupported event target null for event change
    at DomEventsPlugin.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.EventManagerPlugin.addGlobalEventListener (platform-browser.js:876)
    at EventManager.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.EventManager.addGlobalEventListener (platform-browser.js:840)
    at EmulatedEncapsulationDomRenderer2.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.DefaultDomRenderer2.listen (platform-browser.js:1132)
    at DebugRenderer2.push../node_modules/@angular/core/fesm5/core.js.DebugRenderer2.listen (core.js:11514)
    at listenToElementOutputs (core.js:8149)
    at createViewNodes (core.js:10366)
    at callViewAction (core.js:10715)
    at execComponentViewsAction (core.js:10634)
    at createViewNodes (core.js:10427)
    at createRootView (core.js:10313)
```

I have run across this issue when emitting `CustomEvent`s from my own custom elements a while back, and decided to go with a lowercase kebab naming style as it makes the component easier to use for other developers across frameworks.

I found this older issue in regards to Aurelia, and although it's a different issue, it's still due to the naming convention: https://github.com/material-components/material-components-web/issues/837

Have there been any thoughts on adopting a different format?

I use something like this for example "mdc-slider-change" ([unique prefix]-[component name]-[event name]) instead of "MDCSlider:change" ([class name]:[event name]) and it has worked out well. This way it's still unique while being clear where the event originated from. Although I could see how the event name could get mixed up with the component name at times... Just a suggestion.

As we continue to wrap up these components within custom elements, we are going to run into this quite a bit and wanted to avoid re-emitting the events with different names if possible, while still supporting the Angular event binding syntax.

**Comment by kfranqueiro** [comment]
I checked with the Angular team and this is indeed a limitation of Angular's templates (specifically the colon; they have a couple of specific event constructs of their own that use it).

You can still use `addEventListener` to listen to MDC's events (the Angular team specifically suggested this as an alternative), but you will need to remember to remove the event listeners yourself.

I'm also inquiring with them as to whether this might be something they're interested in supporting within templates in the future, but no word on that yet.

**Comment by DRiFTy17** [comment]
Great, thanks for information! Hopefully they can support this convention in the future.

I totally understand wanting to avoid renaming the events. I will continue to use `addEventListener`, or re-emit the events with different names since these are all wrapped up and interfaced through my own custom elements.

**Comment by acdvorak** [comment]
Closing this issue because we're not able to rename our events. Feel free to reopen if necessary. Thanks!
