### ISSUE TITLE
Flaky text field screenshot test in Edge

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#4229]
See https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/01/04/23_22_57_670/report/report.html for example. I encountered this twice today.

We might need to redact some more text?

**Comment by acdvorak** [comment]
More examples of the same flake:

* [2019-01-07 at 18:37:05.270 UTC](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/01/07/18_37_05_270/report/report.html)
* [2019-01-07 at 20:04:07.447 UTC](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/01/07/20_04_07_447/report/report.html)
* [2019-01-08 at 20:30:04.059 UTC](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/01/08/20_30_04_059/report/report.html)
* [2019-01-08 at 22:01:15.569 UTC](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/01/08/22_01_15_569/report/report.html)

It's flaked at least 3 times on PR #4232.

We need to redact the labels in `mdc-textfield/issues/4170.html` for Edge.
