### ISSUE TITLE
Integrating MDC Web into Frameworks Has Bad Example

### ISSUE THREAD

**Issue by DieLaughing** [material-components/material-components-web#4230]
> "For an example of this approach, check out [this plunk](https://plnkr.co/edit/b4v160c186ErrPG5vNza?p=preview) which shows how to wrap our text field within an angular v1 component, as well as our button (with a ripple) within an attribute directive."

That example doesn't show an input field at all.

**Comment by nemethmik** [comment]
You might give a try to this Google Codelab tutorial [MDC 112](https://codelabs.developers.google.com/codelabs/mdc-112-web/)

**Comment by DieLaughing** [comment]
Nah, I'm good. I was just trying to alert a Google "Genius" that their stuff doesn't work.

**Comment by DieLaughing** [comment]
It's not important. Details aren't important. Timely responses aren't important. Examples aren't important. MDC isn't important. It's fine. It's all fine.
