### ISSUE TITLE
align-items unsupported value "start" (should be "flex-start")

### ISSUE THREAD

**Issue by VlkaFenryka** [material-components/material-components-web#4233]
### What MDC Web Version are you using?

> 0.43

### What OS are you using?

> Win 10 1809

### Location of the mentioned bugs

https://github.com/material-components/material-components-web/blob/master/packages/mdc-toolbar/mdc-toolbar.scss#L66
https://github.com/material-components/material-components-web/blob/master/packages/mdc-toolbar/_mixins.scss#L67

### What is the expected behavior?

- https://www.w3.org/TR/css-flexbox-1/#align-items-property

> flex-start

**Comment by abhiomkar** [comment]
Thanks for reporting this issue.

`start` seems to be a valid CSS value of `align-items` as per [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items).

> **start**
> The items are packed flush to each other toward the start edge of the alignment container in the appropriate axis.

Please note that `MDCToolbar` is deprecated and no longer supported. Please see [MDC Top App Bar](https://github.com/material-components/material-components-web/tree/master/packages/mdc-top-app-bar) that replaces MDCToolbar.

**Comment by acdvorak** [comment]
I think @VlkaFenryka is referring to the fact that `start` is not supported in IE or Edge.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#Browser_compatibility):

![Screenshot of browser compatibility table on MDN](https://user-images.githubusercontent.com/409245/50864275-5bd03e00-1356-11e9-97eb-a5955dd85d93.png)

That said, @abhiomkar is right that `MDCToolbar` is no longer supported, so unfortunately we won't be able to fix this issue. I would recommend switching to [Top App Bar](https://github.com/material-components/material-components-web/tree/master/packages/mdc-top-app-bar), which is actively maintained and does not have this problem.

The good news is we're not using `start` or `end` anywhere else.

**Comment by VlkaFenryka** [comment]
@abhiomkar 
As @acdvorak said: `start` has a very limited support (Firefox only) and therefore all the "prefixed" `flex-` values are the better alternative for cross browser development.

Thank you for pointing out that `MDCToolbar` is deprecated and already replaced.

**Comment by acdvorak** [comment]
Closing this issue because `MDCToolbar` is deprecated and no longer actively maintained or supported. Thanks!
