### ISSUE TITLE
Documentation of snackbar not updated

### ISSUE THREAD

**Issue by Alan-Liang** [material-components/material-components-web#4234]
version: 0.43.0
browsers, OS: All
tl;dr: Docs of snackbar is not updated while the package is, causing inconsistency.

The package has been updated to 0.43.0 (so does `latest`), but the [documentation on material.io](https://material.io/components/web/catalog/snackbars/) hasn't been updated yet, causing invalid snackbar DOM structure to not only existing code but also new code pasted from the docs.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

Unfortunately it takes a few days for the documentation on material.io to get updated after a release.

In the mean time, you can [read the docs directly on GitHub](https://github.com/material-components/material-components-web/tree/v0.43.0/packages/mdc-snackbar).

Sorry for the inconvenience!

**Comment by acdvorak** [comment]
https://material.io/develop/web/components/snackbars/ has been updated for v0.43.0. Thanks for your patience and sorry for the inconvenience!
