### ISSUE TITLE
MDCCard: text and background colours

### ISSUE THREAD

**Issue by monstasat** [material-components/material-components-web#4238]
According to the `mdc-card` [stylesheet](https://github.com/material-components/material-components-web/blob/d4f77e1a25bc2f78cf575ad7c69bd55ee3d26941/packages/mdc-card/mdc-card.scss#L33), the fill colour of a card is `surface`. But the colour for icons is [defined below](https://github.com/material-components/material-components-web/blob/d4f77e1a25bc2f78cf575ad7c69bd55ee3d26941/packages/mdc-card/mdc-card.scss#L133) as `text-icon-on-background`. As surface and background colours can differ, it seems like a bug.

Moreover, why there are no predefined variables like `text-<TEXT-STYLE>-on-surface`?
There are some for `background`, `light`, `dark`, but no for `surface`. It seems that text on surface is quite common. Is it missing on purpose or by accident?

### What MDC Web Version are you using?

0.43.0

**Comment by monstasat** [comment]
There is also a similar colour mismatch in MDCMenu component.
It uses MDCMenuSurface, which background colour [is defined](https://github.com/material-components/material-components-web/blob/d4f77e1a25bc2f78cf575ad7c69bd55ee3d26941/packages/mdc-menu-surface/mdc-menu-surface.scss#L33) as `surface` variable.
But in MDCMenu stylesheet the colour for icon and graphic elements [is defined](https://github.com/material-components/material-components-web/blob/d4f77e1a25bc2f78cf575ad7c69bd55ee3d26941/packages/mdc-menu/mdc-menu.scss#L32) as `on-background`.
IMO there there may be problems when `background` and `surface` colours are different.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

This certainly seems problematic. Adding it to our backlog.

**Comment by kfranqueiro** [comment]
I asked our designer and he confirmed that the icon buttons should use the on-surface color. This was probably an oversight when `surface` and `on-surface` were first added.

The `surface` and `on-*` variables were added more recently than the `text-<TEXT_STYLE>-*` variables, and in combination with `$mdc-theme-text-emphasis`, are intended to eventually replace them. However, additional color design work is still forthcoming, so we're still in an intermediate state at the moment.
