### ISSUE TITLE
Initial dialog focus seems to trigger side-effects on underlying page

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#424]
### What MDC-Web Version are you using?

0.7.0

### What browser(s) is this bug affecting?

Chrome Version 56.0.2924.87 (64-bit)

### What OS are you using?

macOS Sierra Version 10.12.3

### What are the steps to reproduce the bug?

1. Navigate to http://material-components-web.appspot.com/dialog.html
1. Click somewhere blank on the page to ensure that focusing will be within the context of the document
1. Press the `tab` key twice so that the "Show Scrolling Dialog" button is focused
1. Press the spacebar to display the dialog
1. Press the `tab` key to focus on the "Decline" button

### What is the expected behavior?

The decline button should be the only element that gains focus, or changes at all

### What is the actual behavior?

The "Show Dialog" button also appears to highlight as if it were being focused.

<img width="1228" alt="screen shot 2017-03-22 at 13 14 55" src="https://cloud.githubusercontent.com/assets/1185269/24211145/92bcf1a2-0f01-11e7-996f-bf047428f4a0.png">

### Any other information you believe would be useful?

When you hit the `esc` key to cancel the dialog, both buttons appear to have gained focus:

<img width="667" alt="screen shot 2017-03-22 at 13 15 46" src="https://cloud.githubusercontent.com/assets/1185269/24211191/aecfcd1a-0f01-11e7-87b3-891766c5b494.png">

**Comment by vivekmarakana** [comment]
@traviskaufman There has been too many issues related to Web Dialog. Should we consider refactoring the entire dialog module?
