### ISSUE TITLE
 mdc-text-field--textarea  with variant Full Width, unexpected behaviour.

### ISSUE THREAD

**Issue by rubenmendoza** [material-components/material-components-web#4246]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs
![image](https://user-images.githubusercontent.com/3853885/51096186-e0b3cf80-180e-11e9-84fa-fd15d7aeec1e.png)

When clicking on the text area, it resizes. Also, the label looks bad.
![image](https://user-images.githubusercontent.com/3853885/51096230-21abe400-180f-11e9-96c5-27aa9e475368.png)

Please check the bug in the official page: https://material-components.github.io/material-components-web-catalog/#/component/text-field.
No codepen is needed.

### What MDC Web Version are you using?

> 0.43.0

### What browser(s) is this bug affecting?

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

### What OS are you using?

> Windows 10

### What is the expected behavior?

> Textarea keeps its original width.

### Any other information you believe would be useful?

The following styles are added to the component, possibly via javascript:
width: auto;
overflow: hidden;

**Comment by CyborgSemon** [comment]
Weird that doesn't seem to happen to me on any browser or OS

**Comment by acdvorak** [comment]
Thanks for filing this issue!

I'm not able to reproduce the problem. If you still believe there's a bug, please feel free to reopen.

Thanks! 😀

**Comment by acdvorak** [comment]
@eschava I'm still not able to repro. Did you try a hard-refresh as @CyborgSemon suggested?

If you're still seeing it after clearing your cache and reloading the page, please upload/link a
[video screen capture](https://www.google.com/search?q=windows+10+video+screen+capture) to this issue and include the **name of the browser(s)** you're seeing it in
(e.g., "Chrome", "Firefox", "Edge"). Unfortunately, [User Agent strings are not reliable indicators](https://stackoverflow.com/a/31279980/467582).

Thanks! 😀

**Comment by eschava** [comment]
@acdvorak Thanks for your attention!
Finally, I've found the reason of the issue: it's a "Grammarly for Chrome" plugin (https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen)
It adds custom styles to the text fields

Sorry for bothering you :)

**Comment by acdvorak** [comment]
I had a sneaking suspicion it might be a Chrome Extension. Glad to hear you figured it out!
