### ISSUE TITLE
MDCDrawer can't find the scrim when initialising the element inside the Shadow DOM

### ISSUE THREAD

**Issue by vedtam** [material-components/material-components-web#4254]
Hi,

While trying to implement the modal version of the MDCDrawer, I hit the following exception:

![screen shot 2019-01-16 at 17 29 32](https://user-images.githubusercontent.com/4981592/51281751-034f0f80-19ec-11e9-8d2b-ab1186424ebe.png)

I've created a demonstration [here](https://indigo-hunter.glitch.me), you can find the source [here](https://glitch.com/edit/#!/indigo-hunter?path=src/main-app.js:80:83).

Any idea?
Thanks.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

We can _probably_ fix this in MDC by changing `parentElement` to `parentNode` (and adding a unit test that moves the DOM into a document fragment).

Until then, you can work around this problem by wrapping the
`<aside class="mdc-drawer mdc-drawer--modal">` element in an extra `<div>`:

- [Demo](https://fertile-tracker.glitch.me/#)
- [Code](https://glitch.com/edit/#!/fertile-tracker?path=src/main-app.js:1:0)

**Comment by vedtam** [comment]
Thanks for the workaround @acdvorak! And thanks for the nice explanation, gonna follow the subject to see what will be the final solution.
