### ISSUE TITLE
MDCDrawer: color variables

### ISSUE THREAD

**Issue by monstasat** [material-components/material-components-web#4256]
MDC Web Version: 0.43.0

Is it OK that colors in MDCDrawer are [defined](https://github.com/material-components/material-components-web/blob/9beee27cf952cb39d529b95427cd0ac91446c887/packages/mdc-drawer/_variables.scss#L26) as constant values via `mdc-theme-prop-value`? IMO this breaks the idea of theme change via css variables redefinition. E.g., if the `mdc-theme-surface` css variable is changed to `black`, side-sheet background color will still be `#fff` (default value).

In the opposite, MDCRadio (other randomly selected MDC widget) colors are [defined](https://github.com/material-components/material-components-web/blob/cffe8951ff8827b6107af2b4d0582110a95ec9a5/packages/mdc-radio/_variables.scss#L30) as SASS variables, hence changing css theme variables will cause MDCRadio color change (as intended).

**Comment by acdvorak** [comment]
Thanks for filing this issue!

This was also brought up in #3066. It's a broader problem that we need to figure out for all of our components.

**Comment by acdvorak** [comment]
Superseded by #4431.
