### ISSUE TITLE
Opening Dialog Adds aria-hidden to Entire Page

### ISSUE THREAD

**Issue by nbtorcol** [material-components/material-components-web#426]
This is applicable for all operating system, browser, and screen reader combinations.
When a dialog is opened, the other elements on the page are supposed to have aria-hidden. However, in the mdc dialog, the document body has aria-hidden applied to it, which also hides the dialog itself since the dialog is a child of the document body.

**Comment by amsheehan** [comment]
@nbtorcol thank you for filing this issue. Though we do set `aria-hidden="true"` on the body, we also set `aria-hidden="false"` on the dialog. Is this sufficient for screen readers, or can you not nest the `aria-hidden` attribute?

**Comment by nbtorcol** [comment]
The aria-hidden attribute is inherited from any parent elements, so putting
aria-hidden on an element hides all of its children, too.

**Comment by amsheehan** [comment]
@nbtorcol Even if aria-hidden is set to false on a child?

**Comment by nbtorcol** [comment]
Yes. Please consider testing the widgets with a screen reader; most
operating systems come with one. If you have already done this and found
results that conflict with what I have told you, then I need to know what
operating system, browser, and screen reader you are using, including all
of the versions.

**Comment by amsheehan** [comment]
Thank you for your help with this. I just bounced an idea or two off of @traviskaufman and we may have a solve, but can you point to any existing implementation of a modal dialog that you feel is implemented to these specifications?

**Comment by Garbee** [comment]
The bit on inheritance is correct here, check this out...

1. Open `chrome://accessibility/`
1. New tab and put `data:text/html,<!doctype html><div aria-hidden="false"><span aria-hidden="false">Hello</span></div>` into the Omnibar.
1. Go back to a11y tab, refresh and see the tab you just opened. Now open the a11y tree and it should show the tree with the text.
1. Set `aria-hidden=true` on the div in the omnibar and press `enter` to have the page reload with the new markup.
1. Return to a11y tab and refresh the a11y tree.

You'll notice when toggling the parent div's `aria-hidden` attribute, it still hides the child's content even though it has a shown attribute.



<details>
<summary>Output with nothing hidden</summary>

```
[document web] enabled focusable focused id=25<newline>
++[section] enabled id=28<newline>
++++[text] name='Hello' enabled id=30<newline>
```

</details>

<details>
<summary>Output with hidden on div</summary>

```
[document web] enabled focusable focused id=31<newline>
```

</details>
