### ISSUE TITLE
Is it a bug on mdc-text-field when input is empty?

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#4280]
browser: safari 12.0.2 on macOS 10.14.2

take a look, thanks
---
![textfield](https://user-images.githubusercontent.com/39903550/51522287-fb67f300-1e63-11e9-9b64-27bf3c1ac238.png)

**Comment by moog16** [comment]
Closing since we do not support dense and leading-icon & dense styles are being refactored.
