### ISSUE TITLE
[Bug] MDCSelect highlight isn't removed when it is deselected (Except for the enhanced version)

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4289]
## Bugs

The MDCSelect that doesn't have the enhanced menu using MDCMenu stays highlighted when it is deselected. It then takes a second click for the highlight to go away.
> Gif is from the https://material-components.github.io/material-components-web-catalog/#/component/select page

![select](https://user-images.githubusercontent.com/26075792/51673089-06707e00-2032-11e9-9ad1-a1bdfd34bb82.gif)

### What MDC Web Version are you using?

> 0.43.1

### What browser(s) is this bug affecting?

> Tested on latest version of Chrome
> Haven't tried other browsers

### What OS are you using?

> MacOS 10.14.2

### What are the steps to reproduce the bug?

> [CodePen](https://codepen.io/anon/pen/vbOMvo)

### What is the expected behavior?

> All the selects stop being highlighted when they are deselected

### What is the actual behavior?

> The select that doesn't have the enhancement should remove the highlight when it is deselected the first time and not require 2 clicks.

Edit: The same behavior occurs even when an item is selected:
![bug2](https://user-images.githubusercontent.com/26075792/51674367-4c7b1100-2035-11e9-8ba6-4f19b5f46b20.gif)

**Comment by moog16** [comment]
This is happening because the native select behavior dictates what element gains focus on click. Edge loses focus, while Chrome/FF does not (as you have seen).  This is not something we can control/fix ourselves, since this is not consistent on every browser. Closing issue since we can't fix issue.
