### ISSUE TITLE
Mdc autoInit for MDCSwitch? It seems that this is missing?

### ISSUE THREAD

**Issue by mep253** [material-components/material-components-web#4290]
If i try to auto init an mdc switch i get the following error:
(mdc-auto-init) Could not find constructor in registry for MDCSwitch

My code snippet:
```

                    <div class="mdc-switch mdc-switch--checked"  data-mdc-auto-init="MDCSwitch">
                        <div class="mdc-switch__track"></div>
                        <div class="mdc-switch__thumb-underlay">
                          <div class="mdc-switch__thumb">
                            <input type="checkbox" id="another-basic-switch" class="mdc-switch__native-control" role="switch" checked>
                          </div>
                        </div>
                    </div>
                    <label for="another-basic-switch">off/on</label>
          
```

**Comment by kfranqueiro** [comment]
You might be running into this due to using individual component packages rather than the all-in-one material-components-web package, which is where the auto-init registrations occur. (This was the most expedient option without requiring every package to depend upon auto-init).

https://github.com/material-components/material-components-web/blob/v0.43.1/packages/material-components-web/index.js#L57

If you're using individual packages, you'll want to include the appropriate `register` calls to use with auto-init.

**Comment by mep253** [comment]
Hi @kfranqueiro ,
i actually use exactly the all-in-one package ...
```
import 'jquery';
import 'bootstrap';
import * as mdc from 'material-components-web';

mdc.autoInit();
```
and i get the error ...

**Comment by moog16** [comment]
are you able to reproduce in a glitch (similar to codepen and stackblitz)? Here is a link to get you started [glitch](https://glitch.com/edit/#!/material-starter-kit-top).

**Comment by abhiomkar** [comment]
Please refer this example on [glitch](https://glitch.com/edit/#!/mica-feeling) that demos initiating MDC Switch component using auto init feature.

Since there was no response from last few days, closing this issue.

**Comment by Oj18** [comment]
It seems to work with auto init, but it doesn't stay initially checked? If I get rid off the auto init it stays initially checked. Putting this here as it's related. HTML:
```html
        <div class="mdc-switch mdc-switch--checked" data-mdc-auto-init="MDCSwitch">
          <div class="mdc-switch__track"></div>
          <div class="mdc-switch__thumb-underlay">
            <div class="mdc-switch__thumb">
              <input name="overlay" type="checkbox" id="overlay-switch" class="mdc-switch__native-control" role="switch" selected>
            </div>
          </div>
        </div>
        <label for="overlay-switch">Overlay</label>
```
