### ISSUE TITLE
Is it possible to add new feature "Popover"?

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#4302]
do you have any plan to add popover ui?
when mouse over or click to appear it

![popover](https://user-images.githubusercontent.com/39903550/51784336-0c757480-2182-11e9-9a75-1d14b6d1fb5c.png)

**Comment by CyborgSemon** [comment]
This isn't really a material "Popover" component that is on the [Material Design guidelines website](https://material.io).
I would say that the closest thing to a popover would be a [tool tip](https://material.io/design/components/tooltips.html), which is in the material design guidelines, but currently there is no MDC version of it.
There is a request for the tool tip to be made though [here](https://github.com/material-components/material-components-web/issues/24), so you can follow that.
But as for the popover, I think it would have to be something that you would have to come up with.

**Comment by iPHiLGG** [comment]
On the case study about Fortnightly, there's that kind of popover in the components section. Apparently it's using a dialog and I guess the scrim is something you could disable. I don't know if you can use the one on MDC Web to do a popover.
![image](https://user-images.githubusercontent.com/7622264/51785698-c3dd9d00-2128-11e9-80bc-b5da43c79b2f.png)
Reference: https://material.io/design/material-studies/fortnightly.html#components

**Comment by diuming** [comment]
@iPHiLGG 
Thanks for helping me.
Can I control the dialog location?

**Comment by diuming** [comment]
@CyborgSemon 
thanks for your advice.

**Comment by iPHiLGG** [comment]
@diuming With the current one, I don't think it's possible. It's always centered and the position is fixed, but I believe the option to have a relative position should be considered for that use case.

I think your best choice for now would be to make one yourself with a simple div with the [elevation class](https://material-components.github.io/material-components-web-catalog/#/component/elevation) that you display on hover or toggle on click.

**Comment by moog16** [comment]
@diuming sorry, but we don't have this component on the roadmap. This is very similar behavior to the [menu-surface](https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu-surface), so you can try using that.
