### ISSUE TITLE
Dialog Closing Animations not running 

### ISSUE THREAD

**Issue by tranrate** [material-components/material-components-web#433]
## What MDC-Web Version are you using?

0.7.0
## What browser(s) is this bug affecting?

Chrome Version 57.0.2987.110 (32-bit)
Firefox 52.0.1 (64-bit)
## What OS are you using?

Windows 10
## What are the steps to reproduce the bug?

On your Demo site open a Dialog and then Close it.
## What is the expected behavior?

The Dialog should run its "Closing" Animation.
## What is the actual behavior?

The Close method "hides" the Dialog without waiting for the animation to run.

## Any other information you believe would be useful?

The foundation needs to wait for a TransitionEnd event before hiding the the Dialog and closing everything down. At the moment the adapter doesn't allow for a TransitionEnd event.

**Comment by amsheehan** [comment]
Good catch! LMK if this is something you have time to submit a PR for we would greatly appreciate it.

**Comment by tranrate** [comment]
@amsheehan Yes I am happy to submit a PR in the next few days. Is it worth waiting for the outcome of the discussion of #434 as this would require modifications to the same code, and this bug is not stopping anyone using the dialog?
