### ISSUE TITLE
MDCDialog cuts off right edge of some elements only in Chrome

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4330]
## Bugs

When some elements are in a dialog, depending on the width of the browser window, the right edge seems to get cut off. This only seems to happen in Chrome
### What MDC Web Version are you using?

> 0.43.1

### What browser(s) is this bug affecting?

> Google Chrome Version 71.0.3578.98 **AND** 72.0.3626.81
>
> **Only seems to effect Chrome. I have tested in Safari and Firefox on MacOS and the issue does not occur**

### What OS are you using?

> MacOS 10.14.2

### What are the steps to reproduce the bug?

> For example, Have a chipset with chips inside a dialog
> Then resize the browser window 
> Observe the right edge of the chips get cut off randomly
> [CodePen](https://codepen.io/anon/pen/bzqwqB)
>
> Also note, the left notched outline input field in the dialog is where the edge getting cut off is most noticeable.

### What is the expected behavior?

> The right edge doesn't get cut off in

### What is the actual behavior?

> The right edge of some elements gets cut off

### Any other information you believe would be useful?

An example of what I'm seeing.

![bug](https://user-images.githubusercontent.com/26075792/52096386-8b0f5d80-262b-11e9-90f4-b0a46a9607e2.gif)

You can see the right side of each chip get slightly cut off with each pixel of the browser window resizing while the left side of each chip stays fine
As stated earlier, the notched outlined text field is where its most noticeable

### Edit

It appears that with the notched outline text field, if you hover your mouse over it, the cut out disappears and then resizing the window doesn't cut out the right side any more. The chip is unaffected by this however.

![bug2](https://user-images.githubusercontent.com/26075792/52100575-e8f87100-263c-11e9-8eaa-6b8d0dbc7485.gif)

**Comment by abhiomkar** [comment]
Thanks for providing clear repro steps @CyborgSemon!

I'm able to repro chip edge being cut off but I couldn't repro notched outline issue.

Unsetting `will-change` property on `.mdc-chip` element seems to rectify the issue. Still need more investigation on this.

Please see updated [codepen](https://codepen.io/abhiomkar/pen/rPzBdq) example here.

**Comment by abhiomkar** [comment]
As discussed offline with the team, `will-change` property seems to improve rendering performance for pages that renders many components. Since we've found a workaround (ie., unsetting `will-change`) which can be done at consumer level, I'm going to close this issue.

**Comment by CyborgSemon** [comment]
Do you think that maybe this is an issue with Chrome?
Because now that `will-change` has been unset in your CodePen, there is this weird jumping movements that the chips do (as well as the text field label and outline) when the page is resized. However this doesn't seem to happen in Firefox or Safari. And neither do the random cut offs from the chips and text field.

Chrome:
![bug3](https://user-images.githubusercontent.com/26075792/52242454-9c15e280-293b-11e9-87b1-64335e7bb5e9.gif)

Firefox:
![firefox](https://user-images.githubusercontent.com/26075792/52242528-cf587180-293b-11e9-872e-16e374995811.gif)
