### ISSUE TITLE
MDCChipSet documentation change for removeChild (see comments)

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4339]
I cant seem to get the `removeChild()` function to work to remove a chip by clicking the close button on the chip.
I only seem to get this error
<img width="477" alt="screen shot 2019-02-02 at 1 11 06 am" src="https://user-images.githubusercontent.com/26075792/52122307-719bff00-2687-11e9-825c-5e3bac2a7711.png">

[CodePen](https://codepen.io/anon/pen/GzWBdz)
Either I'm missing something really obvious, or the [documentation](https://material.io/develop/web/components/chips/#removing-chips-from-the-dom) is wrong with something

**Comment by rikvdk** [comment]
The [`removeChild`](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild) method expects an argument of type `Node` (see error message). You are currently calling it with `event.id` which is `undefined`.

The documentation says that you should use the following:
```javascript
chips.listen('MDCChip:removal', function(event) {
  chipsEl.removeChild(event.root);
});
```

This doesn't work for the same reason: `event.root` is `undefined`. Looking at the [`Events`](https://material.io/develop/web/components/chips/#events) paragraph we see that we need to use `event.detail.root`:

```javascript
chips.listen('MDCChip:removal', function(event) {
  chipsEl.removeChild(event.detail.root);
});
```

**Comment by CyborgSemon** [comment]
Ahhhhhhh thank you so much @rikvdk!
I think that the [documentation](https://material.io/develop/web/components/chips/#removing-chips-from-the-dom) then needs to be changed to say `event.detail.root` instead of `event.root`
