### ISSUE TITLE
MDC Switch not enough padding

### ISSUE THREAD

**Issue by Richienb** [material-components/material-components-web#4343]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Follow the template below **and include a codepen** to ensure the quickest and most accurate response to your issue.

### What MDC Web Version are you using?

> Please be specific, e.g. 0.43.1

### What browser(s) is this bug affecting?

> All, but mine is Chrome 72.0.3626.81

### What OS are you using?

> Windows 10.0.17134

### What are the steps to reproduce the bug?

> Go to [this codepen](https://codepen.io/Richienb/full/OdggoB).
> Observe.

### What is the expected behavior?

> MDC Switches should have `8px` of `right-padding` for the main element.

### What is the actual behavior?

> The padding is `4px` instead, making the switch look squashed.

**Comment by abhiomkar** [comment]
Also, Please refer [@material/form-field](https://github.com/material-components/material-components-web/tree/master/packages/mdc-form-field) that auto aligns checkboxes with its label and makes it RTL-aware. It also activates a ripple effect upon interacting with the label.
