### ISSUE TITLE
[Feature request] MDCFormField (MDCCheckbox, MDCRadio) support for vertical alignment in one form field div

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4344]
[Feature request]
It would be great to have vertical alignment supported in a single form field div.
Currently the only way to achieve vertical alignment is to have a separate form field div for each element, like this:
```html
<div class="mdc-form-field">
	<div class="mdc-checkbox">
		<!-- Checkbox content -->
	</div>
</div>

<div class="mdc-form-field">
	<div class="mdc-checkbox">
		<!-- Checkbox content -->
	</div>
</div>
<!-- etc... -->
```

It would be great if an extra CSS class was added to make the elements be vertical. So like `mdc-form-field--vertical` for example.
Proposed change:
```html
<div class="mdc-form-field mdc-form-field--vertical">
	<div class="mdc-checkbox">
		<!-- Checkbox content -->
	</div>

	<div class="mdc-checkbox">
		<!-- Checkbox content -->
	</div>
</div>

```

[CodePen](https://codepen.io/anon/pen/XOgEVm) example of change.
[Guidelines](https://material.io/design/components/selection-controls.html#checkboxes) link to show vertical alignment of checkboxes.

**Comment by abhiomkar** [comment]
This seems like something that has to be done at consumer level. Form field is not opinionated about the block width of the field.

Also, `mdc-form-field` is wrapped only to single form field element. It doesn't support multiple form fields (ie., checkbox) in a single form field block.

**Comment by CyborgSemon** [comment]
Don't you think it should though?
It just seems unnecessarily complex, where as a single class addition could simplify the code a lot more

**Comment by kfranqueiro** [comment]
MDC Form Field is intentionally designed as an atomic component to manage one label together with one input element. It manages not only styling, but also JS logic to trigger ripple on the associated input element when the label is interacted with. Managing multiple inputs and labels together in one form field would significantly increase complexity and would kind of defeat the point of the clean abstraction that currently exists.

**Comment by CyborgSemon** [comment]
Ahhhh ok. Thanks for the clarification :)
