### ISSUE TITLE
Request: Improve source code examples (Drawer)

### ISSUE THREAD

**Issue by PunchyRascal** [material-components/material-components-web#4345]
I am having a hard time understanding what is the exact HTML and CSS needed for the drawer and app bar to work together. When I download the official CSS and try to combine the two, the app bar is clipped (no right-hand side icons visible). I wanted to check the examples for the exact HTML code, but they only contain some javascript, which I don't want to use (and it is not even JS, but som other form that does not work in the browser).

Even when I replicated the exact HTML structure via inspector from the example page, it still did not work.

It only started to work after I added the CSS from the example page, but it is not clear what exactly it is adding on top of the MD CSS and why.

This is specifically about this case:
https://material-components.github.io/material-components-web-catalog/#/component/drawer/permanent

Thanks.

**Comment by abhiomkar** [comment]
Please see this example on [codepen](https://codepen.io/abhiomkar/pen/VgWJOy) that demos the MDC Drawer (permanent variant) with HTML / CSS only. Copied snippets from [mdc-drawer/README.md](https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer).

**Comment by PunchyRascal** [comment]
Thanks, I eventually had to switch to MDL anyway, since the main MD does not implement some stuff (e.g. tables).

**Comment by kfranqueiro** [comment]
We're aiming to implement data tables in Q2 of this year.

Since it looks like there's no further action to take here, I'm closing this issue. Thanks!
