### ISSUE TITLE
Ripple computeBoundingRect should escape out if return null or undefined

### ISSUE THREAD

**Issue by jamesmfriedman** [material-components/material-components-web#4348]
https://github.com/material-components/material-components-web/blob/c8d9117e2c3f7a538cf1fa65ae67f22399c8d05d/packages/mdc-ripple/foundation.js#L545

This is a React specific issue. We can never guarantee that we'll actually have a DOM element since we might be in process of tearing a component down.

This leads us to an adapter implementation like this which isn't ideal
```
computeBoundingRect: () =>
        this.root.ref ? this.root.ref.getBoundingClientRect() : {width: 0, height: 0},
```

Should be an easy enough fix, just a check in the foundation that computeBoundingRect returns a truthy value, which would lead to an implementation like this, and do nothing if we don't have a dom node

```
computeBoundingRect: () =>
        this.root.ref && this.root.ref.getBoundingClientRect()
```

**Comment by acdvorak** [comment]
Thanks for filing this issue, James!

Have you run into the same problem anywhere else? It seems like it could be a broader issue across all of our packages.

**Comment by jamesmfriedman** [comment]
The second typescript gets released I’ll know about every single one of them!

**Comment by acdvorak** [comment]
Please do! 😀 

We're planning to publish a pre-release version (`v1.0.0rc1`?) after #4407 gets merged.

**Comment by jamesmfriedman** [comment]
Awesome. Just let me know when if I miss it. I finished my full adapter foundation integration in TS so RMWC will be a good testbed

**Comment by acdvorak** [comment]
Ken reminded me that we also need to merge #4409 before we do a 1.0 release candidate. We'll keep you posted! 😀

**Comment by acdvorak** [comment]
Pre-release version `1.0.0-0` has been [published on npm](https://www.npmjs.com/package/material-components-web/v/1.0.0-0) 🎉

**Comment by jamesmfriedman** [comment]
Woot woot! Checking today.

**Comment by moog16** [comment]
@jamesmfriedman we have been talking about this, and although it would clean up React code (for RMWC and MDC React), it would mean we would need to have the null check in many places. We think that it should be the responsibility of the framework instead.

**Comment by jamesmfriedman** [comment]
Cool, I’ll just keep returning the fake object as a workaround.
