### ISSUE TITLE
material.io is broken

### ISSUE THREAD

**Issue by mraak** [material-components/material-components-web#4353]
Home page is empty.

https://material.io/

As well as Icons page.

https://material.io/tools/icons/

**Comment by CyborgSemon** [comment]
They work fine for me?

**Comment by mraak** [comment]
Interesting. This is the error I'm getting in the console.

![image](https://user-images.githubusercontent.com/812714/52270228-9a9ae900-2940-11e9-8477-acb7d6b38310.png)

**Comment by CyborgSemon** [comment]
I think there changes currently going on. The site is different for me now than it was 2 hours ago.

**Comment by mraak** [comment]
It works on Mac/Chrome it even works in Win/IE, but not in Win/Chrome.

**Comment by CyborgSemon** [comment]
Oh thats really odd. I haven't tried on windows so thats why I'm not seeing any errors :P

**Comment by kfranqueiro** [comment]
I just tried it in Chrome + Firefox + Edge on Windows and it worked in all 3.

Can you try force-refreshing Chrome (Ctrl+F5)?

**Comment by mraak** [comment]
Still the same error. Very strange.

**Comment by CyborgSemon** [comment]
I'm suspecting this might be an issue with Chrome. It might be an extension that you have downloaded, but tbh I cant see that being the case. 
Have you tried re-installing chrome and seeing if that works?
Thats the only thing I can come up with :P

**Comment by kfranqueiro** [comment]
I agree with Simon; an interfering extension is the only other thing I can think of. Short of reinstalling, you could try creating a new profile in Chrome and see if it still has the issue.

Unfortunately with no one else able to reproduce this, I'm afraid there isn't much else left for us to suggest :/

**Comment by kfranqueiro** [comment]
Given that we unfortunately haven't been able to reproduce this, I'm going to close this issue under the assumption it's an extension or other client-side problem. Sorry we haven't been able to be of more help.

**Comment by Blaq5** [comment]
just tried opening material.io and its not even loading at all
