### ISSUE TITLE
Investigate making the Stepper

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#44]
Spec reference: https://www.google.com/design/spec/components/steppers.html

- [ ] All steppers / step types, _except_ "Mobile Step"
- [ ] "Mobile Step"

Caveat: We might want to split this up differently once we get to this task, and recategorize the stepper types from the spec language to make it less ambiguous.
> Copied from https://github.com/google/material-design-lite/issues/4501

**Comment by ziyafenn** [comment]
Would love to see it implemented ! :)

**Comment by ColdRevsEnt** [comment]
Would love to see this as well!

**Comment by aaronhudon** [comment]
Here's my crack at creating a vertical stepper using the current state of the MDC library.

https://codepen.io/aaronhudon/full/MELydx/

**Comment by AndryHTC** [comment]
Are there some news?

**Comment by yxchng** [comment]
Same here

**Comment by mikaturk** [comment]
Will this see the light of day or is this not happening?

**Comment by sharpmachine** [comment]
What happened to the stepper? The new material design docs don't have it.

**Comment by GHXST01** [comment]
Is this still happening?

**Comment by Praveen-Rai** [comment]
Any updates ?

**Comment by Praveen-Rai** [comment]
I am not sure, what's the rational behind removing steppers from material design. I believe they are basic building blocks, when a step-by-step movement is required in UX flow. 

The progress indicators in Material Design spec. lacks the flexibility to show step progress ( which might have been useful to create a work-around for Stepper ). For e.g. i just want to display user's progress in a course ( number of lessons completed, and total number of lessons ). [ Basic step progress indicator ](https://stackoverflow.com/a/50347998/7491048). This isn't pretty, but the best i could get with Materialize & Material Design. 

CC @abhiomkar

**Comment by abhiomkar** [comment]
I sent this to design for response on this request.

**Comment by Praveen-Rai** [comment]
FYI .. I've raised a related request regarding [Determinate Progress Indicators](https://github.com/material-components/material-components/issues/70) design spec.

**Comment by equinusocio** [comment]
So steppers are dead... long live to steppers!

**Comment by abhiomkar** [comment]
Update: Our archived guidance is guidance that wasn't updated with our Material Theming release. We'll let the design team know that there is interest in this!

I'm closing this issue since nothing to implement until design guidance is updated for this component.

**Comment by danieleades** [comment]
@abhiomkar where can we track progress on this?

**Comment by emc5ud** [comment]
Not a solution, but for others that are searching on this topic:

If you can learn angular, the Angular Material stepper is quite good:
https://material.angular.io/components/stepper/overview

I personally do not know angular so this MDL stepper library is the best implementation I could find:
https://ahlechandre.github.io/mdl-stepper/
