### ISSUE TITLE
Filled text fields floating label doesn't align with trailing icon

### ISSUE THREAD

**Issue by TedSander** [material-components/material-components-web#4416]
### What browser(s) is this bug affecting?

Chome

### What OS are you using?

ChomeOS

### What are the steps to reproduce the bug?

Have a boxed input with a floating label and a trailing icon, input some text. The floated label will not align with the input.

### What is the expected behavior?

The floated label and the text will align.

**Comment by kfranqueiro** [comment]
Are there any particular details that would help reproduce this? Testing with the outlined text field with trailing icon on the [catalog page](https://material-components.github.io/material-components-web-catalog/#/component/text-field), the floating label seems to align correctly:

![image](https://user-images.githubusercontent.com/398379/52864705-b9e80200-3108-11e9-868c-9ce4d2155deb.png)

Can you get it to happen by forking [this codepen](https://codepen.io/kfranqueiro/pen/ErdrOe)?

**Comment by TedSander** [comment]
Boxed not outline. Screenshot from catalog. ChromeOS but also happens in Linux screenshot tests.

![screenshot 2019-02-15 at 3 28 10 pm](https://user-images.githubusercontent.com/5643740/52866470-a0f64580-3136-11e9-9b2c-faa1857e98e9.png)

**Comment by kfranqueiro** [comment]
Oh, sorry for the confusion. Wow yeah that definitely looks off. Thanks for reporting.
