### ISSUE TITLE
Label notch size width is calculated incorrectly on page load if value is set in textarea

### ISSUE THREAD

**Issue by gertcuykens** [material-components/material-components-web#4439]
version: `<link href="https://unpkg.com/material-components-web/dist/material-components-web.min.css" rel="stylesheet">`
`import {MDCTextField} from 'https://unpkg.com/@material/textfield?module'`
`root.querySelectorAll('.mdc-text-field').forEach((i)=>MDCTextField.attachTo(i))`

![image](https://user-images.githubusercontent.com/863731/53179621-5b34f380-35f4-11e9-8280-9b8eef28f300.png)

![image](https://user-images.githubusercontent.com/863731/53179643-68ea7900-35f4-11e9-8585-f82d6467cc2a.png)

```
        <div class="mdc-text-field mdc-text-field--textarea">
          <textarea id="textarea" name="intro" class="mdc-text-field__input" rows="8" cols="80">test</textarea>
          <div class="mdc-notched-outline">
            <div class="mdc-notched-outline__leading"></div>
            <div class="mdc-notched-outline__notch">
              <label for="textarea" class="mdc-floating-label">Intro</label>
            </div>
            <div class="mdc-notched-outline__trailing"></div>
          </div>
        </div>
```

Label notch size width is calculated incorrectly on page load if value is set in textarea. The correct width is recalculated after focus of textarea

**Comment by acdvorak** [comment]
Thanks for filing this issue! 😀 

I'm not able to reproduce it in a [CodePen](https://codepen.io/kfranqueiro/pen/gqJZXO); could you possibly send us one that shows the problem?

Out of curiosity, is the textarea being rendered inside of a dialog or some other component that's not initially visible when the page loads? If so, you'll need to call [`layout()`](https://github.com/material-components/material-components-web/tree/9b7dce7/packages/mdc-textfield#mdctextfield-properties-and-methods) on the `MDCTextField` instance after it becomes visible. There's a note about this in the [`mdc-dialog` README](https://github.com/material-components/material-components-web/tree/e58313d/packages/mdc-dialog#javascript-instantiation).

**Comment by gertcuykens** [comment]
Thanks for response

https://jsbin.com/hurevepohu/edit?html,output

Something like this but then lazy loaded with 
```html
    <script type="module">
       import('./hello.js').then(HelloWorld => customElements.define('hello-world', HelloWorld.default));
    </script>
  </head>
  <body>
    <hello-world></hello-world>
  </body>
</html>
```
Not sure how I can demonstrate this with jsbin

**Comment by gertcuykens** [comment]
A wait it already does show the wrong behavior without lazy loading, but not always apparently
https://jsbin.com/hurevepohu/edit?html,output
![image](https://user-images.githubusercontent.com/863731/53214927-b1368500-364e-11e9-97a7-f6582a2b1ae4.png)

**Comment by acdvorak** [comment]
Thanks for the jsbin!

I think I see the problem now: The `<link rel="stylesheet">` for
`material-components-web.min.css` is added to the DOM _after_ the page loads, which means it doesn't block rendering of `mdc-text-field`:

```js
render(html`
  <link href="https://unpkg.com/material-components-web/dist/material-components-web.min.css" rel="stylesheet">
  <form>
    <br>
    <div class="mdc-text-field mdc-text-field--textarea">
```

As a result, `MDCTextField.attachTo()` gets called before the CSS has loaded, which causes it to calculate the dimensions for the Floating Label and Notched Outline incorrectly.

You can add a `'load'` event handler to the `<link>` element that calls
`textfield.layout()`:

https://jsbin.com/judazonune/1/edit?html,output

```js
const linkEl = root.querySelector('link[rel="stylesheet"]');
const textfield = MDCTextField.attachTo(root.querySelector('.mdc-text-field'));
linkEl.addEventListener('load', () => textfield.layout());
```

Does that solve your problem?

**Comment by gertcuykens** [comment]
Thanks that fixes it, but this also means every `textfield.layout()` is runed twice right? One with the wrong size and then one time with the correct size right? Is there a way to do manual layout() only?

**Comment by acdvorak** [comment]
Correct. You can avoid calling `layout()` twice by running `MDCTextField.attachTo()` inside of the `'load'` event listener.
