### ISSUE TITLE
Material Design Lite library of components for Angular 2+

### ISSUE THREAD

**Issue by YagoLopez** [material-components/material-components-web#444]
First of all excuses for my English. It is not my first language and I hope do not to bother anyone opening here an issue.

I started to learn Angular 2 creating components based on Material Design Lite v1 as an experiment. Eventually I ended up creating a library of components that could be useful. It is open source but I dont know if I have permission to release to the public. Maybe in the future MCW could be adapted to Angular2+. In my opinion could be lighter, more performant and easier to use that the actual Material Design 2, it is just my opinion.

The repo is hosted here:
https://github.com/YagoLopez/material-light

You can check an online demo there.

I would like to hear any opinion or comment from your team.
Anyway thanks for your time.

Cheers,
Yago Lopez.

**Comment by traviskaufman** [comment]
Hey @YagoLopez,

Thanks for reaching out to us, and nice work on material-light!

You can definitely use MDC-Web with Angular2. In fact we have an example of how this can be achieved within https://github.com/material-components/material-components-web/tree/master/framework-examples/angular2. 

While we don't have any plans to support an angular2+ wrapper ourselves, we encourage community members (like yourself!) to try that out and publish your results! 

Thanks so much!

**Comment by YagoLopez** [comment]
Thanks for your message, Travis. The work you and your collaboratos have done with MDL is and MDC is excellent. Good performance and great results, thats why I made an Angular version. I'll take a look to the examples you provided and try to do another integration in the future

When I have someting new I'll let you know although it will take some time. Still ending details of ML v1 :)

It's been a pleasure.
till then keep the good work guys 👍

**Comment by WindSaber** [comment]
Hi all
I'm afraid the branch provided by @traviskaufman  is not available anymore (https://github.com/material-components/material-components-web/tree/master/framework-examples/angular2)

Do you have another example to work with? I'm having troubles working with angular 5 + mdc and any help will be appreciated
