### ISSUE TITLE
using MDC with netbenas

### ISSUE THREAD

**Issue by 16rajumane** [material-components/material-components-web#4456]
Respected Admin,
I am a beginner in MDC I want to know how to download MDC component in netbeans IDE. and use with other web frameworks such as apache struts. Plz help as this is my first college project

**Comment by acdvorak** [comment]
Hi there! Thanks for your interest in MDC Web 😀 

Text editors like NetBeans are used to write code, and typically do not have facilities for "downloading" front end libraries such as ours.

Please read our [Getting Started guide](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md), which explains how to set up a project that uses MDC Web.
You'll need to install [Node.js](https://nodejs.org/en/download/) first. It comes with a tool called [`npm`](https://docs.npmjs.com/about-npm/), which is a package manager that lets you "download" JavaScript libraries, [including ours](https://www.npmjs.com/package/material-components-web). Make sure to run the `npm i` command inside a folder within your project.

We're more than happy to investigate bugs and feature requests, but unfortunately we don't have the bandwidth to help with coding questions.

I would recommend reading [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask). After that, you can try asking your questions on [StackOverflow](https://stackoverflow.com/) or the [`ProgrammingHelp` sub-Reddit](https://www.reddit.com/r/ProgrammingHelp).

Thanks again!
