### ISSUE TITLE
top app bar with left right margin

### ISSUE THREAD

**Issue by keinagae** [material-components/material-components-web#4457]
i want to give left right margin to top app bar  but giving margin make it go out side container element ignoring right margin or even padding

**Comment by acdvorak** [comment]
Thanks for filing this issue!

We're happy to help, but first we need more information 😀 

Could you provide a [CodePen](https://codepen.io/abhiomkar/pen/gQWarJ) with the minimum code needed to demonstrate the problem?

**Comment by kfranqueiro** [comment]
Given no further response, we're closing this issue. We can reopen it if you provide some kind of reproduction case in a codepen or similar.
