### ISSUE TITLE
how to open new html page on button click

### ISSUE THREAD

**Issue by 16rajumane** [material-components/material-components-web#4459]
respected admin,
I am creating a website using google material component. I want to know how to open new html page on button click.

**Comment by CyborgSemon** [comment]
Just add button styles to an `<a class="mdc-button" href=""></a>`?
Or add an `onclick` or `addEventListener` to the button with `location.href = 'www.google.com'`

**Comment by acdvorak** [comment]
Hi there! Thanks for your interest in MDC Web 😀 

We're more than happy to investigate bugs and feature requests, but unfortunately we don't have the bandwidth to help with coding questions.

I would recommend reading [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask). After that, you can try asking your questions on [StackOverflow](https://stackoverflow.com/) or the [`ProgrammingHelp` sub-Reddit](https://www.reddit.com/r/ProgrammingHelp).

Thanks again!

(@CyborgSemon thanks for the helpful response! 😁 )
