### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by gertcuykens** [material-components/material-components-web#4460]
chrome example: https://output.jsbin.com/fotedog

https://jsbin.com/fotedog/edit?html,output

probably related to https://github.com/material-components/material-components-web/issues/629

Not sure how to fix it

![image](https://user-images.githubusercontent.com/863731/53515281-e406d000-3ac9-11e9-955d-1f7572d0800c.png)

![image](https://user-images.githubusercontent.com/863731/53520192-5df08680-3ad5-11e9-865e-8cf7d67c0f65.png)

**Comment by acdvorak** [comment]
Thanks for bringing this to our attention!

We'll need to update the component's default adapter implementation to pass `{passive: true}` as the third parameter to `addEventListener()` in [supported browsers](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener):

https://github.com/material-components/material-components-web/blob/ad5743ae665d138c38a23ba36a3d2f63b5c388d5/packages/mdc-textfield/component.ts#L381-L390

It looks like a number of components listen to `touchstart` events: `ripple`, `select`, `slider`, `textfield`, and `tab-bar-scroller`. So we might want to extract the `applyPassive()` function from ripple util and move it to `mdc-dom`:

https://github.com/material-components/material-components-web/blob/2025c8b5eb9891ec3f159e2fde03f45d23f6bbed/packages/mdc-ripple/util.ts#L91-L109

**Comment by moog16** [comment]
I'm no longer seeing this issue in our screenshot tests, unit tests, or in the jsbin provided. Is this something we should still fix?

**Comment by gertcuykens** [comment]
When you refresh the page it still happens, why you need to refresh I don't know.

![image](https://user-images.githubusercontent.com/863731/57415935-5b5d8c00-71fe-11e9-9030-6035a8088eeb.png)

**Comment by abhiomkar** [comment]
I'm able to reproduce this, the log level should be set to verbose.

**Comment by moog16** [comment]
I see this with verbose as well.
