### ISSUE TITLE
Strange jquery unobtrusive validation behavior

### ISSUE THREAD

**Issue by berets76** [material-components/material-components-web#447]
### What MDC-Web Version are you using?

0.7.0

### What browser(s) is this bug affecting?

All

### What OS are you using?

Windows 10 64 bit

### What are the steps to reproduce the bug?

If you go on the demo login form hereunder, can see different behavior on validation errors, basically :
1) if you type a non valid email address, e.g. "kjhkjhkjhkjhjkhjkjkhkj", error message becomes visible, validation fails and textfield label becomes red;
2) if you leave email blank or if you type a valid email address with more than 10 chars, e.g. "kjhkjhkjhkjh@jkhjkjkhkj", error message becomes visible, validation fails BUT textfield label keep its original color (blue)

We create a demo with jsfiddle https://jsfiddle.net/berets/nf7w7kLe/4/

### What is the expected behavior?

Always red label or always original color

### What is the actual behavior?

Unpredictable

### Any other information you believe would be useful?
Debugging, the problem is that when fails email format rule the class [mdc-textfield--invalid] is added to [mdc-textfields] DIV, when insted fails required or max length validation that class isn't added.

**Comment by anton-kachurin** [comment]
The MDC Textfield component internally uses `checkValidity` method of the input, which is a part of [Constraint Validation API](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/HTML5_updates#Constraint_Validation_API), therefore [HTML Syntax for Constraint Validation](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/HTML5_updates#HTML_Syntax_for_Constraint_Validation) must be used for the input.

jQuery plugin uses custom `data-val-*` attributes which is incompatible with it.

To make you markup consistent to Validation API, add `pattern=".{1,10}"` attribute to the input. Check the [modified fiddle](https://jsfiddle.net/8qnt34an/).

Alternatively, you can use`maxlength="10"` attribute, but this will prevent from typing in more than 10 symbols.

**Comment by berets76** [comment]
Understood: I'm using ASP.NET Core MVC to generate my HTML, and validation attributes are generated using [DataAnnotations ](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation) that produces JQuery's needed attributes.

Email validation works anyway because the `[EmailAddress(ErrorMessage = "ERR1")]` statement produces a `type="email"` attribute that works with HTML5 validation.

So, I've only two possible ways to use MDC with ASP.NET Core MVC:
- don't use DataAnnotations to manage validation client side and manually set attributes in views (not very DRY);
- write my own DataAnnotations (or search if them already exist) that produces HTML5 validation's attribute.

Thanks

**Comment by amsheehan** [comment]
JavaScript versions of `mdc-textfield` have a class `mdc-textfield--invalid` that can be [added/removed programatically](https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/mdc-textfield.scss#L502). So, to solve the problem, you may add the class when validation fails due to required or max length.

This solve only works for JavaScript versions of `mdc-textfield`, but it sounds like that's what you're using anyway. We will have to think on an implementation for CSS-only versions.

**Comment by anton-kachurin** [comment]
@amsheehan please correct me if I'm wrong, the component will add/remove `--invalid` modifier class to the element [on blur](https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/foundation.js#L112) after calling `.checkValidity()`, and it's currently not possible to prevent it from doing so. 

So if there is some third-party Javascript that adds that class, but there is no `pattern`, `type`, `maxlength`, or `required` attribute set to the input element, chances are the modifier class will be removed by the component, therefore validation must be done through the HTML5 Validation API.
