### ISSUE TITLE
Text Field with character count can be bypassed in Chrome on Pixel Devices

### ISSUE THREAD

**Issue by Charizard** [material-components/material-components-web#4480]
A user can by-pass the character limit of text field elements in Chrome for Android (able to replicate in Pixel 2 and 3).

### What MDC Web Version are you using?

Latest

### What browser(s) is this bug affecting?

Chrome on Pixel Devices

### What OS are you using?

Android

### What are the steps to reproduce the bug?

- Open the [demo page](https://material-components.github.io/material-components-web-catalog/#/component/text-field) in Chrome browser on Pixel 2 and 3.
- Keep typing without a space on a textarea with character count.

### What is the expected behavior?

> When the limit is reached, user input should not be allowed.

### What is the actual behavior?

> The inputs are shown in the field after exceeding the limit.

**Comment by abhiomkar** [comment]
Thanks for reporting this issue @Charizard!

Seems like this is expected behaviour in Chrome on Android. As per [caniuse.com](https://caniuse.com/#feat=maxlength):
```
Allows text beyond maxlength to be entered at first,
but removes all characters past the maxlength when focus is lost.
```

**Comment by Charizard** [comment]
@abhiomkar Thanks. Closing the issue.
