### ISSUE TITLE
FR for MDC Tab: Remove hardcoded opacity and allow developers to specify

### ISSUE THREAD

**Issue by bwobrien** [material-components/material-components-web#4487]
The opacity of the Tab's text label and icon is hardcoded with no way to overwrite it via official mixins (https://github.com/material-components/material-components-web/blob/master/packages/mdc-tab/mdc-tab.scss#L90,L101).

Rather than add a mixin for opacity specifically, this request is to remove the hardcoded opacity and simply allow developers to specify opacity by passing an rgba value to color-related Sass mixins (e.g. mdc-tab-text-label-color)

**Comment by abhiomkar** [comment]
Seems like this was fixed in #4675 Closing this one.
