### ISSUE TITLE
The text colour for .mdc-drawer .mdc-list-item--activated doesn't use the primary mixin

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4489]
When chancing the primary colour mixin, The text for `.mdc-drawer .mdc-list-item--activated` stays at the default purple because it is set to a `rgba()` value.
This might also be the case for other colours, I'm not 100% sure though. Im just guessing that if it has slipped though once, it might have slipped though a second time.
(Currently using 1.0.0)
<img width="238" alt="Screen Shot 2019-03-09 at 4 52 55 PM" src="https://user-images.githubusercontent.com/26075792/54065902-ed432a00-428b-11e9-95bb-8b3a40e448a8.png">
<img width="266" alt="Screen Shot 2019-03-09 at 4 52 38 PM" src="https://user-images.githubusercontent.com/26075792/54065903-efa58400-428b-11e9-8f8e-60308c21a227.png">
<img width="225" alt="Screen Shot 2019-03-09 at 4 52 46 PM" src="https://user-images.githubusercontent.com/26075792/54065905-f502ce80-428b-11e9-8171-04a20d751bfc.png">

**Comment by kfranqueiro** [comment]
This is one instance of a recurring issue represented in #4431.
