### ISSUE TITLE
Linear Progress's buffer always set to 1 after setting determinate to true

### ISSUE THREAD

**Issue by tychenjiajun** [material-components/material-components-web#4491]
## Bugs

https://codepen.io/chankcccc/pen/GevMWM

The buffer was set to 0.7 initially but would be set to 1 after clicking the button

### What MDC Web Version are you using?

0.44.1

### What browser(s) is this bug affecting?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

### What OS are you using?

Manjaro

### What are the steps to reproduce the bug?

https://codepen.io/chankcccc/pen/GevMWM

### What is the expected behavior?

The buffer is not set to 1 or set the progress to a default value like what it does to the buffer

**Comment by kfranqueiro** [comment]
Looks like we're indeed clearing it when determinate is set to false: https://github.com/material-components/material-components-web/blob/v1.0.0/packages/mdc-linear-progress/foundation.ts#L71

So we'd either need to store that value for later, or see whether we can get away with not doing that.
