### ISSUE TITLE
MDCTextField: Stop using i tag for icons

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#4496]
Semantically, this is incorrect usage and the documentation should reflect the correct element to use `span`.

**Comment by rarous** [comment]
`i` does not have any semantic meaning. This is correct use.

**Comment by williamernest** [comment]
According to the HTML5 spec: 
```The i element represents a span of text in an alternate voice or mood, or otherwise offset from the normal prose in a manner indicating a different quality of text, such as a taxonomic designation, a technical term, an idiomatic phrase from another language, transliteration, a thought, or a ship name in Western texts.```

Icons are not "a span of text in an alternate voice or mood". A more appropriate element to use is a `span`. 

https://dev.w3.org/html5/spec-LC/text-level-semantics.html#the-i-element

**Comment by rarous** [comment]
It is, because icon has its text representation and it should be pitched in text reader (voice output) to distinguish it from other texts.

**Comment by BhavyaSingh2611** [comment]
why to extend your work and use span instead of i as the end result is going to be same and user sees webpage and not the source code

**Comment by kfranqueiro** [comment]
IIUC this report originated from a remark on Twitter. However, I think the counter-argument here is also valid. Moreover, the usage of `<i>` is consistent with documentation on the [Material icons site](https://material.io/tools/icons/) as well as with other icon font libraries such as [Font Awesome](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use). So I agree that this isn't something to prioritize here, especially if it causes inconsistency with Material Icons documentation.
