### ISSUE TITLE
Switch word order of MDCTopAppBar Sass Variable

### ISSUE THREAD

**Issue by ALMaclaine** [material-components/material-components-web#4497]
The sass variable in MDCTopAppBar [Here](https://github.com/material-components/material-components-web/blob/master/packages/mdc-top-app-bar/_variables.scss#L56).

Should be 
```$mdc-top-app-bar-dense-prominent-title-bottom-padding``` 

Instead of 
```$mdc-top-app-bar-prominent-dense-title-bottom-padding```

With dense and prominent switched. It's preferred throughout the package for dense to be before prominent.

In the associated class name:
```.mdc-top-app-bar--dense-prominent-fixed-adjust```
[Here](https://github.com/material-components/material-components-web/blob/master/packages/mdc-top-app-bar/mdc-top-app-bar.scss#L220).

In the order of the classes:
```.mdc-top-app-bar--dense.mdc-top-app-bar--prominent``` [Here](
https://github.com/material-components/material-components-web/blob/master/packages/mdc-top-app-bar/mdc-top-app-bar.scss#L187).

Should at the very least help with autocomplete and seems sensible.

**Comment by ALMaclaine** [comment]
Pull request to update.

https://github.com/material-components/material-components-web/pull/4498

**Comment by kfranqueiro** [comment]
Fixed by #4498
