### ISSUE TITLE
MDCTab.active can not be watched by Vue.js, while some other components' similar props can be watched

### ISSUE THREAD

**Issue by tychenjiajun** [material-components/material-components-web#4505]
### What MDC Web Version are you using?

1.0.1

### What browser(s) is this bug affecting?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

### What OS are you using?

Manjaro

### What are the steps to reproduce the bug?

https://codepen.io/chankcccc/pen/LaQYyG?editors=1111
Try clicking the tabs and type `app.first` or `app.second` to see the return value

For comparison, see https://codepen.io/chankcccc/pen/EMQYMM . click the button and type in `app.open` when the snackbar is opened or closed.

### What is the expected behavior?

The MDCTab.active should be watched. Thus the `app.first` and `app.second` in the codepen should be updated when the corresponding tab is activated or deactivated.

### What is the actual behavior?

The app.first` and `app.second` in the codepen stay the same no matter what tab is activated.

**Comment by abhiomkar** [comment]
Thanks for reporting this issue @tychenjiajun!

Since Vue.js doesn't support attaching custom event that has colon in HTML, you might've to bind the event manually using computed property for listener.

```
  computed: {
    tabChangeListener: function () {
      var vm = this;
      return Object.assign({},
        this.$listeners,
        {
          'MDCTabBar:activated': function (event) {
            console.log('changed', event.detail)
          }
        },
      );
    }
  },  
  template: '<div v-on="tabChangeListener" class="mdc-tab-bar"...
```

Here is an updated [codepen](https://codepen.io/abhiomkar/pen/LaQaXN?editors=1011).

**Comment by abhiomkar** [comment]
Also please take a look at [Tabs](https://stasson.github.io/vue-mdc-adapter/#/component/tabs) implementation in Vue.js.

**Comment by tychenjiajun** [comment]
@abhiomkar 
Sorry for my mistake that makes the problem confusing, I've updated my codepen and change `:active` to `v-model`, which was a mistake.

Vue.js support attaching custom event that has colon in HTML, I can write like the following

```javascript
  <div
    role="tablist"
    class="mdc-tab-bar"
    @MDCTabBar:activated="onActivated"
  >
    <slot />
  </div>
```
 and it works.

**Comment by abhiomkar** [comment]
I've limited knowledge on using `v-model` for custom components in Vue.js. But if you look at my codepen example above, the MDCTabBar instance returns the appropriate value on `.activeTab` property.

**Comment by abhiomkar** [comment]
I'm closing this issue, implementing this component in Vue.js with v-model seems like out of the scope of this project. Please feel free to re-open if you think this issue is related to MDCTabBar component.
