### ISSUE TITLE
MDC-web: clicking enhanced select hides options after releasing click.

### ISSUE THREAD

**Issue by scbrading** [material-components/material-components-web#4514]
Using the Enhanced Select...

Clicking on the select flickers the options menu.
Holding a click leaves the options menu displayed. Releasing the click closes the options menu.

This can be observed here using chrome:
https://material-components.github.io/material-components-web-catalog/#/component/select

Notice: Clicking on any of the enhanced selects causes inconsistent displaying of the menus.

Desired behavior: The menu should open when clicked and close when the user clicks again.

**Comment by kfranqueiro** [comment]
Thanks for the report. This is a duplicate of #4173.
