### ISSUE TITLE
[Select] MDC-web: Select truncation is hidden by icon

### ISSUE THREAD

**Issue by scbrading** [material-components/material-components-web#4515]
When the value/placeholder of the select box needs to be truncated, the ellipsis begins after the trailing icon (down arrow). This causes the text to run right into the icon.

<img width="200" alt="Screen Shot 2019-03-19 at 10 33 48 AM" src="https://user-images.githubusercontent.com/17559523/54614392-b3fc7e00-4a32-11e9-8424-cad8f933a5bb.png">

Desired behavior: The ellipsis begins and ends in front of the down arrow.

**Comment by kfranqueiro** [comment]
Thanks for the report. Looks like we've potentially got a couple of issues to iron out in this regard.

Codepen: https://codepen.io/kfranqueiro/pen/vPzBLm

FWIW, I think we made a conscious decision to avoid the ellipsis in the select, but clearly we're inconsistent about that between filled and outlined variants.

Preferably you'd want to pick a width for your selects that leave enough width to fit its items, but I can understand if that's not always feasible, and we should at least make this behave consistently and a bit more nicely.

**Comment by allan-chen** [comment]
The selected text truncation is fixed after 28d10a96. The placeholder (label) fix is upcoming.

**Comment by allan-chen** [comment]
#6044 should fix this
