### ISSUE TITLE
Incorrect / confusing README info regarding applying text style classes in themes

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#4523]
When looking at the [css custom properties section of the mdc-theme README](https://github.com/material-components/material-components-web/tree/master/packages/mdc-theme#css-custom-properties), it says:

> **A note about <TEXT_STYLE>,** <TEXT_STYLE> represents the lowercase name of the text styles listed above, e.g. `hint`

However, AFAICT there don't seem to be any "text styles" listed above, and when I look in the table of modifiers I do not see "hint" anywhere on the page:

![mdc-theme-no-textstyles](https://user-images.githubusercontent.com/1185269/54718040-01aae080-4b30-11e9-8701-3aab5138d19e.png)

I was able to find it by looking in [the code](https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_variables.scss#L51-L66); perhaps it was removed from the docs at some point and needs to be re-added back in?

FWIW even though it's a bit more work listing out the text styles explicitly would create less work for me as an end user :smiley: 

Thanks for all your hard work on the library!

**Comment by moog16** [comment]
We might have remove this thinking we would add them back. We will try to digging in history and put that table back in place.

**Comment by kfranqueiro** [comment]
This might've been intentionally removed while work was being done on mdc-theme last year... but it also might've been unintentionally removed when we cleaned up formatting in our readme files.

We've gradually been moving towards 3 text emphasis levels (see `$mdc-theme-text-emphasis` below the code you highlighted), which we tend to combine with a color via `rgba` in Sass (though this is admittedly less css-custom-property friendly), but there are still some styles (and the existing mdc-theme variables) referencing the original 5-level map that went missing from the docs. For the time being, at least, it seems like we'll need to document both.
