### ISSUE TITLE
MDC Menu: Implement API to change selected item in selection group

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#4525]
Implement API to change selected item in selection group. 

For example,

```
// API Signature
menu.setSelectedIndex(index: number, selectionGroupIndex = 0)

// Usage
menu.setSelectedIndex(3)
```

![image](https://user-images.githubusercontent.com/47312/54722748-af6fbc80-4b3b-11e9-8a49-e6d4d040e49d.png)

Plausible ARIA attributes for selectable menu items

- `role="menuitemradio"` for each selectable menu item.
- `aria-checked="true"` for selected menu item.

**Comment by moog16** [comment]
We should also be updating the aria tags with regards to the checkbox.

**Comment by moog16** [comment]
Closing for #4620
