### ISSUE TITLE
checkbox is missing a required prop as a form component

### ISSUE THREAD

**Issue by dohomi** [material-components/material-components-web#4537]
## Feature Requests

Checkbox component is missing a "required" option to align with Textfield and other form input fields. Not sure if this is part of Material Design spec but I think many GDPR forms need this option on any forms of the website

Hope this make sense

**Comment by moog16** [comment]
Design does not have any spec on this. So this isn't something in scope of checkbox at this point. MDC Web still allows you to have checkbox validation with the required attribute.

**Comment by dohomi** [comment]
@moog16 thanks for your answer. Thats very interesting how would people use this element in any form? If checkbox is activated and validation fails no visual color change happens.

**Comment by moog16** [comment]
Yes we realize there is a use case, but this isn't a priority for design. It should be fairly straightforward to come up with an error state using our sass mixins/css. Please try using those, and let us know if you run into any issues.
