### ISSUE TITLE
[question]why? MDC-web components so big?

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#4539]
just checking

**Comment by moog16** [comment]
@diuming what do you mean by huge? Is this file size you're talking about?

**Comment by diuming** [comment]
@moog16 thank you for replying!
sorry! I did not say very clearly about huge.
I'm talking about the size of UI components, example: I have 10 text field in <div>.
I'm not challenge you just checking.
thanks.

**Comment by kfranqueiro** [comment]
If you're referring to visual size of components, there is a design effort in the works to systematize the "density" of components. We don't have much in the way of code yet (aside from the already-existing `--dense` variants for a couple of components, which may end up replaced once this system is designed), and there's no ETA currently, but it's on the roadmap for 2019.

**Comment by diuming** [comment]
@kfranqueiro 
I got it.
thank you!
