### ISSUE TITLE
Grid-list does not handle empty list

### ISSUE THREAD

**Issue by larserikfinholt** [material-components/material-components-web#454]
v0.7.0
Chrome
Windows10

1. run the demo server
2. go to localhost:8080/grid-list.html
3. no errors
4. remove all li from one of the ul
5. error: Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at Object.getOffsetWidthForTileAtIndex (index.js:32)

It should handle empty ul's

### What is the actual behavior?
Throws error when list is empty

### Any other information you believe would be useful?
This is the failing line: `return this.root_.querySelectorAll(MDCGridListFoundation.strings.TILE_SELECTOR)[index].offsetWidth;
      },`

Here's an working version of getOffsetWitdthForTileAtIndex:

`getOffsetWidthForTileAtIndex: (index) => {
        const tile = this.root_.querySelectorAll(MDCGridListFoundation.strings.TILE_SELECTOR)[index];
        return tile ? tile.offsetWidth : 0;
      },`

**Comment by amsheehan** [comment]
Thanks for filing this! Definitely a bug.

**Comment by amsheehan** [comment]
It looks like to solve this issue, the following should be addressed:

- [ ] Implement proposed solution
- [ ] Update tests
- [ ] Reflect changes in README
- [ ] Reflect changes in Demo
