### ISSUE TITLE
MDCDrawer@1.1.0 crashes when no item is active

### ISSUE THREAD

**Issue by cmath10** [material-components/material-components-web#4544]
## Bugs

MdcDrawer (modal variant) without any active item crashes when opened:

https://codepen.io/cmath10/pen/wObyWR

But dismissable variant works fine:

https://codepen.io/cmath10/pen/WmBMwW

Got it in console:

Error: You can't have a focus-trap without at least one focusable element index.js:198
    y index.js:198
    b index.js:268
    n index.js:72
    trapFocus component.ts:147
    opened_ foundation.ts:39
    handleTransitionEnd foundation.ts:146
    handleTransitionEnd_ component.ts:100

### What MDC Web Version are you using?

1.1.0

### What browser(s) is this bug affecting?

Firefox 66.0.1
Chrome 73.0.3683.86

### What OS are you using?

Linux Mint 19.1

### What are the steps to reproduce the bug?

1. Open codepens above.
2. Open console.
3. Open drawer.
4. See behavior.

### What is the expected behavior?

No errors in console, no crashes

### What is the actual behavior?

App crashed, console has error message

### Any other information you believe would be useful?

Possible workaround - adding empty anchor to menu top:
`<a href="#"></a>`

**Comment by moog16** [comment]
This might have already been reported @abhiomkar can you remember was this about drawer or dialog?

**Comment by abhiomkar** [comment]
This seems to be dup of #762

Please see this comment https://github.com/material-components/material-components-web/issues/762#issuecomment-448918913 for explanation.

**Comment by cmath10** [comment]
> This seems to be dup of #762
> 
> Please see this comment [#762 (comment)](https://github.com/material-components/material-components-web/issues/762#issuecomment-448918913) for explanation.

I read the comment, and example of dismissible drawer you provided:
https://stackblitz.com/edit/mdc-drawer-demo-ytwosc?file=index.html

This still not clear for me. I notice that drawer in your example has no item with class `mdc-list-item--activated` or `mdc-list-item--selected`. I have the same drawer content in my _modal_ drawer, it crashes if no item has a class `mdc-list-item--activated`, if i add it to entry, problem disappears, but i really need menu in my app without already selected item(s). I has `mdc-list` with items like `<a class="mdc-list-item" href="#">...<a>`, why this anchors is not focusable, but empty is? `aria-selected="true"` does not help as well.

**Comment by abhiomkar** [comment]
Thanks for spotting it! The list expects at least one item to have `tabindex="0"`. I fixed your example by simply adding `tabindex="0"` to first list item. See [MDCList's Accessibility section](https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#accessibility).

Here is the [updated codepen](https://codepen.io/abhiomkar/pen/pBaKXm) that has fix.

**Comment by cmath10** [comment]
@abhiomkar, thanks, this helped.
