### ISSUE TITLE
MDCTopAppBar README should not import index file

### ISSUE THREAD

**Issue by ALMaclaine** [material-components/material-components-web#4554]
In the MDCTopAppBar README [here](https://github.com/ALMaclaine/material-components-web/blob/master/README.md#javascript).

The import statement should not import the `/index` but rather the package name.

```js
// From
import {MDCTextField} from '@material/textfield/index';

// To
import {MDCTextField} from '@material/textfield';
```

As per the [importing-js.md](https://github.com/material-components/material-components-web/blob/master/docs/importing-js.md#es-modules) and #4509

**Comment by Richienb** [comment]
By removing `/index`, the code is made much slower.

**Comment by kfranqueiro** [comment]
Can you elaborate on how the code is made slower? Do you mean it is causing your bundles to get larger?

Removing `/index` should not have any effect whatsoever on webpack, etc. because it will resolve `module` in `package.json` to `/index` anyway.

**Comment by ALMaclaine** [comment]
@Richienb in case you aren't following.

**Comment by Richienb** [comment]
According to [this page](https://material.io/develop/web/docs/importing-js/), `However, if you want to take advantage of tree-shaking and dependency sharing within MDC Web’s code to reduce the size of your built assets, you will want to explicitly reference the package’s index.js`

**Comment by kfranqueiro** [comment]
That comment is similarly obsolete for the same reason. It was written before we were able to define the `module` property in `package.json` (because prior to the TypeScript conversion, our ES modules' contents were not purely ES5).

**Comment by Richienb** [comment]
@kfranqueiro Oh. I see.
