### ISSUE TITLE
Disabled menu items should be focusable

### ISSUE THREAD

**Issue by marcianx** [material-components/material-components-web#4561]
Per [the menu README](https://github.com/material-components/material-components-web/blob/797ebc89e97348d5aac80616f70581c7b0f76a13/packages/mdc-menu/README.md):

> ## Disabled Menu Items
> Menu items can be disabled by adding the `mdc-list-item--disabled` modifier class (from MDC List). Disabled menu items will be excluded from keyboard navigation.`

However, the [ARIA practices documentation](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) states that disabled menu items must be focusable (i.e. keyboard navigable), though not activatable (see the first point under the green "NOTE" section).

See also [further elaborations on ARIA-practices on handling disabled elements](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_disabled_controls).

**Comment by aeromac** [comment]
Is it possible that mdc-list-item--disabled includes pointer-events:none? Otherwise, it is visually disabled but functionally still enabled. I'm not sure how this will affect aria.
