### ISSUE TITLE
MDC without SASS and WebPack

### ISSUE THREAD

**Issue by Zeni241** [material-components/material-components-web#4564]
I am new to MDC and following  [Quick Start (CDN)](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md).  
I have nodejs server behind nginx reverse proxy. So I don't know how webpack will fit in. Thus I want to avoid webpack. Also I don't want to use SASS (as I know nothing about it :) ). 
Buttons and many things worked OK but I am stuck at [Drawer](https://material.io/develop/web/components/drawers/).

Can anyone please guide me how to make MDC work completely without webpack and SASS?

**Comment by moog16** [comment]
@Zeni241 it's totally ok to use MDC without Sass or Webpack. Is your nodejs server a REST service?

1. You could setup nginx to redirect to a webpack-dev-server, but that's an advanced configuration of nginx (difficult to figure out via a GH issue). 
2. You could have webpack build static JS files (and/or CSS) and have nginx serve the same directory that webpack builds those static JS files into.
3. You could just use the CDN as you mentioned by including `<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>` in your `<head>`. This gives you access to the global variable `mdc`. Reference [this object](https://github.com/material-components/material-components-web/blob/master/packages/material-components-web/index.ts#L83) to see what lives in the global `mdc` object. 

Does this help?

**Comment by Zeni241** [comment]
Thanks @moog16 . I will take MDC without Sass or Webpack path.  I am doing  [MDC-102 Web: Material Structure and Layout (Web) ](https://codelabs.developers.google.com/codelabs/mdc-102-web/#2)tutorial now and I am getting error
   `Uncaught ReferenceError: MDCList is not defined`

My complete listing is as follows:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="https://material.io/favicon.ico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    
    <title>Document</title>
<style>
    .shrine-logo-drawer {
        display: block;
        width: 48px;
        padding: 40px 0 0;
        margin: 0 auto;
        fill: currentColor;
      }
      
      .shrine-title {
        text-align: center;
        margin: 5px auto;
      }
    </style>
</head>
<body>
    <aside class="mdc-drawer shrine-drawer">
        <div class="mdc-drawer__header">
          <svg class="shrine-logo-drawer" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
             width="48px" height="48px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve" fill="#000000" focusable="false">
            <g>
              <g>
                <path d="M17,2H7L2,6.62L12,22L22,6.62L17,2z M16.5,3.58l3.16,2.92H16.5V3.58z M7.59,3.5H15v3H4.34L7.59,3.5z
                   M11.25,18.1L7.94,13h3.31V18.1z M11.25,11.5H6.96L4.69,8h6.56V11.5z M16.5,12.32 M12.75,18.09V8h6.56L12.75,18.09z"/>
              </g>
              <rect fill="none" width="24" height="24"/>
            </g>
          </svg>
          <h1 class="shrine-title">SHRINE</h1>
        </div>
        <div class="mdc-drawer__content">
          <nav class="mdc-list">
            <a class="mdc-list-item mdc-list-item--activated" aria-selected="true" tabindex="0" href="#">
              <span class="mdc-list-item__text">Featured</span>
            </a>
            <a class="mdc-list-item" href="#">
              <span class="mdc-list-item__text">Apartment</span>
            </a>
            <a class="mdc-list-item" href="#">
              <span class="mdc-list-item__text">Accessories</span>
            </a>
            <a class="mdc-list-item" href="#">
              <span class="mdc-list-item__text">Shoes</span>
            </a>
            <a class="mdc-list-item" href="#">
              <span class="mdc-list-item__text">Tops</span>
            </a>
            <a class="mdc-list-item" href="#">
              <span class="mdc-list-item__text">Bottoms</span>
            </a>
            <a class="mdc-list-item" href="#">
              <span class="mdc-list-item__text">Dresses</span>
            </a>
            <a class="mdc-list-item" href="#">
              <span class="mdc-list-item__text">My Account</span>
            </a>
          </nav>
        </div>
      </aside>
      <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
      |<script>
     new MDCList(document.querySelector('.mdc-list'));
      // const list = MDCList.attachTo(document.querySelector('.mdc-list')); list.wrapFocus = true;
      // const drawer = MDCDrawer.attachTo(document.querySelector('.mdc-drawer'));

      </script>
</body>
</html>
```

I tried different variants of drawer javascripts from [here](https://material.io/develop/web/components/drawers/) without success.

**Comment by BhavyaSingh2611** [comment]
use `const list = new mdc.list.MDCList.attachTo(document.querySelector('.mdc-list')); 
list.wrapFocus = true;
const drawer=new mdc.drawer.MDCDrawer.attachTo(document.querySelector('.mdc-drawer'));`

**Comment by BhavyaSingh2611** [comment]
to instantiate list and drawer

**Comment by kfranqueiro** [comment]
@BhavyaSingh2611 You don't need to instantiate both `MDCList` and `MDCDrawer`. In the case of permanent drawer like the one in the codelab, you only need to instantiate `MDCList`. In the case of dismissible and modal drawers, you instantiate `MDCDrawer` and it takes care of instantiating the list. See the [MDC Drawer](https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer#javascript-instantiation) documentation on JS instantiation.

@Zeni241 RE the error you're getting, the way to consume MDC Web components is slightly different when relying on CDN or `dist/*.js`, whereas the codelab instructions assume direct consumption of ES modules.

Instead of this:

```js
import {MDCList} from '@material/list';
new MDCList(...);
```

You will do this:

```js
new mdc.list.MDCList(...);
```

See [importing the JS component](https://github.com/material-components/material-components-web/blob/master/docs/importing-js.md) for more information.

**Comment by Zeni241** [comment]
Thanks @kfranqueiro your reply solved the MDCList problem. If you can please also tell what is the alternate of code bellow as now I am stuck at [next page](@include mdc-image-list-standard-columns(4);)  
`@import "@material/image-list/mdc-image-list";`
and 
`@include mdc-image-list-standard-columns(4);`

I would humbly suggest to make available  **version of these tutorials for CDN users** as not everyone is using SASS and Node.

**Comment by abhiomkar** [comment]
@Zeni241 Unfortunately there is no easy way to customize the image list with given column size without using Sass or some sort of custom CSS.

You can extract the CSS styles [defined in above mixin](https://github.com/material-components/material-components-web/blob/71a118043884cc8f2da431df6a9f1be3b94fdf0e/packages/mdc-image-list/_mixins.scss#L182) and apply to image list item as below:

```css
.mdc-image-list__item {
  width: calc((100% / 4) - (4px + 1px) / 4);
  margin: calc(4px / 2);
}
```

**Comment by Zeni241** [comment]
Thanks @abhiomkar. 
I thinks I better wait till there is some series of tutorial for CDN users . For me CDN is much less time consuming and viable option even if I couldn't do everything in it.
Till then OnsenUI with pure javascript...

**Comment by abhiomkar** [comment]
Thanks for the feedback! We're considering to improve our documentation with inline code samples & demos which might help avoid any confusion.
