### ISSUE TITLE
MDC complete typescript ES6 Modules

### ISSUE THREAD

**Issue by gertcuykens** [material-components/material-components-web#4570]
Trying instead of using the complicated webpack setup to push es6 modules forward

related to issue: https://github.com/material-components/material-components-web/issues/4507

attempt to fix it: https://github.com/gertcuykens/mdc-dialog

Run `index.sh`, use `http-server` and go to `dist/`

MDC relies on many non es6 modules making it a serious handicap to write decent es6 code. Managed to rewrite a few dependencies to be modules but I realize now that this node module webpack rabit hole is much worse than I thought.

**Comment by abhiomkar** [comment]
Thanks for filing the issue!

I assume this is related to packages that depend on non-ES6 modules such as drawer, dialog that depends on CommonJS module including `focus-trap`. Sorry, it is not feasible for us to build pure ES6 modules without migrating all dependencies to ES6 modules.

Please feel free to open a PR at focus-trap that helps migrate to ES6.

Thanks!

**Comment by gertcuykens** [comment]
I understand and there was already a ticket open for it dating way back https://github.com/davidtheclark/focus-trap/issues/30 For years we are in this webpack node module backward compatibilty mess. Was hoping more people would understand that to get out of this webpack mess is to fork every dependency that is still not a es6 module instead of waiting. The good news is does dependency are small code bases. The bad news nobody cares enough to just do it even if 90% of MDC is already es6.
