### ISSUE TITLE
textfield: how to get updated property

### ISSUE THREAD

**Issue by XHMM** [material-components/material-components-web#4574]
When I changed `valid` property as below, I cannot get correct value anymore. I have to use the protected methods to get correct value. I wonder whether I had a wrong usage and how to get updated value ?

```
const mdcEndTime = new MDCTextField(rdom('#activityEndTime'))
mdcEndTime.valid = false
console.log(
  mdcEndTime.valid, // true
  mdcEndTime.getDefaultFoundation().isValid(), // true
  mdcEndTime.foundation_.isValid(), // true
  mdcEndTime.foundation_.isValid_ // false
)
```

**Component:**  TextField
**Version**: 1.1.0
**UA**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36`
**OS**: Win10

### What is the expected behavior?
`mdcEndTime.valid` return false
### What is the actual behavior?
`mdcEndTime.valid` returned true

**Comment by abhiomkar** [comment]
You might need to set `useNativeValidation` to `false` for custom validations, MDCTextField uses native input validation otherwise.

**Comment by XHMM** [comment]
@abhiomkar When I set `useNativeValidation=false`，it seems that all builtin validations not worked any more such as onblur event, so I have to handle all circumstances. So is there  no way to combine builtin validation and custom validation together ?

**Comment by abhiomkar** [comment]
TextField's `.valid` API can be used to read native or custom validation based on the boolean flat that you set using `.useNativeValidation`. If you still need native validation you can use input element's DOM API `inputEl.validity.valid`.

**Comment by XHMM** [comment]
Thanks for your remind😁, I forget I can use native apis.
