### ISSUE TITLE
only show copyright notification once in the minified version approx. 33% size reduction

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#4580]
## Feature Requests

only show copyright notification once in the minified version 
material-components-web.min.js

in the 1.1.1 release it is is around 3000+ lines of repeated strings.
464KB in release version.
without the repeated notice the release would be 295 KB
that is probably one of the biggest minification improvements you can get with 1 fix! 

## potential solution

the @license should only be used on the main entry license notification - then the issue would eventually be solved by the default settings from webpack / terser.

:-)

**Comment by cintaccs** [comment]
Maybe this could be configured (the build process including TypeScript etc. is beyond what I can follow - but as I understand WebPack is used):

extractComments
Type: Boolean|String|RegExp|Function<(node, comment) -> Boolean|Object>|Object Default: false

Whether comments shall be extracted to a separate file, (see details). By default extract only comments using /^\**!|@preserve|@license|@cc_on/i regexp condition and remove remaining comments. If the original file is named foo.js, then the comments will be stored to foo.js.LICENSE. The terserOptions.output.comments option specifies whether the comment will be preserved, i.e. it is possible to preserve some comments (e.g. annotations) while extracting others or even preserving comments that have been extracted.

https://webpack.js.org/plugins/terser-webpack-plugin/

**Comment by cintaccs** [comment]
in other words - it looks like the default behaviour is to preserve all:
 * @license
which is currently repeated in the 3000 lines for each single instance. Without preserving the @license - all the comments would be removed - then a general overall copy right notice could be added to the top with gulp concat or something similar.

OR the @license should only be used on the main entry license notification - then the issue would eventually be solved by the default settings from webpack / terser.

**Comment by abhiomkar** [comment]
Thanks for filing this issue with more information!

I'm marking this as dup of #4220 - please follow this bug for future activity.
