### ISSUE TITLE
Checkbox ripple mixin doesn't allow customization

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#4597]
Expected use of `@mixin mdc-ripple-radius-unbounded` with the checkbox is:
```
.mdc-checkbox {
  @include mdc-ripple-radius-unbounded(50%);
}
```

This however doesn't work, since the JS checkbox progamatically creates CSS vars and puts them on the element. This overrides the sass mixin, which stops this from working. 

Example:
https://glitch.com/edit/#!/fishy-course?path=index.scss:5:7

**Comment by abhiomkar** [comment]
This might be related to #4530 (as per Density work).

**Comment by moog16** [comment]
Not sure if the change allows us to break the ratio between size of checkbox and radius of unbounded ripple. It looks like we can change the size of the checkbox, but what if we want to make the ratio of the ripple size larger/smaller?

**Comment by abhiomkar** [comment]
PR #4697 fixes this?
