### ISSUE TITLE
MDCSelect dense variant

### ISSUE THREAD

**Issue by cmath10** [material-components/material-components-web#4613]
## Feature Requests
More question than request, so...

In official guidelines described dense variant of form fields:
[Filled text field](https://material.io/design/components/text-fields.html#filled-text-field)
[Outlined text field](https://material.io/design/components/text-fields.html#outlined-text-field)

MDCTextField has dense variant, but in MDCSelect this variant still not implemented. Is dense variant planned?

**Comment by abhiomkar** [comment]
The dense variant in [MDCTextField is being deprecated](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#deprecation-notice). There are no plans for dense variant of MDCSelect as of now.

We're forecasting that dense variants may be added across all components in future.
