### ISSUE TITLE
Text field input overlaps icon when there is no label

### ISSUE THREAD

**Issue by rbare1** [material-components/material-components-web#4617]
### What MDC Web Version are you using?

> v1.1.1

### What browser(s) is this bug affecting?

> Chrome Version 73.0.3683.86

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

> Add a text field with a leading (or trailing) icon and the no-label class
> https://codepen.io/anon/pen/NmyXYp

### What is the expected behavior?

> The input should not overlap the icon.

### What is the actual behavior?

> The input overlaps the icon

### Any other information you believe would be useful?
> https://github.com/material-components/material-components-web/issues/4239 added support for text fields without labels, and always sets the padding to 16px for text fields with the class `.mdc-text-field--no-label`. It should avoid setting left/right padding when a leading/trailing icon is present.

**Comment by abhiomkar** [comment]
Thanks for spotting this! Adding this to our backlog.

PRs are welcome!
