### ISSUE TITLE
[Select] After choosing an element in mdc-select the arrow still points to the top

### ISSUE THREAD

**Issue by mohammadrafigh** [material-components/material-components-web#4618]
### What MDC Web Version are you using?

1.1.1

### What browser(s) is this bug affecting?

All

### What OS are you using?

Ubuntu

### What are the steps to reproduce the bug?

> 1. Go to https://codepen.io/anon/pen/mgxvKR
> 2. Choose an item
> 3. You can see the arrow is still pointing to the top

### What is the expected behavior?

the arrow should be depended to the visibility of the menu (options) and not the focus status of the select element.

### What is the actual behavior?

The arrow is pointing to the down.
![Screenshot from 2019-04-17 21-28-10](https://user-images.githubusercontent.com/6737508/56308118-bf3ee880-615b-11e9-9467-c20172a7bf2b.png)

**Comment by abhiomkar** [comment]
Demo server is obsolete and no longer maintained. Please run `npm run start` that starts web server on port `8080` to see updated demos, these are also used for screenshot testing.

**Comment by mohammadrafigh** [comment]
I don't know why you closed this issue. My problem is not with demo server. My problem is with mdc-select behavior which still is wrong in the examples in website and in my own app!

**Comment by abhiomkar** [comment]
I'm sorry. Since you mentioned demo server I assumed you're referring to the demo server in our repository.

Can you please upload your example that has this issue? I'm not able to reproduce this bug in our catalog.

Thanks!

**Comment by mohammadrafigh** [comment]
added a code pen to the descriptions of the issue.

1. select an option
2. see the arrow of mdc-select is still pointing to the top

**Comment by abhiomkar** [comment]
Thanks for the attaching the example!

Seems like a bug. Adding this to our backlog.
