### ISSUE TITLE
Mention to use normalize.css

### ISSUE THREAD

**Issue by akshaybabloo** [material-components/material-components-web#4628]
I think it will be useful to mention in the documentation to use something like `normalize.css` for the components to render correctly for the newbies at least.

**Comment by moog16** [comment]
@akshaybabloo we purposely do not advocate using other libraries like `normalize.css`. Deciding to use normalize, another library, or a home grown solution is left to the discretion of the app developer. We believe the MDC Components should behave as atomic units unless they are app components (such as dialog, drawer etc.). This means they should behave like the the native elements such as `<input />` or `<button />`.
