### ISSUE TITLE
Width of interactive list with ripple-upgraded is too large.

### ISSUE THREAD

**Issue by h-ikeda** [material-components/material-components-web#463]
### What MDC-Web Version are you using?

> v0.7.0

### What browser(s) is this bug affecting?

> Chrome Version 56.0.2924.87 (64-bit)

### What OS are you using?

> Windows 7 Service Pack 1

### What are the steps to reproduce the bug?

> At https://material-components-web.appspot.com/list.html
> The list items of "Interactive Lists (with ink ripple) " escape from "nav" container.

### What is the expected behavior?

> Width of list items ("a") is "nav" container's width + 32px.

### What is the actual behavior?

> Padding of list items is 16 + 16 = 32px, so width of list items should be container's width - 32px.

**Comment by traviskaufman** [comment]
Thanks for reporting @h-ikeda 

Looks like the issue is with this line: https://github.com/material-components/material-components-web/blob/master/packages/mdc-list/mdc-list.scss#L165.

It seems to me that we should just make this `width: 100%`. Definitely willing to accept a PR for this fix! 😄
