### ISSUE TITLE
[Button] Add "fill: color" to disabled button

### ISSUE THREAD

**Issue by maracuja-juice** [material-components/material-components-web#4631]
## Feature Requests

When using SVG icons in Buttons the CSS attribute `color` doesn't change the actual color of the SVG icon. Therefore an icon is not greyed out correctly when used with a disabled button. See demo below:

![image](https://user-images.githubusercontent.com/16801528/56497192-df283080-64fc-11e9-98dd-d59fa6a42086.jpeg)

(there is a white icon on the `Next` button that should be greyed out)

I suggest that additionally to the `color` attribute that there is the `fill` attribute that would add the same color.

So instead of this:
![image](https://user-images.githubusercontent.com/16801528/56497323-5a89e200-64fd-11e9-8b8e-e1af32e314ea.jpeg)

There would be this CSS:
![image](https://user-images.githubusercontent.com/16801528/56497336-65447700-64fd-11e9-9e10-d342467638eb.jpeg)

This would produce my expected output for the disabled button icon:
![image](https://user-images.githubusercontent.com/16801528/56497382-96bd4280-64fd-11e9-9200-9ec8fbe3e9b3.jpeg)

**Comment by jamesmfriedman** [comment]
This issue is what originated https://github.com/material-components/material-components-web/issues/4633

**Comment by maracuja-juice** [comment]
Also the `fill` property is missing in a few other places. (Card Action Buttons for example)

**Comment by abhiomkar** [comment]
I'm not able to reproduce this issue. am I missing something?

[Demo of disabled button](https://glitch.com/edit/#!/meadow-position?path=index.html:18:21) on glitch.

**Comment by jamesmfriedman** [comment]
In your demo you're specifying a fill for the svg which is whats taking precedence

**Comment by abhiomkar** [comment]
I'm not sure if I understand the issue. The original issue says that the svg color isn't changing when button is disabled, but I couldn't repro this.

The fill style property is applied to `mdc-button__icon` block element which is the svg element. Can you please share a demo for investigation?

**Comment by jamesmfriedman** [comment]
I double checked the code and you are correct. @maracuja-juice put together a repro using rmwc and it does appear to be working as intended. I'll leave this to you guys, but it seems invalid to me. https://codesandbox.io/s/ywlnkjnmpx

**Comment by maracuja-juice** [comment]
We discussed this some more and it actually seems to be an RMWC bug instead.

**Comment by jamesmfriedman** [comment]
Yep, rmwc is rendering an svg inside of an i tag instead of the svg being the root node of the icon.
