### ISSUE TITLE
MDCTabScroller - Determining the scrollbar height only intermittently works.

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#4642]
In the mdc-tab-scroller package, the util.computeHorizontalScrollbarHeight function determines if the document adds a scrollbar to scrollable elements and then attempts to compute the height of the scrollbar so it can offset it using margin-bottom. This function does not work consistently resulting in the scrollbar showing in some cases, but disappearing when refreshed.

**Comment by moog16** [comment]
- related to https://github.com/material-components/material-components-web/issues/4643
- might need a raf

**Comment by abhiomkar** [comment]
Closing this one to track this bug in #4648

**Comment by szTheory** [comment]
I'm also seeing this issue
