### ISSUE TITLE
[Suggestion] MDCSelect: Add mdc-select--no-label variant

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#4645]
Like MDCTextField, MDCSelect should not require a label

### What MDC Web Version are you using?

> 1.1.1

### What is the actual behavior?
> A padding remains if the label is removed, see the screenshot

![imagen](https://user-images.githubusercontent.com/11841575/56693479-2c95d080-66aa-11e9-864f-484df382db15.png)

**Comment by moog16** [comment]
@Darhakexge I believe what you're saying is that the blue outlined area you have in the screenshot above should not exist? And instead should be collapsed?

**Comment by Darhakexge** [comment]
Yes, it is exactly that
