### ISSUE TITLE
Using MDC with native ES6

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [material-components/material-components-web#4651]
Hello,

I am running a few web apps in native ES6, using Chrome. Arrow functions, imports and whatnot...

My question is, can I somehow use the un-webpacked, un-transpiled MDC directly in the browser?

**Comment by moog16** [comment]
When you say un-transpiled, are you asking about the TypeScript source code? For that you would need to download our source files from Github directly and use those.

**Comment by bjorn-ali-goransson** [comment]
Well typescript would need transpiling to es6 to run natively in chrome. So
I understand that I'd need to roll my own. Thanks.

Den fre 26 apr. 2019 19:39Matt Goo <notifications@github.com> skrev:

**Comment by moog16** [comment]
Correct, so I'm wondering what you mean by un-transpiled and running directly in the browser. We have transpiled code, and link directly to the browser using a CDN through [unpkg](https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js). Is this what you're looking for?

**Comment by bjorn-ali-goransson** [comment]
Well no... Almost. As chrome is fully (?) ES6 capable nowadays, I'm not
looking for code that is transpiled to ecmascript. It just feels
suboptimal, catch my drift?

Den fre 26 apr. 2019 20:43Matt Goo <notifications@github.com> skrev:

**Comment by moog16** [comment]
Sorry, I'm not sure if I do. We have non-transpiled TypeScript code, and transpiled ES code. Suboptimal in what way?

**Comment by bjorn-ali-goransson** [comment]
Sorry, I won't be long on this. I'm writing an application in es6 that is
run natively on Chrome, without transpiling it. So then it would seem nice
to me to also run this script without having it transpiled away from es6.

But then again I may be rewriting the application to typescript so we'll
see exactly what I'll end up doing.

Thanks a lot!

Den mån 29 apr. 2019 18:38Matt Goo <notifications@github.com> skrev:

**Comment by moog16** [comment]
I would still use the transpiled code. I see what you're saying, since it's not written in the same syntax as your source. It will work and behave the same. Closing as this issue is solved. If you have any further questions please continue to use this.
