### ISSUE TITLE
How to integrate chips into an mdc-textfield?

### ISSUE THREAD

**Issue by i-am-the-slime** [material-components/material-components-web#4669]
I am trying to create an input field with chips as per material design but I'm failing to put the chips into an `input` (think gmail recipient input).

Is this supported at all? I see that there are input chips but I don't see an example of putting them into an input. Is the trick for this to have multiple inputs?

**Comment by moog16** [comment]
We currently do not have a working demo of this, but technically an `<input />` cannot have a chip element (divs). Just off the top of my head, try placing the `.mdc-chips` element and the`.mdc-text-field` element within a wrapper div. Make the wrapper div element position relative, and the `.mdc-chips` position absolute. 

Please see example [codepen](https://codepen.io/moog16/pen/ROXGQQ). NOTE: UI looks broken, but should point you in the right direction.

**Comment by i-am-the-slime** [comment]
Wow, thank you very much for the comprehensive and swift reply.

**Comment by jimmyhdolores** [comment]
Any demo for this?
