### ISSUE TITLE
Improve accessibility by use HTML tags and attributes to styling instead of class name!

### ISSUE THREAD

**Issue by OmidHekayati** [material-components/material-components-web#4670]
It is always a question for me why we don't have any CSS library that works in the semantic markup HTML in web UI world!! In this way we just need (or force!!) to write (or improve) our HTML code to right semantic and accessible architecture to use proper design languages like material! For example why we need to add ```class="mdc-button"``` to ```<button>``` standard tag to style standard button in material or other design language class! or add ```class="mdc-tab"``` to the element that we must add ```role="tab"``` to have properly accessible website! and much more tags and attributes that can use instead of class!!

We use this idea in our new opensource project that finds here. Can we have hope one-day this way styling be standard or you think we will face problems in this development architecture?
https://github.com/SabzCity/www.sabz.city/blob/master/assets/widget-localize/design-language--material.js

Also in this way browsers or developers can change website design language defaults in an easy way by something like this style tag without need to change any HTML markup code!
```css
body {
    -webkit-design-language: "material";
    design-language: "material"; /*maybe some day get standard tag!! ;) */
}
```

**Comment by moog16** [comment]
Interesting idea! However currently in today's dev environment using classes to style is best practice and a common pattern. Using attributes and tag properties for styling will not work for everyone, and therefore break many of our customers/clients. We do not intend to switch from this practice. I think if this practice works for you then by all means keep on keeping on!
