### ISSUE TITLE
Select component contains extra option

### ISSUE THREAD

**Issue by dessant** [material-components/material-components-web#4671]
The basic and enhanced Select component contains an empty option that is not part of the spec. The menu guidelines have several examples of the widget, including on desktop, none of which indicate that an extra option should be present.

The current implementation of the component does not seem to appear in previous versions of the guidelines either. Has the component been implemented based on an unpublished specification?

![](https://user-images.githubusercontent.com/7513068/57075337-2e394700-6cef-11e9-938e-5624aa9507da.png)

https://material.io/design/components/menus.html#exposed-dropdown-menu

![mio-design_assets_1RABVLpsjAjSPIarQDmDYMnN1tH6zs8-b_select-behavior-filled](https://user-images.githubusercontent.com/7513068/57075741-537a8500-6cf0-11e9-9ddc-5e6d1cbbfc48.png)

![mio-design_assets_1rL2xG7X_c0Hd81tlCPpo0puWwT68z_Nt_select-intro](https://user-images.githubusercontent.com/7513068/57075751-5b3a2980-6cf0-11e9-9597-2493867218ef.png)

**Comment by moog16** [comment]
@dessant no the select is based off of the spec you referenced. Having an empty option is a native `<select />` feature. In the case that the select is not required, a user should be able to select a value, and then unselect the select. 

Designers cannot cover every use case in their mocks, and must defer to the engineers to make these technical feature decisions. If you don't need the empty option, you can remove it from your application/webapp.

**Comment by dessant** [comment]
I understand the tradeoffs that have to be made during implementation, but this feature was not added because of a platform limitation. It introduces a new experience within the component that should likely be discussed with the UX team, and reflected in the guidelines.

> In the case that the select is not required, a user should be able to select a value, and then unselect the select.

The extra option in the native component cannot be selected for the value to be cleared, the option is always disabled.

**Comment by moog16** [comment]
Reopening issue as I didn't get to discuss with the rest of the team.

**Comment by williamernest** [comment]
The empty option is included in the native `select` element as a means of clearing a select that may not be required. The spec doesn't explicitly show this use case, but it is a valid use case that we considered when implementing the component. If a developer wants to achieve the exact UX that spec shows, they can do so with this component by not including an empty option.

This feature was discussed with the UX team, and it was deemed to be common platform pattern/behavior and should be included in our component.

**Comment by dessant** [comment]
The feature is useful, and it appears to be important enough to be added to the default [examples](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select) in the docs, not as a variation. It's also possible that the same pattern for clearing the data is reusable on other platforms. Do native Android or Flutter components have a way to reset the selected option?

If it is a common pattern, it may make sense to mention it in the guidelines. There are other component frameworks implementing Material Design or being inspired by it, and it would benefit both developers and users to recommend a UI pattern for resetting the state of the component, otherwise every implementation will attempt to deal with the issue on their own. For example, Vuetify adds an X button next to the selected value if the component is configured to be clearable.

Btw, the example for the basic Select component adds a disabled option that cannot be used to clear the selected option, the issue is also present in the [demo](https://material-components.github.io/material-components-web-catalog/#/component/select).

**Comment by williamernest** [comment]
It is a common pattern for the web, since our components attempt to implement the spec but also maintain flexibility for the platform. I'm not sure what the guidance is for other platforms, but this is what is very common for the web. 

The disabled option is another common pattern on the web to show a select without a selected option, but now allow an empty option to be selected after a selection is made. 

Overall, the goal is to build components that can implement material design, but also allow enough flexibility to fit many use cases common to the individual platform. Although material design strives to provide guidelines for many use cases, it does not attempt to cover every use case for every platform.

**Comment by abhiomkar** [comment]
As @williamernest stated in his previous comment, Select component can be rendered without an empty option in dropdown (See [demo](https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2019/02/11/21_55_33_374/spec/mdc-select/classes/enhanced-baseline.html)).

We'll consider updating our catalog demos with this example. Closing this issue.
