### ISSUE TITLE
.mdc-snackbar__action doesn't respect color variables

### ISSUE THREAD

**Issue by KayvandenHeuvel** [material-components/material-components-web#4699]
### What MDC Web Version are you using?

2.1

### What browser(s) is this bug affecting?

all browsers

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

[https://material-components.github.io/material-components-web-catalog/#/component/snackbar]

Visit the demo page and you'll see that the button inside the snackbar does not respect the color variable theming.

### What is the expected behavior?

`color: #6200ee;
color: var(--mdc-theme-primary,#6200ee) `

### What is the actual behavior?

It's :not(disabled) form has an hardcoded color:
`    color: #bb86fc;`

**Comment by Johnniey** [comment]
I think the predefined color (`#bb86fc`) is just a lighter version of the default purple, there's currently no way to define the primary color for light/dark surfaces. We could simply change the variable to lighten/dark the primary color, but I don't know if that is allowed (as this won't work well with all colors).

This code changes the color to a lighter/darker version of the primary:
`$mdc-snackbar-action-ink-color: mix(mdc-theme-prop-value(primary), if(mdc-theme-contrast-tone($mdc-theme-primary) == "dark", #000, #fff) , 75%) !default;`

For now you can simply overwrite the `$mdc-snackbar-action-ink-color` variable with the a different color that works well with your primary color.

**Comment by abhiomkar** [comment]
We do not fully support CSS variables since we rely on sass functions like `mix()`, `rgba()`.

I'm marking this as dup of #4709

**Comment by KayvandenHeuvel** [comment]
@abhiomkar I know mdc relies on sass functions, but it looks like this button does not have a theming color.

We have changed the mdc-theming colors but this button stays purple. So now we have to override this button color like @Johnniey mentioned.

**Comment by abhiomkar** [comment]
My bad. I thought the original issue was about CSS variables. That’s right, we can override the button color using $mdc-snackbar-action-ink-color variables as mentioned by @Johnniey mentioned in his previous comment. 

Please feel free to re-open the issue if you still think there is a bug.
