### ISSUE TITLE
Feature Request MDCSelect: Consider splitting select into native and enhanced packages

### ISSUE THREAD

**Issue by suneelv** [material-components/material-components-web#4700]
Thank you for the amazing library. 

I would like to propose a feature request regarding mdc-select package. 
Currently you support a native select element and a fully enhanced select element. But if we want to use only the native select component in an app,  we will get all the javascript for enhanced select too (this includes other packages like menu, list). 
https://bundlephobia.com/result?p=@material/select@2.0.0

When we include mdc-select javascript, this is what we see with BundleAnalyzer plugin (More than 15kb gzip being added because of the select package). 
![image](https://user-images.githubusercontent.com/6492948/57513214-04df7300-730e-11e9-8d92-aa361151ac02.png)
This is fine if we are using enhanced select component, but this is bad for developers who just want to use native select.

Here's a screenshot without mdc-select javascript being included
![image](https://user-images.githubusercontent.com/6492948/57513356-525be000-730e-11e9-8a44-7a5075eaa3de.png)

So if its possible, please consider splitting this component into two packages, where native select component gets minimal javascript.

**Comment by abhiomkar** [comment]
We're refactoring select to select to only include enhanced version. Please see #4993 for updates.
