### ISSUE TITLE
Issue is back again (Chrome 74 MDC ) - Black hover over list item with checkbox #4629

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#4714]
## Bug report
shows black on hover on List with Checkbox - as in previously closed issue #4629 

### Steps to reproduce
https://material-components.github.io/material-components-web-catalog/#/component/list
hover over 
List with Trailing Checkbox

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |2.2.0
| Browser          |Chrome 74
| Operating System | Win10

**Comment by cintaccs** [comment]
https://github.com/material-components/material-components-web/issues/4629#issuecomment-487366408

workaround provided earlier seems still to work

**Comment by abhiomkar** [comment]
We haven't got chance to update MDC Web version in our catalog site.

I couldn't reproduce this with latest version (v2.2.0), demo here from our screenshot test:
https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/05/10/14_25_41_111/spec/mdc-list/classes/checkbox.html?utm_source=golden_json

**Comment by cintaccs** [comment]
I have it in my own application - on a list with checkboxes (list item has trailing icons). However now it seems to be gone again...

**Comment by cintaccs** [comment]
for whatever reason unclear to me - it goes black at the same as

**Comment by cintaccs** [comment]
As I can't reproduce consistently I am ok if you close the issue. It might be a Chrome issue with some sort of HW acceleration that is not solid.
However the implementation is maybe not super solid (the workaround provided seems to be...).

**Comment by cintaccs** [comment]
btw: thanks for fast response!! 👍

**Comment by cintaccs** [comment]
The issue occurs again when the browser is performance stressed.... whatever I mean with that.... quickly opening and closing items and moving around will suddenly trigger the issue back again.

**Comment by abhiomkar** [comment]
Can you please confirm if you're able to reproduce it on this test page?
https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/05/10/14_25_41_111/spec/mdc-list/classes/checkbox.html?utm_source=golden_json

**Comment by cintaccs** [comment]
> Can you please confirm if you're able to reproduce it on this test page?
> https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/05/10/14_25_41_111/spec/mdc-list/classes/checkbox.html?utm_source=golden_json

I can't reproduce with that test page.

After a few days - the issue is coming and going. It must be related to something else breaking the CSS somehow - but the only difference I see when the issue occur is that the hover gets black on that specific list with checkboxes and the tab bar 

.mdc-tab-indicator .mdc-tab-indicator__content--underline {
border-color: orange;
border-top-width: 3px;
}

is no longer in effect.

It might be my implementation breaking things.... I will close the issue - I can re-open if I can consistently reproduce it.
