### ISSUE TITLE
[Tooltip] Font size for desktop web application is too small

### ISSUE THREAD

**Issue by atiris** [material-components/material-components-web#4723]
## Bug report

Recommended font height 10 px [for desktop](<https://material.io/design/components/tooltips.html#spec>) is too small.

### Steps to reproduce

1. Go to https://material.io/design/components/tooltips.html#spec
2. Ask for user feedback to read text within the tooltip using desktop settings.

### Actual behavior

I created web application for desktop that follows the material principles for tooltips. App users complain to me about a small and hard to read font.

### Expected behavior

The tooltip font is well readable for most users. Tooltip is presented visually mainly by frame and background, not by small (difficult to read) font.

### Screenshots

In documentation

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web | 2.2.0 Tooltip |
| Browser | Latest Chrome |
| Operating System | Linux Fedora 29 64bit |

### Additional context

Please, if you have any study that confirms that the appropriate font size for the desktop tooltip is 10 px, can you refer me to it?

### Possible solution

Increase recommended font size, eliminate specific font size for tooltip, or set it in proportion to the basic font size.

**Comment by atiris** [comment]
Now i'm not sure if I wrote this request in a good repository :roll_eyes:
Is "desktop" [in documentation](<https://material.io/design/components/tooltips.html#spec>) equivalent to [web](<https://github.com/material-components/material-components-web>) here?

**Comment by abhiomkar** [comment]
Please note that MDC Web doesn't have Tooltip component implemented. Are you suggesting a change in design spec?

**Comment by atiris** [comment]
Yes, my proposal concerns general design as [described here](<https://material.io/design/components/tooltips.html#spec>). Apparently I used the wrong github repo to enter this request. Can you advise me where to put it? If I follow a link from documentation (github at the bottom of the page with tooltips design) it redirects me to this list of all repositories: https://github.com/material-components and I obviously chose the wrong one :smile:

**Comment by abhiomkar** [comment]
Seems like you've already opened but at https://github.com/material-components/material-components/issues/56

Closing this one :)

**Comment by atiris** [comment]
Yes, I would close it myself, I just waited to confirm it was the right repository. I'm still not sure about it :smile: .
