### ISSUE TITLE
[MDCTextField] throws an error when its value is set to null

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#4724]
### Steps to reproduce
See the [codepen](https://codepen.io/Darhakexge/pen/NVjxZX)

### Screenshots
![Captura](https://user-images.githubusercontent.com/11841575/57869415-9c3f3d00-77ca-11e9-9fe7-9c4f55e53ca1.PNG)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 2.2.0
| Browser          | All
| Operating System | Windows 10

**Comment by abhiomkar** [comment]
TextField's value only supports string type. In this case we suggest setting the value to empty string (`''`) instead of `null`.
