### ISSUE TITLE
Extend MDCComponent to be aware of wrapper components

### ISSUE THREAD

**Issue by zoofadoofa** [material-components/material-components-web#4727]
## Feature Request

Extend MDCComponent to allow wrapper components or shadow dom to disjoint eventing and mutation observations. At the moment events end up needing to be rewired when a mdc component gets wrapped because the listeners are pointing to the wrong element in hierarchy.

### Proposed solution

Add a host_ property to MDCComponent that can optionally be passed into the constructor
`new MDCComponent(root, host?, foundation?);`
listen, unlisten, and emit methods use host_ instead of root_.

When host is not passed in, in MDCComponent we assign Root to Host and everything works the same.
So by default **Root** is **Host** unless overridden

### Alternatives considered

This will be a breaking change to how the constructor is used `new MDCComponent(root, host?, foundation?);` However, it is necessarily to insure host_ will be initialized in Foundation the same way root_ is.

### Additional context

I built a very detailed demo that shows the problem and shows the solution.
[Stackblitz Demo](https://stackblitz.com/edit/mdc-base-host-root?file=index.html)
[Diagram of architecture](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggTFJcbnN1YmdyYXBoIENvbXBvbmVudFxuc3ViZ3JhcGggU2hhZG93IFJvb3QgJ0lzb2xhdGVkJ1xucm9vdFtSb290IEVsZW1lbnRdXG5lbmRcbmhvc3RbSG9zdCBFbGVtZW50XVxuZW5kXG5jaGlsZFtDaGlsZCBFbGVtZW50XVxucGFyZW50W1BhcmVudCBFbGVtZW50XVxuXG5yb290IC0tPnwgRGlzam9pbnRlZCBFdmVudCBMaXN0ZW5pbmcgfCBob3N0XG5yb290IC0tPnwgRGlzam9pbnRlZCBBdHRyaWJ1dGUgT2JzZXJ2aW5nIHwgaG9zdFxuY2hpbGQgLi0-fCBFdmVudCB8IGhvc3RcbnBhcmVudCAtLT58IFNldC9SZW1vdmUgQXR0cmlidXRlIHwgaG9zdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

summary of code changes for those who don't have time for demo:
```typescript
import { MDCFoundation, CustomEventListener, EventType, SpecificEventListener} from '@material/base';

export class MDCComponentModified<FoundationType extends MDCFoundation> {
  static attachTo(root: Element, host?: Element): MDCComponentModified<MDCFoundation<{}>> {
    return new MDCComponentModified(root, host, new MDCFoundation({}));
  }

  protected root_: Element;
  protected host_: Element; //(zoofadoofa): new property for disjointing
  protected foundation_: FoundationType;

  constructor(
      root: Element,
      host?: Element,
      foundation?: FoundationType,
      ...args: Array<unknown>
  ) {
    this.root_ = root;
    //(zoofadoofa): here we want to check if host was defined.
    // in cases where its undefined we assign root to host 
    // so eventing still works the way we expect.

    this.host_ = host !== undefined && host instanceof Element ? host : this.root_;
    this.initialize(...args);
    //(zoofadoofa): now we initialize this.host_ as well 
    //so that it can be used in the foundation class. just like this.root_
    this.foundation_ = foundation === undefined ? this.getDefaultFoundation() : foundation;
    this.foundation_.init();
    this.initialSyncWithDOM();
  }

  initialize(..._args: Array<unknown>) {

  }

  getDefaultFoundation(): FoundationType {
    throw new Error('Subclasses must override getDefaultFoundation to return a properly configured ' +
        'foundation class');
  }

  initialSyncWithDOM() {

  }

  destroy() {
    this.foundation_.destroy();
  }

  listen<K extends EventType>(evtType: K, handler: SpecificEventListener<K>): void;
  listen<E extends Event>(evtType: string, handler: CustomEventListener<E>): void;
  listen(evtType: string, handler: EventListener) {
    //(zoofadoofa): listen for events with host instead of root
    this.host_.addEventListener(evtType, handler);
  }

  unlisten<K extends EventType>(evtType: K, handler: SpecificEventListener<K>): void;
  unlisten<E extends Event>(evtType: string, handler: CustomEventListener<E>): void;
  unlisten(evtType: string, handler: EventListener) {
    //(zoofadoofa): listen for events with host instead of root
    this.host_.removeEventListener(evtType, handler);
  }

  emit<T extends object>(evtType: string, evtData: T, shouldBubble = false) {
    let evt: CustomEvent<T>;
    if (typeof CustomEvent === 'function') {
      evt = new CustomEvent<T>(evtType, {
        bubbles: shouldBubble,
        detail: evtData,
      });
    } else {
      evt = document.createEvent('CustomEvent');
      evt.initCustomEvent(evtType, shouldBubble, false, evtData);
    }
    //(zoofadoofa): dispatch events with host instead of root
    this.host_.dispatchEvent(evt);
  }
}
```

**Comment by moog16** [comment]
@zoofadoofa if you want to use MDC Web with the Shadow DOM, we have another repo https://github.com/material-components/material-components-web-components. This repo is built with Web Components which utilizes the Shadow DOM. 

Does this work for you?

**Comment by zoofadoofa** [comment]
I already work in that repo and have made [PRs](https://github.com/material-components/material-components-web-components/pull/254).

This isn't just an issue with shadow dom. the same would apply for Angular, React, Vue, and any library that attempts to consume MDC by wrapping the MDC components.

by not having a host property within MDC components every library has to duplicate work that has already been done by the MDC component itself.

**Comment by moog16** [comment]
@zoofadoofa I'm not sure what you mean by disjointing. I've seen the stackblitz you created. However can't you create some logic within your ShadowDom accordion-original to keep track of the expanders? 

Also MDC Web provides the foundation/adapter for you to wrap to create components. The MDC Web components are not really designed to be wrapped again, even though there are a lot of people doing this.

**Comment by zoofadoofa** [comment]
@moog16 there is always the option to duplicate code to make it work in a wrapper.
but to your second point the reason people are wrapping the MDC components is because MDC does not provide the template as a part of the components. So these other libraries and frameworks provide the template while trying not to modify the logic and styles that are provided.

I'm not saying its unavoidable, at some point a wrapper will have concerns the only the wrapper cares about. I agree that in those cases the component layer should be rewritten.

But adding the exact same code that a MDC Component already provides just because its pointing to the wrong element. that's the part that I don't understand.

If the MDC Component is aware that it can be wrapped. then it prevents (n) number of libraries from duplicating the same component layer.

**Comment by zoofadoofa** [comment]
updated title to clarify the discussion taking place

**Comment by zoofadoofa** [comment]
@moog16 I'm okay if the answer is MDC Component Layers should not concern itself with quality of life for consuming libraries. I just wanted to see if my feedback was of interest. As I have consumed MDC in roughly 6+ frameworks at this point and its always the same set of rewrites.

If you feel there is nothing to be gained from extending the component layer then feel free to close the issue.

**Comment by moog16** [comment]
@zoofadoofa I appreciate the recommendation, but this change would be a larger architectural change. It would require a lot of time to actually get this in place. I don't think we have the bandwidth to address something like this at this time. Thank you
