### ISSUE TITLE
[mdc-slider] Replace cumbersome track marker (discrete tick marks) logic with simple background style ruleset

### ISSUE THREAD

**Issue by jonjohnjohnson** [material-components/material-components-web#4729]
Not so much a bug, as an optimization...

You can remove most/all the logic of your `appendTrackMarkers`, `removeTrackMarkers`, & `setLastTrackMarkersStyleProperty` code by simply using background style like this...

```css
.mdc-slider--discrete.mdc-slider--display-markers .mdc-slider__track-marker-container {
  --mdc-slider-tick-count: 50;
  --mdc-slider-tick-width: 2px;
  background:
    linear-gradient(
      to right,
      var(--mdc-theme-secondary, #018786) var(--mdc-slider-tick-width),
      transparent 0)
    0px center /
    calc((100% - var(--mdc-slider-tick-width)) / var(--mdc-slider-tick-count))
    100% repeat-x
  ;
```
This way you don't need to hack a layout with a flex container that has heaps of marker nodes, a negative `margin-left` value, and your `.mdc-slider__track-marker-container:after` pseudo element to offset its end marker.

**Comment by moog16** [comment]
@jonjohnjohnson your proposition sounds enticing! Would you mind opening a PR with these changes?

**Comment by jonjohnjohnson** [comment]
@moog16 I may be able to send an adequate PR soon, but for now, here's that code shoved into fiddle.

https://jsfiddle.net/3bjpx6ch/

It's insanely straightforward, just scoping the min/max/step values into custom properties and, for now, simply hiding all the tick mark elements. 😅

**Comment by moog16** [comment]
Close issue with #4756
