### ISSUE TITLE
Ripple disappeared from button components after update

### ISSUE THREAD

**Issue by prateekbh** [material-components/material-components-web#473]
### What MDC-Web Version are you using?
https://github.com/prateekbh/preact-material-components/blob/master/package.json#L38-L62

### What browser(s) is this bug affecting?
Chrome but may be others as well

### What OS are you using?
mac sierra

### What are the steps to reproduce the bug?
Go to https://prateekbh.github.io/preact-material-components/#/component/button click on `Flat Button with ripple` notice nothing happens
This worked before i updated the versions of mdc

### What is the expected behavior?
Ripple should appear

### Any other information you believe would be useful?
This is the way I import mdc.button.css
https://github.com/prateekbh/preact-material-components/blob/gh-pages/Components/ButtonsPage/ButtonsPage.jsx#L3

**Comment by prateekbh** [comment]
one thing, Ripple is working here:
https://prateekbh.github.io/preact-material-components/#/component/checkbox

**Comment by prateekbh** [comment]
I did some more investigation,
follow these steps:

1.) Goto https://prateekbh.github.io/preact-material-components/#/component/button
2.) Inspect -> remove `<link rel="stylesheet" href="public/app.css">`
3.) Add `style` tag and copy paste the `dist/material-components-web.css` from the published package, hurray Ripple works
4.) Take a pull of `master` of https://github.com/material-components/material-components-web
5.) run npm run build and copy contents of `build/material-components-web.css`
6.) Remove the above `style` tag and from the https://prateekbh.github.io/preact-material-components/#/component/button page
7.) Add a new style tag and paste the contents
8.) Ripple gone again :(

**Comment by yeelan0319** [comment]
It seems like a bug. We will look into it more closely and get back to you soon.

**Comment by traviskaufman** [comment]
Hey @prateekbh 

Turns out that we really don't have the bandwidth right now to prioritize looking into this. However, marking this as `"help wanted"` in case any of our awesome community members want to take a crack at what's going wrong here!

**Comment by talves** [comment]
@prateekbh There may be something wrong with the mdc.button.css copy you are using. I copied over the file from the current `0.8.0` version in my `node_modules` folder and it started to work just fine.

Here is the working plunkr copy
[https://plnkr.co/edit/KnpqXCmTkOaOtee5wqTU?p=preview](https://plnkr.co/edit/KnpqXCmTkOaOtee5wqTU?p=preview)

This was the latest version from `npm` also.

**Comment by prateekbh** [comment]
Deleted my node modules and reinstalled. Works now

Verified, working fine..
