### ISSUE TITLE
Update testing framework

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#4734]
Currently testing framework consists of many different npm packages (>9). By using a testing framework like jasmine/jest, we could reduce the amount of dependency from 9(ish) to 1. This would reduce the amount of context switching when having to go to/from different docs. Also this would reduce the amount of maintenance and overhead that comes with greenkeeper PRs, etc. 

Another huge benefit of updating/fixing tests is that other parts of the team use Jasmine. This would also reduce the context switching cost for team members also contributing to mdc web that need to write tests for their features/bugs.

Lastly the tests take a lot longer than they should to start up. We have to build the entire project before running the tests. Sometimes they take 5 - 10 minutes locally to run once. Also changing one file while debugging/writing new tests takes a while as well (1 - 2 minutes) to see the change be reflected. 

By spending time on this now, we could decrease the ongoing costs associated with slow testing.

Issue Notes:
5/17: (Linux machine)
- Unit test start up: 48 seconds
- Unit test refresh (time it takes for a change from src code to propagate to browser): 27.87 seconds

**Comment by allan-chen** [comment]
Unit tests now use Jasmine framework (select should be done by end of week)
