### ISSUE TITLE
install and usage material-components-web in blazor 3

### ISSUE THREAD

**Issue by ebrahimtorabi** [material-components/material-components-web#4741]
I want to install and use the material-components-web in blazor 3. But unfortunately, there are no sources in this area. Please give me some guidance.
Thank you

**Comment by moog16** [comment]
@ebrahimtorabi What is blazor 3? Is this it https://github.com/aspnet/Blazor? 

I'm not sure how this works, is this a package manager?

**Comment by ebrahimtorabi** [comment]
Hi. Thanks for your follow up. So, I mean asp.net core 3. It can be
installed but it does not work properly.

**Comment by ebrahimtorabi** [comment]
I mean exactly blazor 3 hosted core

**Comment by moog16** [comment]
Sorry, but none of our team is familiar with asp.net, so we're not sure if we can help you. If it anything specific to how the components or styles are used please feel free to open an issue.

**Comment by SamProf** [comment]
> I want to install and use the material-components-web in blazor 3. But unfortunately, there are no sources in this area. Please give me some guidance.

https://github.com/SamProf/MatBlazor

**Comment by ebrahimtorabi** [comment]
Tancks.but it does not work .
