### ISSUE TITLE
[MDCTextField] - Outlined border color should be 38% opacity

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#4743]
The states for the text field component changed in December and no longer have a background color change, and the bottom border does not change color on hover. 

https://material.io/design/components/text-fields.html#filled-text-field

![image](https://user-images.githubusercontent.com/34519388/58115066-19ddc100-7bae-11e9-95f3-0be2506f473f.png)

**Comment by moog16** [comment]
It doesn't show in the spec, but as per the design it background should change 4% on-surface color state layer added. Working as intended.

**Comment by williamernest** [comment]
So there should be a 4% opacity on-surface color added to the background on hover? What about when activated (focus) ? Is that still 8% ?
