### ISSUE TITLE
Add Angular4 framework integration example.

### ISSUE THREAD

**Issue by trimox** [material-components/material-components-web#475]
Add framework integration example for Angular4. 
* Example Angular4 components for MDC Textfield and Button
* Example page demonstrating Textfield and Button bindings and events.

PR: https://github.com/material-components/material-components-web/pull/477
If you have any suggestions, please let me know..

**Comment by trimox** [comment]
Also, if anyone is interested. 
I created a repo for Angular wrappers I'm working on; just completed a wrapper for MDC FAB.
https://github.com/trimox/angular-mdc-web

**Comment by steren** [comment]
But isn't Material Design officially implemented in Angular too? https://material.angular.io/
I would suggest to link to it from thie site.

**Comment by trimox** [comment]
@steren, the folks at material.angular.io do not use MDC-Web. They are designing Angular MD components which may or may not align with the official Google vision.
Closing since I closed my PR https://github.com/material-components/material-components-web/pull/477

**Comment by steren** [comment]
Isn't Angular from Google too? Why cannot it be another appeoved
implementation of the library?

Le ven. 12 mai 2017 à 16:11, Dominic Carretto <notifications@github.com> a
écrit :
