### ISSUE TITLE
Are there plans for Grouping of (Toggle) Buttons ?

### ISSUE THREAD

**Issue by pvogel2** [material-components/material-components-web#4757]
Hi there,
I've a question: are there any plans to introduce some kind of button grouping component or modifier in MDC as it is described on material.io for [Toggle Buttons](https://material.io/design/components/buttons.html#toggle-button) ?

**Comment by moog16** [comment]
We do not have this on our roadmap. You can achieve the toggle button by either using buttons (filled and outline) or [icon buttons](https://github.com/material-components/material-components-web/tree/master/packages/mdc-icon-button). you will need to style the icon buttons if you go that route to match that of the spec, but you get most of the functionality of toggling between the two states.

**Comment by pvogel2** [comment]
Hi moog16, thanks for the reply.
So I understand that there is just no priority on such a component, but in principle there is no reason 'against' it? In fact it is a very similar behaviour like the chip-set.

**Comment by moog16** [comment]
No reason against it. As a team we must prioritize what we work on. I'm not saying this isn't an important component, but there are other more important components/subsystems out there that need our attention.

**Comment by pvogel2** [comment]
Thanks, I understand. Don't know if I will try to do some button group component, but I wanted to know if there are would be some principle obstacles ore reasons against if someone tries. From my point of view the question is well  anwered, so I close the issue.
