### ISSUE TITLE
[MDCChipSet] Input Chips appears to have no effect

### ISSUE THREAD

**Issue by Tiedye** [material-components/material-components-web#4759]
## Bug report
Chips defined as Input Chips appear to have no special behaviour.

### Steps to reproduce
https://glitch.com/~real-mass-1

### Actual behavior
The class `mdc-chip-set--input` has no effect

### Expected behavior
The class `mdc-chip-set--input` should allow the chips to be edited?

**Comment by moog16** [comment]
This class actually needs to be on the mdc-chip-set element:

```
<div class="mdc-chip-set mdc-chip-set--input">
```

**Comment by Tiedye** [comment]
It is...

**Comment by Tiedye** [comment]
This is what is in the example:

```html
<html>
  <head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>
  <body>
    <div class="mdc-chip-set">
      <div class="mdc-chip">
        <div class="mdc-chip__text">Chip content</div>
      </div>
      <div class="mdc-chip">
        <div class="mdc-chip__text">Chip content</div>
      </div>
    </div>
    <div class="mdc-chip-set mdc-chip-set--input">
      <div class="mdc-chip">
        <div class="mdc-chip__text">Chip content</div>
      </div>
      <div class="mdc-chip">
        <div class="mdc-chip__text">Chip content</div>
      </div>
    </div>
    <!-- Run `parcel` (https://parceljs.org) command to bundle this javascript -->
    <script src="./index.js"></script>
  </body>
</html>
```

**Comment by moog16** [comment]
Looks like there is something else going on. Also your JS has 2 "m"...It should be:

```
$('.mdc-chip-set').each((index, el) => {
  new MDCChipSet(el);
});```

**Comment by Tiedye** [comment]
Updated the thing to fix typo.

**Comment by moog16** [comment]
https://github.com/material-components/material-components-web/tree/master/packages/mdc-chips#input-chips

Input chips actually have no JS associated with them. Input chips only give the animation to the chips when being inserted or removed from the chip-set. Is input-chips the correct variant you are looking for?

**Comment by Tiedye** [comment]
Ah I see, I guess I assumed they did a little more.  The "which enable user input" implied that it had a hand in the text to chip conversion.
