### ISSUE TITLE
[TextField] not compatible with wrap="hard" in Edge

### ISSUE THREAD

**Issue by katenorth** [material-components/material-components-web#4762]
## Bug
TextField not compatible with wrap="hard" in Edge

### What MDC Web Version are you using?
2.1.1

### What browser(s) is this bug affecting?
Edge 41.16299.1004.0

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
1. Open pen in Edge: https://codepen.io/anon/pen/LoBrPK
2. Type in the textarea that specifies wrap="hard" until text begins to wrap onto next line
3. Try to click out of textarea - Edge will freeze

### What is the expected behavior?
You should be able to type any amount of text in the textarea without Edge freezing.

### What is the actual behavior?
After typing enough text to cause a wrap, Edge will freeze when you try to leave the textarea.

**Comment by abhiomkar** [comment]
Not able to repro this issue on codepen that you shared?

Tested on Win 10 Edge 42.17134.1.0

**Comment by abhiomkar** [comment]
Closing since inactive.
