### ISSUE TITLE
[Help] select with a cascading menu

### ISSUE THREAD

**Issue by leudis** [material-components/material-components-web#4765]
Hello, my name is Leudis. I've been trying for some time to achieve something like I show in the image. Basically it is a select with a cascading menu. They could help me, in the documentation I have not found a way to achieve it.
![custom-select](https://user-images.githubusercontent.com/8507834/58492141-b7089e80-8146-11e9-8751-47c5bafa80d3.png)

**Comment by moog16** [comment]
Thanks for opening the issue. We currently have no plans not on our roadmap.
