### ISSUE TITLE
[MDCTabScroller] Error while using auto init

### ISSUE THREAD

**Issue by jecisc** [material-components/material-components-web#4792]
### Steps to reproduce

I have an application with a tab bar. For now, the application is available at: https://mdc.ferlicot.fr/mdc/Components/TabBar

### Actual behavior
The application is using auto-init to instantiate every component. 

When looking at the console I see this error: ` Error: (mdc-auto-init) Could not find constructor in registry for MDCTabScroller`

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | v3.0.0-0
| Browser          | Firefox 66.0.5 (64-bit)
| Operating System | WIndows 7

**Comment by jecisc** [comment]
Removing the auto init for MDCTabSroller, I then get the same error for MDCTab then MDCTabIndicator.

**Comment by abhiomkar** [comment]
Can you please test if you're able to repro this on stable version? `v2.3.0`

**Comment by jecisc** [comment]
I tried to use v2.3.0 and I get the same result.

**Comment by abhiomkar** [comment]
`MDCTabScroller itself can't be instantiated using autoinit. Please see https://github.com/material-components/material-components-web/blob/master/packages/material-components-web/index.ts for list of components that can be instantiated with autoInit.

Also see JS Instantiation section in https://github.com/material-components/material-components-web/tree/master/packages/mdc-tab-scroller and https://github.com/material-components/material-components-web/tree/master/packages/mdc-tab-bar for help.

**Comment by jecisc** [comment]
Good to know thank you. Maybe the documentation page about autoInit could provide the list or point to the link you gave me?

**Comment by jecisc** [comment]
I am also wondering if there is a reason why not all components can be used with the auto init?

**Comment by abhiomkar** [comment]
Clients usually don't have to instantiate `MDCTabScroller` manually, `MDCTabBar` automatically instantiates its child components.

Please see JS Instantiation section in [MDCTabBar](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tab-bar) docs for more details.
