### ISSUE TITLE
npm install fails on debian stretch 32 bit

### ISSUE THREAD

**Issue by pvogel2** [material-components/material-components-web#4801]
## Bug report
 Cloning the project on debian stretch  and running `npm install` fails on installation of the canvas node module.

The package falls back to build the module and is missing lib dependencies.

This it not orignial a problem of mdc I think. Does anybody else had this problems on debian stretch? Maybe there can be added some hint on the installation description?

### Possible solution
There are descriptions on the canvas homepage, I could solve the problem by calling `apt-get install pkg-config libpixman-1-dev libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev`

**Comment by pvogel2** [comment]
`canvas` is a dependency of `resemblejs` which is a dependency of mdc.

**Comment by pvogel2** [comment]
OK, it is in fact only a problem on 32 bit systems. Setup the vm with 64 bit runs npm install without any problems. So I guess the report can be closed?

**Comment by abhiomkar** [comment]
Thanks for the update Peter. I'm closing this issue.
