### ISSUE TITLE
Enhanced Select with no label has too much top padding

### ISSUE THREAD

**Issue by ndtreviv** [material-components/material-components-web#4811]
The first field in this screen capture is a TextField with no label, the second is an enhanced Select:
<img width="425" alt="Screenshot 2019-06-06 at 11 57 35" src="https://user-images.githubusercontent.com/1530653/59028031-7699d680-8852-11e9-8220-33a6263a9877.png">

# Expected Behaviour
TextField and Select(enhanced) should have the same top padding when there is no label

# Actual Behaviour
TextField has `padding-top: 16px`, Select(enhanced) has `padding-top: 20px`

**Comment by moog16** [comment]
closing this issue in favor of https://github.com/material-components/material-components-web/issues/4829
