### ISSUE TITLE
Create initial prototype with Rollup.js on MDC Web mono repo

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#4818]

**Comment by moog16** [comment]
Notes and findings after experimenting and digging into rollup:

*The good:*
- Good tool for building libraries like MDC Web/React
- Really easy documentation to follow that "just works"
- If we were to start all over again I would suggest using rollup over webpack
- Build of JS and CSS assets also _seems_ faster (this is just human perception)
- Andy made it easy to "unplug" webpack and replace it with rollup
- there are solid OSS plugins to achieve what we need

*The bad:*
- MDC Web has too much reliance on webpack
  - screenshots for reporting, spec files, JS and CSS assets all use webpack in some capacity
  - webpack builds sass, typescript, vanilla css/js, images/other assets, handlebars (from my search through the screenshot testing framework), which would all have to be rebuilt/engineered with rollup configs


*My conclusion:*
The cost of switching to rollup is much higher than would be to upgrade to webpack4. Switching to rollup would basically be a complete rewrite of all webpack infrastructure. While webpack might not be the best tool, it does in fact work with minimal maintenance.
