### ISSUE TITLE
2.3.1 material-components-web\dist folder unchanged from 2.3.0?

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#4825]
## Bug report
using npm - comparing the 2.3.1 dist folder to the previous version shows identical file sizes and minor changes indicated on the css files only.

Mentioned elsewhere I got the impression that the new table component (in a first version) would be included in this release.

Is that correct and intended?

**Comment by abhiomkar** [comment]
It was intended, it was a patch release with minor CSS change. See our [CHANGELOG](https://github.com/material-components/material-components-web/tree/master/CHANGELOG.md) file for more details.

Data Table component will be available in premajor release (`v3.0.0-alpha.*`) soon.
