### ISSUE TITLE
[Select] Top Padding should be 16px to match Text Field

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#4829]
original issue: https://github.com/material-components/material-components-web/issues/4811

Both enhanced and native select have 20px top padding. The text field has 16px top padding, and looks misaligned. Spec confirms it should match.

See https://github.com/material-components/material-components-web/issues/4811#issuecomment-500627476 for verification of text field and select being misaligned.

**Comment by allan-chen** [comment]
This should no longer be an issue after the recent select overhaul to match textfield @ 28d10a9
