### ISSUE TITLE
Implement Expand/Colapse for mdc-list

### ISSUE THREAD

**Issue by KaRkY** [material-components/material-components-web#483]
It would be nice to have Expand/Collapse on mdc-list as documented here.

https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls

**Comment by Garbee** [comment]
Related to #46 

Same JS logic for both, just slightly different style on top to fit into lists.

**Comment by yeelan0319** [comment]
Duplicate of #46 , we will close this one.

**Comment by CarlosV89** [comment]
This doesn't really count as the "same" anymore since expansion panels are not part of the MDC Spec, but Expandable/Collapsible lists are.

https://material.io/design/components/lists.html#types

Sorry for reviving but should this remain closed?

**Comment by kfranqueiro** [comment]
This is somewhat of a timely question, since I believe we'll be discussing scope/prioritization of List features across platforms sometime soon. We'll likely end up entering new issues to reflect the outcome of that discussion after it happens.

**Comment by Garbee** [comment]
From the referenced issue this is a dupe of...

> This is no longer within scope of the MD spec, so we're no longer planning to add this to the core MDC Web repository.

**Comment by tamalsaha** [comment]
But the material.io website still shows a `Expand and collapse` option for List. Is that going to be support in the MDc components?

![mdc-list](https://user-images.githubusercontent.com/94814/51151402-9c7cfb00-181f-11e9-8d48-887913bce472.png)

**Comment by calebccff** [comment]
Is there any news on this? I'd really like this feature for a website.

**Comment by suhailkc** [comment]
Any plan to implement Expand/Collapse?
It's necessary !!

**Comment by LionstoothSoftware** [comment]
Does anyone have a good workaround? I'm about to just implement my own thing without using the MDC list.

**Comment by KingFalse** [comment]
Need it!

**Comment by clevercodenl** [comment]
Also need it

**Comment by jfbrennan** [comment]
If not directly available is there a code sample for achieving the same? I can only find screenshots:
<img width="824" alt="Screen Shot 2020-09-20 at 11 18 49 AM" src="https://user-images.githubusercontent.com/1817868/93718777-1dcb7b80-fb33-11ea-8e12-a70f5889da1d.png">

I'm comparing Material Web's markup to [M-](http://m-docs.org/accordion) and want to make sure I'm putting out an accurate comparison. Right now I have to put "Unsupported" for Material, but the https://material.io/components/lists#types has that example in the screenshot above. Confusing...

**Comment by c-dinkel** [comment]
This is not a duplicate of #46 any longer, since the spec does not contain the Expansion Panel any more.

This is now an issue again, since expanding and collapsing lists are still part of the spec.
