### ISSUE TITLE
--mdc-theme-text-secondary-on-background : why 54% and not 60%?

### ISSUE THREAD

**Issue by djibe** [material-components/material-components-web#4833]
Hi, material.io states that medium emphasis text is black with 60% opacity.
I see in code that material components use black 54% opacity.

Did I miss something ? 
Thanks for your help in my quest (trying to bring MD to Bootstrap 4.3.1) ;-)

**Comment by abhiomkar** [comment]
`text-secondary-on-background` is deprecated, please see https://github.com/material-components/material-components-web/issues/3124 for details.
