### ISSUE TITLE
How to set the position for a mdc.menu?

### ISSUE THREAD

**Issue by joergklein** [material-components/material-components-web#4840]
I am not sure if this the right place for this question. 
How to set the position for a mdc.menu?
I will move the mdc-menu from the left, top corner to the right corner. 70px from top and 25px from the right. How can I change the element style?
Please take a look at my javascript  code. Where I have to make the changes? 

      <header class="mdc-top-app-bar mdc-top-app-bar--fixed app-bar" id="app-bar">
        <div class="mdc-top-app-bar__row">
          <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <a href="#" class="demo-menu material-icons mdc-top-app-bar__navigation-icon">menu</a>
            <span class="mdc-top-app-bar__title">Title</span>
          </section>
          <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">
            <a href="#" class="material-icons mdc-top-app-bar__action-item" aria-label="Download this page">file_download</a>
            <button id="menu-button" class="material-icons mdc-top-app-bar__action-item" aria-label="Personal settings" alt="Personal settings">person</button>
          </section>
        </div>
      </header>

    <div class="mdc-menu mdc-menu-surface" tabindex="-1">
      <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical">
        <li class="mdc-list-item" role="menuitem">
          <i class="material-icons mdc-list-item__graphic" aria-hidden="true">person</i>
          <span class="mdc-list-item__text">Profil</span>
        </li>
        <li class="mdc-list-item" role="menuitem">
        <i class="material-icons mdc-list-item__graphic" aria-hidden="true">settings</i>
          <span class="mdc-list-item__text">Settings</span>
        </li>
        <hr class="mdc-list-divider">
        <li class="mdc-list-item" role="menuitem">
          <i class="material-icons mdc-list-item__graphic" aria-hidden="true">exit_to_app</i>
          <span class="mdc-list-item__text">Sign out</span>
        </li>
      </ul>
    </div>

    <main>
      <h1 class="mdc-typography--headline1">title h1</h1>
    </main>

    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <script>
        const menu = mdc.menu.MDCMenu.attachTo(document.querySelector('.mdc-menu'));
        menu.setAnchorCorner(mdc.menu.Corner.BOTTOM_LEFT);
        menu.open = false;
        menu.setFixedPosition(true);

      const btn = document.querySelector('#menu-button');
      btn.addEventListener('click', () => {
        menu.open = !menu.open;
      });
    </script>
  </body>

```

**Comment by abhiomkar** [comment]
Please see this [example on Codepen](https://codepen.io/abhiomkar/pen/dBXoYY). You'll need to use `setAnchorMargin` for offsetting the menu position.

**Comment by tjmosia** [comment]
@joergklein you may have to do the following:

> menu.setAbsolutePositioning(70,25);

This method kind of sets the `top` and `right` properties of the HTMLElement `style` object when the latter is in absolute position.

When it comes to how you want to style and best position your menu, I would encourage you to have an anchor DIV within which the menu will be positioned. Don't just let it float relative to `<body>` as parent... Well you can do that but it's gets trickier. So put you menu inside a `<div class="mdc-menu-surface-anchor">`.


I hope this help, others! :)
