### ISSUE TITLE
No Flexbox Support

### ISSUE THREAD

**Issue by virgiltu** [material-components/material-components-web#4851]
It is funny that Material.Io has so many guidelines of how the web should look like but it is missing the most important ones. 

Please implement flex-box. This should be the first thing when it comes to alignment. 
Also grid layout. The current grid layout is mostly obsolete. 

I really want to love this platform but it has to be the worst out of all the css frameworks in terms of documentation and features.

**Comment by abhiomkar** [comment]
Can you please elaborate 'implementing Flexbox'?

**Comment by virgiltu** [comment]
flexbox and grid designs are the new standard and all other css web frameworks implement it. 

https://css-tricks.com/snippets/css/a-guide-to-flexbox/ 

https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by abhiomkar** [comment]
Thanks for the feedback. We're working on improving our documentation and component features.

At this point we've other pressing things going on. We do not have enough resources to work on layout grid in near future. Please follow our [GitHub milestones](https://github.com/material-components/material-components-web/milestones) for upcoming features / bug fixes.
