### ISSUE TITLE
Automate API Docs

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#4858]
Epic issue to track tasks related to automating API docs.

### Background

So far component authors are manually editing API docs in README file. This comes with maintenance cost and we easily forget to update in our docs when we make changes in component. We had few components with discrepancies in documentation.

### Goals

Auto generate following API doc tables in component README files:

* Component properties, methods & events.
* Adapter
* Foundation
* Sass Mixins

**Comment by abhiomkar** [comment]
@moog16 Converted this issue to Epic. We can add blocking child issues to split this work into smaller chunks.
