### ISSUE TITLE
Outdated Chip documentation

### ISSUE THREAD

**Issue by Bloemendaal** [material-components/material-components-web#4867]
Could you please update the Chip component [documentation](https://material.io/develop/web/components/chips/) and [demo](https://material-components.github.io/material-components-web-catalog/#/component/chips) page, since it does not longer match with the [readme.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-chips/README.md) file.

Thanks in advance!

**Comment by moog16** [comment]
Thanks for opening the issue. Yes this is a valid request and we'll get on this :)

**Comment by bonniezhou** [comment]
This should be fixed now!

**Comment by Bloemendaal** [comment]
I think the demo page does not behave as it should. The choice chipset does not select other chips and the filter chipset doesn't select & deselect. Both unselected choice and filter chips have the class undefined. 🤔

**Comment by bonniezhou** [comment]
Yes, that's a separate issue that has been filed [here](https://github.com/material-components/material-components-web-catalog/issues/176).
