### ISSUE TITLE
Toolbar package is missing.

### ISSUE THREAD

**Issue by ruwaroshan** [material-components/material-components-web#4875]
As in Change Log version 3.0.0 there is not mentioned to remove toolbar package.
But the toolbar documentation is no longer exists.

https://github.com/material-components/material-components-web/tree/master/packages/mdc-toolbar.

**Comment by abhiomkar** [comment]
We missed to update this commit message in catalog since it had `chore:` commit convention. I can confirm that it was deleted in v3.0.0 version.
