### ISSUE TITLE
Better customisation docs

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#49]
The [customize](http://www.getmdl.io/customize/index.html) page of the docs do a great job of showing how to customize the color theme. However, some users may want more customization. I happen to know that simply adding an extra css file that loads last, with whatever customization a user wants, will override anything in MDL, but not every user will be aware that. Adding something to that effect might be helpful.

Great job so far. I'm especially impressed how fast issues are being addressed. Thanks for this.

> Copied from https://github.com/google/material-design-lite/issues/841

**Comment by kfranqueiro** [comment]
I think this is now covered by a combination of docs and codelabs (https://codelabs.developers.google.com/?cat=Web and search for MDC).
