### ISSUE TITLE
How to disable MDC Select Menus from opening through keyboard event

### ISSUE THREAD

**Issue by yijiem** [material-components/material-components-web#4904]
Hi!

I would like to prevent mdc-select (I'm using enhanced select) to open up the menu through keyboard (focus and then hitting enter) when it is disabled. I followed the Disabled select guidance here:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#disabled-select

But the menu is still able to be opened when I hit enter key and I saw there are 3 events fired on mdc-select at that time (mousedown, mouseup, and click). This is for accessibility concern and marking the mdc-select as "aria-disabled=true" only makes voice program to say "Unavailable". But I would prefer to disable opening the menu also. Any hint will be helpful! Thanks!

**Comment by abhiomkar** [comment]
Disabled select components are not tabbable. See this example: https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2018/11/21/19_18_38_795/spec/mdc-select/classes/disabled.html?utm_source=golden_json for reference.

**Comment by yijiem** [comment]
From my experiment, it seems like if I add 'mdc-select--disabled' to the 'mdc-select' element in the html, it works which conforms with what the documentation has said "To initially render a MDCSelect in a disabled state, ...". But in my use case, I want to disable it after the initial loading of the page through javascript where I found it didn't work.

**Comment by yijiem** [comment]
FYI, in this case, manually set the 'tabindex' property to -1 for the div with class 'mdc-select__selected-text' and role 'button' in the enhanced select mode successfully make the whole select menu untabbable. But I don't know if it considers as a hack or not.

**Comment by yijiem** [comment]
Disabled enhanced select is not tabbable, but it's still accessible through arrow key navigation. Reopen this bug to request investigation.
