### ISSUE TITLE
datatable Error

### ISSUE THREAD

**Issue by libertizer** [material-components/material-components-web#4906]
Probably this issue is due to to the fact that data-table component is in version 3.0.0-alpha.0 but I wanted to report it anyway:
![Capture](https://user-images.githubusercontent.com/13909216/61288464-7a146c00-a7c7-11e9-9b0a-07f2a2934b6d.PNG)

**Comment by abhiomkar** [comment]
Can you please try again with new version of MDC Web? v3.1.0

**Comment by libertizer** [comment]
I still got an error, I unfortunately don't have time today to investigate further now since I go on holiday in 10 min ;-)

![error](https://user-images.githubusercontent.com/13909216/62361478-65500c00-b51b-11e9-8b58-81f623fcffa5.PNG)

**Comment by abhiomkar** [comment]
Looking at the error log it seems like you're missing TypeScript loader.

**Comment by libertizer** [comment]
I use typescript loader from babel, it works for 15 material components I used so far except for datatable comonent. I tried with "@babel/preset-typescript" and "@babel/typescript" in .babelrc, same behaviour
