### ISSUE TITLE
[IconButton] icon button toggle documentation not clear how to import JS

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4907]
## Bug report
In the documentation for the icon button, the part where it has the icon button toggle section, it doesn't show how to import the JS and instead it does it through CDN way. This is not very consistent compared to the rest of the MDC components where they show how to import the JS.
It does have the import for the ripple effect, just not for the icon button toggle.

### Screenshots
Icon toggle:

<img width="702" alt="Screen Shot 2019-07-17 at 1 04 58 AM" src="https://user-images.githubusercontent.com/26075792/61296867-1e7dc900-a82f-11e9-9340-b213c718d019.png">

Other components (examples):

<img width="708" alt="Screen Shot 2019-07-17 at 1 07 00 AM" src="https://user-images.githubusercontent.com/26075792/61296919-348b8980-a82f-11e9-9fe2-450e7730a001.png">
<img width="704" alt="Screen Shot 2019-07-17 at 1 07 31 AM" src="https://user-images.githubusercontent.com/26075792/61296954-49681d00-a82f-11e9-8a7f-78b1b6c68d34.png">

### Proposed change

Replace:
```js
var toggleButton = new mdc.iconButton.MDCIconButtonToggle(document.getElementById('add-to-favorites'));
```
With:
```js
import {MDCIconButtonToggle} from '@material/icon-button';
const iconToggleEl = querySelector('#icon-toggle-button');
const iconToggle = new MDCIconButtonToggle(iconToggleEl);
iconToggle.unbounded = true;
```
Or:
```js
import {MDCIconButtonToggle} from '@material/icon-button';
const iconToggle = new MDCIconButtonToggle(querySelector('#icon-toggle-button'));
iconToggle.unbounded = true;
```

**Comment by moog16** [comment]
@CyborgSemon that makes sense! It should be consist with the rest of the documentation. Would appreciate a PR! :)
