### ISSUE TITLE
[TextField] Making an empty text field in-valid triggers the select animation when it shouldn't. 

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4919]
## Bug report
Making an empty text input invalid triggers the select animation when it shouldn't

### Steps to reproduce
1. Go to https://codepen.io/anon/pen/oKNvgX
2. Click on the make invalid button
3. See error

### Actual behavior
![textFieldBug](https://user-images.githubusercontent.com/26075792/61421535-96491200-a95b-11e9-8704-9d7b2283f9e4.gif)

### Expected behavior
The text input just goes red and no animation is played

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | The version that is run on the code pen
| Browser          | Chrome 75
| Operating System | MacOS 10.14.5

**Comment by abhiomkar** [comment]
Fixed in #5097
