### ISSUE TITLE
[textField] Forcing validation

### ISSUE THREAD

**Issue by ftaiolivista** [material-components/material-components-web#4921]
When update a textField  with javascript (not by direct user input) the validation is not immediatly triggered and the field remain valid(or invalid) hiding(or showing) the help text until the user click the input field and focus out from it.
How I can programmatically trigger the field validation and relative help text management when value is altered by javascript?

**Comment by moog16** [comment]
1. `useNativeValidation` --> false
1. on `change` event update the `textField.valid` to whatever you determine to be the correct value.

Let us know if this helps.

**Comment by abhiomkar** [comment]
Closing this issue since inactive, Please feel free to re-open if required.
