### ISSUE TITLE
Impossible to import scss (vue cli 3)

### ISSUE THREAD

**Issue by LightBen** [material-components/material-components-web#4933]
I want to use material-components-web via npm in my Vue CLI 3 project. 

Here is some configuration:

App.vue
```
<style src="./main.scss" lang="scss"></style>
```

main.scss
```
@import "~material-components-web/material-components-web";
```

main.js
```
import Vue from 'vue'
import * as mdc from 'material-components-web';
import App from './App.vue'
import router from './router'
import store from './store'
import './registerServiceWorker'

Vue.config.productionTip = false

Vue.use(mdc)

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')
```

Error I get:
```
ERROR  Failed to compile with 1 errors
 error  in ./src/main.scss?vue&type=style&index=0&lang=scss&
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
undefined
^
      File to import not found or unreadable: @material/button/mdc-button.
      in C:\Users\...\my-project\node_modules\material-components-web\material-components-web.scss (line 23, column 1)
```

I looked on the internet, including all possible GitHub related issues, stackoverflow for 5 hours now with all trial possible, the solution that got repeated is to add node modules in the includePaths.

I tried that (but in many different ways):
vue.config.js
```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        includePaths: ["node_modules"]
      }
    }
  }
}
```
I tried for example:
```
const path = require('path')
...
loaderOptions: {
      sass: {
        includePaths: [path.resolve(__dirname, "node_modules")],
      },
    }
```
or:
```
includePaths: glob.sync('node_modules').map((d) => path.join(root, d))
```
or:
```
includePaths: ['node_modules', 'node_modules/@material/*'] .map((d) => path.join(__dirname, d))
```
or:
```
loaderOptions: {
            sass: {
                data: [
                    '../node-modules/material-components-web/material-components-web.scss'
                ].map(fileName => fs.readFileSync(fileName, 'utf-8')).join('\n')
            }
        }
```

But still the same error. He finds the main scss in node_modules/material-components-web/material-components-web.scss but then he can't process the first line of it which is 
`@import "@material/button/mdc-button";`
in this case.

Nothing seems working. Anyone would see what am I missing?

**Comment by moog16** [comment]
Hey @LightBen - do any of these framework libraries help you? https://material.io/develop/web/docs/framework-wrappers/

**Comment by LightBen** [comment]
Hi @moog16 
I tried to follow the instructions at https://github.com/material-components/material-components-web-components but the index.html resources are not loaded (Failed to load resource: the server responded with a status of 500 (Internal Server Error))

I then tried to create a new empty project following the same instructions with npm (also from https://www.npmjs.com/package/material-components-web) but when I do polymer serve nothing happens, may be I missed something. I try to use my own thing (npm run serve with vue cli) but I get the same error as above. 

I would prefer to use something official than third party for this project that I intend to keep a long time... if there is no solution I assume I'll have to wait :(

**Comment by skatAn8rwpas** [comment]
Follow the instractions of how to import the scss files from [material.io](https://material.io/develop/web/components/buttons/)

```
@import "@material/button/mdc-button";

.foo-button {
  @include mdc-button-ink-color(teal);
  @include mdc-states(teal);
}
```

And just include the node_modules directory. THre is a "./" at the bigin.
```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        includePaths: ["./node_modules"]
      }
    }
  }
}
```

delete the lines
```
import * as mdc from 'material-components-web';

Vue.use(mdc);
```
and lastly 
import components in your .vue files as in documentation

**Comment by LightBen** [comment]
Hi @skatAn8rwpas 

Thanks for your answer
Isn't it a way to import everything instead of component per component in @material?

**Comment by bonniezhou** [comment]
@LightBen yes, [here](https://github.com/material-components/material-components-web/tree/master/packages/material-components-web) are instructions for importing all components at once.

Closing this issue since it seems to be resolved.

**Comment by LightBen** [comment]
@skatAn8rwpas It works! I'm so happy. I'm putting the summary of what is final in case other people need.
Project with vue and material design web :
1) ```npm install material-components-web```
2) In vue.config.js:
```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        includePaths: ["./node_modules"]
      }
    }
  }
}
```
3) In src/app.scss:
```@import "~material-components-web/material-components-web";```
4) If someone wants the icons, add in public/index.html, in the <head>:
```<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">```
5) Use Material. Example of a button in my views/About.vue:
```
<button class="mdc-button">
  <span class="mdc-button__label">Button</span>
</button>
```

Thanks everybody!
