### ISSUE TITLE
mdc-checkbox: Background issues when inside an mdc-list

### ISSUE THREAD

**Issue by zposten** [material-components/material-components-web#4934]
**Steps to reproduce:**
1. Create a `.mdc-list`
1. Copy-paste an `.mdc-checkbox` from [the documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-checkbox#basic-usage) into a `.mdc-list-item`
1. Move the mouse around the checkbox list item

**Observed behavior**
The background of the checkbox appears to flicker in and out on the background of the list item.  However, a list item in the same list without a checkbox works as expected.

**Expected behavior**
The background of the list item should be the same with a checkbox inside it as it is without one.

Reproducible [example on stackblitz](https://stackblitz.com/edit/mdc-list-demo-b4t1a4).

**Comment by abhiomkar** [comment]
This is fixed is new version of MDC Web. Marking this as closed.
