### ISSUE TITLE
[Select] Refactoring follow-ups

### ISSUE THREAD

**Issue by joyzhong** [material-components/material-components-web#4935]
Follow-up cleanup tasks from https://github.com/material-components/material-components-web/pull/4830:
1. Remove #hoistMenuToBody from https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/component.ts, https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu-surface/component.ts; it's not needed anymore
2. Update all public Sass mixins to be called from root element. https://github.com/material-components/material-components-web/pull/4830/files/495e7bad0ec4a083199b97dbfde28e572097c766#diff-0b8ddbeeed600580f713f5a6953e5efa
3. Move logic from component and adapters into foundation, e.g. in `MDCSelectAdapter.openMenu()` and `MDCSelectAdapter.setValid()`

**Comment by bonniezhou** [comment]
Tasks in this bug resolved by PR #4958.

Further tasks added in issue #4993.
