### ISSUE TITLE
List demo avatars are too amazing

### ISSUE THREAD

**Issue by unascribed** [material-components/material-components-web#494]
Are there any more avatars similar to the ones used in the list demo?

i.e. [animal1](https://github.com/material-components/material-components-web/blob/master/demos/images/animal1.svg), [animal2](https://github.com/material-components/material-components-web/blob/master/demos/images/animal2.svg), [animal3](https://github.com/material-components/material-components-web/blob/master/demos/images/animal3.svg)

I'd imagine they were made by a Google-internal designer specifically for MDC, but it would be beyond awesome if they were an open-licensed set of example avatars. I've tried to look for where they might be from, but I can't find anything - everything links back to the demo site.

Sorry for bugging you guys with something as trivial as this, I'm sure you have better things to do. >.<

**Comment by yeelan0319** [comment]
Hey @unascribed, glad that you show the love for our cute animals!

We need to ask our designer for design guidance on this issue and will keep you posted!

**Comment by traviskaufman** [comment]
Just FYI we haven't forgotten about this and are still working on it!
