### ISSUE TITLE
Checkboxes and radios render incorrectly when label has multiple lines

### ISSUE THREAD

**Issue by mikeyzm** [material-components/material-components-web#495]
### What MDC-Web Version are you using?

0.8.0

### What browser(s) is this bug affecting?

Chrome 57.0.2987.133 (64-bit)

### What OS are you using?

Windows 10 

### What are the steps to reproduce the bug?

1. Navigate to https://material-components-web.appspot.com/checkbox.html
2. Add some text to label, make the label be splitted into multiple lines.

### What is the expected behavior?

Checkbox height and width should be equal.

### What is the actual behavior?

As the rows increase, the checkbox width becomes narrower.

Radios have the same issue.

**Comment by yeelan0319** [comment]
Thanks for reporting. This is definitely a bug.

It seems like we haven't specified the `flex-basis` for checkbox as well as radio button. We would like to accept a PR if you are willing to help us fix it! The PR should: 

- [ ] Add `flex: 0 0 18px` to `.mdc-checkbox`
- [ ] Add `flex: 0 0 40px` to `.mdc-radio`

Thanks a lot!

**Comment by mikeyzm** [comment]
I'd be glad to.
