### ISSUE TITLE
Selections controls labels have no styles applied in the --disabled state

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#4952]
### Steps to reproduce
1. See the [codepen](https://codepen.io/Darhakexge/pen/ymJmyj)

### Actual behavior

The label color of the disabled selection control keeps the default text color

### Expected behavior

The label color of the disabled selection control should change to the disabled state

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 3.1.0
| Browser          | Any
| Operating System | Any

**Comment by moog16** [comment]
This is intended behavior, the label color doesn't change. You the user will have to manually do this yourself. 

If you would like, you can use mdc-list, and use the `mdc-list-item--disabled` class. You can have either a radio or checkbox within the list.
