### ISSUE TITLE
MDC Form Components won't update UI when values are added or reset via javascript

### ISSUE THREAD

**Issue by oneezy** [material-components/material-components-web#4955]
## Bug report
I'm trying to reinitialize/ redraw all MDC components for form elements when their values change via `ajax` or `form.reset()`, but so far my attempts have fallen short. Is there an easy way to achieve this with a built in MDC method that I'm unaware of?

I created a custom way to reload the MDC components with a `data-mdc-reload` html attribute that fires on click but this isn't quite doing the job.

### Steps to reproduce
1. Go to [my codepen](https://codepen.io/oneezy/pen/XvMavP)
2. click the `UPDATE FORM VALUES` button to add data
3. the `VALUE` output in red means the component is broke/ blue means it works
4. click the `RESET` button to reset data to initial state (this is broke too)

### Actual behavior
- The form field components **don't** update their UI when the components value changes via `javascript` or `AJAX`.
- The form field components **don't** update their UI when the components value is reset via `form.reset()` or `<button type="reset">`.

### Expected behavior
- The form field components **should** update their UI when the components value changes via `javascript` or `AJAX`.
- The form field components **should** update their UI when the components value is reset via `form.reset()` or `<button type="reset">`.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 3.1.0
| Browser          | Chrome Beta
| Operating System | Windows 10

**Comment by abhiomkar** [comment]
Updating DOM elements will not update component state, you'll have to use JS component APIs.

For example. textField.value = 3 to update text field value. See https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield for API reference.
