### ISSUE TITLE
[mdc-list-item] List items react to user clicks when using mdc-list-item--disabled and mdc-list-item--selected at the same time

### ISSUE THREAD

**Issue by janoschpelzer** [material-components/material-components-web#4961]
List items can be selected and deselected by clicking on them when using the style classes mdc-list-item--disabled and mdc-list-item--selected at the same time. The expected behavior would be for them to look like selected list items but not to react to any user input, because they are disabled.

**Comment by bonniezhou** [comment]
This should be resolved by #4922
