### ISSUE TITLE
[Select] Enhanced select should close on scroll

### ISSUE THREAD

**Issue by irahopkinson** [material-components/material-components-web#5002]
## Bug report
When enhanced select is open, scrolling leaves the menu open and does not move the menu with the the select input.

### Steps to reproduce
1. Go to 'https://material-components.github.io/material-components-web-catalog/#/component/select'
2. Scroll down to **Demos**
3. Under **Filled Enhanced**, click on the select to open the menu
4. Scroll the page
5. The menu doesn't close or move with the page/select input

### Actual behavior
The open menu doesn't close or move with the select input when scrolling the page.

### Expected behavior
The menu closes on scroll event like the native select.

### Screenshots
Open menu
![image](https://user-images.githubusercontent.com/5582153/63138948-8d089f00-c006-11e9-9167-ea4604c97b53.png)

After scroll
![image](https://user-images.githubusercontent.com/5582153/63138690-96ddd280-c005-11e9-8cca-fe5965fc8902.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |  I can't tell what version is on https://material-components.github.io, but latest is 3.1.1
| Browser          | Chrome Version 76.0.3809.100 (Official Build) (64-bit)
| Operating System | Windows Version 10.0.18362 Build 18362

### Additional context
n/a

### Possible solution
The menu closes on scroll event like the native select.

**Comment by abhiomkar** [comment]
We fixed detaching behavior in `feature/select` branch this'll be shipped in next major release. Please see #5010 for updates.
