### ISSUE TITLE
[data-table] Cannot read property 'checked of undefined'

### ISSUE THREAD

**Issue by buzziam** [material-components/material-components-web#5004]
## Bug report
Upon rendering a page containing an @material/data-table, and then attempting to interact with checkboxes - the following error is reported in the JS Console: 
```
Uncaught TypeError: Cannot read property 'checked' of undefined
    at Object.isHeaderRowCheckboxChecked (component.ts:162)
    at MDCDataTableFoundation.handleHeaderRowCheckboxChange (foundation.ts:193)
    at HTMLTableRowElement.handleHeaderRowCheckboxChange_ (component.ts:71)
```
*However*, if the rendered view is changed to the previous view (where the data-table is not) and then changed again to the view in which the data-table exists, clicking on a checkbox results in no error.

Got to run - but I'll see if I can distill the problem into a repeatable demo in a starter kit within the next 24hrs. 

### Steps to reproduce
1. Will try to get a demo together in the next 24.

### Actual behavior
Clicking on a check box in a table row results in the above error. 

### Expected behavior
Clicking on check box in a table row results in no error.

### Screenshots
N/A

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 3.1.0 |
| Browser          | Chrome 76.0.3809.100 |
| Operating System | Win 10 |

**Comment by buzziam** [comment]
Also seeing the following: 
```
component.ts:159 Uncaught TypeError: Cannot read property '0' of undefined
    at Object.isCheckboxAtRowIndexChecked (component.ts:159)
    at MDCDataTableFoundation.handleRowCheckboxChange (foundation.ts:193)
    at HTMLTableSectionElement.handleRowCheckboxChange_ (component.ts:79)
```

**Comment by abhiomkar** [comment]
Thanks for reporting issue. We need a working example to investigate this.

**Comment by buzziam** [comment]
Okay - I've tried to reproduce. I think the issue has to do with the way table population is achieved (in `element-one.js` of the glitch) - but I'm not really sure why that is a problem. 

There is one aspect of the error reported that I'm not able to reproduce (in the glitch sample):
- no-error occurring upon switching view to a second view and then back. 

However, the main issue can be seen upon interacting with the checkbox(es) after adding row(s):

https://plant-nightshade.glitch.me

**Comment by abhiomkar** [comment]
Are you calling dataTable's `.layout()` API after adding a row?

**Comment by buzziam** [comment]
Yes - but it's being called after adding several rows. Doing so isn't completely out of line of the documentation :)

In the case of the the example, the entire table structure is being rebuilt each time `render()` is called on ElementOne assuming nothing tricky is going on in lit.  

Quoting Doc:
> MDC Data Table component auto instantiates MDCCheckbox for header row checkbox and all row checkboxes. Make sure to set required class names to instantiate checkbox component. We suggest to use layout API when rows are added or removed from data table to register new checkbox components.

Also -

**Comment by buzziam** [comment]
I'll try re-rendering the whole table explicitly in case there is something tricky (along the lines of shadowy) going on because things work just fine the first time the table is rendered in whole.

**Comment by buzziam** [comment]
I believe this issue was occurring because the underlying model was being modified at the same time `.layout()` was being called. Closing for now.
