### ISSUE TITLE
[MDCRipple] Hover state is persistent after tapping on a component with ripple on mobile Safari

### ISSUE THREAD

**Issue by Victguo** [material-components/material-components-web#5005]
## Bug report
On mobile Safari, after tapping on a component that has ripple, the hover styles are still applied to the component.

### Steps to reproduce
1. Go to https://material-components.github.io/material-components-web-catalog/#/component/ripple on mobile Safari.
2. Tap on the button with the label "Click Here!".
3. You can see that the button still has its ripple effect if you were to hover over it with a cursor on a desktop browser. The hover effect disappears once there is a tap elsewhere.

### Actual behavior
There is a persistent hover ripple effect after tapping on a component with ripple which does not go away until there is a tap elsewhere.

### Expected behavior
The component with ripple (in this case the button) after tapping should revert back to what it was before the tap.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | Not sure, but latest version is 3.1.1
| Browser          | Mobile Safari
| Operating System | iOS 12

**Comment by abhiomkar** [comment]
This is iOS bug, but not related to MDC Web. Please see https://bugs.webkit.org/show_bug.cgi?id=158517 to follow the bug.

Meanwhile there are bunch of other alternatives that you can use (Using JS) to remove hover state.
