### ISSUE TITLE
[Button] Support disabled design same with a element

### ISSUE THREAD

**Issue by TroyTae** [material-components/material-components-web#5012]
## Feature Request
Now MCW is allowed to use `<a>` element in Button.
But `<a>` element cannot apply disabled attribute and disabled design isn't applied.

### Proposed solution
1. Add style rule `[href=""]`
2. Add style rule `[disabled]`

**Comment by abhiomkar** [comment]
Anchor tag does not semantically support disabled attribute. We might need to offer a mixin that adds disabled styles instead.

**Comment by TroyTae** [comment]
@abhiomkar 
How about change this code?
I cannot sure what is link style...
But It seems we can remove `:not(:disabled` and change `:disabled` to `[disabled]`.
Because every tag supports attribute select.

**Comment by abhiomkar** [comment]
`:not(:disabled)` applies styles to button that are only enabled. We need this pseudo selector to override styles only for enabled buttons.

`disabled` HTML attribute is only supported by `<button>` element but not `<a>`. See [MDN docs](https://developer.mozilla.org/en/docs/Web/HTML/Element/a).

**Comment by TroyTae** [comment]
@abhiomkar 
Yes you're right.
`:disabled` pseudo selector is supported only fieldSet element.
My opinion is how about to use `[disabled]` selector instead of `:disabled`.

ex)
`&:not(:disabled)` -> `&:not([disabled])`
`&:disabled` -> `[disabled]`

**Comment by abhiomkar** [comment]
I would recommend implementing a mixin to apply presentational disabled state instead of introducing selectors that are not semantic.

**Comment by TroyTae** [comment]
@abhiomkar
Ah I see
Thank you for your reply :)
