### ISSUE TITLE
Unable to use components using css-loader with modules enabled

### ISSUE THREAD

**Issue by emilmuller** [material-components/material-components-web#5017]
I am unable to use material design using webpack's css-loader with modules. It works to a certain degree, but ripple effects do not work (as well as everything else related to keyframes).

When using css modules, variable names get scoped. This can be disabled with :global { ... } before importing the css. However, the :global instruction does not take effect on keyframes. See https://github.com/css-modules/css-modules/issues/115.

So I am stuck.

**Comment by abhiomkar** [comment]
This issue does not seem to be related to MDC Web. We can separate keyframe into a separate entry point but that'll be a bigger refactor. 

I would watch the css-modules issue mentioned in your comment.
