### ISSUE TITLE
mdc-textfield and mdc-select: Selection boxes and text fields go out of alignment when one filled in and one not

### ISSUE THREAD

**Issue by mishushakov** [material-components/material-components-web#5028]
## Bug report

Selection boxes and text fields go out of alignment when one filled in and one not

### Steps to reproduce

```html
<div class="mdc-text-field mdc-text-field--outlined">
    <input class="mdc-text-field__input">
    <div class="mdc-notched-outline">
        <div class="mdc-notched-outline__leading" />
        <div class="mdc-notched-outline__notch">
            <label class="mdc-floating-label">Name</label>
        </div>
        <div class="mdc-notched-outline__trailing" />
    </div>
</div>
<div class="mdc-select mdc-select--outlined">
    <i class="mdc-select__dropdown-icon" />
    <select class="mdc-select__native-control">
        <option value="16-25">16-25</option>
        <option value="26-35">26-35</option>
        <option value="36-45">36-45</option>
        <option value="46-55">46-55</option>
        <option value="56-65">56-65</option>
        <option value="65+">65+</option>
    </select>
    <div class="mdc-notched-outline">
        <div class="mdc-notched-outline__leading" />
        <div class="mdc-notched-outline__notch">
            <label class="mdc-floating-label">Age</label>
        </div>
        <div class="mdc-notched-outline__trailing" />
    </div>
</div>
```
### Actual behavior

<img width="419" alt="Screenshot 2019-08-26 at 14 30 02" src="https://user-images.githubusercontent.com/10400064/63691366-49d0dc00-c80f-11e9-80f8-a9d5ebb2d1b0.png">

<img width="410" alt="Screenshot 2019-08-26 at 14 31 33" src="https://user-images.githubusercontent.com/10400064/63691368-4d646300-c80f-11e9-97b4-a9eafe453ee2.png">

### Expected behavior

<img width="412" alt="Screenshot 2019-08-26 at 14 39 36" src="https://user-images.githubusercontent.com/10400064/63691382-56553480-c80f-11e9-8a18-0b9b34e0de10.png">

### Your Environment:

Packages:

<img width="395" alt="Screenshot 2019-08-26 at 14 37 25" src="https://user-images.githubusercontent.com/10400064/63691273-0f673f00-c80f-11e9-87b0-a6c8f307cca9.png">

Browser:

<img width="396" alt="Screenshot 2019-08-26 at 14 37 58" src="https://user-images.githubusercontent.com/10400064/63691296-1b530100-c80f-11e9-9e01-678bb5493536.png">

As well as Chrome 76

OS:

MacOS Mojave, 10.14.6 (18G87) & Windows 10

Thank you!!!

**Comment by Darhakexge** [comment]
This is caused because `.mdc-select` is an inline element, just add this in your css

```css
.mdc-text-field, .mdc-select{
	vertical-align: middle;
}
```

**Comment by mishushakov** [comment]
Thanks @Darhakexge that did the job :)
