### ISSUE TITLE
[MDCChipSet] Dynamically adding filter chips doesn't work

### ISSUE THREAD

**Issue by quantumfrost** [material-components/material-components-web#5048]
I am trying to add filter chips dynamically, but they do not work (ex. clicking on them will not toggle the checkmark).

In the below codepen I have some chips in the html source. Before calling the MDCChipSet constructor, I also add some chips through javascript. After the constructor is called, only the ones that were present in the html function properly.

https://codepen.io/quantcon/pen/jONaNVw

I'm quite new to web programming, so it's possible I'm doing something wrong. But I checked the html generated by the javascript code, and it was identical to what the html file has.

**Comment by abhiomkar** [comment]
Please use `.addChip` API of chipSet. Please see https://github.com/material-components/material-components-web/tree/master/packages/mdc-chips#adding-chips-to-the-dom for help.

**Comment by quantumfrost** [comment]
I am modifying the DOM before I call the constructor, so it shouldn't matter if I'm calling the addChip method.
However, I fixed it by using the svg namespace when creating svg and path elements (edited the codepen in case it helps someone).
