### ISSUE TITLE
mdc-list-item class does not handle button elements.

### ISSUE THREAD

**Issue by Garbee** [material-components/material-components-web#505]
### What MDC-Web Version are you using?

`0.8.0` - From Unpkg distribution.

### What browser(s) is this bug affecting?

All supported browsers.

### What OS are you using?

Leenux

### What are the steps to reproduce the bug?

Use `mdc-list-item` styling on a button element. Primary use-case is within a drawer for a logout form.

```html
<div class="mdc-list">
  <a class="mdc-list-item" href="/">
    Home
  </a>
  <a class="mdc-list-item" href="#">
    Gaming
  </a>
  <a class="mdc-list-item" href="#">
    Comics
  </a>
  <a class="mdc-list-item" href="#">
    Contact
  </a>
  <a class="mdc-list-item" href="#">
    Store Information
  </a>
  <a class="mdc-list-item" href="#">
    Cart
  </a>
  <!-- If user is not logged in show login link -->
    <a class="mdc-list-item" href="/login">
      Log in
    </a>
  <!-- Otherwise, we show an inline form to log the user out -->
    <form method="post" action="logout">
      <input type="hidden" value="_token" value="csrf-token-value">
      <button class="mdc-list-item" type="submit">Log out</button>
    </form>
  <!-- end if -->
</div>
```

### What is the expected behavior?

The submission button ("Log out") should display like a regular list item.

### What is the actual behavior?

The button retains normal browser styling. Making it look like it isn't a list item.

### Any other information you believe would be useful?

This code gets it working enough here:

```css
.mdc-list-item {
  width: 100%;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  background: transparent;
  border: none;
}
```

I've only looked at basic CSS styling on anchors, not getting ripple integration or anything. So the full fix may be more involved. Especially with the various modifiers of list items that are possible.

**Comment by yeelan0319** [comment]
I am afraid that covering restyling for all potential children is out of the scope for `mdc-list`. It should be done as a user level specification.
The reason for that is because from the library level, we would like to provide as generic components as possible and only restyle when it is necessary, e.g, `mdc-button` will restyle all native <button> element.

**Comment by Garbee** [comment]
I concur that covering every possibility isn't doable. Tags such as `details` and `summary` for instance get too complex  to handle this way. However, `buttons` are a valid and simple elements that can be a child of a list node. They are clear indicators that upon interacting with the element, something will happen. You could imagine a `div.mdl-list` that contains only `button.mdl-list-item` children to convey that each item has an action when clicked. This also helps dramatically with a11y concerns for developers when building their apps.

The library should be capable of conforming in *most* cases that developers will hit without much of a problem. There will always be edge-cases that are too difficult/not worth including in the library.

**Comment by Garbee** [comment]
Thinking this over some more the button styling would actually be quite odd to do internally and possibly lead to confusion for developers.

This is because a list item itself could have actions within it that are represented with buttons. That would mean by supporting buttons on the list item directly, developers could easily end up with nested buttons and get weird browser actions without realizing it.

So, this actually shouldn't be handled internally since no matter how much this quirk could be documented people would still ignore it and end up with buggy code. Best let developers manually handle this for the few cases where it is needed.
