### ISSUE TITLE
[Documentation] Please update roadmap

### ISSUE THREAD

**Issue by suneelv** [material-components/material-components-web#5051]
There is no roadmap update after January 2019.
Please consider updating it.

It would be good if you can include in roadmap about density spec implementation across components.

**Comment by abhiomkar** [comment]
We use ZenHub to triage our bugs and create sprint backlogs. You can probably see our current sprint here - https://app.zenhub.com/workspaces/material-web-5d375f9ccfdb2800013b39c5/board?repos=75642389

If not we'll sync this to GitHub milestones from next sprint. See our experimental branch for density example usage - https://github.com/material-components/material-components-web/tree/feature/density/packages/mdc-density
