### ISSUE TITLE
Vue MDC Adapter links to deprecated repo

### ISSUE THREAD

**Issue by JonathanTroyer** [material-components/material-components-web#5071]
The [current docs](https://github.com/material-components/material-components-web/blob/master/docs/framework-wrappers.md) for MDC Web on other frameworks reference a [deprecated repo](https://github.com/stasson/vue-mdc-adapter#deprecated). There's a [fork](https://github.com/pgbross/vue-material-adapter) that is up-to-date and meets the [criteria](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md), as far as I can tell. This should be a simple URL swap. I'm willing to open a PR to do this, just need the go-ahead. Thanks!

**Comment by abhiomkar** [comment]
Please send a Pull Request. Thanks!
