### ISSUE TITLE
Top app bar: a CSS class for a "search" input element.

### ISSUE THREAD

**Issue by ibelenski** [material-components/material-components-web#5106]
It would be nice to have a CSS class to apply to a "search" input inside the top app bar, e.g.

```
<header class="mdc-top-app-bar">
  <div class="mdc-top-app-bar__row">
    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
      <button class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button">arrow_back</button>
      <input type="text" class="mdc-top-app-bar__search">
    </section>
  </div>
</header>
```

It would make it easier to implement "search" according to the [guidelines](https://material.io/design/navigation/search.html).

**Comment by bonniezhou** [comment]
Hey, thanks for the feature suggestion. A search input is not in the [Top App Bar guidelines](https://material.io/components/app-bars-top) so there are no plans to put it on our roadmap. 
However the top app bar is flexible and you can include subcomponents in it, like a search box of your own.
