### ISSUE TITLE
`mdc-list` should allow linking entire list item content

### ISSUE THREAD

**Issue by elyobo** [material-components/material-components-web#5114]
## Feature Request
`mdc-list` should allow the `li` content to be wrapped in a link to make the whole item linked; this is possible by breaking the `ul`/`li` semantics already (swap `ul` to `div` and `li` to `a`, keeping the same classes) but it would be preferable to keep the semtantics correct.

### Proposed solution

Styles should accommodate an `ul` -> `li` -> `a` -> various spans as currently supported, as well as `ul` -> `li` -> spans

### Alternatives considered
As noted above, simply switching the `ul` for `div` and `li` for `a` works with the styling, but is semantically a little odd.

**Comment by C-rsin** [comment]
The following structure works for me:

ul.mdc-list > li > a.mdc-list-item

**Comment by elyobo** [comment]
Try adding an avatar and some metadata in there :-/

**Comment by abhiomkar** [comment]
Thanks for reporting this! Can you please provide an example on glitch or codepen?

**Comment by abhiomkar** [comment]
Closing this since inactive.
