### ISSUE TITLE
[MDCTextField] How to change "NOTCH_ELEMENT_PADDING"?

### ISSUE THREAD

**Issue by inf1783** [material-components/material-components-web#5115]
I installed `@material/textfield` via npm and want to change the following value defined in `mdc.textfield.js`:

```javascript
/** @enum {number} */
var numbers = {
  // This should stay in sync with $mdc-notched-outline-padding * 2.
  NOTCH_ELEMENT_PADDING: 8
};
```

How can I change/overwrite this value from my project?

**Comment by bonniezhou** [comment]
Sorry, we don't support overriding padding values since it's not in line with our [spec](https://material.io/components/text-fields/#specs).
