### ISSUE TITLE
[mdc-ripple] no unfocus animation because mdc-states-wash-duration is 15 milliseconds

### ISSUE THREAD

**Issue by mikelpr** [material-components/material-components-web#5119]
when the element is unfocused, no animation is seen (with a screen refresh rate of 60Hz)

I believe it is a [typo in _variables.scss](https://github.com/material-components/material-components-web/blob/f5d217055a8dbcb2899daeb60fa29593b97178ec/packages/mdc-ripple/_variables.scss#L26) (instead of being intentional), and that the intended value was 75ms. that is what I'm using, and it looks good.

**Comment by bonniezhou** [comment]
Can you provide a codepen? The value of 15ms seems correct, since when an element is blurred you shouldn't see a ripple.

**Comment by mikelpr** [comment]
[here it is](https://codepen.io/mikelpr/pen/rNBgqeX)

15ms looks unsightly on mobile (at least on 60Hz) and breaks the illusion of the app feeling native

**Comment by abhiomkar** [comment]
Thanks for the demo! It is intended to keep unwash duration very short so that the previous ripple is immediately dismissed before it is applied to next focusable element.

**Comment by mikelpr** [comment]
why not 0ms in that case? it's not worth computing animations that don't even show because the screen won't refresh until it's already over
