### ISSUE TITLE
[Touch Target] Update component HTML structure to have --touch by default.

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#5121]
Currently component with touch target structure is recommended in [accessibility section](https://github.com/material-components/material-components-web/tree/develop/packages/mdc-button#accessibility), HTML Structure in component README files need to be updated to have [HTML structure](https://github.com/material-components/material-components-web/tree/develop/packages/mdc-button#html-structure) with touch target by default.

**Comment by abhiomkar** [comment]
Can this be closed now?

**Comment by joyzhong** [comment]
Closing. Leaving as is after discussion with binghamj@, since adding touch target to the other examples would make them too verbose.
