### ISSUE TITLE
Prefilled outlined MDCTextField - float-above modifier is not working well for the label

### ISSUE THREAD

**Issue by new-mikha** [material-components/material-components-web#5133]
The MDCTextField doco is [saying](https://material.io/develop/web/components/input-controls/text-field/):

> When dealing with JS-driven text fields that already have values, you’ll want to ensure that you render mdc-floating-label with the mdc-floating-label--float-above modifier class. This will ensure that the label moves out of the way of the text field’s value and prevents a Flash Of Un-styled Content (FOUC).

However, it doesn't work entirely well for the outlined fields. Before the JS arrives, the label is moved up indeed, however it's striken through:
![image](https://user-images.githubusercontent.com/5769929/65758163-eb738200-e15b-11e9-8c4d-d5f6f2409fd3.png)

Here is a sample page. To simulate late arrival of bundle.js, it does`new MDCTextField` when a button is pressed:
https://label--float-above.glitch.me/

Here is the source:
https://glitch.com/edit/#!/label--float-above

The reason why it's happening is that MDCTextField adds two more classes to the DIV with `mdc-notched-outline` class:
`mdc-notched-outline--upgraded` and `mdc-notched-outline--notched`

Expected behaviour: I guess that just adding `mdc-floating-label--float-above` modifier class should be enough. OR at least the doco should be changed.

MDC version: 3.1.1
Relative new Chrome used (77.0.3865.90)
OS: Windows

**Comment by bonniezhou** [comment]
Hi, thanks for the bug. Yes you would need to add the `mdc-notched-outline--notched` class to the `mdc-notched-outline` element in your HTML. (No need to add `mdc-notched-outline--upgraded`, that's done through the JS controller)
Feel free to submit a PR for the doc update!

**Comment by new-mikha** [comment]
Hi @bonniezhou , thanks for the quick reply!

I still suspect it might be technically possible to apply a single class to a single element to achieve the correct result - probably to the mdc-text-field itself. It will make the live of the devs who're using the component a bit easier. 

Would it make sense to try to prepare a corresponding PR? I can have a look into it myself.

**Comment by abhiomkar** [comment]
The problem with outlined text field is that the floating label is rendered inside notched outline that makes it harder to detect if there is a label inside it. I think that is why it uses a modifier (`--notched`) to apply a notch on render time.

See this example:
https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/10/16/15_42_39_928/spec/mdc-textfield/classes/baseline-no-js.html

**Comment by mrethical** [comment]
Also having the same problem here. Has there been a PR to fix this one?

**Comment by new-mikha** [comment]
> Also having the same problem here. Has there been a PR to fix this one?

@mrethical not from what I know. I tried to prepare such PR myself, looks doable but not easy.
