### ISSUE TITLE
[MDCSelect] Enhanced select changes de focus to the first focusable element if is inside in MDCDialog

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#5138]
### Steps to reproduce
1. Go to the [codepen](https://codepen.io/Darhakexge/pen/WNeqOVx)
2. Open the select options
3. The focus changes to the text field
4. Select an option
5. Open the select options
6. The focus no longer changes to another element

### Actual behavior

When MDCSelect is inside in MDCDialog and the menu is opened then the focus changes to the first focusable element of the dialog (either in the title or the content of the dialog).
### Expected behavior

The focus should remain on the select

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |3.2.0
| Browser          |All
| Operating System | Windows 10

**Comment by bonniezhou** [comment]
Hi, I am a little confused as to what the bug is. When I open the select and click on an option, the focus remains on the select.

**Comment by Darhakexge** [comment]
Hi, this is the behavior:
![select](https://user-images.githubusercontent.com/11841575/67231537-1b354300-f405-11e9-87dd-6d41e0b0044c.gif)

**Comment by bonniezhou** [comment]
Ah, I'm not seeing this on Chrome on my Macbook so it might be a Windows issue. I'll add this to the backlog, thanks for reporting this!

**Comment by Darhakexge** [comment]
I'm unable to reproduce this bug in v4.0.0. The select refactoring fixed it.
