### ISSUE TITLE
[MDC Chips] Need Example of Input Chips with MDC Textfield  

### ISSUE THREAD

**Issue by zentek-dmitry-bret** [material-components/material-components-web#5139]
## Bug report
I'll tryed to implement MDC Input Chips(v. 3.2.0) with MDC Textfield(v. 3.1.0).

Unfortunately without success. The two components are not compatible for each other.
Would be good if that would be possible without even trying with CSS and JS.

Thanks in advance

**Comment by abhiomkar** [comment]
We do not support placing chips inside text field as of now.

You can try using full width text field or text field with no label and absolutely position chips. Please let us know how it goes.

Thanks!

**Comment by jimmyhdolores** [comment]
Any demo for this?
