### ISSUE TITLE
[MDC Select] enhanced select setHelperTextContent not working

### ISSUE THREAD

**Issue by Jelmer7** [material-components/material-components-web#5149]
## Bug report

Programmatically setting an enhanced select's helper text does not work.

### Steps to reproduce
**https://codepen.io/jelmer7/pen/poozEae**
1. Create an enhanced select element following [instructions](https://material.io/develop/web/components/input-controls/select-menus/)
2. Initialize element using `new MDCSelect(element)`
3. Add (in)valid styles using `.setValid(false)`
4. Set helper text using `.setHelperTextContent('text')`

### Actual behavior

Helper text is not showing up.

### Expected behavior

Helper text shows up

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | latest
| Browser          | Chrome 77
| Operating System | Windows 10

**Comment by abhiomkar** [comment]
@bonniezhou is this fixed in latest MDC Select changes that are unpublished?

**Comment by bonniezhou** [comment]
You need to add the `aria-controls` attribute to the `mdc-select__selected-text` element, and it needs to match the `id` of the `mdc-select-helper-text` element.

[Here](https://codepen.io/bonniezhou/pen/rNNmYEE) is the same codepen with the fix.

For reference, [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select/helper-text#accessibility) is the instruction under the Select Helper Text docs. Hope this helps!
