### ISSUE TITLE
Data Table destroy() exception

### ISSUE THREAD

**Issue by richturner** [material-components/material-components-web#5150]
## Bug report
The destroy method of MDCDataTable doesn't check if `headerRowCheckbox` is set before calling `destroy` on it, this causes an exception when not using row selection:

```
MDCDataTable.prototype.destroy = function () {
        this.headerRow_.removeEventListener('change', this.handleHeaderRowCheckboxChange_);
        this.content_.removeEventListener('change', this.handleRowCheckboxChange_);
        this.headerRowCheckbox_.destroy();
        this.rowCheckboxList_.forEach(function (checkbox) { return checkbox.destroy(); });
    };
```

### Steps to reproduce
1. Create a Data Table that doesn't use row selection
2. Call destroy on the data table
3. Exception is thrown

### Actual behavior
Exception is thrown

### Expected behavior
No exception should be thrown

### Possible solution
Check if it exists before calling destroy.

**Comment by richturner** [comment]
I guess the `javascript` initialisation is only required when using row selection but that isn't mentioned in the README (it is for other components).

**Comment by abhiomkar** [comment]
That's correct. Clients wouldn't need to instantiate JS when not using row selection. See https://github.com/material-components/material-components-web/tree/master/packages/mdc-data-table#javascript-instantiation README section.

Thanks!

**Comment by nbrown5392** [comment]
> Instantiating MDCDataTable component is only required to add interactions for example, row selection.

To me, this implies there are any interactions other than row selection, and also that it's allowed even if there aren't those interactions. If other interactions are planned, is the MDCDataTable's destroy function going to require all possible interactions, or is it going to check if those even exist before destroying them?

It should be reworded to something like "Only instantiate the MDCDataTable component if it will have row selection interactions."

**Comment by abhiomkar** [comment]
@nbrown5392 Yes, the doc refers to the row selection features. PR Welcome! :)
