### ISSUE TITLE
Are the code generator tool's code open source?

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#5151]
Is there somewhere that I could contribute to the creation of more of these generator tools like the [MDCButton one](https://material-components.github.io/material-components-web-catalog/#/component/button)? I absolutely love the idea and have used them where available. I also have a few extra ideas of how they could be improved so I would love to have a crack at adding some things if I can.

**Comment by abhiomkar** [comment]
Yes, it is open source. You can see the source code in this repository:
https://github.com/material-components/material-components-web-catalog

**Comment by CyborgSemon** [comment]
@abhiomkar I cant seem to get started with the README. Ive cloned down the repo, got node-gyp set up, run `npm i` and it crashes saying that `fibers^3.1.1` failed.
Any idea how to fix it?
