### ISSUE TITLE
[MDCTextField] Text area has scroll bar when overflowing

### ISSUE THREAD

**Issue by jeh-goog** [material-components/material-components-web#5163]
## Bug report
[The spec](https://material.io/components/text-fields/#input-types) shows that when there is more text than a text area can hold, the displayed area scrolls without showing any kind of scroll bar.  The text field shows a scroll bar, however.

### Steps to reproduce
1. Go to /spec/mdc-textfield/classes/textarea.html on the local development server

### Actual behavior
The bottom text area has a scroll bar.

### Expected behavior
The bottom text area should not have a scroll bar

### Screenshots
![image](https://user-images.githubusercontent.com/20590153/66431441-d656e880-e9d0-11e9-88d4-cf2282565dea.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web | 3.2.0 |
| Chrome | 78.0.3904.44 |
| Operating System | Linux |

### Possible solution
overflow: hidden;
![image](https://user-images.githubusercontent.com/20590153/66431530-01413c80-e9d1-11e9-8b55-45bf6b7cc3b8.png)

**Comment by abhiomkar** [comment]
As discussed, having a scrollbar to textarea is expected when it renders overflowing text content.
