### ISSUE TITLE
[MDCSelect] Native select field visible

### ISSUE THREAD

**Issue by jocdu** [material-components/material-components-web#5165]
When using MDCSelect with webpack the css class

`.mdc-select__native-control`

is missing. 

```
...
@import "~@material/select/mdc-select";
...
```
is in the scss file.

When using "material-components-web.min.css" from a CDN it works fine.

The issue is already described here:

https://stackoverflow.com/a/57818765/5907189

**Comment by bonniezhou** [comment]
Hello, we are removing the native select component in the upcoming release. In the meantime I would recommend you use the enhanced select until changes are merged into `master`.
