### ISSUE TITLE
Any integration planned for Svelte?

### ISSUE THREAD

**Issue by QuantumInformation** [material-components/material-components-web#5166]
The only example in the wild I've seen in the wild is here:

https://svelte.dev/repl/e7bf253eb9ef40ababcaf8861cdb7e5e?version=3.12.1

The only integration here is using the class names in the .svelte files.

There's no way I'm gonna write my code like this:

https://codepen.io/abhiomkar/pen/gQWarJ

**Comment by abhiomkar** [comment]
There is a Svelte implementation of MDC Web:
https://sveltematerialui.com
