### ISSUE TITLE
[Button] Outlined outline color should not be set to primary but 12% on-surface

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web#5170]
## Bug report

The ~[Material spec for button theming](https://material.io/components/buttons/#theming)~ Material spec notes that the border color of an outlined button should be set to ~secondary theme~ on-surface at 12%, but [we seem to set it as primary](https://github.com/material-components/material-components-web/blob/master/packages/mdc-button/_mixins.scss#L109)

### Steps to reproduce
1. Create an mdc-button that is outlined
2. Set secondary to be a different color, like red

### Actual behavior

The outline of the button is the same, primary color

### Expected behavior

The outline of the button should be the secondary color (red in this case)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | canary |
| Browser          | chrome |
| Operating System | macos  |

**Comment by abhiomkar** [comment]
For records, it seems like the spec says On Surface, 12%. But not secondary.

![image](https://user-images.githubusercontent.com/47312/66763867-9e3f2200-ee76-11e9-97c0-e160047a909c.png)

**Comment by e111077** [comment]
Heya, perhaps it's a typo in the theming section in the buttons part in material.io:

![image](https://user-images.githubusercontent.com/5981958/66784695-09e1b900-ee90-11e9-87a6-b14f42619968.png)

**Comment by e111077** [comment]
update: internal chat pointed out that the doc I pointed to is not spec, but also that it should still not be primary but on-surface 12%
