### ISSUE TITLE
Addition of dark theme support 

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#5176]
## Feature Request
Dark theme support for the theme component based off already determined variables or separate dark theme dedicated variables.

### Proposed solution
Keep all the same SASS variables and make dark theme versions of those variables that are activated by adding a `.mdc-theme-dark` class to the body. Adding / removing this class will toggle dark mode for the application and its MDC components.
For example, based off the material.io spec, the `$mdc-theme-primary` color would be
```scss
// Light mode primary
#6200ee

// Dark theme primary
#BB86FC
```

### Alternatives considered
If creating dark mode values based off the normal light theme variables is too difficult, then make a default set of dark mode variables, like the light mode variables, and just have them able to be manually changed. The addition of the `.mdc-theme-dark` class to the body element will still function the same as perversely stated.

### Extra info
I've created a concept on how I would implement a dark theme which uses the same idea as having a class for the body, but not the automatically darken variables idea. Hopefully this example could help with coming up with an idea on how to implement it into MDC. I'm not 100% sure where to even start if I was going to try to make a PR with this in mind. So any pointers on where I could start would be appreciated a ton!
Anyway, here is the [example](https://drive.google.com/open?id=1XKmADFB7RqDUitele_uEp-mdEmumL3q5). I hope it helps :D

**Comment by bonniezhou** [comment]
Thanks for the suggestion! Added this to the backlog. Can you throw this into a codepen so we can see it in action more easily?

**Comment by CyborgSemon** [comment]
Yeah sure!
Here it is. https://codepen.io/MrSimmons/pen/GRRNpoy
You can toggle dark mode by clicking the `Toggle dark mode` button on the top left of the preview

**Comment by salamanders** [comment]
Dark mode - so hot right now.  It would be fantastic to support an easy switch to dark theming.

**Comment by abhiomkar** [comment]
Thanks for reporting this. Dark Mode is currently WIP.

Please follow this issue for tracking:
#5253
