### ISSUE TITLE
Commit msg is cannot handle multiple scopes

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#518]
When multiple scopes are affected by a single commits, for example #512, the scope cannot be set to multiple scopes that are being affected.

```
> husky - npm run -s commitmsg

INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
chore(menu, select): Move const definition to separate constants.js file (#387) (#512)
```

In [angular contribution guide](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit), they use * in this case. But this behavior is also not supported by us.

```
> husky - npm run -s commitmsg

INVALID COMMIT MSG: "*" is not an allowed scope ! Valid scope are: animation, auto-init, base, button, card, checkbox, dialog, drawer, elevation, fab, form-field, grid-list, icon-toggle, layout-grid, list, menu, radio, ripple, rtl, select, snackbar, switch, textfield, theme, toolbar, typography, demos, framework-examples, infrastructure, package
chore(*): Move const definition from foundation to separate constants.js file (#387) (#512)
```

The effect of this is relatively small, however, it seems our `determine-pkg-versions.js` rely on the commit message to generate proper summary so as `npm run changelog`.

**Comment by traviskaufman** [comment]
This is actually by design. The way to do multiple scopes is just to omit the scopes altogether, e.g.

```
refactor: Move const definition to separate constants.js file 
```
