### ISSUE TITLE
[BottomSheet] How to scroll underlying page

### ISSUE THREAD

**Issue by spenoir** [material-components/material-components-web#5183]
##  Bug report
Why in the Angular docs example of a Bottom sheet: https://material.angular.io/components/bottom-sheet/overview does the underlying page, with the Bottom Sheet open, scroll (which is the behaviour I'd like); while in StackBlitz: https://angular-mhukw4.stackblitz.io it doesn't?

### Steps to reproduce
1. Click the button to open the Bottom sheet.
2. Try to scroll the underlying page.

### Actual behavior
Underlying page doesn't scroll while bottom sheet open.

### Expected behavior
Underlying page should scroll while bottom sheet open.

### Possible solution
Set some styles on page containers or body; perhaps flex related rules would help.
If there is specific code for locking the underlying page scroll, expose a boolean in the api for toggling it.

**Comment by CyborgSemon** [comment]
@spenoir I think you have the wrong repo?
This is the repo for Angular Material Components: https://github.com/angular/components

**Comment by spenoir** [comment]
oh sorry
