### ISSUE TITLE
Data Table - Option to freeze the table header row

### ISSUE THREAD

**Issue by boikle** [material-components/material-components-web#5185]
## Feature Request
A useful addition to the data table component would be the option to freeze the header row (similar to spreadsheet software). This will allow the table header row to stay in place, while vertically scrolling through table rows.

**Comment by abhiomkar** [comment]
Thanks for the feature request, this feature is in our roadmap.

Our priorities for Data Table in upcoming releases are: Sort & Pagination.

Nothing to do here, I'm closing this issue. Please follow this repo for updates.
