### ISSUE TITLE
[MDCSnackbar] Can't set -1 to timeoutMs property, error in console

### ISSUE THREAD

**Issue by Arnimag** [material-components/material-components-web#5189]
## Bug report
[MDCSnackbar documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-snackbar)
In the description of snackbar there is part in the documentation for timeoutMs property saying: 

> Gets/sets the automatic dismiss timeout in milliseconds. Value must be between 4000 and 10000 (or -1 to disable the timeout completely) or an error will be thrown. Defaults to 5000 (5 seconds

You can't set timeoutMs property to -1 (to disable timeout) as described in documentation because of error in console. 

### Steps to reproduce
1. Create snackbar
2. Set it property "timeoutMs" to -1
3. Try to use "open" method

### Actual behavior
> Error: timeoutMs must be an integer in the range 4000–10000, but got '-1'

### Expected behavior
Can set -1 to disable timeout for snackbar as described in documentation

### Environment
1. Go to this codepen example https://codepen.io/Arnimag/pen/xxxEzVo
2. Click ugly button "open snackbar"
3. Check console for error

### Possible solution
Fix MDCSnackbarFoundation validation to handle -1 as well. Check if further logic works correctly.

**Comment by abhiomkar** [comment]
The changes related to indeterminate timeout are not yet released on NPM.

Please follow this document for `v3.2.0` snackbar:
https://github.com/material-components/material-components-web/blob/v3.2.0/packages/mdc-snackbar/

Thanks!
