### ISSUE TITLE
[mdc-icon-button] types error

### ISSUE THREAD

**Issue by mikaelkaron** [material-components/material-components-web#5192]
## Bug report

According to [the docs](https://material.io/develop/web/components/buttons/icon-buttons/#javascript-instantiation) `MDCIconButtonToggle` is supposed to have a `unbounded` property (just like `MDCRipple`) but this is missing from the types.

### Steps to reproduce

```
const button = new MDCIconButtonToggle(el);
button.unbounded = true; // type error
```

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 3.2.0 |
| Browser          |
| Operating System |

**Comment by CyborgSemon** [comment]
Able to recreate here:
https://codepen.io/MrSimmons/pen/QWWGjQX

Adding toggle unbounded makes no difference to the icon toggle button.
