### ISSUE TITLE
support permanent variant for drawer 

### ISSUE THREAD

**Issue by dbollinger** [material-components/material-components-web#5197]
## Feature Request
Improve support for permanent variant of drawer component.

#### Option 1
A drawer with a "permanent" variant class could include the necessary styling to the drawer and app-content elements.
```
.mdc-drawer--permanent {
  position: fixed;

  ~ .mdc-drawer-app-content {
    margin-left: $mdc-drawer-width;
  }
}
```

#### Option 2
Include additional guidance and documentation in the README for implementing permanent drawer.

### Alternatives considered
The linked demo page includes a permanent variant, but it is wrapped in a root element with additional styling that does not appear to be part of the included styles in the @material/drawer package.

https://material-components.github.io/material-components-web-catalog/#/component/drawer

### Additional context
The drawer's README (https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/README.md) briefly mentions the permanent variant, but does not explicitly state how to implement it.

**Comment by bonniezhou** [comment]
Hi, the default drawer is the permanent one! Please follow [these docs](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/README.md#html-structure) to implement.
