### ISSUE TITLE
[MDCMenuSurface] duplicate export

### ISSUE THREAD

**Issue by dgoogles** [material-components/material-components-web#5198]
## Bug report
index.ts exports Corner and CornerBit twice which causes errors when building with rollup.

### Steps to reproduce
1. Import MDCMenuSurface into a polymer project and try to compile with polymer-cli

### Actual behavior
Rollup fails to compile with the duplicate export error
 
### Expected behavior
This module should be buildable using rollup

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |3.2.0
| Browser          |N/A
| Operating System | OSX

### Possible solution
There is no need to export Corner and CornerBit since they are already exported when you do export * from ./constants

**Comment by dgoogles** [comment]
https://github.com/material-components/material-components-web/blob/80a7ae4300ac94c9998a598c47be04ca828ea14a/packages/mdc-menu-surface/index.ts#L26

**Comment by bonniezhou** [comment]
Hi, are you importing both `constants` and `index`? There is no need to import from both, please follow [these instructions](https://github.com/material-components/material-components-web/blob/80a7ae4300ac94c9998a598c47be04ca828ea14a/docs/importing-js.md) for importing JS, specifically if you're using Webpack/Rollup.

**Comment by abhiomkar** [comment]
I think the fix looks correct, we accidentally exported Corner & CornerBit twice.

Thanks for the PR! It's merged now.
