### ISSUE TITLE
[Layout-grid] Layout Grid not working properly on IE11

### ISSUE THREAD

**Issue by kevinlo123** [material-components/material-components-web#5199]
## Bug report

I am using the layout-grid component to create a basic layout. Everything works fine until i test the layout on IE11 using browser stack testing software. You guys have said that this library should work on IE11 so a little confused. I might be missing a step any help will appreciated.

### Actual behavior
The layout doesn't seem to be getting some styles or some styles aren't working on IE11

### Expected behavior
The layout should be the same across all major browsers that you guys test on.

### Screenshots

![Screen Shot 2019-10-23 at 12 00 38 PM](https://user-images.githubusercontent.com/29260507/67412200-d805dc00-f58c-11e9-9c23-d82c26873621.png)
![Screen Shot 2019-10-23 at 4 05 19 PM](https://user-images.githubusercontent.com/29260507/67429886-11e7da00-f5af-11e9-9a09-671704ef2484.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | Latest
| Browser          | Chrome (but testing on IE11)
| Operating System | MacOS

**Comment by bonniezhou** [comment]
Can you please send us a Codepen of this layout?

**Comment by kevinlo123** [comment]
@bonniezhou Thank you for your response. https://codepen.io/kevinlo123/pen/eYYWMJK

**Comment by kevinlo123** [comment]
@bonniezhou any thoughts on this?

**Comment by kevinlo123** [comment]
Ive noticed the layouts are now working properly has this been resolved?

**Comment by abhiomkar** [comment]
Thanks for sharing the codepen. There wasn't any recent changes to layout grid.

Here is the grid demo page on our catalog:
https://material-components.github.io/material-components-web-catalog/#/component/layout-grid

I'm not able to repro this issue on IE11, works as expected.
![image.png](https://images.zenhubusercontent.com/5cf957522e4fe4691d7f08f0/f00a32bd-96b9-4e0d-b8ca-d1f58a14b474)

Please reference this doc for usage:
https://material.io/develop/web/components/layout-grid/
