### ISSUE TITLE
Add support for Circular Progress Indicator FAB integration

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#52]
Spec reference: https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

See also: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B0NGgBg38lWWbTlSaHdQZEMtalk/components-progressactivity-typesofindicators-061101_Circular_Aspirational_xhdpi_002.webm

See also: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B6Okdz75tqQsa0QwVnd6NVlvWkk/components-progressactivity-typesofindicators-Circular_wFab_xhdpi_003.webm

> Copied from https://github.com/google/material-design-lite/issues/4509

**Comment by MobiusHorizons** [comment]
This looks like a useful feature, and there doesn't seem to have been much movement on it in the last year. I would be interested in contributing, but have no idea where to start. Can anyone point me to how contributing in this repo usually works?

**Comment by Garbee** [comment]
The github standard [contributing.md](https://github.com/material-components/material-components-web/blob/master/CONTRIBUTING.md) details how to get started with designing components and building them out.

**Comment by MobiusHorizons** [comment]
missed that somehow, my bad. thanks @Garbee

**Comment by muhajirframe** [comment]
any progress on this?
