### ISSUE TITLE
MDCDialog.open property is still true after closing dialog.

### ISSUE THREAD

**Issue by h-ikeda** [material-components/material-components-web#520]
### What MDC-Web Version are you using?

> v0.8.0

### What browser(s) is this bug affecting?

> Chrome 57.0.2987.133 (64-bit)

### What OS are you using?

> Windows 7 Professional SP1 (64-bit)

### What are the steps to reproduce the bug?

> Please see https://jsfiddle.net/fq35b6hm/
> click the button and dialog is shown, then click accept/cancel button.

### What is the expected behavior?

> dialog.open after accepted/canceled is false.

### What is the actual behavior?

> dialog.open is still true.

**Comment by traviskaufman** [comment]
Thanks for reporting! This was fixed in #465 and will be released today!
