### ISSUE TITLE
[MDCTextField] Outlined field with long label overlaps if using a leading icon

### ISSUE THREAD

**Issue by robcaldecottvelo** [material-components/material-components-web#5203]
## Bug report
When using an **outlined text field** with a **leading icon** and a long label, the label can end up rendering beyond the outline.

Any CSS workarounds are welcome.

![image](https://user-images.githubusercontent.com/41152621/67558978-e9c3bc80-f70f-11e9-9b31-920876bbbdb8.png)

### Steps to reproduce
Codepen: https://codepen.io/rec71/pen/KKKmJKw

```html
<div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon">
  <i class="material-icons mdc-text-field__icon">favorite</i>
  <input class="mdc-text-field__input" id="text-field-hero-input">
  <div class="mdc-notched-outline">
    <div class="mdc-notched-outline__leading"></div>
    <div class="mdc-notched-outline__notch">
      <label for="text-field-hero-input" class="mdc-floating-label">The quick brown fox jumps over the lazy dog</label>
    </div>
    <div class="mdc-notched-outline__trailing"></div>
  </div>
</div>
```

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | @material/textfield@3.1.0 |
| Browser          | All |
| Operating System | MacOS |

**Comment by CyborgSemon** [comment]
Its looks a bit odd, but here is a workaround I've found.
If you add this to the css:
```css
.mdc-floating-label {
  width: 180px;
}

.mdc-floating-label--float-above {
  width: auto;
}
```

You can check it out here [https://codepen.io/MrSimmons/pen/vYYZKrL](https://codepen.io/MrSimmons/pen/vYYZKrL)
