### ISSUE TITLE
event listen fire multiple times

### ISSUE THREAD

**Issue by massimoliani** [material-components/material-components-web#5221]
On the new version of MDCSelect is not possible to use anymore <select> tag.
Using <ul> I have to insert the onchange event on the listened of MDCSelect class.
When registering the event handler the system fire many and many onchange event everytime I make a change.

I've seen this multiple event firing on some other components too implementing the listening paradigm.

Any possible solutions?

Thank you.

**Comment by treminaor** [comment]
What was the resolution? I am having this issue too.

**Comment by allan-chen** [comment]
Are you on the latest release?

**Comment by allan-chen** [comment]
#5570 and #5783 may be relevant. Both issues are resolved as of 7.0

**Comment by treminaor** [comment]
Assuming the CDN link is the latest release I am yes.
**<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>`**

**Comment by treminaor** [comment]
Also it happens 8 times consistently on my end. If I create the MDCSelect:change event myself and dispatch it then it only fires once, behaving normally.

**Comment by allan-chen** [comment]
Here's a codepen where it seems to be behaving as expected: https://codepen.io/allanchenmdc/pen/MWKEqrK

Please feel free to fork it to reproduce your issue.

**Comment by luclorencini** [comment]
> Also it happens 8 times consistently on my end. If I create the MDCSelect:change event myself and dispatch it then it only fires once, behaving normally.

It's happering eigth times with me as well.

$(document).ready(function () {
    const select = new mdc.select.MDCSelect(document.querySelector('#NivelAcesso'));
    select.listen('MDCSelect:change', () => {
        alert('hello');
    });   
})

This fire 8 alerts on screen.

**Comment by allan-chen** [comment]
@luclorencini  - I have modified this [codepen] to include a version of your code and it only seems to fire once. Please feel free to fork it to reproduce your issue: https://codepen.io/allanchenmdc/pen/MWKEqrK

**Comment by treminaor** [comment]
> @luclorencini - I have modified this [codepen](https://codepen.io/allanchenmdc/pen/MWKEqrK) to include a version of your code and it only seems to fire once. Please feel free to fork it to reproduce your issue: https://codepen.io/allanchenmdc/pen/MWKEqrK

Is it possible we are doing something wrong which would produce this behavior in our local environments? I didn't reply anymore because I could not reproduce the issue in codepen. I fixed my local code with a "hack" to ignore the 7 erroneous event fires but that's not a fix it's just a bandaid.

**Comment by allan-chen** [comment]
Hi @treminaor,

From your previous comment it seems like you're using CDN for the latest version, and if that's confirmed we can rule out any MDC build problems or versioning issues (all components, esp `select`, `menu`, and `list`, must be at v7). I would try to get the absolute bare minimal version of the component running locally - with just the HTML and JS from the codepen + MDC CDN to start and see if the issue persists. 

In essence, we're trying to first get an equivalent environment to the codepen, then see what digressions we can see from there.
