### ISSUE TITLE
[mdc-button] Ripple effect not working.

### ISSUE THREAD

**Issue by Simonmicro** [material-components/material-components-web#5225]
## Bug report
The ripple effect in version 4.0.0 (actual lastest) is not working. The button should react if it is clicked; Instead nothing happens. Switching to the older version 3.2.0 has still the working effect included.

### Steps to reproduce
1. Go to 'https://codepen.io/abhiomkar/pen/gQWarJ'
2. Click on 'GREET'

### Actual behavior
No circular ripple is shown.

### Expected behavior
Ripple should show up.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web         |  lastest / 4.0.0
| Browser          | Firefox 70
| Operating System | Linux Mint 19.2

### Possible solution
Inside codepen: Just switch back to version 3.2.0 - in that version the button ripple is still working...

**Comment by cintaccs** [comment]
according to the changelog - I think you should be expect that - you need to have

<button class="mdc-fab" aria-label="Favorite">
  <div class="mdc-fab__ripple"></div>
  <span class="mdc-fab__icon material-icons">favorite</span>
</button>

now

... I think...

**Comment by Simonmicro** [comment]
Okay, to get the button working again I modified it to:
```
<button class="mdc-button greet-button">
  <div class="mdc-button__ripple"></div>
  Greet
</button>
```
On the other hand my js code to add the ripple to all buttons doesn't work anymore (so I guess it doesn't work for only one button ether):
```
    document.querySelectorAll('.mdc-button').forEach(
    function(ele) {
        mdc.ripple.MDCRipple.attachTo(ele);
    });
```

**Comment by cintaccs** [comment]
do you even have to attach it? I don't think I do have to do that.... I think it is all css based.

**Comment by allan-chen** [comment]
Hi! The ripple works without javascript. Javascript is needed if you need to programmatically deactivate/activate the ripple. [Here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button#javascript-instantiation) is more information on this. Let me know if you have more questions.
