### ISSUE TITLE
[mdc-select] @latest CSS from unpkg removes support for mdc-select?

### ISSUE THREAD

**Issue by c-tanner** [material-components/material-components-web#5226]
## Bug report
Select components became unstyled (showing default HTML select menu, see screenshot). Switching to another CDN has seemed to fix this issue. No network issues were detected.

### Steps to reproduce
1. Include `https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css`
2. Create mdc-select element

### Screenshots
![Screen Shot 2019-11-04 at 10 25 56 AM](https://user-images.githubusercontent.com/55005098/68147158-50a25c00-feee-11e9-8094-b2314f2a0fa9.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0
| Browser          | Chrome (latest), FF Dev (latest), Safari (latest)
| Operating System | Mac OS 10.14.6

## Solution

Switched CSS to `https://cdnjs.cloudflare.com/ajax/libs/material-components-web/4.0.0-canary.e851d4f40.0/material-components-web.min.css`

** Edit

I see now that 4.0.0 [changes the HTML structure](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md) for MDCSelect, but the description of changes isn't very clear:

> In MDCSelect, HTML structure changed: the select anchor is now wrapped in a parent element, and the anchor's sibling is the select menu.

Can we get updated documentation or an example to work with? Still confused why the CDNJS 4.0.0 works fine while unpkg 4.0.0 breaks the styling.

**Comment by allan-chen** [comment]
Hi,
Thanks for your question! The [README](https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/README.md) for select has been updated and should have working examples. Please let me know if you have more questions.
