### ISSUE TITLE
Density - looks like great achievements in the new 4.0 release

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#5228]
the https://glitch.com/~material-density examples looks extremely useful and IMO addressing a much needed/requested issue on the general density of MDC components.

I can get Text Field, Checkbox, Radio working - but where do I find where to apply the density class on List and Tab Bar?

```
//
 // Checkbox
 //
 .mdc-checkbox {
   &.dense-compact {
     @include mdc-checkbox-density(-3);
   }
 
   &.dense-comfortable {
     @include mdc-checkbox-density(-1);
   }
 
   &.dense-default {
     @include mdc-checkbox-density(0);
   }
 }
````
from your example I can get this to work for Checkbox and Text Fields - but on which element class (mdc-???) do I set this for List? and Tab Bar? ... and what are the plans for MDCSelect? having them not in the same density as the rest of the elements is kind of not a solution?

**Comment by allan-chen** [comment]
Hi, thank you for your questions. Currently MDC Select is undergoing a refactor, but density will be available soon for it as well. In general, density mixins should be applied to the root element of the component. Please let me know if you have more questions!
