### ISSUE TITLE
[MDCSelect] Wrong label behavior when selected option has value=""

### ISSUE THREAD

**Issue by JacobBlana** [material-components/material-components-web#5229]
## Bug report
In my latest try of getting the MDC framework work for our product. I discovered weird behavior. Many of already created select elements have most of the time first option without value. In this situation the label doesnt float and acts like nothing is selected, even if i select the option and then cancel focus the label it self floats back down. 

I tried filling the value with random char, which obviously works but i was told by our other developers that i should not be sending any undefined values.

Is this correct behavior ?

### Steps to reproduce
1. Use select with multiple options
2. Create first option without value - the behavior will be visible on init
3. When you then try selecting any value it works normally
4. But when selecting the option without value the label floats down again

| Software         | Version(s) |
| ----------------| ---------- |
| MDC Web       |   "^3.2.0"
| Browser           |   Chrome 78
| Operating System |    Win 10

**Comment by allan-chen** [comment]
Hi,
If I understand correctly, the behavior you describe is also seen in [the demo page](https://material-components.github.io/material-components-web-catalog/#/component/select) (see enhanced select at the bottom). This is intended behavior - when nothing (`""`) is selected, the label remains in the default floated-down position to indicate this. Please let me know if you have more questions.
