### ISSUE TITLE
[MDCSelect] 4.0.0 removed the hidden form element

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#5230]
## Bug report
According to the new mdc-select specification we no longer have a hidden input element to capture the selected value. 

When using the mdc-select on a submit form - how is the selected value intended to be captured?

**Comment by cintaccs** [comment]
relates to #4799

**Comment by cintaccs** [comment]
@bonniezhou : the problem I have is that I don't know whether it was intended to remove the hidden input element under the mdc-select or it will pop back in again (which I think it should) in a future build.

there are 2 scenarios for grabbing the selected value - with or without an underlying model for the selected value. 

Scenario 1: With an underlying model the mdc-select listener that you provide will handle the value update - which is fine and works. GOOD!

Scenario 2: is a mdc-select component implemented on a submit form or without an underlying data-model. In this case we either:
 A: need to write the value somewhere using your provided listener (or use a queryselect to grab the selected item from the list elements (which is no problem either)). But where to write the value?
B: not writing the selected value anywhere - in which case it will not be picked up by a submit button and not delivered as part of a form submit. NOT GOOD.

In my code I can handle both cases - but it would be nice to know whether the INPUT hidden will suddenly pop back up again in the specification? or whether I can consistently assume that it will not suddenly appear with the value (which would then be redundant to any custom solutions made?

**Comment by cintaccs** [comment]
I have written an alternative solution using MDCText, MDCMenu and MDCList components. Because I use the MDCText - I now again have a form element for submitting. It uses type ahead and actually allows more characters to match an entry than the native SELECT - and your MDCLIST keyboard handling at least for the single select navigation is as good as native ever was. I got lost in foundations, foundation_, defaultfoundation (I therefore use querySelectors instead) so it is not following the component skeletons well enough for pushing as a suggestion for a general solution - however it integrates well with the other components.

**Comment by sclausen** [comment]
Would you mind sharing some code? I can't understand, why submit form support has been deliberately removed and am currently stuck with this issue too :frowning_face:

**Comment by bonniezhou** [comment]
sorry for the delay, the hidden input element seems to have been overlooked during a refactor. Created #5428.

**Comment by sclausen** [comment]
@bonniezhou [this comment](https://github.com/material-components/material-components-web/issues/4799#issuecomment-550085500) stated that it has been removed on purpose.

**Comment by bonniezhou** [comment]
@sclausen That comment explains removal of support for native `<select>`, not the removal of the hidden `<input>` element
