### ISSUE TITLE
MDCSelect 4.0.0 fires change event twice

### ISSUE THREAD

**Issue by jocdu** [material-components/material-components-web#5234]
## Bug report
MDCSelectbox 4.0.0 fires change event twice.

When setting a value via javascript the change event is fired twice. I think it should not fire an event at all when changed programmatically.
There was already an bug report which confirms this: https://github.com/material-components/material-components-web/issues/3577

Here is a example of the issue:
Codepen: https://codepen.io/Jochen99/pen/VwwXRzm

**Comment by maicol07** [comment]
@bonniezhou this issue is also in latest canary
