### ISSUE TITLE
Ripples get cut-off when they are nested in mdc-toolbar__section

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#524]
### What MDC-Web Version are you using?

> Master

### What browser(s) is this bug affecting?

> All browser

### What are the steps to reproduce the bug?

> Here is an [example](https://material.uplabs.com/posts/google-material-design-components-demo) the ripples get cut-off

### What is the expected behavior?

> The ripples should complete

### What is the actual behavior?

> The ripples get cut off to the shape of mdc-toolbar__section 

### Any other information you believe would be useful?

We added `overflow:hidden` for #508 to accommodate very long section. It seems removing that from `mdc-toolbar__section` is necessary but I haven't yet thought a way to solve these 2 problems together without introducing extra structure. Thoughts?

**Comment by anton-kachurin** [comment]
How about using `min-width: 0` instead of `overflow: hidden`? Here is an [example](http://codepen.io/anton-kachurin/pen/WjrWwp).

**Comment by traviskaufman** [comment]
@anton-kachurin that fix seems to magically work! ✨ whoah ✨ Happy to accept a PR if you'd like to submit one! And thanks for all of your continued help with our codebase!
