### ISSUE TITLE
[MDCCard] The actions area of the docs have not been updated to the new MDCButton spec

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#5257]
Card docs: https://github.com/material-components/material-components-web/tree/master/packages/mdc-card#actions

Button docs: https://github.com/material-components/material-components-web/tree/master/packages/mdc-button#html-structure

Im not sure if any other packages that use MDCButtons also haven't been updated. I just spotted this one today. I'll take a look around everything when I have some spare time to check and I'll file a PR when I can. unless anyone else wants to do it :)

**Comment by asyncLiz** [comment]
Related to #5297

**Comment by Darhakexge** [comment]
Same in dialog and snackbar docs

**Comment by asyncLiz** [comment]
Thanks @Darhakexge!
