### ISSUE TITLE
Drawer list with ripple

### ISSUE THREAD

**Issue by Shyam-Chen** [material-components/material-components-web#526]
http://codepen.io/Shyam-Chen/pen/RVPexY?editors=1010

![default](https://cloud.githubusercontent.com/assets/13535256/25111991/f2538f8e-2420-11e7-8016-dfd356a671ec.PNG)

**Comment by vivekmarakana** [comment]
Issue seems to be with `left: -16px;` in `.mdc-list-item.mdc-ripple-upgraded`.

@traviskaufman Also, we should add `box-sizing: border-box;` to all element as `width: 100%` overflows the space when there's padding involved.

**Comment by Shyam-Chen** [comment]
I added this.

```css
.mdc-list-item.mdc-ripple-surface {
  box-sizing: border-box;
  left: 0;
}
```

![default](https://cloud.githubusercontent.com/assets/13535256/25116442/63367ec8-243f-11e7-8049-bdad2199ea97.PNG)

**Comment by Shyam-Chen** [comment]
Before:

![default](https://cloud.githubusercontent.com/assets/13535256/25111991/f2538f8e-2420-11e7-8016-dfd356a671ec.PNG)

***


Add this

```css
.mdc-list-item.mdc-ripple-surface {
  box-sizing: border-box;
  left: 0;
}
```

***

After:

![default](https://cloud.githubusercontent.com/assets/13535256/25116442/63367ec8-243f-11e7-8049-bdad2199ea97.PNG)

**Comment by traviskaufman** [comment]
@vivekmarakana the `box-sizing` suggestion is a good one, however, @Shyam-Chen could you clarify exactly what your issue is, and what you're trying to achieve? Is the issue that the drawer items are misaligned?

**Comment by Shyam-Chen** [comment]
http://codepen.io/Shyam-Chen/pen/aWNRWb?editors=1000

**Comment by mhuebert** [comment]
I am also experiencing this problem. In a permanent drawer, adding the class `mdc-ripple-upgraded` to an `mdc-list-item` removes its left padding.

It looks like the cause is `.mdc-permanent-drawer`'s handling of `.mdc-list`. The rule:

```css
.mdc-permanent-drawer .mdc-list-group, .mdc-permanent-drawer .mdc-list {
    padding-right: 0;
    padding-left: 0;
```

overrides the padding in the rule:
```
.mdc-list-item.mdc-ripple-upgraded {
    ...
    left: -16px;
    padding: 0 16px;
```

Below is an example. "Lists" is a mdc-list-item with ripple, "Checkbox" is identical but without a ripple.
<img width="170" alt="screenshot 2017-04-24 01 28 35" src="https://cloud.githubusercontent.com/assets/165223/25318364/65117232-288d-11e7-9c40-493877d94ec3.png">

**Comment by traviskaufman** [comment]
Thanks for doing that digging @mhuebert! Submitting a fix.

**Comment by mhuebert** [comment]
Fix on the drawer works great - I'm now implementing mdcSimpleMenu, and we have the same problem there:

```css
.mdc-simple-menu .mdc-list-group, .mdc-simple-menu .mdc-list {
    padding: 0;
}
```

In the screenshot below, the second ListItem in the SimpleMenu has a ripple, the first does not:

<img width="860" alt="screen shot 2017-05-02 at 7 47 24 pm" src="https://cloud.githubusercontent.com/assets/165223/25631296/393f703e-2f70-11e7-9d24-ec86e62730d5.png">

**Comment by carlitux** [comment]
Using ripple on drawer the width is bigger than the 100% of the parent width. End detail is hidden. You can se here https://carlitux.github.io/material-toolbox
