### ISSUE TITLE
[MDCMenuSurface] properties are not proxied to foundation methods

### ISSUE THREAD

**Issue by dbollinger** [material-components/material-components-web#5261]
## Bug report
MenuSurface component doesn't open

### Steps to reproduce
Recreated on codepen:
https://codepen.io/howie_bollinger/pen/abbPwbZ

### Actual behavior
setting `myMenuSurfaceInstance.open` to true does not cause the instance of the component to open.

### Expected behavior
Setting open to true should call trigger the foundation's open method.

### Your Environment:
MDC Web
Chrome
MacOS

### Additional context
The [README](https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu-surface#mdcmenusurface-properties-and-methods) states that the open property is a proxy to the foundation methods, but they don't appear to be implemented:
https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu-surface/component.ts

### Possible solution
Implement the same proxy methods as the MDC Menu component: https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/component.ts#L99

**Comment by bonniezhou** [comment]
The API for Menu Surface changed such that `open` is now a method, not a property.
Thanks for the catch! Doc update is in #5291. Let us know if we're missing anything else :)

**Comment by dbollinger** [comment]
Thanks for the update!
