### ISSUE TITLE
(mdc-auto-init) Could not find constructor in registry for MDCPersistentDrawer

### ISSUE THREAD

**Issue by neclepsio** [material-components/material-components-web#527]
MDCPersistentDrawer constructor seems to not be registered in MDCAutoInit: when using it, the error message in the title is displayed.

**Comment by traviskaufman** [comment]
😐 whoops. Will make a hotfix release for this today. Thanks for catching so quickly!

**Comment by traviskaufman** [comment]
Released with MDC-Web@v0.9.1
