### ISSUE TITLE
[select] Selecting option on select component--outlined creates extra space

### ISSUE THREAD

**Issue by brycekirk** [material-components/material-components-web#5270]
## Bug report
Clicking the blank option on a select component adds some space somewhere that moves all other elements

### Steps to reproduce
1. Go to https://material-components.github.io/material-components-web-catalog/#/component/select
2. scroll down to Demos
3. Click the select field under Shaped Outline
4. Make a selection
5. Some space is created or eliminated and the elements/page moves

### Your Environment:

This is on the Material Web Components site itself, and when I try to implement it.

**Comment by abhiomkar** [comment]
Thanks for reporting this issue.

Seems like there is additional 4px vertical space added when mdc-select is in idle state:

![image.png](https://images.zenhubusercontent.com/5cf957522e4fe4691d7f08f0/e465bc47-a252-4d8f-a3da-93da33a1d862)

Adding `display: inline-flex` seems to remove additional whitespace:

![image.png](https://images.zenhubusercontent.com/5cf957522e4fe4691d7f08f0/4edb04ec-8438-455a-99aa-a0d16cfc381e)

**Comment by brycekirk** [comment]
That does it, thanks! Might also need to add `width: 100%;` depending on usage.

**Comment by asyncLiz** [comment]
Reopening because we should fix this on our end

**Comment by allan-chen** [comment]
This should be fixed after 2673adb. Closing - feel free to reach out with any further issues.
