### ISSUE TITLE
[MDCTopAppBar] mdc-top-app-bar--fixed-adjust required for standard Top App Bar

### ISSUE THREAD

**Issue by zbot473** [material-components/material-components-web#5271]
For a standard app bar, the subsequent element shouldn't need an `mdc-top-app-bar--fixed-adjust` class. However, it starts under the app bar and requires the `mdc-top-app-bar--fixed-adjust` to be displayed properly.

I'm using the CDN, with EJS.
Here are the results. I have blacked out personal information.
<img width="1280" alt="Screen Shot 2019-11-23 at 10 30 30 PM" src="https://user-images.githubusercontent.com/49821700/69489256-005e5000-0e43-11ea-892b-3a0644518efe.png">
<img width="1280" alt="Screen Shot 2019-11-23 at 10 30 45 PM" src="https://user-images.githubusercontent.com/49821700/69489257-00f6e680-0e43-11ea-8018-786632c6af18.png">

**Comment by abhiomkar** [comment]
`mdc-top-app-bar--fixed-adjust` class name is required to add offset to top app bar content as per https://github.com/material-components/material-components-web/tree/master/packages/mdc-top-app-bar

Are there any references that explains otherwise?
