### ISSUE TITLE
[MDCCheckbox] Replace unique-id with a deterministic function

### ISSUE THREAD

**Issue by jathak** [material-components/material-components-web#5284]
## Feature Request
mdc-checkbox [currently uses](https://github.com/material-components/material-components-web/blob/d6a1d4b/packages/mdc-checkbox/_mixins.scss#L300) the built-in [`unique-id`](https://sass-lang.com/documentation/modules/string#unique-id) function when generating keyframes. This function is non-deterministic, which can hurt caching when using mdc-checkbox in a complicated build.

### Proposed solution
To make the result of compiling mdc-checkbox deterministic, we can replace this call to `unique-id` with a call to a user-defined function similar to:

```
$_next-id: 0 !default;

@function deterministic-unique-id() {
  $_next-id: $_next-id + 1 !global;
  @return u#{$_next-id};
}
```

### Alternatives considered
An alternative would be to add a method to seed randomness in the Sass compiler (for both `unique-id` and `random`) but the main benefit of these functions being something built-in is that they're likely to be unique across compiler runs as well.

### Additional context
b/145002342 has internal context on this

**Comment by allan-chen** [comment]
Closed by #5404
