### ISSUE TITLE
Add support for arbitrarily cascading dropdown menus

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#53]
Spec reference: https://www.google.com/design/spec/components/menus.html#menus-usage

> Copied from https://github.com/google/material-design-lite/issues/4508

**Comment by sconover** [comment]
@lynnmercier Does your team still have plans to implement this feature?

**Comment by sclausen** [comment]
Is there any place where discussions happen? I regularly see answers or close comments which lead to other issues with comments like "It's not on our roadmap" [Closed] for things which are either valid feature requests regarding the md spec or issues which haven't even been briefly discussed anywhere I can see.

I don't demand you working on this or that feature, but a little transparency in decision making would feel a bit less being snubbed.
