### ISSUE TITLE
Unexpected token: name (MDCRipple) from UglifyJS

### ISSUE THREAD

**Issue by amrittb** [material-components/material-components-web#531]
I am using [Laravel Mix](https://github.com/JeffreyWay/laravel-mix/) to compile my assets. **Laravel Mix** has a script to compile minified assets.

```sh
npm run production
```
This, in turn, invokes **UglifyJS** to minify assets.
During this step it throws an error.
```sh
Unexpected token: name (MDCRipple) [./~/@material/ripple/index.js:25,0]
```

I am using **material-components-web** version **0.8.0**.

**Comment by Garbee** [comment]
Is your webpack build setup to use babel with the es2015 presets? That is what fixed the same type of error for me [and others](https://github.com/joeeames/WebpackFundamentalsCourse/issues/3).

**Comment by amrittb** [comment]
Yes. The package I mentioned [Laravel Mix](https://github.com/JeffreyWay/laravel-mix/) has support for es2015, .vue files, .jsx files.

**Comment by Garbee** [comment]
You may want to try the [uglify version for harmony](https://github.com/JeffreyWay/laravel-mix/issues/462) syntax.

Looking at [other issues](https://github.com/JeffreyWay/laravel-mix/issues/186) on mix as well, it seems like this is all related to the various syntax differences between projects. You just need to make sure your babel is configured right.

This is my config that works.
<details>
<summary>.babelrc</summary>

```json
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-es2015-block-scoping"
  ]
}
```

</details>

**Comment by amrittb** [comment]
I have no idea where I went wrong.

Here is my **package.json** file.

```json
{
  "name": "project",
  "version": "1.0.0",
  "description": "Project",
  "main": "index.js",
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack --progress --hide-modules",
    "watch": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules",
    "server": "php -S localhost:8080 -t public",
    "hot": "cross-env NODE_ENV=development webpack-dev-server --inline --hot",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-plugin-transform-es2015-block-scoping": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "cross-env": "^4.0.0",
    "laravel-mix": "^0.10.0",
    "material-components-web": "^0.8.0",
    "webpack": "^2.4.1",
    "webpack-dev-server": "^2.4.2",
    "uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony"
  }
}

```

Here is **.babelrc** file.
```json
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-es2015-block-scoping"
  ]
}
```

**Comment by traviskaufman** [comment]
Hey @amrittb,

We use uglifyJS ourselves after a pass using babel and it seems to work fine for us. Code you link us to a demo repo we could use to triage the issue? It sounds like something is off with your build system.

**Comment by traviskaufman** [comment]
Any updates on this @amrittb?

**Comment by amrittb** [comment]
I have created a Demo Repository. Here - [Test Repository](https://github.com/amrittb/laravel-mix-material-components-web-test)

**Comment by lpirola** [comment]
I got this same bug with this repo: https://github.com/nossas/vivos-em-nos 

When I try to ```yarn run build``` the exception occur.

**Comment by Garbee** [comment]
@lpirola Do you mind pointing out how MCW is being used in that vivos-em-nos repository? I'm not seeing it being included right off.

**Comment by lpirola** [comment]
After have commented I tried to add uglify with harmony and the build work like a charm!

**Comment by lpirola** [comment]
@Garbee It's used through https://github.com/prateekbh/preact-material-components 

Thanks for fast reply! :)

**Comment by Garbee** [comment]
@amrittb Your problem is you aren't running *js* files through the babel-loader. There is no rule set for js files. Once you run the JS files through babel things compile properly.

I suspect what is going on for you @lpirola is around the same lines. You need to make sure the material component JS files get ran through babel. This means allowing `node_module` stuff to be compiled through babel.

**Comment by lpirola** [comment]
@Garbee you are right, thanks!

**Comment by amrittb** [comment]
@Garbee, Thanks! It worked like a charm.

**Comment by MicroDreamIT** [comment]
I am have same problem, can you please take a look, 

https://github.com/JeffreyWay/laravel-mix/issues/878

**Comment by crocodilered** [comment]
I have material-components-web@0.44.0 and the issue is still here :-(

**Comment by shmshd** [comment]
@crocodilered use [`terser-webpack-plugin`](https://github.com/webpack-contrib/terser-webpack-plugin) instead of `uglifyjs-webpack-plugin`.
