### ISSUE TITLE
Importing several components creates a long list

### ISSUE THREAD

**Issue by xeon826** [material-components/material-components-web#5311]
I've imported a lot of components and it's created a sizable list, can I just do something like 
`import { MDCRadio, MDCChipSet, MDCMenuSurface } from @material;`
```
import {
  MDCRadio
} from '@material/radio';
import {
  MDCChipSet
} from '@material/chips';
import {
  MDCMenuSurface
} from '@material/menu-surface';
import {
  MDCTextField
} from '@material/textfield';
import {
  MDCList
} from '@material/list';
import {
  MDCMenu
} from '@material/menu';
import {
  MDCRipple
} from '@material/ripple';
import {
  MDCFormField
} from '@material/form-field';
import {
  MDCCheckbox
} from '@material/checkbox';
import {
  MDCSelect
} from '@material/select';
import {
  MDCTopAppBar
} from '@material/top-app-bar';
import {
  MDCDialog
} from '@material/dialog';
import {
  MDCSnackbar
} from '@material/snackbar';

```

**Comment by nirmpate** [comment]
I would recommend breaking down your code into smaller files and importing these components in their respective spots.

Or you can barrel them in one file.  Heres an example.  https://medium.com/@klauskpm/do-a-barrel-export-aa5b79b76b05

**Comment by allan-chen** [comment]
Feel free to try @nirmpate 's suggestion (thanks Nirmal!) Alternatively, if you find yourself importing most of the components perhaps importing the master library [like so](https://github.com/material-components/material-components-web/tree/master/packages/material-components-web#including-the-javascript) may help.

**Comment by xeon826** [comment]
I went ahead and separated it into several smaller files, thanks.
