### ISSUE TITLE
Dense property on button with no result

### ISSUE THREAD

**Issue by Mansi1** [material-components/material-components-web#5318]
Dense disappeared in scss [selector=mdc-button--dense]
![image](https://user-images.githubusercontent.com/12079044/70476620-5f74c380-1ad7-11ea-9baa-bf32d084e5c5.png)
Have to look like 
![image](https://user-images.githubusercontent.com/12079044/70476707-92b75280-1ad7-11ea-9fca-5fb71ac4ea6a.png)

**Comment by allan-chen** [comment]
Hello,

Thanks for filing an issue. As of version 4.0.0 the `mdc-button--dense` class was removed in favor of density [mixin](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button#advanced-sass-mixins), namely `mdc-button-density($density-scale)`.  See [changelog](https://github.com/material-components/material-components-web/blob/067b7547c24a68ccfe34515679941b5b0c1ca9a3/CHANGELOG.md) at the bottom of v4.0.0.
