### ISSUE TITLE
Position fixed on body-tag (on mobile) disrupts UI 

### ISSUE THREAD

**Issue by MarcoTroost** [material-components/material-components-web#5327]
Hi,
We use an mdc-dialog to construct a menu from the bottom-bar. 
On mobile however, "position: fixed" on the body-tag completely disrupts the interface underneath.

Adding width: 100% to .mdc-dialog-scroll-lock seems to resolve this. 

![mdc-dialog-scroll-lock-issue](https://user-images.githubusercontent.com/16369103/70723889-f0c38000-1cf9-11ea-8f6d-896f953759ab.jpg)

Hope this could be helpfull

**Comment by allan-chen** [comment]
Hi,

Thanks for the information! Does this happen only when a dialog is instantiated? Also, do you have a codepen demonstrating this issue so we can investigate whether a general fix is needed?

**Comment by MarcoTroost** [comment]
Hi Allen,

Disruption of the UI happens when a user clicks the button "Rubrieken" in the bottom-bar; it opens a dialog that facilitates a menu-list.

The project is only available on our develop-server, but i've saved the page to a sandbox-folder on my own domain. Perhaps this could be of assistance.

https://www.marcotroost.com/sandbox/prikbord.htm

kind regards, Marco

**Comment by allan-chen** [comment]
Hi Marco,

It seems like the dialog doesn't play well with adding `position:fixed` on the body tag; may I ask the motivation behind this? For now it seems like your approach of adding `width: 100%` is the best way to resolve this for your particular use case.

**Comment by abhiomkar** [comment]
Unfortunately dialog component does not support this layout.

Please consider using [MDCMenuSurface](https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu-surface) for use-cases like this. You'll need to create your own scrim if you use menu surface.
