### ISSUE TITLE
Remove Stale Branches

### ISSUE THREAD

**Issue by BhavyaSingh2611** [material-components/material-components-web#5340]
## Feature Request

There are so many stale branches in material design repo!!!! as compared to other design systems repo

### Proposed solution

the solution is to delete the stale branches which arent in use

**Comment by allan-chen** [comment]
Hi Bhavya,

Thanks for bringing this up! We're working on removing the stale branches in the repository. As a start, I've removed all the `greenkeeper/*` branches as they are no longer needed.

**Comment by allan-chen** [comment]
Removing `greenkeeper/*` brought branch count from 550+ --> 200
