### ISSUE TITLE
[text-field] floating label notched width

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#5341]
when using a floating label in dense mode

```
<div class="mdc-text-field mdc-text-field--outlined dense-compact">
<input type="text" class="mdc-text-field__input String" id="FULLNAME" 
value="Adam Smith" autocomplete="off" autocorrect="off" 
autocapitalize="off" spellcheck="false">

<div class="mdc-notched-outline 
mdc-notched-outline--upgraded mdc-notched-outline--notched">

<div class="mdc-notched-outline__leading"></div>

<div class="mdc-notched-outline__notch" style="width: 62px;">
<label for="FULLNAME" 
class="mdc-floating-label mdc-floating-label--float-above" style="">
Full name</label>
</div>

<div class="mdc-notched-outline__trailing"></div>
</div>
</div>
```

I get the problem that the notched outlined label (above the input field when a value is entered) gets cut. There are a couple of scenarious resulting in this - e.g. having a value initially in the input field will initialize the field correctly - but if the value is deleted (empty input) then the floating label gets cut.

I have tried various ways to get around it - but because a calculated width (in this case 62px) is hardcoded into the element automatically I can't figure out a work around.

Is it because of dense mode?

```
.mdc-floating-label {
    :not(.mdc-notched-outline--notched) & {
         font-size: 0.875rem;
    }
    .mdc-notched-outline--notched & {
        font-size: 1rem;
    }
}
````

I am trying above but I can't get around the hardcoded width I think...

Does anyone else have similar problems (I have tried this for a while on both 3.0, 4.0 and latest canary builds)?

**Comment by allan-chen** [comment]
Hi Carsten,

Thanks for reaching out. Can you create a codepen for this so that we can reproduce it and investigate?

**Comment by cintaccs** [comment]
Hi Allan-Chen,

Thanks for getting back!
I created a pen - and maybe found the issue... might be some of my own customisation causing the issue. Then I apologise for creating the issue! Remains is a small jumping on entering a filled field... 

<p class="codepen" data-height="265" data-theme-id="default" data-default-tab="html,result" data-user="cintaccs" data-slug-hash="VwYPaeP" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="MDCFloating">
  <span>See the Pen <a href="https://codepen.io/cintaccs/pen/VwYPaeP">
  MDCFloating</a> by Carsten Sørensen (<a href="https://codepen.io/cintaccs">@cintaccs</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>




If you change the the font-size to 1rem (that was what I originally had) in below:

```
.mdc-text-field--outlined.dense-compact.mdc-notched-outline--upgraded .mdc-floating-label--float-above, 
.mdc-text-field--outlined.dense-compact .mdc-notched-outline--upgraded .mdc-floating-label--float-above {
    -webkit-transform: translateY(-26.75px) scale(.75);
    transform: translateY(-26.75px) scale(.75);
    //font-size: 1rem;
    font-size: .875rem; //0.875 fix the issue!
}
```
Then you can see the original problem.

Thanks for initiating the solution  :-)
Best regards,
Carsten

**Comment by allan-chen** [comment]
Really happy that you were able to resolve this issue! And thanks for providing such detailed instructions to reproduce it. I was able to reproduce the small jumping. From a preliminary look seems like it's caused by the border width's increase from 1px --> 2px in the focus state.

**Comment by cintaccs** [comment]
Good catch with the border width increase! however I can't find where that is set... 
Thanks!
