### ISSUE TITLE
Question: Applying [mdc-density] to general web server.

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#5343]
My web server is general using CDN.(without npm, webpack, node. `but I have sassc in local`).
I'm not using node.js in production.
is it possible to applying `mdc-density` for some components(button, data-table, ...)?
If so, could you give me an example?
thanks

**Comment by allan-chen** [comment]
Hi,

Assuming you are able to compile SASS, density can be applied by applying the relevant SASS mix-ins in each component. The general guideline for applying density is [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-density#basic-usage). In short, you need to call the density mix-ins made available in each component, such as `mdc-data-table-density($density-scale)` for data-table.

**Comment by diuming** [comment]
@allan-chen thanks for response.
I'm not familiar with web front end. 

I try to compile scss to css using sassy in CLI, but I get errors.

Q)Do I need to download the whole `material-components-web` to local?
thanks

following are my steps

1)create a file `mybutton.scss`
---
```
@import "@material/button/mixins";
.my-custom-button {
  // Sets button density scale to `-3`, i.e. button height to `24px`.
  @include mdc-button-density(-3);
}
```
2)compile it to css in terminal
---
```
sassc mybutton.scss mybutton.css
```

error messages
---
```
Error: File to import not found or unreadable: @material/button/mixins.
        on line 1:1 of mybutton.scss
>> @import "@material/button/mixins";

   ^
```

**Comment by allan-chen** [comment]
You would need the material components SASS files at the minimum locally. We recommend using npm, as it will download the required dependencies for you. [Here](https://github.com/bonniezhou/material-starter-kit) is a quick-start kit that might help you get up and running. In short, you can add your app's custom mix-ins in `app.scss`, then run:

```
npm install
npm run-script build
```
which will produce the compiled `bundle.js` and `bundle.css` in the `dist/` folder. 

Hope this helps!

**Comment by diuming** [comment]
@allan-chen  thanks,
so, I can't get rid of npm, webpack and node.js. right?

**Comment by allan-chen** [comment]
Assuming we want to compile from SASS, getting rid of NPM would mean you'd have to download and place the dependencies in the right places manually, which would be possible but impractical.

**Comment by diuming** [comment]
@allan-chen thanks
I got it.
