### ISSUE TITLE
Picker Documentation

### ISSUE THREAD

**Issue by kmlkrks** [material-components/material-components-web#5346]
We want to use our picker component but can't find user doc. How to find picker documentation?

**Comment by IvanFrescas** [comment]
Maybe this documentation can help you https://material.io/components/pickers/#desktop-pickers

**Comment by allan-chen** [comment]
Hi Kemal,

The link above has the design specification for pickers. However, the picker component is not yet available in MDC Web.  #55 and #54  tracks feature requests for those components.
