### ISSUE TITLE
[top-app-bar] 

### ISSUE THREAD

**Issue by zposten** [material-components/material-components-web#5353]
## Bug report

This is more of a question than a bug report.  I'm using the [`top-app-bar--adjust` classes](https://github.com/material-components/material-components-web/blob/a95be81dc7cefb3fd5e1c448e6207d82276a5261/packages/mdc-top-app-bar/mdc-top-app-bar.scss#L199) alongside the top-app-bar component.

These classes are currently:
  - mdc-top-app-bar--fixed-adjust
  - mdc-top-app-bar--dense-fixed-adjust
  - mdc-top-app-bar--short-fixed-adjust
  - mdc-top-app-bar--prominent-fixed-adjust
  - mdc-top-app-bar--dense-prominent-fixed-adjust

Notice that each of these has the word "fixed" in them.  My question is in short, why?  

This adjustment is required whether the app bar stays fixed to the top of the page, or if it scrolls away as the user scrolls down (the "non-fixed" behavior that happens when a `MDCTopAppBarFoundation` "standard" foundation is used), correct?  When the user is at the top of the page (e.g. when the page loads) and the standard app bar has not yet scrolled away, the content still needs to be pushed below the app bar.

So given that the adjustment is required for both standard and fixed app bars, isn't it confusing to have "fixed" in each of the names?

The names could be, for example:
  - mdc-top-app-bar--standard-adjust
  - mdc-top-app-bar--dense-adjust
  - mdc-top-app-bar--short-adjust
  - mdc-top-app-bar--prominent-adjust
  - mdc-top-app-bar--dense-prominent-adjust

Thank you for your time, I apologize if I'm missing something here.

**Comment by allan-chen** [comment]
Hi Zach,

Good question - this naming convention may have been an artifact of the class initially being used for the fixed variant, but also later re-used for the non-fixed variant. We'll consider the impact of making those renaming changes in terms of backwards compatibility. Thanks for reaching out!
