### ISSUE TITLE
[MDCChips] Sass Error: File to import not found or unreadable: @material/rtl/mixins

### ISSUE THREAD

**Issue by damian-mariachi-team** [material-components/material-components-web#5362]
## Bug report

When compiling Sass styles, I get the following error message:
```
Error: File to import not found or unreadable: @material/rtl/mixins.        
on line 32 of node_modules/@material/chips/_mixins.scss
```

### Possible solution

Add dependency from **@material/rtl** in package.json

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0
| Browser          | Chrome
| Operating System | Windows 10

**Comment by allan-chen** [comment]
Thanks for bringing this up! This should be resolved now.

**Comment by damian-mariachi-team** [comment]
Thanks Allan, perfect...
