### ISSUE TITLE
Opening a menu

### ISSUE THREAD

**Issue by dleangen** [material-components/material-components-web#5372]
Hello,

I cannot determine from the docs how to set up a menu in a static website context.

For instance, how do I listen for a button click event and then trigger the menu open?

Thank you.

**Comment by allan-chen** [comment]
Hi David,

Please see the example on codepen [here](https://codepen.io/abhiomkar/pen/gQYNKL) - hope this helps!

**Comment by dleangen** [comment]
Yes, thank you! The menu opens, but for some reason it does not get anchored on the button (or any other element I have tried to anchor it to, for some reason). Using exactly the same code, but in the context of my static page.

Stepping through the code when the event is triggered, all I can tell is that for some reason the anchor becomes the top-level element, so the menu always opens at the top of the page.

**Comment by allan-chen** [comment]
Hey David,

To help us track down what's going on in your specific context, would it be possible for you to provide a codepen for your specific use case? If it helps, you can fork the pen above to start with. And just in case, please make sure you're using v4.0.0 of MDC. Thanks!

**Comment by dleangen** [comment]
Ah, never mind.

In creating the CodePen, I finally noticed that there was more than one element being selected by the query selector I used to determined the element used as the method parameter. I had not noticed that before.

Just a thought, but would it be possible to include a setAnchorElement method that takes a query selector filter as a parameter instead of an element? That way, if more than one element is selected, a warning could be logged. This could potentially help to avoid the kind of stupidity that I just achieved. It could even potentially be worthwhile replacing:

```
    MDCMenu.prototype.setAnchorElement = function (element) {
        this.menuSurface_.anchorElement = element;
    };
```

with something like this (totally unverified code, but hopefully you get the idea):

```
    MDCMenu.prototype.setAnchorElement = function (filter) {
        const element = document.querySelector(filter);
        // If more than one element is found:
        //     - select some reasonable default element, and
        //     - log a warning
        this.menuSurface_.anchorElement = element;
    };
```

Just a thought.

**Comment by allan-chen** [comment]
Hey David,

Glad you found the bug, and thanks for the suggestion! The crux of the issue here seems to be type safety, and a quick and easy to improve that may be to use typescript - ensuring that nothing but an `Element` can be passed into the method, as in [here](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/component.ts#L196). 

Closing the issue for now, but let me know if anything else comes up!
