### ISSUE TITLE
[MDCSlider] Discrete Slider schows value "-0" by default

### ISSUE THREAD

**Issue by damian-mariachi-team** [material-components/material-components-web#5379]
## Bug report
Discrete Slider schows value "-0" by default. Must only "0"

### Steps to reproduce
1. Go to 'https://material-components.github.io/material-components-web-catalog/#/component/slider'
2. Click on 'Discrete Slider'
3. Drag slider to the left to zero
4. Then pull just a little to the right
4. See error: value "-0"

### Actual behavior
value "-0"

### Expected behavior
value only "0"

### Screenshots
[Slider bug](http://dmitry-bret.de/screenshots/bug-slider.jpg "Slider bug")

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0
| Browser          | Chrome
| Operating System | Windows 10

**Comment by BhavyaSingh2611** [comment]
this bug can be reproduced on codepen

https://codepen.io/BhavyaSingh2003/pen/zXbzvv

**Comment by abhiomkar** [comment]
There is an open PR that might fix this issue #5379
