### ISSUE TITLE
Cant load material io resources CDN! 

### ISSUE THREAD

**Issue by solomonbelda** [material-components/material-components-web#5385]
<img width="941" alt="Screen Shot 2019-12-24 at 12 09 27 PM" src="https://user-images.githubusercontent.com/31472599/71393175-4d059880-2646-11ea-97a9-e0059136a099.png">

**Comment by solomonbelda** [comment]
My website depends on it. All pages with js crashes.

**Comment by BhavyaSingh2611** [comment]
Hi @solomonbelda try using these links

https://unpkg.com/material-components-web@4.0.0/dist/material-components-web.min.js
https://unpkg.com/material-components-web@4.0.0/dist/material-components-web.min.css

and tell if it helps!!

**Comment by BhavyaSingh2611** [comment]
or try these as the console shows error 429 too many requests 

https://cdn.jsdelivr.net/npm/material-components-web@4.0.0/dist/material-components-web.min.js
https://cdn.jsdelivr.net/npm/material-components-web@4.0.0/dist/material-components-web.min.css

and tell if it helps

**Comment by MartinKolarik** [comment]
This was an unpkg outage, the jsDelivr links work fine.

**Comment by abhiomkar** [comment]
HTTP 429 seems like unpkg outage. unpkg.com urls seems to be working now.
