### ISSUE TITLE
Placeholder text not animating

### ISSUE THREAD

**Issue by jaimeamedina** [material-components/material-components-web#5419]
Not able to really implement mdc-text-field component. The placeholder text does not animate upward as per demo.

https://stackblitz.com/edit/angular-uicufl

**Comment by asyncLiz** [comment]
You need to attach the MDC component to the element to get the JavaScript interactivity working.

```ts
import { Component, AfterViewInit, ElementRef } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent implements AfterViewInit {
  name = 'Angular';

  constructor(private elementRef: ElementRef) {}

  ngAfterViewInit() {
    (window as any).mdc.textField.MDCTextField.attachTo(
      this.elementRef.nativeElement.querySelector('.mdc-text-field')
    );
  }
}
```

Have you tried using [Angular Material](https://material.angular.io/)? MDC is the baseline implementation for the web, but they offer ready-to-go Angular components that implement Material Design.

They are also [updating to use MDC](https://github.com/angular/components/projects/25#card-22597886) to be consistently spec compliant.

**Comment by asyncLiz** [comment]
@jaimeamedina let me know if you have any other questions!

**Comment by jaimeamedina** [comment]
Liz,
My apologies for not getting back sooner, and thank you for your responses.
It took a bit, but I think I've finally got the 'material landscape' sorted
out; my consternation notwithstanding :).

Per your suggestion, I've got angular material working, with a couple of
mdc components thrown in the mix.

Thanks again!
