### ISSUE TITLE
Snackbar.show when already shown

### ISSUE THREAD

**Issue by neclepsio** [material-components/material-components-web#542]
In my opinion, an option should be added to the data passed to `show` to alter the behavior when the snackbar is already shown.

Instead of adding the message to the queue, it should be immediately shown on the current snackbar and the timeout should be reset.

This could be useful, for example, to use a snackbar to show the current level of zoom.

**Comment by traviskaufman** [comment]
We could definitely see a use case for this, and it's way better than just stackig up queued up snackbars. However, we'll have to get in touch with design as to whether or not text in the snackbar can be changed or should be automatically reset.

**Comment by Garbee** [comment]
Changing the text seems incorrect. If you only change the text then people may not notice that it is updated and things have changed. One of the important reasons for the animation in-and-out is for a clear indicator that the information is changed and should get some attention. This behavior is in fact specifically defined in the spec.

> When a second snackbar is triggered while the first is displayed, the first should start the contraction motion downwards before the second one animates upwards.

**Comment by neclepsio** [comment]
In my opinion, it's not always true. For my use case, showing the exact zoom level, if the user is interested in a particular value, his eye will be kept on the snackbar. If he's not interested, it's not useful to try and get more attention than the inital: "hey, you can read the exact value here".

**Comment by Garbee** [comment]
I don't see zoom level as a good use of the Snackbar. In that case you want a dedicated area that you can dynamically update as-needed and then show/hide as-needed. That isn't a direct use-case of a Snackbar as their contents aren't meant to be modified once shown. They are concrete transient information providers, not malleable transient ones.

**Comment by traviskaufman** [comment]
Hey @neclepsio ,

we spoke with our design team and they pretty much echoed what @Garbee had mentioned. The animations in and out exist by design to make sure that the user pays attention to what's being displayed within the snackbar.

To that end, you may want to consider a different UX for your zoom level, for example, put the current level inline next to the control that allows you to zoom in and out. Thanks!
