### ISSUE TITLE
[MDCSelect] Add hidden input element to support HTML forms

### ISSUE THREAD

**Issue by bonniezhou** [material-components/material-components-web#5428]
Since MDC Select does not use a `<select>` element, add a hidden `<input>` element to capture the value in HTML forms.

Note that it had previously been added in #3986 but seems like got overlooked in a refactor.

Related issues: #5230 and #5295.

**Comment by hebbet** [comment]
Any news on that?

**Comment by Splaktar** [comment]
> Any news on that?

Only that a related change happened in https://github.com/material-components/material-components-web/pull/5811, but it doesn't fully address this issue.

**Comment by allan-chen** [comment]
Hi! This is in progress now. Apologies for the wait.

**Comment by im-n1** [comment]
@allan-chen great work! We are all waiting for this more than upcoming Christmas :)
