### ISSUE TITLE
[MDC Tab-Bar] in package.json is @material/tab-indicator dependency missing

### ISSUE THREAD

**Issue by damian-mariachi-team** [material-components/material-components-web#5441]
### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0
| Browser          | Chrome
| Operating System | Windows 10

### Possible solution
**package.json now:**
```
"dependencies": {
    "@material/animation": "^4.0.0",
    "@material/base": "^4.0.0",
    "@material/density": "^4.0.0",
    "@material/elevation": "^4.0.0",
    "@material/feature-targeting": "^4.0.0",
    "@material/tab": "^4.0.0",
    "@material/tab-scroller": "^4.0.0",
    "tslib": "^1.9.3"
  },
```
**package.json solution:**
```
"dependencies": {
    "@material/animation": "^4.0.0",
    "@material/base": "^4.0.0",
    "@material/density": "^4.0.0",
    "@material/elevation": "^4.0.0",
    "@material/feature-targeting": "^4.0.0",
    "@material/tab": "^4.0.0",
    "@material/tab-indicator" : "^4.0.0",
    "@material/tab-scroller": "^4.0.0",
    "tslib": "^1.9.3"
  }, 
```

**Comment by asyncLiz** [comment]
While it does not _technically_ depend on `@material/tab-indicator`, I agree that it should be part of its dependencies. A tab indicator cannot be used on its own and a tab-bar _should not_ be used without an indicator.

Would you be willing to open a PR for this?

**Comment by damian-mariachi-team** [comment]
Hi asyncLiz. 

What is PR and how can i it open?

**Comment by asyncLiz** [comment]
It is a Pull Request, a way for you to contribute code changes to the repository. You can [fork this repo](https://help.github.com/en/github/getting-started-with-github/fork-a-repo), make the changes, and then [open a PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) to submit them to us for review.

**Comment by damian-mariachi-team** [comment]
Thanks.
I have a Pull Request opened...

**Comment by allan-chen** [comment]
I notice that tab depends on tab-indicator. Does the transitive dependency not work here?

**Comment by asyncLiz** [comment]
Good find @allan-chen. I created a new directory and ran `npm install @material/tab-bar` and that tab-indicator is installed as well.

@damian-mariachi-team can you confirm?

**Comment by asyncLiz** [comment]
See https://github.com/material-components/material-components-web/issues/5441#issuecomment-574775382, tab-indicator is correctly installed since it's a dependency of `@material/tab`. Thanks for looking into it!
