### ISSUE TITLE
Floating label for drop-down selects?

### ISSUE THREAD

**Issue by mbirth** [material-components/material-components-web#547]
I couldn't find any information about this in the MD guidelines. For drop-down (i.e. single-line) selects, a floating label would be helpful in many cases like in the [MDL-EXT](http://leifoolsen.github.io/mdl-ext/demo/selectfield.html) version of this component.

This would provide a uniform look in-between text fields and also give a hint of what kind of value was asked for after a selection has been made. The [current version](https://material-components-web.appspot.com/select.html) doesn't show the label (first option) anywhere after a selection was made. So e.g. after selecting "Fruit", when glancing over the form again later (or the form loaded prefilled, e.g. when you want to change something later), you need to remember what was asked for in that select field or open the drop-down to look at the first item again.

**Comment by traviskaufman** [comment]
Hey @mbirth,

floating labels are only meant for text inputs, not dropdowns. Thus, we won't be implementing this behavior. Have you considered using a `<label>` element along with `mdc-select` in order to show what the select is asking for? That would be our advice on how to solve this pattern.

**Comment by mbirth** [comment]
This doesn't look anywhere near as nice as it does with a floating label. Could you probably add CSS classes to make a static "floating above" label, e.g. `mdc-select__label` and/or `mdc-select__label--float-above`?

**Comment by Garbee** [comment]
Not unless it is added to the Material Design specification by the spec team. The goal of Material Components for Web is to be a reference implementation of the design specification from that team.

It can be passed along to the team that some feel the design on form elements is inconsistent with each other and perhaps the team can try to help by making some consistent form view. However MCW shouldn't add in miscellaneous extra modifiers and views except in extreme cases. It is a reference implementation of a set specification, not a framework to do everything developers may wish.

**Comment by mbirth** [comment]
While not explicitly mentioned, the "floating-label above a drop-down selection" appears multiple times in your [Text fields components](https://material.io/guidelines/components/text-fields.html#text-fields-layout) guidelines.

![2017-04-24 18_31_39-text fields - components - material design guidelines](https://cloud.githubusercontent.com/assets/130302/25347791/51e08132-291c-11e7-8a0f-7b496ed731bc.png)

<img src="https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xORDV6SjN6WEhHUlU/single1.png" width="240"> <img src="https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B5ZSepuCX1xOLTFIRURTTl9mQWc/single2.png" width="240">

It also talks about nesting a drop-down inside a text field to get the matching design. Having a `<select>` with the floating (or static "float-above") label would accomplish that for the web.

**Comment by Garbee** [comment]
Yup, it sure does. It's very oddly worded though. Perhaps this should be pinged back to the team to clarify what exactly should be going on. The wording makes me feel the author of these spec pieces didn't quite understand nesting in the way the web works. It very well may not have been their original intent to describe it this way.

**Comment by djensen47** [comment]
@traviskaufman Given @mbirth's observation that this **_is_** part of the spec, why is it still closed? Or will this be addressed by #1097?
