### ISSUE TITLE
Temporary drawer overlay persists when drawer is swiped to close

### ISSUE THREAD

**Issue by prateekbh** [material-components/material-components-web#548]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

> 0.9.0 or 0.9.1 whatever demos are using

### What browser(s) is this bug affecting?

> Chrome 

### What OS are you using?

> Mac/Android

### What are the steps to reproduce the bug?

1.) On a phone, navigate to 
http://material-components-web.appspot.com/drawer/temporary-drawer.html#

2.) open the temporary drawer
3.) Now swipe this drawer to close.
4.) Look at the main screen looks like an overlay has remained on the entire document

### What is the expected behavior?

Overlay must be fully invisible

> Please describe what the component/code should be doing that it's not.

### What is the actual behavior?

Remaining overlay is having an alpha > 0

**Comment by BBosman** [comment]
We're seeing the same issue.

It appears it was introduced in commit 79a235269a8c15e145853d2a613624b2a6b5d5f6.

**Comment by traviskaufman** [comment]
I was able to reproduce this on my iPhone. Filing as a bug.
