### ISSUE TITLE
[DataTable] example code of DataTable

### ISSUE THREAD

**Issue by jony666666** [material-components/material-components-web#5483]
### Steps to reproduce
1. Go to '/material-components-web/packages/mdc-data-table/'
2. Click on 'README.md'
3. Scroll down to 'Variants:Data table with row selection'
4. See error at ` <svg class="mdc-checkbox__checkmark" viewbox="0 0 24 24">`

### Actual behavior
the `viewbox` attribute  dosen't work ,  the style of checkbox is broken .

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | -
| Browser          | Safari 13.04/FireFox 72.0.1
| Operating System | macOS 10.15.2

### Additional context

Webpack/SASS/Vue

### Possible solution
this svg attribute seems to be case-sensitive, i replaced viewbox with viewBox and solved it.

**Comment by asyncLiz** [comment]
Thanks for the issue! Looks like it also needs to be updated in the [component test](https://github.com/material-components/material-components-web/blob/master/packages/mdc-data-table/test/component.test.ts#L51).

Would you be willing to open a PR to fix it?

**Comment by asyncLiz** [comment]
Fixed in #5493
