### ISSUE TITLE
Deletable Chip

### ISSUE THREAD

**Issue by phidias51** [material-components/material-components-web#5520]
It would be useful if you could delete the chips as well. Other chip components had the ability to specify whether or not they were deletable. If they were, an X icon would appear at the end of the chip. The user could click on it and the chip would disappear.

**Comment by joyzhong** [comment]
We support removable input chips: https://github.com/material-components/material-components-web/tree/master/packages/mdc-chips#removing-chips-from-the-dom

Does that work for your use case?

**Comment by allan-chen** [comment]
Sounds like the removable chip might be appropriate here - feel free to reopen if any further issues arise!
