### ISSUE TITLE
[mdc-drawer] Drawer should not stop working just because transitions are disabled

### ISSUE THREAD

**Issue by austinw-fineart** [material-components/material-components-web#5569]
### Bug report
While this technically isn't a supported use case, the fact that a style change breaks the component's functionality should be cause for concern. When `transition: none` is applied to the drawer, the next time the drawer is opened/closed programmatically it will become stuck and refuse to close/open. This applies to any of the drawer variants.

### Steps to reproduce
1. Apply the style `transition: none` to the drawer element
2. Open/Close the drawer
3. Close/Open the drawer again

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |4.0.0
| Browser          |Chrome 80
| Operating System |Windows 10

**Comment by allan-chen** [comment]
Hey Austin,
Drawers rely on the transition-end event to trigger some internal state logic after drawer open/close. If your use case demands a hastier/complete absence of transitions, one possibility is to set the transition-duration to something like 0.0001s.
