### ISSUE TITLE
Wordpress theme

### ISSUE THREAD

**Issue by Touficbatache** [material-components/material-components-web#557]
Hi,
I would like to inform that the wordpress theme has been finished. @traviskaufman @yeelan0319

**Comment by traviskaufman** [comment]
Thanks!

**Comment by Touficbatache** [comment]
What should I do now?

**Comment by traviskaufman** [comment]
That question is kind of outside the scope of our GH issues 😄 This issue tracker is for reporting issues / questions with core MDC-Web code. Feel free to do whatever you'd like with your wordpress theme!

**Comment by Touficbatache** [comment]
Could you please go to Discord?

**Comment by Touficbatache** [comment]
Could you please reply on Discord? @traviskaufman You said that you'll try to put me "in touch with the design team for a review"
