### ISSUE TITLE
[MDCSelect] Setting value causes change event to be fired twice

### ISSUE THREAD

**Issue by Malloreon** [material-components/material-components-web#5570]
## Bug report
Setting the selected option of an MDCSelect element by setting the value causes the change event to be fired twice.

### Steps to reproduce
1. Initialize an MDCSelect element
2. Listen to the MDCSelect:change event
3. Set the MDCSelect value through Javascript

### Actual behavior
The change event is fired twice.

### Expected behavior
The change event should only be fired once.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | Latest
| Browser          | Chrome
| Operating System | Windows 10

### Additional context
I've created a JSFiddle showing the issue here:
https://jsfiddle.net/1q09hsc2/7/

**Comment by allan-chen** [comment]
Hi - Thanks for reaching out. I was able to reproduce this on the given fiddle. It seems like in the foundation code, `handleChange()` is called both in `setSelectedIndex()` and `setValue()`, which calls `setSelectedIndex()`

**Comment by brycekirk** [comment]
This still appears to be an issue in the 5.1.0 release

**Comment by allan-chen** [comment]
Looks like this missed the [5.1.0 release](https://github.com/material-components/material-components-web/releases/tag/v5.1.0) by a day - should be out next release

**Comment by lafonju** [comment]
@allan-chen Do you know when the next version will be available via NPM to take advantage of the correction ?
Thanks you
