### ISSUE TITLE
[MDCSelect] Disabled items can still be selected

### ISSUE THREAD

**Issue by Malloreon** [material-components/material-components-web#5571]
## Bug report
Items with the 'mdc-list-item--disabled' class can still be selected.

### Steps to reproduce
1. Create a MDCSelect element with at least one of the options having the class 'mdc-list-item--disabled'
2. Click on the MDCSelect to open the list of options
3. Click on the option that you have disabled
4. Disabled option becomes selected

### Actual behavior
There is no highlight when mousing over the disabled option, but clicking on it still causes it to be selected.

### Expected behavior
Disabled options should not be able to be selected.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | Latest
| Browser          | Chrome
| Operating System | Windows 10

### Additional context
I've created an example fiddle that demonstrates the issue here:
https://jsfiddle.net/1q09hsc2/10/
(Try clicking on the 'Disabled Option' option)

**Comment by allan-chen** [comment]
Hello again,
This seems reproducible - thanks for the bug report!
