### ISSUE TITLE
Create a path towards the standardization of our READMEs

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#558]
MDC-Web has grown very quickly and organically, and to that end, so have our READMEs. Many of them are created by copy-pasting info around from other READMEs, but also contain duplicated information (e.g. how to include the JS / CSS for a component), are extremely dense (e.g. the MDC-Ripple README), and lack consistency and/or cohesion.

I'd like us to look into standardizing all of our component READMEs such that they:

- Surface the most relevant information directly up front
- Provide a consistent experience regardless of which components we're looking at
- Can be templatized such that READMEs for new components can be spun up quickly
- Retain authenticity such that our READMEs don't become "generated API docs" for our components, but rather a nice welcome mat for new developers to walk on.
- Do not contain `TODO`s, `_TK_`s, or superfluous `**NOTE:**` blockquotes

Some things we can look into here include:

- A current survey of what works and does not work about our READMEs
- A way to take any common information - such as including dependencies in code - and "refactor" it out into shared documentation that we can link to from our component READMEs
- A process to ensure that our contributors can author READMEs with confidence knowing that they can follow along with our convention.
- A way to somehow include links to demos and/or screenshots to go along with the example DOM shown in the REAMDE
- "Documentation tests" to ensure that our READMEs are consistently up-to-date

This issue can serve as a discussion as well as a story for researching the best way to do this.

**Comment by Teoxoy** [comment]
You guys could use [Verb](https://github.com/verbose/verb), I find it alot easier than writing READMEs by hand.

**Comment by kfranqueiro** [comment]
This has been accomplished via https://github.com/material-components/material-components-web/blob/master/docs/code/readme_template.md and https://github.com/material-components/material-components-web/blob/master/docs/code/readme_standards.md. See also #2476.
