### ISSUE TITLE
[Layout Grid] Include an ability for mdc-layout-grid to look at the container width instead of the window width to determine if breakpoint needs to be changed

### ISSUE THREAD

**Issue by peterlitvak** [material-components/material-components-web#5581]
I've noticed that `mdc-layout-grid` looks at the window width when determines which breakpoint to use.
It means that if a component with `mdc-layout-grid` is part of some other container the breakpoint is not switched until the width of the browser window (more precisely the viewport) crosses the breakpoint width boundary. This leads to the `mdc-layout-grid` not changing layout even though the container width that it is enclosed in is less than a breakpoint target width.
This demonstrates what I mean.
```
<table>
        <tr>
          <td style="min-width: 220px;">left</td>
          <td>
            <div class="mdc-layout-grid">
              <div class="mdc-layout-grid__inner">
                <div
                  class="mdc-layout-grid__cell--span-2-desktop mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone"
                  style="height: 150px; background-color: red;"
                ></div>
                <div
                  class="mdc-layout-grid__cell--span-2-desktop mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone"
                  style="height: 150px; background-color: red;"
                ></div>
                <div
                  class="mdc-layout-grid__cell--span-2-desktop mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone"
                  style="height: 150px; background-color: red;"
                ></div>
                <div
                  class="mdc-layout-grid__cell--span-2-desktop mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone"
                  style="height: 150px; background-color: red;"
                ></div>
                <div
                  class="mdc-layout-grid__cell--span-2-desktop mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone"
                  style="height: 150px; background-color: red;"
                ></div>
                <div
                  class="mdc-layout-grid__cell--span-2-desktop mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone"
                  style="height: 150px; background-color: red;"
                ></div>
              </div>
            </div>
          </td>
          <td style="min-width: 220px;">
            right
          </td>
        </tr>
      </table>
```

**Comment by CyborgSemon** [comment]
Im unsure why this feature would be needed? What should your example be doing that its currently not doing?

**Comment by peterlitvak** [comment]
Sorry, my description was probably a bit cryptic.
Basically in the layout that I have I'd like breakpoint to happen when container element for `mdc-layout-grid` (not the viewport) reaches the certain width. Maybe it is already possible but I didn't find a way to do this.
I'd imagine having something like `mdc-layout-grid__cell--span-{number of columns}-{container-width}`
Then for the example above I would be able to define a layout where breakpoints would happen when the width of the `<td>` containing the `mdc-layout-grid` div riches certain width(s).
Hopefully this makes things a bit more clear.

**Comment by CyborgSemon** [comment]
Ahh I see. I don't think this is possible in CSS though (see https://stackoverflow.com/questions/12251750/can-media-queries-resize-based-on-a-div-element-instead-of-the-screen) Layout grid is one of the components that doesn't have any JS built into it. So if you were to want this functionality, you would probably need to make your own custom css and javascript to do this.

Check out this for an example: https://codepen.io/MrSimmons/pen/OJVPWjN

**Comment by allan-chen** [comment]
Hi,
This component was implemented according to [Material Design guidelines](https://material.io/design/layout/responsive-layout-grid.html#) to account for viewport widths only. For your use case, it might be best to use a solution that polyfills element queries.

**Comment by peterlitvak** [comment]
Thank you!
