### ISSUE TITLE
[MDCMenu] race condition with quick mode: firing close event indefinitely

### ISSUE THREAD

**Issue by 200Puls** [material-components/material-components-web#5583]
## Bug report
I did file this bug report originally for the WebComponent in https://github.com/material-components/material-components-web-components/issues/839 and was told to file it here as it is an upstream issue. So my example uses the webcomponents menu. Original description:

I am trying to create a unit test with the menu. As soon as I enable the quick mode the element does not stop producing 'closed' events.

I'm using the open-wc setup with karma and mocha. This happens in regular chrome in debug mode and in chrome headless.

### Steps to reproduce
1. Go to https://stackblitz.com/edit/mwc-example-839-bq8p5m?file=index.html
2. Open developer tools and see "closed event" log message in console. This is printed each time the close event is fired

### Actual behavior
close events are fired indefinitely

### Expected behavior
A close event should only be fired once when the menu is closed.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |
| Browser          |  Chrome 80
| Operating System | Ubuntu

### Additional context
Info from @e111077:
It seems as if the open and close function runs in an animation frame regardless of quick open or not:

https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu-surface/foundation.ts#L171

For a workaround for mwc, I suggest awaiting @open or waiting for a RAF.

**Comment by allan-chen** [comment]
Hi, thanks for reaching out.
I can't reproduce the issue at the MDC level here https://codepen.io/allanchenmdc/pen/dyoPNXr - can you verify if the JS logic there replicates the stackblitz demo?

**Comment by asyncLiz** [comment]
I was able to reproduce the issue here: https://jsbin.com/geyepowuku/edit?html,output

The problem comes from trying to sync to the open state of the menu.

**Comment by e111077** [comment]
quick should now be synchronous

**Comment by e111077** [comment]
confirmed fix with #5838
