### ISSUE TITLE
Add number icons, too. I'm using Material icons.

### ISSUE THREAD

**Issue by N1Mirzo** [material-components/material-components-web#5589]
### Feature Request
Hi, I am in trouble I believed that material icons have numbers. And I wanted to use them in my stepped form component. But I couldn't find them by searching or writing like "one, number_one, first" or others and I looked for the documentation and icons list. Finally, I couldn't found them.
You may say just use real letters. No, this stepped slider component only gets icons. I didn't made it. And even the component owner is not responding to me. I think the owner entered internet one or two years ago. So help me please. I'm using Vue-Stepper component.

### Proposed solution
If you add number icons to the icons list it will be great. Just I want the 1 to 10 only.
But what about the others. Other people may ask for other numbers, too. Whatever adding numbers to the icons list is so hard. Because people may ask 1299666 like numbers. And creating numbers like this may take time. But should be an easy way to do so whatever. And for the beginning add from 1 to 10. Then 10 to 100. And you may even finish there if you want. 
We may use numbers like this. icon="one four two six nine" and it may show us "14269". For example you only make 0 to 9 numbers and we may have an opportunity to use numbers like above.

### And others
And if you make the numbers without circle, square or without any borders it will be great.

### Specially thanks
Thanks for everyone who read this. And specially thanks for the owners and creators of material components.

**Comment by asyncLiz** [comment]
Thanks for the issue! Unfortunately this project isn't related to the team that creates icons. My recommendation would be to download the SVGs for the [filter icons](https://material.io/resources/icons/?search=filter&style=baseline) and extract the numerical part of the icon. You can then create and use your own icon font with Material-inspired numbers.

**Comment by CyborgSemon** [comment]
@N1Mirzo The other option would be to use the open source material icon library. Ive been using this library for a few of my projects along side MDC and it works quite well.
https://materialdesignicons.com/

NOTE: This isn't the supported material icons list by Google, but it includes all of Googles ones + a huge amount of community suggested and made ones as well.

This is the CDN if you are interested, though it is very large. I recommend downloading each icon you need individually using NPM or just by downloading the SVG directly.
https://cdn.materialdesignicons.com/4.7.95/css/materialdesignicons.min.css
