### ISSUE TITLE
Replace stylelint `order/declaration-block-properties-order` rule with `order/properties-order`

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#559]
<img width="1005" alt="screen shot 2017-04-25 at 16 38 20" src="https://cloud.githubusercontent.com/assets/1185269/25406739/c45d3fb6-29d5-11e7-88a6-1305bf8009de.png">

https://github.com/hudochenkov/stylelint-order

- [ ] Replace the rule with the above plugin, using the `properties-order` array to preserve the order of our current properties.
- [ ] Fix any files which cause the new lint rule to fail

**Comment by trimox** [comment]
Got it.

**Comment by trimox** [comment]
@traviskaufman, all set. 
Merged on the 26th.

**Comment by traviskaufman** [comment]
Thank you @trimox!
