### ISSUE TITLE
[MDCSelect] overflow inside of dialog

### ISSUE THREAD

**Issue by dy** [material-components/material-components-web#5590]
## Bug report

Select within dialog creates overflow for dropdown menu
![image](https://user-images.githubusercontent.com/300067/74149572-107e0400-4bd6-11ea-9ff0-6bbbfbfd525d.png)

That was one of the reasons we used `mdc-select__native-control`, besides [#5428](https://github.com/material-components/material-components-web/issues/5428) (we can't simply send form data as `fetch(url, new FormData(formElement))` now).
Also mobiles handle native select dropdowns better.

### Steps to reproduce

1. Create dialog with MDCSelect inside

### Actual behavior

↑

### Expected behavior

Not to have overlay. 
### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0 |
| Browser          | Brave / Chrome |
| Operating System | Win10 |

### Possible solution

Hoist menu to body in some way?

**Comment by SamProf** [comment]
Same issue

**Comment by asyncLiz** [comment]
Thanks for the issue! Definitely is a problem 😔

**Comment by Pupix** [comment]
I fixed it by using `mdcSelect.setFixedPosition(true)` after instantiation.

**Comment by DimaChaichan** [comment]
> I fixed it by using `mdcSelect.setFixedPosition(true)` after instantiation.

Don't works for me. 
A Fixed Postion make problems. If you scale the window for example the Selection postion are not updated.

**Comment by arnaudbuy** [comment]
Using `mdc-menu-surface--fixed` can help

**Comment by ftaiolivista** [comment]
> Using `mdc-menu-surface--fixed` can help

@arnaudbuy  Fixed prevent the cutoff but with it the dropdown start from the center of the select field
![Screenshot_20200504_152944](https://user-images.githubusercontent.com/150721/80970991-613f7a80-8e1c-11ea-9c08-b608493a63b2.jpg)

**Comment by abhiomkar** [comment]
Setting menu to fixed position will work with a workaround. Any ancestors of menu  should not contain `transform` property other than `none`.

Workaround for incorrect menu positioning when it is fixed: Set dialog's root elements `transform` property to `none`.

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position):

> Position `fixed`
> The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to the initial containing block established by the viewport, except when one of its ancestors has a transform, perspective, or filter property set to something other than none (see the CSS Transforms Spec), in which case that ancestor behaves as the containing block. (Note that there are browser inconsistencies with perspective and filter contributing to containing block formation.) Its final position is determined by the values of top, right, bottom, and left.

**Comment by arnaudbuy** [comment]
@ftaiolivista 

[From the documentation](https://material.io/develop/web/components/input-controls/select-menus/)

> The select requires that you set the width of the mdc-select__anchor element as well as setting the width of the mdc-select__menu element to match.

**Comment by ftaiolivista** [comment]
> Set dialog's root elements `transform` property to `none`.

@abhiomkar thats works.

**Comment by simonziegler** [comment]
I have this too, but am still using MT 6.0.0. Has this been worked on for 7.0.0 please?

**Comment by allan-chen** [comment]
#6012 should have removed the transform property from dialog. Setting menu to position fixed and defining a custom width for the anchor + menu should resolve this.

**Comment by simonziegler** [comment]
Thanks!

**Comment by simonziegler** [comment]
This problem has now been fixed the the Material Theme team. As a note for anybody wondering how to apply this to their own projects, do the following:

- Use Material Theme 7.0.0
- Add the `mdc-menu-surface--fixed` class to the div that already has the `mdc-select__menu` class
- Add a new class, eg `my-width-class` to the two div with classes `mdc-select__anchor` and `mdc-select__menu`
- Set an explicit width in `my-width-class`, e.g. 200px

**Comment by data-handler** [comment]
Has anyone tried this fix inside an MDCDataTable? Although the menu displays correctly, clicking on an option does not update the selected item.
