### ISSUE TITLE
Implement Chips Component 

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#56]
Spec reference: https://www.google.com/design/spec/components/chips.html

> Copied from https://github.com/google/material-design-lite/issues/4505

**Comment by Wonay** [comment]
is it still planed ? I need it :(

**Comment by juliancoleman** [comment]
peeping for later. Any progress on this one? Would be a great little feature to have :100:

**Comment by lynnjepsen** [comment]
See #2003 and other "chip" issues for the implementation of chips
