### ISSUE TITLE
[MDCSelect]  Can select disabled item wrong doc

### ISSUE THREAD

**Issue by DimaChaichan** [material-components/material-components-web#5601]
## Bug report

If you create a MDC Select from documentation: 
https://github.com/material-components/material-components-web/tree/master/packages/mdc-select
and disable a Item. This Item looks normal. 

```
<li class="mdc-list-item mdc-list-item--disabled" data-value="vegetables" aria-disabled="true" disabled role="option">Is disabled 1</li>
```
The Text must inside a Span with the class:mdc-list-item__text
```
      <li class="mdc-list-item mdc-list-item--disabled" data-value="vegetables" aria-disabled="true" disabled role="option"><span class="mdc-list-item__text">
        Is disabled 2</span>
      </li>
```
But this is not descriptived in the Documentation.
You can also select a disabled Item:

### Actual behavior

Disabled Item can selected.

### Expected behavior

Don't select a disabled Item.

### Example

 https://codepen.io/dimachaichan/pen/LYVGVoL

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0
| Browser          | Chrome
| Operating System | Debian 10

**Comment by asyncLiz** [comment]
Looks like this is just a docs issue. We need to update the MDCList structure inside of MDCSelect.

**Comment by asyncLiz** [comment]
#5571 is tracking the issue around being able to select disabled items. We'll keep this one open as the doc update issue.
