### ISSUE TITLE
Mdc-layout-grid shorthand classes

### ISSUE THREAD

**Issue by alex321** [material-components/material-components-web#562]
Feature Requests:

Would it be possible to introduce shorthands for the mdc-layout-grid component?

Among the examples you can see this:
`<div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6 mdc-layout-grid__cell--span-8-tablet"></div>` 
which I don't think is very readable. I know we want to avoid clashes but "mdc-cell, mdc-cell-span" or even "mdc-span" might be quite nice. 

Thanks for the great work though!

**Comment by Garbee** [comment]
A shorthand naming convention wouldn't follow [BEM ](http://getbem.com/) guidelines for naming. The provided classes can become overly-verbose however it helps a great deal making a maintainable package to provide to others.

I'd recommend using Sass using the `@extend` function or any other applicable things, to make your own shorthand for your applications. That way you can keep your writing as concise as you wish while the library only needs to worry about adhering to BEM as best it can all around.

**Comment by traviskaufman** [comment]
@Garbee is correct; these classes exist to follow BEM and for maximum flexibility.
