### ISSUE TITLE
[MDCTextField] Error state disappears after focus out

### ISSUE THREAD

**Issue by JsonGuy** [material-components/material-components-web#5620]
## Bug report
If input has error state active, after input focus out the error state seems to disappear.

### Steps to reproduce
Go to: https://codepen.io/karli_ots/pen/OJVXPWK

### Actual behavior
Error state disappears

### Expected behavior
Error state should stay

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0
| Browser          |  Chrome Version 80.0.3987.106 (Official Build) (64-bit)
| Operating System | Windows 10

**Comment by asyncLiz** [comment]
Your textarea does not have any validation associated with it, either declarative (e.g. the `required` attribute) or programmatic (e.g. using `setUseNativeValidation(false)` and `setValid(false)`).

When you blur, it will see that the textarea is valid and remove invalid styles.

See https://codepen.io/asyncliz/pen/gOpMvLr for an example of it working with the `required` attribute.
