### ISSUE TITLE
[Snackbar] Investigate mobile breakpoint

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-components-web#5629]
See #4433. 

Snackbars should be 100% on mobile. The current [breakpoints for layout](https://material.io/design/layout/responsive-layout-grid.html#breakpoints) defines several breakpoint ranges for mobile. Currently we use 480px as the breakpoint. We should ask design whether or not this is acceptable, or if snackbars should be 100% width at a different breakpoint.

**Comment by angdesign** [comment]
It appears that the examples for snackbar beyond 480px do not have an 100% width, but allow for a fluid width depending on the contents within (see https://material.io/components/snackbars/#anatomy and scroll down to the wide layouts example.)

**Comment by angdesign** [comment]
Also https://material.io/components/snackbars/#placement shows alignment options for a snackbar in a wider layout. Recommendation would be to only apply the 100% at 480 and below.
