### ISSUE TITLE
README.md incorrectly documented how to import MDC in JavaScript

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#563]
All readme files are currently document import MDC in following way:

```
import {someComponent, someComponentFoundation} from 'mdc-some-component'
```

which instead should be 

```
import {someComponent, someComponentFoundation} from '@material/some-component'
```

Similar things to non-ES2015 module import.

**Comment by traviskaufman** [comment]
This is definitely an issue. Spoke with team and agreed to roll into #558, which we will prioritize for near-term sprints.
