### ISSUE TITLE
Investigate adding sourcemaps and removing Babel

### ISSUE THREAD

**Issue by cdock1029** [material-components/material-components-web#5638]
### Steps to reproduce
1. Use packages that depend on `@material/...` components
2. Build
3. Observe bundler not finding source files listed in source maps.

### Actual behavior
Parcel bundler showing many errors of `Could not load source file.... in source map..`
because only javascript files are uploaded to npm, but source map is looking for typescript files.

### Expected behavior
No error messages polluting the console. The source map is directed to the javascript files or the typescript files are uploaded to npm.

### Screenshots

![error message](https://doc-00-28-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/707c8r0uht05dv6igocvgdsefbrbbbte/1582235100000/09745027216445744095/*/1d3W9frBFrq5nBjTxVZxLeiYZ6pqb5Vnz)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |3.2.0
| Operating System |Pop!_OS 19.10

### Additional context

https://github.com/parcel-bundler/parcel/issues/2185

https://github.com/material-components/material-components-web/pull/4206

### Possible solution

Upload typescript files to npm.
OR, remove sourcemaps

**Comment by EstebanG23** [comment]
Thank you for reporting. Moving to backlog to add ts files.

**Comment by mattmspie** [comment]
I recently updated `react-scripts` in a React project that includes `@material/circular-progress`. I'm now seeing the following warnings during build, that look the same as this issue:

```
Failed to parse source map from '<path-sanitized>/node_modules/@material/base/component.ts' file : error : ENOENT: no such file or directory, open '<path-sanitized>/node_modules/@material/base/component.ts'

Failed to parse source map from '<path-sanitized>/node_modules/@material/base/foundation.ts' file : error : ENOENT: no such file or directory, open '<path-sanitized>/node_modules/@material/base/foundation.ts'

Failed to parse source map from '<path-sanitized>/node_modules/@material/circular-progress/adapter.ts' file : error : ENOENT: no such file or directory, open '<path-sanitized>/node_modules/@material/circular-progress/adapter.ts'  

Failed to parse source map from '<path-sanitized>/node_modules/@material/circular-progress/component.ts' file : error : ENOENT: no such file or directory, open '<path-sanitized>/node_modules/@material/circular-progress/component.ts'

Failed to parse source map from '<path-sanitized>/node_modules/@material/circular-progress/constants.ts' file : error : ENOENT: no such file or directory, open '<path-sanitized>/node_modules/@material/circular-progress/constants.ts'

Failed to parse source map from '<path-sanitized>/node_modules/@material/circular-progress/foundation.ts' file : error : ENOENT: no such file or directory, open '<path-sanitized>/node_modules/@material/circular-progress/foundation.ts'

Failed to parse source map from '<path-sanitized>/node_modules/@material/circular-progress/index.ts' file : error : ENOENT: no such file or directory, open '<path-sanitized>/node_modules/@material/circular-progress/index.ts'
```

As a quick test, I updated the `.map` files corresponding to the warnings above to change `"sources":["filename.ts"]` to `"sources":["filename.js"]` and the warnings went away.

**Comment by mattmspie** [comment]
@allan-chen Is there a chance this issue and #5904 could be separated and the title restored to "Source maps refer to non-existent source files (.ts)" (i.e. undo your May 12, 2020 edits)? This issue is a bug report whereas investigating a move away from Babel is a more invasive chore. For example, if this issue is restored to focus just on the broken sitemaps, then PR #7506 could actually be sufficient to close this issue.

**Comment by mattmspie** [comment]
I didn't heard back from @allan-chen on my last comment. Any chance @acdvorak might be able to weigh-in on my request? I see you have done some maintenance of the webpack and typescript configs.

**Comment by asyncLiz** [comment]
Hi @mattmspie! I believe this issue is obsolete now that we're focusing on [Material You](https://github.com/material-components/material-web/tree/master/components). MDC will soon enter maintenance-only mode.

We'll keep this in mind for the Material You components and packaging! We definitely want sourcemaps for them :)
