### ISSUE TITLE
Action label misaligned in RTL Snackbar

### ISSUE THREAD

**Issue by omerziv** [material-components/material-components-web#564]
### What MDC-Web Version are you using?

Latest (Found this in the demos)

### What browser(s) is this bug affecting?

Chrome 57.0.2987.133 (64-bit)

### What OS are you using?

OS X 10.12.4 (16E195)

### What are the steps to reproduce the bug?

1. Open Demos, Select Snackbar
2. Click "Show RTL"
4. Click "Show RTL" again

### What is the expected behavior?

"Undo" label on button is always aligned :)

### What is the actual behavior?

The first time that the snackbar shows up, everything is fine. The second time the snackbar shows up, "Undo" is misaligned and partially hidden.

### Any other information you believe would be useful?

Nope.

**Comment by traviskaufman** [comment]
Thanks for reporting! Definitely a bug, rolled into #28
