### ISSUE TITLE
[linear-progress] indeterminate animation fails under high CPU load

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web#5649]
## Bug report

MDC linear-progress's indeterminate state's animation skips frames under large CPU loads.

### Steps to reproduce
1. Place an indeterminate linear-progress on the page
2. Run `while (true) {}` in the console

### Actual behavior

The animation pulsates

### Expected behavior

The indeterminate animation should be playing

### Screenshots

![linear-progress-indet-frames](https://user-images.githubusercontent.com/5981958/75268794-fa6f6680-57c5-11ea-8407-ef71a438973a.gif)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | Canary
| Browser          | Chrome 80
| Operating System | Mac OS 10.15.3

**Comment by allan-chen** [comment]
As discussed, this is due to usage of % in the keyframes. @e111077 is there a chrome bug filed for this?

**Comment by e111077** [comment]
This seems to be a relevant bug. Mind adding a comment explaining our use case?

https://bugs.chromium.org/p/chromium/issues/detail?id=990258&q=transform%20percent&can=2

**Comment by allan-chen** [comment]
+1'd the feature request at https://bugs.chromium.org/p/chromium/issues/detail?id=990258&q=transform%20percent&can=2

**Comment by adi518** [comment]
Any workarounds?

**Comment by e111077** [comment]
Hello I forgot to close this issue. We have implemented a workaround using resize observer in Chrome which now needs to be removed since Chrome has fixed the underlying issue in the browser. Unfortunately there are no other workarounds for other browsers.

Are you running into any of these issues?

**Comment by adi518** [comment]
I'm using [rmwc](https://github.com/jamesmfriedman/rmwc), which unfortunately still has this issue in its latest version.

**Comment by e111077** [comment]
Rmwc does not use mwc under the hood. It also uses an older version of the base mdc library which does not include this fix. I am unable to reproduce this issue in our mwc library, so it seems like your best route of action is to file a bug under the rmwc library to update their dependencies and implement the resize observer in the new linear progress adapter.

**Comment by adi518** [comment]
But if it still happens with their version of the linear progress, doesn't that mean Chrome still has a bug?

**Comment by e111077** [comment]
Correct, following the bug it looks like it was reverted from the stable track because it caused a regression. Here's the new bug to follow https://bugs.chromium.org/p/chromium/issues/detail?id=389359
