### ISSUE TITLE
[Textfield] Read-only fields are not supported

### ISSUE THREAD

**Issue by motss** [material-components/material-components-web#5675]
### Steps to reproduce
NA

### Actual behavior

`mwc-textfield` does not support `readOnly` property.

### Expected behavior

`mwc-textfield` supports `readOnly` property. When `readOnly` sets to true, it renders the textfield in read-only mode which is also part of the MD specs.

### Screenshots

<img width="1504" alt="Screen Shot 2020-03-02 at 10 35 44 AM" src="https://user-images.githubusercontent.com/10607759/75640930-99d2a480-5c71-11ea-951d-810a0769fbcd.png">

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | NA |
| Browser          | NA |
| Operating System | NA |

**Comment by asyncLiz** [comment]
Thanks for the issue! We'll check in with design on some styling guidance. The text says that read-only fields are styled the same, but it appears as though the value text is a lighter gray color.

If the spec screenshot is incorrect and the textfield should be styled the same, then there's nothing to do in MDC. User's can add the `readonly` attribute to the input.

If the spec screenshot _is_ correct and the wording misleading, then we'll need to add style changes.

**Comment by asyncLiz** [comment]
Confirmed with design that the screenshots are incorrect. There are no stylistic changes to the value text for read-only fields.

Closing this as there's nothing to do for MDC. I've created https://github.com/material-components/material-components-web-components/issues/942 for MWC to track the property that is needed there.
