### ISSUE TITLE
[shape] Shape should use --mdc-shape-* custom props

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web#5677]
## Feature Request

Shape library should not be using prop-value but instead prop. This is because shapes should be editable with CSS custom props. See our CDS demo where we applied a "bandaids.css" file to make material-theme-generator work. 

https://glitch.com/edit/#!/material-theme-generator?path=public/bandaids.css:93:9

### Proposed solution

Shape should use something like [mdc-theme-prop](https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_mixins.scss#L86) which will automatically add a css custom property if it is in the map in `_variables.scss`.

Here are the relevant spots [application](https://github.com/material-components/material-components-web/blob/master/packages/mdc-shape/_functions.scss#L112), [map](https://github.com/material-components/material-components-web/blob/master/packages/mdc-shape/_variables.scss#L29).

### Alternatives considered

Manually adding these in.

### Additional context

MWC internal buganizer

**Comment by abhiomkar** [comment]
Instead of creating util functions for every theme properties it would make sense to use postcss polyfill as described in internal bug. We might need to roll our own postcss build rule until we've an official Sass build rule.

**Comment by asyncLiz** [comment]
Added in https://github.com/material-components/material-components-web/pull/5985
