### ISSUE TITLE
[MenuSurface] menu open animation is delayed

### ISSUE THREAD

**Issue by the-ress** [material-components/material-components-web#5682]
## Bug report
There's 120ms (`TRANSITION_OPEN_DURATION`) delay before the menu open animation starts.

### Steps to reproduce
1. Go to https://material-components.github.io/material-components-web-catalog/#/component/menu
2. Click the "Open menu" button

### Actual behavior
There's 120ms delay before the open animation starts.

### Expected behavior
The open animation should start immediately after mouseup.

### Screenshots
![image](https://user-images.githubusercontent.com/1612377/75893457-1eb8ec00-5e33-11ea-8912-bf16bb2cfd3d.png)

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | the version currently at https://material-components.github.io/material-components-web-catalog/
| Browser          | Chrome 80
| Operating System | Windows 10 (1803)

### Additional context
@DRiFTy17 mentioned it in https://github.com/material-components/material-components-web/issues/4411#issuecomment-463788609 (in the last paragraph)

https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu-surface/foundation.ts#L189

**Comment by asyncLiz** [comment]
@abhiomkar can you confirm if this is intentional or not? We also have #4411 that mentions the open transition duration.
