### ISSUE TITLE
[IconButtons] Bugged ripple when scaling icon button

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#5691]
## Bug report
Ripple don't get resized when using the CSS `scale` rule
Demo: https://codepen.io/maicol07/pen/bGdYaQE

### Steps to reproduce
1. Create an icon button with ripple (so initialized) following docs
2. Set the `scale` rule to 0.x (x can be whatever, like 0.75)
3. See error

### Expected behavior
Ripple should resize like button

### Screenshots
![immagine](https://user-images.githubusercontent.com/9463142/76144658-fc1d1200-6082-11ea-921a-a935a1e2f924.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.0.0
| Browser          | Mozilla Firefox
| Operating System | Windows 10

**Comment by asyncLiz** [comment]
You should be using the [density](https://github.com/material-components/material-components-web/blob/master/packages/mdc-icon-button/_mixins.scss#L91) (recommended to be spec-compliant) or [size](https://github.com/material-components/material-components-web/blob/master/packages/mdc-icon-button/_mixins.scss#L107) mixins to change the scale of the icon button. Changing it via a CSS transform is not supported.

```scss
@use "@material/icon-button/mdc-icon-button";
@use "@material/icon-button";

.mdc-icon-button {
  @include icon-button.density(-3); /* 75% of normal size */
}
```

Let me know if you have any questions!

**Comment by maicol07** [comment]
> 
> 
> You should be using the [density](https://github.com/material-components/material-components-web/blob/master/packages/mdc-icon-button/_mixins.scss#L91) (recommended to be spec-compliant) or [size](https://github.com/material-components/material-components-web/blob/master/packages/mdc-icon-button/_mixins.scss#L107) mixins to change the scale of the icon button. Changing it via a CSS transform is not supported.
> 
> ```css-scss
> @use "@material/icon-button/mdc-icon-button";
> @use "@material/icon-button";
> 
> .mdc-icon-button {
>   @include icon-button.density(-3); /* 75% of normal size */
> }
> ```
> 
> Let me know if you have any questions!

Thank you, but I use plain CSS, how can I do this?
