### ISSUE TITLE
[theme] Cannot customize a theme using sass module `with` syntax

### ISSUE THREAD

**Issue by kimurakenshi** [material-components/material-components-web#5695]
## Bug report

I'm not able to customize the colors of the theme using `with` as suggested in the [official documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-theme#color-scheme) 

### Steps to reproduce

1. I have an `index.scss` file with:  

```css
@use "@material/theme" with (
  $primary: #fcb8ab,
  $secondary: #feeae6,
  $on-primary: #442b2d,
  $on-secondary: #442b2d,
);
```
> This is being imported before loading `@material/theme/mdc-theme` or `@material/theme`

 2. When i try to compile the scss i get this error:

```
 ERROR in ./site/core/styles/index.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--13-3!./site/core/styles/index.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: This module was already loaded, so it can't be configured using "with".
        ┌──> node_modules/@material/theme/_index.scss
    2   │   @forward "./variables";
        │   ^^^^^^^^^^^^^^^^^^^^^^ new load
        ╵
        ┌──> node_modules/@material/theme/_mixins.scss
    26  │   @use "./variables";
        │   ━━━━━━━━━━━━━━━━━━ original load
        ╵
        ┌──> src/core/_core.config.scss
    95  │ ┌ @use "@material/theme" with (
    96  │ │   $primary: #fcb8ab,
    97  │ │   $secondary: #feeae6,
    98  │ │   $on-primary: #442b2d,
    99  │ │   $on-secondary: #442b2d,
    100 │ │ );
        │ └─^ configuration
        ╵
      node_modules/@material/theme/_index.scss 2:1  @use
      src/core/_core.config.scss 95:1               @use
      src/core/dsm-core.scss 2:1                    @use
      /Users/giras009/Documents/projects/ds-material-ui/site/core/styles/index.scss 4:1                                     root stylesheet
```

### Additional context
This was not happening before when i was using custom properties to create my own theme but it seems the features provided  by custom properties are limited and and i cannot change the `on-surface` color unless i use the sass variables approach due to some logic like the following in the theme package:

```css
// _variables in mdc theme package
$surface: #fff !default;
$on-surface: if(functions.contrast-tone($surface) == "dark", #000, #fff) !default;
```

**Comment by asyncLiz** [comment]
This is likely due to an `@use` or `@import` that is loading `@material/theme` before you're customizing it in `src/core/_core.config.scss`.

I would check your imports in that file as well as `src/core/dsm-core.scss` to make sure there is nothing depending on our Sass files before your theme customization. If you can't immediately find the problem, you could share a repository link with me and I can help you identify where the issue is.

For reference, I just tested the following single Sass file and it compiles correctly with customizations:

```scss
@use "@material/theme" with (
  $primary: #fcb8ab,
  $secondary: #feeae6,
  $on-primary: #442b2d,
  $on-secondary: #442b2d,
);

@import "@material/button/mdc-button";
```

**Comment by kimurakenshi** [comment]
Thank you @asyncLiz,
                                    I couldn't find an `@use` before doing the module configuration for my theme just yet but if in your test it worked for you i'm sure this is an issue on my end. I will double check my code and reopen this issue if i have more precise steps to reproduce it.

Thank you so much.

**Comment by mlbiche** [comment]
Hi @kimurakenshi ! Have you fixed your issue ?

I am facing a similar issue here ! Here is my styles.scss file :

```
@use "@material/typography" with (
  $font-family: unquote("Poppins, sans-serif"),
  $styles-headline1: (
    font-size: 24px,
    line-height: 32px,
    font-weight: 800
  ),
  $styles-headline2: (
    font-size: 18px,
    line-height: 24px,
    font-weight: 600
  ),
  $styles-headline3: (
    font-size: 18px,
    line-height: 24px,
    font-weight: normal
  ),
  $styles-headline4: (
    font-size: 14px,
    line-height: 26px,
    font-weight: normal
  ),
  $styles-body1: (
    font-size: 14px,
    line-height: 16px,
    font-weight: normal
  )
);
@use "@material/theme" with (
  $primary: #0A99B7,
  $secondary: #F4AE1A,
  $on-primary: #FFFFFF,
  $on-secondary: #FFFFFF,
  $text-primary-on-light: #333333,
  $text-secondary-on-light: #333333
);

@use "@material/typography/mdc-typography";

@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap');

...
```

When preprocessing with :

```
sass --load-path node_modules styles.scss styles.css
```

I am getting a similar error to yours :

```
Error: This module was already loaded, so it can't be configured using "with".
   ┌──> node_modules/@material/theme/_index.scss
2  │   @forward "./variables";
   │   ^^^^^^^^^^^^^^^^^^^^^^ new load
   ╵
   ┌──> node_modules/@material/theme/_mixins.scss
28 │   @use "./variables";
   │   ━━━━━━━━━━━━━━━━━━ original load
   ╵
   ┌──> style.scss
29 │ ┌ @use "@material/theme" with (
30 │ │   $primary: #0A99B7,
31 │ │   $secondary: #F4AE1A,
32 │ │   $on-primary: #FFFFFF,
33 │ │   $on-secondary: #FFFFFF,
34 │ │   $text-primary-on-light: #333333,
35 │ │   $text-secondary-on-light: #333333
36 │ │ );
   │ └─^ configuration
   ╵
  @material/_index.scss 2:1            @use
  style.scss 29:1  root stylesheet
```

Removing the typography `@use` or putting the theme `@use`in first doesn't fix it. I have also tried removing some of the overrode value but it doesn't change anything.

When I am removing the @use "@material/theme with ..., it is working fine.
