### ISSUE TITLE
[mdc-select] [a11y] support typeahead

### ISSUE THREAD

**Issue by kvdheuvel** [material-components/material-components-web#5705]
## Bug report
The new mdc-select component does not support first letter navigation like the default 'select' > 'option' variant does.

### Steps to reproduce
Open the a11y variant of the mdc-select component and try to navigate to a list item with the keyboard.

### Actual behavior
The list items wont get selected

### Expected behavior
That the list item can be selected with the keyboard by selecting the first letter

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0
| Browser          | Chrome
| Operating System | Windows

**Comment by asyncLiz** [comment]
Thanks for the bug! We're currently working on select, so we'll add this to the features requested for it

**Comment by allan-chen** [comment]
Hi,

We're prototyped this feature in the list foundation and we're likely to ship it with select.
Will keep this issue updated, but currently the prescribed behavior is:

- Type a character: focus moves to the next item with a name that starts with the typed character.
- Type multiple characters in rapid succession: focus moves to the next item with a name that starts with the string of characters typed.

**Comment by ivangusev** [comment]
First letter navigation doesn't work. As reference you can see on demo page: [](https://material-components.github.io/material-components-web-catalog/#/component/select)

**Comment by allan-chen** [comment]
The demo is on v4.0 and needs to be updated. Meanwhile you can play with the latest version here: https://codepen.io/allanchenmdc/pen/MWKEqrK

**Comment by ivangusev** [comment]
@allan-chen Thanks, it works in codepen. Btw, can you please suggest how to make it open always down (i have a long list and it opens up, v6)?

**Comment by allan-chen** [comment]
Glad it works! Menusurface opens up if there's not enough space to open downwards. One way to nudge it to open down is to restrict the `max-height` of the `mdc-select__menu` element so there's more often than not space to open below. Hope this helps!
