### ISSUE TITLE
[mdc-linear-progress] scss files are not updated with new class names

### ISSUE THREAD

**Issue by kvdheuvel** [material-components/material-components-web#5706]
## Bug report
The new mdc-linear-progress scss files still uses the old class names for buffering. `mdc-linear-progress__buffering-dots` vs `mdc-linear-progress__buffer-dots`. The styling is not applied to the new classes.

### Steps to reproduce
1. Open a new mdc-linear-progress
2. Set the state to buffering
3. Styling is not applied

### Actual behavior
No styling is applied to the `buffer-dots` classes

### Expected behavior
Styling applied to the `buffer-dots` classes

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0
| Browser          | Chrome (but expect all)
| Operating System | Windows

### Additional context
The demo page isnt updated either

**Comment by asyncLiz** [comment]
That change has not been released yet, which is why the classes aren't working on v4.

You can try installing the `canary` version from npm if you'd like to see the new features!

**Comment by kvdheuvel** [comment]
@asyncLiz What do you mean with the change not being release yet? We installed `material-design-component@4.0.0` and tried to use the `mdc-linear-progress` but it is not working. The component itself has the new classnames but the scss still uses the old classnames.

Or am I missing something here?

**Comment by asyncLiz** [comment]
[v4.0.0](https://github.com/material-components/material-components-web/tree/v4.0.0/packages/mdc-linear-progress#html-structure) uses `mdc-linear-progress__buffering-dots`. [The latest](https://github.com/material-components/material-components-web/tree/master/packages/mdc-linear-progress#html-structure) uses `mdc-linear-progress__buffer-dots`.

Neither version's component directly refers to the dot class, that should be provided by the end user in markup.

Can you point out where in v4.0.0 it is referencing the newer `mdc-linear-progress__buffer-dots` class?

**Comment by kvdheuvel** [comment]
Right [here ](https://github.com/material-components/material-components-web/tree/master/packages/mdc-linear-progress) at the basic usage html structure:

`<div class="mdc-linear-progress__buffer">
    <div class="mdc-linear-progress__buffer-bar"></div>
    <div class="mdc-linear-progress__buffer-dots"></div>
  </div>`

**Comment by asyncLiz** [comment]
That link is pointing to the `master` branch, which is the canary release of 6.0.0.

If you're on an older version, you can switch to that version's tag to get the correct documentation: https://github.com/material-components/material-components-web/tree/v4.0.0/packages/mdc-linear-progress#html-structure.

**Comment by kvdheuvel** [comment]
@asyncLiz We have been using MDC since release 0.12 or something like that and I never noticed that tag. Thank you for your help (Y)
