### ISSUE TITLE
[mdc-checkbox] Unable to configure sass module

### ISSUE THREAD

**Issue by kimurakenshi** [material-components/material-components-web#5710]
## Bug report
While trying to overwrite some of the mdc-checkbox sass variables using `with` an error is being thrown during sass compilation phase. 

### Steps to reproduce
1. Try to configure the module like this:
```scss
@use "@material/checkbox" with (
  $ripple-size: 20px,
  $minimum-size: 20px,
  $maximum-size: 28px
);
```

```
 SassError: Can't find stylesheet to import.
        ╷
    110 │ ┌ @use "@material/checkbox" with (
    111 │ │   $ripple-size: 20px,
    112 │ │   $minimum-size: 20px,
    113 │ │   $maximum-size: 28px
    114 │ │ );
        │ └─^
        ╵
      src/core/_core.config.scss 110:1  @use
      src/core/dsm-core.scss 2:1        @use
      /Users/giras009/Documents/projects/ds-material-ui/site/core/styles/index.scss 7:1                         root stylesheet
```

### Actual behavior

Sass compilation fails.

### Expected behavior

I should be able to override sass variables.

### Additional context

I have done this kind of configuration with other mdc modules like typography and it works just fine. In this case i'm trying to override some sass variables to support custom sizes for the checkbox component.

**Comment by asyncLiz** [comment]
I just tested the following Sass file and was able to compile without error:

```scss
@use "@material/checkbox" with (
  $ripple-size: 20px,
  $minimum-size: 20px,
  $maximum-size: 28px
);

@import "@material/checkbox/mdc-checkbox";
```

We usually see this error when the Sass build system has not been set up to include paths for "node_modules". This is typically a `load-path` or `include_paths` option in your build system.

If you're still having trouble, can you post a full reproduction including your Sass build?

**Comment by kimurakenshi** [comment]
Thank you @asyncLiz. I have my build system configured to include `node_modules`, i had to setup that way from the beginning:
![image](https://user-images.githubusercontent.com/353436/76556327-8a641000-6456-11ea-98ca-f6293b33ff61.png)

It might be something on my end, maybe related to `sass-loader`. It's strange that it works for some modules and fails for others...

Since it works fine for you I will close this issue  and reopen if i have more information about it.

Thank you again.

**Comment by asyncLiz** [comment]
You could also try this workaround for Webpack's sass-loader: https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020

**Comment by kimurakenshi** [comment]
That fixed it, thank you!
