### ISSUE TITLE
[Chips] Choice chips not working

### ISSUE THREAD

**Issue by Zenoo** [material-components/material-components-web#5715]
## Bug report
Choice chips simply don't work.
If you set a chip to be selected at first, you see it, but as soon as you interact with it or others, nothing works anymore.

### Steps to reproduce
1. Go to https://material-components.github.io/material-components-web-catalog/#/component/chips
2. Try the Choice Chips demo

### Actual behavior
You can't select any chip

### Expected behavior
You should be able to change the selected chip by clicking another one.

### Screenshots
![](https://i.imgur.com/sMNqWRo.png)  
[See this gifv](https://i.imgur.com/LOXddhj.gifv)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | v5.1.0
| Browser          | Chrome v80.0.3987.132
| Operating System | Windows 10

**Comment by joyzhong** [comment]
Hi, are you able to reproduce this in chips locally? This may just be a material.io bug.

See https://github.com/material-components/material-components-web/issues/new?assignees=&labels=bug&template=--bug-report.md&title=%5BComponentName%5D+title for our recommended bug template and some links where you can set up working examples.

**Comment by Zenoo** [comment]
Oh no, sorry, I meant it doesn't work on material.io.
It works locally, just not on the demo.

**Comment by joyzhong** [comment]
I've moved this over to the catalog issues, see https://github.com/material-components/material-components-web-catalog/issues/284
