### ISSUE TITLE
Cannot make Create React App works with SASS material

### ISSUE THREAD

**Issue by ArthurGerbelot** [material-components/material-components-web#5720]
Cannot make works together:

 - Create React App v3.4 (React 16.13.0) 
 - @material SASS  v5.1.0
 - sass v1.26 

## How to reproduce

[Git Repository](https://github.com/ArthurGerbelot/issue-mdc-cra)
```
git clone https://github.com/ArthurGerbelot/issue-mdc-cra.git
cd issue-mdc-cra
npm i
npm start
```

## Error

Always getting errors:

**Using @import**
```
SassError: Two forwarded modules both define a variable named $mdc-feature-mdc-feature-all-features.
  ╷
3 │ @forward "@material/feature-targeting/variables" as mdc-feature-*;
  │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original @forward
4 │ @forward "@material/feature-targeting/mixins" as mdc-feature-*;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ new @forward
```
**Using @use**

```
SassError: Undefined function.
   ╷
72 │ @mixin common($query: feature-targeting-functions.all()) {
   │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Things I did

 - Create an app using `Create React App`
 - Adding [`sass` (and not `node-sass`)](https://github.com/material-components/material-components-web/issues/5502#issuecomment-590974715)
 - I added an `.env` file containing `SASS_PATH=./node_modules`
 - I tried all combinaison with(out) `~` and using `@import` or `@use`

Also tried to eject the app (not the best solution.. but..) in order to add on webpack config ([like here](https://github.com/material-components/material-components-web/issues/5502#issuecomment-587991004) or [here](https://github.com/robcaldecott/rmwc-cra2-example))but no success.

```
              implementation: require('sass'),
              webpackImporter: false,
              sassOptions: {
                includePaths: ['./node_modules'],
              },
```

**Comment by ArthurGerbelot** [comment]
Look like this issue is directly related to https://github.com/webpack-contrib/sass-loader/pull/808

**Comment by joyzhong** [comment]
Closing this, as the fix is tracked in https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-600265587.
