### ISSUE TITLE
Sass mixin mdc-elevation is not available unless @import is used

### ISSUE THREAD

**Issue by nmggithub** [material-components/material-components-web#5722]
## Bug report

The SASS compiler fails to find the mdc-elevation mixin unless '@import' is used to import mdc-elevation. '@use' does not work.

### Steps to reproduce
1. Create a SASS file called ```style.css``` with the following code:
```
@use "@material/elevation/mdc-elevation";

.elevated {
    @include mdc-elevation(5);
}
```
2. Open the terminal and run ```SASS_PATH=node_modules sass style.scss style.css```
3. See error
4. Change the code to:
```
@import "@material/elevation/mdc-elevation";

.elevated {
    @include mdc-elevation(5);
}
```
5. See the compilation succeeds.

### Actual behavior

Compilation using `@use` fails, but using `@import` doesn't.

### Expected behavior

Compilation using `@use` works, and so does using `@import`.

### Your Environment:

SASS (v1.26.3)
MDC (v5.1.0)

### Additional context

I may just be using mixins wrong. I've had difficulty getting them to work in general.

**Comment by asyncLiz** [comment]
Thanks for the issue! It looks like you're trying to use the `mdc-*` entrypoint, which applies styles but does not forward anything. You should use the index file to import mixins for customizations.

```scss
@use "@material/elevation";

.elevated {
  @include elevation.elevation(5);
}
```

Our Sass documentation for the new module system is a bit confused. I've created #5723 to follow up on improving it.

**Comment by NathanDePachtere** [comment]
Still, not working for me with that code :
`@use "~@material/elevation";
    .component :global{
        @include elevation.elevation(12);
    }`

I got this error : 
`SassError: Invalid CSS after "...clude elevation": expected "}", was ".elevation(12);"
        on line 52 of /.../project-card.vue
>>     @include elevation.elevation(12);`

Someone has an idea ?

**Comment by asyncLiz** [comment]
@NathanDePachtere check your Sass implementation. That error is indicative of the project using libsass (`node-sass`), which does not support the `@use` syntax. You must use the [dart-sass](https://sass-lang.com/dart-sass) implementation. You can get it by doing `npm uninstall node-sass && npm install sass`.

Webpack's sass-loader will automatically use it as the default implementation as long as `node-sass` is not installed.

**Comment by StraightOuttaCrompton** [comment]
I m getting the same issue where using the `@use` syntax doesn't work but using `@import` does. I am using `"parcel-bundler": "^1.12.4",` to bundle the sass with `"sass": "^1.26.10",`.
