### ISSUE TITLE
Typography styles question

### ISSUE THREAD

**Issue by blendsdk** [material-components/material-components-web#574]
Hi @sgomes,

Could you please clarify where the `latter-spacing `and the `margin `values in following URL come from?
I have not been able to find them in in MD specs!

[https://github.com/material-components/material-components-web/blob/master/packages/mdc-typography/_variables.scss](url)

Thnaks In advance.

**Comment by amsheehan** [comment]
Hello @blendsdk `letter-spacing` can be seen under tracking values in the typography section of the spec. Scroll down a little from [here](https://material.io/guidelines/style/typography.html#typography-other-typographic-guidelines)

As for margins, we have a class called `mdc-margin-adjust` which tweaks text such that Roboto on the web aligns with the [vertical rhythm detailed in the spec](https://material.io/guidelines/layout/metrics-keylines.html#)
