### ISSUE TITLE
Support space-between in form field

### ISSUE THREAD

**Issue by Misiu** [material-components/material-components-web#5747]
## Feature Request

I'm trying to create this type of UI:
![image](https://user-images.githubusercontent.com/1741838/77621202-484dca80-6f3c-11ea-972a-fd825336ced0.png)
with web components, but unfortunately it isn't  easy doable.
I was suggested to use `formfield` but this gives me this:
![image](https://user-images.githubusercontent.com/1741838/77621303-7a5f2c80-6f3c-11ea-88df-da18e1a68371.png)

The label is on the other side and there is no space between.

I got a suggestion from @asyncLiz (in https://github.com/material-components/material-components-web-components/issues/999) to create this FR and ask to add `mdc-form-field--space-between` that would allow easy creating such UI.

This type of UI is presented at official material.io site: https://material.io/components/selection-controls/#switches so I think there should be first-class support for it.

### Additional context

My main goal is to have support for this in `https://github.com/material-components/material-components-web-components`, but I think if this will be addressed here then the next step is adding support in web components.

**Comment by asyncLiz** [comment]
Proposed solution would be to add the following CSS:

```css
.mdc-form-field--space-between {
  justify-content: space-between;
}
```

**Comment by asyncLiz** [comment]
@Misiu we'll need to prioritize resources for this, but it should be a relatively easy feature to add if you want to take a shot at a pull request.

**Comment by Misiu** [comment]
@asyncLiz something like this: https://jsfiddle.net/Misiu/quzgcsev/25/ ??
I never did PR to this repo, but I can try if the results are ok with you 🙂
