### ISSUE TITLE
[mdc-typography] global Sass variable overrides don't work

### ISSUE THREAD

**Issue by nicholaschiang** [material-components/material-components-web#5781]
## Bug report

The global Sass variable overrides as documented on the ([rather out-dated](https://github.com/material-components/material-components-web/issues/5780)) [website documentation](https://material.io/develop/web/components/typography/) and [this `README.md`](https://github.com/material-components/material-components-web/tree/master/packages/mdc-typography#style-customization) **do not work**.

I'm overriding the `$mdc-typography-styles-headline1` and then `@use`-ing the `@material/typography` library (in `src/styles/global.scss`):
```sass
$mdc-typography-styles-headline1: (
  font-family: unquote("Roboto Condensed"),
  font-size: 96
);
@use '@material/typography/mdc-typography';
@import url('https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,500');
```
But the generated styling still uses `Roboto` as it's font:

![image](https://user-images.githubusercontent.com/20798889/78467221-33510400-76bf-11ea-9373-4e8e25eceac9.png)

### Steps to reproduce
1. Clone [this repository](https://github.com/tutorbookapp/covid-tutoring) at [`47735a5`](https://github.com/tutorbookapp/covid-tutoring/commit/47735a54310595c492f0c52fafd5c00426149d61)
2. Install our dependencies with the following (**in this order** because of [this issue](https://github.com/tutorbookapp/covid-tutoring/issues/6)):
```
$ npm install
$ lerna bootstrap --hoist
```
3. Start a development server by running:
```
$ npm run dev
```
4. Open [`http://localhost:3000/`](http://localhost:3000/), inspect any text element, and see error

### Actual behavior

The generated styling uses `Roboto` as it's font instead of `Roboto Condensed`.

### Expected behavior

It should use `Roboto Condensed` as the `font-family` for all `mdc-typography--headline1` elements.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | `^6.0.9`
| Browser          | Mozilla Firefox for Ubuntu 74.0 (64-bit)
| Operating System | Ubuntu 18.04.2

### Additional context

We're using Next.js and other frameworks as described in [this `README.md`](https://github.com/tutorbookapp/covid-tutoring#contributing) but that shouldn't be an issue.

### Possible solution

Our current workaround (in `src/styles/global.scss`) is to use Sass module variables:
```sass
@use '@material/typography' with (
  $font-family: unquote('Roboto Condensed'),
);
@include typography.core-styles;
@import url('https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,500');
```

**Comment by asyncLiz** [comment]
This is working as intended. You cannot use a global variable and `@use` at the same time. You may use global variables to override when using `@import` only.

See [Typography's Overriding Styles section](https://github.com/material-components/material-components-web/tree/master/packages/mdc-typography#overriding-styles) for the possible combinations.

Our recommendation would be to prefer Sass modules. The correct way to override the styles with your code using Sass modules is this:

```scss
@use "@material/typography" with (
  $styles-headline1: (
    font-family: unquote("Roboto Condensed"),
    font-size: 96
  )
);

@use '@material/typography/mdc-typography';
@import url('https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,500');
```

Using global variables, it would look like this. Be warned that if you are mixing `@use` and `@import` that this partial should be imported _first_ in your application. Otherwise it won't be configured properly.

```scss
$mdc-typography-styles-headline1: (
  font-family: unquote("Roboto Condensed"),
  font-size: 96
);

@import '@material/typography/mdc-typography';
@import url('https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,500');
```
