### ISSUE TITLE
[Theme] Update to M2 and clean up text styles

### ISSUE THREAD

**Issue by asyncLiz** [material-components/material-components-web#5784]
## Feature Request
MDC's theme needs to be cleaned up. There are references to the old M1 spec and some missing features that are blocking theming for MWC.

### Proposed solution
**1. Text style names**
In M1, text styles were referred to as "primary" and "secondary". This caused confusion with "primary" and "secondary" theme colors. In M2 text opacity is now referred to as ["high" and "medium" emphasis](https://material.io/design/color/text-legibility.html#text-backgrounds).

Our [text styles](https://github.com/material-components/material-components-web/tree/master/packages/mdc-theme#text-styles) should replace `primary` with `high` and `secondary` with `medium`.

**2. Provide on-surface text styles**
We provide keys for [`text-<STYLE>-on-background`](https://github.com/material-components/material-components-web/blob/6a40ef217f597138ee2920d2160364649dbf5620/packages/mdc-theme/_variables.scss#L101-L106), but none for `on-surface`. These should be added, and components that use `on-surface` with a custom opacity should use the new keys.

For example, textfield's [`$ink-color`](https://github.com/material-components/material-components-web/blob/776291ef03205e4063b4040eb66f9648e16b4af6/packages/mdc-textfield/_variables.scss#L47) should use `text-high-on-surface` instead of `rgba(on-surface, 0.87)`.

**3. Use $text-emphasis values**

[`$text-emphasis`](https://github.com/material-components/material-components-web/blob/6a40ef217f597138ee2920d2160364649dbf5620/packages/mdc-theme/_variables.scss#L70-L74) defines M2 text opacity values, but they are not currently being used in the [`$text-colors`](https://github.com/material-components/material-components-web/blob/6a40ef217f597138ee2920d2160364649dbf5620/packages/mdc-theme/_variables.scss#L53-L68). This should change.

This will be a breaking change for dark theme since currently dark theme (light text) opacities are different. Per spec, both [light](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1584058305895%2Fassets%2F1GhaWa2gWZeKpAHyHoN4DMHZTD-ZqUZp5%2Fcolor-legibility-darktext.png) and [dark](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1584058305895%2Fassets%2F1iibya7ExTm_Lh_qB0ivDyzLjVmy3qEDC%2Fdarktheme-adjustedcolor-textlegibility.png) theme text opacities should be the same.

We should additionally upgrade these to first-class property keys with custom property support. That way if a component needs to refer to the opacity value (such as [switch's track](https://github.com/material-components/material-components-web/blob/6a40ef217f597138ee2920d2160364649dbf5620/packages/mdc-switch/_mixins.scss#L283)), they may use `theme.prop(text-emphasis-<STYLE>)`.

**4. Deprecate and remove instances of `theme.prop-value()` where possible**

`theme.prop-value()` removes the capability to use CSS custom properties. In many instances, this is not necessary at all, such as [checkbox's `$mark-color`](https://github.com/material-components/material-components-web/blob/6a40ef217f597138ee2920d2160364649dbf5620/packages/mdc-checkbox/_variables.scss#L29). In most others, this will no longer be necessary with the introduction of `on-surface` text styles.

Deprecating the function will encourage the use of other solutions that focus on prioritizing keeping CSS custom properties as a theming solution.

### Alternatives considered
N/A

### Additional context
N/A

**Comment by MrBirb** [comment]
I must say this is taking quite a long time

**Comment by asyncLiz** [comment]
This issue is a bit obsolete now that we're focusing on [Material You](https://github.com/material-components/material-web/issues/2441) in the material-web repository, which will have a new focus on tokens and theming support.

Closing to clean up some of these old issues.
