### ISSUE TITLE
[circular-progress] Missing .npmignore file

### ISSUE THREAD

**Issue by trimox** [material-components/material-components-web#5800]
Missing `.npmignore` file causing typescript `*.ts` to be included on registry publish..

![image](https://user-images.githubusercontent.com/11887843/78898950-a8676500-7a42-11ea-8bed-5bf48f50032d.png)

**Comment by patrickrodee** [comment]
Sounds like a possible issue with Google internal-first development. Need to explore generating an .npmignore file for new components.

**Comment by patrickrodee** [comment]
Ignoring `.ts` files might be a moot point as we explore publishing sourcemaps.
