### ISSUE TITLE
[Switch] [Angular] Not clear (no pun intended) how to obtain transparent track border color

### ISSUE THREAD

**Issue by andrewseguin** [material-components/material-components-web#5804]
Angular Material wants to use the Switch with different colors. The mixins support this by using this set of Sass includes:

```scss
.my-rainbow-switch {
  @include mdc-switch-without-ripple($query: (structure));

  .mdc-switch {
    @include mdc-switch-toggled-on-track-color(red);
    @include mdc-switch-toggled-on-thumb-color(purple);
    @include mdc-switch-toggled-off-track-color(green);
    @include mdc-switch-toggled-off-thumb-color(blue);
  }
}
```

However, this misses one important style found in the switch's `thumb_` mixin:
```scss
@mixin track_($query) {
  ..  

  @include feature-targeting-mixins.targets($feat-color) {
    @include theme-mixins.prop(border-color, transparent);
  }

  ..
}
```

The workaround would be to call `mdc-switch-without-ripple((structure, color)` but this includes a lot of color styles that would be unnecessary and overwritten.

Perhaps we can have a separate mixin that applies the border-color like `mdc-switch-track-border-color($color)`?

**Comment by patrickrodee** [comment]
Need to look into removing the color feature targeting from the transparent border.
