### ISSUE TITLE
focused Select has shaded background, without padding

### ISSUE THREAD

**Issue by mhuebert** [material-components/material-components-web#582]
### What MDC-Web Version are you using?

0.10.0

### What browser(s) is this bug affecting?

All browsers AFAIK (I am using Chrome Version 57.0.2987.133 (64-bit))

### What OS are you using?

Mac OS 10.12.3

### What are the steps to reproduce the bug?

View the Select component on the demo, either CSS-only or JS-upgraded

### What is the expected behavior? Actual behavior?

The focused state is communicated using a shaded background, without padding inside the edges of the background:

<img width="410" alt="screen shot 2017-05-03 at 11 49 32 pm" src="https://cloud.githubusercontent.com/assets/165223/25683158/317524e8-305b-11e7-95e0-b4545a139118.png">

This immediately caught my eye and I spent some time digging into the guidelines to see what has been specified. I found at least three areas of Material guidelines which may be relevant (there doesn't seem to be just one place where this component is cleanly spec'd):

1. The guidelines for [dropdown buttons](https://material.io/guidelines/components/buttons.html#buttons-dropdown-buttons) include a number of component examples with behavior similar to a Select component, which contain an arrow icon and show content on click. Whenever these components are displayed with a border or background, the focused and selected states include padding around the text and icon.

    <img width="323" alt="screen shot 2017-05-04 at 1 32 11 pm" src="https://cloud.githubusercontent.com/assets/165223/25701788/26b7ca24-30ce-11e7-8515-3b15d7365a81.png">

    <img width="239" alt="screen shot 2017-05-03 at 11 56 42 pm" src="https://cloud.githubusercontent.com/assets/165223/25683385/370996b8-305c-11e7-9473-5f8a3563ca2f.png">

Unfortunately the primary illustration for Dropdown buttons, which the Select component seems to be modeled after, does not show an 'active' state, but there are no examples anywhere in the guide that display text or icons without padding on the edge of a shaded or bordered region. 

2. The [guidelines for text fields](https://material.io/guidelines/components/text-fields.html#text-fields-layout) also include a section on dropdown icons. 

    Icons are displayed with padding:

    <img width="251" alt="screen shot 2017-05-03 at 11 51 02 pm" src="https://cloud.githubusercontent.com/assets/165223/25683216/6341983a-305b-11e7-9f9e-acd7ab2d46d9.png">

    <img width="199" alt="screen shot 2017-05-03 at 11 50 33 pm" src="https://cloud.githubusercontent.com/assets/165223/25683206/57ad4302-305b-11e7-9ffd-0621011bc84b.png">
    
    Focus is indicated by thickening and coloring the underline:

    <img width="286" alt="screen shot 2017-05-03 at 11 55 39 pm" src="https://cloud.githubusercontent.com/assets/165223/25683345/08ded3a2-305c-11e7-8ca3-985a7093bd01.png">

    When a shaded background is used to indicate focus, all of its interior sides are padded:

    <img width="258" alt="screen shot 2017-05-03 at 11 52 33 pm" src="https://cloud.githubusercontent.com/assets/165223/25683268/a51a238a-305b-11e7-8135-59965fcd500e.png">

3. The [guidelines for menus](https://material.io/guidelines/components/menus.html#menus-specs) are also relevant but this page does not display examples of dropdowns with icons in a focused state.

I think a simple way to indicate focus, consistent with the guidelines, would be to thicken the underline and not change the background at all. If the background is to be darkened or depth added, then we have to add padding and the layout will have to change more dramatically.

Normal and focused states could like something like:

<img width="291" alt="screen shot 2017-05-04 at 12 12 00 am" src="https://cloud.githubusercontent.com/assets/165223/25683824/57a21cae-305e-11e7-8ba3-241f2c584893.png">

Lastly, this discussion is somewhat related to #547.  The decision there was to style the Select element more as a drop-down button than a drop-down text field, and avoid floating labels. But there are multiple guidelines that cover Select-like elements, so it's not clear why we should only look at the 'button' section and ignore the rest of the guides for the reference implementation. Select elements are often used in forms, require labels for clarity, and [many examples in the guidelines](https://github.com/material-components/material-components-web/issues/547#issuecomment-296735384) have floating labels. If we don't provide it, developers will have to implement it independently _if they want to follow the guidelines_. For reference, here is the same normal/focused preview with floating labels: 

<img width="294" alt="screen shot 2017-05-04 at 12 08 45 am" src="https://cloud.githubusercontent.com/assets/165223/25701374/74348d20-30cc-11e7-81ed-bed0321f39f6.png">

**Comment by amsheehan** [comment]
You are correct! This is actually a case where the component was built before recent spec changes. If you would like to track the progress of updating `mdc-select` to the newest spec, you can take a look at the Text Field Improvements Epic (stories forthcoming).

**Comment by mhuebert** [comment]
Great!

Forgive my ignorance, but where can the Epic be tracked?

**Comment by mbirth** [comment]
Pivotal links back to: [Milestone 5](https://github.com/material-components/material-components-web/milestone/5).
