### ISSUE TITLE
How to add multi selection groups for drawer list?

### ISSUE THREAD

**Issue by iMrDJAi** [material-components/material-components-web#5826]
Look at this example:

![Capture](https://user-images.githubusercontent.com/42304709/79499301-a5f8a280-8022-11ea-9fba-a43eec62b540.PNG)

I used multiple lists here, but this will break the keyboard control.

Anyway to do that using only one list?

**Comment by CyborgSemon** [comment]
Just have one list and separate each section with a separator and then a sub header (you don't need the separator, but it looks nice with it 😉)
```html
<a class="mdc-list-item" href="#"><span class="mdc-list-item__text">Rising</span></a>
<hr class="mdc-list-divider">
<h6 class="mdc-list-group__subheader">Submit</h6>
<a class="mdc-list-item" href="#"><span class="mdc-list-item__text">Self Text</span></a>
```
etc...
Hope this helps!

**Comment by iMrDJAi** [comment]
Didn't work, I only can select one item at once on the whole list.
That's what I did for now:
```html
<nav class="mdc-list">
     <h6 class="mdc-list-group__subheader">Sorting</h6>
     <a class="mdc-list-item mdc-list-item--activated" href="#" tabindex="0"><span class="mdc-list-item__text">New</span></a>
     <a class="mdc-list-item" href="#"><span class="mdc-list-item__text">Hot</span></a>
     <a class="mdc-list-item" href="#"><span class="mdc-list-item__text">Rising</span></a>
     <hr class="mdc-list-divider">
     <h6 class="mdc-list-group__subheader">Flairs</h6>
     <a class="mdc-list-item mdc-list-item--activated" href="#"><span class="mdc-list-item__text"># Memes</span></a>
     <a class="mdc-list-item" href="#"><span class="mdc-list-item__text"># News</span></a>
     <a class="mdc-list-item" href="#"><span class="mdc-list-item__text"># Videos</span></a>      
</nav>
```

**Comment by CyborgSemon** [comment]
ohhhhhh you want to to have multiple selections? I think you might be using the wrong component then. The draw component is meant for navigation.
(See https://material.io/components/navigation-drawer#usage)
I would recommend have multiple select drop downs at the top of your page somewhere for each category. (You can find that component here: https://material-components.github.io/material-components-web-catalog/#/component/select)
Either that, or make your own custom script that can handle one big list with multiple selections and just use the CSS for the MDCList component.

So, something like this:
```js
[].forEach.call(document.querySelectorAll('.mdc-list-item'), (ele)=> {
  ele.addEventListener('click', ()=> {
    if (ele.classList.contains("mdc-list-item--activated")) {
      ele.classList.remove("mdc-list-item--activated");
      // Do any other JS you need to for toggling off that option
    } else {
      ele.classList.add("mdc-list-item--activated");
      // Do any other JS you need to for toggling on that option
    }
  });
});
```
That should work if you don't use the MDCList JS, but I would definitely recommend going thorough the select drop down option. It's always best to use the components for their intended use case as that is what they were built to do.

Hope that helps :)

**Comment by iMrDJAi** [comment]
Select drop downs seems good to me, can I use them inside the drawer?

**Comment by CyborgSemon** [comment]
I would recommend against it. Draws are built for direct navigation, and this doesn't really count. You may run into some issue trying to get it work as draws also were only really build to handle MDCList. 
You should try to add the drop downs into the top app bar (best example of this is the google calendar app). But again, idk if the top app bar was built for drop downs. so you may have to mess around with the css a little
<img width="1440" alt="Screen Shot 2020-04-18 at 3 13 15 AM" src="https://user-images.githubusercontent.com/26075792/79584607-bb54f600-8122-11ea-91c5-a78f1ae3dedb.png">

<img width="364" alt="Screen Shot 2020-04-18 at 3 13 29 AM" src="https://user-images.githubusercontent.com/26075792/79584622-bf811380-8122-11ea-9f01-22fb62b32d75.png">

**Comment by iMrDJAi** [comment]
You're right, it kindly looks bad on the drawer, even css can't really help.
I think I will try it on the top bar.

![image](https://user-images.githubusercontent.com/42304709/79584854-dd208f80-80c6-11ea-97b7-c30a039e372e.png)

**Comment by CyborgSemon** [comment]
Yeah. Check my last message as well for another option. (I updated it :P)

**Comment by iMrDJAi** [comment]
Yes, I saw it. I can use something similar to Reddit too.
or maybe a [tab bar](https://material-components.github.io/material-components-web-catalog/#/component/tabs)? Is that recommended?

**Comment by CyborgSemon** [comment]
Well, for your case I would say no. As you are wanting multiple selection options. Having 3 tab bars on top of each other would look very weird.
I would say go the reddit option first, then if you don't like how it kooks give the top app bar option a try.

**Comment by iMrDJAi** [comment]
Not 3, just one to navigate on multiple flairs and one to select sorting method, I would keep the first on the drawer.

For the submit section, it would be just like buttons.

**Comment by CyborgSemon** [comment]
Yeah I could see that working. Give it a shot.

**Comment by iMrDJAi** [comment]
@CyborgSemon Hey again, I got another question to ask: How can I disable the keyboard interaction from a list? This maybe help me at the first case.

**Comment by iMrDJAi** [comment]
So look at what I did: I added 2 extra lists inside the main drawer list:

```html
<nav class="mdc-list" data-main="true">
    <div class="mdc-list-group">
        <h3 class="mdc-list-group__subheader">List 1</h3>

        <ul class="mdc-list" role="listbox">
            <li class="mdc-list-item mdc-list-item--activated" role="option" aria-selected="true" tabindex="0">
                <span class="mdc-list-item__text">line item</span>
            </li>
            <li class="mdc-list-item">
                <span class="mdc-list-item__text" role="option" aria-selected="false">line item</span>
            </li>
            <li class="mdc-list-item">
                <span class="mdc-list-item__text" role="option" aria-selected="true">line item</span>
            </li>
        </ul>

        <h3 class="mdc-list-group__subheader">List 2</h3>

        <ul class="mdc-list" role="listbox">
            <li class="mdc-list-item mdc-list-item--activated" role="option" aria-selected="true" tabindex="0">
                <span class="mdc-list-item__text">line item</span>
            </li>
            <li class="mdc-list-item" role="option" aria-selected="false">
                <span class="mdc-list-item__text">line item</span>
            </li>
            <li class="mdc-list-item" role="option" aria-selected="false">
                <span class="mdc-list-item__text">line item</span>
            </li>
        </ul>

    </div>
</nav>
```
```js
var {MDCRipple} = require('material-components-web').ripple;
var {MDCDrawer} = require('material-components-web').drawer;
var {MDCList} = require('material-components-web').list;


var drawer = new MDCDrawer(document.querySelector('.mdc-drawer'));
drawer.list.singleSelection = false;

for (mdcList of document.querySelectorAll('.mdc-list')) {
    if (!mdcList.getAttribute("data-main")) {
        const list = new MDCList(mdcList);
        list.listElements.map((listItemEl) => new MDCRipple(listItemEl));
        list.singleSelection = true;
    }
}
```
Now the multiple selection works fine:

![image](https://user-images.githubusercontent.com/42304709/79600265-c71ec900-80de-11ea-86a0-20cd18b8ed85.png)

But pressing the keyboard up/down key will give focus at the second next element, and you can figure why, both of the nested lists and the main lists handle the keyboard interaction at the same time, so I have to disable that from the nested list to make it work fine.

**Comment by CyborgSemon** [comment]
Well, the keyboard interaction comes baked into the javascirpt when you initiate the list. I don't know if you can disable it sadly. Looking at the documentation for the list, it doesn't look like you can disable the keyboard interaction without disabling the entire list. I would go down the tab bar idea you mentioned earlier. That sounds the most promising.

**Comment by iMrDJAi** [comment]
I guess I'm going to create another issue to suggest these features:

- Multi-selection lists.
- A way to disable keyboard interaction.

I tried the tab bar but it didn't really looks good to me, I guess I'm going to disable the whole drawer list in that way until new update:

```js
var drawer = new MDCDrawer(document.querySelector('.mdc-drawer'));
drawer.list.destroy();
```

The keyboard interaction will work like that but you have to press TAB to get to the other list.

THX for helping anyway :)
