### ISSUE TITLE
Table sorting using CDN

### ISSUE THREAD

**Issue by cojua8** [material-components/material-components-web#5827]
Hi,
I've been trying to use the table with sorting ([here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-data-table#data-table-with-column-sorting)) with CDN, but I just can't make it work. 
The first problem comes when I try to instantiate it with:
```
mdc.dataTable.MDCDataTable.attachTo(document.querySelector('.mdc-data-table'));
```

this throws the following error
```
material-components-web.min.js:1 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at p.initialSyncWithDOM (material-components-web.min.js:1)
    at p.a (material-components-web.min.js:1)
    at new p (material-components-web.min.js:1)
    at Function.p.attachTo (material-components-web.min.js:1)
    at <anonymous>:1:28
```

How can I solve it?.

**Comment by asyncLiz** [comment]
It looks like our docs are missing `class="mdc-data-table__header-row"` on the header row. Can you try adding that to your template?

**Comment by asyncLiz** [comment]
@abhiomkar I've copied the template from the docs to https://jsbin.com/hujipupoba/edit?html,output with the header row class added, can you confirm that this is the only thing missing? I'm not sure if the styles or interactivity is correct.

**Comment by abhiomkar** [comment]
Sorting is not yet launched in MDC Web vanilla implementation. But styles should work in `@canary` - here is an [example](https://jsbin.com/mucobukoza/edit?html,output).

I'll update the docs with sorting implementation status.
