### ISSUE TITLE
mdl-cell--hide-phone corresponding class in mdc-layout-grid

### ISSUE THREAD

**Issue by berets76** [material-components/material-components-web#583]
As in the subject, how can I hide a mdc-layout-grid__cell in mobile or tablet devices ?

Thanks

**Comment by amsheehan** [comment]
We actually have an [open issue](https://github.com/material-components/material-components-web/issues/23) that may be of some help once implemented.

We feel this will be helpful for more than just `mdc-layout-grid` so special breakpoint modifiers will not be implemented on a component by component basis.

Closing now, as this is a duplicate of #23
