### ISSUE TITLE
[mdc-list] We need the ability to do multiple selection.

### ISSUE THREAD

**Issue by iMrDJAi** [material-components/material-components-web#5839]
## Feature Request
Lists on Material Design Components are great, but there is something missing.
We can do a single selection on the whole list, but we should also be able to do multiple selection as I mentioned in this [issue](https://github.com/material-components/material-components-web/issues/5826).

### Proposed solution
The deal here is the ability to do a single selection on each nested section.
Maybe this can happen by grouping the list elements, or a new attribute to define which group an element belongs to.

### Alternatives considered
In the other side this can be happen too if we put lists inside lists like [that](https://github.com/material-components/material-components-web/issues/5826#issuecomment-615390377).
Sadly, this method will break the keyboard interaction, so as an alternative solution we need the ability to disable the keyboard interaction to be able to apply that on the nested list so the main list will handle it alone. 

### Additional context
![image](https://user-images.githubusercontent.com/42304709/79636706-8b810f00-8171-11ea-88f4-f6874114eadf.png)

**Comment by CyborgSemon** [comment]
There are a few examples of lists with check boxes in the design spec here: https://material.io/components/lists
I guess that would offer multi select functionality, but it wouldn't look as nice as just having them selectable.

**Comment by iMrDJAi** [comment]
Yeah, and I noticed that the example [here](https://material.io/inline-tools/list/) has something similar:

![image](https://user-images.githubusercontent.com/42304709/79640012-1caeb080-8187-11ea-9060-fc3765410d80.png)
