### ISSUE TITLE
The textfield component's bottom bar doesn't respect the "invalid styling"

### ISSUE THREAD

**Issue by AustP** [material-components/material-components-web#584]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

v0.10.0

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

Linux

### What are the steps to reproduce the bug?

1. Visit https://material-components-web.appspot.com/textfield.html
2. Scroll down to "Password field with validation"
3. Look at the "Choose password*" textfield

### What is the expected behavior?

The bottom bar should be red.

### What is the actual behavior?

The bottom bar is gray.

### Any other information you believe would be useful?

![image](https://cloud.githubusercontent.com/assets/2007045/25719380/7b171e38-30c6-11e7-9f0c-e8ee67d1030e.png)

should be

![image](https://cloud.githubusercontent.com/assets/2007045/25719404/8af539b6-30c6-11e7-83d3-e5ee4dbf7bcd.png)

The styling is set, but the invalid styling is not specific enough so it gets overridden by the default color.

**Comment by amsheehan** [comment]
Thanks for filing an issue for this. It's something we've noticed and have a solution for and will be fixed when #570 gets merged.

**Comment by AustP** [comment]
@amsheehan This issue isn't about checking for bad input. This issue is about the styling rules for invalid text fields.

![image](https://cloud.githubusercontent.com/assets/2007045/25816415/4974e9d2-33e1-11e7-9831-b77977c968fd.png)

should be

![image](https://cloud.githubusercontent.com/assets/2007045/25816445/596993a6-33e1-11e7-8ac6-3111786b8f4e.png)

Notice the dividing line between the helptext and the label. It should be red but it is gray. You can see my proposed changes in #585 to see that this is a SASS issue.

**Comment by amsheehan** [comment]
Aha, Yep.

Pardon me while I put my foot in my mouth 😄 

I'll checkout the PR. Thanks! Also... nice jersey 👍

**Comment by AustP** [comment]
Ok, cool. And thanks! Go, Pack, Go! :wink:
