### ISSUE TITLE
[TextField] Floating label does not move when input is entered [regression?]

### ISSUE THREAD

**Issue by tomasdev** [material-components/material-components-web#5857]
## Bug report
When using @v5.1.0 from CDN the bug is not present. When using @latest as the docs recommends, it is present.

No bug @v5.1.0:
![no-bug](https://user-images.githubusercontent.com/364033/80143499-34ce6780-85ad-11ea-9478-b6ebee4f45a4.gif)
Source-code: https://jsbin.com/wujuwuxipi/1/edit?html,output

Bug present in @latest:
![bug](https://user-images.githubusercontent.com/364033/80143500-3566fe00-85ad-11ea-8f63-3d1b86850268.gif)
Source-code: https://jsbin.com/hobalazehu/1/edit?html,output

**Comment by tomasdev** [comment]
Probably unrelated but worth mentioning:
`.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label` has a hard-coded value that is not using the CSS variable it should (`--mdc-theme--primary`)
![Screenshot 2020-04-23 at 22 04 23](https://user-images.githubusercontent.com/364033/80144244-73185680-85ae-11ea-8a5c-5a659746ad9f.png)

**Comment by asyncLiz** [comment]
As mentioned in the [breaking changes](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#breaking-changes) for the latest version (v6):

> **textfield:** Default textfields must now specify mdc-text-field--filled. Disabled outlined textfields no longer have a shaded background. Height mixin no longer specifies a baseline override, use typography's baseline-top mixin

Add the `mdc-text-field--filled` class to your textfield and it works correctly: https://jsbin.com/ciwujoxusi/1/edit?html,output (note that you're also missing the `mdc-text-field__ripple` element).

The docs in this repo should be updated, but there may be codelabs or examples outside that have yet to be updated referencing the new `mdc-text-field--filled` class.

For the label color, CSS custom properties are not fully supported everywhere. Textfield is notorious for not supporting them. We're tracking fixing this in https://github.com/material-components/material-components-web/issues/5242.

**Comment by tomasdev** [comment]
@asyncLiz thanks, may be worth adding that to the docs at m.io site

**Comment by asyncLiz** [comment]
material.io has not been updated with the latest docs yet, we're currently in the process of updating it
