### ISSUE TITLE
MDCTemporaryDrawer not removing opacity

### ISSUE THREAD

**Issue by cgfarmer4** [material-components/material-components-web#586]
For some reason whenever I set `mdc.drawer.MDCTemporaryDrawer.open = false`, the drawer opacity layer does not return to 0. Works sometimes on desktop but not sure what I'm calling to make it fail or not work. 

I can see that a css class is not updating the opacity to 0 but I'm not sure how to go about fixing it with your guys foundation obfuscations.

![kapture 2017-05-04 at 18 21 21](https://cloud.githubusercontent.com/assets/336449/25730960/7f565fe2-30f6-11e7-9df8-903cac85344e.gif)

**Comment by anton-kachurin** [comment]
Already addressed #555

**Comment by cgfarmer4** [comment]
Thanks for your quick response and fix!

I will keep this open until the commit has landed in master and so I can test.

**Comment by amsheehan** [comment]
As @anton-kachurin mentioned, this has been addressed by #555 

Thanks for filing!

**Comment by cgfarmer4** [comment]
@amsheehan can we get the fix merged down into master?

**Comment by amsheehan** [comment]
@cgfarmer4 Consider it done!

**Comment by cgfarmer4** [comment]
@amsheehan thank you!
