### ISSUE TITLE
[ripple] - animation not working as expected

### ISSUE THREAD

**Issue by slaven3kopic** [material-components/material-components-web#5869]
Ripple animation behaves differently in the demo 
(https://material-components.github.io/material-components-web-catalog/#/component/button) and in the "real" world (https://codesandbox.io/s/vigorous-sound-3bf0e?file=/index.html) . In the demo animation is nice, smooth and with transition while in the real world just has "highlight" effect.

**Comment by abhiomkar** [comment]
You'll also need to initialize ripple on the target button in JS. Updated your [codesandbox example](https://codesandbox.io/s/nostalgic-gauss-56y0z).
