### ISSUE TITLE
[mdc-text-field] and [mdc-select] floating labels, [mdc-snackbar] action text, [mdc-drawer] list text and icon: color should be --mdc-theme-secondary/primary, but is hard-coded to purple

### ISSUE THREAD

**Issue by danielweck** [material-components/material-components-web#5878]
## Bug report

The text field's floating label is always purple, even when `--mdc-theme-secondary` or `--mdc-theme-primary` is set to custom colors.

https://material-components.github.io/material-components-web-catalog/#/component/text-field

https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield

Note that this problem of "hard-coded" colors exists also for:

* `mdc-select` ( to reproduce, open: https://material-components.github.io/material-components-web-catalog/#/component/select )
* `mdc-snackbar` ( to reproduce, open: https://material-components.github.io/material-components-web-catalog/#/component/snackbar )
* `mdc-drawer` / `.mdc-list-item--activated` ( to reproduce, open: https://material-components.github.io/material-components-web-catalog/#/component/drawer )

### Steps to reproduce

1. Go to https://material-components.github.io/material-components-web-catalog/#/component/text-field
2. Open the web inspector, and add a `style` attribute to the `body` or `html` element, in order to change the theme's primary and secondary color CSS properties, for example: `style="--mdc-theme-primary: magenta; --mdc-theme-secondary: orange;"`

### Actual behavior

The floating label is always purple

### Expected behavior

The floating label should have the color of either primary or secondary

### Screenshots

![MDC_floatingLabel](https://user-images.githubusercontent.com/625201/80789469-f83dd580-8b83-11ea-92c2-0ff85aa5478b.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 6.0.0
| Browser          | Firefox (latest)
| Operating System | MacOS 10.15.4

### Possible solution

My current workaround is to override the following selectors:

```
/* MDC select floating label */
.mdc-select:not(.mdc-select--disabled).mdc-select--focused .mdc-floating-label,

/* MDC drawer list item text */
.mdc-drawer .mdc-list-item--activated .mdc-list-item__graphic,

/* MDC drawer list item leading icon */
.mdc-drawer .mdc-list-item--activated,

/* MDC snackbar */
.mdc-snackbar__action:not(:disabled),

/* MDC textfield floating label */
.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label
{
    color: var(--mdc-theme-secondary); /* or primary */
}
```

**Comment by asyncLiz** [comment]
Thanks for the bug! This is related to #5242; there are several components where custom properties are not fully supported. To keep things organized, I've added your findings to that issue and I'll close this one.

Feel free to subscribe to that issue for updates!
