### ISSUE TITLE
[list] Row Selection like in Datatable 

### ISSUE THREAD

**Issue by RobinLouisSchmidt** [material-components/material-components-web#5885]
-> checkbox in head to select all fields
-> checkbox in head to deselect all fields

-> Counter to show the amount of all selected fields

**Comment by joyzhong** [comment]
Thanks for reaching out with this feature request! Unfortunately, as an engineering team with the goal of implementing components that are aligned with Material Design spec, we do not currently accept FR's that are not in the spec (https://material.io/components/lists).

**Comment by Pupix** [comment]
Hey @joyzhong I am looking for the same thing and the feature is indeed in the spec over at https://material.io/components/selection-controls#usage
![image](https://user-images.githubusercontent.com/4929965/97715954-498f3900-1ac3-11eb-9d7a-c80d073f2f42.png)
