### ISSUE TITLE
[MDCSlider] Slider v6.0.0 does not slide on Mobile Devices 

### ISSUE THREAD

**Issue by jbjet777** [material-components/material-components-web#5894]
## Bug report
MDC-Slider sliders do not slide via touch on mobile Chrome.

### Steps to reproduce
1. Go to https://mwc-demos.glitch.me/demos/slider.html on mobile Chrome (responsive / emulation of mobile device in Developer Options or actual Chrome on Android (using Pixel 2XL, latest Android, current Chrome v81.0.4044.138)

2. Try to slide, via touch, both non-disabled sliders.  Sliding does not work, point and click action does.  

3.  Use of Mobile Safari works as expect Safari in iOS 13.4.1

4. Previous version of Material Components Web (v5.1.0 and down) work as expected.  See [https://material-components.github.io/material-components-web-catalog/#/component/slider](https://material-components.github.io/material-components-web-catalog/#/component/slider)
(As of bug filing date May 05, 2020)

### Expected behavior

Non-disabled sliders should smoothly slide, via touch action.

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | v6.0.0
| Browser          | Chrome v81.0.4044.138
| Operating System | Android and LinuxMint Desktop Mobile Device emulation in Chrome Developer Tools

### Screenshots
![image](https://user-images.githubusercontent.com/9014556/81319004-e789d580-9043-11ea-941c-627e4e6543d7.png)
Older Material Design Components registers event listeners of 'mousedown', 'touchstart', and 'pointerdown' on 'mdc-slider__thumb-container'.

![image](https://user-images.githubusercontent.com/9014556/81319412-7a2a7480-9044-11ea-92ec-a6f49f56a691.png)
New Material Design Components registers event Listeners of only 'pointerdown' on 'mdc-slider__thumb-container'. 

### Possible solution
Material Design Components should register Event Listeners of 'mousedown', 'touchstart', and 'pointerdown' on 'mdc-slider__thumb-container' for greater browser compatibility, without repetitively firing MDCSlider Events.

**Comment by joyzhong** [comment]
Looks like this regressed in https://github.com/material-components/material-components-web/pull/5845/files. Not sure why `pointerdown` event would not fire on thumb container though.

**Comment by jbjet777** [comment]
I agree, that was my thought to on the issue.  I'm wondering if this is a Chromium bug?  Should pointerdown event fire on screen touch? Is this issue is even standardized among the browsers?
