### ISSUE TITLE
why have no router?

### ISSUE THREAD

**Issue by anlexN** [material-components/material-components-web#5903]

**Comment by allan-chen** [comment]
Hi Anlex,
Thanks for reaching out. This codebase consists of building block UI components intended for wrapping in a larger web framework, where those frameworks may provide routing functionality. As such, MDC web does not plan to support routing.

**Comment by anlexN** [comment]
@allan-chen , can you give me examples that demonstate how to make a router?

**Comment by allan-chen** [comment]
If you decide to use [Angular](https://angular.io/guide/setup-local), for instance, you can use their router implementation at https://angular.io/guide/router.

**Comment by allan-chen** [comment]
Also, feel free to hop onto https://www.polymer-project.org/slack-invite Slack channel and ask the community for their recommendations!
