### ISSUE TITLE
material component is written by typescript, but why also use babel?

### ISSUE THREAD

**Issue by anlexN** [material-components/material-components-web#5904]

**Comment by allan-chen** [comment]
We currently use Babel to transpile [from ES2015 to standard Javascript](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#step-3-webpack-with-es2015). However, we will be investigating using TS compiler all the way, as well as investigating generating sourcemaps. Combining this issue with #5638

**Comment by anlexN** [comment]
you are wasting much time in babel, so silly.
