### ISSUE TITLE
Question about preparing a sheet: side

### ISSUE THREAD

**Issue by danialBakhtiary513** [material-components/material-components-web#5906]
Hello don't be bored I wanted to use a filter tool. It is still under construction. Will it be built?

link:
https://material.io/components/sheets-side

**Comment by asyncLiz** [comment]
Yes it will. Side sheets are still a beta design component. They will be planned and implemented when they have been finalized. You can follow https://github.com/material-components/material-components-web/issues/2665 for progress.
