### ISSUE TITLE
[mdc-icon-button] Firefox shows dotted outline when clicking icon button

### ISSUE THREAD

**Issue by austinw-fineart** [material-components/material-components-web#5908]
## Bug report
On Firefox, clicking on an icon button that uses the `<button>` tag causes a dotted outline to appear around the icon.

### Steps to reproduce
1. Go to https://material-components.github.io/material-components-web-catalog/#/component/icon-button
2. Click on any icon button (including drawer)

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |6.0.0
| Browser          |Firefox 76.0.1
| Operating System |Windows 10

### Possible solution
`mdc-button` handles this by styling `::-moz-focus-inner`

**Comment by allan-chen** [comment]
Using Firefox 76.0 on Win7, I can reproduce this only when the button has been tabbed into first. Simply clicking on it after first render does not cause the border to appear. However, after it has been tabbed into, any subsequent clicks trigger an outline.

**Comment by allan-chen** [comment]
Closing and using #5940 as tracking issue

**Comment by asyncLiz** [comment]
Woops, sorry didn't notice the duplicate 😔
