### ISSUE TITLE
Update status of components in "Component equivalence" section in docs

### ISSUE THREAD

**Issue by mdecaffmeyer** [material-components/material-components-web#591]
It seems that the following table needs an update, if I'm not wrong:
https://github.com/material-components/material-components-web/blob/master/docs/migrating-from-mdl.md#component-equivalence

E.g. it says the dialog is TBI, however I see a version of dialog here (?) :
https://github.com/material-components/material-components-web/tree/master/packages/mdc-dialog

**Comment by amsheehan** [comment]
You are correct. I've assigned this to myself and will take care of it. Thanks for noticing!

If you _do_ have the cycles and would like to  make a PR addressing this, we'd of course be happy to review it.

Thanks!

**Comment by mdecaffmeyer** [comment]
I barely know the library, so I'd prefer to let you handle this. Thank you for your work:-)
