### ISSUE TITLE
[MDC Select] The select component appears broken.

### ISSUE THREAD

**Issue by LucianVoju** [material-components/material-components-web#5916]
## Bug report
Display a simple outlined component following steps from here https://github.com/material-components/material-components-web/tree/master/packages/mdc-select
Select appears not to function: selection is not displayed, icon a appears multiple times.
### Steps to reproduce
Here is my repo.
https://github.com/LucianVoju/mdc.git

### Screenshots
<img width="229" alt="image" src="https://user-images.githubusercontent.com/23416504/81846566-f6e4b380-955a-11ea-867a-3c05e8a3bb4c.png">

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 6.0.0
| Browser          | Firefox 76
| Operating System | Mac Os Catalina

Thank you,

**Comment by asyncLiz** [comment]
Can you try following the HTML structure from https://github.com/material-components/material-components-web/tree/v6.0.0/packages/mdc-select?

You're using the HTML structure for v7 canary.

**Comment by LucianVoju** [comment]
It's ok. Thank you for the quick response.

**Comment by asyncLiz** [comment]
No problem, let us know if you have any more problems!
