### ISSUE TITLE
[Checkboxes] Cycling three-state checkboxes

### ISSUE THREAD

**Issue by hartwork** [material-components/material-components-web#5917]
Hi!  Thanks for sharing material-components-web as software libre, it's a great gift to the community!

While material-components-web does have [intermediate checkboxes](https://material-components.github.io/material-components-web-catalog/#/component/checkbox), I would need a version cycling through all three states — checked, indeterminate, unchecked, checked, indeterminate, .. — with each click and also send `indeterminate` (or a custom value) rather than `on` when the surrounding form is submitted [to support "maybe" for an answer](https://github.com/hartwork/jawanndenn/issues/26) in my mini-Doodle [jawanndenn](https://jawanndenn.de/).  I'd be willing to switch jawanndenn from [Materialize](https://materializecss.com/) to material-components-web just for that feature.  I have implemented a [cycling tristate checkbox as a Vue.js component](https://github.com/hartwork/vue-tristate-checkbox) recently that supports form submission so I know it can be done, in general.

Is this something you envision inside our outside of core material-components-web?

Thanks and best

Sebastian

**Comment by allan-chen** [comment]
Hi Sebastian,

Thank you for your question! The three-state-cycling checkbox doesn't appear to be part of the [spec](https://material.io/components/selection-controls#checkboxes). As such, we will likely not be able to support it as part of the core library. In this case we recommend that you implement a custom one that contains these state transitions, as you have done above. Let me know if you have any further questions!
