### ISSUE TITLE
How to import scss؟

### ISSUE THREAD

**Issue by danialBakhtiary513** [material-components/material-components-web#5919]
Hi, I don't know how to import `scss`. I want to customize the button style using the `filled-accessible` feature, but it gives an error.

That's how I imported
`@use "material-components-web/material-components-web";`

I am from Iran, my English is not good, I hope you have understood, thank you❤

**Comment by allan-chen** [comment]
Hi,

Thank you for your question! [Here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button#styles)'s some getting started guide for importing the button SASS. In general, you would have something like:

```scss
@use "@material/button";

@include button.filled-accessible($your-container-fill-color-here);

```

Let me know if you have any further questions!

**Comment by danialBakhtiary513** [comment]
> Hi,
> 
> Thank you for your question! [Here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button#styles)'s some getting started guide for importing the button SASS. In general, you would have something like:
> 
> ```css-scss
> @use "@material/button";
> 
> .my-foo-button {
>   @include button.filled-accessible($your-container-fill-color-here);
> }
> ```
> 
> Let me know if you have any further questions!

It does not work in some components
link: https://github.com/material-components/material-components-web/tree/master/packages/mdc-tab-bar
I feel like you are working on it

**Comment by allan-chen** [comment]
What is the error that you get?
It should work the same way:
```scss
@use "@material/tab-bar";
.my-tab-bar {
  @include tab-bar.density(-2);
}
```

**Comment by danialBakhtiary513** [comment]
> What is the error that you get?
> It should work the same way:
> 
> ```css-scss
> @use "@material/tab-bar";
> .my-tab-bar {
>   @include tab-bar.density(-2);
> }
> ```

![Untitled](https://user-images.githubusercontent.com/65126900/81960406-290f1780-9626-11ea-9b4c-f679a7f9c369.png)

**Comment by allan-chen** [comment]
Is "@material/tab-bar" in your `package.json` deps and included in node_modules?

**Comment by danialBakhtiary513** [comment]
Yes, I downloaded the latest version

link: https://www.npmjs.com/package/material-components-web

image:
![Untitled](https://user-images.githubusercontent.com/65126900/81961771-14338380-9628-11ea-8502-2cc0a31374f0.png)

**Comment by allan-chen** [comment]
That's odd - all the necessary files seem to be there. But the other components like button work?

**Comment by danialBakhtiary513** [comment]
> That's odd - all the necessary files seem to be there. But the other components like button work?

Yes, that's right, some components, such as themes and buttons, work well, but some do.

**Comment by danialBakhtiary513** [comment]
Even this error occurs `@use "material-components-web";`
But that's how it works `@use "material-components-web/material-components-web";`

**Comment by allan-chen** [comment]
Can you share your folder structure?

**Comment by danialBakhtiary513** [comment]
> آیا می توانید ساختار پوشه خود را به اشتراک بگذارید؟



[app.zip](https://github.com/material-components/material-components-web/files/4631509/app.zip)

**Comment by danialBakhtiary513** [comment]
I sent you the source for your convenience. I didn't write much code. You can see the errors related to it

**Comment by allan-chen** [comment]
Sorry, just a screenshot is fine, thanks!

**Comment by danialBakhtiary513** [comment]
> Sorry, just a screenshot is fine, thanks!

Do you mean this

![Untitled](https://user-images.githubusercontent.com/65126900/81997301-95a90700-9664-11ea-94c7-5803a0dd25d1.png)

**Comment by allan-chen** [comment]
Can you include dependencies for the components you need in this format, then run `npm install`?

```
  "dependencies": {
    "@material/animation": "^6.0.0",
    "@material/base": "^6.0.0",
    "@material/density": "^6.0.0",
    "@material/feature-targeting": "^6.0.0",
    "@material/tab": "^6.0.0",
    "@material/tab-scroller": "^6.0.0",
  },
```

**Comment by danialBakhtiary513** [comment]
yes

**Comment by danialBakhtiary513** [comment]
Sorry for the delay, I did the same thing you said, it gives the same error, I don't know, is it my problem or yours?

**Comment by allan-chen** [comment]
One more attempt: what about `@use "@material/tab-bar/mixins";`?

**Comment by danialBakhtiary513** [comment]
> One more attempt: what about `@use "@material/tab-bar/mixins";`?
> 
> Edit: Followed by `@include mixins.density(-1);`

Hi, this is good

**Comment by allan-chen** [comment]
Great! This may be another SASS loader bug. Wonder if it's loosely related to https://github.com/webpack-contrib/sass-loader/issues/804.

**Comment by danialBakhtiary513** [comment]
> Great! This may be another SASS loader bug. Wonder if it's loosely related to [webpack-contrib/sass-loader#804](https://github.com/webpack-contrib/sass-loader/issues/804).

Will this bug be fixed in the near future or will it remain the same?
