### ISSUE TITLE
Outlined Select Ripple overflow

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#5923]
## Bug report
Ripple for an Outlined Select extends beyond the outline.

![image](https://user-images.githubusercontent.com/11708435/82095148-5d520900-96f6-11ea-97a3-4ef41028b75b.png)

### Steps to reproduce
1. Paste this code into a web page: https://github.com/material-components/material-components-web/tree/v6.0.0/packages/mdc-select#outlined-select
2. place `<link href="https://unpkg.com/material-components-web@6.0.0/dist/material-components-web.css" rel="stylesheet">` into the `<head>` section of that page
3. hover your mouse over the select
4. the same thing happens whether or not you initialize the select's javascript
5. the file attached at the end of this post has full HTML markup to reproduce this issue.

### Actual behavior
See the picture above

### Expected behavior
The ripple should be constrained within the border

### Screenshots
As above

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 6.0.0 |
| Browser          | Chrome and Edge Chromium |
| Operating System | Windows 10 |

### Additional context
The only potential point of relevance is that the CSS comes from the CDN.

### Possible solution
I don't know what the solution is.

[MT600-oulined-select.txt](https://github.com/material-components/material-components-web/files/4637143/MT600-oulined-select.txt)

**Comment by simonziegler** [comment]
Hey Liz, amazingly quick response. That does fix the issue. So should the docs just be amended to remove the ripple span? I tried hacking css and setting overflow to hidden for the anchor which fixed the overflow issue, but by the looks of things you don't want the ripple anyway. I'll remove the line from my web app per your suggestion.

Thanks, Simon

**Comment by asyncLiz** [comment]
Yup, I'm 99% sure the docs just need to be fixed. Similar to textfield, the ripple should only be present in filled variants, not outlined.

**Comment by simonziegler** [comment]
Thanks for the heads up wtih text fields - I'll fix them too. By the way I don't seem to be getting ripple to work on filled text areas. Am I wrong to be using filled text areas, because I think I only see the outlined variety in the docs?

Tx

**Comment by asyncLiz** [comment]
Right now only outlined text areas are supported. Filled text areas are coming in #5851.

**Comment by simonziegler** [comment]
Great to know. I'll make a note in my project to loop back when the filled text areas are done. Thanks for responding so quickly!

**Comment by simonziegler** [comment]
Hi, how long until this propagates to the Reeadme and material.io? And many thanks for the super quick handling of this issue.

**Comment by asyncLiz** [comment]
Unfortunately it won't be until the next release that material.io gets updated.
