### ISSUE TITLE
[mdc-textfield] Weird behaviuor

### ISSUE THREAD

**Issue by m-alzam** [material-components/material-components-web#5927]
## Bug report

Outlined text field have a weird behaviour since the update to version 6.0.0

### Steps to reproduce
In a [separate demo](https://codepen.io/alcarazzam/pen/RwWeOQK) it works fine, but not using npm modules. Here's my code, the same from the docs:

```html
<label class="mdc-text-field mdc-text-field--outlined" id="new-link">
  <input type="text" class="mdc-text-field__input" aria-labelledby="new-link__label">
  <span class="mdc-notched-outline">
    <span class="mdc-notched-outline__leading"></span>
    <span class="mdc-notched-outline__notch">
      <span class="mdc-floating-label" id="new-link__label">Link</span>
    </span>
    <span class="mdc-notched-outline__trailing"></span>
  </span>
</label>
```
```javascript
import {MDCTextField} from '@material/textfield';
const add_link_input = new MDCTextField(document.getElementById("new-link"));
```
```scss
@use "@material/textfield";
@include textfield.core-styles;
```

### Actual behavior
(The purple line at the top is part of the top app bar)
![error](https://user-images.githubusercontent.com/47950933/82152344-ce153480-9860-11ea-829a-2f9dfefb07a2.gif)

### Expected behavior

Normal behaviour.

### My Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 6.0.0
| Browser          | Chromium 81.0.4044.138
| Operating System | Arch Linux

**Comment by asyncLiz** [comment]
Thanks for the issue! I think there may be an issue with our style documentation. Can you try removing 
```scss
@include textfield.core-styles;
```
and add this to your imports?
```scss
@use "@material/textfield/mdc-text-field";
```
I don't believe the single core-styles mixin is including everything you actually need for textfield. The old `mdc-*` import path should do the trick.

**Comment by m-alzam** [comment]
> Thanks for the issue! I think there may be an issue with our style documentation. Can you try removing 
> ```scss
> @include textfield.core-styles;
> ```
> and add this to your imports?
> ```scss
> @use "@material/textfield/mdc-text-field";
> ```
> I don't believe the single core-styles mixin is including everything you actually need for textfield. The old `mdc-*` import path should do the trick.

Thanks, it works now. The docs should be updated or the core-styles part.

**Comment by Nileshdcool** [comment]
If I am using CDN then, this doesn't work for me. CDN doesn't have updated code. The problem is also with floating labels when I use CDN. 

Can you give me a solution for this

**Comment by asyncLiz** [comment]
@Nileshdcool if you're using a CDN, you would need to change the version to point to `@canary`. The fix has not been published yet.

Instead, I would recommend following the workaround I mentioned in https://github.com/material-components/material-components-web/issues/5927#issuecomment-630321434 and use the `@material/textfield/mdc-text-field` import instead of the core-styles mixin.
