### ISSUE TITLE
Provide mechanism to reset JS-enhanced toolbar to allow change of toolbar style

### ISSUE THREAD

**Issue by pdf** [material-components/material-components-web#593]
Currently, once a toolbar has been enhanced using JS, it and other elements affected by it are stuck in whatever style it's initialized with, based on the specified classes at the time the JavaScript attaches to the element.

It would be beneficial to be able to reset the styling (and any style properties set on external elements, like `fixedAdjustElement`) to allow switching dynamically between toolbar styles, without completely removing the element from the DOM (which can be challenging in some frameworks, and results in jank).

A minimal approach might be to remove modified style properties on `destroy`, returning elements to their original state, which would allow a subsequent upgrade after CSS class changes.  Alternatively, a `reset` method might clear styles, then re-initialize.

A more involved implementation might additionally hook the `addClass`/`removeClass` methods to recompute the desired display style, and add/update/remove the style properties and eventListeners dynamically.

**Comment by amsheehan** [comment]
We agree. We've added this to tracker and will groom it in one of our upcoming sprint planning meetings.

Thanks for filing the issue!

**Comment by pdf** [comment]
Is this fixed @lynnjepsen? If so, it's not obvious to me how, could you provide some details?
