### ISSUE TITLE
Material Icons library + google font not showing in one WordPress website 

### ISSUE THREAD

**Issue by Marc557799** [material-components/material-components-web#5941]
I use material Icons in most of my websites on WordPress, most of time using Google Fonts link API. 

For one of my websites that is currently in production, the icons do not display ONLY when using Google Search bar. If I open the website on Chrome, the icons are showing normally.. 

1. On a smartphone, write ''millepatte.com'' in Google Search bar, access https://millepatte.com website from search results : icons do not show up

2. Repeat the process by opening Chrome browser on your smartphone, write millepatte.com in search bar to acess the website : icons show up

On the same website : I used Lobster Google font that seems to do the same : not showing up only from Google Search bar results but actually working fine on other browsing devices. I used also Adobe fonts for this project using the same <link> method and the problem only appears for Google fonts API (and only in that weird browser "made by Chrome" that pops up when using Google Search App for Android) . 

Problem does not appear in desktop browser 
Problem does not repeat on other websites using the same integration method. 

My ''environment'' : 
WordPress.org
Theme : DIVI complete licence with child theme
Link rel=stylesheet method to integrate the fonts
PHP 7.2
MYSQL 5.3

I used both feature from DIVI theme to integrate code in header, or function.php file from Child Theme. None of them works. 

I disabled all cache plugins from website and emptied the cache, the problem remains the same.

I also tried @import method with hosting material Icons font and the lobster google font and that does not work neither... 

Anybody has a valid solution that would avoid me to reintegrate all icons using pngs?? 🤔

Thanks!

**Comment by asyncLiz** [comment]
Thanks for the issue!

I tried reproducing as you described, but on my smartphone I was able to access your website and view the Material icons normally both in Chrome and via the Google Search Bar.

Unfortunately though, this sounds like it might be a bug with either Android, Chrome, or (least likely) the Fonts api. I'd suggest first filing some bug reports on the Android team to investigate, since that's the most likely suspect!
