### ISSUE TITLE
Unstyled icons in toolbar

### ISSUE THREAD

**Issue by joshas** [material-components/material-components-web#598]
If I take HTML code from example https://material-components-web.appspot.com/drawer/temporary-drawer.html I need additional style to remove default button styles and set button size. Shouldn't menu button styling be defined in material-components-web CSS?

**Comment by Garbee** [comment]
Do you mean buttons as list items within the drawer? If so see #505.

Otherwise, could you be more specific about what you're expecting? I'm not quite sure what it is you're asking about exactly.

**Comment by joshas** [comment]
I had issue with "hamburger" menu icon, but now implemented it from toolbar example, where it has other issues.

**Comment by donmccurdy** [comment]
Was this resolved? I'm copying one of the toolbar examples from the documentation:

```html
<header class="mdc-toolbar">
  <div class="mdc-toolbar__row">
    <section class="mdc-toolbar__section mdc-toolbar__section--align-start">
      <a href="#" class="material-icons">menu</a>
      <span class="mdc-toolbar__title">Title</span>
    </section>
  </div>
</header>
```

And getting this:

<img width="916" alt="screen shot 2017-05-22 at 4 26 09 pm" src="https://cloud.githubusercontent.com/assets/1848368/26332424/795f5cce-3f0b-11e7-9be2-91ec1e57c6b1.png">

I assume I need to do something to get icons working, but can't find what that is.

**Comment by joshas** [comment]
@donmccurdy To get icons working, you need to load Material Icons stylesheet
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

But you'll get unstyled icons. To fix it demo uses a bit of custom css:
```css
.material-icons {
    text-decoration: none;
    cursor: pointer;
    padding-right: 8px;
    color: white;
}
```
For use in production you'll probably want to make icon styles specific to toolbar only and maybe set `color: inherit` so icons would get correct color when changing theme.

I'd expect that icon colors should be handled by framework.

**Comment by donmccurdy** [comment]
Thanks @joshas — your snippet works nicely in my case. 

I was expecting icon colors to match the theme automatically; if that's out of scope for some reason, a section in the docs discussing how to get icons working and properly colored would be great. Glad to send a PR for that.

**Comment by yeelan0319** [comment]
We agree with having this feature out of box is totally a valid ask. To address this problem, we would like to breakdown it into 2 sub-problems:

1. Correct wrong positioning for icon in toolbar. This is already captured by #607 file by @joshas 
2. Set default color for material-icon in toolbar. 

    - [ ] Add class `mdc-toolbar__icon` to prevent accidentally overwrite other icon styles
    - [ ] Add `@include mdc-theme-prop(background-color, primary);` to use mdc theme background color instead of hard coding it.
    - [ ] Add `@include mdc-theme-prop(color, text-primary-on-primary);` to use mdc theme text color instead of hard coding it.
    - [ ] Overwrite `text-decoration`, `border`,  `cursor` of the browser default

We would really like someone could help us with it and we will facilitate the PR 😄 

Moreover, since @donmccurdy mentioned, we would also like to add document into `mdc-toolbar` about how to properly include material-icons. That could also be another PR.

**Comment by danielbolan** [comment]
Unless there's something else I'm not noticing, it seems as though this can be closed now, since @amsheehan's #764 also took care of pretty much all of those action items.

**Comment by touficbatache** [comment]
This issue should be closed as it has been resolved by #764 @amsheehan @traviskaufman

**Comment by amsheehan** [comment]
Correct. Thanks for bringing this to our attention!

**Comment by touficbatache** [comment]
No problem :smile:
