### ISSUE TITLE
[MDCDrawer] Can't close when more than one drawer exists

### ISSUE THREAD

**Issue by Zenoo** [material-components/material-components-web#5981]
## Bug report
Modal drawers can't be closed if they are not the first modal drawer on the page.

### Steps to reproduce
1. Go to https://codepen.io/zenoo-the-animator/pen/RwWOrJO
2. Click on `Open drawer 1`, it works fine
3. Click on `Open drawer 2`, you can't close it anymore

### Actual behavior
The second modal drawer can't be closed

### Expected behavior
You should be able to close the second modal drawer.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.0.0
| Browser          | Chrome 83.0.4103.6
| Operating System | Windows 10

**Comment by sigmapi** [comment]
Actually the problem is that you have two `mdc-drawer-scrim` divs inside the body tag.
They work fine if you just enclose each drawer and its scrim sibling inside a div.
```
<div>
  <drawer1 ...>
  <scrim1 ...>
</div>
<div>
  <drawer2 ...>
  <scrim2 ...>
</div>
```

**Comment by EstebanG23** [comment]
Hi there, thank you for filing this issue. 

The MDC Drawer currently does not support more than one drawer. We are looking into supporting more than one drawer, however a potential work around could be to change the content based on what you would like to show, but to use the same drawer.

**Comment by Zenoo** [comment]
I worked around this by listening to the user's click on the second scrim and closing the second Drawer.

```js
window.addEventListener('load', () => {
  const drawerElement = ...;
  const drawer = ...;

  drawerElement.nextElementSibling.addEventListener('click', () => {
    drawer.open = false;
  });
});
```

**Comment by Zenoo** [comment]
Also, @sigmapi the documentation shows otherwise:

![](https://i.imgur.com/qoy3rBm.png)
