### ISSUE TITLE
Misaligned arrow_upwards FAB icon

### ISSUE THREAD

**Issue by salamanders** [material-components/material-components-web#599]
The up arrow FAB is misaligned within the circle.
https://jsfiddle.net/salamanders/40vr2x5k/
The others (arrow_back, arrow_downward etc) all look fine.

**Comment by anton-kachurin** [comment]
If there are two `arrow_upward`s on the page, the latter looks fine:
https://jsfiddle.net/27zu5284/

If there are three, all of them look fine:
https://jsfiddle.net/curqhxga/

**Comment by traviskaufman** [comment]
@anton-kachurin has the fix; use `arrow_upward` instead. Thanks!
