### ISSUE TITLE
Difficulty downloading the package

### ISSUE THREAD

**Issue by danialBakhtiary513** [material-components/material-components-web#6017]
What's the problem, I can't load the package

**Comment by danialBakhtiary513** [comment]
![2020-06-02 (5)](https://user-images.githubusercontent.com/65126900/83545589-adadd100-a514-11ea-870a-79447900c4ea.png)

**Comment by asyncLiz** [comment]
Looks like a local cache problem. Try running `npm cache verify` and then installing again. If that doesn't work, try `npm cache clean --force`.

**Comment by danialBakhtiary513** [comment]
> Looks like a local cache problem. Try running `npm cache verify` and then installing again. If that doesn't work, try `npm cache clean --force`.

Thanks❤

**Comment by asyncLiz** [comment]
No problem, closing since the problem seems to be resolved.
