### ISSUE TITLE
Is there plan to use root em unit instead of pixel unit?

### ISSUE THREAD

**Issue by TroyTae** [material-components/material-components-web#6029]
Hello thank you for your maintaining.
Now I making a responsive web.
So I use rem for making layout frame.
But it seems mdc use `px`.
Do you have some plan to use `rem` instead of `px`?
Or is there guide for making responsive web??
Thanks :)

**Comment by asyncLiz** [comment]
Yes, this has been in our backlog for a while with some design guidance needed. The main issue is https://github.com/material-components/material-components-web/issues/2731. I'd recommend subscribing to that issue for any updates.

Closing for now as a duplicate.
