### ISSUE TITLE
[MDCSelect] Wrong position of opened Select inside Dialog component with option fixed + anchorCorner

### ISSUE THREAD

**Issue by BePo65** [material-components/material-components-web#6034]
## Bug report
When using a MDCSelect with anchorCorner='bottomStart' and fixed=true inside of a MDCDialog, then the selection list (MDCMenu) is positioned too far to the right.
![MDCSelect_in_MDCDialog](https://user-images.githubusercontent.com/6582465/83871686-c8f52800-a730-11ea-921f-78c62b85a8a9.jpg)

**Reason why**:  MDCMenu has 'position:fixed' (in .mdc-menu-surface--fixed) and mdc-dialog-container has 'transform:scale(1)' (in .mdc-dialog--open .mdc-dialog__container). Therefore mdc-dialog-container creates a stacking context and will act as a containing block for the MDCMenu (instead of the browser window).

### Steps to reproduce
1. Create dialog with MDCSelect inside
2. Open dialog
3. Click icon of select to open selection list
4. list is positioned too far to the right

### Actual behavior
Left position of menu is calculated based on browser viewport (in MDCMenuSurfaceFoundation.prototype.adjustPositionForHoistedElement_).

### Expected behavior
Left position of menu should be calculated based on stacking context.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.1.0
| Browser          | FF 77.0 and Chrome 83.0
| Operating System | Windows 10 1909

### Additional context
In issue #5590 a hack is proposed (set 'transform:none' in MDCMenu style (but this is only a hack with sideeffects unknown to me).

In issue #2399 the 'solution' was  a rework for MDCSelect.

**Comment by allan-chen** [comment]
Thanks for filing the bug, could you check if `.mdc-dialog__content` has `transform: scale(1)` set?

If so, that should be fixed by #6012

**Comment by allan-chen** [comment]
This should be fixed by #6012
