### ISSUE TITLE
Generated JS is becoming too big

### ISSUE THREAD

**Issue by m-alzam** [material-components/material-components-web#6057]
Hi,

I've saw an increase in the JavaScript bundle recently. For example, using the following dependencies generates a **275 KiB** file.

```javascript
import {MDCTopAppBar} from '@material/top-app-bar';
import {MDCDrawer} from "@material/drawer";
import {MDCMenu} from "@material/menu";
import {MDCRipple} from "@material/ripple";
import {MDCTabBar} from '@material/tab-bar';
import {MDCSnackbar} from '@material/snackbar';
import {MDCTextField} from '@material/textfield';
import {MDCDialog} from '@material/dialog';
import {MDCList} from '@material/list';

import Cookies from "js-cookie"; // Not relevant, less than 30 KiB unpacked
```

Webpack warns about web performance, recommending to not exceed 244 KiB. How can we improve the situation?

Regards

**Comment by abhiomkar** [comment]
I did not notice any steep increase in bundle size. As per [bundlephobia](https://bundlephobia.com/result?p=@material/menu@6.0.0) results, bundle size is almost same as previous releases. Can you confirm which package impacts the total bundle size?

**Comment by abhiomkar** [comment]
Closing since inactive. Please re-open if you're able to reproduce the issue.

**Comment by m-alzam** [comment]
After some refactoring, maybe the cause of big bundles is that I was using different versions of each package.
