### ISSUE TITLE
Release MDC Segmented Button

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#6069]
Tracking bug to implement and release MDC Segmented Button (AKA Toggle Group Button).

- [x] Draft Design Doc
- [x] Get Design Doc reviewed
- [x] Build initial prototype
- [x] Create bare structure of Segmented button component
  - Create folder (`packages/mdc-segmented-button`)
  - Add bare minimum files including package.json, Sass files (bare minimum)
  - Add README file with bare minimum document structure
- [x] Add base styles and theme mixins
- [x] Add adapter interface & foundation (Add unit tests)
- [x] Implement MDC vanilla component - `component.ts` (Add unit tests)
- [x] Update README documentation in each above step.
- [x] Fully test (Manual) for accessibility.
  - Perform accessibility audit using chrome dev tool.
  - Manually test using screen readers (Minimum 2 screen readers)
- [x] Set appropriate visibility setting in NPM registry for `@material/segmented-button` package.
- [ ] UX review (Material Design)
- [ ] Remove package from [dependency test](https://github.com/material-components/material-components-web/blob/master/scripts/check-pkg-for-release.js) exemptions

**Comment by gschrag** [comment]
Pull Requests related to this Issue:

[PR#6073](https://github.com/material-components/material-components-web/pull/6073): Add new package for segmented button
[PR#6141](https://github.com/material-components/material-components-web/pull/6141): Add initial SASS styles
[PR#6165](https://github.com/material-components/material-components-web/pull/6165): Add Adapters and Foundations
[PR#6198](https://github.com/material-components/material-components-web/pull/6198): Add foundation business logic
[PR#6222](https://github.com/material-components/material-components-web/pull/6222): Add component outlines
[PR#6223](https://github.com/material-components/material-components-web/pull/6223): Implement components

**Comment by gschrag** [comment]
I believe there are still some themeability that needs to be added to the component before it's finished, such as density and being disabled, as well as some functionality like if there should be a default selection in the case of `single-select`. But could you provide the specific things that need to be completed for the component to be included in the `material-component-web` npm package?

**Comment by abhiomkar** [comment]
Hi Gabriel -- Do you have a link to the updated demo of this component?

**Comment by abhiomkar** [comment]
Sent you the checklist for accessibility self-assessment. You'll have to manually test using at-least 2 screen readers.

**Comment by gschrag** [comment]
The updated demo is live at: [http://mdc-segmented-button.surge.sh/](http://mdc-segmented-button.surge.sh/)

**Comment by abhiomkar** [comment]
Looking great! Can you update the demo to include following usages?

* Single select with only icons
* Multi-select with only icons
* Single select containing icons + label in all segments.
* Multi-select containing icons + label in all segments.

(Remove baseline example).

I'll share this demo with design for feedback. Meanwhile please fill out the a11y self-assessment checklist.

Let me know if you've any questions!

**Comment by gschrag** [comment]
I've updated the demo.

**Comment by gschrag** [comment]
I've filled out the a11y checklist as much as I could, except for:

1.16 Magnification and screen reading works, but I haven't tested on Firefox or IE.
2.7 I don't know if the singleSelect unselecting a segment should be read out loud with a screen reader (or how to do it)
Secondary Use Cases: I don't know what to put here. The component works with tab, shift+tab, and enter, but not arrow keys
Platforms: I've only tested the component in Chrome on a Pixelbook

**Comment by aeromac** [comment]
Is there a difference between this at the [toggle buttons](https://material.io/components/buttons/web#toggle-button)? The buttons page says 'MDC Web currently does not support toggle button groups' but it looks like it, in fact, does - but by a different name?
