### ISSUE TITLE
Toolbar layout issues

### ISSUE THREAD

**Issue by joshas** [material-components/material-components-web#607]
In toolbar example code https://material-components-web.appspot.com/toolbar/index.html Action Bar icons are missing padding and title is too close to menu icon.
![mcw-toolbar](https://cloud.githubusercontent.com/assets/79141/25864501/50f89894-34f8-11e7-893d-0898a342caa6.PNG)
Compare to Material Design guidelines:
![layout_structure_appbar_metrics1](https://cloud.githubusercontent.com/assets/79141/25864524/69511948-34f8-11e7-9dd1-c619177429f5.png)
Is toolbar component still WIP or I'm just missing Action Bar button classes?

**Comment by amsheehan** [comment]
After reviewing the demo, we agree that margins and padding could be more uniform in the implementation. Thanks for filing this!

**Comment by traviskaufman** [comment]
Also will be addressing #736 since according to @amsheehan the demo page will have to be significantly changed for this work anyway.
