### ISSUE TITLE
Toolbar spacer on Persistent Drawer animates differently than Persistent Drawer

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#611]
### What MDC-Web Version are you using?

0.10.0

### What browser(s) is this bug affecting?

Chrome 57.0.2987.133 (64-bit)

### What OS are you using?

macOS 10.12.4

### What are the steps to reproduce the bug?

1. Open [demo site](http://material-components-web.appspot.com/drawer/persistent-drawer.html)

### What is the expected behavior?

When activating the drawer, all parts of the drawer should animate as one.

### What is the actual behavior?

When activating the drawer, the toolbar spacer animates much more quickly than the rest of the drawer.

**Comment by Touficbatache** [comment]
I think they want this effect with the animation. Not sure if it's a bug...

**Comment by amsheehan** [comment]
@Touficbatache After discussing with the team we have determined you are correct, and will close this issue. Thanks!

**Comment by Touficbatache** [comment]
No problem :)
