### ISSUE TITLE
[MDCMenu] hover style not working after 7.0.0

### ISSUE THREAD

**Issue by dkgof** [material-components/material-components-web#6135]
After upgrading to version 7.0.0 MDCMenu does not seem to trigger hover style correctly on its Items:

https://codepen.io/dkgof/pen/GRombBw

If both css and js is changed to 6.0.0 instead, it works as expected.

**Comment by abhiomkar** [comment]
MDCList (or MDCMenu) `v7.0.0` adds ripple styles to separate child element of list item. You'll need to add a child element with `mdc-list-item__ripple` class name inside every list item element for ripple styles to work.

Please follow [updated documentation](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/README.md#html-structure) for sample HTML structure.
