### ISSUE TITLE
[MDCDrawer] No modal variant styles

### ISSUE THREAD

**Issue by m-alzam** [material-components/material-components-web#6137]
## Bug report
When loading the styles for the drawer as said in the documentation (see below)
```scss
@use "@material/drawer";
@use "@material/list";

@include drawer.core-styles;
@include list.core-styles;
```

the styles for the modal variant are no present since I updated to version 7.0.0. If I use the following, everything is fine:
```scss
@use "@material/drawer/mdc-drawer";
@use "@material/list";

@include list.core-styles;
```

### Actual behavior
No `mdc-drawer--modal` class available.

### Expected behavior
`mdc-drawer--modal` class available.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |7.0.0
| Browser          |83.0.4103.116
| Operating System |Arch Linux

**Comment by joyzhong** [comment]
Thanks for reporting! This is a documentation bug. The correct styles should be:

```scss
@use "@material/drawer";
@use "@material/list";

@include drawer.core-styles;
@include drawer.dismissible-core-styles;
@include drawer.modal-core-styles;
@include list.core-styles;
```

Sending out a fix now.
