### ISSUE TITLE
Issue with label positions for text areas

### ISSUE THREAD

**Issue by counterbeing** [material-components/material-components-web#6140]
## Bug report
The labels on text areas are in the wrong position.

### Steps to reproduce
1. Visit https://codepen.io/corylogan/pen/GRoENzv
2. Click in the text area.

### Actual behavior
The label moves slightly, but not all the way up and does not resize.

### Expected behavior

The label should move up to the notch and resize to fit.

### Screenshots
![image](https://user-images.githubusercontent.com/239798/85631356-61e9d580-b643-11ea-8622-6acd568b158a.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| Browser          | Chrome
| Operating System | Mac OS 10.15

**Comment by asyncLiz** [comment]
Don't forget to review the changelog's [breaking changes](https://codepen.io/asyncliz/pen/bGERgGx) section for v7.0.0. For textarea there are two breaking changes in the latest update:

1. With the introduction of filled textareas, outlined textareas must specify the `mdc-text-field--outlined` modifier class.
2. The `mdc-text-field__resizer` wrapper element is needed for resizing.

See https://codepen.io/asyncliz/pen/bGERgGx for an updated version of your codepen with the correct v7 DOM structure.

**Comment by counterbeing** [comment]
Thanks so much @asyncLiz. This appears to work, however it sounds like the docs themselves need to be updated, as I copied and pasted that markup straight from the documents for the purposes of this demo. I assume that's in the pipeline after doing the release.

**Comment by asyncLiz** [comment]
That's correct. Looking at your codepen again, I see you're referring to material.io. Those docs are in the process of being updated with yesterday's new release. They're always a little slower to update since they have to be published. This repo's [textfield readme docs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#outlined) should already be up to date.
