### ISSUE TITLE
[MDCDialog]  The second dialog `data-mdc-dialog-initial-focus` doesn't work.

### ISSUE THREAD

**Issue by ota-meshi** [material-components/material-components-web#6142]
## Bug report

The second dialog, `data-mdc-dialog-initial-focus` doesn't work.

When the dialog is opened, the element to which `data-mdc-dialog-initial-focus` is added should be initially focused, but it does not work in the second and subsequent dialogs.

https://github.com/material-components/material-components-web/tree/master/packages/mdc-dialog#other-customizations

### Steps to reproduce
1. Go to https://codepen.io/ota-meshi/pen/eYJRWOK
2. Click on 'OPEN DIALOG2'
3. I have added `data-mdc-dialog-initial-focus` to the `<button>`, but focus on the `<input>`.

### Actual behavior

I have added `data-mdc-dialog-initial-focus` to the `<button>` in DIALOG2, but focus on the `<input>`.
DIALOG1 does not have this problem and works correctly.

### Expected behavior

When DIALOG2 is opened, the `<button>` with `data-mdc-dialog-initial-focus` on focus.

### Screenshots

The first dialog works.

![image](https://user-images.githubusercontent.com/16508807/85645853-d705eb00-b6d5-11ea-91c1-f2a3427c5d58.png)

But the second dialog doesn't work.

![image](https://user-images.githubusercontent.com/16508807/85645843-cc4b5600-b6d5-11ea-8f4e-458e03186485.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 6.0.0 |
| Browser          | Chrome |
| Operating System | Mac |

### Additional context

Only one `data-mdc-dialog-initial-focus` can be enabled in the document because it uses `document.querySelector`.

https://github.com/material-components/material-components-web/blob/035cf2a6f132f8f81279e1b071c0a31536ac2797/packages/mdc-dialog/component.ts#L199-L201

```
  private getInitialFocusEl_(): HTMLElement|null {
    return document.querySelector(`[${strings.INITIAL_FOCUS_ATTRIBUTE}]`);
  }
```

**Comment by joyzhong** [comment]
Thanks for filing an issue! We can fix this by changing to:

```
private getInitialFocusEl_(): HTMLElement|null {
  return this.root.querySelector(`[${strings.INITIAL_FOCUS_ATTRIBUTE}]`);
}
```

We should also add a test with the fix.

Adding to team backlog, but please feel free send out a PR.
