### ISSUE TITLE
Ficus drawer problem

### ISSUE THREAD

**Issue by danialBakhtiary513** [material-components/material-components-web#6143]
Hello
The country buttons have a problem, and also when the drawer is closed, the menu button is not fixed

![Untitled](https://user-images.githubusercontent.com/65126900/85652420-eaa65700-b6bf-11ea-9d9b-13da8976ae13.png)
![jkhk](https://user-images.githubusercontent.com/65126900/85652298-98653600-b6bf-11ea-92b2-e0a112f58f5a.png)

Link https://github.com/material-components/material-components-web/issues/6038
Version 7

**Comment by joyzhong** [comment]
Hi there, I'm not sure I fully understand the bug. Can you please add more details (expected vs. actual behavior) and also a demo link (Glitch, etc.)?

**Comment by danialBakhtiary513** [comment]
> Hi there, I'm not sure I fully understand the bug. Can you please add more details (expected vs. actual behavior) and also a demo link (Glitch, etc.)?

hello

link https://stackblitz.com/edit/react-4hjhxe

**Comment by joyzhong** [comment]
Your demo seems to be working fine for me - drawer opens and closes as expected. Can you specify the incorrect behavior?

**Comment by danialBakhtiary513** [comment]
> Your demo seems to be working fine for me - drawer opens and closes as expected. Can you specify the incorrect behavior?

Please open the drawer and select a button and close the drawer and open it again and see the problem.

**Comment by danialBakhtiary513** [comment]
![Untitled](https://user-images.githubusercontent.com/65126900/85877765-e62b8c80-b7ec-11ea-8853-027e015e19fc.png)

**Comment by joyzhong** [comment]
This looks like an underlying bug in MDC List. The tabindex is not reset to -1 when a focused list item is blurred. This causes the drawer to focus on the first item (since it still has tabindex=0) rather than the currently selected one.

I believe https://github.com/material-components/material-components-web/pull/6147 should fix this, adding @allan-chen to confirm.

**Comment by danialBakhtiary513** [comment]
> This looks like an underlying bug in MDC List. The tabindex is not reset to -1 when a focused list item is blurred. This causes the drawer to focus on the first item (since it still has tabindex=0) rather than the currently selected one.
> 
> I believe #6147 should fix this, adding @allan-chen to confirm.

In my opinion, you have made the path very difficult and complicated. Let us do some things. For example, this drawer should only close the arm operation. Open it for its items. I hope you understand what I mean. My words are just ideas

**Comment by allan-chen** [comment]
Confirming that #6147 should resolve this.
