### ISSUE TITLE
[MDCList] Sass Compilation error

### ISSUE THREAD

**Issue by elisco-latour** [material-components/material-components-web#6149]
### Steps to reproduce
1. Configure environment using webpack by following MDC Web "Getting started documentation"
2. `npm install @material/list --save-dev`
3. In my app.scss `@use "@material/list";` and `@include list.core-styles;`
4. Run `webpack --watch`

### Actual behavior
 ERROR in ./assets/src/app.scss
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: No arguments named $border-width or $border-style.
       ┌──> node_modules/@material/list/_mixins.scss
    93 │ ┌       @include dom-mixins.transparent-border(
    94 │ │         $border-width: 3px, $border-style: double, $query: $query);
       │ └──────────────────────────────────────────────────────────────────^ invocation
       ╵
       ┌──> node_modules/@material/dom/_mixins.scss
    30 │   @mixin transparent-border($query: feature-targeting-functions.all()) {
       │          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ declaration
       ╵
      node_modules/@material/list/_mixins.scss 93:7   transparent-border()
      node_modules/@material/list/_mixins.scss 93:7   without-ripple()
      node_modules/@material/list/_mixins.scss 44:3   core-styles()
      node_modules/@material/list/mdc-list.scss 22:1  @use
      /Users/tania/dev/projects/econf/assets/src/app.scss 29:1       root stylesheet
     @ multi ./assets/src/app.scss ./assets/src/app.js main[0]

### Expected behavior
No error at all

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | v7
| Browser          | Chrome Version 83.0.4103.106 (Build officiel) (64 bits)
| Operating System | OSX El Captain

**Comment by joyzhong** [comment]
Can you try disabling `webpackImporter` in `sass-loader` per https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020?

**Comment by allan-chen** [comment]
This should be resolved by upgrading `@material/dom` package to 7.0.0. Please feel free to reopen if there is still an issue after the upgrade.
