### ISSUE TITLE
Updating the Demos provided

### ISSUE THREAD

**Issue by jimmyhdolores** [material-components/material-components-web#6150]
In the component demo links they refer to https://material-components.github.io/material-components-web-catalog, the problem is that those demos are with an outdated version and therefore it does not help much since new things have been removed and added in the latest versions; I use version 6.0.0 and for example the demo of the Linear Progress Indicator component uses different style classes than the current one and also uses the effect of an ellipsis; well I hope they update the demos.

**Comment by abhiomkar** [comment]
[Catalog demo site](http://material-components.github.io/material-components-web-catalog) is outdated and may never be updated in future.

We're in the process of migrating catalog site to official website - material.io. Here are the things that you can try to get access to sample HTML structure.

* Use material.io site to see live demos hosted on individual component design pages. (E.g., [text field demo](https://material.io/components/text-fields) built using Material Components Web).
* Use component [README](https://github.com/material-components/material-components-web/tree/master/packages/mdc-linear-progress) documentation for sample HTML structure for each component variant.
* See up-to-date [live](https://material-components.github.io/material-components-web-components/demos/index.html) [demos](https://mwc-demos.glitch.me) implemented in [Web Components](https://github.com/material-components/material-components-web-components).

If you see any discrepancy with README docs please feel free to open a bug.
