### ISSUE TITLE
change color mdc-linear-progress__buffer-dots

### ISSUE THREAD

**Issue by jimyhdolores** [material-components/material-components-web#6156]
When trying to change the color using the buffer-color and passing a sass variable, the ellipsis do not change color
![image](https://user-images.githubusercontent.com/10909792/85910110-c8592a00-b7e2-11ea-9bb1-3cba8a7b8993.png)

![image](https://user-images.githubusercontent.com/10909792/85910122-d5761900-b7e2-11ea-9b04-9fc78dbe572c.png)

Version: 6.0.0

**Comment by allan-chen** [comment]
Hey Jimmy,

Thank you for the issue! This requires a change in implementation from background-image to inline SVG in the HTML in order to be able to css custom properties.
