### ISSUE TITLE
[MDCTheme] Theme.Property mixin not correctly using theme keys (primary, secondary, etc.)

### ISSUE THREAD

**Issue by AnthonySwierkosz** [material-components/material-components-web#6158]
## Bug report

When attempting to use the `theme.property` mixin with an MDC Theme key (primary, secondary, etc.) the build fails.
However `theme.prop` which is now deprecated works correctly.

### Steps to reproduce
1. Use `theme.property` mixin with MDC Theme key (primary, secondary, etc.)
Example: `@include theme.property(border-color, primary);`
2. See error

### Actual behavior

The build fails with output:
```Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
   ╷
94 │     $custom-prop: custom-properties.create(--mdc-theme-#{$style}, $fallback);
   │                                                          ^^^^^^
   ╵
  node_modules\@material\theme\_mixins.scss 94:58  property()
```

### Expected behavior

`theme.property` will correctly use MDC Theme keys with output:
```
border-color: #6200EE;
border-color: var(--mdc-theme-primary, #6200EE);
```
when using `@include theme.property(border-color, primary);`

### Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |7.0.0
| Browser          |Chrome 83
| Operating System |Windows 10 (2004)

**Comment by allan-chen** [comment]
Hi Anthony,

Thanks for filing the issue - it seems that `$style` may need to be `$value` instead - adding @asyncLiz to confirm.

**Comment by asyncLiz** [comment]
Confirmed!
