### ISSUE TITLE
[DataTable] Lack of guidance or documentation for Pagination

### ISSUE THREAD

**Issue by OmarHuang** [material-components/material-components-web#6159]
Despite https://material.io/components/data-tables/#Pagination indicating can display number of rows per page on a data table, there is apparently no guidance or documentation on pagination anywhere.

**Comment by allan-chen** [comment]
Hi Omar,

Thank you for reaching out! Pagination is actively being developed and we expect to see documentation shortly.

+ @abhiomkar

**Comment by abhiomkar** [comment]
Pagination docs are now updated in https://github.com/material-components/material-components-web/commit/30eef05837ee3c969f71c80846df22bb87eee121

Should be available in `@canary` release (`@material/data-table@canary`)
