### ISSUE TITLE
[MDCChipSet] Error for remove the last chip.

### ISSUE THREAD

**Issue by ota-meshi** [material-components/material-components-web#6160]
## Bug report

When I remove the last chip, I get an error in the console.

### Steps to reproduce
1. Go to https://codepen.io/ota-meshi/pen/zYrENev
2. Click on `X` to the right of "Please remove it".
3. See error on Chrome dev tool console.

### Actual behavior

The following error is displayed on the console.

```console
component.ts:123 Uncaught TypeError: Cannot read property 'focusTrailingAction' of undefined
    at Object.focusChipTrailingActionAtIndex (component.ts:123)
    at MDCChipSetFoundation.handleChipRemoval (foundation.ts:125)
    at HTMLDivElement.handleChipRemoval_ (component.ts:81)
    at MDCChip.MDCComponent.emit (component.ts:115)
    at Object.notifyRemoval (component.ts:257)
    at MDCChipFoundation.handleTransitionEnd (foundation.ts:217)
    at HTMLDivElement.handleTransitionEnd_ (component.ts:157)
```

### Expected behavior

I expect no error.

### Screenshots

![image](https://user-images.githubusercontent.com/16508807/85989767-f41b2080-ba2b-11ea-93a1-ca3c83be586f.png)

Click on `X` to the right of "Please remove it".

![image](https://user-images.githubusercontent.com/16508807/85989784-fc735b80-ba2b-11ea-8015-2d09642e9a7b.png)

Set a breakpoint.

![image](https://user-images.githubusercontent.com/16508807/85989990-4eb47c80-ba2c-11ea-9977-0c5ea02d3ce7.png)

![image](https://user-images.githubusercontent.com/16508807/85990032-5e33c580-ba2c-11ea-9188-21e56786122b.png)

`chips_` is empty.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| Browser          | Chrome  83.0.4103.106
| Operating System | Mac 10.13.6

**Comment by allan-chen** [comment]
Hi Ota,

Thanks for filing the issue! It seems some range checking is missing, so when the only item is removed the adapter method attempts to find a chip in an empty array.
