### ISSUE TITLE
Need to be able to set the value of an input or select without firing change event.

### ISSUE THREAD

**Issue by nmunday** [material-components/material-components-web#6166]
## Feature Request
I have a set of select elements that listen to the MDC:Change event. This page can also be updated when a change occurs on the server and is pushed to the client. I do not want the change event to fire when it is NOT the user who changed the value.

### Proposed solution
Allow some way to set the value property using JavaScript on an MDCSelect component that does not fire the change event.

### Alternatives considered
Remove the event handler before updating the value and add it back after.

### Additional context
I am using MDCSelect.value to set the value and MDCSelect.listen to add the event handler.

**Comment by allan-chen** [comment]
An update to this - the option to skip notifying via event is already available as a param in the foundation. It's just that at the component level getters & setters make this hard to thread to that layer.

We may add functions `setValue` or `setSelectedIndex` in `component.ts` which take actual params. It'll be slightly redundant with `set  value()` and such but it will grant more control.

**Comment by somboo** [comment]
Is there an update on the status of this?  It is pretty basic functionality to be able to programmatically load an existing value into a form field without firing a change event and then only fire an event to update the value when the user is the one changing the value.  I'm just wondering if this functionality is implemented now or if I will need to code my own workaround.  Thanks.
