### ISSUE TITLE
Lack of proper example about Multi select

### ISSUE THREAD

**Issue by robimalco** [material-components/material-components-web#6174]
Dear Team,

I am struggling finding a proper example of multi select (potentially with checkboxes.)

Something similar to here: https://material.angular.io/components/select/examples

It seems like an obious example but still there are none out there. Can you please help me finding one?

Best.

**Comment by allan-chen** [comment]
Hello,

Thanks for your question! Multiple selection is currently an open feature request at #5839. For now, the list component offers [list with checkboxes](https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#list-with-checkbox-items) which offers similar functionality. Please follow #5839 for tracking on multi-select lists.

Let me know if you have any further questions!

**Comment by robimalco** [comment]
Hello @allan-chen , many many thanks.

The example you posted is defintely useful, do you know if it is possibile to incorporate it within an expandable drop down menu?

That would perfectly fit my desire.

Thanks again!

**Comment by allan-chen** [comment]
Since select menu only supports single selection, another possibility is to use a menu button with selection group: https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu#selection-group-menu
