### ISSUE TITLE
[CircularProgress] Error when building JS - File not found

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6180]
## Bug report
This error shows up when building with Webpack Circular Progress (this only happened when upgrading the other components to v7):
```
ERROR in ./node_modules/@material/circular-progress/node_modules/@material/base/component.js
Module build failed: Error: ENOENT: no such file or directory, open 'D:\Maicol\Documents\Progetti\Web\account\node_modules\@material\circular-progress\node_modules\@material\base\component.js'
 @ ./node_modules/@material/circular-progress/component.js 24:0-56 108:2-14
 @ ./node_modules/@material/circular-progress/index.js
 @ ./resources/js/_material.js
 @ multi ./resources/js/_material.js ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/auth.scss

ERROR in ./node_modules/@material/circular-progress/node_modules/@material/base/foundation.js
Module build failed: Error: ENOENT: no such file or directory, open 'D:\Maicol\Documents\Progetti\Web\account\node_modules\@material\circular-progress\node_modules\@material\base\foundation.js'
 @ ./node_modules/@material/circular-progress/foundation.js 24:0-58 127:2-15
 @ ./node_modules/@material/circular-progress/index.js
 @ ./resources/js/_material.js
 @ multi ./resources/js/_material.js ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/auth.scss
```

### Steps to reproduce
1. Download some MDC v6
2. Download MDC Circular Progress v7
3. Upgrade all the v6 components to v7
4. Build JS
5. See error

### Actual behavior
Error

### Expected behavior
Everything should work

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| Browser          | Firefox 78.0
| Operating System | Windows 10 2004 x64

**Comment by allan-chen** [comment]
Hi,

Thank you for your issue. As build errors like this are difficult to reproduce locally, could you provide a Glitch demo outlining the issue? Alternatively, a recommended workaround is to upgrade all packages to the latest version at once.

Please let me know if there's any further questions.

**Comment by maicol07** [comment]
I've built a sample glitch: https://glitch.com/edit/#!/diamond-productive-lettuce?path=index.html%3A86%3A35
However, I don't know what is the problem and it can't find the stylesheet

**Comment by allan-chen** [comment]
I don't see how it's failing to load the transitive dependency of `@material/animation`.

Anyways, [here's](https://glitch.com/edit/#!/lying-cooing-archaeopteryx?path=package.json%3A8%3A22) a working Glitch. I didn't do much except fork your link and trim down the dependencies.

**Comment by maicol07** [comment]
Ok, but I need them. If I remove the circular-progress the build is successful

**Comment by allan-chen** [comment]
Sure - here's the same Glitch with the deps added back

https://glitch.com/edit/#!/lying-cooing-archaeopteryx?path=package.json%3A32%3A3

**Comment by maicol07** [comment]
Strange... It seems that switching to Yarn 2 (with PnP), then switching back to the classic Yarn (with the `node_modules` folder) worked...
