### ISSUE TITLE
[top-app-bar] Sass Mixins not working

### ISSUE THREAD

**Issue by youbet1980** [material-components/material-components-web#6190]
In the documentation here:
https://material.io/develop/web/components/top-app-bar
under Sass mixins
@use "@material/icon-button";
@use "@material/top-app-bar/mdc-top-app-bar";

@include icon-button.core-styles;

.mdc-top-app-bar{
@include top-app-bar.ink-color(black)
}
This does not work. None of the SASS mixins work for top-app-bar.

@asyncLiz would you please help? Or anyone who can see where I am going wrong?

**Comment by youbet1980** [comment]
Ok so I added an extra line.
@use "@material/top-app-bar"
Is this correct?

**Comment by asyncLiz** [comment]
That's correct!

This should be a little more clearer as we update our documentation, sorry if it was confusing. All of the mixins for components are available at the index file of the package: `@use '@material/<component-name>';`
