### ISSUE TITLE
mdc-select V7 component no longer functions correctly

### ISSUE THREAD

**Issue by cwalker-reveille** [material-components/material-components-web#6197]
## Bug report
When upgrading from V6.0.0 to V7.0.0, the mdc-select component no longer functions correctly.

### Steps to reproduce

1. Using the HTML and the Styles (verbatim) from the Basic Usage section in the documentation:
[https://material.io/develop/web/components/input-controls/select-menus](url)
2. Use V6.0.0 of the material components (I set all of my components to V6.0.0, not just the mdc-select)
3. Observe the action of the select, by clicking the dropdown icon and then selecting an item
4. Switch the components to V7.0.0
5. Observe that the selected item does not appear, nor does the dropdown icon

### Actual behavior

- The width of the component is now set to min-width of 200px and ignores the width set in the mdc-select__anchor per the documentation.
- The selected value does not appear in the <input> value of the component. It looks like its being set as innerText rather than the value.
- The dropdown icon is not visible, however clicking in the area where the icon should be does function.

### Expected behavior
I am expecting to see the selected value, the dropdown icon and have the width adjusted per the CSS as stated in the documentation in V7.0.0 as I saw in 6.0.0

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| Browser          | Chrome
| Operating System | Win 10, macOS Catalina 10.15.5

### Possible solution
Per other issues that I see in this repository, I am suspecting that the documentation is incorrect and needs to be corrected/updated for V7.0.0

**Comment by asyncLiz** [comment]
The documentation on material.io has not been updated to v7.0.0. Check out the [v7 readme HTML section for select](https://github.com/material-components/material-components-web/tree/v7.0.0/packages/mdc-select#html) for the proper html structure, since it has changed greatly since v6.

Feel free to comment on this issue if you continue to have trouble with the new structure for select!
