### ISSUE TITLE
List component does not work with version 7.0.0 and onwards

### ISSUE THREAD

**Issue by asyncoder** [material-components/material-components-web#6211]
**Describe the bug**
The component List (Hover and Ripple) does not work using latest version (7.0.0 and onwards)

**To Reproduce**
- Using version 6.0.0 works fine
- Codepen Url: [https://codepen.io/asyncoder/pen/OJMwVoz](https://codepen.io/asyncoder/pen/OJMwVoz)

- Using version 7.0.0 does not work
- Codepen Url: [https://codepen.io/asyncoder/pen/RwrBPeV](https://codepen.io/asyncoder/pen/RwrBPeV)

**Expected behavior**
This should work in version 7.0.0 as well.

**Browser Version (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge Chromium and Chrome]
 - Version [Edge: 83.0.478.61 - Chrome: 83.0.4103.116]

**Comment by asyncLiz** [comment]
List was changed in https://github.com/material-components/material-components-web/pull/6055, though it looks like we missed added a breaking change note.

Add the `<span class="mdc-list-item__ripple"></span>` element to each list item for the ripple to work correctly

https://codepen.io/asyncliz/pen/wvMxEJB
