### ISSUE TITLE
material-components-web vs material-components-web-components

### ISSUE THREAD

**Issue by MaximBalaganskiy** [material-components/material-components-web#6262]
What is the future of `material-components-web-components` with regards to this project?
I've seen indication that Angular team is working towards rebuilding Angular Material on top of `material-components-web`.
Would web components follow?

**Comment by jbingham** [comment]
Thanks for asking. Material Web Components are already built on top of material-components-web. The same team is developing both projects, and we're working to bring them even closer together, while continuing to support the needs of Angular Material.

**Comment by patrickrodee** [comment]
I'm going to close this for now but feel free to reopen if you have more questions.
