### ISSUE TITLE
mdc permanent drawer not working as expected in IE11

### ISSUE THREAD

**Issue by kiransp** [material-components/material-components-web#627]
Dear team,
i just added more data into the p tag of your demo link **http://material-components-web.appspot.com/drawer/permanent-drawer-below-toolbar.html** and it worked perfect in firefox. but in IE, this edit made the left drawer to shrink to very small size. [not even visible]. I have attached the screen shot for your reference. Please help me on this.
![mdcdrawerissue](https://cloud.githubusercontent.com/assets/4695339/25946887/98eb902a-366a-11e7-9649-ade6d80202b7.png)

**Comment by amsheehan** [comment]
This does indeed look to be a bug. We think it's because of Flexbox. Thanks for filing!

**Comment by anton-kachurin** [comment]
As I recall, this isn't IE specific bug. A solution is to use `flex: 0 0 auto;` for the `.mdc-permanent-drawer`

**Comment by kiransp** [comment]
that worked for me. Thanks a lot. 
if i want to run this http://material-components-web.appspot.com/drawer/permanent-drawer-below-toolbar.html purely in my local,without using node., how should i do it ?

**Comment by anton-kachurin** [comment]
@kiransp simply save the page from your browser, it will create required css and js files

**Comment by kiransp** [comment]
thank you !! using those saved css and js files, can i implement any other mdc components ?

**Comment by anton-kachurin** [comment]
You can use any existing components with those files. However, if you're making anything other than a demo, it's better to follow the suggested approach:
https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#creating-the-skeleton-indexhtml-file

**Comment by kiransp** [comment]
dont we have sticky footer in MDC ? I wanted to implement a sticky footer but i am not able to achieve it

**Comment by anton-kachurin** [comment]
According to [this table](https://github.com/material-components/material-components-web/blob/master/docs/migrating-from-mdl.md#component-equivalence), footer is not currently planned.

Are you talking about [this component](https://material.io/guidelines/components/bottom-navigation.html)?

**Comment by kiransp** [comment]
i am looking something like this https://getbootstrap.com/examples/sticky-footer/ ,  to achieve at the end of  mdc-permanent drawer.

**Comment by anton-kachurin** [comment]
I'm afraid this won't be trivial. [Drawer's specification](https://material.io/guidelines/patterns/navigation-drawer.html) doesn't have a footer, therefore it will not be implemented in this library.

You could fork this project and extend functionality of the drawer for your needs, or you could simply write custom CSS and include it on your page, but either way keep in mind that any changes to the drawer within the scope of this library might potentially break your changes.

I would suggest not to use `mdc-drawer` at all, but use it as a reference to create your own drawer.
