### ISSUE TITLE
Use passive event listeners for the ripple

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#629]
There are going to be some new metrics in [Lighthouse](https://developers.google.com/web/tools/lighthouse/), one of which looks at whether touch event listeners are being marked as passive.

We currently use touch events in two places: drawers and the ripple. We already have passive event listeners for [the drawer](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/util.js#L61) where supported, but the ripple doesn't do the same. As long as it doesn't cancel the events, it should be able to make use of passive as well.

Making sure we apply passive event listeners wherever possible would both ensure better performance in MDC-Web components, as well as higher Lighthouse scores for applications using it.

**Comment by traviskaufman** [comment]
Great suggestion @sgomes! Adding "help wanted" to this as the work is straightforward:

- [ ] Copy the `applyPassive` code into `mdc-ripple/util.js` (this will be refactored as part of #70)
- [ ] Use `applyPassive` to instantiate the ripple adapter (via `createAdapater`) the [same way as in drawer](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/temporary/index.js#L54-L56)
- [ ] Add tests for `applyPassive` e.g. https://github.com/material-components/material-components-web/blob/master/test/unit/mdc-drawer/util.test.js#L102-L122

**Comment by sgomes** [comment]
Woohoo, thank you @trimox!
