### ISSUE TITLE
[MDCTextField] When prefilled it doesnt move

### ISSUE THREAD

**Issue by robimalco** [material-components/material-components-web#6290]
Dear Team,

I am struggling because my floating-label when prefilled doesn't move.

![Screenshot from 2020-07-28 17-24-39](https://user-images.githubusercontent.com/30242227/88686328-461c9800-d0f7-11ea-9e2a-6439e68efaa2.png)

I have already instantiated the component:

mdc.textField.MDCTextField.attachTo(document.getElementById("UserName"));

As soon as I click it, it works perfectly:

![Screenshot from 2020-07-28 17-25-22](https://user-images.githubusercontent.com/30242227/88686468-69dfde00-d0f7-11ea-8acb-5dbf365249f2.png)

May somebody help me out with this?

Many thanks and best regards

**Comment by robimalco** [comment]
Here a workaround I created, maybe ugly but it works
Inside the method which fetches data from the server, you can assign the class "mdc-floating-label--float-above" if the value is present:

```    
methods: {
        fetchProfile: function() {
                const edtTexts = [].map.call(document.querySelectorAll('.mdc-floating-label'), function(el) {
                    if (YOUR_FETCHED_DATA[el.id] !== "") {
                        el.classList.add('mdc-floating-label--float-above');
                    }
                });
        },
},
```

**Comment by asyncLiz** [comment]
This is working as intended. The documentation mentions in the [pre-filled section](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#pre-filled) that you must add the following classes to the text field:

- `mdc-text-field--label-floating` to `mdc-text-field`
- `mdc-floating--float-above` to `mdc-floating-label`

If you attach the MDCTextField element to a text field that _already_ has a value, it will assign these classes for you, but you will see a Flash Of Unstyled Content (FOUC). 

If you attach the MDCTextField first and intend to set the value after, you must use the MDCTextField component's `value` property to set the value. Do not set the `<input>` element's `value` property after fetching data from the server. The component will not be notified and the label will not float.

Let us know if you have any more questions!
