### ISSUE TITLE
Add fast scroll

### ISSUE THREAD

**Issue by Touficbatache** [material-components/material-components-web#630]
Hi,
Yesterday I was searching for an app in the settings and I found it took a lot of time to scroll through all the other apps so I noticed the fast scroll which helped me a lot to find what I want quicker. 
I thought that you could add this feature as it is really useful. I'll add a screenshot for better understanding.
![screenshot_20170510-215308](https://cloud.githubusercontent.com/assets/17137918/25951433/6141c2d8-3666-11e7-846c-37b518317231.png)

**Comment by amsheehan** [comment]
Looks like this is a feature of a specific Android app. There are currently no plans to implement a feature like this in MDC Web—but this makes sense. 

If you think of what MDC Web solves for, it's a library that provides UI components with zero opinion on the framework being used. Something like this would be a feature implemented app to app in your framework of choice, but not necessarily a UI element.

What MDC Web _could_ be used for in an example like this is theming, elevation, typography, etc... as those concepts apply to this feature.

Either way, thanks for filing! Closing the issue.
