### ISSUE TITLE
[mdc-density] Question: using sassc compile scss to css

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#6300]
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| node | v12.18.3
| npm | 6.14.6
| Operating System | macOS 10.15.6

I installed mdc-7.0.0 locally by npm.
I try to compile scss to css with command `sassc --load-path=node_modules my-custom-button.scss my-custom-button.css`, but get error always.

I have no idea.
Any advice?

sassc version
---
sassc: 3.6.1-8-g3e73
libsass: 3.6.4-11-gb916-dirty
sass2scss: 1.1.1
sass: 3.5

converting error
---
```
Error: Invalid CSS after "  @include button": expected "}", was ".density(-3);"
        on line 5:12 of mdc.scss
>>   @include button.density(-3);

   -----------^
```

my-custom-button.scss
---
```
@use "@material/button";

.my-custom-button {
  // Sets button density scale to `-3`, i.e. button height to `24px`.
  @include button.density(-3);
}
```

**Comment by asyncLiz** [comment]
libsass does not support the `@use` syntax. You'll need to use the primary [dart-sass](https://sass-lang.com/dart-sass) implementation when compiling MDC.

**Comment by diuming** [comment]
@asyncLiz thanks! it works well.
