### ISSUE TITLE
Label on textfield with fullwidth class is not visible on Safari (OS X)

### ISSUE THREAD

**Issue by abyr** [material-components/material-components-web#631]
### What MDC-Web Version are you using?

> v0.10.0 

### What browser(s) is this bug affecting?

> Safari Version 10.1 (12603.1.30.0.34)
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30

### What OS are you using?

> OS X 10.12.4

### What are the steps to reproduce the bug?

> 1. Open demos/textfield.html in IDE to start editing
> 2. Add "mdc-textfield--fullwidth" class to the first input with ID "my-textfield"
> 3. Do not fill value attribute
> 4. run the demo server
> 5. go to localhost:8080/textfield.html
> 6. Tab-focus on the first text field
> 7. Observe the component's behavior

### What is the expected behavior?

> Label on the textfield should be visible

### What is the actual behavior?

> Textfield is empty. Label is not visible.

### Any other information you believe would be useful?

> The result code:

       <div class="mdc-textfield mdc-textfield--fullwidth">
          <input type="text" class="mdc-textfield__input" id="my-textfield"
                 name="email" aria-controls="my-textfield-helptext"
                 data-demo-no-auto-js autocomplete="email">
          <label for="my-textfield" class="mdc-textfield__label">Text Field</label>
        </div>

**Comment by amsheehan** [comment]
Hey, @abyr thanks for filing!

Currently, there is no support for labels on full width text fields.

**Comment by abyr** [comment]
Got it. :) Thanks for the response!
