### ISSUE TITLE
MDC IconButton Sass Variable Error

### ISSUE THREAD

**Issue by jimmyhdolores** [material-components/material-components-web#6316]
Hello, I am trying to change the buton color through a Sass variable but it appears that you are taking it as text in the ink-color function, any suggestions?

![image](https://user-images.githubusercontent.com/10909792/88979894-2f597b00-d288-11ea-99b7-c898cc0b50d7.png)

![image](https://user-images.githubusercontent.com/10909792/88979948-47c99580-d288-11ea-8fd8-b6eb36fe4cf0.png)

This problem also happens with CheckBoxes.

**Versions:**
"material-components-web": "^7.0.0"

**Comment by asyncLiz** [comment]
Using `var()` with MDC mixins is not supported. You will need to use the `@material/theme/custom-properties` utilities to provide the correct custom property Map structure.

```scss
@include icon-button.ink-color(custom-properties.create(--color-icon-button));
```

Keep in mind that not all MDC mixins support providing your own custom properties as values at the moment. Support for complete custom property theming can be tracked in https://github.com/material-components/material-components-web/issues/5242.

**Comment by jimmyhdolores** [comment]
I tried the custom-properties functions but there is no success, I suppose they will add this functionality in some future version.

![image](https://user-images.githubusercontent.com/10909792/89058057-4188f700-d324-11ea-8424-161f834068c6.png)

![image](https://user-images.githubusercontent.com/10909792/89058072-4b125f00-d324-11ea-806a-1df4cbd578d1.png)


other

![image](https://user-images.githubusercontent.com/10909792/89058209-86149280-d324-11ea-9a89-b45f2e800c7c.png)
![image](https://user-images.githubusercontent.com/10909792/89058230-8dd43700-d324-11ea-96b2-c5378d3b1021.png)

**Comment by asyncLiz** [comment]
Try adding a fallback value to your custom property. Ripple is trying to check the opacity value of the color, and it's throwing an error because the fallback value is `null`.
