### ISSUE TITLE
Data table docs have incorrect mixin import path

### ISSUE THREAD

**Issue by rolanday** [material-components/material-components-web#6317]
## Bug report
Upgraded MDC components from 6.0.0 to 7.0.0. Fully functional build on 6.0.0, but I am now getting a SassBuild error when adding data-table styles as per documentation:

```
@use "@material/data-table";

@include data-table.theme-baseline;
@include data-table.core-styles;
```

Build now complains:

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
   ╷
57 │ @include data-table.theme-baseline;
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

> **Note:** All 25 other MDC styles build fine  -- issue is specific to data-table.

Relevant webpack config as follows:
```
          {
            /// https://material.io/develop/web/docs/getting-started/
            loader: 'sass-loader',
            options:
              {
                // implementation: require('sass'),
                implementation: require('dart-sass'),
                sassOptions: {
                  includePaths: ['./node_modules']
                },
                sourceMap: true,
                webpackImporter: false
              }
          }
```

> **Note:** Tried both sass and dart-sass implementations => same result.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.00
| Browser          | N/A
| Operating System | macOS

**Comment by patrickrodee** [comment]
Hey Roland, thanks for reporting this bug. It looks like our docs are incorrect here. The [`core-styles`](https://github.com/material-components/material-components-web/blob/a3212b2099765947f2a41d71af2cd95fcbca4b97/packages/mdc-data-table/_data-table.scss#L44) and [`baseline-theme`](https://github.com/material-components/material-components-web/blob/a3212b2099765947f2a41d71af2cd95fcbca4b97/packages/mdc-data-table/_data-table.scss#L323) mixins are provided by the [`_data-table.scss` file](https://github.com/material-components/material-components-web/blob/v7.0.0/packages/mdc-data-table/_data-table.scss).

If you update your Sass import to the following, it should resolve the issue.

```
@use "@material/data-table/data-table";
```

We'll leave this open as a documentation bug to be fixed.

Let me know if you have any questions!

**Comment by rolanday** [comment]
Works like a charm now! Thanks :-)
