### ISSUE TITLE
Demo MDC-Chips Input Chips

### ISSUE THREAD

**Issue by jimmyhdolores** [material-components/material-components-web#6321]
I am trying to use the Input Chips but I am not successful, do you have any demo?

**Comment by abhiomkar** [comment]
Created a sandbox demo using docs from [chips README file](https://github.com/material-components/material-components-web/tree/master/packages/mdc-chips).

You can use this as [sample demo of MDC input chips](https://glitch.com/edit/#!/gifted-meowing-stoat?path=index.html%3A1%3A0).
