### ISSUE TITLE
[Select] Dropdown icon SVG needs focusable="false" for IE11

### ISSUE THREAD

**Issue by austinw-fineart** [material-components/material-components-web#6323]
## Bug report
This isn't as much of a bug as it is a warning but in IE11 all SVG elements are navigable by keyboard so you'll need to explicitly set the attribute `focusable="false"` on them for the correct behavior. At the very least you'll want to note this in the documentation if you happen to support IE11.

### Actual behavior
With IE11, each select component takes 2 tab presses to navigate.

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |7.0.0
| Browser          |IE11
| Operating System |Windows 10

### Possible solution
Set the attribute `focusable="false"` on the SVG element.

**Comment by allan-chen** [comment]
Hey Austin,

Thank you for finding this! I was able to repro on IE. We are working on a fix.
