### ISSUE TITLE
@material/select fullwidth style does not exist

### ISSUE THREAD

**Issue by stefanloerwald** [material-components/material-components-web#6324]
## Bug report

I'm using version 7.0.0 and according to the docs, the CSS class `mdc-select--fullwidth` should exist. It doesn't seem like it actually does though.

### Steps to reproduce

1. Install @material/select
2. Use `mdc-select--fullwidth`

or simply grep for "select--fullwidth" and you'll only find the README entry, but no other hit.

**Comment by asyncLiz** [comment]
The fullwidth variant was removed in https://github.com/material-components/material-components-web/pull/6106. Looks like there are a few places that didn't get updated in the readme.

The fullwidth class is unnecessary. You can simply add `width: 100%` to the select to achieve the same effect. Pinging @allan-chen for the docs issue.
