### ISSUE TITLE
Components layout incorrectly in hero section of new demo site (IE11)

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#633]
### What MDC-Web Version are you using?

0.10.0

### What browser(s) is this bug affecting?

IE11

### What OS are you using?

Windows 8.1 on VirtualBox VM

### What are the steps to reproduce the bug?

1. Open [demo site](http://material-components-web.appspot.com/) in IE11
2. Navigate to any component

### What is the expected behavior?

Component in hero section should be centered both horizontally and vertically.

### What is the actual behavior?

The component is stuck at the top of the element

### Any other information you believe would be useful?

There is a known issue: https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview

The fix is to set a `height` rule on the hero element:

```css
.hero {
  ...
  height: 360px;
  ...
}
```

**Comment by traviskaufman** [comment]
Marking as "help wanted". Fix is detailed above. That code should go into `demos/demos.css`.

**Comment by Aedalus** [comment]
I'm hoping to start contributing to the project, and attempted to clone/fix/make a PR here:

https://github.com/material-components/material-components-web/pull/636

If there are any issues with it, please let me know!
