### ISSUE TITLE
[MDCTooltip] Not working in latest web components version

### ISSUE THREAD

**Issue by rolanday** [material-components/material-components-web#6349]
As per https://github.com/material-components/material-components-web/issues/24 (Investigate making the Tooltip Component), tool tips support is available in latest version.

I tried tooltip support using 8.0.0-canary.2e5711e04.0 and not working. No build or web pack errors and all other MDC components functioning as expected. Can you please confirm it tooltip support is expected to work in this version or not? I followed the README instructions exactly.

Thanks.

**Comment by asyncLiz** [comment]
Can you provide a jsbin/glitch or similar reproduction of your problem with the code that you've tried?

**Comment by maicol07** [comment]
@asyncLiz the problem is that the tooltip doesn't show up with the current canary version
