### ISSUE TITLE
Tabbed/Step Dialog

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6356]
## Feature Request
Dialog with a tabbar, like [SweetAlert2 Chaining Modals](https://sweetalert2.github.io/#chaining-modals), where dialog has some "steps" (tabs). Clicking on these change its content. Also the confirm button should move onto the next tab. On the last one, it should close the dialog.

### Proposed solution
Extend dialog component to make a tabbed version and customize content based on current tab

### Alternatives considered
Building a wrapper but it isn't so simple with my current TS and JS knowledge

**Comment by joyzhong** [comment]
Hi there, thanks for filing this feature request. Our team builds components directly based on the [Material Design spec](https://material.io/components/dialogs), which does not currently include chained dialogs. As such, closing this request.
