### ISSUE TITLE
[mdc-list] support selection using CTRL + A shortcut

### ISSUE THREAD

**Issue by devversion** [material-components/material-components-web#6366]
## Feature Request

As per W3C recommended shortcuts for listbox patterns, the CONTROL + A shortcut should
select all items/options in a listbox. This is currently not supported in the MDC list.

https://www.w3.org/TR/wai-aria-practices-1.1/#listbox_kbd_interaction

### Proposed solution

MDC already supports various keyboard shortcuts. The existing keyboard handler could
be extended to support the CTRL + A shortcut. This should be fairly straightforward.

Note: If all options are selected and the shortcut is used, all items should be unselected.

**Comment by joyzhong** [comment]
Thank you for filing! Adding to our backlog.

It's unlikely our team will have bandwidth to fix this in the near future, but please feel free to send a PR for this. We are open to contributions.
