### ISSUE TITLE
[Question] Microsoft Edge bugs are known?

### ISSUE THREAD

**Issue by djensen47** [material-components/material-components-web#638]
I was playing around with the demo site on Microsoft Edge and there are numerous bugs. Are these known or should I file a bug for each?

Keep in mind there's probably several dozen bugs. Although they all seem to be related to Javascript components. CSS only seem to work.

**Comment by amsheehan** [comment]
Hello!

We would welcome any new issues on bugs you may find. If you wouldn't mind doing a cursory search to see if a particular bug is accounted for, that would be much appreciated!

Thanks

**Comment by djensen47** [comment]
It doesn't _seem_ to be accounted for in any of the open bugs. It weird because one is quite glaring, the ripple effect does very weird things on Edge.

I'll start filling bugs today. Thanks!
