### ISSUE TITLE
[DataTable] destroy() exception

### ISSUE THREAD

**Issue by YuoMamoru** [material-components/material-components-web#6385]
## Bug report
The destroy method of MDCDataTable doesn't check if headerRowCheckbox is set before calling destroy on it, this causes an exception when not using row selection:

```
MDCDataTable.prototype.destroy = function () {
    this.headerRow.removeEventListener('change', this.handleHeaderRowCheckboxChange);
    this.headerRow.removeEventListener('click', this.headerRowClickListener);
    this.content.removeEventListener('change', this.handleRowCheckboxChange);
    this.headerRowCheckbox.destroy();
    this.rowCheckboxList.forEach(function (checkbox) {
        checkbox.destroy();
    });
};
```

Docment says "Instantiating MDCDataTable component is only required to add interactions for example, row selection.", but client needs to instantiate JS to use data table with column sorting.

### Steps to reproduce
1. Create a Data Table that doesn't use row selection, but it uses column sorting.
2. Call destroy on the data table
3. Exception is thrown

### Actual behavior
Exception is thrown

### Expected behavior
No exception should be thrown

### Possible solution
Check if it exists before calling destroy.

**Comment by joyzhong** [comment]
Thanks for reporting! Adding to our backlog, but please feel free to send a PR for this.
