### ISSUE TITLE
[MDC Circular Progress] Circular Progress not displayed correctly inside button

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6388]
## Bug report

Circular progress not displayed correctly

### Steps to reproduce

1.  Create a button
2.  Create a circular progress inside button

### Actual behavior

See codepen: https://codepen.io/maicol07/pen/QWNNwxO

### Expected behavior

Circular Progress displayed correctly

### Your Environment:

| Software | Version(s) |
| --- | --- |
| MDC Web | 7.0.0 |
| Browser | Firefox |
| Operating System | Windows 10 |

**Comment by joyzhong** [comment]
Thanks for reporting this issue! Can you clarify your use case for using a circular progress indicator inside of a button?

**Comment by maicol07** [comment]
@joyzhong sure.
I'm using a circular progress isnide a button to show a loading button. When a user clicks on it, an AJAX request is sent to the server. Meanwhile, the button is loading

**Comment by joyzhong** [comment]
Got it! This pattern is demonstrated in [the MD spec](https://material.io/components/progress-indicators#circular-progress-indicators): "A circular indicator can be integrated into a button or actionable icon to express a connection between an interaction and a specific item. They are typically used to express when an interaction, such as clicking a button again, isn’t available."

Adding to our backlog.
