### ISSUE TITLE
[MDC Tooltip] Tooltip trimmed

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6392]
## Bug report

Tooltip is trimmed if content is larger than 120px (see screenshot)

### Steps to reproduce

1.  Create a tooltip with a long content
2.  Attach tooltip to an element
3.  See the tooltip

### Actual behavior

Tooltip is trimmed if content is larger than 120px (see screenshot)

### Expected behavior

Tooltip should show all the content

### Screenshots

![immagine](https://user-images.githubusercontent.com/9463142/90376519-e3c01300-e076-11ea-9cb3-34b370741020.png)

### Your Environment:

| Software | Version(s) |
| --- | --- |
| MDC Web | 7.0.0 + tooltip canary |
| Browser | Firefox |
| Operating System | Windows 10 |

### Possible solution

Can be fixed setting the `max-width` css property (of the surface) to `max-content`

**Comment by allan-chen** [comment]
+CC @sayris

**Comment by sayris** [comment]
Expected behavior is for the tooltip to wrap once it hits the `max-width` (though in discussions about potentially increasing this width). Would you mind sharing the full string that is intended to be shown in the tooltip?

**Comment by maicol07** [comment]
This is the full string: `Attivato con il numero XXX-XXX-9421`

**Comment by sayris** [comment]
Unfortunately, I'm unable to reproduce this on my end (text wraps rather than extending beyond the boundaries of the tooltip container). Would you be able to create/attach a CodePen reproducing this issue?

Thanks!

**Comment by maicol07** [comment]
At the moment this is what I could get:

https://codepen.io/maicol07/pen/VwaWbGx

**Comment by sayris** [comment]
https://github.com/material-components/material-components-web/pull/6425 updated how tooltips handle labels that extend beyond the maximum-width, and should fix this issue. If you're still running into issues, I would recommend utilizing the `word-break` mixin.
