### ISSUE TITLE
[test] tests are not running locally

### ISSUE THREAD

**Issue by YonatanKra** [material-components/material-components-web#6393]
## Bug report
Tests are not running locally

### Steps to reproduce
1. Fork the repo
2. Clone the repo
3. npm i
4. npm test

### Actual behavior
I get the following output:

### Expected behavior
```
17 08 2020 14:22:44.528:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.8.3
17 08 2020 14:22:51.148:INFO [compiler.karma-typescript]: Compiled 355 files in 6484 ms.
17 08 2020 14:22:52.413:ERROR [karma-server]: UncaughtException
17 08 2020 14:22:44.528:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.8.3
17 08 2020 14:22:51.148:INFO [compiler.karma-typescript]: Compiled 355 files in 6484 ms.
17 08 2020 14:22:52.413:ERROR [karma-server]: UncaughtException
```
### Screenshots
![image](https://user-images.githubusercontent.com/6459899/90392011-c438e280-e096-11ea-83dd-0e0507c38d6d.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0 |
| Browser          | N/A |
| Operating System | MacOS |

**Comment by abhiomkar** [comment]
I'm not able to reproduce this bug for following node version.

Node `v10.22.0` (npm: `6.14.6`)

@YonatanKra Can you try running `npm run clean` and try running unit tests (`npm run test:unit`)?

**Comment by YonatanKra** [comment]
That did it. Thanks @abhiomkar !
