### ISSUE TITLE
[MDC TextField] How do i change floating-label color?

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#6398]
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| Browser          | Safari 13.1.2
| Operating System | macOS 10.15.6

I prefer gray color(non clicked)
![Screen Shot 2020-08-18 at 12 19 41 PM](https://user-images.githubusercontent.com/39903550/90470262-96fb3b80-e14d-11ea-9085-ad4ad70dc831.png)

But,
How do i change folating-label color the same as outlined-border color using sass?
![Screen Shot 2020-08-18 at 12 08 49 PM](https://user-images.githubusercontent.com/39903550/90469770-46cfa980-e14c-11ea-81c4-48e85304cadd.png)

**Comment by asyncLiz** [comment]
You can use the `textfield.label-color()` mixin. This mixin and others are documented in the [Sass mixins section of the textfield readme](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#mixins-for-all-text-fields).

```scss
@use '@material/textfield';

.custom-text-field {
  @include textfield.label-color(blue);
}
```

**Comment by diuming** [comment]
@asyncLiz thanks.

But I want to keep label in gray when non clicked.

**Comment by CyborgSemon** [comment]
This has popped up for a while. There have been a number of issues submitted over the years around this issue that has been apparent in a few components. #5842, #5878, #4709, #4489, #4431 going all the way back to #3145

**Comment by asyncLiz** [comment]
You can use the `.mdc-text-field--label-floating` modifier class to customize your selector to only apply when the label is floating. CSS classes are documented in [this section](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#css-classes) of the text field readme.

```scss
@use '@material/textfield';

.custom-text-field.mdc-text-field--label-floating {
  @include textfield.label-color(blue);
}
```
