### ISSUE TITLE
Cannot resolve symbol 

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6399]
## Bug report

Using PHPStorm or any other Intellij IDE, I get this weak warning when importing JS components:

![](https://user-images.githubusercontent.com/9463142/90518087-958a3d00-e166-11ea-9c1c-e410022bbaa8.png)

Example import code:

```javascript
import { MDCCheckbox } from '@material/checkbox';
import { MDCChip, MDCChipSet } from '@material/chips';
import { MDCCircularProgress } from '@material/circular-progress';
import { MDCDrawer } from '@material/drawer';
import { MDCDialog } from '@material/dialog';
import { MDCFormField } from '@material/form-field';
import { MDCList } from '@material/list';
import { MDCMenu } from '@material/menu';
import { MDCMenuSurface } from '@material/menu-surface';
import { MDCNotchedOutline } from '@material/notched-outline';
import { MDCRipple } from '@material/ripple';
import { MDCSelect } from '@material/select';
import { MDCTabBar } from '@material/tab-bar';
import { MDCTextField } from '@material/textfield';
import { MDCTextFieldIcon } from '@material/textfield/icon';
import { MDCTooltip } from '@material/tooltip';
import { MDCTopAppBar } from '@material/top-app-bar';
```

### Steps to reproduce

1.  Download at least 1 MDC component with Yarn/NPM
2.  Import in JS
3.  See the warning (if you're using Intellij IDEs)

### Actual behavior

Getting this warning: 

![](https://user-images.githubusercontent.com/9463142/90518188-b6eb2900-e166-11ea-94fb-383d62652179.png)

### Expected behavior

No warning

### Your Environment:

| Software | Version(s) |
| --- | --- |
| MDC Web | 7.0.0 |
| Browser | Firefox |
| Operating System | Windows 10 |

**Comment by allan-chen** [comment]
Hi Maicol,

Does compilation work fine?

**Comment by maicol07** [comment]
@allan-chen yes

**Comment by allan-chen** [comment]
This is a shot in the dark as I am not quite familiar with PHPStorm, but do the steps suggested in [this](https://stackoverflow.com/questions/35741847/cannot-resolve-symbol-when-using-es6-import-syntax) stackoverflow post help at all?

**Comment by maicol07** [comment]
@allan-chen the only problem with TS libraries is that MDC ones are really old (version 0.52). They should be updated...

**Comment by allan-chen** [comment]
Where are you finding these outdated versions?

**Comment by maicol07** [comment]
@allan-chen here: https://www.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types

**Comment by allan-chen** [comment]
Apologies for the confusion - my intent was to suggest if you could add our packages using the method above. Please remove that type library, as our npm packages ship with `d.ts` type declaration files.

**Comment by maicol07** [comment]
Ok, I think I understand what are you saying.
I'll try tomorrow and will tell you
________________________________
Da: Allan Chen <notifications@github.com>
Inviato: martedì 18 agosto 2020 20:55
A: material-components/material-components-web
Cc: Maicol; Author
Oggetto: Re: [material-components/material-components-web] Cannot resolve symbol (#6399)


Apologies for the confusion - my intent was to suggest if you could add our packages using the method above. Please remove that type library, as our npm packages ship with d.ts type declaration files.

**Comment by maicol07** [comment]
@allan-chen didn't work, but this work:

```javascript
import { MDCCheckbox } from '@material/checkbox/index';
```

If I click on `MDCCheckbox` to see its source I see it came from a `component.d.ts` file. Maybe there is a way to enable this from `@material/checkbox`?

**Comment by allan-chen** [comment]
The type definitions definitely exist but somehow aren't picked up without explicitly referencing the index file instead of directory root. This sounds like a quirk with the resolver that the IDE is using. Since it's an (albeit weird) soft warning and a workaround exists, I'll close this issue for now.
