### ISSUE TITLE
Simple menu addition

### ISSUE THREAD

**Issue by Touficbatache** [material-components/material-components-web#641]
Hey,
I noticed that if you have a small word in the MDC Simple Menu, it doesn't really look good. This could be fixed by adding a small `min-width: 150px;` to the `.mdc-simple-menu` class. It will be at _least_ 150px and if you add a bigger word, it will work as expected.
![mdc menu](https://cloud.githubusercontent.com/assets/17137918/25990214/9d2ea094-3707-11e7-8f14-7e8509f49e3c.png)

**Comment by yeelan0319** [comment]
@Touficbatache Thanks for filing the bug, we will follow up with the design team and follow up with you later on.

**Comment by yeelan0319** [comment]
We have discussed this with our design team. Based on the spec:

> Menu width varies depending on string length, and on mobile is defined as a multiple of a 56dp unit. Simple menus always maintain a 16dp margin (phone) or 24dp margin (tablet) to the left and right edges of the screen.

We want to keep the menu without minimal width so it might benefit small screen or dense layout. But we do encourage you to set minimal width to fit your layout or stylistic choices by overriding mdc's default value as always.

I am closing this issue. Just a side note, if you decided to do so, that minimal value should be used consistently throughout.
