### ISSUE TITLE
[MDC TextField] difference behavior between browsers.

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#6414]
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| Browser          | Safari 13.1.2
| Browser          | Chrome 84.0.4147.135
| Operating System |mac OS 10.15.6

Safari
---
![Screen Shot 2020-08-20 at 1 50 25 PM](https://user-images.githubusercontent.com/39903550/90722449-681bcb80-e2ed-11ea-9e72-6783c5bccb84.png)

Chrome
---
![Screen Shot 2020-08-20 at 1 59 11 PM](https://user-images.githubusercontent.com/39903550/90722441-64884480-e2ed-11ea-80ee-16ee5986114f.png)

**Comment by asyncLiz** [comment]
Thanks for the bug! This has already been reported and is being tracked in https://github.com/material-components/material-components-web/issues/5879
