### ISSUE TITLE
[dialog] ignoring enter key on deep elements

### ISSUE THREAD

**Issue by 43081j** [material-components/material-components-web#6429]
In the dialog foundation we have this:
https://github.com/material-components/material-components-web/blob/58eaa9f027bb7ced126d3fe97cab5a0f627eb098/packages/mdc-dialog/foundation.ts#L208-L212

Essentially to prevent the enter key from triggering the primary action if you're in a "special" element ([here](https://github.com/material-components/material-components-web/blob/58eaa9f027bb7ced126d3fe97cab5a0f627eb098/packages/mdc-dialog/constants.ts#L47-L50) defined as a textarea or a list-item).

This works in most cases but doesn't account for event retargeting.. so if we have a textarea in a shadow root, inside the dialog, it will not be detected as one of these "special cases" and will trigger the primary action still when you press enter.

Am i ok to get a PR together which changes this to use the composed path instead of the event target?

**Comment by asyncLiz** [comment]
Adding to our backlog. I made some comments on the PR for an alternate solution that I think may be more flexible
