### ISSUE TITLE
openFrom and closeTo options for dialog

### ISSUE THREAD

**Issue by caseyjhol** [material-components/material-components-web#643]
As described in Angular Material (https://material.angularjs.org/latest/demo/dialog):

> A dialog can specify its origin and target with openFrom and closeTo properties. The options showFrom and closeTo can be specified as a string [where internally querySelector( ) is used to perform the DOM element lookup], element or an Rect object [with top, left, width, height fields].

openFrom and closeTo default to the clicked element.

I've looked at the code Angular Material uses, and I think it might not be *that* difficult to port over to vanilla JS. If this is outside the scope of this project, let me know, but I think it could be useful and well within the spirit of Material design.

**Comment by Garbee** [comment]
This feels to me like it pushes the framework territory over pure library. The focus has traditionally been for MCW to be as vanilla as possible to allow easy integration into any framework people want if desired. I personally think it best to not over-complicate the features provided outside of the scope of what Material Design requires in terms of UX. This goes into the functional boundary only, so it feels out of place to me.

**Comment by yeelan0319** [comment]
@Garbee is right. 
Based on the design guideline, dialog is modal by design and should always appear from the center of the screen, which is different from a contextual menu.
