### ISSUE TITLE
MDC-Drawer FocusTrap: Element must have at least one focusable child

### ISSUE THREAD

**Issue by jimyhdolores** [material-components/material-components-web#6434]
Hello, I am receiving this error and it does not allow to close the Modal, I am working with StencilJS and JSX, the error appears when I assign the content of the Drawer through the SLOT tag.

![image](https://user-images.githubusercontent.com/10909792/91235304-e8319f00-e6fa-11ea-8f95-aa45cbf7e589.png)
![image](https://user-images.githubusercontent.com/10909792/91235351-fed7f600-e6fa-11ea-84de-28ff818e16d8.png)
![image](https://user-images.githubusercontent.com/10909792/91235413-1f07b500-e6fb-11ea-849f-9b1a0dfe686c.png)
I set the tabIndex to 0 but it has no effect; If I assign the content directly, it does not give this error, but in my case I need to assign it through the SLOT tag, I hope you can help me

**VERSION**

"material-components-web": "^7.0.0"

**Comment by asyncLiz** [comment]
Thanks for the bug!

Unfortunately the [MDCDrawer](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/component.ts) component does not support projecting content through a `<slot>` with shadow DOM, and that's out of scope for what our components will support. You would need to create your own component that implements [MDCDrawerAdapter](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/adapter.ts) and connect it to the [MDCDismissibleDrawerFoundation](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/dismissible/foundation.ts) or [MDCModalDrawerFoundation](https://github.com/material-components/material-components-web/blob/master/packages/mdc-drawer/modal/foundation.ts).

From there, you can use a different implementation in the adapter's request to `trapFocus()` that is compatible with shadow DOM slots.

This is what Material Web Components' [`<mwc-drawer>`](https://github.com/material-components/material-components-web-components/tree/master/packages/drawer) does, which uses the [blocking-elements](https://github.com/PolymerLabs/blocking-elements) library to [trap and release focus from its slot](https://github.com/material-components/material-components-web-components/blob/14a172db1a5357a2985419cc0d42e160fbf9fe4d/packages/drawer/mwc-drawer-base.ts#L83-L90). I would recommend looking at `<mwc-drawer>` as a web component implementation to use, or as a reference for a shadow DOM-based implementation with slots to get started.

**Comment by jimyhdolores** [comment]
@asyncLiz  thank you very much, is what you need.
