### ISSUE TITLE
[mdc-select] Using a select inside a data table doesn't work

### ISSUE THREAD

**Issue by davekaro** [material-components/material-components-web#6440]
### Steps to reproduce
1. Go to https://glitch.com/edit/#!/join/881c81a3-2bd7-4868-9ea4-1a7e489fbe95
2. Click on "Pick a food group" selects
3. Notice the menus within the table don't show - if the table row is high enough it does show (as showcased in the middle row)

### Actual behavior
Select menus are clipped with Data tables

### Expected behavior
Select menu should open within a Data table

### Screenshots
Example of clipped menu in middle of table
<img width="449" alt="clipped-middle-row" src="https://user-images.githubusercontent.com/21263/91648760-6498ea80-ea39-11ea-93dd-5549888f6c3f.png">

This select menu works fine outside the table
<img width="447" alt="not-clipped-outside-table" src="https://user-images.githubusercontent.com/21263/91648766-7084ac80-ea39-11ea-84e8-3dbd58b51487.png">

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| Browser          | Firefox 80
| Operating System | Windows 10

### Additional context
Perhaps a select menu within a data table is discourage UX?

### Possible solution
z-index is set to 8 on the select menu, I tried increasing but it didn't work.

**Comment by allan-chen** [comment]
Hi Dave,

You should be able to resolve this using the same strategy as display of a select menu inside dialogs.

Please see this [comment](https://github.com/material-components/material-components-web/issues/5590#issuecomment-657032119) in another issue for the solution. In essence, a fixed menu needs to be used instead.

It may be possible to resolve this by removing overflow: hidden on the datatable cells but that requires further investigation.

Please feel free to let me know if there's more questions!
