### ISSUE TITLE
[mdc-list] pointer cursor showing for non-interactive lists

### ISSUE THREAD

**Issue by devversion** [material-components/material-components-web#6443]
## Bug report

The MDC list provides styles for Material Design lists, and _optionally_ (as per documentation) provides an upgraded JavaScript variant that can provide an keyboard interaction, typeahead etc.

This is not always used though. i.e. there are cases where a list is providing content without the need
of interaction. Purely used as a "decorated" standard `<ul>` and `<li>`.

Currently this works fine in terms of visual appearance of the list and items, but the cursor seems to be
showing up incorrectly as "pointer", indicating the possibility of interaction.

### Steps to reproduce
1. Go to https://stackblitz.com/edit/mdc-list-demo-non-interactive?file=index.html
2. Hover over the list items
3. See the pointer cursor

### Actual behavior

Pointer cursor is always showing up.

### Expected behavior

Pointer cursor to only show up if the list is interactive. i.e. with selection checkbox/radio or single.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | canary  |
| Browser          |  Chrome | 
| Operating System | Windows |

### Additional context

I can see that in the past there was a class called `.mdc-list--non-interactive`. That one seems to be not
used anymore in mdc-list but is still leftover in the `mdc-drawer` (as a side note).

I think a class indicating the "interactivity" should be added by the component/foundation. Without the
component/foundation it seems to be responsibility of the user to provide the proper cursor. e.g. by using
a button as a list item instead.

**Comment by devversion** [comment]
Related: In the past this seems to have worked as expected: https://github.com/material-components/material-components-web/commit/d2f0ccbbb2dc096f2c8be5d7ef924d8ee680ba59, but https://github.com/material-components/material-components-web/commit/2553e86 removed support for it.

Any context on this? The commit/PR does not provide context.

**Comment by brandondiamond** [comment]
Closing as WAI (this feature was removed during the first refactoring of list to support better component reuse; the best workaround is to add a cursor property to the list in custom styles similar to pr/3474aaa).
