### ISSUE TITLE
ROADMAP.md not updated

### ISSUE THREAD

**Issue by matti** [material-components/material-components-web#6445]
since 2019

**Comment by jbingham** [comment]
Thanks for filing this, @matti . We have a team that's continuing to actively work on this project, adding new Material components and features, and fixing bugs. We haven't been updating the roadmap file though. We may just delete it and let people follow along with the commits and issues.

**Comment by abhiomkar** [comment]
As mentioned by @jbingham ROADMAP document is deleted in #6463 since it is outdated. Please follow along with the commits and issues for updates.

Please feel free to open an issue if you have any specific questions!
