### ISSUE TITLE
[MDCTextField] outlined and no-label variant throws error when call layout()

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#6452]
### Steps to reproduce
1. See the console logs in [this pen](https://codepen.io/Darhakexge/pen/oNxoYVY)

### Actual behavior

The outlined text field with no label variant trows this error when call `layout()`

```
Uncaught TypeError: can't access property "style", _this.notchElement_ is null
    removeNotchWidthProperty component.ts:81
    closeNotch foundation.ts:80
    closeNotch component.ts:69
    closeOutline component.ts:445
    notchOutline foundation.ts:216
    layout component.ts:358
    <anonymous> pen.js:31
component.ts:81:10
    removeNotchWidthProperty component.ts:81
    closeNotch foundation.ts:80
    closeNotch component.ts:69
    closeOutline component.ts:445
    notchOutline foundation.ts:216
    layout component.ts:358
    <anonymous> pen.js:31

```

### Expected behavior

the outlined text field with no label variant should not trows errors when call `layout()`

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |7.0.0
| Browser          |All
| Operating System |Windows 10

### Additional context

The problem is solved when I add the `.mdc-notched-outline__notch` element

**Comment by asyncLiz** [comment]
Thanks for the bug! The text field should definitely check if it _has_ a label before trying to notch the outline.
