### ISSUE TITLE
Adjust the close animation for temporary drawer

### ISSUE THREAD

**Issue by jonboj** [material-components/material-components-web#646]
### What MDC-Web Version are you using?

0.10.0

### What browser(s) is this bug affecting?

Chrome Version 58.0.3029.110 (64-bit), Firefox 53.0.2 (64-bit). Android Chrome 58

### What OS are you using?

Linux 64 bit, Android 6.0.1, Should be similar on Mac and Windows.

### What are the steps to reproduce the bug?
Open the Temporary Drawer
https://material-components-web.appspot.com/drawer/temporary-drawer.html#
Close the Drawer, e.g. with `Esc`.

### What is the expected behavior?

A close animation of around 200ms duration
https://material.io/guidelines/motion/duration-easing.html#duration-easing-common-durations

### What is the actual behavior?

A very fast close animation, almost instant. Haven't measured, but e.g. the Gmail app on Android has a much smoother and gentle close animation.

**Comment by j-o-d-o** [comment]
I am not sure this qualifies as a "Bug":

`$mdc-slidable-drawer-transition-time: .13s;
$mdc-slidable-drawer-transition-open-time: .33s;`

These are the scss variables you might be interested in.

**Comment by yeelan0319** [comment]
Hi @j-o-d-o , all MDC component have designers checked and signed off before release. However, your feedback is definitely valuable voice from the community. We will resurface the issue with designer and keep you posted!

**Comment by jonboj** [comment]
@j-o-d-o Thanks for the tip. Have tested and could tune the close duration with this.

 Have tested on other phone with better graphics performance. Of course subjective, but still the animation of the drawer on e.g. the Gmail app seems more smooth and gentle. Maybe less flickering from the opacity change. Also in the end the animation slows down and contributes to an impression that the drawer is folded under the egde. Maybe these two things contributes to an impression of a more fluent/continues animation.

 The app, that I try to build is inspired by native android apps and here the drawer is the backbone and a large part of the selections results in drawer open/close animations. So these two animations are like first and main impression of the app to the user, this is my background for putting much attention to these. Anyhow the sass variables above gives possibility to tweak.

**Comment by yeelan0319** [comment]
@j-o-d-o and @jonboj 

Designer came back after carefully review the animation, it is indeed to fast. Here are the actions we will take:
- Slow down the animation to 195ms
- Change the curve to `cubic-bezier(.4, 0, 0.6, 1)`

Here is a [prototype pen](http://s.codepen.io/yeelan0319/debug/KmbyMJ/NjMYzwWzqnzr) for after making those changes, please take a look and give your feedback. I will send out a PR regarding this later.

**Comment by jonboj** [comment]
@yeelan0319  Great! Thanks. When I try to open the attached codepen link, it seems that I am denied access, due to missing debug license. Other codepen links works with no problem e.g. the mdc-web template.
