### ISSUE TITLE
[MDCList] Add Support for Title

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web#6460]
Hi Material team,

Could you please take a look at the following ticket:
https://github.com/material-components/material-components-web-components/issues/1770

Basically, I am wondering whether it could be possible to add support for title in list, so far it is possible to add a title either by slotting an <mwc-list-item> and style it in a title way or by adding a header tag just before the list, but this does not give the nice Material feel.

So please refer to the aforementioned ticket and advice on this feature request.

Kind regards,
Alex

**Comment by asyncLiz** [comment]
This is already implemented in MDC as [list group subheaders](https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#list-groups).

I'll update the MWC issue to reflect the feature request request more accurately.
