### ISSUE TITLE
[MDCDrawer] Missing Theming Property

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web#6466]
## Bug report

The `mdc-drawer` does not export the `--mdc-theme-surface` property to allow styling the background for different theme, right now my application got a dark/light mode, but the drawer remains always white.

### Actual behavior

- Dark mode:
![image](https://user-images.githubusercontent.com/11601622/92967869-e5140e00-f471-11ea-9542-08e0cb94d7bd.png)

-Light mode:
![image](https://user-images.githubusercontent.com/11601622/92967710-a5e5bd00-f471-11ea-9c7b-28333f38f38a.png)

### Expected behavior

I would expect to explicitly set the background colour for the `mdc-drawer` so that I can adapt it to my different themes.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |
| Browser: Google Chrome: Version 85.0.4183.102 (Official Build) (64-bit)  |
| Operating System: Windows 10 Pro - latest build |

**Comment by asyncLiz** [comment]
`prop-value()` needs to be removed from the following areas upstream to expose the `--mdc-theme-surface` custom property:

- [variables.$surface-fill-color](https://github.com/material-components/material-components-web/blob/fc0eb5013603a4d5cb4dbc0a999e94df64cc5005/packages/mdc-drawer/_variables.scss#L31)
- [surface-fill-color() mixin](https://github.com/material-components/material-components-web/blob/fc0eb5013603a4d5cb4dbc0a999e94df64cc5005/packages/mdc-drawer/_mixins.scss#L410)
