### ISSUE TITLE
[MDCDrawer] Drawer Header Logo Branding

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web#6471]
## Feature Request

I would like to be able to include the logo branding - in accordance with the MD best design practices - of a company in the `MDCDrawer` -> `header` section.

### Proposed solution

Adding a logo/branding slot to `MDCDrawer`. Something like:

![image](https://user-images.githubusercontent.com/11601622/93017306-6f1dbd00-f5bf-11ea-9922-ce840a58d0bf.png)

The logo could also be left-aligned to the text instead of right-aligned, for example:

![image](https://user-images.githubusercontent.com/11601622/93017375-1569c280-f5c0-11ea-8089-b79a20d3486d.png)

**Comment by patrickrodee** [comment]
Hey Alexandre, thanks for filing this issue. While the feature you're requesting is not part of the Material Design spec, you should be able to accomplish this yourself.

Let me know if you have any questions!
