### ISSUE TITLE
[MDCDrawer | MDCList] Dropdown/Nested List Documentation

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web#6472]
## Feature Request

I am in the process of implementing my `MDCDrawer` for responsive navigation and I am finding myself struggling with the implementing of a dropdown list for sub-pages.

As far as I know, the process consists in implementing nested `MDCLists`, however the styling of the animations will not be consistent with the `Material Design` specs if implemented by myself. And to be honest, I am bumping into a lot of issues when trying to implement it myself 😅.

![image](https://user-images.githubusercontent.com/11601622/93017452-d25c1f00-f5c0-11ea-9d6d-dca61dd0be83.png)

### Proposed solution

Drop down/nested `MDCLists` for `MDCDrawer` navigation is one of the most common designing pattern/use cases. Therefore, to simplify the life of hobbyist devs such as myself, I would really appreciate if you could add to the `MWC/MDC` documentation the optimal way of implementing it.

**Comment by patrickrodee** [comment]
Hey Alexandre. We currently do not support expandable list items but we'll update the docs when we do. That work is currently not on the roadmap. Let me know if you have any questions.

**Comment by aress31** [comment]
@patrickrodee a work around would be to use nested list with some `CSS` to hide/show the nested list and rotate the trailing icon. In the meantime could you please consider updating the doc of `mwc-list` to show how to do?
