### ISSUE TITLE
MdcSwitch title

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#6474]
Is `role="switch"` a valid value of the role attribute?
Please see https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch#switch-example and https://www.w3.org/WAI/PF/HTML/wiki/RoleAttribute.

Many thanks.

**Comment by asyncLiz** [comment]
Yes, it is an ARIA 1.1 attribute value.

https://www.w3.org/TR/wai-aria-1.1/#switch
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role

**Comment by simonziegler** [comment]
Many thanks!
