### ISSUE TITLE
Version 0.11.0 cannot be imported

### ISSUE THREAD

**Issue by anton-kachurin** [material-components/material-components-web#650]
### What MDC-Web Version are you using?

0.11.0

### What are the steps to reproduce the bug?

1. Install MDC-Web:
```sh
npm i material-components-web
```

2. Import the library:
```javascript
import * as mdc from 'material-components-web';
```
### What is the expected behavior?

Should produce no errors.

### What is the actual behavior?

```
Error: Cannot find module "../../../packages/mdc-animation" at webpack:///~/@material/tabs/tab-bar/foundation.js:18:0
```

### Any other information you believe would be useful?

It is caused by improper import of the `@material/animation` module. This type of errors seriously affects the ability of the third-party developers to update MDC-Web to the latest version.

Can we think of a way how to incorporate checking of this behavior before the release?

**Comment by traviskaufman** [comment]
I'm adding a `pretest` script today to prevent this from ever happening again
