### ISSUE TITLE
upcoming release?

### ISSUE THREAD

**Issue by cintaccs** [material-components/material-components-web#6519]
Hi,
Sorry for making an "issue" on this topic - however I believe we are a lot of developers using your work on the material components that would appreciate all the fixes and improvements that have been done for a long time... (release 7.0.0 is more than 3 months ago - and I watch daily changes to this repo....). Before we get too many breaking changes .... is there any plan to release any time soon? Also the lack of a Roadmap document... are there any updates to where we are heading ... or would you recommend looking elsewhere for material components work... (I don't want to be indicating anything negative here - I appreciate the work you do - but wonders how much external releases and use is being prioritised - not a complain - just trying to get information). Thanks for the work and efforts your are doing!!
Best regards!

**Comment by cintaccs** [comment]
Sorry for the inconvenience - but can't we get some sort of reaction to this question after 3+ weeks? (not a complain but worried about heavily depending on a repository that have this note on the main page:

"We typically follow a 2-week release schedule which includes one major release per month with breaking changes, and intermediate patch releases with bug fixes."

please...?

**Comment by abhiomkar** [comment]
Hi @cintaccs -- Thanks for the question! We're scheduling a major release (`v8.0.0`) on next week Monday, November 2nd.

In the meantime please feel free to use `canary` releases for testing. We push to `canary` tag on every commit to master branch.

We're continuing to actively work on this project, adding new Material components and features, and fixing bugs. You can watch this repository for further updates.

Please let me know if you've any questions!

**Comment by cintaccs** [comment]
Hi @abhiomkar,
Thanks a million for clarifying! - I already to ```canary``` a while ago ... :-) 
Good to hear that you keep at it!
Thanks!!!
