### ISSUE TITLE
Breakpoint for 1280 – 1439

### ISSUE THREAD

**Issue by userconcept** [material-components/material-components-web#6527]
Hi!
I like your design system and base my projects on your recommendations, especially I like your spacing methods based on 4/8... etc numbers, because I use only percents and rems units with html font-size: 100%; (16px by default in most browsers). When I change font-size for html (root element) on breakpoint for largest screen (@media min-width: 1600px - font-size: 1vw;) this works great, website is responsive for 4K, 8K and more. But I don't understand one moment. In your recommendations - breakpoint for 1280px specified for large tablet, but many people have 1366px monitor, and 1280px with 12 columns don't have full pixels in each of them (1280 / 12 = 106.666666667). Maybe it's more logical to do breakpoint for 1200px ?

**Comment by joyzhong** [comment]
Hi there, thanks for the feedback! Unfortunately we don't currently have a process for funneling external design feedback to our UX team, so I'll need to close this, as it's not an implementation bug or component feature request.
