### ISSUE TITLE
[Dialog] Demo page crashes on Safari

### ISSUE THREAD

**Issue by jpic** [material-components/material-components-web#6528]
Hello !

A safari user has reported the modal crashes Safari on https://oss.yourlabs.me/autocomplete-light/

We're using the same scripts as your dialog demo page, I asked the user if they could reproduce on https://material-components.github.io/material-components-web-components/demos/dialog/

They said yes indeed.

I'm sorry but I have no more to offer (I run Linux without Safari)

Have a great day

**Comment by joyzhong** [comment]
Hi there, did you mean to file this in https://github.com/material-components/material-components-web-components?

**Comment by joyzhong** [comment]
Closing, as this is not an MDC bug.

**Comment by jpic** [comment]
Thank you for your notification, this is open on https://github.com/material-components/material-components-web-components/issues/1907
