### ISSUE TITLE
Compile problem in phpstorm

### ISSUE THREAD

**Issue by danialbakhtiari3884** [material-components/material-components-web#6534]
Hello, do not be tired

I want to do the compilation with phpstorm, but it gets in trouble, does anyone know how to help?

![image](https://user-images.githubusercontent.com/72765801/96041641-ff7a4680-0e78-11eb-9f5e-34733866153e.png)

![image](https://user-images.githubusercontent.com/72765801/96041719-1d47ab80-0e79-11eb-8349-e3fe9f476e57.png)

**Comment by joyzhong** [comment]
Hi there, unfortunately I'm not familiar with your installation setup and workflow. I'd recommend reading through the [installation docs](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#getting-started) or asking a StackOverflow question for phpstorm users. Thanks.
