### ISSUE TITLE
mwc-textfield  type="date or datetime_local" do not show label when included inside mwc-dialog

### ISSUE THREAD

**Issue by adinkes** [material-components/material-components-web#6544]
<mwc-dialog>
     <mwc-textfield type="date" label="SHOW THIS LABEL"></mwc-textfield>
</mwc-dialog>
the label is not displayed

**Comment by allan-chen** [comment]
Please file this in the [MWC repo](https://github.com/material-components/material-components-web-components) with preferably a jsbin/codepen example.
