### ISSUE TITLE
Question: best practice calling "init" and "destroy"

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#6547]
## Feature Request
This is a best practice question rather than a feature request. I'm one of the owners of a open source library called [Material.Blazor](https://material-blazor.com), applying material-components-web to the ASP.NET Blazor framework. We call `init()` for all of our components but have not used `destroy()`. We don't see `destroy()` referenced much in your documentation and would like to know what you consider to be best practice.

For instance will we have a memory leak if we fail to call `destroy()`? If so, we have some coding to do!

Many thanks,  Simon

**Comment by allan-chen** [comment]
Hey Simon,

Destroy is mainly used to deregister event listeners, which can pile up if there's a lot of components cycling through the page.  It's best practice to call destroy as elements are removed from the DOM. Removing references to the element/component removed will also [cause GC to happen](https://stackoverflow.com/a/12528067) but calling `destroy()` is arguably more explicit.

**Comment by simonziegler** [comment]
Hey Allan, thanks again for a super speedy reply. We thought this might be the case. I'll add it to our project issues to resolve.

Cheers!

**Comment by simonziegler** [comment]
Hi Allan, we just had an issue related to this crop up for the [Material.Blazor](https://github.com/Material-Blazor/Material.Blazor) project, which integrates material-components-web into ASP.NET Blazor. We find that individual calls to SJ functionality from C# can be expensive, so we have started to batch them together in 20ms chunks.

A consequence of this is that when we are alerted by ASP.NET of a component being disposed, the delay introduced by batching means that we try to call `destroy()` once ASP.NET has already removed the element from the DOM.

We are now wondering whether we (i) need to put in some effort to detect when an item is about to be removed from the DOM with some kind of JS listener (we don't know how to do this), or (ii) should stop calling `destroy()`. You said in October that using it is best practice, however are there any circumstances when it is strictly necessary? For instance we don't have any globally referenced listeners that could go stale.

Thanks, Simon
