### ISSUE TITLE
[mdc-select] (v4.0.0) Outlined select not displaying

### ISSUE THREAD

**Issue by dimitri-luno** [material-components/material-components-web#6558]
### Steps to reproduce
Codepen: https://codepen.io/dimitri-luno/pen/gOMoNwE

### Actual behavior
The select is not displaying 

### Expected behavior
Expect it to look something like this: 
<img width="317" alt="" src="https://camo.githubusercontent.com/9f6263e5c1cf36c89433e6f2dbea00315f3bb539/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563663935373532326534666534363931643766303866302f65343635626334372d613235322d346438662d613364612d393364613333613164383632">

### Screenshots
<img width="317" alt="Screenshot 2020-10-28 at 13 34 07" src="https://user-images.githubusercontent.com/49513132/97431003-5aed0f80-1922-11eb-9084-8a8fce2f2fab.png">

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 4.0.0 |
| Browser          | Chrome  86 |
| Operating System | macOS 10.15.7 |

### Additional context
```html
<div class="mdc-select mdc-select--outlined mdc-select--with-leading-icon language-select">
  <div class="mdc-select__anchor">
    <div class="mdc-notched-outline mdc-notched-outline--upgraded">
      <div class="mdc-notched-outline__leading"></div>
      <div class="mdc-notched-outline__notch">
        <div id="language-selected-text" class="mdc-select__selected-text" role="button" aria-haspopup="listbox" aria-labelledby="language-select-label language-selected-text" tabindex="0" aria-disabled="false">
        </div>
        <label id="language-select-label" class="mdc-floating-label" style="">
          Language
        </label>
        <i class="material-icons mdc-select__icon" tabindex="0" role="button"></i>
      </div>
      <div class="mdc-notched-outline__trailing"></div>
    </div>
  </div>
  <div class="mdc-select__menu mdc-menu mdc-menu-surface language-select" role="listbox">
    <ul class="mdc-list">

      <li class="mdc-list-item" data-value="/en/" role="option" tabindex="-1">
        <span class="mdc-list-item__graphic">
          <img src="/static/icons/languages/en.png" alt="English flag icon">
        </span>
        <span class="mdc-list-item__text">English</span>
      </li>

      <li class="mdc-list-item" data-value="/fr/" role="option" tabindex="-1">
        <span class="mdc-list-item__graphic">
          <img src="/static/icons/languages/fr.png" alt="Français flag icon">
        </span>
        <span class="mdc-list-item__text">Français</span>
      </li>

      <li class="mdc-list-item" data-value="/id/" role="option" tabindex="-1">
        <span class="mdc-list-item__ripple"></span>
        <span class="mdc-list-item__graphic">
          <img src="/static/icons/languages/id.png" alt="Indonesia flag icon">
        </span>
        <span class="mdc-list-item__text">Indonesian</span>
      </li>

      <li class="mdc-list-item" data-value="/it/" role="option" tabindex="-1">
        <span class="mdc-list-item__graphic">
          <img src="/static/icons/languages/it.png" alt="Italiano flag icon">
        </span>
        <span class="mdc-list-item__text">Italiano</span>
      </li>
    </ul>
  </div>
</div>
```

**Comment by sayris** [comment]
Hi! 

Seems like your HTML is a little off. Specifically:
- The leading icon is not specified (needs to put a string between the `<i>` tags to specify which icon should be rendered)
- The icon element is in the wrong place, it should come after the `.mdc-notched-outline` element
-  Not sure the purpose of the `#language-selected-text` div, the fact that its given the `.mdc-select__selected-text` class (which is expected elsewhere) is also likely throwing things off. 
- The `.mdc-notched-outline__trailing` div is also misplaced. 

Check out https://codepen.io/shws/pen/oNLEray for the adjusted html.

Thanks!

**Comment by dimitri-luno** [comment]
Thank you @sayris !
