### ISSUE TITLE
Change Log Missing for v8.0.0

### ISSUE THREAD

**Issue by mikail-khan** [material-components/material-components-web#6572]
Simple request, can one be added please.

**Comment by abhiomkar** [comment]
Hi @mikail-khan -- You can find `v8.0.0` changelog (and any future version's changelogs) in [./CHANGELOG.md](https://github.com/material-components/material-components-web/blob/v8.0.0/CHANGELOG.md#800-2020-11-02) file located at root folder.

Let me know if you've any questions!
