### ISSUE TITLE
[Shape] SassError: (varname: --mdc-shape-small, fallback: 4px) isn't a valid CSS value

### ISSUE THREAD

**Issue by devslyfox** [material-components/material-components-web#6573]
### Steps to reproduce
Hello!
Use scss file.
Set MyComponent in scss file

```
.mdc-drawer .mdc-list-item {
    // @include shape.radius(large);
    border-radius: shape.resolve-radius(large);
}

```
Work
`@include shape.radius(large);`
Does not work
`border-radius: shape.resolve-radius(large);`
I get the error:
SassError: (varname: --mdc-shape-large, fallback: 0) isn't a valid CSS value.
   ╷
12 │     border-radius: shape.resolve-radius(large);
   │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  my-components.scss 12:20  root stylesheet

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 8.0.0
| Browser          | Opera
| Operating System | Windows

**Comment by abhiomkar** [comment]
Can you please share a demo to investigate the issue?

This happens mostly because of version mismatch. Make sure all MDC components are upgraded to `v8.0.0`.

**Comment by devslyfox** [comment]
I installed the components one week ago. The most recent version v8.0.0.
I don't use now:
```
.mdc-drawer .mdc-list-item {
    // @include shape.radius(large);
    border-radius: shape.resolve-radius(large);
}
```
Change on:
```
.mdc-drawer {
    @include drawer.item-shape-radius(large);
```
And I try to use them.
I put it according to the Getting Started instructions.
P/S
The instructions need to be updated.
Remove:
`{
  loader: 'postcss-loader',
  options: {
     plugins: () => [autoprefixer()]
  }
},`
Change
```
{
    loader: 'postcss-loader',
    options: {
        postcssOptions: {
            plugins: () => [autoprefixer()]
        },
    },
},
```
And Remove:
```
{
  test: /\.js$/,
  loader: 'babel-loader',
  query: {
    presets: ['@babel/preset-env'],
  },
}
```
Change on:
```
{
    test: /\.js$/,
    loader: 'babel-loader',
    options: {
        presets: ['@babel/preset-env']
    }
}
```
