### ISSUE TITLE
[README demo website] Glitch project is broken

### ISSUE THREAD

**Issue by w-b-dev** [material-components/material-components-web#6575]
#6411  Bug report

The Glitch demo project is broken

### Steps to reproduce
1. Go to https://glitch.com/~mdc-web-quick-start
2. See error

### Actual behavior
Error page

### Expected behavior
Should not error

### Screenshots
![image](https://user-images.githubusercontent.com/18291038/98163898-6eafed00-1eb1-11eb-9ea1-5dce8a1f50c9.png)

### Your Environment:

n/a

**Comment by abhiomkar** [comment]
`~mdc-web-quick-start` demo is outdated. Please use [~new-web](https://glitch.com/edit/#!/remix/new-web) instead.

Sent a fix (PR #6576) to our docs to update the demo link.
