### ISSUE TITLE
Error text on Text fields

### ISSUE THREAD

**Issue by rafalou38** [material-components/material-components-web#6581]
Expected behavior
<img src="https://lh3.googleusercontent.com/DNHVc4J4YEXhTy3cV4-5xGWAC-Foy4jHKTx7gmM7F6WzSPAeTlfHP31W6von4b-IXEFwc9Y_lHDMOynwCTHN-ErRsrcN0DvLNbhMG1w=w1064-v0">
curently:
<img src="https://res.cloudinary.com/dr844cxrp/image/upload/v1604600518/Capture_d_%C3%A9cran_2020-11-05_202054_v0jqy4.png">

**Comment by EstebanG23** [comment]
Hi there just to confirm, your request is for the "Error message" labeled with the number 2 correct?

MDC Textfield does support [helper text](https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/README.md#text-field-with-helper-text) that can act as a validation message. [These](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield/helper-text#css-classes) are some css classes that you can add to the helper text to either make it persistent or act as an error message. 

Please let me know if this helps or if you have any questions.

**Comment by rafalou38** [comment]
Yes it was for that I just hoped there was going to be an automatic way just with HTML and something that says when you leave it empty with different error message

**Comment by EstebanG23** [comment]
Changing the helperText with just HTML is not supported however you can adjust the helpertext content using JS with the MDC Textfield property [helperTextContent](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#mdctextfield-properties-and-methods).

**Comment by EstebanG23** [comment]
Something worth pointing out is that [Material Web Components](https://github.com/material-components/material-components-web-components) does have a textfield that has separate `helper` and `validationMessage` [properties](https://github.com/material-components/material-components-web-components/tree/master/packages/textfield#propertiesattributes) that may help with your use case.
