### ISSUE TITLE
Toolbar ratio calculation not updated on resize

### ISSUE THREAD

**Issue by mhuebert** [material-components/material-components-web#659]
The Toolbar foundation sets calculations.toolbarRatio once, on init: 

https://github.com/material-components/material-components-web/blob/master/packages/mdc-toolbar/foundation.js#L167

But this ratio depends on the toolbarRowHeight, which changes on resize: 

https://github.com/material-components/material-components-web/blob/master/packages/mdc-toolbar/foundation.js#L124

The ratio is not updated, however. This means that if you resize the window and cross a threshold such that the toolbarRowHeight changes, the ratio is no longer correct, and an incorrect margin is applied to the sibling element.

I believe this would be a simple fix, by adding 
```js
this.calculations_.toolbarRatio = this.adapter_.getOffsetHeight() / newToolbarRowHeight;
```
after line 124.

**Comment by traviskaufman** [comment]
Thanks for the PR @mhuebert! Left some comments there 😄

**Comment by mhuebert** [comment]
@traviskaufman thanks for the comments! I just submitted PR #697, which includes a test and also conforms to expected commit message format.
