### ISSUE TITLE
[TextField] Disappear cursor i beam on safari

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#6590]
Disappear cursor i beam on safari

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 8.0
| Browser          | Safari 14.0
| Operating System | macOS 10.15.6

#### Chrome
![Screen Shot 2020-11-08 at 2 33 22 PM](https://user-images.githubusercontent.com/39903550/98458904-49342380-21d0-11eb-8709-5cb1113372f7.png)

#### Safari
![Screen Shot 2020-11-08 at 2 33 37 PM](https://user-images.githubusercontent.com/39903550/98458908-4c2f1400-21d0-11eb-89d2-ebd7dac4c5fa.png)

**Comment by FryingggPannn** [comment]
Are you sure this is from MDC Web? It doesn't have an underlined variant for text fields.

**Comment by joyzhong** [comment]
Closing, as these don't seem to be MDC web textfields: https://material-components.github.io/material-components-web-catalog/#/component/text-field
