### ISSUE TITLE
mdc-select and mdc-textfield alignment issues - 8.0.0

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#6601]
## Bug report
Upgrading a project from version 7.0.0 to 8.0.0 shows some misalignment issues in selects and text fields:

- Filled selects with density of minus 2 and below vertically misalign selected text (due to missing adjustment when floating label is hidden?)
- Outlined selects and text fields misalign text and floating labels when border radius is set to zero in a custom theme

I believe that these issues are due to changes from the version upgrade rather than my code - do please let me know if I'm wrong!

Many thanks, Simon

### Steps to reproduce
1. Visit https://simonziegler.github.io/MaterialSelects/ for a demonstration
2. Code for this demo is at https://github.com/simonziegler/MaterialSelects

### Actual behavior
Please see demo from step 1 above

### Expected behavior
Regular/expected alignment should be observed - none of these issues existed in version 7.0.0.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 8.0.0 |
| Browser          | Any |
| Operating System | Windows 10 |

**Comment by simonziegler** [comment]
Hi,is there any further info you think I can help you with?

**Comment by allan-chen** [comment]
Hi Simon,

Looking at your generated css, there's no sign of the `mdc-select__selected-text-container` class anywhere. This indicates that your Sass may not be updated to the latest version, since that class should exist in the baseline styles, even without any customizations. Could you double check that your stylesheet is built from the latest version?

**Comment by simonziegler** [comment]
Let me check for that Allan. I'll report back in a few days.

**Comment by simonziegler** [comment]
@joyzhong I need a few more days to get to this - I'm crazily busy with work for a bit. Please bear with me!

**Comment by simonziegler** [comment]
@allan-chen I've had an opportunity to update the CSS which now includes `mdc-select__selected-text-container` - I don't know what went wrong with my build before. However unfortunately this hasn't had any impact on the issue which remains live.

**Comment by allan-chen** [comment]
Hey Simon,

Please try setting the shape radii variable to `0px` instead of `0`. Essentially there's some machinery involving `width: max(12px, var(--mdc-shape-small, 0))` which resolves to invalid CSS `width: max(12px, 0)` if 0 is used.

**Comment by simonziegler** [comment]
Hey Allan, that fixed the issue. Thanks so much!
