### ISSUE TITLE
MDC Dialog does not have 8dp padding between side-by-side buttons

### ISSUE THREAD

**Issue by robzenn92** [material-components/material-components-web#661]
### What MDC-Web Version are you using?

0.11.1

### What browser(s) is this bug affecting?

I tried with Safari 10.1.1 and Firefox 53.0.2 but I think it does happen in all of them.

### What OS are you using?

macOS Sierra 10.12.5

### What are the steps to reproduce the bug?

Open http://localhost:8080/dialog.html or visit the [demo](http://material-components-web.appspot.com/dialog.html) page

### What is the expected behavior?

As described in the [Material Design guidelines](https://material.io/guidelines/components/dialogs.html#dialogs-specs), dialogs should have 8dp padding between side-by-side buttons.

<img width="376" alt="specs" src="https://cloud.githubusercontent.com/assets/3225625/26161682/e00a7430-3b24-11e7-9c41-e96c35ae0b16.png">

### What is the actual behavior?

Dialogs do not have 8dp padding between side-by-side buttons.

<img width="581" alt="dialog" src="https://cloud.githubusercontent.com/assets/3225625/26161586/a1539776-3b24-11e7-8da7-8df7b44fc337.png">

### Any other information you believe would be useful?

Thank you for your hard work and commitment! Amazing stuff! :pray:

**Comment by Garbee** [comment]
That should be *margin* not *padding*.

**Comment by robzenn92** [comment]
I agree, but I kept the same naming convention written in the [Material Design guidelines](https://material.io/guidelines/components/dialogs.html#dialogs-specs): "Button width and padding":

> Button height: 36dp
Minimum button width: 64dp
Internal button padding: 8dp
Padding between buttons: 8dp

**Comment by traviskaufman** [comment]
Good catch @robzenn92 ! Marking this as "help wanted" as the fix is relatively straightforward:

- [ ] Within the [&__footer selector](https://github.com/material-components/material-components-web/blob/master/packages/mdc-dialog/mdc-dialog.scss#L128) add the following:

```scss
&__button {
  margin-right: 8px;
  
  &:last-child {
    margin-right: 0;
  }
}
```

If stylelint complains that the above declarations cause too many levels of nesting, feel free to flatten it out.
