### ISSUE TITLE
"Card collections" should be implemented

### ISSUE THREAD

**Issue by teohhanhui** [material-components/material-components-web#6615]
## Feature Request
"Card collections" should be implemented

### Proposed solution
https://material.io/components/cards#card-collections

### Alternatives considered
N/A

### Additional context
N/A

**Comment by joyzhong** [comment]
Hi there, thanks for filing this FR! We do not intend on implementing card collections at this time as historically, our layout utilities have been underused and requirements may vary widely based on the needs of your application. However, you can use flexbox or grid layout to achieve the specced design.
