### ISSUE TITLE
[MDCButton] html validator error:  Element div not allowed as child of element button in this context

### ISSUE THREAD

**Issue by achinchen** [material-components/material-components-web#6620]
## Bug report
Got Error by using w3c html validator to test HTML structure.

I followed the HTML structure which was mentioned on [MDCButton Doc](https://material.io/develop/web/components/buttons#-buttons-accessible), but it caused this issue `Element div not allowed as child of element button in this context`.

### Steps to reproduce
Copy the code down below into [w3c validator](https://validator.w3.org/nu/) check option textarea.
```html
<h5 class="mdc-typography mdc-typography--headline5 demo-headline">MDC Button Issue</h5>

<section>
  <h6 class="mdc-typography mdc-typography--headline6">This one will not pass html-validator,
    due to block element "div" inside inline element "button"</h6>
  <button class="mdc-button greet-button">
    <div class="mdc-button__ripple"></div>
    <div class="mdc-button__label">Greet</div>
    <div class="mdc-button__touch"></div>
  </button>
</section>

<section>
  <h6 class="mdc-typography mdc-typography--headline6">This one will pass html-validator</h6>
  <button class="mdc-button greet-button">
    <span class="mdc-button__ripple"></span>
    <span class="mdc-button__label">Greet</span>
    <span class="mdc-button__touch"></span>
  </button>
```
### Actual behavior
The html structure referred in document caused HTML validator issue. 

### Expected behavior
Dom of UX enhancement shouldn't cause structure error.

### Screenshots
![image](https://user-images.githubusercontent.com/40432044/99210481-deeb3680-2800-11eb-92b4-8e4e4bebf892.png)

### Your Environment:
It's not associated environment.

### Possible solution
Update document.
If the solution I referred above is accepted, I'm happy to make PR to update it.

**Comment by brandondiamond** [comment]
Thanks for your bug report! You're definitely correct -- button should only contain "phrasing content". We do apply "display: inline" to the DIV, which avoids issues (validation aside). But there's no reason for us to use `<div />` in the examples when a `<span />` works better and is valid markup.

We'd greatly appreciate your help with a PR updating the DIVs in the README.
