### ISSUE TITLE
Tooltip has extraneous TypeScript modules when resolved by NPM

### ISSUE THREAD

**Issue by MarkStega** [material-components/material-components-web#6629]
## Bug report
After you install material components web with a devDependency of "material-components-web": "8.0.0",
the @material\tooltip directory has some extraneous TS files. Namely adapter.ts, index.ts, and types.ts. None of the other components have tese files.

### Steps to reproduce
1. Simply do an npm install with the aforementioned devDependency and examine the resultant tooltip component

### Actual behavior
Extraneous TS files

### Expected behavior
Follow behavior of other components

### Your Environment:
Node 14.15.0
Npm 6.14.8
Windows 10 x64 Professional
MDC Web 8.0.0

**Comment by brandondiamond** [comment]
Thanks for flagging this, Mark! I'll reach out to that component's developer to investigate.
