### ISSUE TITLE
Problem setting up using terminal

### ISSUE THREAD

**Issue by davy440** [material-components/material-components-web#6636]
Hello all,
I am trying to setup the working environment for material design and I'm stuck at the **Getting Started** stage.
I'm following the steps as mentioned in [this](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) page. The problem i'm facing is starting the webpack-dev-server. The command `npm start` runs into error.

These are the dependencies - 
   ```
 "css-loader": "^5.0.1",
    "extract-loader": "^5.1.0",
    "file-loader": "^6.2.0",
    "sass": "^1.29.0",
    "sass-loader": "^10.1.0",
    "webpack": "^4.44.2",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "^3.11.0"
```
The terminal throws the error as shown in the following image -

<img width="961" alt="Screen Shot 2020-11-20 at 11 45 07 PM" src="https://user-images.githubusercontent.com/8796717/99835693-f7ee4180-2b8a-11eb-8ab3-6c8930d2e3f5.png">
image.

What's the deal with this? This seems like some version compatibility issue but I can't get my head around it.
Some help in the right direction would be really appreciated!

**Comment by joyzhong** [comment]
Fixed in https://github.com/material-components/material-components-web/pull/6679
