### ISSUE TITLE
Edge: Text Field issue

### ISSUE THREAD

**Issue by djensen47** [material-components/material-components-web#664]
When using/testing mdc-web on the demo site, there seems to be an issue with the text field.

### What MDC-Web Version are you using?

0.11.1 via this page:
https://material-components-web.appspot.com/

### What browser(s) is this bug affecting?

Microsoft Edge 41.16193.1001.0

### What OS are you using?

Windows 10 Build 16193

### What are the steps to reproduce the bug?

Open Edge to https://material-components-web.appspot.com/textfield.html and click inside of a text field and start typing.

### What is the expected behavior?

It behaves normally.

### What is the actual behavior?
The background turns black.

![text-field-edge](https://cloud.githubusercontent.com/assets/527865/26179863/d1f588b2-3b1a-11e7-817b-85486b634fce.gif)

**Comment by kbrownhbs** [comment]
I have been seeing the same issue in Edge as well.  I'm using version  40.15063.0.0

**Comment by KayvandenHeuvel** [comment]
We are using MDC version 0.16 and we still have this problem. Checkboxes & radio buttons got the same problem.

I think it has something to do with the ::after elements that are set.

**Comment by Derekjohnson277** [comment]
Any workarounds or solutions?

**Comment by dpraul** [comment]
Running MDC v0.17.0 on Edge 40.15063.0.0. Can reproduce this problem on text fields, checkboxes, radio buttons, and CSS-only tabs.

**Comment by jordyboytjuh** [comment]
Same issues over here. MDC components in Edge are very buggy. Hope some bugfixes will resolve this.

**Comment by Kerrick** [comment]
We're also seeing the same issue [here](https://secondstreet.github.io/ember-material-components-web/), for EdgeHTML 15.15.063 / Edge 40.15063.0.0, including radio buttons and checkboxes.
