### ISSUE TITLE
[mdc-slider] The disabled slider demo in the README.md is incorrect

### ISSUE THREAD

**Issue by wagnermaciel** [material-components/material-components-web#6649]
## Bug report

The [mdc-slider README.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/README.md#disabled-slider) states:

> To disable a slider, add the following:
> 
> *   mdc-slider--disabled class on the root element
> *   tabindex="-1" attribute on the thumb(s)
> *   aria-disabled="true" on the thumb(s)

But the html example does not set the tabindex to -1 or aria-disabled to true.

> ```html
> <div class="mdc-slider mdc-slider--disabled">
>   <input class="mdc-slider__input" type="range" min="0" max="100" value="50" step="10" disabled name="volume" aria-label="Disabled slider demo">
>   <div class="mdc-slider__track">
>     <div class="mdc-slider__track--inactive"></div>
>     <div class="mdc-slider__track--active">
>       <div class="mdc-slider__track--active_fill"></div>
>     </div>
>   </div>
>   <div class="mdc-slider__thumb">
>     <div class="mdc-slider__thumb-knob"></div>
>   </div>
> </div>
> ```

**Comment by abhiomkar** [comment]
Thanks @wagnermaciel for creating the issue! Please feel free to send us a CL (Reviewer: @joyzhong )

**Comment by joyzhong** [comment]
Fixed in https://github.com/material-components/material-components-web/pull/6651
