### ISSUE TITLE
MDC-checkbox custom size

### ISSUE THREAD

**Issue by jimyhdolores** [material-components/material-components-web#6655]
Hi, is there a way to change the height and width of the checkboxes?

version:
"material-components-web": "^8.0.0"

**Comment by joyzhong** [comment]
There is no supported mixin for changing the height/width of the checkbox, but see the [density mixin](https://github.com/material-components/material-components-web/blob/master/packages/mdc-checkbox/README.md#sass-mixins) to adjust the checkbox's ripple size.
