### ISSUE TITLE
mdc-select add external, non floating label

### ISSUE THREAD

**Issue by lpoulter** [material-components/material-components-web#6672]
It would be great if you could set an label external to the select menu.      
Something like this, and if you click the "select a project" label the dropdown opens. More like a native label/input combo.

![Screenshot 2020-12-04 at 17 43 20](https://user-images.githubusercontent.com/3940567/101196313-7b626500-3658-11eb-91f2-3eed6777df08.png)

```
      <label id="outlined-select-label" for="demo-selected-text"><p>Select a project</p></label>
      <div class="mdc-select mdc-select--outlined">
        <div class="mdc-select__anchor" aria-labelledby="outlined-select-label">
          <span class="mdc-notched-outline">
            <span class="mdc-notched-outline__leading"></span>
            <span class="mdc-notched-outline__trailing"></span>
          </span>
```

**Comment by joyzhong** [comment]
Hi there, thank you for filing this request. However, since our implementation is heavily based on the [Material Design spec](https://material.io/components/menus), which does not include an external label, this is not likely a feature our team will add to our roadmap.
