### ISSUE TITLE
[SegmentedButton] Namespace collision

### ISSUE THREAD

**Issue by m-alzam** [material-components/material-components-web#6680]
## Bug report

There's a namespace collision for stylesheets:

### Steps to reproduce
Import the following two modules in the same file:

```scss
@use "@material/tooltip/styles";
@use '@material/segmented-button/styles';
```

You get the following error:

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: There's already a module with namespace "styles".
    ╷
11  │ @use "@material/tooltip/styles";
    │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original @use
... │
13  │ @use '@material/segmented-button/styles';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ new @use
    ╵
```

### Actual behavior

I can't import both stylesheets in the same file

### Expected behavior

I can import both stylesheets in the same file

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |8.0.0
| Operating System |Arch Linux

### Additional context
Similar errors:

- https://github.com/material-components/material-components-web/issues/6598#issuecomment-725878477

### Possible solution

- The docs should be updated to use the same approach in all the components.
- You can use the following solution in the docs: https://github.com/sass/sass/issues/2778#issuecomment-558365532

**Comment by joyzhong** [comment]
Please use the workaround solution in https://github.com/sass/sass/issues/2778#issuecomment-558365532.
