### ISSUE TITLE
A bug with initialization

### ISSUE THREAD

**Issue by alexjelin2100** [material-components/material-components-web#6685]
Hello to everyone !

I have a issue with my site and MDCSlider. 
I used on my site two mdc sliders who is working but before 2 weeks, the sliders are broken. I used this link to import the library:
https://unpkg.com/material-components-web@8.0.0/dist/material-components-web.min.js.

The error is : Uncaught Error: MDCSliderFoundation: `aria-valuemin` must be non-null. and the site is throw the error after this line:
mdc.autoInit();

My html structure for two sliders is:
```
<div id="sslider" class="mdc-slider mdc-slider--discrete" tabindex="0" role="slider" aria-label="Select Value" data-mdc-auto-init="MDCSlider">
                                <div class="mdc-slider__track-container">
                                    <div class="mdc-slider__track"></div>
                                </div>
                                <div class="mdc-slider__thumb-container">
                                    <div class="mdc-slider__pin">
                                        <span class="mdc-slider__pin-value-marker">200</span>
                                    </div>
                                    <svg class="mdc-slider__thumb" width="21" height="21">
                                        <circle cx="10.5" cy="10.5" r="7.875"></circle>
                                    </svg>
                                    <div class="mdc-slider__focus-ring"></div>
                                </div>
                            `</div>`
```

------------------------------------------------

```
<div id="pslider" class="mdc-slider mdc-slider--discrete" tabindex="0" role="slider" aria-valuemin="3" aria-valuemax="18" aria-valuenow="0" aria-label="Select Value" data-mdc-auto-init="MDCSlider">
                                <div class="mdc-slider__track-container">
                                    <div class="mdc-slider__track"></div>
                                </div>
                                <div class="mdc-slider__thumb-container">
                                    <div class="mdc-slider__pin">
                                        <span class="mdc-slider__pin-value-marker">3</span>
                                    </div>
                                    <svg class="mdc-slider__thumb" width="21" height="21">
                                        <circle cx="10.5" cy="10.5" r="7.875"></circle>
                                    </svg>
                                    <div class="mdc-slider__focus-ring"></div>
                                </div>
                            </div>

```
I would be very grateful if you could help me with this problem!

**Comment by joyzhong** [comment]
Hi there! We've actually updated the slider recently to conform to the Material spec, add the range slider feature, and with improved accessibility. Please see https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/README.md for the new markup.

Unfortunately the changes are not yet included in our most recent release. I will work on pushing out a new release in the upcoming week.

**Comment by nalin** [comment]
Could you provide examples of how to make this work? Where are these attributes needed? Adding them to the input element doesn't seem to stop the issue.

**Comment by johnhelmuth** [comment]
I am also running into this issue.  I dug a little deeper into the source code, and found that this path has some details that seem to apply to this issue, as opposed to the URL to the master branch @joyzhong linked above: https://github.com/material-components/material-components-web/blob/v8.0.0/packages/mdc-slider/README.md

From that link:
> Making sliders accessible
> 
> Sliders follow the WAI-ARIA guidelines. Per the spec, ensure that the following attributes are added to the mdc-slider__thumb element(s):
> 
>     role="slider"
>     aria-valuenow: Value representing the current value.
>     aria-valuemin: Value representing the minimum allowed value.
>     aria-valuemax: Value representing the maximum allowed value.
>     aria-label or aria-labelledby: Accessible label for the slider.
> 
> If the value of aria-valuenow is not user-friendly (e.g. a number to represent the day of the week), also set the following:
> 
>     aria-valuetext: Set to a string that makes the slider value understandable, e.g. 'Monday'.
>     Add a function to map the slider value to aria-valuetext via the MDCSlider#setValueToAriaValueTextFn method.
> 

I have added the addition role and aria-value* attributes to the <input> element, but I continue to get the same error.
