### ISSUE TITLE
Components |  Calendar

### ISSUE THREAD

**Issue by abelardolg** [material-components/material-components-web#6695]
## Feature Request

The following feature request is not related to a problem.
### Proposed solution

An almanac where a user can add events (unique o repeateds)
To have available a calendar component

### Alternatives considered

Add events to any day of the date picker component

### Additional context

Refer to: https://fullcalendar.io/

**Comment by joyzhong** [comment]
Hi there, at this time, we do not intend on implementing a calendar component, as it is not yet supported in the Material Design spec. However, we are planning on implementing time and date pickers in the near future, which may be helpful subcomponents in building a calendar widget.
