### ISSUE TITLE
[web] mdc-dialog wrong position, maybe replace "width: 100%" with "width: 100vw", etc

### ISSUE THREAD

**Issue by lborgman** [material-components/material-components-web#6698]
## Bug report
A dialog is not centered on screen as expected.

### Steps to reproduce
The problem appears on mobile phones, but not on Windows 10. (Using the mobile "emulator" in Chrome Dev Tools is enough to show the problem. Which surprices me. An explanation of that would be welcome.)

I do not know exactly how to pin it down, but you can see the problem here:

   https://clintools.web.app/mct.html

Click on the "i" in the middle of the screen after the "cloud" has passed.
The dialog will be misplaced (it is moved right and down).

### Actual behavior
See above.

### Expected behavior
Dialog should be centered.

### Your Environment:
Latest Chrome on Android 10. (Or Chrome Dev Tools on Windows 10, see above.)

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | Latest, 
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
| Browser          | Chrome (Windows 10: Version 87.0.4280.88 (Official Build) (64-bit), Mobile 87.0.4280.101)
| Operating System | Windows 10, Android 10 (Android One)

### Possible solution
It looks like changing width and head to vw resp wh (instead of %) might solve the problem.

.mdc-dialog,.mdc-dialog__scrim {
    position: fixed;
    top: 0;
    left: 0;
    align-items: center;
    justify-content: center;
    box-sizing: border-box;
    width: 100vw;
    height: 100vh
}

**Comment by lborgman** [comment]
Looking a bit more at this it might be a chromium bug. Please let me know when you do not need my example any more so I can apply some workaround.

**Comment by sayris** [comment]
Hi!

I think this is an issue with the page sizing -- I noticed that when emulating mobile, there's a horizontal page scroll (which is why the dialog appears to be off-centered). 

The dialog width/height is set to 100% to ensure it takes up the full page (even if the page extends beyond the viewport). So switching it to 100vw/100vh would result in the dialog scrim not covering the full page if the page is larger than the viewport.

**Comment by lborgman** [comment]
@sayris Thanks, I see. But if you are writing responsive web pages that should not be necessary, or?

I must say I am confused over how the page sizing works here. The element that stretches the page is absolutely positioned. I expected it to not change the page size (since the parts that are outside the viewport are not visible by default).

**Comment by sayris** [comment]
I'm not certain how your web page is set up, so I can't give advice on how to adjust things so the sizing works as expected (and you'll probably get faster/more useful advice for that sort of thing on stackoverflow or other similar sites 🙂).

As a starting point, I'd recommend starting with a single element and experiment with different widths/positions until you achieve the desired styling, and then slowly add additional elements on top of that.

Thanks!

**Comment by lborgman** [comment]
@sayris 
Thanks, maybe there is someone who knows the standards. I am not sure.
