### ISSUE TITLE
[Spinner] Not enough spinner using design

### ISSUE THREAD

**Issue by YouraHalloween** [material-components/material-components-web#6707]
## Feature Request

Let's say this
Large
![image](https://user-images.githubusercontent.com/5162766/102781005-c4384e80-43b8-11eb-9c5c-a83ee245cc40.png)
Small
![image](https://user-images.githubusercontent.com/5162766/102781163-fcd82800-43b8-11eb-82ec-f37fdf085a71.png)

```javacript
const MDCSpinner = (function () {

    let _size = {
        'extra-small': 'mdc-spinner-extra-small',
        'small': 'mdc-spinner-small',
        'medium': 'mdc-spinner-medium',
        'large': 'mdc-spinner-large'        
    }

    MDCSpinner.attachTo = function (root) {
        return new MDCSpinner(root);
    };

    function MDCSpinner(root) {
        this.root = root;
    }

    Object.defineProperty(MDCSpinner.prototype, "size", {
        get: function () {
            for (var key in _size) {
                var cls = _size[key];
                if (this.root.classList.contains(cls)) {
                    return key;
                }
            }
            return null;    
        },
        set: function (value) {            
            for (var key in _size) {                
                this.root.classList.remove(_size[key]);                
            }            
            this.root.classList.add(_size[value]);
        },
        enumerable: true,
        configurable: true
    });

    MDCSpinner.prototype.open = function () {
        this.root.style.display = 'inline-flex';
    };

    MDCSpinner.prototype.close = function () {
        this.root.style.display = 'none';
    };

    return MDCSpinner;
})();

export { MDCSpinner };
```

**Comment by allan-chen** [comment]
Hello,

If I understand correctly this is asking for the usage of classes in the [CircularProgress](https://github.com/material-components/material-components-web/tree/master/packages/mdc-circular-progress) component to control sizing. Due to certain constraints some dimensions of the spinner needs to be specified in the markup. 

Our next generation of components, [MWC](https://github.com/material-components/material-components-web-components/tree/master/packages/circular-progress#mwc-circular-progress-) solves this issue by leveraging lit-html templating mechanism and collapsing all sizing parameters into a single property `density` in the range [-8, 0]. Feel free to check out this new iteration (and trying out various values of density in the dev tools).

**Comment by YouraHalloween** [comment]
> Hello,
> 
> If I understand correctly this is asking for the usage of classes in the [CircularProgress](https://github.com/material-components/material-components-web/tree/master/packages/mdc-circular-progress) component to control sizing. Due to certain constraints some dimensions of the spinner needs to be specified in the markup.
> 
> Our next generation of components, [MWC](https://github.com/material-components/material-components-web-components/tree/master/packages/circular-progress#mwc-circular-progress-) solves this issue by leveraging lit-html templating mechanism and collapsing all sizing parameters into a single property `density` in the range [-8, 0]. Feel free to check out this new iteration (and trying out various values of density in the dev tools).

Hello!
Thank you so much!
I first found Line Progress, then I tried to search for the classic Spinner)
But Circle Progress has a bug:

```javascript
const circularProgress = new MDCCircularProgress(document.querySelector('.mdc-circular-progress'));
console.log(circularProgress);
        circularProgress.determinate = false;
        circularProgress.open();
```
It turns out like this:
![image](https://user-images.githubusercontent.com/5162766/102858203-b253bb80-444b-11eb-8de0-b8f1f443d36b.png)
This is one Circular progress, not two.
The code took from here
[Circular progress](https://github.com/material-components/material-components-web/tree/master/packages/mdc-circular-progress)

In progress mode works
```javascript
const circularProgress = new MDCCircularProgress(document.querySelector('.mdc-circular-progress'));
console.log(circularProgress);
        circularProgress.determinate = true;
circularProgress.progress = 0.4;
        circularProgress.open();
```
![image](https://user-images.githubusercontent.com/5162766/102859192-5722c880-444d-11eb-96d5-01359b0cfb43.png)


Iam use v8.0.0
Opera/Chrome
WIndows

**Comment by allan-chen** [comment]
Apologies - the code in the README is newer than 8.0.0 code. That code is meant for 9.0.0. 

You can use the code from [the 8.0.0 documentation](https://www.npmjs.com/package/@material/circular-progress) which only has minor differences.

**Comment by YouraHalloween** [comment]
Sorry, maybe I'm doing something wrong. But that's the only way I can )
![image](https://user-images.githubusercontent.com/5162766/102863655-b59f7500-4454-11eb-9613-cc505db044bf.png)
![image](https://user-images.githubusercontent.com/5162766/102863741-d5369d80-4454-11eb-9262-d99d772a66d7.png)

**Comment by allan-chen** [comment]
Here's a live [codepen](https://codepen.io/allanchenmdc/pen/RwGZzJM) example using the code from the README + your javascript. Hope it helps - I would suggest double checking your markup and making sure that the styles are being loaded properly.

**Comment by YouraHalloween** [comment]
Yes, I found the problem. Fault code formatter fixes
[codepen](https://codepen.io/yourahalloween/pen/rNMGBNv)

IMPORTANT: Do not introduce space between the adjacent </div><div> tags above. Doing so will produce unwanted visual artifacts.

```html
</div><div class="mdc-circular-progress__gap-patch">
and
</div><div class="mdc-circular-progress__circle-clipper mdc-circular-progress__circle-right">
```

**Comment by simonziegler** [comment]
Hi @allan-chen 

> Our next generation of components, MWC solves this issue by leveraging lit-html templating mechanism and collapsing all sizing parameters into a single property density in the range [-8, 0]. Feel free to check out this new iteration (and trying out various values of density in the dev tools).

What timeline do you think you have for MWC to be released to version 1? It's an exciting progression from presently using Material Components Web.
