### ISSUE TITLE
Segmented Button Typescript

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#6708]
We've discovered that #6629 also exists in Segmented Buttons. Can you please take a look and perhaps review all new 8.0.0 components for the same.

**Comment by allan-chen** [comment]
#6633 should have solved this as well.
This can be verified by exploring output files from the latest canary release https://www.npmjs.com/package/@material/segmented-button/v/9.0.0-canary.30fdfd06e.0

**Comment by simonziegler** [comment]
Hi Allan, thanks for the prompt response and I'll check. Does that mean however that we need to reference 9.0.0 pre-release rather than 8.0.0? We're building [Material.Blazor](https://material-blazor.com) and for the sake of quality need to follow your full release cycle. This means that we could ideally benefit from a correction to version 8.0.0.

Simon
