### ISSUE TITLE
tooltip disappear timing

### ISSUE THREAD

**Issue by tanekim77** [material-components/material-components-web#6711]
When a cursor hovers over a tooltip element, then a tooltip appears.
But when the cursor moves away, the tooltip lingers for a while before disappearing. Is there a way to configure the tooltip to disappear immediately once the cursor moves away?

**Comment by allan-chen** [comment]
Hello,

That appears to be configured by the constant ` HIDE_DELAY_MS: 600,` [here](https://github.com/material-components/material-components-web/blob/f89d8b8f295c80c7b7e691ec712a30de8a0b26d5/packages/mdc-tooltip/constants.ts#L38). Feel free to adjust that value to get the desired effect.

**Comment by tanekim77** [comment]
Thanks, but it seems HIDE_DELAY_MS applies tool all tooltips. So, if I change the HIDE_DELAY_MS = 0, then all tooltips in my website will have that setting. Is it possible to set the setting for some tooltips, not all tooltips?

**Comment by asyncLiz** [comment]
At the moment it is not possible to customize that setting for individual tooltips. Can you describe your use case where some tooltips need to immediately be hidden while others do not?

**Comment by tanekim77** [comment]
@asyncLiz 
I like the delay for most of the tooltips in my pages. I think it's intuitive and natural.

But I have a page with a header bar that contains many menu icons that are placed horizontally next to one another. And each of the icon will display a tooltip describing its description. If I hover over the left most icon and move my mouse to the right, hovering over the rest of the icons, then all those icons will have tooltips for a period of the delayed time. And they look horrible if that happens. I would rather have tooltip disappear immediately for the menu, so that when my mouse moves, it would display one tooltip at a time for the menu.

**Comment by asyncLiz** [comment]
It seems reasonable for tooltips to synchronize with each other and immediately hide if another tooltip is trying to display so that there's only ever "one" visible tooltip on the screen, even if there are multiple DOM instances.

@sayris could you follow up with design on what the intended UX should be in this situation?

**Comment by sayris** [comment]
Hi!

Thanks for flagging this -- unfortunately this is not something that the current infrastructure for components can support out-of-the-box (this requires a singular class that is aware of when tooltips are being shown/hidden). 

We recommend that clients build this themselves -- I'm creating a PR that will expose an `isShown` and `hide` method on the MDCTooltip component. You can add `mouseenter`/`mouseleave` listeners on various anchor elements and use these methods to detect when an old tooltip should be hidden immediately.

Let us know if you need more support/explanations on how to set this up. Thanks!
