### ISSUE TITLE
[Select] mdc-select does not show options when clicked

### ISSUE THREAD

**Issue by MaryWeeb** [material-components/material-components-web#6717]
## Bug report
Using the supplied template for mdc-select and including the correct <script> and <link> tags to MDC, it does not function as expected.

### Steps to reproduce
1. Put the HTML in a page.
2. Click the element
3. Nothing happens

### Actual behavior
Nothing happens when the element is clicked

### Expected behavior
A dropdown should appear, showing available options

### Screenshots
![Screenshot_20201228_133042](https://user-images.githubusercontent.com/16361449/103214522-eb3ed500-4910-11eb-8ffa-214d2bb8b351.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | latest
| Browser          | Chromium latest
| Operating System | Arch Linux latest

**Comment by asyncLiz** [comment]
Can you please provide a jsbin or glitch of your issue?

Here is a [jsbin with select working with the example markup from the readme](https://jsbin.com/koginomaje/edit?html,output).

**Comment by MaryWeeb** [comment]
After adding JS it works
