### ISSUE TITLE
[MDCTextField] Adapter protected

### ISSUE THREAD

**Issue by youra-halloween** [material-components/material-components-web#6742]
## Bug report

I use TypeScript.
I'm using the MDCTextField component. I am trying to access Input, but it is either private or with **property adapter**, but it is protected.
I want to use **hasClass**, but not possible, **property adapter** protected.
I'm trying to return **helperTextContent**, but it's write-only. I'm trying to access **helperText**, but it's private.
I am trying to return the **useNativeValidation** state, but only for writing. I'm trying to find out through foundation, but this property is private.
Fixed a Javascript bug https://github.com/material-components/material-components-web/issues/6654. But in TypeScript, nothing can be accessed because everything is private. Buttons are private, **HelperText** is private, **Adapter** protected.
This is a composite component, why does it all consist of private fields?

Added the values array to MDCList. So that it displays not only text, but also value.
Added the SelectedByValue method. To be able to work with data like [Value => Text]
In MDCMenu, the list property is private. 

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 8.0.0
| Browser          | Opera/Chrome
| Operating System | Windows

**Comment by brandondiamond** [comment]
Thank you for your question!

Material Web tries to provide a streamlined, focused interface for interacting with components. Though many of the fields and methods you mentioned may be useful from time to time, we've decided to limit their visibility in order to encapsulate implementation details. We strive to offer a public API that allows you to achieve the most common applications -- here's documentation on what's available today:

https://material.io/components/text-fields/web#span-class-inline-code-mdctextfield-span-properties-and-methods

We design our components this way for many reasons, but primarily to ensure that there's a clear delineation between how the component is built and how users interact with our components. This allows us to iterate on each component's implementation without worrying about breaking user code.

That said, we're certainly not perfect :), so if there's a use case that you think we should support, please let us know through a GitHub issue. In general, it's helpful to describe your end goal (in addition to the obstacle you encountered) so we can make sure there isn't another solution we can recommend. It's also much appreciated if you're able to include a PR that implements the missing feature. 

You should also feel empowered to work around any limitations in your own code (e.g., by retaining a local copy of the helper text when you set it, or retrieving it from the DOM). In many cases, this is the preferred solution.

As for this issue in particular, I'd like to learn more about your end goal (what would you like to achieve with MDCTextField?). And if there are particular features that are missing but that you think would be useful to most users, we'd love to hear about that, too.

**Comment by youra-halloween** [comment]
Hi Brandon! I'll start from afar :)
In the days of Windows XP, I developed components for displaying data from a database. The main task was maximum automation when working with data.
Since 2016 I have not been involved in programming and 3 months ago I returned to web programming. Therefore, in many things I can be wrong.
So...
To simplify work and automate work, I did several things:
1. I made classes for working with MDC in php. More or less like this:
```php
class Button extends _Component {
}

Button::one(
// for internationalization
    Yii::t('backend/login', 'Login'), 
    ['tabIndex' => 4], 
    ['spinner' => 'auto']
)                    
->setParent($form)
->submit();

or

Menu::list([
    'id' => 'locale-menu',
    'items' => I18nLocale::getList()
])            
->render()

or

Snackbar::one('')
            ->setProperty(['closeButton'=> Yii::t('backend', 'Close')])
            ->setId('app-snackbar')
            ->render()
```
Where **_Component** class registers all components in JavaScript
2. In the MDC components, I added a class for managing components
```javascript
class CollectionControl {}
//add new component
app.controls.add('loginform-username','textField',{"useNativeValidation":false},'loginform');
app.controls.add('loginform-rememberme','checkbox',[],'loginform');
app.controls.add('locale-menu','menu',{"values":["en-EN"]});
//get
app.controls.item('loginform-username')
//disabled
app.controls.groupEnabled('loginform', false)
```
**Your MDCButton class does not have a disabled property**. So I had to create this property and class TButton myself.  To remove crutches in the automation of the process.
Enabled button
![image](https://user-images.githubusercontent.com/5162766/104808013-124c4080-5805-11eb-8fb8-80bf25272e38.png)
Disabled button/submit + auto spinner and form components
![image](https://user-images.githubusercontent.com/5162766/104808035-4fb0ce00-5805-11eb-918b-3e42e611b0e0.png)
3. I used to use JavaScript and in general everything was fine.
Since the new year, I decided to learn TypeScript, to rewrite all the code for this, and faced a lot of problems. Private properties are one of them.
What have I added to the MDC components?
```typescript
TButtonSyg
property disabled
// As you know, all performed actions are asynchronous, I added a Spinner animation for the buttons
method spinnerToggle

MDCDrawer
// Hide menu blocks
method renderActiveGroup

// New component LeftAppBar
TLeftAppBarSyg
// Allows you to manage MDCDrawer blocks

MDCList
// Selected item or checbox selected
property text
// Get key for working with databases
// Returns the key or a list of keys loaded using the keys array
property key
// Make the Key menu items inactive
method setEnabledByKey

// Highlight the menu item with key = 12
list.key = 12

// So... PROBLEMS
// I used to use JavaScript and in general there were no problems with private properties :)
MDCList
property list_ - private
// Accordingly, everything that I added to the MDC List is no longer available here.

TSpinnerSyg
//I use my own spinner instead of the buggy MDCCircularProgress

MDCTextField
// I have already discussed extending this component with you. I was told that it is not necessary within the framework
property helperMessage
// The helperMessage property uses helperText - private
// Used for convenient (automated) output of information or errors during validation
// An error will appear if valid = false
textField.helperMessage.error = 'Error';
// The info property is initialized from helperText
// this._info = (this.parent.helperText.root as HTMLElement).innerText;
textField.helperMessage.info = 'Info';
// or for special cases of validation
textField.helperMessage.ex.tooLong = 'tooLong'
textField.helperMessage.ex.valueMissing = 'tooLong'

//add property
// used property Input - private 
property id
// used property Input - private
property type
property key
// This is how I solved the problem https://github.com/material-components/material-components-web/issues/6654
method disabledRenderDeactivateFocus
method enabledRenderDeactivateFocus

MDCTextFieldIcon
property disabled
// The TextField component often uses the Clear button to clear text or to break the link to the model by clearing the Key property
property clear
// This is how I solved the problem https://github.com/material-components/material-components-web/issues/6654
// Adds code to event MouseDown and MouseUp
property enabledRenderBlur

set(value: boolean) {
        if (this._enabledRenderBlur !== value) {
            this._enabledRenderBlur = value;
            if (value === true) {
                this.mousedown(this._handleDisabledRenderDeactivateFocus);
                this.mouseup(this._handleEnabledRenderDeactivateFocus);
            } else {
                this.root.removeEventListener(
                    'mousedown',
                    this._handleDisabledRenderDeactivateFocus
                );
                this.root.removeEventListener(
                    'mouseup',
                    this._handleEnabledRenderDeactivateFocus
                );
            }
        }
    },

// This requires trailingIcon and leadingIcon to be public.
```
**Two days ago I figured out how to use private properties**
I created a crutch.ts file. Unfortunately, this is a real crutch.

```typescript
import { MDCTextField } from '@material/textfield/component';
import { MDCTextFieldHelperText } from '@material/textfield/helper-text/component';
import { MDCTextFieldIcon } from './component';

declare module '@material/textfield/component' {
    interface MDCTextField {
        useNativeValidation: boolean;
        helperText: MDCTextFieldHelperText;
        input: HTMLInputElement;
        leadingIcon: MDCTextFieldIcon;
        trailingIcon: MDCTextFieldIcon;
    }
}

Object.defineProperty(MDCTextField.prototype, 'input', {
    get(): HTMLInputElement {
        return this.input_;
    },
    enumerable: true,
    configurable: true,
});

Object.defineProperty(MDCTextField.prototype, 'trailingIcon', {
    get(): MDCTextFieldIcon {
        return this.trailingIcon_;
    },
    enumerable: true,
    configurable: true,
});
...
```

I understand that all this is necessary within my business logic and not required for the overall development of the framework ;)
So the task can be closed. The main thing I figured out is how to use private properties to extend the capabilities of a component.
Thank you!

**Comment by youra-halloween** [comment]
I get the feeling that the components were done by different teams.
- There is an MDCTextFIeld component
- MDCList
- MDCMenu
- MDCSelect
And these are all different components with different properties, how so?
MDCSelect has a data-value attribute and a value property. But MDCMenu and MDCList don't have such properties.
Different actions and return values:
MDCList - MDCList:action, return {index: number}
MDCSelect - MDCSelect:change, return {value: string, index: number}
MDCMenu - MDCMenu:selected, return {item: Element, index: number}
How so? Why? What for?

What do I expect?
MDCSelect will consist of MDCTextField and MDCList, with all properties and methods implemented. MDCSelect is a standalone component that increases the size of the MDC library. 

MDCList has the ability to use checkbox and radio, and has a **selectedIndex** property. This property is missing from MDCMenu and MDCSelect.

DropDown implements List well with checbox. The values are displayed with semicolons.
white; black; green
✓ white
- yellow
- red
- blue
✓ black
✓ green

For MDCSelect to work with MDCTextField, there must be a Style property.
Style property type of component: 
- csDropDown - input field and drop-down list (data can be entered in the edit field or selected from the list; 
- csSimple - only the edit field; 
- csDropDownList - only the drop-down list

**Comment by youra-halloween** [comment]
In MDCTextField, the **helperText** property is private.
In MDCSelect, the **helperText** property is public.
In this case, the **helperText** object is simultaneously different and the same.
In MDCTextFeld, **helperText** has a method **setPersistent (isPersistent: boolean) => void**
And in MDCSelect the same method is called **setValidationMsgPersistent (isPersistent: boolean) => void**

**Comment by joyzhong** [comment]
Thanks for your feedback - we'll definitely consider consistency across components when implementing the next generation of MDC Web in MWC (https://github.com/material-components/material-components-web-components). The MWC API should also provide a better development experience.
