### ISSUE TITLE
[mdc-slider] using border to set border-width and border-style overrides custom border-colors

### ISSUE THREAD

**Issue by wagnermaciel** [material-components/material-components-web#6748]
## Bug report
In [_slider.scss](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/_slider.scss), the use of the `border` css rule to set the `border-width` and `border-style` in one line also automatically sets the `border-color` to black by default. This means any custom `border-color` provided (in my particular case, by the angular implementation) will be overridden.

### Proposed solution
Split the three usages of `border` in [_slider.scss](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/_slider.scss) into `border-width` and `border-style` to avoid this.

[Edit]
The same for the `border-top` in [_slider.scss on line 347](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/_slider.scss#L347).

**Comment by joyzhong** [comment]
Hi Wagner, do you have a Codepen or other demo of this? Afaiu `border-color` should override `border` if both rules have the same specificity.

**Comment by wagnermaciel** [comment]
Hi Joy, I'm not sure how to create a Codepen to reproduce this, but I can reproduce the bug consistently in my local angular components repository which can be found here: https://github.com/angular/components/pull/21381.

But also, if you have css like this
```css
    border-color: blue;
    border: 1px solid;
    border-width: 1px;
    border-style: solid;
```
the border color will be black, not blue

**Comment by wagnermaciel** [comment]
Closing issue as the problem was resolved (thank you, Joy).

Adding the `thumb-color`, `track-active-color`, `track-inactive-color`, and `value-indicator-color` mixins resolved the issue.
