### ISSUE TITLE
Label class for MDCSwitch, MDCCheckbox, and MDCRadio to match padding/height of other form components

### ISSUE THREAD

**Issue by SampsonCrowley** [material-components/material-components-web#6768]
## Feature Request

There is no built in way to have a Switch/Radio/Checkbox that has the same height as an `MDCTextField` on the same grid row.
There should be an easy way to combine with `MDCFormField` to produce both a standard and a `--filled`  element with styles similar to other components on the same form.

### Proposed solution

add an `mdc-(switch/checkbox/radio)--label` class that adds padding or margins to match other components, so that less experienced developers don't need to know the specifics of the internals to add their own classes.

### Additional context

![Screenshot from 2021-01-16 02-56-29](https://user-images.githubusercontent.com/22461638/104808929-a5a25900-57a6-11eb-8b80-95fe3f0dd5d8.png)

**Comment by joyzhong** [comment]
Hi there, can you clarify what you're trying to achieve here? Are you trying to fit a checkbox/switch/radio on the same row as the textfield component?

**Comment by SampsonCrowley** [comment]
Personally, I just want a built in way of keeping all single-row elements the same height, even if they're not on the same row, but yeah that's pretty much the goal; to be able to have a checkbox on the same row as an input component without needing to get into the minor details to match things up

**Comment by joyzhong** [comment]
Textfield is 56px in height, while other form controls (checkbox, radio, switch) do not exceed 48px in height. For these controls, we do not currently support larger sizes, so closing this for now. Note however that this will likely become feasible in the future, when the density subsystem is upgraded to support increasing component sizes.

**Comment by SampsonCrowley** [comment]
@joyzhong if it's *that* simple, then why is a class that adds said style values out of the question? Newcomers to MDC Web aren't going to just know that text fields are always exactly 56px
