### ISSUE TITLE
[Docs] missing `build:demos` in package.json

### ISSUE THREAD

**Issue by CroMarmot** [material-components/material-components-web#6773]
### Steps to reproduce
1. View https://github.com/material-components/material-components-web/blob/master/CONTRIBUTING.md#building-mdc-web
2. run `npm i`
3. run `npm run build:demos` 

### Actual behavior

```
npm run build:demos
npm ERR! missing script: build:demos
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     build:min

npm ERR! A complete log of this run can be found in:
```

### Expected behavior

work as what `CONTRIBUTING.md` say:

`npm run build:demos # Cleans out build/ and builds demo CSS/JS files, e.g. for deploying to App Engine`

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 0c95c9f7bf1e0d465e99fd7dd3f1497d37d871ff |
| Browser          | no browser, command line only |
| Operating System | Ubuntu 20.04.1, Linux 5.8.0-38-generic |

**Comment by EstebanG23** [comment]
Hi there, this is a bug in the documentation. Demos were removed from the repository in PR #4752.
Next steps forward will be to remove that line from documentation. Thank you for bringing this to our attention!
