### ISSUE TITLE
Documentation for use of Layout API() to add Data Table rows with Checkbox

### ISSUE THREAD

**Issue by ctmckee** [material-components/material-components-web#6776]
In the for Data tables documentation you state "use Layout() API when new row checkboxes are added or removed from data table."  An example or further documentation would be very helpful.  I can't figure it out.

**Comment by uptimal-julia-pujol** [comment]
Any advance in here? Could someone please provide an example of Layout API usage to add functionality to new rows added in a Table?

Thanks,

**Comment by abhiomkar** [comment]
That's correct! Calling `layout()` method on data table instance will automatically register new checkboxes.

Example:

```ts
const dataTable = new MDCDataTable(dataTableEl);
// .. Insert new rows to data table here..
dataTable.layout();
```

Let me know if you've any questions!
