### ISSUE TITLE
MDC-TextField the floating label does not wrap

### ISSUE THREAD

**Issue by jimyhdolores** [material-components/material-components-web#6784]
Hi, when using outline-height on a textbox with icons, it only sets the height of the textbox but does not do the floating label adjustment. Any suggestions?

![image](https://user-images.githubusercontent.com/10909792/105722807-0d1d7e80-5ef4-11eb-8ab1-b81d390f965b.png)
![image](https://user-images.githubusercontent.com/10909792/105723399-bb292880-5ef4-11eb-9e0c-75c2fc4980a8.png)
![image](https://user-images.githubusercontent.com/10909792/105723316-a51b6800-5ef4-11eb-8c57-953e634a7dd3.png)

Version: 9.0.0

**Comment by abhiomkar** [comment]
Can you please share a codepen or standalone example for us to investigate this issue?

Thanks!

**Comment by abhiomkar** [comment]
Update: Text field does not support text field height more than 56px (default height). But it supports lesser height (Upto density scale `-4`). Please use text field's density mixin instead for Sass input validation.

Let me know if that helps!

**Comment by jimyhdolores** [comment]
@abhiomkar  The problem persists, both outlined-height and outlined-density modify the height of the textField but do not adjust the float-label
