### ISSUE TITLE
Full screen dialog boxes

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#6790]
I note in mdc-dialog that there are some fullscreen CSS classes. Are full screen dialogs in some form supported? Thanks.

https://github.com/material-components/material-components-web/blob/master/packages/mdc-dialog/_mixins.scss#L92

**Comment by abhiomkar** [comment]
Thanks for the question!

Full screen dialog is currently under development and we'll update dialog's README file once it is ready for consumption. Let me know if you've any other questions!

**Comment by simonziegler** [comment]
No, that was it. Full screen dialogs will be  great addition.

**Comment by dvelasquez** [comment]
Is there any estimation on when this would be ready?

**Comment by sayris** [comment]
Current estimation is end of Feb/beginning of March.

**Comment by dvelasquez** [comment]
@sayris fantastic, thanks very much!
