### ISSUE TITLE
[icon] tooltip not showing on mobile devices

### ISSUE THREAD

**Issue by stefanloerwald** [material-components/material-components-web#6824]
## Bug report

I ran into an issue with displaying a tooltip on an icon (a help icon in this instance)

Icon html:
```html
<i aria-describedby="892f63ed-1223-459d-8f8d-1b9102583423" class="material-icons" aria-hidden="true">help</i>
```

Tooltip html:
```html
<div id="892f63ed-1223-459d-8f8d-1b9102583423" class="mdc-tooltip" role="tooltip" aria-hidden="true" style="z-index: 1000; top: 635px; left: 254.719px;"><div class="mdc-tooltip__surface">Tooltip text</div></div>
```

Creating the tooltip:
```js
tt = new mdc.tooltip.MDCTooltip(document.getElementById('892f63ed-1223-459d-8f8d-1b9102583423'))
```

On desktop, this tooltip shows nicely. On a touch device (or when dev-tools simulates a touch device), the tooltip never shows. I can see that the classes `mdc-tooltip--showing mdc-tooltip--hide` are applied simultaneously on the tooltip.

### Actual behavior
An action such as tapping or long-pressing the icon should reveal the tooltip.

### Expected behavior
No matter what I try on mobile devices, the tooltip does not show.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 9.0.0
| Browser          | Chrome 88
| Operating System | Windows 10

**Comment by sayris** [comment]
Hi, thanks for flagging this issue! Can you attach a codepen so that we can reproduce? Also what mobile device/browser are you using?

**Comment by stefanloerwald** [comment]
Hi, I'll try to reproduce using codepen tomorrow. As for the browser: I'm using Chrome on Windows 10 (using dev tools mobile device emulation) and Android 10.

**Comment by stefanloerwald** [comment]
Here's a codepen link that shows the issue: https://codepen.io/stefanloerwald/pen/GRNqYzy

**Comment by sayris** [comment]
Thanks for the codepen -- was able to reproduce and working on a fix!
