### ISSUE TITLE
[MDCDrawer] CRASH/REGRESSION: FocusTrap: Element must have at least one focusable child

### ISSUE THREAD

**Issue by regnaio** [material-components/material-components-web#6825]
Describe the bug
REGRESSION: No issues with v9.0.0. Somewhere between v9.0.0 to v10.0.0, this crash was introduced

(I'm using npm)

When opening a MDCDrawer, this crash occurs

I'm just using the modal navigation drawer example from https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer

Observe that when the drawer is opened, v8.0.0 surrounds the mdc-drawer__content with mdc-dom-focus-sentinel with tabindex="0", as shown below:

```
<aside class="mdc-drawer mdc-drawer--modal ...>
    <div tabindex="0" aria-hidden="true" class="mdc-dom-focus-sentinel"></div>
    <div class="mdc-drawer__content">...</div>
    <div tabindex="0" aria-hidden="true" class="mdc-dom-focus-sentinel"></div>
</aside>
```

v10.0.0 forgets to do this surround, as shown below:

```
<aside class="mdc-drawer mdc-drawer--modal ...>
    <div class="mdc-drawer__content">...</div>
</aside>
```

Due to no wrapping with tabindex="0", this causes focusableEls.length === 0, which causes the crash (source code below)

```
if (focusableEls.length === 0) {
    throw new Error('FocusTrap: Element must have at least one focusable child.');
}
```

Can we please bring back the behavior that wraps and does not crash?

**Comment by regnaio** [comment]
The regression occured somewhere between v9.0.0 and v10.0.0-canary.776c18681.0

This seems to correspond with the v9.0.0 commit: https://github.com/material-components/material-components-web/commit/555aecce59125bc3f162b065dca47384bb5822b1

and the 776c18681 commit: https://github.com/material-components/material-components-web/commit/776c1868154e5b99a332f60927b78b32b82fe19f

Though, I'm unsure in which exact commit the regression was introduced

**Comment by joyzhong** [comment]
The modal drawer requires a focusable element (tabindex="0" or other native interactive elements such as button) within the drawer content - when the drawer opens, for accessibility reasons, we automatically trap focus and focus on the first interactive element.

**Comment by regnaio** [comment]
@joyzhong I'm using the exact demo code for modal navigation drawer (https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer)

It has a tabindex="0" mdc-list-item

Can we please unclose and reopen this issue?

```
<body>
  <aside class="mdc-drawer mdc-drawer--modal">
    <div class="mdc-drawer__content">
      <nav class="mdc-list">
        <a class="mdc-list-item mdc-list-item--activated" href="#" aria-current="page" tabindex="0">
          <span class="mdc-list-item__ripple"></span>
          <i class="material-icons mdc-list-item__graphic" aria-hidden="true">inbox</i>
          <span class="mdc-list-item__text">Inbox</span>
        </a>
        <a class="mdc-list-item" href="#">
          <span class="mdc-list-item__ripple"></span>
          <i class="material-icons mdc-list-item__graphic" aria-hidden="true">send</i>
          <span class="mdc-list-item__text">Outgoing</span>
        </a>
        <a class="mdc-list-item" href="#">
          <span class="mdc-list-item__ripple"></span>
          <i class="material-icons mdc-list-item__graphic" aria-hidden="true">drafts</i>
          <span class="mdc-list-item__text">Drafts</span>
        </a>
      </nav>
    </div>
  </aside>

  <div class="mdc-drawer-scrim"></div>
  <div>Main Content</div>
</body>
```
