### ISSUE TITLE
Demo checkbox: make indeterminate for third example does not work

### ISSUE THREAD

**Issue by robzenn92** [material-components/material-components-web#683]
### What MDC-Web Version are you using?

0.11.1

### What browser(s) is this bug affecting?

I tried with Safari 10.1.1 and Firefox 53.0.2 but I think it does happen in all of them.

### What OS are you using?

macOS Sierra 10.12.5

### What are the steps to reproduce the bug?

1. Open http://localhost:8080/checkbox.html or visit the [demo](https://material-components-web.appspot.com/checkbox.html) page
2. Scroll down till you find the 3rd example "With Javascript"
3. click on the "Make indeterminate" button

### What is the expected behavior?

The checkbox on the left hand side should be in an indeterminated state.

### What is the actual behavior?

Nothing happens.

### Any other information you believe would be useful?

The issue is caused by lines [197-198](https://github.com/material-components/material-components-web/blob/master/demos/checkbox.html#L197) which throw `TypeError: _this3.root_ is null` exception because there is no #mdc-disabled-js-checkbox element in the page.

The fix is really simple and it sufficient to comment (or  I suggest remove) those lines and the problem is solved.

```
//        var disabledCheckbox = document.getElementById('mdc-disabled-js-checkbox');
//        var disabledCheckboxInstance = new MDCCheckbox(disabledCheckbox);
```
I will create a pull request in which I removed those lines. Please let me know if any concern about it.

**Comment by anton-kachurin** [comment]
Adding an example of a disabled checkbox would be great too. It was there but then got lost during refactoring.

**Comment by robzenn92** [comment]
@anton-kachurin I agree! I am on it!
