### ISSUE TITLE
[mdc-button] missing core-styles mixin

### ISSUE THREAD

**Issue by jcwchriswalker** [material-components/material-components-web#6837]
## Bug report
upgrading to mdc-button 10.0.0 from 9.0.0 the mixin button.core-styles is missing. However the most current readme.md for mdc-button still has the mixin as needed.

### Steps to reproduce

1. package.json : @material/button": "10.0.0"
2. scss :
@use "@material/button";
@include button.core-styles;

### Actual behavior
When running sass against the scss file, the error 
 'undefined mixin button.core-styles'

### Expected behavior
The same scss file using @material/button 9.0.0 does not throw this error.
### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |10.0.0
| Browser          |
| Operating System | Windows 10

**Comment by damianog** [comment]
@jcwchriswalker 
I am creating a [blazor wrapper](https://github.com/exentials/MdcBlazor) for material component web, by upgrading to v10  I found this issues too.
Is there a workaround?

**Comment by sayris** [comment]
Hello!

Sorry about this -- the button style sheets were refactored and the updated syntax (noted by @damianog) was not added into the docs. I'll submit an update to the documentation. 

Apologies again!

**Comment by cwalker-reveille** [comment]
Thank you. I thought that was what happened.

**Comment by whizyrel** [comment]
It is needless to submit another issue for this. Yeah, you are right. I was going to create stencil components too with mdc but I have already been delayed enough.

> @jcwchriswalker
> I am creating a [blazor wrapper](https://github.com/exentials/MdcBlazor) for material component web, by upgrading to v10 I found this issues too.
> 
> I managed to use core styles in my sass by using:
> 
> ```sass
> @use "@material/button/styles";
> ```
> 
> instead of:
> 
> ```sass
> @use "@material/button";
> @include button.core-styles;
> ```
> 
> Am I right?

**Comment by femiadeniyi** [comment]
This is not updated. Things like this cause thousand of developer hours wasted on configuration. Dev is getting more automated and errors like this can't be expected.
![image](https://user-images.githubusercontent.com/4870868/114288477-28fede00-9a68-11eb-8cca-c8033d9f959e.png)

**Comment by MikaStark** [comment]
Same issue here. MDC is a pain to use ><
