### ISSUE TITLE
[mdc-progress-indicator] obtain determinate state, progress, closed state with consistency

### ISSUE THREAD

**Issue by sigmapi** [material-components/material-components-web#6845]
## Bug report
Documentation for `mdc-progress-indicator` component API lists `determinate` method as;

"determinate: boolean | Whether the indicator is in the determinate or indeterminate state."

The description leads me to assume that it returns the determinate state value (as there is another method setDeterminate in the foundation API). However looking at the code and the implementation in Linear and Circular progress indicators this is a method to set the determinate state, not to retrieve it.
Same applies for `progress` method.

I was looking for methods to obtain the current state (determinate, progress, opened/closed) of a given progress component (linear or circular) and I see that there are differences between them:

MDCCircularProgressFoundation has methods:
- isDeterminate()
- getProgress()
- isClosed() This also appears in MDCCircularProgress component

MDCLinearProgressFoundation has methods  
- getDeterminate()
- getProgress()

The two progress components look like they evolved separately. The naming internally is different too.

### Actual behavior
Inconsistency in method naming between progress components 

### Expected behavior
Consistent API to obtain progress component state.

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 10.0.0
| Browser          | Firefox/Chrome
| Operating System | Linux

### Possible solution
Update the docs in mdc-progress-indicator.
Use methods `isDeterminate` and `isOpen` in progress API and in both components, like it is used in checkbox and menuSurface.

**Comment by allan-chen** [comment]
Thanks for the issue. Indeed some refactoring is overdue. I'll have a PR out soon.

**Comment by sigmapi** [comment]
Looks great @allan-chen, thank you!
Would you mind adding a `getBuffer()` method to MDCLinearProgressFoundation?

**Comment by allan-chen** [comment]
@sigmapi sure, I'll do that in a followup
