### ISSUE TITLE
[MDCTab] Ripple is not working

### ISSUE THREAD

**Issue by rubysamurai** [material-components/material-components-web#6847]
## Bug report

Upon upgrading from @material/tab v9.0.0 to v10.0.0 ripple effect for the tab is not working. 

### Actual behavior

[MDCTab v10.0.0 codepen](https://codepen.io/rubysamurai/pen/oNYZqNK)

![v10](https://user-images.githubusercontent.com/426523/107993772-4bd2c000-6fec-11eb-9dd2-252900aad141.gif)

### Expected behavior

[MDCTab v9.0.0 codepen](https://codepen.io/rubysamurai/pen/poNeaMp)

![v9](https://user-images.githubusercontent.com/426523/107993670-0a421500-6fec-11eb-9cce-ebffaf674d1d.gif)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 10.0.0
| Browser          | Chrome 88
| Operating System | Ubuntu 20.04

**Comment by allan-chen** [comment]
#fb793939 may have caused this - @EstebanG23 could you take a look?

**Comment by MaximBalaganskiy** [comment]
Please reopen. This sets `overflow: hidden` on the tab which hides a sliding tab indicator.

**Comment by allan-chen** [comment]
Hey Maxim, AFAIK overflow is only set on `mdc-tab__ripple` subelement. On the codepen here with the canary release it seems to work properly: https://codepen.io/allanchenmdc/pen/KKNyKpK

Let me know if you can reproduce with a codepen. Thanks!

**Comment by MaximBalaganskiy** [comment]
Sorry, my fault. Should not have added the surface class in the tab
