### ISSUE TITLE
[MDCSlider] Slider ripple is missing the "pressed" state

### ISSUE THREAD

**Issue by wagnermaciel** [material-components/material-components-web#6876]
## Bug report
The MDC Slider implementation's ripple is missing the "pressed" state

### Screenshots
![Screen Shot 2021-02-23 at 10 37 45 AM](https://user-images.githubusercontent.com/25158423/108891146-3862be80-75c3-11eb-8eae-55b58fdf5dbb.png)

### Additional context
I'm filing this issue as the result of [this comment from the Angular Components repo](https://github.com/angular/components/pull/21979#discussion_r581179240). We'd like for you to define & expose ripple opacity vars for the 'hover', 'focused', and 'pressed' states on the mdc-slider, similar to [how it's done in mdc-radio](https://github.com/material-components/material-components-web/blob/master/packages/mdc-radio/_radio-theme.scss#L36).

**Comment by asyncLiz** [comment]
I believe this can be fixed by adding an optional `$opacity-map` param to `thumb-ripple-color`, so that individual state opacities may be specified.

```scss
@mixin thumb-ripple-color($color, $opacity-map: null, $query: feature-targeting.all()) {
  .mdc-slider__thumb {
    @include ripple-theme.states($color: $color, $opacity-map: $opacity-map, $query: $query);
  }
}
```

**Comment by asyncLiz** [comment]
@wagnermaciel do you think you could send in a CL with the above fix?

**Comment by wagnermaciel** [comment]
@asyncLiz I'm not sure I fully understand the solution. Wouldn't this make it so that it is up to the developer to complete the MDC spec for the slider by passing in the correct opacities for the different ripple states? Shouldn't it be already set up with the correct opacities and just expose those variables to the developer?

**Comment by joyzhong** [comment]
Discussed offline with Wagner; this was a misunderstanding from running the component test in an internal environment (couple of things you need to manually tweak in the test env to get the pressed ripple working).
