### ISSUE TITLE
[checkbox] checkbox 's size bug

### ISSUE THREAD

**Issue by dang0705** [material-components/material-components-web#6880]
if the mdc-data-table with a row-checkbox props  or a mdc-checkbox in html td tag in table,   and then the table in the mdc-dialog, the checkbox's size will be very strange

**Comment by asyncLiz** [comment]
Hi! Can you provide a jsbin or glitch demo reproduction with the issue?

**Comment by patrickrodee** [comment]
Closing due to lack of response. Feel free to reopen!
