### ISSUE TITLE
Getting started documentation is broken 

### ISSUE THREAD

**Issue by jr305** [material-components/material-components-web#6887]
## Bug report
The 'Getting Started' walkthrough is broken due to an npm install error.

### Steps to reproduce
Downloaded the [Material Starter Kit](https://glitch.com/~material-starter-kit) and running npm install fails with the following error: 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
npm ERR! 404
npm ERR! 404  'har-validator@5.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'raspy-ajar-haze'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by asyncLiz** [comment]
I was able to `npm install` from the Material Starter Kit's package.json locally without issue. If you continue to have trouble, try removing the `package-lock.json` and run `npm install` again (it should try to install har-validator@5.1.5).

Let us know if you have any other questions!

**Comment by jr305** [comment]
Thank you so much for the quick response Liz. That worked :)
