### ISSUE TITLE
layout-grid SASS variable `$mdc-layout-grid-columns` doesn't appear to work

### ISSUE THREAD

**Issue by ukozdan** [material-components/material-components-web#6896]
## Bug report

Setting the SASS variable `$mdc-layout-grid-columns` to 24 from its default 12 does not change what is rendered in the browser. 

### Steps to reproduce

Define SASS variable, [as documented](https://github.com/material-components/material-components-web/tree/master/packages/mdc-layout-grid#sass-variables): 

```scss
$mdc-layout-grid-columns: (
    desktop: 24,
    tablet: 16,
    phone: 8,
) !default;
```

Import layout-grid module: 

```scss
@import "~@material/layout-grid";
```

Update HTML for 24 columns: 

```html
<div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
            <p>.mdc-layout-grid__cell.mdc-layout-grid__cell--span-12-desktop</p>
        </div>
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
            <p>.mdc-layout-grid__cell.mdc-layout-grid__cell--span-12-desktop</p>
        </div>
    </div>
</div>
```

### Actual behaviour

`mdc-layout-grid__cell--span-12-desktop` spans the full page width.

### Expected behaviour

Expected `mdc-layout-grid__cell--span-12-desktop` to span half the page width.

### Code example

https://codesandbox.io/s/eloquent-nash-tsqi8

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 10.0.0
| Browser          | Firefox 86.0
| Operating System | Windows 10

**Comment by EstebanG23** [comment]
Hi there, from initial investigation none of the mdc-layout-grid styles are being loaded. When I add `<link
      rel="stylesheet"
      href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css"
    />` to your index.html then default styles are loaded. 

Please check your dependencies and if they are being loaded correctly in the environment you are using.

**Comment by ukozdan** [comment]
OK, thanks for investigating. However, importing the CSS does not allow one to change the total amount of columns. What is the correct method for importing the layout grid SASS and modifying its variables?

**Comment by EstebanG23** [comment]
Codepen/Sandbox environments are not very good for writing sass however following our [documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-layout-grid#layout-grid) and using the [sass documentation](https://sass-lang.com/documentation/variables#configuring-modules) you should be able to either use the [mixins](https://github.com/material-components/material-components-web/tree/master/packages/mdc-layout-grid#sass-mixins) provided or the sass variables to change the columns.

**Comment by ukozdan** [comment]
If you look at [this codesandbox](https://codesandbox.io/s/jz8n259693), importing the SASS works as follows: `@import "@material/layout-grid/mdc-layout-grid.scss";` until one raises the module version to v5.0.0, after which neither `@import "@material/layout-grid/_index.scss"` or `@import "@material/layout-grid/"` works.

**Comment by ukozdan** [comment]
I ran my provided example both locally and in a code pen with the same result.
In the [provided codepen](https://codesandbox.io/s/mdc-layout-grid-wxs1z), the default Material Components for the Web styles are being loaded; one can see them being applied to the grid in the browser inspector. Therefore, the SASS is being loaded. My example code follows the documentation. Please explain how I am _not_ applying the documentation.

**Comment by ukozdan** [comment]
I've updated [the codepen](https://codesandbox.io/s/eloquent-nash-tsqi8). It works now.

**Comment by EstebanG23** [comment]
Thats great! What did you do differently? Is there something we can add to the documentation for future developers?

**Comment by ukozdan** [comment]
I used the Codesandbox [basic-material-starter-kit](https://codesandbox.io/s/github/kekscs/basic-material-starter-kit/tree/main/) which uses Webpack and perhaps, as you suggested, processes SASS correctly. 

The difference from my original implementation was as follows: 

`npm install @material/layout-grid`

```scss
$mdc-layout-grid-columns: (
    desktop: 24,
    tablet: 16,
    phone: 8,
) !default;

@use "@material/layout-grid/mdc-layout-grid";
```

I tried the `@use` technique on the old codepen and it didn't work. So, perhaps Webpack and sass-loader are the solutions. Not sure.

Regarding the MDC documentation. [The SASS Map](https://github.com/material-components/material-components-web/tree/master/packages/mdc-layout-grid#sass-variables), `mdc-layout-grid-columns` is not provided with any code examples; I had to find it on Stackoverflow. This is something I have found specifically with the customization documentation: a lack of working examples. The documentation could do with codepens demonstrating the types of customizations in their simplest form.

**Comment by ukozdan** [comment]
Anyway. If you agree, I think we can close this ticket and perhaps a ticket can be raised for documentation. I'll leave it in your hands. Thanks for the support.

**Comment by ukozdan** [comment]
BTW. Can I also add that some of the links and examples that the MDC NPM and Github pages link to are dead, the code examples are very old and there are few to no Typescript examples. The Glitch examples use very early versions of the MDC library.

**Comment by abhiomkar** [comment]
Thanks for the update! Please create separate bug for documentation or feel free to send us a PR.
