### ISSUE TITLE
[MDCTooltip] tooltips only supports one anchor element

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#6906]
### Steps to reproduce
1. [See this pen](https://codepen.io/Darhakexge/pen/RwoBdyN)
2. Hover the card buttons
3. The tooltips only shows on first card

### Actual behavior

Tooltips are shown only on the first anchor element

### Expected behavior
In some use cases the tooltips can describe more than one element, so the tooltips should support many anchor elements

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 10.0.0
| Browser          | All
| Operating System | Windows 10

**Comment by sayris** [comment]
Hi!

Thanks for flagging this -- it is actually WAI that a given tooltip element is only associated with a single anchor element, though I definitely understand the desire to reduce the amount of HTML one has to write if the same tooltip label is going to be displayed across different anchor elements. I've switched this over to a feature-request and will follow-up on this thread if we decide to put this on our roadmap.
Thanks!
