### ISSUE TITLE
Is there a way to implement it to next.js?

### ISSUE THREAD

**Issue by kavazvah** [material-components/material-components-web#6915]
After going through documentation on how to implement material components, and doing so, I was having some troubles with it while changing framework's server-side rendering style options and material wouldn't show it's normal style. 
Do you have any demos or examples that show how to implement this library to next.js fully?

**Comment by abhiomkar** [comment]
Next.js allows you to import Sass files. Follow instructions at https://nextjs.org/docs/basic-features/built-in-css-support#sass-support

Make sure to set `includePaths` option appropriately to resolve imports correctly.
