### ISSUE TITLE
Imported the SASS not working from the node_modules

### ISSUE THREAD

**Issue by yurisbeljimenez** [material-components/material-components-web#692]
As stated on the README.md:

### Including the Sass

```scss
@import "material-components-web/material-components-web";
```

When The SASS imported does not work since it needs the @material dependency to be in the same folder than the material-components-web.scss file. The address resolution using the SASS import is broken because of this.

The solution should be the target dependency to be retrieved from the main node_modules for the project.

**Comment by yeelan0319** [comment]
Hi @yurisbeljimenez ,

We realized that people might bump into this issue when we started this project. So if you scroll down a bit in the section you are reading, you can find the following [note](https://github.com/material-components/material-components-web#css)

> NOTE: The components' Sass files expect that the node_modules directory containing the @material scope folder is present on the Sass include path.

Hope this solves your question!
