### ISSUE TITLE
[mdc-checkbox] IE11 no fallback for padding, margin

### ISSUE THREAD

**Issue by austinw-fineart** [material-components/material-components-web#6930]
## Bug report
`mdc-checkbox` class has no fallback for variables used in padding and margin.

### Actual behavior
Compiled CSS:
```
padding: calc(var(--mdc-checkbox-ripple-size, 40px)/2 - 9px);
margin: calc(var(--mdc-checkbox-ripple-size, 40px)/2 - var(--mdc-checkbox-ripple-size, 40px)/2);
```

### Screenshots
![Untitled](https://user-images.githubusercontent.com/40481873/111095306-1c29c000-8578-11eb-8611-7aa1811f787b.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |10.0.0
| Browser          |IE 11
| Operating System |Windows 10

**Comment by patrickrodee** [comment]
Can you make a simple repro demo?

**Comment by austinw-fineart** [comment]
I was wondering why I couldn't reproduce it until I realized it was being caused by my PostCSS setup, specifically my choice of minifier csso. No idea why it decided to remove those but, anyway it ain't your problem so I'll close this. Sorry for the inconvenience o:
