### ISSUE TITLE
Order of included individual component stylesheets influences styles

### ISSUE THREAD

**Issue by bmihelac** [material-components/material-components-web#695]
### What MDC-Web Version are you using?

> Please be specific, e.g. _major.minor.patch_

v0.11.1

### What browser(s) is this bug affecting?

Chrome, Firefox tested (probably all)

> Please include the browser version. A user-agent string is also quite helpful.

Version 60.0.3101.0 (Official Build) canary (64-bit)

### What OS are you using?

OSX

> Please include the OS version.

10.9.x

### What are the steps to reproduce the bug?

Using individual stylesheets and including stylesheet for *select* component before including stylesheet for *menu* component.

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.
>

Demonstration of change that would trigger *incorrect* styles:

https://github.com/material-components/material-components-web/compare/master...bmihelac:issue-stylesheets-order?expand=1

> We also have a [template on CodePen](http://codepen.io/traviskaufman/pen/pNQmRp) which we encourage you to use to create a reproduction of
> the issue. The less time it takes for us to repro the issue, the less time it takes to verify and
> fix it!

### What is the expected behavior?

Styles of `mdc-select__menu` to overide `mdc-simple-menu`, ie: `width`, `overflow-y`

![css-menu-before-select](https://cloud.githubusercontent.com/assets/13813/26299596/9e1fe8d8-3edb-11e7-98fc-7a8e827cd08e.png)

> Please describe what the component/code should be doing that it's not.

`mdc-select`

### What is the actual behavior?

Select does not looks equal anymore.

![css-select-before-menu](https://cloud.githubusercontent.com/assets/13813/26299568/8c8d4a20-3edb-11e7-897d-6d98fbe800f1.png)

### Any other information you believe would be useful?

Including *menu* component stylesheet before *select* stylesheet yields correct styles.

**Comment by yeelan0319** [comment]
@bmihelac, this happens because simple menu is a dependency of select. In this way, we try to minimize the styles duplicated between modules. As a result, it does need to be imported in the order of `mdc-list` > `mdc-simple-menu` > `mdc-select`.

Since it is creating some confusion to you, I think we haven't make this relationship clear enough. So the best way to me is to explicitly document that when user trying to use sass to compile, they should use the order of `mdc-list` > `mdc-simple-menu` > `mdc-select`.

I would really like to facilitate the PR if you would like to help author it.

**Comment by bmihelac** [comment]
Thanks for answer @yeelan0319! 
One of the option would be to add more specificity so css rules for `mdc-select__menu` would be more important than rules for `mdc-simple-menu`, ie:

```css
.mdc-select .mdc-select__menu {
}
```

instead of 

```css
.mdc-select__menu {
}
```

This is demonstrated in https://github.com/bmihelac/material-components-web/commit/ee1905f06f5c2c974068f2e5324dc00dc627ce18 commit. 
What do you think?

**Comment by abhiomkar** [comment]
Marking this as obsolete.
