### ISSUE TITLE
Why ui of mdc-select looks ui when click outside

### ISSUE THREAD

**Issue by EABangalore** [material-components/material-components-web#6961]
Hi my UI looks  ugly when i click outside after selecting options

Here is the UI look

![image](https://user-images.githubusercontent.com/21359377/112148136-83dcac80-8c03-11eb-82eb-c06723d84fb6.png)

Here is that stackoverflow question: https://stackoverflow.com/questions/66685878/why-mdcselectchange-is-not-working-with-javascript-for-material-design?noredirect=1#comment117938704_66685878

**Comment by abhiomkar** [comment]
Based on [codepen example](https://codepen.io/eabangalore/pen/xxRvREg?editors=1010) that you shared you're missing `mdc-list-item--selected` class name on the selected item. See [pre-selected option section](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#select-with-pre-selected-option) for documentation.
