### ISSUE TITLE
[MDCSelect] hijacks other keyboard functions

### ISSUE THREAD

**Issue by Code-DJ** [material-components/material-components-web#6971]
## Bug report
When MDCSelect has focus, cannot do CMD+F to open the browser search box. Same for opening a new window or a new incognito window on Safari.

### Steps to reproduce

Reusing @jkevingutierrez's codepen from #6770 https://codepen.io/jkevingutierrez/pen/OJRdGaw
1. Click on the select box for it to get focus.
2. Try to do CMD+F in Safari/Chrome/Edge, the search box won't open.
3. Click outside (lose focus from select), try CMD+F. See that the search box appears.

### Actual behavior
Cannot perform keyboard functions that are irrelevant to select box.

### Expected behavior
User should be able to use any keys that are not relevant to select box.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 10.0
| Browser          | Safari 14.0.3
| Operating System | macOS Big Sur 11.2.3

### Possible solution
event.preventDefault should not fire when isModifier is true?
https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/foundation.ts#L356

**Comment by joyzhong** [comment]
Seems reasonable - @allan-chen what do you think?

**Comment by allan-chen** [comment]
This should've been fixed in 6f678a9 but was done after v10 release. The code as linked should be correct - `preventDefault` is not called since early return on line [342](https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/foundation.ts#L342) would exit on keys such as "F".
