### ISSUE TITLE
Validation/Helper text for radio and checkbox inputs?

### ISSUE THREAD

**Issue by ukozdan** [material-components/material-components-web#6974]
In the use case where a user is required to agree/disagree (radio) or accept (checkbox) TOS to submit a valid form, why does MDC not provide, for instance, `.mdc-radio-helper-text` and `.mdc-checkbox-helper-text` classes for a consistent form validation function and style across all form elements?

**Comment by joyzhong** [comment]
What's the ask here? Please add additional context (screenshots, your specific use case).

Please note that we implement based on the Material Design spec. The [radio buttons spec](https://material.io/components/radio-buttons) for example does not include validation-specific specs.

**Comment by EstebanG23** [comment]
Closing due to lack of response.
