### ISSUE TITLE
[MDCSelect] arrow navigation error when initializing more than once #6769

### ISSUE THREAD

**Issue by jkevingutierrez** [material-components/material-components-web#6984]
## Bug report

I'm opening a new issue as https://github.com/material-components/material-components-web/issues/6769 was closed.

Initializing multiple times a MDCSelect (`new MDCSelect(element)`) and trying to navigate the list using the arrow keyboards is moving multiple times.

Also, the `change` event is triggered multiple times.

### Steps to reproduce
https://codepen.io/jkevingutierrez/pen/XWjOQNv

1. Follow https://material.io/develop/web/components/input-controls/select-menus but Initialize more than once the MDCSelect in Javascript
2. Open the MDCSelect
3. Navigate using the arrow keyboards
4. See navigation error
5. Select some element in the list
6. See on change event being triggered multiple times

```
const select = document.querySelector('.mdc-select')
let mdcSelect = new MDCSelect(select);
mdcSelect = new MDCSelect(select);

mdcSelect.listen('MDCSelect:change', () => {
  alert(`Selected option at index ${mdcSelect.selectedIndex} with value "${mdcSelect.value}"`);
});
```

### Actual behavior

The arrow keyboards move `x` number of elements, being `x` the number of times that the element have been initialized (`new MDCSelect(element)`).

Also the `change` element is triggered x times.

### Expected behavior

The arrow keyboards should always move only one element.

The `change` element should triggered just once.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 10.0
| Browser          | Chrome Version 87.0.4280.141 (Official Build) (x86_64)
| Operating System | macOS BigSur

### Additional context

#6769

### Possible solution

- Remove listeners on the element every time that it is initialized.
- Another alternative is to provide a function to "destroy" or "unmount" the component, so it can be initialized again.

**Comment by joyzhong** [comment]
The MDCSelect does provide a [#destroy method](https://github.com/material-components/material-components-web/blob/1f636b205b9609d19a96bef707ab87a0f8ca4f1a/packages/mdc-select/component.ts#L189). Can you try using that before re-initializing the component?

**Comment by jkevingutierrez** [comment]
Hi @joyzhong, thanks for your reply. Using destroy works for me!

But, It would still be good to not having to call the `destroy` method. Initializing the Select should destroy it if it was initialized before.

If that's not possible, it would be good to add documentation about the destroy method in https://material.io/develop/web/components/input-controls/select-menus

**Comment by joyzhong** [comment]
The #destroy method is documented [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-base#lifecycle-methods).

What's your use case for initializing the select multiple times? Please note that if you need to dynamically update the menu options, you can manually update the select's list item elements, then call MDCSelect#layoutOptions()
.
