### ISSUE TITLE
v0.11.1 full-width Textfields vertical alignment is off

### ISSUE THREAD

**Issue by jrop** [material-components/material-components-web#701]
### What MDC-Web Version are you using?

> v.0.11.1

### What browser(s) is this bug affecting?

> Tested in Chrome 58.0.3029.110

### What OS are you using?

> macOS Sierra 10.12.2

### What are the steps to reproduce the bug?

[See this Codepen](https://codepen.io/jrop/pen/vmvWvj/):
```pug
// The following is already included in <head>: <link rel="stylesheet" href="https://unpkg.com/material-components-web@0.11.1/dist/material-components-web.min.css">
// <html> tag has class="mdc-typography"
// Pug markup:
div.mdc-textfield.mdc-textfield--fullwidth(data-mdc-auto-init="MDCTextfield")
    input.mdc-textfield__input(type='text', id='missaligned', name='missaligned')
    label.mdc-textfield__label(for='missaligned') Miss-Aligned

div.mdc-textfield(data-mdc-auto-init="MDCTextfield")
    input.mdc-textfield__input(type='thisoneworks', id='thisoneworks', name='thisoneworks')
    label.mdc-textfield__label(for='thisoneworks') This One Is Better

script(src='https://unpkg.com/material-components-web@0.11.1/dist/material-components-web.min.js')
script.
    mdc.autoInit()
```

### What is the expected behavior?

When focusing a full-width text area, the editable area should be properly vertically aligned in the component.  For example, in the codepen above, focus the first (full-width) textfield.  The editable area will not be correctly vertically aligned:

![Screenshot of issue](http://i.imgur.com/mqn0iDC.png)

### What is the actual behavior?

See above

**Comment by anton-kachurin** [comment]
Currently, there is no support for labels on full width text fields. Consider using `placeholder` attribute on the `input` and removing `label`.

**Comment by jrop** [comment]
Thank you @anton-kachurin for the fast reply.  Do you know if there are plans to support this in the future, or am I best left looking for an alternative workaround?

**Comment by anton-kachurin** [comment]
No problem, @jrop. You're probably looking for how to stretch a regular textfield (with a label and highlighting bottom on focus) so that it takes 100% width. In this case, add custom CSS to your app.

Full-width textfields, [as it seems](https://material.io/guidelines/components/text-fields.html#text-fields-field-variations), have special semantics and are not to just fill all available width, and probably will never have a label.

**Comment by yeelan0319** [comment]
@anton-kachurin is right. 

In [material guideline](https://material.io/guidelines/components/text-fields.html#text-fields-field-variations):

> Full-width text fields are useful for in-depth tasks or entering complex information.

Though it visually takes up the full row, it is not for the same purpose of a text field whose width is 100% of the container and thus don't have a label.

However, as @anton-kachurin suggested, you can overwrite the style to make the text field width 100% to meet your design need.
