### ISSUE TITLE
[MDC-LIST] missing core-styles mixin

### ISSUE THREAD

**Issue by MaximBalaganskiy** [material-components/material-components-web#7013]
## Bug report
Suggested by the docs styles usage does not work - `core-styles` mixin is missing.
```scss
@use "@material/list";
@include list.core-styles;
```
### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 11.0.0

### Additional context
I see that the original styles have been renamed to deprecated so have a lot of original mixins.

**Comment by EstebanG23** [comment]
Thanks for bringing this to our attention. Currently only deprecated-core-styles exists.
@brandondiamond could you take a look if we should update documentation to support List Evolution or add a core-styles in the evolution mixin?

**Comment by MaximBalaganskiy** [comment]
The issue with evolution styles is that there are no docs on how to use them. I’ve tried building core styles myself but without dom structure understanding it is a bit hard

**Comment by brandondiamond** [comment]
Hey Maxim! Thanks for flagging this -- I'm currently working on updating the API docs to describe the new evolution DOM structure. To help unblock you ASAP, I've attached a draft that includes full details on our DOM API. The specific wording and organization of this document will likely change but the API itself is stable.

Core-styles is definitely something we want to provide. I'm working on getting that added to the stylesheet this week.

[List Evolution Public Documentation (PUBLIC DRAFT).pdf](https://github.com/material-components/material-components-web/files/6379109/List.Evolution.Public.Documentation.PUBLIC.DRAFT.pdf)

**Comment by zbot473** [comment]
How do we use MDCList in the meantime? Should we just downgrade to 10.0.0?

**Comment by MaximBalaganskiy** [comment]
Have a look at the pdf, the DOM is described there.
In a nutshell, `two-line` has been moved to item's level and some internal containers got renamed.

**Comment by ckotzbauer** [comment]
Is there any chance that the fix from #7096 is released as patch-release? Or will this only be released in the next major?

**Comment by Byloth** [comment]
> «Why should we simply publish a patch release to make an already merged fix available to everyone when we can keep waiting everyone for it in the next major release?»

---

Just joking...  
But... Talking seriously... Is it possible to know any ETA for this?

Thanks. ❤

**Comment by ckotzbauer** [comment]
@MaximBalaganskiy @brandondiamond @EstebanG23 
Does anybody know why the following scss file still produces the same error at `@include list.core-styles;` in version 12?
```scss

@use "@material/list";
@use "@material/menu-surface/mdc-menu-surface";
@use "@material/menu/mdc-menu";
@use "@material/icon-button";
@use "@material/select/styles";
@use "@material/top-app-bar/mdc-top-app-bar";
@use "@material/card";
@use "@material/floating-label/mdc-floating-label";
@use "@material/line-ripple/mdc-line-ripple";
@use "@material/notched-outline/mdc-notched-outline";
@use "@material/textfield";
@use "@material/checkbox";
@use "@material/form-field";

@use "@material/ripple";
@import "@material/button/styles";

@include list.core-styles;
@include icon-button.core-styles;
@include card.core-styles;
@include textfield.core-styles;
@include checkbox.core-styles;
@include form-field.core-styles;
```

The usages of list are in the same order as mentioned in the docs.

**Comment by MaximBalaganskiy** [comment]
Looks like the list has not been promoted from "evolution" yet.
The following should work
```scss
@use "@material/list/evolution-mixins"as list-evolution-mixins;
@include list-evolution-mixins.core-styles();
```

**Comment by ckotzbauer** [comment]
Thanks @MaximBalaganskiy, this fixed the issue.

**Comment by giltee** [comment]
> Looks like the list has not been promoted from "evolution" yet. The following should work
> 
> ```css-scss
> @use "@material/list/evolution-mixins"as list-evolution-mixins;
> @include list-evolution-mixins.core-styles();
> ```

This works but is super unintuitive, the documentation is incorrect. https://material.io/components/lists/web#using-lists 

It would be very helpful to either fix the code or your documentation, as someone should not have to get to this ticket to be able to simply use the list component.
