### ISSUE TITLE
How to use new chips/chipset?

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#7014]
Hi,

I've seen chips and chipsets were deprecated in the new release. Why? Will they be renewed or removed forever?

There are three new dirs in the mdc-chip package: action, chip and chip-set, but there isn't any docs that explains how to use them.

Can you explain these points?

Thanks

**Comment by MaximBalaganskiy** [comment]
For now I just import everything chips related from the `deprecated` folder.

**Comment by maicol07** [comment]
@MaximBalaganskiy I use the deprecated folder too, but I think it will be deleted in the next release and currently we don't have any documented replacement.

**Comment by MaximBalaganskiy** [comment]
At least with chips there's unchanged `deprecated` folder. Mdc-list is completely screwed

**Comment by patrickrodee** [comment]
Hey all, apologies for the release with incomplete docs. There was a miscommunication about the release status and we should have held off until we had complete docs for the new release of chips.

We're working on the docs now and will update this issue once they're complete. Thanks for your patience.

**Comment by patrickrodee** [comment]
> @MaximBalaganskiy I use the deprecated folder too, but I think it will be deleted in the next release and currently we don't have any documented replacement.

We currently have no plans to delete the deprecated chips directory. If that changes, we'll be sure to communicate that ahead of time.

**Comment by patrickrodee** [comment]
[Docs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-chips#readme) have been updated. Let me know if you have any questions!
