### ISSUE TITLE
deregisterAnchorEventHandler in Tooltip component does not remove the listener.

### ISSUE THREAD

**Issue by hperrin** [material-components/material-components-web#7032]
https://github.com/material-components/material-components-web/blob/3f342c3f4715fd3587f327ce4ea6b5dd314c5c55/packages/mdc-tooltip/component.ts#L243

deregisterAnchorEventHandler in Tooltip component does not remove the listener. You can see in the link above, it adds another listener.

**Comment by EstebanG23** [comment]
Thank you for bringing to our attention. @sayris can you take a look?
