### ISSUE TITLE
[MDCDialog] Missing documentation for mdc-dialog__surface-scrim element.

### ISSUE THREAD

**Issue by hperrin** [material-components/material-components-web#7034]
## Bug report
Not so much a bug as a missing documentation report.

### Steps to reproduce
1. Go to https://github.com/material-components/material-components-web/blob/v11.0.0/packages/mdc-dialog/README.md
2. Search the page for "mdc-dialog__surface-scrim"
3. See that this element and class are not documented.

### Actual behavior
No documentation for where this element should be placed is found.

### Expected behavior
This element's placement should be documented.

**Comment by EstebanG23** [comment]
Thanks for bringing this to our attention. `mdc-dialog__surface-scrim` element was added with the full-screen dialog support. Assigning to our full-screen dialog developer.

**Comment by sayris** [comment]
Hello! `mdc-dialog__surface-scrim` is tied to a feature that is not supported by MDC Dialogs. The Dialog README does not mention this class so clients won't use this unsupported feature.

Thank!
