### ISSUE TITLE
Drawer + toolbar default layout unexpected

### ISSUE THREAD

**Issue by donmccurdy** [material-components/material-components-web#704]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

0.11.1

### What browser(s) is this bug affecting?

macOS, Chrome Version 58.0.3029.110 (64-bit)

### What are the steps to reproduce the bug?

The drawer documentation, under _Permanent drawer usage_,  suggests putting the drawer first, then the toolbar and page content next inside a wrapping `<div/>`. I've attempted to do that in a simple boilerplate example here:

Source: https://zeit.co/donmccurdy/donmccurdy-toolbar-demo/lpusuqxeas/source?f=index.html&redirect=1
Demo: https://donmccurdy-toolbar-demo-lpusuqxeas.now.sh/

### What is the expected behavior?

I hoped to see the draw alongside the page content, both beneath the header:

<table>
  <tr><td colspan=2>Header</td></tr>
  <tr><td>Drawer</td><td>Content</td></tr>
</table>

### What is the actual behavior?

<img width="590" alt="screen shot 2017-05-22 at 4 59 06 pm" src="https://cloud.githubusercontent.com/assets/1848368/26333107/0bf72a68-3f10-11e7-88f7-ef956f643a2f.png">

Changing the order of the markup to `header, drawer, content` does no better, as the drawer is still stacked on top of the content. I realize I could fix all this with a few lines of `display:flex`, but wanted to verify that there wasn't some out-of-the-box way first.

**Comment by jonboj** [comment]
@donmccurdy Hi, just a small tip. The mdc-web project provides a codepen template with the latest version preloaded. I have started to use that,  easy to dump a snippet in a "clean" environment. 
http://codepen.io/traviskaufman/pen/pNQmRp

By the way the source code above, seems in my environment (Linux, Chrome) blocked for copy.

**Comment by donmccurdy** [comment]
Oops, sorry I didn't realize the copy/paste situation in my host was quite that broken... here's a codepen: http://codepen.io/donmccurdy/pen/rmPayy?editors=1010

**Comment by yeelan0319** [comment]
Hi @donmccurdy ,

For having the structure you described in the issue, you need a different markup structure.
Please take a look at this [example](http://material-components-web.appspot.com/drawer/permanent-drawer-below-toolbar.html)

Let me know if this solves the problem. 

BTW, since you are using a persistent drawer, you might want to remove the hamburger icon.

**Comment by donmccurdy** [comment]
Ok thanks — I think I was expecting the suggested markup to include the `display:flex` styles that place the sidebar next to the content, rather than stacking them, but that's easy enough to add manually as you've done in the demo app. Works for me.
