### ISSUE TITLE
Banner stacking should not be bound to a media query

### ISSUE THREAD

**Issue by flunderpero** [material-components/material-components-web#7043]
## Feature Request
Perhaps I do not understand the scope of the banner component completely. But I would like to use banner not only on the top level of my app spanning the whole viewport width but also on a single component. For example, I want to add a banner to a drawer to inform the user about something or to guide them in their first time use of the app.

Currently, the banner would not stack if the _width of the banner_ is below 480px but the _width of the viewport_.

### Proposed solution
Banners should stack if their width is above the breakpoint (currently 480px) or there should be a class out of the box that forces stacking.

**Comment by allan-chen** [comment]
Adding @EstebanG23 to confirm whether this is something we would support.

**Comment by EstebanG23** [comment]
Fixed by #7090
