### ISSUE TITLE
[MDC-FAB] Ripple effect is missing

### ISSUE THREAD

**Issue by MaximBalaganskiy** [material-components/material-components-web#7053]
## Bug report
Ripple effect is not working on fabs

### Steps to reproduce
https://codepen.io/maximbalaganskiy/pen/abpxGQP

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 11.0.0

### Possible solution
Use default `fab-theme.$opacity-map` in `fab-theme.ripple-color` mixin instead of an empty one.

**Comment by allan-chen** [comment]
It seems like a null map should be passed to `ripple-theme` if we want the default opacities to apply. @abhiomkar , could you take a quick look?

**Comment by abhiomkar** [comment]
@allan-chen Good find! Fix is on the way.
