### ISSUE TITLE
Select does not respect disabled property on items

### ISSUE THREAD

**Issue by Holi0317** [material-components/material-components-web#706]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

MDC 0.3.6

### What browser(s) is this bug affecting?

Chromium 58.0.3029.110

### What OS are you using?

Arch Linux

### What are the steps to reproduce the bug?

[CodePen demo](http://codepen.io/Holi0317/pen/XRowGQ)
1. The upper one is select with JS enabled, while the other one is not
2. An option, `Milk, Yogurt, and Cheese` is disabled in HTML markup
3. Select it

### What is the expected behavior?

When an item is disabled in HTML markup property, it should be disabled in both JS or pure CSS version of select component.

### What is the actual behavior?

 - In JS enabled version of select, we can select that option.
 - In pure CSS version, disabled works correctly.

**Comment by yeelan0319** [comment]
Thanks for filing this. This definitely seems a bug!
