### ISSUE TITLE
Width of permanent drawer becomes obscured with main content

### ISSUE THREAD

**Issue by aaronhudon** [material-components/material-components-web#709]
### What MDC-Web Version are you using?

> 0.11.1

### What browser(s) is this bug affecting?

> Chrome v58

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

Create a permanent drawer just like the demo.  Add more than just a small amount of content to the main area.  The main area will resize and "take over" the drawer.

https://codepen.io/anon/pen/wdNNMM

### What is the expected behavior?

> The drawer width should not change

### What is the actual behavior?

The drawer's width shrinks

**Comment by Garbee** [comment]
When using flexbox to align content you need to make sure to `flex-shrink:0;` things that shouldn't lose space with content changes. That is the solution for the drawer. This should be added to our demo page just in case. No changes internally to the component should be necessary since we don't have any page-layout stuff since that level is left to developers.

**Comment by aaronhudon** [comment]
Thanks, I have updated the pen to include
`    .mdc-permanent-drawer {
    	flex-shrink:0;
    }`

**Comment by aaronhudon** [comment]
@Garbee any chance you can review the [pen](https://codepen.io/anon/pen/wdNNMM) again?    What would be the appropriate adjustments when you want the toolbar to be fixed?  When .mdc-toolbar--fixed is applied, it does not obey its flex position.

I'd think this could be something expanded on in the demos.

**Comment by Garbee** [comment]
`z-index` is the problem there with the layering of the components. You need to increase the placement of the toolbar so it sits over the drawer.

Issue #461 is open to investigate these issues and find a resolution that works across all the components.
