### ISSUE TITLE
The Material icon font does not appear in safari

### ISSUE THREAD

**Issue by Aratmany** [material-components/material-components-web#7123]
![dZd0KsiQ7ok](https://user-images.githubusercontent.com/66491452/118005982-8af68000-b353-11eb-8f17-dd007e0cb96b.jpg)
## Error report
In Safari iPhone browser (iOS 14.5) - Font is not displayed correctly. In other browsers (For example: Chrome, Brave - everything is correct)

### Steps for playback
1. Go to the 'https://property.mylistingtheme.com/' page in iPhone Safari.
2. You will see squares. In some places emoji.
3. Go to the same page 'https://property.mylistingtheme.com/' in iPhone only in a different browser (For example: Chrome).

![dZd0KsiQ7ok](https://user-images.githubusercontent.com/66491452/118006049-99449c00-b353-11eb-965e-a7c828819598.jpg)

### Actual behavior.
A blank square appears instead of icons - ◻

### Expected behavior.
Correct display of icons

### Screenshots.
https://disk.yandex.ru/d/g180skYtJeM5-w?w=1 - here you can find the screenshots

### Your environment:
| Software | version(s) |
| ---------------- | ---------- |
| Mobile Safari 14 (14.1)|
| iOS 14.5|

**Comment by Aratmany** [comment]
@patrickrodee Hi, can you please advise - what could this be related to?

**Comment by sayris** [comment]
Are you still experiencing issues? Using iOS + Safari I'm not seeing any problems with the icons.

![IMG_0235](https://user-images.githubusercontent.com/6932089/120518759-e7235180-c39f-11eb-9bdf-ec4c192096a9.PNG)
![IMG_0236](https://user-images.githubusercontent.com/6932089/120518772-eab6d880-c39f-11eb-84f7-c361411aec9e.PNG)

**Comment by sayris** [comment]
I'm going to close this since it looks like things were resolved -- feel free to reopen if you're still having issues.
