### ISSUE TITLE
Linear Progress is not published to npm

### ISSUE THREAD

**Issue by dimik** [material-components/material-components-web#713]
```
$ npm install --save @material/linear-progress
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "@material/linear-progress"
npm ERR! node v4.4.0
npm ERR! npm  v3.9.2
npm ERR! code E404

npm ERR! 404 Not found : repository
```

**Comment by traviskaufman** [comment]
We publish once every two weeks, as per our release cycle. It'll be on there next Monday!

P.S. any component with a version number of `0.0.0` has not yet been published to npm

**Comment by amsheehan** [comment]
Always good to just keep in mind that the Master branch on Github should _not_ be considered the latest stable release.
