### ISSUE TITLE
[mdc-button] Screenreader announces button elements twice

### ISSUE THREAD

**Issue by Rlund-google** [material-components/material-components-web#7140]
## Bug report
When using the MDC button component, voiceover (ChromeVox) reads the button label twice.  This can be seen here in the MDB button Demo page:

https://material.io/components/buttons

### Steps to reproduce

1) Open https://material.io/components/buttons
2) Turn on ChromeVox voiceover 
3) Find the "Interactive Demo" section, and click on the button. Notice that ChromeVox reads the button text twice.

This may be hard to notice at first, so you can click on a tab in the demo, and click back to the button to hear it again.

### Actual behavior

The screenreader reads the button text twice

### Expected behavior
I would expect the button's aria text to only be read once

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |  Whatever is on head on google3
| Browser          | Chrome
| Operating System | ChromeOS

### Additional context

This is a blocking bug for our GAR Sphinx A11Y compliance.

**Comment by joyzhong** [comment]
Are you able to repro using a vanilla HTML button? Something like:

```<button><span>Button label</span></button>```

There's nothing special about the MDC buttons.

**Comment by sayris** [comment]
I'm going to close this due to lack of a response -- feel free to re-open with more information.
