### ISSUE TITLE
MDCSliderFoundation: Slider value must be valid based on the step value

### ISSUE THREAD

**Issue by nyanpasu** [material-components/material-components-web#7148]
https://github.com/material-components/material-components-web/blob/ec31ae1ed1e6483d972f0eddece0fbf30ac721c2/packages/mdc-slider/foundation.ts#L1000

Hi, I'm getting this error even for valid values, such as:

```
  min={0.01}
  step={0.01}
  value={2500}
```

This is due to a floating point error... and checking if it is divisible by 1...

```
(2500 - 0.01) / 0.01
> 249998.99999999997
```

Thanks javascript.
I've actually encountered this problem in a downstream library, `svelte-material-ui`. Reporting it here as well for reference in case anyone bumps into it or if there is a more obvious way of dealing with this issue.

**Comment by simonziegler** [comment]
There are now two PRs waiting both of which fix this issue. #7439 from @ThomasOrlita and also #7458 by me (presently awaiting completion of my CLA). Can you please review and accept one of them. Until this point sliders continue to be unusable after six months and counting.

@joyzhong @asyncLiz @vkirilyuk @abhiomkar @allan-chen

(Sorry for all the at links, but this is quite a damaging bug with two alternative quick and easy fixes)

**Comment by joyzhong** [comment]
Fixed in https://github.com/material-components/material-components-web/pull/7458
