### ISSUE TITLE
[Tooltip] never closes

### ISSUE THREAD

**Issue by jdoubleu** [material-components/material-components-web#7150]
## Bug report
Using the examples from the documentation at https://material.io/components/tooltips/web#tooltips, the tooltips never actually close.

### Steps to reproduce
https://jsfiddle.net/3emy0hsz/1/

### Actual behavior
The tooltip opens, but never closes.

### Expected behavior
After the [`HYDE_DELAY_MS`](https://github.com/material-components/material-components-web/blob/633a9fc7a98d0d9bdc177bc9ccbd49beb25bd5b6/packages/mdc-tooltip/constants.ts#L39) the tooltip fades out and eventually closes.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 11.0.0. |
| Browser          | Firefox/Chrome |
| Operating System | n/a |

### Additional context
https://github.com/material-components/material-components-web/issues/6641 might have the same issue.

### Possible solution
That is because, the `div.mdc-tooltip__surface` (label container) is missing the `mdc-tooltip__surface-animation` css class. If that class exists, the [`mdc-tooltip--showing-transition`](https://unpkg.com/browse/material-components-web@11.0.0/dist/material-components-web.css#L15041) or `
mdc-tooltip--hide-transition` class causes an animation on that element. The tooltip [listenes on animation events](https://github.com/material-components/material-components-web/blob/633a9fc7a98d0d9bdc177bc9ccbd49beb25bd5b6/packages/mdc-tooltip/component.ts#L101) to finally close itself. If there is no animation in the first place, the tooltip never closes.

See fix: https://jsfiddle.net/3emy0hsz/2/

**Comment by joyzhong** [comment]
Thanks for reporting!

It seems this is fixed in our [most recent docs](https://github.com/material-components/material-components-web/blob/master/packages/mdc-tooltip/README.md#plain-tooltip-example). We will update the m.io docs with our next release, so closing this.
