### ISSUE TITLE
Allow Appbar logo Size change attributes

### ISSUE THREAD

**Issue by VaibhavNalawade** [material-components/material-components-web#7161]
we cannot change size of logo on appbar Android

**Comment by sayris** [comment]
Hi!
Thanks for the feature request -- would you mind providing a little more context. Specifically
- Which component are you referring to? (Do you mean [top app bar](https://github.com/material-components/material-components-web/tree/master/packages/mdc-top-app-bar)?)
- What piece of the component is the "logo"? (Screenshots and pointers to html are helpful.) If the logo is a component in and of itself (e.g. an icon button) -- there might  be existing mixins to configure the size (e.g. for icon button we have a [`size`](https://github.com/material-components/material-components-web/blob/2daa49b35a67a13ac0b2ec19d25fbb37bbcf1920/packages/mdc-icon-button/_mixins.scss#L127) and [`icon-size`](https://github.com/material-components/material-components-web/blob/2daa49b35a67a13ac0b2ec19d25fbb37bbcf1920/packages/mdc-icon-button/_mixins.scss#L148) mixin).

**Comment by VaibhavNalawade** [comment]
still there are some padding on top and bottom fixed issue with increasing size of logo
