### ISSUE TITLE
Figma, AdobeXD & Sketch is not current. When will it be useful? 

### ISSUE THREAD

**Issue by GrooveCS** [material-components/material-components-web#7166]
## Feature Request

Our creative team will not consider Material.IO because the design material for 

1. Adobe XD
2. Figma
3. Sketch

is not current and incomplete. We see active development on the Web, Android, and Flutter, yet it is hard to get your team to consider using incomplete information. 

When will they be updated and aligned with the current state of material.io web components? 

### Proposed solution

Update all support design system tools to be aligned with the current versions of material.io components. 
### Alternatives considered

We are evaluating 

1. PatternFly
2. Fluent.design 
3. A few others 

to see if they have more mature resources. 

### Additional context

Resources
-  [Material Resources](https://material.io/resources)
- [Figma](https://www.figma.com/community/file/778763161265841481)

**Comment by allan-chen** [comment]
Moved the issue to the general MDC repo. Closing this for now.
