### ISSUE TITLE
 MDC-Web Framework Integration Example for React  running  incorrect in ie  or edge

### ISSUE THREAD

**Issue by hanyuzhou2006** [material-components/material-components-web#717]
## Bugs

 MDC-Web Framework Integration Example for React  running  incorrect in ie  or edge

### What MDC-Web Version are you using?

> mdc-web-example-react@1.0.0

### What browser(s) is this bug affecting?

> Internet Explorer 11.1198.14393.0 , Microsoft Edge 38.14393.1066.0

### What OS are you using?

> windows 10.0.14393

### What are the steps to reproduce the bug?

> 1. run the demo server
> 2. go to localhost:3000/
> 3. click the checkbox

### What is the expected behavior?

> the checkbox will be checked 

### What is the actual behavior?

> the checkbox not be checked.

**Comment by yeelan0319** [comment]
Hi @hanyuzhou2006 

Thanks for filing the bug, we created a PR for correcting the bug. 

The thing happened seems to be IE11/Edge is not firing/retrieving the `checked` property with the correct order, so it retrieve the old state (where `checked = false`) and set it as the current state. We found a walk around by removing the `checked` property binds on `Checkbox`.
