### ISSUE TITLE
[MDC-RIPPLE] Ripple fires twice if page is zoomed in

### ISSUE THREAD

**Issue by MaximBalaganskiy** [material-components/material-components-web#7207]
## Bug report
Ripple is rendered incorrectly on iOS devices

### Steps to reproduce
1. Go to https://material.io/components/buttons#interactive-demo
2. Click on the button

### Actual behavior
The ripple is rendered in two places

### Expected behavior
The ripple expands from a single point

### Screenshots
![20210629_093851000_iOS](https://user-images.githubusercontent.com/3712700/123776294-82153a00-d912-11eb-83a4-7c3845284106.gif)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Chrome
| Operating System | iOS

### Additional context
Might be related to https://github.com/material-components/material-components-web/issues/6357.
The issue does not manifest in safari.
Happens to any ripple, not just buttons.

**Comment by joyzhong** [comment]
Are you able to repro this in https://codepen.io/joyzhong/pen/RwVpwoV? Unfortunately the catalog demo is out of date.

**Comment by MaximBalaganskiy** [comment]
I cannot reproduce this anymore, neither in your codepen nor in the catalog.
Unfortunately, I did not take notice of any chrome updates on my iOS devices.

There's another issue thought with the ripple - it fires twice in chrome if a page is zoomed in.

**Comment by joyzhong** [comment]
Thanks, renamed this bug. Can you confirm this is on iOS/Chrome, and are there any other environments you're able to repro in? I'm not able to repro on MacOS/Chrome.

**Comment by MaximBalaganskiy** [comment]
This is on iOS in chrome, only when zoomed in. Btw, the original bug manifested again. It gets resolved when chrome is restarted, so it's probably not an MDC issue.

**Comment by patrickrodee** [comment]
We're closing this as part of bug clean up. If this issue still persists, please file a new bug with browser and OS version info. FYI, this _may_ be a browser-specific bug.
