### ISSUE TITLE
IconToggle (MDCIconToggle) does not update when "on" property is changed

### ISSUE THREAD

**Issue by ElmarJ** [material-components/material-components-web#721]
### What MDC-Web Version are you using?

> 0.11.1

### What browser(s) is this bug affecting?

> Chrome

### What OS are you using?

> Windows

### What are the steps to reproduce the bug?
See code below (or in attachment). Clicking the button should change the toggle icon state, but it doesn't.

```
<!DOCTYPE html>
<html class="mdc-typography">

<head>
    <title>HubbleBubble html</title>
    <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
    <i id="toggle" class="mdc-icon-toggle material-icons" role="button" tabindex="0" data-toggle-on='{"label": "Undone", "content": "check_circle"}' data-toggle-off='{"label": "Done", "content": "done"}'>done</i>
    <button onclick="buttonclick();">toggle toggle</button>
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.js"></script>
    <script>
        mdc.autoInit()
    </script>

    <script>
        document.onload =
            function() {
                document.getElementById("toggle").attachTo(document.querySelector('.mdc-icon-toggle'));
            };

        function buttonclick() {
            var toggle = new mdc.iconToggle.MDCIconToggle(document.getElementById("toggle"));
            toggle.on != toggle.on;
        }
    </script>

</body>

</html>
```

### What `is` the expected behavior?

Toggle icon should change state when button is clicked according to documentation. See https://material.io/components/web/catalog/buttons/icon-toggle-buttons/ ("MDCIconToggle.on: Boolean. Returns whether or not the icon toggle is currently toggled on. [i]Setting this property will update the toggle state.[/i]")

### What is the actual behavior?

Icon should toggle when "on" value  is changed.

### Any other information you believe would be useful?
Zipped version of code above: 
[index.zip](https://github.com/material-components/material-components-web/files/1029737/index.zip)

**Comment by ElmarJ** [comment]
I'm so sorry, I realize I made a stupid mistake (instantiating the element twice). Please close.

**Comment by amsheehan** [comment]
No problem 👍
