### ISSUE TITLE
[MDC-Tooltip] MDCTooltip JavaScript Methods Not Functional

### ISSUE THREAD

**Issue by tonyliunyc** [material-components/material-components-web#7235]
## Bug report
After initialization of the `MDCTooltip` object, the methods `isShown()`, `hide()` don't seem to be working. 

### Steps to reproduce
1.  Create elements 
```html
<div id="tooltip-id" class="mdc-tooltip" role="tooltip" aria-hidden="true">
  <div class="mdc-tooltip__surface">
    lorem ipsum dolor
  </div>
</div>
<a aria-describedby="tooltip-id" href="www.google.com"> Link </a>
```
in an HTML file. 
2. Include the scripts in HTML:
```html
<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
<script>
let tooltipElement = document.querySelector('.mdc-tooltip');
let tooltip = new mdc.tooltip.MDCTooltip(tooltipElement);

document.querySelector("[aria-describedby='tooltip-id']").addEventListener('mouseout', function () {
  tooltip.hide(); // doesn't work
  console.log(tooltip.isShown()); // returns undefined; supposed to return false
})
</script>
```
You can also use the JS imports in the node environment instead of directly using the web package to reproduce.
3. `npm i @material/tooltip`, add `@use "@material/tooltip/styles";` to scss
3. Render webpage. Hover over the link, then mouseout
4. Check web console: returns undefined and tooltip is still visible

### Actual behavior
Tooltip still visible, returns `undefined`

### Expected behavior
Hides tooltip, returns `false`

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 11.0.0 (latest) |
| Browser          | Chrome: Version 91.0.4472.114 (Official Build) (arm64) |
| Operating System | macOS 11.4 |

**Comment by joyzhong** [comment]
Was able to repro in https://codepen.io/joyzhong/pen/abWWpdx.

The `hide()` method is invoked on mouseout, but it seems we only remove the SHOWN, not SHOWING class: https://github.com/material-components/material-components-web/blob/d5f1f7c722ada3b62265e12e47a6f714d5bd7351/packages/mdc-tooltip/foundation.ts#L438, such that the tooltip remains shown.

**Comment by sayris** [comment]
Thanks for flagging this. I have a PR to fix the issue with the `isShown()` method.

The issue with `hide()` is coming from a missing class in your html -- you're missing an `mdc-tooltip__surface-animation` class, so the html should be:

```
<div id="tooltip-id" class="mdc-tooltip" role="tooltip" aria-hidden="true">
  <div class="mdc-tooltip__surface mdc-tooltip__surface-animation">
    lorem ipsum dolor
  </div>
</div>
<a aria-describedby="tooltip-id" href="www.google.com"> Link </a>
```

(This missing class results in no `transitionend` event being triggered, and so the SHOWING class is never removed).

**Comment by tonyliunyc** [comment]
Thanks for the timely response! I was following the guidance on the [Material Web Components for tooltips](https://material.io/components/tooltips/web#tooltips) (See Plain Tooltip Example) and the `mdc-tooltip__surface-animation` class was missing there. Hope it can also be fixed on the material website so future users won't run into the same issue.
