### ISSUE TITLE
Grid List demo has one example that does not behave as expected when changing window size

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#724]
### What MDC-Web Version are you using?

0.11.0

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

macOS v10.12.4

### What are the steps to reproduce the bug?

1. Open [demo](http://material-components-web.appspot.com/grid-list.html)
1. Resize window

### What is the expected behavior?

Each example resizes and flows uniformly

### What is the actual behavior?

The second example does not conform to the behavior of the others

### Any other information you believe would be useful?

![screen shot 2017-05-25 at 4 27 54 pm](https://cloud.githubusercontent.com/assets/1578263/26469344/a938b87e-4167-11e7-888a-10b247467b04.png)

**Comment by traviskaufman** [comment]
Cannot repro on my machine. @amsheehan assigning to you to triage on a large monitor and if there's no bug, close it.
