### ISSUE TITLE
[MDC-Tooltip] Tooltip Doesn't Hide Immediately After mouseout (mixin "exit-transition" is undefined)

### ISSUE THREAD

**Issue by tonyliunyc** [material-components/material-components-web#7246]
## Bug report
I'd like to hide the tooltip immediately with a quick transition after the cursor moves away from the target element. The default transition seems to take a second or so to take place. (The desired effect is on the [Tooltip - Behavior on material.io](https://material.io/components/tooltips#behavior) but I can't get it to work) I tried to fix this by setting the mixin `exit-transition`, but was told by the sass compiler that the mixin `exit-transition` is undefined.

### Steps to reproduce
1. Create HTML elements:
```html
<div id="tooltip-id" class="mdc-tooltip" role="tooltip" aria-hidden="true">
  <div class="mdc-tooltip__surface mdc-tooltip__surface-animation">
    lorem ipsum dolor
  </div>
</div>
<a aria-describedby="tooltip-id" href="www.google.com"> Link </a>
```
2. JS Instantiation
```js
import {MDCTooltip} from '@material/tooltip';
const tooltip = new MDCTooltip(document.querySelector('.mdc-tooltip'));
```
3. SASS
```scss
@use "@material/tooltip/styles";
@use "@material/tooltip";

.mdc-tooltip {
    @include tooltip.exit-transition(0s); // error
}
```
3. While converting to CSS, sass compiler returns 
```
Error: Undefined mixin.
   ╷
5  │     @include tooltip.exit-transition(0s);
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```
### Actual behavior
After mouseout, it takes a second or so for the tooltip to fade out. The mixin `exit-transition` is undefined.

### Expected behavior
Hides the tooltip immediately after mouseout [just as demonstrated on the design guidelines](https://material.io/components/tooltips#behavior). Should be able to use the mixin `exit-transition` without errors.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 11.0.0 (latest) |
| Browser          | Chrome: Version 91.0.4472.114 (Official Build) (arm64) |
| Operating System | macOS 11.4 |

### Additional context

 I also tested `show-transition`, and interestingly, `show-transition` went through the compiler with no errors. I tried searching `exit-transition` in my `@material/tooltip` folder and got no results except the `README.md` file.

### Follow-up Question
I'm new to this community so forgive me if I'm asking questions with obvious answers. I recently raised another issue related to MDC-Tooltip - the responses were timely and very helpful. I checked the pull requests and found that the issue has been fixed and merged to the master branch - but when I try to install it from npm using `npm i @material/tooltip`, it still seems to give me the old version. How would I be able to get the latest version and how often is the latest version pushed to npm?

**Comment by brandondiamond** [comment]
Hi Tony -- thanks so much for this bug report. Could you please provide a minimal glitch/codepen/etc that reproduces this issue? Thank you!

**Comment by brandondiamond** [comment]
Hi Tony -- thank you for this super detailed report! Have you been able to use the `hide-transition` mixin? This may do exactly what you'd like. For an authoritative listing of all supported mixins, you can browse through the code in this repo directly. `_tooltip-theme.scss` contains all of the mixins available for use with tooltip. Hope this helps!

**Comment by tonyliunyc** [comment]
I just tried the `hide-transition` mixin - my sass compiler run with no errors, but the mixin doesn't seem to have any effect. I changed it from 0s to 10s and 100s, and I think it has no impact on how soon the transition happens after the cursor moves away from the element. Any idea on how I can make the tooltip hide _immediately_ after mouseout?

**Comment by sayris** [comment]
Hello! 

The `hide-transition` mixin actually configures the animation duration for hiding the tooltip. I think what you'll actually want to use is the [`setHideDelay`](https://github.com/material-components/material-components-web/blob/08db3d737fa49893d1c3d1d3f7dd07367dd9eaeb/packages/mdc-tooltip/component.ts#L147) method defined in the tooltip component -- to make a tooltip hide immediately you can call `tooltip.setHideDelay(0)`.

**Comment by tonyliunyc** [comment]
@sayris Appreciate you help! I tried the `setHideDelay` method but it seems that I don't have the latest version of the package from GitHub and I get the error `Uncaught TypeError: MDC_tooltip.setHideDelay is not a function`. Sorry that I'm new to this community - how would I be able to always get the latest version of the packages (should I instruct npm to download from GitHub?) Also since it's related, would you mind taking a look at my follow-up question? Thanks.

**Comment by sayris** [comment]
Ah, looks like that method was added after the last release (v11).
I just rolled out a new release, so using MDC version 12.0.0 should give you that function.

**Comment by tonyliunyc** [comment]
@sayris Great! It's working now. Thanks a lot for your help. 

Quick follow-up: How often does your team typically release a new version to npm?

**Comment by sayris** [comment]
Glad it's working! To be honest we don't have a particularly strict release schedule... we try and do a new release at least every few months.
