### ISSUE TITLE
[MDC-Data-Table] thead > tr > th values are not bold as shown in the example

### ISSUE THREAD

**Issue by mhitza** [material-components/material-components-web#7264]
https://codepen.io/mhitza/pen/VwbyJar

## Bug report
Table heading columns do not have an increased font weight/boldness as depicted in the screenshot at https://github.com/material-components/material-components-web/tree/master/packages/mdc-data-table

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | v11.0.0 |
| Browser          | Chrome Version 92.0.4515.107 (Official Build) (64-bit) / Firefox 90.0.2 |
| Operating System | Linux (Fedora 34 XFCE)

**Comment by sayris** [comment]
Hi!

What browser/OS are you using? Opening your linked codepen I am seeing the expected styling -- that is the header cells have a font-weight of 500 (compared to that of the data table content that has a font-weight of 400)

![subtitle2-datatable.png](https://images.zenhubusercontent.com/5f84b5449b473aa3f03794a9/353d0760-e4ae-47eb-8ddd-9bee5e7d9e7d)

![body2-datatable.png](https://images.zenhubusercontent.com/5f84b5449b473aa3f03794a9/038e7a28-5a12-4a64-bc1e-0667cef13b2e)

**Comment by mhitza** [comment]
That's interesting!

Both Chrome/Firefox on Linux the th/td text looks the same even if I see the same weights as in your screenshot. I'll update the ticket table with browser/OS info.

**Comment by EskiMojo14** [comment]
Adding `https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap` as an external stylesheet causes it to display correctly: 
![image](https://user-images.githubusercontent.com/18308300/128481595-ec9552e7-0fc1-47cc-8e5a-f935ec865edc.png)
It looks like it's not importing the medium weight - which isn't possible to notice if you have it installed.
