### ISSUE TITLE
FR: Mega/Mini footer

### ISSUE THREAD

**Issue by Shyam-Chen** [material-components/material-components-web#727]

**Comment by robzenn92** [comment]
This might be interesting, however the only "footer" (in material design) I am thinking of is the [Bottom navigation](https://material.io/guidelines/components/bottom-navigation.html). Have a look at [#59](https://github.com/material-components/material-components-web/issues/59). I don't know whether there is a material design guideline for a mega/mini footer that other frameworks have.

**Comment by Garbee** [comment]
@robzenn92 Is correct on there being no MD Spec for footers. Which is one reason they were not added to the original MDL V2 roadmap. We urged onto going as close to the spec on components as possible and leaving the extra web-specific bits out until the spec team handles their design.

**Comment by traviskaufman** [comment]
As @Garbee mentioned, as part of our [official policy](https://github.com/material-components/material-components/blob/develop/COMPONENTS_REQUEST_POLICY.md#general-policy) we only build components that are documented in the spec. If there's enough interest you could open a "RFC" issue requesting these items with an explanation / justification as to why they would be useful (use cases, adherence to being "Material Design", etc.) and we could pass that along to our UX designers.
