### ISSUE TITLE
[MDC-Select] v12: _select.scss Undefined mixin 

### ISSUE THREAD

**Issue by tonyliunyc** [material-components/material-components-web#7271]
## Bug report
v12 MDC Select throws `Undefined Mixin` error when compiling sass.

### Steps to reproduce
1. Install latest select package:
```
npm install @material/select@12.0.0
```
2. In a SCSS file, import:
```
@use "@material/list/mdc-list";
@use "@material/menu-surface/mdc-menu-surface";
@use "@material/menu/mdc-menu";
@use "@material/select/styles";
```
3. See error from compiler
```
Error: Undefined mixin.
    ╷
96  │ ┌     @include dom-mixins.forced-colors-mode() {
97  │ │       $gray-text: (
98  │ │         disabled: GrayText,
99  │ │       );
100 │ │       @include select-theme.ink-color($gray-text, $query: $query);
101 │ │       @include select-theme.dropdown-icon-color(
102 │ │         (
103 │ │           disabled: red,
104 │ │         ),
105 │ │         $query: $query
106 │ │       );
107 │ │       @include select-theme.label-color($gray-text, $query: $query);
108 │ │       @include select-theme.bottom-line-color($gray-text, $query: $query);
109 │ │       @include select-theme.outline-color($gray-text, $query: $query);
110 │ │       @include select-icon-theme.icon-color($gray-text, $query: $query);
111 │ │       @include select-helper-text-theme.helper-text-color(
112 │ │         $gray-text,
113 │ │         $query: $query
114 │ │       );
115 │ └     }
```

### Actual behavior
scss compiler throws the error

### Expected behavior
Imports styles with no errors

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 12.0.0 |
| Browser          | Chrome@latest |
| Operating System | macOS 11.4 |

### Additional context
v11 works perfectly but shows this error when I update to v12.

### Possible solution
Downgrade to v11? `npm install @material/select@11.0.0`

**Comment by sayris** [comment]
Have you [updated](https://github.com/material-components/material-components-web/tree/master/packages/mdc-dom#installation) the dom package to v12 (looks like the `forced-color-mode` mixin is new to v12).

There is a command to install all the components to ensure the versions don't get out of sync ([instructions here](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#installing-locally)).

Thanks!

**Comment by allan-chen** [comment]
Closing, let us know if this still an issue after upgrading the `@material/dom` package. Thanks!
