### ISSUE TITLE
[MDC-Switch] Not rendering properly

### ISSUE THREAD

**Issue by mhitza** [material-components/material-components-web#7282]
https://codepen.io/mhitza/pen/gOWjyrG

## Bug report
I noticed that the switch markup must have been changed recently (compared to the reference docs on material.io) using a button instead of wrappings around an input element. However this new format doesn't render as a switch at all in either Chrome or Firefox

### Screenshots
Chrome
![chrome](https://user-images.githubusercontent.com/273079/128082942-785e1edf-3cfa-445e-a8e2-97934e44944d.png)

Firefox
![firefox](https://user-images.githubusercontent.com/273079/128082976-6783a4e4-e47a-45d2-986d-240398a0416e.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | v12.0.0 |
| Browser          |  Chrome 92.0.4515.107 (Official Build) (64-bit) / Firefox 90.0.2 |
| Operating System | Linux (Fedora 34 XFCE) |

**Comment by allan-chen** [comment]
It appears that the new switch styles were not built into the release. @asyncLiz, could you take a look?

https://github.com/material-components/material-components-web/blob/8f68de8f3b9722c6a491e55b0b2da284361441ef/scripts/webpack/css-bundle-factory.js#L177

**Comment by mhitza** [comment]
For what it's worth I noticed the same issue moments ago with the `mdc-evolution-chip*` classes. Those do not show up in the release build, only the deprecated classes.

**Comment by asyncLiz** [comment]
I believe this got overlooked in the last release, sending a PR out to fix it!

**Comment by allan-chen** [comment]
@patrickrodee for visibility for chips build still using deprecated CSS
