### ISSUE TITLE
[Button] contained button missing ripple span in docs?

### ISSUE THREAD

**Issue by markborner** [material-components/material-components-web#7283]
## Bug report
I'm wondering why the example HTML for a contained button is missing a span with class "mdc-button__ripple".  Is this a bug with the documentation?

### Steps to reproduce
1. Specify a contained button per the docs without a ripple span

```html
        <button className="mdc-button mdc-button--raised" ref={buttonElement}>
            <span className="mdc-button__label">{props.children}</span>
        </button>
```

Note: I'm using React which is why I have ref={buttonElement} and {props.children}.  I am instantiating the ripple as such:

```javascript
    useEffect(() => {
        const ripple = new MDCRipple(buttonElement.current);
        return () => {
            ripple.destroy();
        }
    });
```

### Actual behavior
No ripple when button clicked.

### Expected behavior
I would expect there to be ripple on contained buttons - is that correct?

If I add the ripple span:

```html
        <button className="mdc-button mdc-button--raised" ref={buttonElement}>
            <span className="mdc-button__ripple"></span>
            <span className="mdc-button__label">{props.children}</span>
        </button>
```
Then when the button is clicked, it has a ripple.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 12.0.0
| Browser          | Chrome
| Operating System | MacOS

**Comment by allan-chen** [comment]
Thanks for pointing this out! Indeed it's a doc bug, sending a quick PR to fix.
