### ISSUE TITLE
[mdc-layout-grid] Code and website do not match the spec ITO breakpoints and body widths

### ISSUE THREAD

**Issue by glen-84** [material-components/material-components-web#7295]
## Bug report

MC web and the material.io website don't appear to follow the spec with regard to breakpoints and body widths.

### Steps to reproduce

1. View the [layout variables](https://github.com/material-components/material-components-web/blob/b47dd37a6e9e49bf40cfec82d55b5486efc7831f/packages/mdc-layout-grid/_variables.scss), or visit the website.
2. Try to find any similarity between the spec and what is used above.

### Actual behavior

- The layout variables only include 3 BPs, and the desktop BP doesn't match the spec.
- The website appears to use different BPs, and has a body of 1240px as opposed to the 1040px max in the spec.

### Expected behavior

I expected the code and website to match the spec exactly.

### Screenshots

n/a

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 12.0.0
| Browser          | Any
| Operating System | Windows 10

### Additional context

I'm urgently seeking confirmation of the current breakpoint and body width recommendations from the design/UX team. With the main website and examples like [this](https://material-template-portfolio-css.glitch.me/) having a width around 1200px, but the spec suggesting 1040px (a bit narrow?), it's very difficult to follow.

1040px also seems like an odd size, not being evenly divisible by 12.

### Possible solution

Update the spec and the website/examples to be consistent. Consider whether 1040px is appropriate for desktop devices.

**Comment by patrickrodee** [comment]
Thanks for reporting this. We'll let the Material.io folks know!
