### ISSUE TITLE
[MDCSelect] Empty option label not allowed

### ISSUE THREAD

**Issue by myovchev** [material-components/material-components-web#7303]
## Bug report
Select is filtering out options with empty labels, thus making impossible to render menu with an empty option. Once an option is chosen for an optional select field, the user is not allowed to reset the select to empty value state. 
This behaviour starts from v11, empty options are rendered properly in v10.

### Steps to reproduce
[Code pen demonstrating the problem](https://codepen.io/myovchev/pen/RwVqBZv)
The code for outlined select variant from the official documentation is used in the demo, and the problem is present for every select variant.

### Actual behavior
Select doesn't render option with empty label

### Expected behavior
Render options with empty label and value

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 12.0.0
| Browser          |  Brave 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)
| Operating System | Ubuntu 20

**Comment by myovchev** [comment]
In case you are wandering why selects behave/look funny - here are some answers:
- https://github.com/material-components/material-components-web/issues/7291
- https://github.com/material-components/material-components-web/issues/7013#issuecomment-827034121

So current list (v12) state is kinda broken (everything is deprecated, evolution is not yet applied)

**Comment by myovchev** [comment]
My last update here. It seems v12 (actually starting from v 11) select is in incomplete state. It uses list, which has no stable version. There are "deprecated-" classes and mixins and "evolition" escape hatch. I might be not familiar with this library release cycle, but I'm pretty much sure those are NOT stable releases. The only reason I've entered this nightmare (v10 looked like pretty stable) was the extremely annoying and unstoppable SASS warning about their great division deprecation... I'll reconsider carefully using any component from this library in the future.

  For those stuck in the loop, here is a temporary solution with awful hacks. 
- move to list evolution mixin (including core-styles) - details in the issues I've posted above.
- your select `selected` text will be broken because of new node structure in list and apparently not updated adapter of the select. In order to fix this you need something ugly like that (I've lost 2 days investigating the whole and I don't have more time to investigate "nice solutions" if there are any at all)
```js
// Initialize all selects
const selects = Array.from(document.querySelectorAll('.mdc-select'));
selects.forEach(el => this.selects.push(new MDCSelect(el)));
// Hack them
const fixSelect = (select) => {
  // this might come handy if it's already fixed by some update
  if (select.selectedText.innerHTML) {
    return;
  }
  const selected = select.root.querySelector('.mdc-list-item--selected .mdc-list-item__text');
  // you need to wait for the next tick 
  setTimeout(() => {
    select.selectedText.innerHTML = selected.innerHTML;
  }, 0);
};

selects.forEach(select => {
  select.listen('MDCSelect:change', () => fixSelect(select));
  setTimeout(() => fixSelect(select), 0);
});
```

Another approach will be to go for `deprecated-` prefix for all css class names you see from the documentation and use the `deprecated-` mixins when styling the list component. I'm not sure this will work with the select foundation though, so you'd might need more ugly hacks.

**Comment by asyncLiz** [comment]
I'm not able to reproduce this issue. Here's an example jsbin at v12 with select and a menu with an empty option.

https://jsbin.com/faxacisifi/edit?html,output

The current select component should [continue to use the old list implementation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#important-changes) (`.mdc-list-deprecated`). Adding the old list classes to your markup seems to fix the issue (the CSS styles are simply not loading).

You can use the new list, but you'll need to load the new list's CSS separately, not from the main bundled `material-components-web.min.css` file.
