### ISSUE TITLE
Change size of mdc-checkbox

### ISSUE THREAD

**Issue by adinu** [material-components/material-components-web#7322]
Hi guys, 

is there an easy way to change the size of the checkbox? (currently the default is 40px/40px let's say i want it 120px/120px)

i tried to override the css but it seems like there are lots of classes i need to change, maybe there is a simpler way.

**Comment by EstebanG23** [comment]
Hi there, currently there is no support to changing the size of the checkbox. Not sure what your use case is but if its touch target an alternative could be to manipulate the ripple surface. More info: https://github.com/material-components/material-components-web/tree/master/packages/mdc-touch-target#touch-target
