### ISSUE TITLE
Permanent Drawer Above Toolbar's layout is incorrect on mobile device

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#733]
### What MDC-Web Version are you using?

> 0.11.1

### What browser(s) is this bug affecting?

> Mobile Safari, Mobile Chrome

### What OS are you using?

> iOS 10.2.1, Android O

### What are the steps to reproduce the bug?

> 1. go to [Permanent Drawer Above Toolbar](http://material-components-web.appspot.com/drawer/permanent-drawer-above-toolbar.html) page on mobile device

### What is the expected behavior?

> Should look similar to [Permanent Drawer Below Toolbar](http://material-components-web.appspot.com/drawer/permanent-drawer-below-toolbar.html)

### What is the actual behavior?

> Permanent drawer is not there

**Comment by traviskaufman** [comment]
Because this is purely demonstrative of a desktop-style layout, and because in a real-world app this would probably switch to a more mobile-friendly layout on smaller devices, marking this as help wanted, with the solve being:

- [ ] Add `min-width: 715px` to the `.demo-body` selector within the `<style>` tag to https://github.com/material-components/material-components-web/blob/master/demos/drawer/permanent-drawer-above-toolbar.html
- [ ] Do the same with https://github.com/material-components/material-components-web/blob/master/demos/drawer/permanent-drawer-below-toolbar.html

**Comment by lynnjepsen** [comment]
Sorry for the confusion here...but I don't think it makes sense to fix this issue through purely demonstrative code. I think the CSS for mdc-drawer should handle this case, not the _demo_ CSS for mdc-drawer.

I also cannot figure out where the "715px" came from...

I'm going to remove the "help-wanted" from this issue so we can re-triage it

**Comment by lynnjepsen** [comment]
Also, here are some screenshots:

Permanent drawer above toolbar on mobile:
![klslpq81bu4](https://user-images.githubusercontent.com/4703432/34186202-247d6aaa-e4df-11e7-9bf8-b38cc55cbbb6.png)

Permanent drawer below toolbar on mobile
![szfrfvcqnwr](https://user-images.githubusercontent.com/4703432/34186217-37626238-e4df-11e7-9cfe-1759c845081c.png)

**Comment by moog16** [comment]
@yeelan0319 is this still an issue? The above/below drawer look as they do on desktop. 


<img width="417" alt="screen shot 2018-01-04 at 15 19 13" src="https://user-images.githubusercontent.com/579873/34588598-b81942fe-f162-11e7-9b7d-24e372b952ec.png">
<img width="414" alt="screen shot 2018-01-04 at 15 19 26" src="https://user-images.githubusercontent.com/579873/34588599-b83423ee-f162-11e7-9f4d-e31f4475633e.png">

**Comment by kfranqueiro** [comment]
I just checked, and can confirm I see the problem in 0.11.1 as reported, but not in recent versions, so I think this is obsolete.

It seems like if nothing else, the effective size/layout of our demo page on mobile devices changed. Around v0.18.0, it the demo page was zoomed in further, so I had to scroll horizontally but could still see both the drawer and the other content.
