### ISSUE TITLE
[MDC Card] Documentation for web implementation incomplete

### ISSUE THREAD

**Issue by ohcibi** [material-components/material-components-web#7345]
There are several examples that show a 'title'  of a card outside the 'media'. The cards documentation is not mentioning it though. 

Heres some examples where I found that 'title' 
* In the anatomy section there is a 'primary title' which - as I said - is not further documented in the api. Either the documentation is super bad or someone forgot to add it. 
* The 'interactive demo'  in its 'based variant'  has a primary title class too in the 'source' tab

**Comment by joyzhong** [comment]
I don't believe the "title" is directly implemented in / related to the cards implementation. Please see the [typography docs](https://github.com/material-components/material-components-web/blob/master/packages/mdc-typography/README.md) for more details on achieving the desired styling for headers, etc.

Feel free to reopen with more context (links, screenshots, etc.) if I've misunderstood.
