### ISSUE TITLE
Switch demo bind to a wrong label

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#735]
### What MDC-Web Version are you using?

> 0.11.1

### What are the steps to reproduce the bug?

> 1. Open [switch](http://material-components-web.appspot.com/switch.html) in catelog
> 2. click the first example label

### What is the expected behavior?

> The switch to the left of it should toggle

### What is the actual behavior?

> The hero switch toggled.

### Any other information you believe would be useful?

Both of it have `id = basic-switch` is why it is causing the problem.

**Comment by traviskaufman** [comment]
@yeelan0319 fix is straightforward enough that we don't need to triage; we can just submit a PR for it.
