### ISSUE TITLE
Toolbar demo page completely jammed on mobile safari

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#736]
### What MDC-Web Version are you using?

> 0.11.1

### What browser are you using?

> Mobile Safari

### What version of OS are you using?

> iOS 10.2.1

### What are the steps to reproduce the bug?

> 1. Open [toolbar](http://material-components-web.appspot.com/toolbar.html) in catelog on mobile safari

### What is the expected behavior?

> Examples are layout correctly to play with

### What is the actual behavior?

> But they all jammed together...

**Comment by traviskaufman** [comment]
Rolling into #607
