### ISSUE TITLE
[MDC-BANNER] TS files are included in the module package

### ISSUE THREAD

**Issue by MaximBalaganskiy** [material-components/material-components-web#7360]
## Bug report
Source `ts` files are included in the bundle which causes typescript to try to compile them.
Which would be fine if not for the `setTimer` typing error.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 12.0

**Comment by asyncLiz** [comment]
Hi! Can you post your `tsconfig.json` for your project? This problem often presents when overriding the `"excludes"` member and not adding `"./node_modules"` to the array. 

See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler

**Comment by MaximBalaganskiy** [comment]
```json
{
	"compilerOptions": {
		"module": "es2015",
		"moduleResolution": "node",
		"target": "es5",
		"sourceMap": true,
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"skipDefaultLibCheck": true,
		"strict": false,
		"skipLibCheck": true,
		"lib": [ "es2017", "dom" ],
		"downlevelIteration": true,
		"importHelpers": true,
		"resolveJsonModule": true,
		"allowSyntheticDefaultImports": true,
	},
	"exclude": [ "bin", "node_modules" ],
	"atom": { "rewriteTsconfig": false }
}
I think this is related to https://github.com/material-components/material-components-web/issues/7367
```

**Comment by MaximBalaganskiy** [comment]
While swapping `module` to dist folder works it might pull a lot of unused code.

**Comment by asyncLiz** [comment]
> module points to ./index.js thus forcing WP to bundle from package root, not dist.

This would be the expected behavior when loading ES modules instead of the bundled CommonJS dist file. What Typescript files are being included?

**Comment by MaximBalaganskiy** [comment]
The ones which are exported by index.js.
Exclude option does not have an effect on this case

**Comment by MaximBalaganskiy** [comment]
Here is the reproduction https://github.com/MaximBalaganskiy/banner-issue

**Comment by asyncLiz** [comment]
Gotcha, specifically it looks like the problem is the banner package folder is missing its [`.npmignore` file](https://github.com/material-components/material-components-web/blob/master/packages/mdc-checkbox/.npmignore), which should be removing the original `.ts` source files from being distributed.

This should be a simple fix by copying the `.npmignore` file from another directory. Would you mind sending in a PR?
