### ISSUE TITLE
Switch toggle not working for me

### ISSUE THREAD

**Issue by adinu** [material-components/material-components-web#7362]
I am trying to add MDCSwitch to a simple html site (with javascript), it isn't the first time i am adding material-io components, however for some reason the switch isn't working as expected.

it seems like the toggle isn't working and i get an error "getBoundingClientRect" in the console

this is the complete code i am using:
https://codepen.io/adi-mor-the-vuer/pen/qBjbLKx

this is the js code i am using (besides inserting the material-io js and css file):
`window.addEventListener("load", function() {
    var select = new mdc.switchControl.MDCSwitch(document.querySelectorAll('.mdc-switch')[0]);
});
`

please help me out.

**Comment by marton987** [comment]
Looking at the codepen, you're using latest which is [12.0.0](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#1200-2021-07-27) and the switch logic changed a bit.

You can use a previous version: https://codepen.io/marton987/pen/abwNyay
```html
<div class="mdc-switch__ripple"></div>
  <div class="mdc-switch__track"></div>
  <div class="mdc-switch__thumb-underlay">
    <div class="mdc-switch__thumb">
      <input
        type="checkbox"
        id="basic-switch"
        class="mdc-switch__native-control"
        role="switch"
        checked
      />
    </div>
  </div>
</div>
<label for="basic-switch">disable/enable</label>
<script src="https://unpkg.com/material-components-web@11.0.0/dist/material-components-web.js"></script>
```

Or migrate to the newest: https://codepen.io/marton987/pen/ZEyWJPB
```html
<button
  id="basic-switch"
  class="mdc-switch mdc-switch--unselected"
  type="button"
  role="switch"
  aria-checked="false"
>
  <div class="mdc-switch__track"></div>
  <div class="mdc-switch__handle-track">
    <div class="mdc-switch__handle">
      <div class="mdc-switch__shadow">
        <div class="mdc-elevation-overlay"></div>
      </div>
      <div class="mdc-switch__ripple"></div>
      <div class="mdc-switch__icons">
        <svg
          class="mdc-switch__icon mdc-switch__icon--on"
          viewBox="0 0 24 24"
        >
          <path
            d="M19.69,5.23L8.96,15.96l-4.23-4.23L2.96,13.5l6,6L21.46,7L19.69,5.23z"
          />
        </svg>
        <svg
          class="mdc-switch__icon mdc-switch__icon--off"
          viewBox="0 0 24 24"
        >
          <path d="M20 13H4v-2h16v2z" />
        </svg>
      </div>
    </div>
  </div>
</button>
<label for="basic-switch">off/on</label>
<script src="https://unpkg.com/material-components-web@11.0.0/dist/material-components-web.js"></script>
```

jic, according #7282 for the newest you need to use: 
```html
<link
      rel="stylesheet"
      href="https://unpkg.com/@material/switch@canary/dist/mdc.switch.css"
/>
```

**Comment by abhiomkar** [comment]
@adinu Seems like the MDC versions for JS & CSS in your codepen are mismatched. 

See this [updated codepen](https://codepen.io/abhiomkar/pen/bGRWdNo) for working example. Or use the previous version of Switch as answered by @marton987
