### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by MaximBalaganskiy** [material-components/material-components-web#7367]
## Feature Request
Please add source maps. This would greatly assist with debugging.

**Comment by asyncLiz** [comment]
Hi, thanks for the issue! Our npm packages are published with sourcemaps (see for example [`@material/checkbox/dist/mdc.checkbox.js.map`](https://unpkg.com/@material/checkbox@12.0.0/dist/mdc.checkbox.js.map).

If bundling with something like rollup or webpack, make sure you have the right plugins to load the source maps! Let us know if you have any other questions.

**Comment by MaximBalaganskiy** [comment]
The problem, and this correlates to TS files present in the package, is that `package.json:module` points to `./index.js`.
Therefore all the d.ts and the rest of the files are not picked from the `dist` folder

**Comment by MaximBalaganskiy** [comment]
When changing `module` to be the same as `main` I could only make it work with following WP config
```js
{ test: /\.js$/, enforce: 'pre', use: ['source-map-loader'], include: [/@material.*checkbox.*dist/] },
```
Otherwise the loader picks up those source maps for es modules which are incomplete

**Comment by MaximBalaganskiy** [comment]
This should be reopened. ESM JS files do not have appropriate source maps. See any of the map files NOT in the dist folder - they all reference TS sources.
