### ISSUE TITLE
MDCSwitch hover/focused poor contrast with dark theme

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#7387]
The New material 12 switch shows poor contrast when hovered or focused with a dark theme

![image](https://user-images.githubusercontent.com/11708435/132949366-45528267-cd82-4073-8b7e-499ab63db37e.png)

**Comment by asyncLiz** [comment]
You can use the switch's [theme mixin](https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch#theme-mixin) to change the [hover](https://github.com/material-components/material-components-web/blob/bdd1a4bf144f283a20c15c137033555b346721f1/packages/mdc-switch/_switch-theme.scss#L99) / [focus](https://github.com/material-components/material-components-web/blob/bdd1a4bf144f283a20c15c137033555b346721f1/packages/mdc-switch/_switch-theme.scss#L94) styles for dark themes.
