### ISSUE TITLE
mdc-linear-progress not included

### ISSUE THREAD

**Issue by crisado** [material-components/material-components-web#739]
Hi.
when i run this command: **npm install --save material-components-web**
this is the result:
└─┬ material-components-web@0.11.1 
  ├── @material/animation@0.2.2 
  ├── @material/auto-init@0.1.2 
  ├── @material/base@0.1.3 
  ├── @material/button@0.3.6 
  ├─┬ @material/card@0.2.1 
  │ └── @material/rtl@0.1.4 
  ├── @material/checkbox@0.3.4 
  ├─┬ @material/dialog@0.2.4 
  │ ├── @material/typography@0.1.1 
  │ └─┬ focus-trap@2.3.0 
  │   └── tabbable@1.0.6 
  ├── @material/drawer@0.4.2 
  ├── @material/elevation@0.1.7 
  ├── @material/fab@0.3.8 
  ├── @material/form-field@0.2.5 
  ├── @material/grid-list@0.2.2 
  ├── @material/icon-toggle@0.1.11 
  ├── @material/layout-grid@0.1.2 
  ├── @material/list@0.2.8 
  ├── @material/menu@0.2.6 
  ├── @material/radio@0.2.4 
  ├── @material/ripple@0.6.1 
  ├── @material/select@0.3.6 
  ├── @material/snackbar@0.1.11 
  ├── @material/switch@0.1.7 
  ├── @material/tabs@0.1.1 
  ├── @material/textfield@0.2.9 
  ├── @material/theme@0.1.5 
  ├── @material/toolbar@0.3.2 
  └── @material/typography@0.2.2 

and mdc-linear-progress is not included
now, i go to demo url:  **demos/linear-progress.html**
show me this error: 
**Uncaught TypeError: Cannot read property 'MDCLinearProgress' of undefined
    at linear-progress.html:183**

**Comment by traviskaufman** [comment]
We haven't yet released the latest version of MDC-Web. That will happen today, and it will include `MDCLinearProgress`.

**As a general FYI, _master does not reflect the current state of what's released_. You can check the releases tag to see what the latest release version is. The versions on npm correlate with these releases**
