### ISSUE TITLE
[mdc-list] No descriptive text why ripples are not present in all examples

### ISSUE THREAD

**Issue by mhitza** [material-components/material-components-web#7398]
The current list examples for single selection either have ripples, or don't, however its not clear if ripples are optional https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#pre-selected-list-item

Is there any simple rule when list items have a ripple effect and when they don't based on a specific context? Or is this an example inconsistency?

**Comment by joyzhong** [comment]
Hello, I believe only non-interactive list items do not have ripples. For other list items, the ripple is mandatory. However, please note that the current docs are based on a deprecated version of list. For the up-to-date docs, see https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#list-is-being-updated.

**Comment by mhitza** [comment]
I hope when those list changes land there'll be a clearer consistency in the application of tags/classes. Aside from a disabled list item is there any other type of list/context where it can be considered non interactive?

I'm writting wrappers around the components using the README's as references, so I could propose PR changes to help ensure consistency in the docs.

**Comment by joyzhong** [comment]
Yes, see the updated docs from https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#list-is-being-updated, specifically docs for the `mdc-list-item--non-interactive` class.

**Comment by Paper-Folding** [comment]
Three years have passed, is the new list still a work in progress?
