### ISSUE TITLE
MDCSlider rounding error

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#7404]
## Bug report
A rounding error exists in [slider foundation.ts at line 1031](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/foundation.ts#L1031) when:

- value is 33.3
- min is 0
- step is 0.1

The correct calculated value would be 333, however a value of 332.99999999999994 is yielded, thus throwing an exception on line 1033.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |   v12.0.0  |
| Browser          |    Edge 93.0.961.47 |
| Operating System |   Windows 10 (fully updated) |

**Comment by simonziegler** [comment]
I found this for reference

https://www.google.co.uk/amp/s/www.avioconsulting.com/blog/overcoming-javascript-numeric-precision-issues%3fhs_amp=true

**Comment by simonziegler** [comment]
I just took a look at the code now that v13.0.0 is released and believe that the issue remains.

**Comment by simonziegler** [comment]
Sorry to push @joyzhong, but can you please give an indication of when you will be able to look at this issue?

**Comment by joyzhong** [comment]
Hi, sorry I likely won't get around to this for at least a few weeks. Feel free to investigate in the meantime and send us a PR if you find a fix. Thank you!

**Comment by vkirilyuk** [comment]
@simonziegler, I propose a fix like

\- const numStepsValueFromMin = (value - min) / step;

\+ let numStepsValueFromMin = (value - min) / step;
\+ // 3.3 / 0.1 = 32.99999999999999 in Chrome 95
\+ numStepsValueFromMin = Number(numStepsValueFromMin.toFixed(6));

but it will take me time to prepare a PR (as I have no experience). Could you do that please?

**Comment by simonziegler** [comment]
Let me see what I can do. I'm more familiar with C# than JavaScript so will make sure I'm certain of my stuff before doing the PR.

**Comment by simonziegler** [comment]
@joyzhong and @vkirilyuk I have submitted a PR. I'm waiting for signature on the Contributor Licence Agreement for the PR to pass tests prior to somebody at your end reviewing the changes. The PR does fix this bug (following a similar pattern to that suggested by @vkirilyuk above), however I still believe a more resilient approach is proper decimal math, using for instance something like [decimal.js](https://mikemcl.github.io/decimal.js/). Have you included any similar libraries in material components web?

**Comment by ThomasOrlita** [comment]
This is a duplicate of https://github.com/material-components/material-components-web/issues/7148. Based on the number of reactions on the issue it would be great if this could get addressed soon. 

I also submitted a PR that fixes this particular case (https://github.com/material-components/material-components-web/pull/7439), but as @simonziegler mentioned, there should be a proper solution for handling decimal arithmetic.

**Comment by simonziegler** [comment]
In reference to @ThomasOrlita, also see https://github.com/material-components/material-components-web/issues/7148#issuecomment-971376714

**Comment by simonziegler** [comment]
My Contributor Licence Agreement is now signed by all parties and active, so this PR is ready for a maintainer review.

**Comment by simonziegler** [comment]
Fixed by #7458

**Comment by kintz09** [comment]
For those of us who are stuck on an older version of this package (v7 an v8 for me), is there any known workaround to get decimals to display properly?
