### ISSUE TITLE
MDCSlider keyboard interaction

### ISSUE THREAD

**Issue by NikkiTheBugSlayer** [material-components/material-components-web#7409]
Is there any plans to bring keyboard interactions back to the MDC Slider?  I see they were removed in v8, but can't see why.

**Comment by joyzhong** [comment]
Can you add more info about which keyboard interactions are not working with the updated slider? You should still be able to adjust the slider via keyboard.

**Comment by UX-Unicorn** [comment]
None of them are working at all.  I didn't see any in the source code when I skimmed through it either.  I am on v11.  Looks like the code for the keyDown event was removed in this [commit](https://github.com/material-components/material-components-web/commit/8158544774c50ba21b114f6fe24786816ba4c4fd).   I was surprised to not see an earlier issue for it.

**Comment by joyzhong** [comment]
Do you have a demo? Please ensure that the HTML is correct as in https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/README.md#sliders - see also https://codepen.io/joyzhong/pen/rNmarao for a working example.

**Comment by UX-Unicorn** [comment]
It appears to not work if you try to set the value from a parent component.  I created this [demo](https://codepen.io/nikki0517/pen/gORZPGv?editors=0010) here.  Is there no way for the slider to be controlled?

**Comment by UX-Unicorn** [comment]
If anyone is interested, I figured out you can have a controlled slider and keyboard interaction work if you set `defaultValue` instead of `value` on the `input`.  You can see it working in this [demo](https://codepen.io/nikki0517/pen/gORZPGv?editors=0010).

**Comment by patrickrodee** [comment]
Per your latest comment, it sounds like this has been resolved. I'm going to close this now but please let us know if you run into any other issues!
