### ISSUE TITLE
mdc-data-table Fails to compile scss in a laravel application

### ISSUE THREAD

**Issue by nulliushealth** [material-components/material-components-web#7414]
## Bug report
Can't compile the scss for the mdc-checkbox and consequently for the mdc-data-table, because it uses it as a dependency, in a fresh laravel application.

### Steps to reproduce
1. Install a fresh laravel application with this composer command: composer create-project laravel/laravel example-app
2. Configure mix to use scss instead of plain css by configuring the same way as the image
![Laravel Mix](https://user-images.githubusercontent.com/86265123/134705000-1f83a84d-eb96-4a0f-a5f2-55b12e5ae8a5.png)
3. Rename the css file to scss in the resources/css folder and paste the styling for mdc-data-table
4. Try to compile with npm run dev

### Actual behavior
I'm receiving this error
![mdc-error](https://user-images.githubusercontent.com/86265123/134706185-e45e247f-5e7a-4e3f-8e63-008283ad2b39.png)

### Expected behavior
Receive a compile css

### Screenshots
My package.json
![packagejson](https://user-images.githubusercontent.com/86265123/134706433-b899b6d8-c9a1-4d73-b911-c99a5d410201.png)

### Your Environment:
![about](https://user-images.githubusercontent.com/86265123/134706758-21877ed6-f946-4d6f-aa04-05968067c0fa.png)
lowing information -->

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |
| Browser          |
| Operating System | Linux PopOS 64bit 21.04

**Comment by sayris** [comment]
You should be able to resolve this by either downgrading your sass version (before 1.40.0) or upgrade your components to the latest release (we just release 13.0.0).

**Comment by nulliushealth** [comment]
Thank you for your answer. I tried lowering the version of my sass and sass-loader before without luck, but now that you've mentioned to upgrade the component to version 13.0.0, it works. Sorry for the trouble and thank you.
