### ISSUE TITLE
[mdc-banner] Required $level and $color parameters

### ISSUE THREAD

**Issue by matyaslapincs** [material-components/material-components-web#7428]
## Bug report
When I try to use mdc-banner component following the documentation `@use "@material/banner/styles";` an error message is shown that $level and $color parameters are missing.

### Steps to reproduce
1.  Place `@use "@material/banner/styles";`  in SCSS file
2. Build (I'm using rollup, but should be the case with other bundlers)

### Actual behavior
During the build I get the following warning message:
```
src/index.js → dist/bundle.js...
WARNING: both $level and $color are required; received $level: '0', $color: ''
    node_modules\@material\elevation\_elevation-theme.scss 234:5   -shadow()
    node_modules\@material\elevation\_elevation-theme.scss 466:20  resolver()
    node_modules\@material\tokens\_resolvers.scss 5:11             -material-elevation()
    node_modules\@material\elevation\_elevation-theme.scss 426:21  with-resolver()
    node_modules\@material\banner\_banner-theme.scss 437:3         -banner-elevation()
    node_modules\@material\banner\_banner-theme.scss 154:3         theme-styles()
    node_modules\@material\banner\_banner.scss 63:5                core-styles()
    node_modules\@material\banner\styles.scss 25:1                 @use
    stdin 1:1                                                      root stylesheet
```

Some banner related code provides a $level: 0 and $color: null value to _elevation-theme.scss, which results in a warning.

```
node_modules\@material\elevation\_elevation-theme.scss:463 DEBUG: 0
node_modules\@material\elevation\_elevation-theme.scss:464 DEBUG: null
```

### Expected behavior
There should be no error message, the -shadow() function should use default values.

### Screenshots
![image](https://user-images.githubusercontent.com/86948201/137470826-4e3d951f-9075-47a2-b4ad-be3e5fd6cae0.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |13.0.0
| Browser          |Google Chrome
| Operating System |Windows 10

**Comment by AshleyJBartlett** [comment]
@brandondiamond - is there any chance this could be fixed? I know it's only a warning but it is frustrating to see these warnings logged out when running a build whilst using that SCSS file?

@EstebanG23 - what's the status of this? Has a fix been released?

**Comment by Vheissu** [comment]
In the interim, you can actually filter this out in Webpack using the `warningsFilter` property: https://ilikekillnerds.com/2023/06/how-to-fix-the-required-level-and-color-parameters-warning-in-webpack-when-using-material-components-web/ - it doesn't fix the warning, but it removes it from your app.
