### ISSUE TITLE
Installation issue using the components

### ISSUE THREAD

**Issue by mdecaffmeyer** [material-components/material-components-web#743]
I try to use e.g. the Dialog component MDCDialog/MDCDialogFoundation.
The doc (https://material.io/components/web/catalog/dialogs/) says to execute the following command:

`npm install --save @material/dialog`

Then importing the component like so:

`import {MDCDialog, MDCDialogFoundation, util} from 'mdc-dialog';`

However, I get the following error:

`Module not found: 'mdc-dialog'`

I only get it working through the following import:

`import {MDCDialog, MDCDialogFoundation, util} from '@material/dialog/dist/mdc.dialog';`
(which is not in the doc)

Am I doing something wrong or does the doc need an update?

**Comment by Garbee** [comment]
`mdc-dialog` is indeed incorrect. Does `@material/dialog` as the import target not work? That should be the shorthand for including a component as a JS module.

**Comment by mdecaffmeyer** [comment]
`import {MDCDialogFoundation} from '@material/dialog';`

gives me:

> Uncaught SyntaxError: Unexpected token import

However,
`import {MDCDialogFoundation} from '@material/dialog/dist/mdc.dialog';`
works

**Comment by traviskaufman** [comment]
`import {MDCDialogFoundation} from '@material/dialog'` expects you to be transpiling the MDC-Web sources using ES2015. `import {MDCDialogFoundation} from '@material/dialog/dist/mdc.dialog';` will work just fine. We'll submit a docs fix for that incorrect module name in the README. Sorry about that! 😅

**Comment by mdecaffmeyer** [comment]
In this doc, step 3:
https://github.com/material-components/material-components-web/blob/master/docs/theming.md#step-3-changing-the-theme-with-sass

The import 

`@import "material-components-web/material-components-web";`

didn't work for me.

Is it again the same problem, where I have to import `@material/something` ?

Error:

> "File to import not found or unreadable: material-components-web/material-components-web.\nParent style sheet: C:/data/xxx/material-components-web/framework-examples/react/public/main.scss",

NPM script:

`"build-css": "node-sass-chokidar --include-path ./public --include-path ./node_modules/@material public/ -o public/",`

This is personally more blocking for me because I don't know how to fix it, any help appreciated:-)

**Comment by amsheehan** [comment]
Resolved by this commit: https://github.com/material-components/material-components-web/commit/44fd5623f3193f4ab6dd79d5ae2e20d99bc8fa2c
