### ISSUE TITLE
some colors are out of theme vars and are not overridable 

### ISSUE THREAD

**Issue by nop1984** [material-components/material-components-web#7464]
#### this is fine, because overridable 
```
.mdc-select--filled:not(.mdc-select--disabled) .mdc-line-ripple::after {
	border-bottom-color: #6200ee;
	border-bottom-color: var(--mdc-theme-primary, #6200ee)
}
```
#### this is not fine, not overridable (no theme var used)
```
.mdc-select:not(.mdc-select--disabled).mdc-select--focused .mdc-floating-label {
	color: rgba(98, 0, 238, 0.87)
}
```
### list of not fine selectors (pure black, pure white, transparent are omitted)

- .mdc-chip-set--choice .mdc-chip.mdc-chip--selected .mdc-chip__icon--leading
- .mdc-select:not(.mdc-select--disabled).mdc-select--focused .mdc-floating-label
- .mdc-select.mdc-select--disabled .mdc-select__dropdown-icon
- .mdc-select--filled:not(.mdc-select--disabled) .mdc-select__anchor
- .mdc-select--filled.mdc-select--disabled .mdc-select__anchor
- .mdc-drawer .mdc-deprecated-list-item--activated .mdc-deprecated-list-item__graphic
- .mdc-drawer .mdc-deprecated-list-item--activated
- .mdc-linear-progress__buffer-bar
- .mdc-snackbar__action:not(:disabled) 
- .mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label

all colour chuncks here https://pastebin.com/16y14zpK

**Comment by sayris** [comment]
Hello! We're in the process of implementing a theming API which should fix this -- will allow for updating the colors on various aspects of components (see the _<component>_theme.scss file for properties that can be styled via this API). Otherwise, the MWC component library (the next iteration of our material components) is addressing the underlying issue of ensuring these styles are approporiately stored in css custom vars.

Thanks!

**Comment by nop1984** [comment]
Cool, meanwhile I am using plain css distr can override missing due to list above.
New API will include all colours and will open opportunity for dark theme also? Because I saw many hardcoded white and black while was reviewing all css to create list above. Would be nice instead of black and white have --def-back-color and --def-front-color which alterations might be with filter: inverse or mix-blend-mode
