### ISSUE TITLE
Fixed heights should be avoided

### ISSUE THREAD

**Issue by ukozdan** [material-components/material-components-web#7465]
## Feature Request

I have noticed, on this occasion with the button component, that fixed heights are being set. This overrides the core native behaviour of HTML and CSS to expand and contract to content and viewports. The visual result is that the text breaks out of the button with multiple words and at certain widths, which is worse than the unstyled default behaviour of a button. 

Given that [Material UI](https://mui.com/) is one of the most popular implementations of the Material Design system, it would seem to make sense to at least assess their implementation choices. So, continuing with the example of the Button component, [Material UI's Button](https://mui.com/components/buttons/) does not set any fixed heights, thereby allowing the button text to remain on one line until no more horizontal space remains, at which point it wraps and the button expands. 

I appreciate that for some JavaScript functions, one may require fixed dimensions for precise calculations. However, fixed and consistent dimensions can also be achieved with a global unit of measurement and system for all padding, borders, margin and typography while still retaining the native flexibility of HTML and CSS. Of course, relative rather than fixed units can also be used for flexibility. 

### Proposed solution

I am a fan of Bootstrap as regards its approach to the HTML and CSS of components. It is simple, minimal and every component has clearly been tested in a wide variety of scenarios and devices. I propose that Material Components for the Web assess some of their approaches and avoid fixed dimensions in all components except in rare and unavoidable scenarios.

**Comment by sayris** [comment]
Hello! 

The material spec indicates that button labels should be brief and should not span multiple lines (https://material.io/components/buttons#anatomy). 
Our buttons are built to adhere to this design spec and so expects the text to only span a single line.

Thanks!


https://material.io/components/buttons#anatomy

**Comment by ukozdan** [comment]
It may be advisable from an accessibility and UX perspective to keep button text short and on one line, but you only need two buttons with two short words in each within a Card or Dialog `.mdc-card__action-buttons` element for this overflow to occur on mobile portrait. 

Research indicates a maximum number of words for a readable line of text. Is MDC also going to start imposing maximum widths for headings and paragraphs?

Material UI is also honouring the Material Design system. However, they do not set fixed dimensions on their buttons and clearly believe that no rule should be so inflexible that a broken UI is preferable.
