### ISSUE TITLE
Elevation Overlay demo is broken

### ISSUE THREAD

**Issue by johnspurlock** [material-components/material-components-web#7493]
1. Go here: https://material-components.github.io/material-web/demos/
2. Click on "Elevation Overlay" aka https://material-components.github.io/material-web/demos/elevation-overlay/

Boom!  see js console for error:

Uncaught TypeError: Failed to resolve module specifier "@material/mwc-elevation-overlay/mwc-elevation-overlay-css". Relative references must start with either "/", "./", or "../".

**Comment by MadhaviMandalia** [comment]
Hello @codr ,
Can I contribute on this issue?

Thanks & Regards.

**Comment by asyncLiz** [comment]
This demo page will be turned down as we go into Material 3, so I'm going to close this bug as won't fix.
