### ISSUE TITLE
[mdc-tooltip] mdc-tooltip__action CSS class is not present

### ISSUE THREAD

**Issue by mpetuska** [material-components/material-components-web#7496]
## Bug report

Looks like `mdc-tooltip__action` CSS class is not present anywhere in this repo. This causes tooltip actions to not be properly styled.

Tested with mdc@13.0.0

### Steps to reproduce
1. Render any of the interactive samples in mdc-tooltip/README.md

### Actual behavior

Action elements use default browser styles

### Expected behavior

Action elements properly styled

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 13.0.0
| Browser          | Firefox
| Operating System | Linux/Ubuntu

**Comment by sayris** [comment]
Can you attache a demo/screenshot of how the tooltip action buttons are being mis-styled? Styling for the button itself comes from the MDC Button component -- styling on the positioning of the tooltip actions are defined in the `mdc-tooltip--rich-actions` class.

Thanks!

**Comment by sayris** [comment]
Huh, guess the PR did not get linked -- anyways this was addressed in https://github.com/material-components/material-components-web/pull/7504

**Comment by mpetuska** [comment]
Unfortunately the PR lists 0 changes (I'm assuming due to heavy force pushing). Could you pinpoint me to what exactly changed? Is it just the docs?

**Comment by sayris** [comment]
Hmmm... how about this: https://github.com/material-components/material-components-web/commit/933e58054e0f7bca14ec826e46a759f5356b0b3a?

The html snippets for rich tooltips were incorrect -- rather than using a native button with `class="mdc-tooltip__action"`, mdc buttons should be used. The docs are updated to include html for a basic filled button.

**Comment by mpetuska** [comment]
Apologies for late reply, but I finally got a chance to test it and I can confirm that just using regular mdc-button works.
