### ISSUE TITLE
[mdc-slider] Incorrect tick marks placement

### ISSUE THREAD

**Issue by mpetuska** [material-components/material-components-web#7497]
## Bug report

MDCSlider tick marks are misplaced

### Steps to reproduce
1. Render `Discrete slider with tick marks` example from `mdc-slider` docs

### Actual behavior

Tick marks are placed bellow the slider

### Expected behavior

Tick marks are placed on top of slider

### Screenshots

![image](https://user-images.githubusercontent.com/23262603/147753380-705152c0-30fe-4283-a982-f53c7a68f97d.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 13.0.0
| Browser          | Firefox
| Operating System | MacOS

**Comment by dfreedm** [comment]
Can you make a demo link with https://glitch.com/edit/#!/remix/new-web so we can see your setup?

**Comment by mpetuska** [comment]
Here's a [reproducer](https://glitch.com/edit/#!/mdc-slider-ticks-repro). Note that I've copied over HTML output from my client-side rendered app.

**Comment by mpetuska** [comment]
Oops, my apologies. Turns out I simply mistyped `mdc-slider__track--active` class as `mdc-slider--active` which was the root issue. 
This issue can be closed.
