### ISSUE TITLE
[MDCTextField] Floating label breaks when pre-populating inputs

### ISSUE THREAD

**Issue by tsteuwer-accesso** [material-components/material-components-web#7503]
## Bug report
If you want to pre-populate a form with data, the component does not update the label position to be floating.

### Steps to reproduce
1. Go to https://stackblitz.com/edit/angular-ivy-i7imzc?file=src/app/app.component.html
2. Select a name from the `<select>` element.
3. Notice the labels to not float above the input and it looks broken.

### Actual behavior
The label stays over the input and looks broken.

### Expected behavior
When an input has a value, the label should be floating.

### Screenshots
![A broken looking form](https://i.imgur.com/SoW0dTQ.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 13
| Browser          | All
| Operating System | All

### Additional context

I have also tried running

```
setTimeout(function updateComponentLayoutDelayed() {
	[].slice.call(document.querySelectorAll('.mdc-text-field')).forEach(function updateComponentLayout(input) {
		if (input.mdcInstance.layout) {
			input.mdcInstance.layout();
		}
	});
}, 500);
```
And it doesn't update the labels.

**Comment by dfreedm** [comment]
The MDCTextField doesn't know that the value was updated by Angular, so it doesn't know to relayout. I suggest keeping a reference to the MDCTextField object you're creating and calling `.layout()` after updating the value, or using [Angular Material's textfield component](https://material.angular.io/cdk/text-field/overview)

**Comment by tsteuwer-accesso** [comment]
I ended up using the following code:

```
Array
  .from(document.querySelectorAll('.mdc-text-field'))
  .forEach((el) => {
	  var input = el.mdcInstance?.input;
	  if (!input) {
		  return;
	  }
  
	  if (el.mdcInstance.label?.foundation?.float) {
		  el.mdcInstance.label.foundation.float(input.value.length > 0);
	  }
  });
