### ISSUE TITLE
[MDC-data-table] Calling `layout()` on data-table after removing a row with a checkbox throws error

### ISSUE THREAD

**Issue by lukepfeiffer10** [material-components/material-components-web#7525]
https://github.com/material-components/material-components-web/blob/ae85f7eba0d72f4fa5f3e8669cd316336b3e6828/packages/mdc-data-table/component.ts#L264-L277

The above code throws a missing element error when calling the `layout()` function on the data-table component after removing a row from a table that contains row checkboxes. This is the error message:

```
Uncaught Error: Checkbox component requires a .mdc-checkbox__native-control element
    getNativeControl ...@material/checkbox/component.js?:233
    deregisterInteractionHandler ...@material/checkbox/component.js?:160
    deregisterRootHandlers ...@material/ripple/foundation.js?:274
    destroy ...@material/ripple/foundation.js?:164
    destroy ...@material/base/component.js?:80
    destroy ...@material/checkbox/component.js?:123
    registerRowCheckboxes ...@material/data-table/component.js?:267
    registerRowCheckboxes ...@material/data-table/component.js?:266
```

Is there something I'm missing about calling the `layout()` function on the data-table component after removing a row?

**Comment by sayris** [comment]
How are you removing the data table row? Can you link to a codepen where this issue is reproducible?

Thanks!

**Comment by lukepfeiffer10** [comment]
I am using rust wasm with the Yew framework to create/update the table (add or remove rows). I was not able to reproduce using typical JS DOM interaction but I will try to create a rust wasm codepen for this if I can (if you're still curious to investigate this issue).
