### ISSUE TITLE
How to access the mdc global variable from TypeScript?

### ISSUE THREAD

**Issue by Slion** [material-components/material-components-web#7551]
Not a bug really, just a question.
Can I access the mdc global variable from TypeScript?
I've migrated a project from plain JavaScript to TypeScript it works fine so far.
However I wish I could still access the mdc variable somehow, if only for inspection purposes.

**Comment by asyncLiz** [comment]
Hi! When using TypeScript, we recommend importing directly from packages rather than using the global variables. That way, when TS compiles, you can tree shake code.
