### ISSUE TITLE
m3.material.io site broken on chrome?

### ISSUE THREAD

**Issue by m-melis** [material-components/material-components-web#7554]
Not sure this is the correct repository for this report. Anyway, m3.material.io site seems broken on Chrome Version 98.0.4758.102, Windows 10.

![image](https://user-images.githubusercontent.com/7879584/155153801-caced3bf-f02e-4038-90d3-221865065257.png)

**Comment by joyzhong** [comment]
Closing, as this repo only tracks MDC Web components issues and not bugs in the material.io reference site.
