### ISSUE TITLE
Snowpack config , @snowpack/plugin-sass" , Saas configuration for google material components -web(MDC) integrations

### ISSUE THREAD

**Issue by sahibnasirov** [material-components/material-components-web#7559]
Hello does anyone successful adding material-components-web into snowpack project ,
I have used @snowpack/plugin-sass" , it work fine with local .scss files but when try to import MDC components with javascript for example (import {MDCRipple} from '@material/ripple'; )it breaks the sass modules of mdc in node-modules and always gives error like 'dependency not found'
Also used saas-migrator package didn't work with them too,
It seems like sass version failure but don't know what is problem ,
because all the example are based on webpack
would be grateful if anyone share proper snowpack+@snowpack/plugin-sass+material-components-web configuration with simple example
many thanks

**Comment by MaximBalaganskiy** [comment]
You may need to configure webpack sass loader to scan node_modules folder
```
    loader: 'sass-loader', options: {
      sourceMap: false,
      implementation: require('sass'),
      sassOptions: {
        includePaths: [path.resolve('../../node_modules/'), path.resolve('./node_modules')]
      }
    }
```
