### ISSUE TITLE
[mdc-snackbar] macOS VoiceOver support

### ISSUE THREAD

**Issue by mdooley** [material-components/material-components-web#7565]
According the the README, macOS VoiceOver is [not supported](https://github.com/material-components/material-components-web/tree/master/packages/mdc-snackbar#screen-readers). I tried finding a tracking issue for this, but couldn't find one.

Is support coming? Is there a workaround that should be used in the meantime?

**Comment by sayris** [comment]
Hey! Snackbar is supported by VoiceOver:
> Snackbars automatically announce their label text to screen reader users with a ["polite" notification](https://www.w3.org/TR/wai-aria-1.1/#aria-live) when open() is called.

What is not supported on macOS VoiceOver is the `util.announce` method -- however this is not necessary for the screen reader to access/read the snackbar.

Apologies for the confusion!

**Comment by asyncLiz** [comment]
Let us know if you have any other questions! :)
