### ISSUE TITLE
docs(rtl): content is messed up after mdc-rtl-reflexive-property

### ISSUE THREAD

**Issue by robzenn92** [material-components/material-components-web#757]
### What MDC-Web Version are you using?

0.12.0 published on [https://material.io/components/web/catalog/](https://material.io/components/web/catalog/)

### What browser(s) is this bug affecting?

All of them

### What OS are you using?

macOS 10.12.4

### What are the steps to reproduce the bug?

1) Visit the [RTL doc page](https://material.io/components/web/catalog/rtl/)
2) Scroll till the end of the page
3) You will see the caption **mdc-rtl-reflexive-property**

### What is the expected behavior?

The content should have the same aspect as in the [README.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-rtl/README.md#mdc-rtl-reflexive-property)
Hence:

<img width="775" alt="readme ok" src="https://cloud.githubusercontent.com/assets/3225625/26645319/e8494e6e-4637-11e7-91b4-2fcb51b80466.png">

### What is the actual behavior?

The content is messed up.

After the text `Takes a base property and emits rules that assign -left to and` the content is interrupted and a new line is inserted.
Moreover the css code is not wrap within css code style as in the [README.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-rtl/README.md#mdc-rtl-reflexive-property).

<img width="787" alt="readme not ok" src="https://cloud.githubusercontent.com/assets/3225625/26645343/fc901dee-4637-11e7-8ae3-e6f4814a2da5.png">

### Any other information you believe would be useful?

The line is the following: [mdc-rtl/README.md#L177](https://github.com/material-components/material-components-web/blame/master/packages/mdc-rtl/README.md#L177)

**Comment by traviskaufman** [comment]
Thanks for reporting! @shyndman could you take a look into this?

**Comment by amsheehan** [comment]
A PR for documenting a mixin tagged this to be closed, reopening. Carry on.

**Comment by robzenn92** [comment]
@amsheehan Am I suppose to do something else here? I din't get sorry.
