### ISSUE TITLE
mdc-select multi value option

### ISSUE THREAD

**Issue by adoumas** [material-components/material-components-web#7571]
## Feature Request
I see in the material guidelines that appear to have an option of multi-select values and I see that is implemented on the mdc-list component the option of multi-select with mdc-checkbox but its not implemented on the mdc-select component. Any plans for implementation? 

### Proposed solution
Add an option on the mdc-select to enables the multi-select value.

### Additional context
mui (react) and mat (angular) have already implement this feature.

**Comment by sayris** [comment]
Hello! Unfortunately, we don't plan to support/implement multi-select at this time.
