### ISSUE TITLE
[MaterialInkTooltipComponent] Is not working nested inside *ngFor 

### ISSUE THREAD

**Issue by smgood** [material-components/material-components-web#7576]
## Bug report
When I added a <material-tooltip-text> component inside of an *ngFor the tooltip would not pop up.
I was able to avoid the issue by having the *ngFor iterate through a List[String] instead of List[dataSource] where dataSource is an abstract class.

### Steps to reproduce
<div *ngFor="let dataSource of dataSources; let i = index">
  <div tooltipTarget #textTargetRef="tooltipTarget">
   {{i}}
  </div>
  <material-tooltip-text [for]="textTargetRef">
   {{i}}
  </material-tooltip-text>
</div>

This code did not work unless I changed the data type of dataSources to a List[String] instead of List[dataSource].

### Actual behavior
Tooltip did not popup 

### Expected behavior
Tooltip pops up

### Your Environment:
chrome

**Comment by sayris** [comment]
Hello! It seems like you're trying to use these MDC components in an Angular environment. There's a separate material library for use with Angular: https://material.angular.io/components/tooltip/overview
