### ISSUE TITLE
Expected release date for v14.0.0

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#7583]
Hi, I'm eagerly waiting for version 14.0.0 of material-components-web to be released so that I can benefit from a November 2021 bug fix (linked below). Do you have a sense when this will be released?

Thanks, Simon

https://github.com/material-components/material-components-web/commit/4103fc14a18847101e63d3735d0fef8324bd8a25

**Comment by asyncLiz** [comment]
Hi Simon! I'll be working on some final releases and documentation for Material 3 next week :)

**Comment by simonziegler** [comment]
Hey Liz, thanks for the quick response! So not only v14 coming relatively soon, but Material 3 is progressing for the web too? That's good news - very good news.

**Comment by mhitza** [comment]
@asyncLiz I just landed upon this comment https://github.com/material-components/material-web/issues/3050#issuecomment-1011464627 . Can you confirm that material-components-web won't be updated to support Material 3?

**Comment by asyncLiz** [comment]
> Can you confirm that material-components-web won't be updated to support Material 3?

MDC (material-components-web) will not be updated to support Material 3. It will remain our Material 2 implementation in maintenance mode.

I understand this might be disappointing for many, but as a team we feel the best use of our resources is to dedicate everything to Material 3 so we actually have a full catalog of components :)

**Comment by simonziegler** [comment]
I'm looking forward to the new material-web library coming online for Material 3.m It's going to be so much easier using web components than having to copy boilerplate HTML.

In the meantime does this mean that this library will not be getting v14, and importantly for me the PR that I prepared as linked above.

**Comment by asyncLiz** [comment]
There will be a final v14.0.0 release in the next couple of weeks. There may be future patch releases for critical bug fixes.

**Comment by asyncLiz** [comment]
Going to close this issue since the original question is answered. Was slowed down a bit setting things up, so it'll likely be next week that v14 is cut :)
