### ISSUE TITLE
Theming Issue

### ISSUE THREAD

**Issue by racile** [material-components/material-components-web#7587]
following Getting Started from [material.io](https://material.io/develop/web/getting-started) or from [github](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) using unpkg CDN native [css](https://unpkg.com/material-components-web@13.0.0/dist/material-components-web.min.css) and [js](https://unpkg.com/material-components-web@13.0.0/dist/material-components-web.min.js) 
customizing theme works except for .mdc-text-field--outlined .mdc-floating-label.
I've tried to override the entire :root{ } and even tried to download the css  file and change everything related to the the default primary color (#6200ee) still doesn't work, now I'm confused to where it's getting the color.
following this solution from [stackoverflow](https://stackoverflow.com/a/58651113/5158824) works but it defeats the purpose to the ease of use through theming.

**Comment by EstebanG23** [comment]
Can you provide repro steps or screenshots to debug?

**Comment by racile** [comment]
> Can you provide repro steps or screenshots to debug?

```
<html>

<head>
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <style>
        :root {
            /* --mdc-theme-primary: #6200ee; */
            --mdc-theme-primary: #4285F4;
            --mdc-theme-secondary: #018786;
            --mdc-theme-background: #fff;
            --mdc-theme-surface: #fff;
            --mdc-theme-error: #b00020;
            --mdc-theme-on-primary: #fff;
            --mdc-theme-on-secondary: #fff;
            --mdc-theme-on-surface: #000;
            --mdc-theme-on-error: #fff;
            --mdc-theme-text-primary-on-background: rgba(0, 0, 0, 0.87);
            --mdc-theme-text-secondary-on-background: rgba(0, 0, 0, 0.54);
            --mdc-theme-text-hint-on-background: rgba(0, 0, 0, 0.38);
            --mdc-theme-text-disabled-on-background: rgba(0, 0, 0, 0.38);
            --mdc-theme-text-icon-on-background: rgba(0, 0, 0, 0.38);
            --mdc-theme-text-primary-on-light: rgba(0, 0, 0, 0.87);
            --mdc-theme-text-secondary-on-light: rgba(0, 0, 0, 0.54);
            --mdc-theme-text-hint-on-light: rgba(0, 0, 0, 0.38);
            --mdc-theme-text-disabled-on-light: rgba(0, 0, 0, 0.38);
            --mdc-theme-text-icon-on-light: rgba(0, 0, 0, 0.38);
            --mdc-theme-text-primary-on-dark: white;
            --mdc-theme-text-secondary-on-dark: rgba(255, 255, 255, 0.7);
            --mdc-theme-text-hint-on-dark: rgba(255, 255, 255, 0.5);
            --mdc-theme-text-disabled-on-dark: rgba(255, 255, 255, 0.5);
            --mdc-theme-text-icon-on-dark: rgba(255, 255, 255, 0.5);
        }
    </style>
</head>

<body>
    <label class="mdc-text-field mdc-text-field--outlined" data-mdc-auto-init="MDCTextField">
        <span class="mdc-notched-outline">
            <span class="mdc-notched-outline__leading"></span>
            <span class="mdc-notched-outline__notch">
                <span class="mdc-floating-label" id="my-label-id">Your Name</span>
            </span>
            <span class="mdc-notched-outline__trailing"></span>
        </span>
        <input type="text" class="mdc-text-field__input" aria-labelledby="my-label-id">
    </label>
    <script>
        window.mdc.autoInit();
    </script>
</body>

</html>
```

**Comment by asyncLiz** [comment]
This is a known issue (see #5242 and #5349). M2 doesn't fully support theming via custom properties, primarily because of IE11 support.

This has been fixed already in [the M3 text field though 🙂](https://github.com/material-components/material-web/blob/8b449c57d447551ab795a51f295dd2bb64b23877/components/field/lib/_label-theme.scss#L24-L31)

**Comment by racile** [comment]
> 

I see good to know, thanks.
although M3 is only available for android, no implementation for web at the moment, right?

**Comment by asyncLiz** [comment]
Material 3 is currently being worked on in [material-components/material-web](https://github.com/material-components/material-web/tree/master/components)! It is not available for beta yet, but will be soon in the next coming weeks :)

**Comment by asyncLiz** [comment]
Closing this as fixed in Material 3
