### ISSUE TITLE
linear-progress dist/ folder has no javascript files

### ISSUE THREAD

**Issue by AustP** [material-components/material-components-web#759]
I just updated to material-components-web v0.12.0 to try out the new linear-progress component. I wasn't able to import `MDCLinearProgress` so I dove into `node_modules/@material/linear-progress/dist` to see what was going on.

As it turns out, there was no `mdc.linearProgress.min.js` or `mdc.linearProgress.js` files in there!

**Comment by traviskaufman** [comment]
Thanks so much for catching this, and I apologize about this 😒 

We'll be submitting a hotfix ASAP.

**Comment by traviskaufman** [comment]
Fixed in `v0.12.1` which is deployed on npm
