### ISSUE TITLE
[MDCSelect] MDCSelect: keyboard arrows allow to select disabled options

### ISSUE THREAD

**Issue by cmoralesencora** [material-components/material-components-web#7606]
## Bug report

thought keyboard the user is able to select a disable option, Select implement the [Collapsible Dropdown Listbox](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html) that includes the arrow up / down select functionality but it do allow the user to select a option with a `mdc-list-item--disabled` class.

this only happens when the MenuList is collapsed and the selected option is next / previous to the disabled option

### Steps to reproduce
1. select the next or previous option to the disabled option
2. with the focus on the select, press the up or down arrow key

### Actual behavior

thought keyboard the user is able to select a disable option

### Expected behavior

the user should no be able to select a disabled option

### Screenshots

https://user-images.githubusercontent.com/93157313/166711302-80a811cd-3d81-4d8a-bdde-5b4ff9f4a4ac.mov

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 13.0.0 |
| Browser          | Chrome |
| Operating System | MacOS |

**Comment by tsteuwer-accesso** [comment]
This looks like `MDCSelectFoundation.prototype.handleKeydown` doesn't check if the next item has a disabled class before calling `MDCSelectFoundation.prototype.setSelectedIndex`.

When you click on a menu item, it calls `MDCListFoundation.prototype.handleClick` which first checks if the list item has the disabled class and if it does, then calls `MDCSelectFoundation.prototype.setSelectedIndex`.
