### ISSUE TITLE
NodeJS v8 (latest) breaks TravisCI

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#771]
Due to a dependency not being updated for the latest version of NodeJS, TravisCI fails. Create a PR with the latest version of Node specified in travis.yml, but do not merge it until all dependencies get updated for TravisCI and NodeJS v8.

**Comment by ClashTheBunny** [comment]
Is there a reason to not have TravisCI stick with Node 8 when it becomes stable for when Node 9 comes out in a year and similar things may happen?

**Comment by amsheehan** [comment]
@ClashTheBunny Could you clarify? When 8 becomes stable and our dependencies don't break the build because of it, it will become the latest version of Node that we test against.

**Comment by abhiomkar** [comment]
Travis is configured to use node_js 8. closing this.
