### ISSUE TITLE
Ripple is broken on elements with `display: none` on page load

### ISSUE THREAD

**Issue by draoncc** [material-components/material-components-web#774]
### What MDC-Web Version are you using?

0.12.1

### What browser(s) is this bug affecting?

Google Chrome Version 57.0.2987.133 (64-bit)
Mozilla Firefox Version 52.0.2 (64-bit)
Others not tested.

### What OS are you using?

Arch Linux Kernel 4.10.8-1

### What are the steps to reproduce the bug?

1. Open this codepen: https://codepen.io/draoncc/pen/OgLrjN
2. Observe the behaviour of ripples on the buttons.

Note: Alternatively to setting the display state to 'none' by script the behaviour can be reproduced by setting an inline style of `display: none` on the ripple element to break.

### What is the expected behavior?

Both buttons have working ripples regardless of "initial" display state.

### What is the actual behavior?

The ripple on the `#broken-button`, which's style is set to `display: none` on run of the script, does not work properly.

**Comment by anton-kachurin** [comment]
Is very likely related to #464 and happening because the size of the element changes after the ripple initialization.

**Comment by amsheehan** [comment]
@draoncc This is because the ripple is trying to calculate its size based on the element's size. This is clearly problematic if `display` is none. After discussing with the team, the proposed solution is to expose the `foundation`'s layout logic.

### Changes:

- [ ] Create a method in the component that proxies through to `foundation.js`'s `layout()` method
- [ ] Write a test for it
- [ ] Document the changes

**Comment by touficbatache** [comment]
Is someone working on that? Same issue here.

**Comment by anton-kachurin** [comment]
The required functionality was added in v0.14. [Check out the pen](https://codepen.io/anon/pen/RgvGzK).

**Comment by touficbatache** [comment]
This works because you are attaching the ripple to the button before the `display:none`. I'm using `data-mdc-auto-init="MDCRipple"` and it seems to not be working.

**Comment by anton-kachurin** [comment]
[It works either way](https://codepen.io/anon/pen/PjVeow).

In your case, call `document.querySelector('#button').MDCRipple.layout()` after changing `display` property of the button.

**Comment by touficbatache** [comment]
I am using `data-mdc-auto-init="MDCRipple"`, not `mdc.ripple.MDCRipple.attachTo()`

**Comment by kfranqueiro** [comment]
As @anton-kachurin mentioned, `layout` is now also exposed at the component level on mdc-ripple, which makes this issue resolvable by calling `layout` on ripples when your element is no longer `display: none`.  As such, I'm going to close this issue.

If anyone still encounters problems particular to a specific use case, please enter a new issue if you think there is something that material-components-web needs to do to resolve it. Thanks!
