### ISSUE TITLE
fullwidth textfield labels appear outside of the input elements on iOS Safari and Chrome

### ISSUE THREAD

**Issue by fzzylogic** [material-components/material-components-web#775]
### What MDC-Web Version are you using?
> ^0.10.0 (textfield component is ^0.2.7)

### What browser(s) is this bug affecting?
> Safari 
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.146 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1

> Chrome (on same device)
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/58.0.3029.113 Mobile/13G36 Safari/601.1.46

### What OS are you using?
> iOS 9.35

### What are the steps to reproduce the bug?
> 1. Check the codepen below using a device running iOS 9.35. 
> 2. Observe that the label text is not within the text input box, but on the very left of the screen, shifted below the text input element.
> 3. A workaround is included in the codepen. 
> .mdc-textfield--fullwidth {position:relative} puts the label text inside its box.
>
> codepen.io demo: https://codepen.io/fzzylogic/pen/yXBwze

### What is the expected behavior?

> Text labels should be in their boxes.

### What is the actual behavior?

> Text labels are outside of their boxes and all overlap at the extreme left of the screen.

**Comment by anton-kachurin** [comment]
Fullwidth textfields do not support labels. They are supposed to use`placeholder` instead. [Modified pen](https://codepen.io/anon/pen/YQzPXg).

**Comment by anton-kachurin** [comment]
Since it causes a lot of confusion (#203, #506, #631, #701), docs for the component need to be updated to make the difference between fullwidth textfields and regular textfields with `width: 100%` clear. Examples for each kind and semantics for choosing either kind would help a lot.

**Comment by fzzylogic** [comment]
Thanks! For future people who may wonder if this will be supported: #701 was particularly useful, clarifying that [fullwidth under material design](https://material.io/guidelines/components/text-fields.html#text-fields-field-variations) isn't just about making the field 100% and so won't support floating labels. For 100% text fields, one may simply set normal text fields to 100% width.

**Comment by amsheehan** [comment]
@anton-kachurin is correct in both stating the problem and the solution. Stay tuned for docs change.

**Comment by evil-shrike** [comment]
Honestly it's hard to understand why fullwidth "isn't just about making the field 100%".
Docs should be updated indeed to make it clear. But maybe instead you should ask yourselves why are so many confusion? Maybe it' better to change semantic of `mdc-textfield--fullwidth`?

> For 100% text fields, one may simply set normal text fields to 100% width.

This helps indeed, but one should not forget to make it two times - one for label and one for input:
```
        <label class="mdc-textfield fullwidth" id="customer">
            <input type="text" class="mdc-textfield__input fullwidth" >
            <span class="mdc-textfield__label">{{ $t('customer') }}</span>
        </label>
```
