### ISSUE TITLE
Page content can be scrolled even if drawer is open.

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#777]
### What MDC-Web Version are you using?

> 0.12.1

### What browser(s) is this bug affecting?

> Chrome 58.0.3029.110

### What OS are you using?

> Windows 7 Professional

### What are the steps to reproduce the bug?

> 1. Go to the [catalog page](http://material-components-web.appspot.com/drawer/temporary-drawer.html).
> 2. Have a lot of page content that can be scrolled.
> 3. Open the drawer then scroll up or down.
> 4. Observe what happens.

### What is the expected behavior?

> You shouldn't be able to scroll the page's content.

### What is the actual behavior?

> The page content can be scrolled up and down as the drawer is open.

**Comment by Touficbatache** [comment]
Closed this issue because it wasn't caused by MDC.

**Comment by amsheehan** [comment]
I believe we can take the same approach as `mdc-dialog` to solve this.

- [ ] Add two methods `addBodyClass` and `removeBodyClass` to the adapter. These methods will add/remove some classname to the body.
- [ ] Style the class such that it sets `height: 100vh` and `overflow: hidden`
- [ ] Write tests for the new methods
- [ ] Document the new methods in the README
- [ ] Mark as a `Breaking Change:` in the last commit message
