### ISSUE TITLE
MDC Simple Menu

### ISSUE THREAD

**Issue by Touficbatache** [material-components/material-components-web#783]
Hey,
I was making a template for my web app when I saw that the MDC Simple Menu does not look like the menu from the Material Design guidelines page. On the left we have MDC and on the right we have Material Design guidelines's menu.
![mdc2](https://cloud.githubusercontent.com/assets/17137918/26752895/bef78ab2-4862-11e7-925c-1082bc9d90c9.png)
It's actually different in: 

1. The `font-size` which should be `16px`.
2. The `font-weight` which should be `400`.
3. The `min-width` which should be `170px`.
4. The `letter-spacing` which should be `0.05px`. (Should it be more or less than 0.05px? @robzenn92)

And with all these changes, the menu will look _**exactly**_ like the one on Material Design guidelines page. On the left we have MDC and on the right we have Material Design guidelines's menu.
![mdc](https://cloud.githubusercontent.com/assets/17137918/26752938/de2a2182-4863-11e7-8c5f-9c2a2b6fc6de.png)

**Comment by robzenn92** [comment]
From the examples you posted, to me it seems that also the letter-spacing it's a bit different..isn't it?

**Comment by Touficbatache** [comment]
Yes it is! I'll fix it later :)

**Comment by amsheehan** [comment]
This looks good. @Touficbatache would you mind making a PR for this? What we'd look for are two things:

- [ ] We _don't_ want to change letter spacing. What may be right for one set of typography may not be for another
- [ ] Make sure `mdc-typography` mixins are used for the solution where appropriate

Thanks!

**Comment by Touficbatache** [comment]
@amsheehan Yes sure! What do you mean by "Make sure mdc-typography mixins are used for the solution where appropriate" ?

**Comment by amsheehan** [comment]
Just not to directly alter properties like `font-size` and `font-weight` directly in the component. Use `mdc-typography` the way it is used on line 137 of `mdc-simple-menu.scss`

**Comment by Touficbatache** [comment]
I'm not sure that I understand. What should I add?

**Comment by Touficbatache** [comment]
@amsheehan
