### ISSUE TITLE
Toolbar for Desktop should be 24px per guidelines

### ISSUE THREAD

**Issue by RhysyG** [material-components/material-components-web#786]
### What MDC-Web Version are you using?

0.11.1

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

MacOS Sierra 10.12.5 (16F73)

### What are the steps to reproduce the bug?

No step, just initial styles.

### What is the expected behavior?

Padding left and right for DESKTOP should be 24px per Material Design Guidelines:
https://material.io/guidelines/layout/structure.html#structure-app-bar

### What is the actual behavior?

Padding left and right is 28px.

**Comment by amsheehan** [comment]
Would you have the time to make a PR with these changes? I believe the change should be fairly simple:

- [ ] Alter the base styles for `mdc-toolbar__icon` and the `left-margin` on `mdc-toolbar__title` to conform to the desktop styles in spec
- [ ] Restore the values for those properties to what they currently are in the media query

**Comment by RhysyG** [comment]
Yeah sure thing. Wouldn't I need to:

Change variable $mdc-toolbar-padding to 20px 24px;
Which will change mdc-toolar__row padding.

Change mdc-toolbar__title to margin-left: 32px ?

Which will position title 72px from left on mobile and 80px left on desktop (presuming the icon only takes up 24px).

**Comment by touficbatache** [comment]
Isn't this issue fixed as of 0.13.0 or I am wrong?
