### ISSUE TITLE
mdc-select and dark theme

### ISSUE THREAD

**Issue by piotr-cz** [material-components/material-components-web#793]
## Feature Requests
none

### What MDC-Web Version are you using?

v0.12.1 and v0.11.1

### What browser(s) is this bug affecting?

Chrome 58.0.3029.110

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. Apply class `mdc-theme--dark` to `select.mdc-select` outer wrapper or `mdc-select--theme-dark` to `select.mdc-select` element
2. Options are not visible either for single-select or multi-select

may be reproduced on Select demo: https://material-components-web.appspot.com/select.html

### What is the expected behavior?

options should be visible

### What is the actual behavior?

options are not visible

### Any other information you believe would be useful?

![dark-select](https://cloud.githubusercontent.com/assets/612953/26821477/d30c3e4e-4aa6-11e7-99a3-baeb3afb1d2d.png)

**Comment by Touficbatache** [comment]
Shouldn't the title be mdc-select instead of mcs-select?

**Comment by piotr-cz** [comment]
True, fixed

**Comment by amsheehan** [comment]
This seems to have been resolved.
