### ISSUE TITLE
Where do I start?

### ISSUE THREAD

**Issue by megamindbrian** [material-components/material-components-web#798]
I am confused, where do I start reading documentation?  Which of these is related to this project?

https://design.google.com/
https://getmdl.io/
https://material.io/
https://material.io/guidelines/
https://material.io/components/web/
https://material-components-web.appspot.com/
http://www.material-ui.com/#/
https://material.angular.io/components

Do we really need 8 separate projects and websites all describing the exact same things?

**Comment by traviskaufman** [comment]
Hey @megamindbrian,

In the future, questions like this are best suited for StackOverflow. That being said, Most of those links you listed are for projects that, while related, are different than ours:

- design.google.com is the home of Google Design
- getmdl.io is for Material Design Lite, which is this project's predecessor
- material-components-web.appspot.com is our demos site
- material-ui.com is for a different library for React
- material.angular.io is for angular-material, which is also a different library

Per our README you'll probably want to look at our Getting Started Guide: https://material.io/components/web/docs/getting-started/

You can also check out our codelab, which you may find useful! https://codelabs.developers.google.com/codelabs/mdc-web/index.html

**Comment by megamindbrian** [comment]
Thanks, looks like at least 3 duplication of efforts.  This project isn't
hosted on StackOverflow and I don't have any points to participate in the
elitist forum.

**Comment by traviskaufman** [comment]
@megamindbrian Sorry, I should've specified: You can ask a Question regarding MDC-Web by tagging it with the tags `material-components` and `web`: https://stackoverflow.com/search?q=material-components+web

**Comment by megamindbrian** [comment]
@traviskaufman Good points.  I should have specified my entire life people have considered me a social outcast and a "troll".  Regardless of how decently I write, I find this message too alienating:
![image](https://user-images.githubusercontent.com/25057134/26891404-bd1932d6-4b69-11e7-8ce6-aad9107ba2b1.png)
Even if I did have something positive to add, I can't.

**Comment by traviskaufman** [comment]
@megamindbrian in any case, as long as you adhere to our [code of conduct](https://github.com/material-components/material-components/blob/develop/CONDUCT.md), you are always welcome to post here 😃
