### ISSUE TITLE
textarea with required option

### ISSUE THREAD

**Issue by Shyam-Chen** [material-components/material-components-web#800]
![default](https://user-images.githubusercontent.com/13535256/26928534-0992c558-4c89-11e7-9892-733e5b020564.PNG)

live demo: https://web-go-demo.firebaseapp.com/contact

**Comment by amsheehan** [comment]
Closing this as it is too vague to be actionable. Please see our [Issue Submission Guidelines](https://github.com/material-components/material-components-web/blob/master/.github/ISSUE_TEMPLATE.md) for more information.

**Comment by Shyam-Chen** [comment]
In the field with validation, `textarea` default should not have red borders.
