### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by nucamoz** [material-components/material-components-web#803]
Using one component that I installed with `npm install --save @material/checkbox` I got error

```
Module build failed: 
@import '@material/checkbox/mdc-checkbox';
^
      File to import not found or unreadable: @material/checkbox/mdc-checkbox.
Parent style sheet: stdin
```

If I tried to add `node_modules` to path, then I got error anyway

```
Module build failed: 
@import "@material/animation/functions";
^
      File to import not found or unreadable: @material/animation/functions.
Parent style sheet: /home/*****/PROJECTS/testing/node_modules/@material/checkbox/mdc-checkbox.scss
```

What to do?

**Comment by traviskaufman** [comment]
Hey @nucamoz ,

What version of npm are you using? (You can find out by running `npm -v`). This may be due to how older versions of npm (`npm < 3`) vendor transitive dependencies.

**Comment by nucamoz** [comment]
5.0.0 @traviskaufman

**Comment by nucamoz** [comment]
It definitely can't resolve that path `@material` in files from `node_modules`. I guess I can manually rewrite them, but if I need to use couple components that a hell of a lot of dirty work. And if I reinstall `node_modules` then do it again? This is very strange, this is the first time I have such issue.

**Comment by nucamoz** [comment]
I am using Webpack

**Comment by nucamoz** [comment]
@traviskaufman any other tips, Jew?
