### ISSUE TITLE
Using Material Design Lite templates. Migration

### ISSUE THREAD

**Issue by kokujin** [material-components/material-components-web#806]
I would like to use a template from the [Material Design Lite site](https://getmdl.io/templates/dashboard/index.html)

I noticed that changing the occurences of "mdl-" to "mdc-" does not work. Is there a documented way to migrate  Material Design Lite markup to Material Components? 
Thanks

**Comment by Garbee** [comment]
No migrations on a component level have been documented. You'll need to look over the docs of the existing components in MDC and see how to handle things in the new way and do a manual conversion on a component-by-component basis until it is all done.

**Comment by traviskaufman** [comment]
As @Garbee mentioned, there isn't an "automatic" way to migrate from MDL to MDC, although we have tried to document some of the things that have changed within a [migration guide](https://github.com/material-components/material-components-web/blob/master/docs/migrating-from-mdl.md). 

Thus you won't be able to automatically use the templates from MDL. Note that we have a discussion issue  around templates open at #456 if you'd like to suggest any!
