### ISSUE TITLE
List: List item start detail avatar seems crushed on mobile

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#814]
### What MDC-Web Version are you using?

> 0.12.1

### What browser(s) is this bug affecting?

> Chrome on Android.

### What OS are you using?

> Android 7.0

### What are the steps to reproduce the bug?

> 1. Go to [the lists demo page](https://material-components-web.appspot.com/list.html)
> 2. Scroll down to **Example - Two-line Lists, Avatars, end detail, inset dividers** => **"Files"**
> 3. Observe the component's behavior

### What is the expected behavior?

> The icon on the left should be a circle.

### What is the actual behavior?

> The icon on the left is crushed.

### Any other information you believe would be useful?

> This could be fixed by adding a `flex: 1;` to the `mdc-list-item__text` class.

**Comment by traviskaufman** [comment]
I can reproduce this for lists whose width is small enough that it makes the start detail avatar shrink. Thanks for reporting!

**Comment by touficbatache** [comment]
No problem :smiley: @traviskaufman

**Comment by touficbatache** [comment]
Will this bug be fixed soon? @traviskaufman. Could anyone help? @amsheehan @yeelan0319

**Comment by moog16** [comment]
I believe this was fixed with: https://github.com/material-components/material-components-web/issues/1941. See screenshot below:

![slice 1](https://user-images.githubusercontent.com/579873/35296492-0f3427d4-0031-11e8-9f3b-fc533c6175f8.png)
