### ISSUE TITLE
Wrong menu screenshot on material.io

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#817]
### What are the steps to reproduce the bug?

> 1. Go to https://material.io/components/web/catalog/menus/
> 2. Look at the screenshot / showcase image

### What is the expected behavior?

> The new MDC-Menu should be showcased

### What is the actual behavior?

> The old MDC-Menu is showcased

**Comment by shyndman** [comment]
@traviskaufman You can assign this to me.

**Comment by traviskaufman** [comment]
@shyndman done. Thanks!

**Comment by touficbatache** [comment]
When will it be fixed? @shyndman

**Comment by shyndman** [comment]
Hey @touficbatache,

Just testing on my end. I'll push live by EOD. Thanks for the report.

**Comment by touficbatache** [comment]
Okay! No problem.
