### ISSUE TITLE
[card] m3 Elevated card uses wrong surface color

### ISSUE THREAD

**Issue by jamesrkiger** [material-components/material-components-web#8203]
## Bug report
According to the [M3 specs](https://m3.material.io/components/cards/specs#e5e74f2e-9243-4324-bf03-09ecd0d3823a) enabled elevated card container color should be `md.sys.color.surface-container-low`. Currently, however, the card component seems to  use `md.sys.color.surface`.

From  material/core/tokens/m3/definitions/_md-comp-elevated-card.scss
```
'container-color': map.get($deps, 'md-sys-color', 'surface'),
```

### Steps to reproduce
Not needed

### Actual behavior
There is no contrast between an elevated card and the app background color.

### Expected behavior
There should be contrast, according to the specs.

### Screenshots
Expected:
![image](https://github.com/user-attachments/assets/2134eeac-2208-459e-a78f-13aff80c5f1d)

Actual:
![image](https://github.com/user-attachments/assets/4f8b6bd9-a97e-48b0-9c6a-6ce30964f06f)

### Your Environment:

```
   @angular/cdk: "18.2.3",
   @angular/material: "18.2.3",
```

### Additional context
A user filed this as [an issue](https://github.com/angular/components/issues/29163) for Angular/Components a while back, but was told this is the appropriate place to file it. I don't think they ever did that, though, so I am filing it here. Please let me know if you need any more information or if there is somewhere else I should be filing this.

**Comment by asyncLiz** [comment]
@andrewseguin would it be appropriate to re-open https://github.com/angular/components/issues/29163 now that Angular supplies its own [card tokens](https://github.com/angular/components/blob/9122335b25b28a5532159ab87c36aab3be9c3716/src/material/core/tokens/m3/definitions/_md-comp-elevated-card.scss#L25)?

**Comment by andrewseguin** [comment]
Yeah that makes sense - I re-opened the issue

**Comment by asyncLiz** [comment]
Thank you!
