### ISSUE TITLE
MDC Switch knob rendered above the toolbar

### ISSUE THREAD

**Issue by stasson** [material-components/material-components-web#834]
## MDC Switch knob rendered above the toolbar

Hello MDC Team, I'm submitting this bug in the context of this project [stasson/vue-mdc-adapter](https://github.com/stasson/vue-mdc-adapter). I'm trying to implement Vue adapters of MDC ( foundation way)

When I scroll down a page containing a Fixed toolbar and a MDC Switch, the switch knob stays above the toolbar. See the project [preview](https://stasson.github.io/vue-mdc-adapter)

### What MDC-Web Version are you using?

> `@material/switch@0.1.8`
> `@material/toolbar@0.3.3`

### What browser(s) is this bug affecting?

> Chrome Version 58.0.3029.110 (64-bit)

### What OS are you using?

> Windows 10 pro

### What are the steps to reproduce the bug?

> 1. open the [preview](https://stasson.github.io/vue-mdc-adapter)
> 2. scroll down until you see the switch element
> 3. scroll so that the switch is masked by the toobar

> I'll try to write a  [template on CodePen](http://codepen.io/traviskaufman/pen/pNQmRp) if you think it'll help more

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/13608867/27196423-a8c28362-520a-11e7-95b4-fa5e22b265bd.png)
![image](https://user-images.githubusercontent.com/13608867/27196404-99384f26-520a-11e7-8a4b-1c45f669c58c.png)
![image](https://user-images.githubusercontent.com/13608867/27196438-bdd2b2cc-520a-11e7-900d-e298699dfa87.png)

> I would expect the knob to not be seen when positioned under the toolbar

### What is the actual behavior?

> the switch nob is not masked by the toolbar

### Any other information you believe would be useful?

I guess could fix it in my CSS but thought it may be something you guys may want to know.

**Comment by traviskaufman** [comment]
Thanks for filing @stasson! This is definitely a bug. We've had multiple issues like this as a result of elevation not being intrinsically mapped to z-indices. We're long-term addressing this problem in #769. 

However, as a short-term fix, the toolbar's elevation is set to a depth of `4`, so we could simply change the `z-index` for _fixed_ toolbars from `1` to `4` to correct for this.
