### ISSUE TITLE
toolbar menu

### ISSUE THREAD

**Issue by broros** [material-components/material-components-web#861]
![screen shot 2017-06-25 at 9 48 10 pm](https://user-images.githubusercontent.com/598228/27525147-309e5242-59f0-11e7-8a6a-c4d86c896ec9.png)
how should I add menu navigation in the toolbar?  is there specific classes I should use?

**Comment by amsheehan** [comment]
See the demo for [MDC Tab Bar]() to get a feel for what this looks like. There are a few examples of tab bars inside of toolbars. Basically:

```html
<div class="mdc-toolbar">
  <div class="mdc-toolbar__row">
    <div class="mdc-toolbar__section mdc-toolbar__section--shrink-to-fit mdc-toolbar__section--align-start">
      <h1 class="mdc-toolbar__title">Title</h1>
    </div>
    <div class="mdc-toolbar__section my-modified-toolbar-section">
      <nav id="toolbar-tab-bar-modified" class="mdc-tab-bar">
        <a class="mdc-tab mdc-tab--active" href="#one">Item One</a>
        <a class="mdc-tab" href="#two">Item Two</a>
        <a class="mdc-tab" href="#three">Item Three</a>
        <span class="mdc-tab-bar__indicator"></span>
      </nav>
    </div>
  </div>
</div>
```

then in JS:

```js
const tabBar = document.querySelector('#toolbar-tab-bar-modified');

const toolbarTabBarModified = new mdc.tabs.MDCTabBar(tabBar);
```

**Comment by broros** [comment]
I found tabs http://material-components-web.appspot.com/tabs.html
 however tabs is not listed in the main site https://material.io/components/web/catalog/
