### ISSUE TITLE
[Feature Request] export animation utilities from material-components-web package

### ISSUE THREAD

**Issue by arabsight** [material-components/material-components-web#863]
Can you please export the animation utilities from material-components-web.

**Comment by amsheehan** [comment]
@arabsight Could you be more specific? Are you referring to something outside of `mdc-animation`?

**Comment by arabsight** [comment]
@amsheehan I want to use *getCorrectEventName* utility function but its not exported from material-components-web (at least I couldn't find it).

**Comment by arabsight** [comment]
I did a custom build, adding this to material-components-web:
```js
import * as animation from '@material/animation';
...

// Export all components.
export {
  base,
  animation,
  checkbox,
...
```
and used it:
```js
import * as mdc from 'material-components-web';
mdc.animation.getCorrectEventName(window, 'animationend')
```

**Comment by moog16** [comment]
we started exporting all utils from a packages under `mdc.foo.utils`. Closing as this has been resolved since.
