### ISSUE TITLE
Update component catalog

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#864]
One of our contributors pointed out in our Discord channel that the [MDC Web Catalog](https://material.io/components/web/catalog/) does not include some of the newer components. We should take some time to get the catalog updated. In this instance, `MDC Tab Bar` was the component in question.

**Comment by touficbatache** [comment]
The slider isn't there too!

**Comment by amsheehan** [comment]
This was done yesterday! The team will figure out a way to make this part of our normal release flow so in the future, everything is up to date!
