### ISSUE TITLE
Component Request: App Shortcut Icon

### ISSUE THREAD

**Issue by JackCA** [material-components/material-components-web#868]
The "Single Avatar" documented on the [Icons Guideline page](https://material.io/guidelines/style/icons.html#icons-app-shortcut-icons) (and embedded bellow) does not appear to be present in MDC-web.

I see references to similar styling in the Avatar List components but nowhere else.

Apologies if I overlooked something but I didn't see any evidence of it alone and it seems like a great component/style to have available.

Guideline Screenshot:
<img width="1240" alt="screenshot 2017-06-27 13 00 13" src="https://user-images.githubusercontent.com/296167/27607565-1f8326fa-5b39-11e7-864f-f5a58b430bb5.png">

**Comment by Garbee** [comment]
Single avatar is not a stand-alone component piece. It is piece that supports the "App Shortcut Icon". The appearance of this component is very familiar to the "Speed Dial" one which is being tracked in issue #283. 

Perhaps Speed Dial should be morphed into App Shortcut Icon? Can we get some guidance from the MD team on this one since there are two components that basically do the same thing.

**Comment by JackCA** [comment]
@Garbee you're right, I've renamed this issue to match that -- my bad.

That being said, if I'm looking at the material design guidelines, I wouldn't personally know that the "Speed Dial" component is the same thing as the "App Shortcut Icon" and would then assume it's missing from MDC-web

**Comment by Garbee** [comment]
They are the same face of functionality. Not sure why we'd need two distinct components to provide the same UX that is only divided by some extra text for the most part. Hence why we should get some input from the MD team as to whether both are required or if there are any plans on merging the two components into one internally.

Just trying to save some extra work if it can be helped.

**Comment by JackCA** [comment]
@Garbee, just to clarify, the intention of my last comment's second paragraph was to provide end-user perspective and to ultimately agree with what you said from your prior comment:

> Perhaps Speed Dial should be morphed into App Shortcut Icon? ...

Looking forward to input from MD team

**Comment by amsheehan** [comment]
I will check with design/product to see what they think. I think @Garbee makes a lot of sense that there's little need to add a second component whose only difference is some text. In any case, the problem of ambiguity that this issue addresses will become more clear with the actual implementation/documentation etc...

Thanks!
