### ISSUE TITLE
mdc-textfield--fullwidth is not working inside mdc-form-field

### ISSUE THREAD

**Issue by dacodekid** [material-components/material-components-web#870]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What MDC-Web Version are you using?

> 0.14.0

### What browser(s) is this bug affecting?

> All

### What OS are you using?

> MacOS

### What is the expected behavior?

> `mdc-textfield--fullwidth` should expand to available width inside `mdc-form-field`

### What is the actual behavior?

> `md-textfield--fullwidth` only works outside of `mdc-form-field` class.
> [Codepen](https://codepen.io/dacodekid/pen/zzPbJL)

### Any other information you believe would be useful?
> Seems [this is what](https://github.com/material-components/material-components-web/blob/afec4704caa0dd790c989b2c2c4c637849a19fed/packages/mdc-form-field/mdc-form-field.scss#L28) causing the issue

**Comment by dacodekid** [comment]
I assume this is related to [this issue](https://github.com/material-components/material-components-web/issues/775). If `fullwidth` doesn't support `label`, then it shouldn't be wrapped under `mdc-form-field`.

**Comment by amsheehan** [comment]
@dacodekid you are correct in your assumption that full width text fields do not support labels. Out of curiosity, why do you assert that they shouldn't be wrapped under `mdc-form-field`?

**Comment by dacodekid** [comment]
Sorry for not being clear... I actually meant that for `floating labels`.  After I opened this issue, noticed the `text` is little off on [`full-width` class](https://github.com/material-components/material-components-web/issues/775) and mixed them all into that wrong conclusion :). 

Solved this issue by setting them to 100% as suggested on that above issue.
