### ISSUE TITLE
FAB z-index

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#872]
### What MDC-Web Version are you using?

> 0.14.0

### What browser(s) is this bug affecting?

> Chrome for Android 58.0.3029.83

### What OS are you using?

> Android 7.0

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/fab.html
> 2. Scroll down a little till the FAB at the bottom right is under another showcased FAB
> 3. Observe the component's behavior

### What is the expected behavior?

> The bottom right FAB should be over the other showcased FABs

### What is the actual behavior?

> The bottom right FAB is under the other showcased FABs

### Any other information you believe would be useful?

> I think that this could be fixed by changing its z-index

**Comment by amsheehan** [comment]
Yep! Can confirm this is a bug. Would you want to submit a PR for this? A fix would be setting a higher `z-index` on `#demo-absolute-fab` in `demos/fab.html`

Thanks!

**Comment by touficbatache** [comment]
Sure. About how much?

**Comment by touficbatache** [comment]
And I wanted to ask you, I have currently another PR. How can I create one that changes the z-index without the other one affecting this one?
