### ISSUE TITLE
BUG: Temporary Drawer display error on IE 11 in win10

### ISSUE THREAD

**Issue by spyhole** [material-components/material-components-web#881]
Bugs

What MDC-Web Version are you using?

v0.14.0

What browser(s) is this bug affecting?

IE 11

What OS are you using?

Windows 10

What are the steps to reproduce the bug?

![2](https://user-images.githubusercontent.com/1698342/27784703-9ed1ae94-600d-11e7-9344-cf7b44679867.gif)

What is the expected behavior?

black color background

What is the actual behavior?

grey color background

Any other information you believe would be useful?

the mdl version is ok.
![1](https://user-images.githubusercontent.com/1698342/27784745-ceabf408-600d-11e7-8311-0b0cd081f3cb.gif)

**Comment by amsheehan** [comment]
This is indeed a bug! We currently set the `background-color` of that icon to `inherit`. Perhaps the correct solution is to set it to `transparent` for more browser compatibility.

Would you have time to make that change and submit a PR?

**Comment by spyhole** [comment]
@amsheehan 

i put all my energy on a rails project that struggle with code structure and browser compatibility.
in fact, there are more bugs (not submitting) on windows 10 with IE 11. 
when free, i will involve it
