### ISSUE TITLE
When the text is too long wrap will lead to lack of clarity between items

### ISSUE THREAD

**Issue by Shyam-Chen** [material-components/material-components-web#889]
### What MDC-Web Version are you using?

v0.14.0

### What browser(s) is this bug affecting?

All browsers

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

https://codepen.io/Shyam-Chen/pen/VWXKGZ

### What is the expected behavior?

![default](https://user-images.githubusercontent.com/13535256/27762056-1d2e2cc2-5e9c-11e7-99fc-ae4ff6f0118c.PNG)

### What is the actual behavior?

![2](https://user-images.githubusercontent.com/13535256/27762077-a1bf232e-5e9c-11e7-9d87-ba048601d1ae.PNG)

### Any other information you believe would be useful?

:x:

**Comment by touficbatache** [comment]
Maybe a lower `line-height` could do the trick? For example a `line-height: 1rem;` instead of `1.5rem` solves the problem. https://codepen.io/anon/pen/QgmmyP

**Comment by amsheehan** [comment]
This one might need some design guidance. Thank you for filing. I'll check out our options and get back to you.

**Comment by touficbatache** [comment]
What's up with the design guidance? @amsheehan

**Comment by moog16** [comment]
Design guidance calls for an ellipsis. This is baked into list now. Closing as this question has been answered/resolved.
