### ISSUE TITLE
Strip redundant source comments out of built entries

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#89]
We can achieve this using [babel-plugin-remove-comments](https://www.npmjs.com/package/babel-plugin-remove-comments). Comments will still be preserved in source maps as well as in distributed source files.

Built files included with npm will have comments added via the webpack banner plugin.

We should also also investigate enforcing scss-only comments via stylelint once all files have been migrated over.

**Comment by sgomes** [comment]
Note that this should cover both `js` and `css` output files.
