### ISSUE TITLE
Integrating MDCSelect to vuejs help

### ISSUE THREAD

**Issue by xxRockOnxx** [material-components/material-components-web#894]
`material-components-web: 0.13.0`

I just looked at the `index.js` to see how the default implementations work and change things from there to match how vuejs does things... or actually, I just use `refs` instead.

Anyway, here's the code:

For the `MDCSimpleMenu`:
~https://www.hastebin.com/ecazajarub.xml~

For the `MDCSelect`:
~https://www.hastebin.com/cuvewejati.xml~

The select is not opening. I'm not sure what's wrong. I just converted the defaults to vuejs one.

**EDIT**
Ok, re-read the docs and saw I should be returning `MDCSimpleMenu`. But how can I return `MDCSimpleMenu` using my own integration? currently, I pass it an `MDCSimpleMenuFoundation` instance.

**EDIT**
I missed the `init()`. Now I get `menu.listen` is not a function.

If you'll look at my `MDCSelect` integration, I have there `let menu = this.$refs.menu.foundation`. Again, I instead access the foundation of `MDCSimpleMenu` and it `listen` is coming from `MDCComponent` which I don't extend.

How should I then fix this?

**EDIT**
on my `MDCSimpleMenu`, I created a method `listen` that actually calls its own `registerInteractionHandler`

and added a `getItems()` method on its adapter so `MSelect` can access its items.

No errors now, but still not working. It doesn't open. No DOM changes (classes, or anything).

MDCSelect: https://www.hastebin.com/vufibupumu.xml
MDCSimpleMenu: https://www.hastebin.com/moxazecuka.xml

**Comment by spyhole** [comment]
maybe u can get help with the link https://github.com/stasson/vue-mdc-adapter

**Comment by xxRockOnxx** [comment]
So I fixed it. Until then when I'll have a problem will I change this.

A little guilty tho cause it beats the sense of having component.

What I did was copy almost everything from the default implementations (index.js).

For `get` and `set` on `index.js`, I made a computed getter/setter.

For the methods, I just made methods also on the component.

The only difference are how I reference the elements:

`this.root_` = `this.$el`
`this.elementOfRoot` = `this.$refs.element`

I'll try to refactor everything to make it more vue-like but for now this works.

**NOTE**: Of course I will still be waiting for the right answers as I'm not really sure what I'm doing is right. Might save me from trouble in the future.

**Comment by xxRockOnxx** [comment]
@spyhole thanks for that. I'll be watching for it. Looks promising :)

**Comment by YavuzSelimGugen** [comment]
Hello there, i have issues too, im trying to implement material.io to vue.js webpack cli. I wanna use only needed components. So after installation of cli i say `npm install --save @material/checkbox` and in my .vue page i wrote import `Checkbox from 'node_modules/@material/Checkbox'`  and added as a component. But error says that _Can't resolve 'node_modules/@material/Checkbox' in 'C:\Users\Yavuz\Documents\apvi-staff\src\components'_ . Im newbi at this area, i dont know where im wrong. Do you have any idea ?

**Comment by moog16** [comment]
Looks like this issue has gone stale. Going to close.
