### ISSUE TITLE
 BUG: Grid List display error on IE 11 in win10

### ISSUE THREAD

**Issue by spyhole** [material-components/material-components-web#895]
Bugs

What MDC-Web Version are you using?

v0.14.0

What browser(s) is this bug affecting?

IE 11

What OS are you using?

Windows 10

What are the steps to reproduce the bug?

access the url with IE 11 on Win10

What is the expected behavior?

![3](https://user-images.githubusercontent.com/1698342/27785006-c8803da4-600e-11e7-9856-f79bb6720a86.gif)

What is the actual behavior?

![4](https://user-images.githubusercontent.com/1698342/27785021-d2a35c44-600e-11e7-8e31-79c482b2630c.gif)

**Comment by amsheehan** [comment]
This is indeed a bug. We are tracking it [here](https://github.com/material-components/material-components-web/issues/597)

If you would like to work on it, we would gladly review any and all PR's that come our way.

Thanks! Closing
