### ISSUE TITLE
MDCSelect wrong setStyle width

### ISSUE THREAD

**Issue by xxRockOnxx** [material-components/material-components-web#896]
### What MDC-Web Version are you using?
`material-components-web@0.14.0`

### What browser(s) is this bug affecting?
Only tested chrome and firefox on GNOME

### What OS are you using?

Ubuntu Gnome 17.04

### What are the steps to reproduce the bug?

- MDCSelect.attachTo(element)
- done.

### What is the expected behavior?

`mdc-select` width should be correct

### What is the actual behavior?

returns short values.

### Any other information you believe would be useful?

When not yet attaching an instance, the element looks good. Once initialized, the selected text cannot be seen.

**Comment by amsheehan** [comment]
Would you mind uploading a few screen shots of this behavior?

**Comment by xxRockOnxx** [comment]
Screenshot:

<img src="https://s9.postimg.org/pscj416kf/Screenshot_from_2017-07-07_06-01-56.png" />

Temporary fix: empty function for `setStyle`

**Comment by kmmbvnr** [comment]
Related issue #1335

**Comment by kmmbvnr** [comment]
I fixed this by patching select, to allow spread them to the whole container width

```
import {select} from 'material-components-web';

class MDCSelect extends select.MDCSelect {
  getDefaultFoundation() {
    let foundation = super.getDefaultFoundation(),
        super_setMenuStyle = foundation.setMenuStylesForOpenAtIndex_

    foundation.resize = function() {
      /* no action here */
    }

    foundation.setMenuStylesForOpenAtIndex_ = function (index) {
      super_setMenuStyle.call(foundation, index)

      const rect = foundation.adapter_.computeBoundingRect()
      foundation.adapter_.setMenuElStyle('width', `${rect.width}px`);
    }

    return foundation
  }
}
```

**Comment by Wroud** [comment]
same issue

**Comment by mellogarrett** [comment]
For some reason, it doesn't calculate my longest option correctly. It's always 24 px short (which is also the padding size).

<img width="214" alt="screen shot 2017-12-04 at 1 36 06 pm" src="https://user-images.githubusercontent.com/9908831/33569659-56d7c2ae-d8f8-11e7-8e84-bad973b738f1.png">

**Comment by RobertSmits** [comment]
Do you do somthing like 
```
* {
  box-sizing: border-box;
}
```
'cause then that's your problem.
The width is calculated as `content-box`

**Comment by mellogarrett** [comment]
Ahh wow! Thanks!

That's in the default css generated by `preact-cli`. Removing it fixed my issue.

**Comment by abhiomkar** [comment]
Closing this as obsolete.
