### ISSUE TITLE
Confused around use of themes

### ISSUE THREAD

**Issue by ZhugeSong** [material-components/material-components-web#902]
After experimenting for a while using MDC-Web, I've become confused regarding how themes are actually supposed to work. Having read the examples provided on https://material.io/ I tried to set up theme colors and a few components. See [my CodePen example](https://codepen.io/ZhugeSong/pen/WOyoBz).

Providing values for the primary (I picked near black) and accent (I picked a red) theme colors works like I would expect, but the theme background color (I picked near black) didn't seem to be used for anything. My first thought was that I simply wasn't using it correctly; that the page's background color is still meant to be light, just certain components would use the theme background color for their background.

However, I'm confused around the behavior of the card component. I've set all the proper theme text colors; white for everything except on a light background, which I set to black. This, I thought, was appropriate because I would want white text on the primary color (black), accent color (red), background color (black), and other dark backgrounds, and white text on other light backgrounds.

The card component seems to be using the text color to go with the theme background, but it doesn't actually use the theme background, so the text is unreadable. Is this intentional, or am I required to specify that the card uses the theme background for it to work correctly by default?

I went back and looked over the theme documentation to see if the "dark theme" option was needed for some reason. However, that seems to just worsen the problem as then the buttons are then set to expect a dark theme background, that, while specified in the CSS, isn't actually used by those components. So I was confused by the point of the dark theme class if it only seems change the text color used by components that you have to set a background for manually anyway. And in that case, why would you not specify the custom text color class at the same time?

My expectation was that either the card (or any other component) would either set both a background and text color (such as theme background and text on theme background), or none at all. If it sets only one as I am observing (such as text on theme background, but leaving background color unchanged), then this seems like it can easily cause default components to break when the theme is set to certain colors.

I suspect I might be missing something fundamental about how the theme colors are supposed to be used (e.g., the variable for text on background doesn't mean theme background, but the default background of the page?), but if not I'd like to try to narrow the focus to what part of my usage is actually breaking.

### What MDC-Web Version are you using?

Version 0.14.0 (latest at this moment)

### What browser(s) is this bug affecting?

Observed in Chrome 59.0.3071.115 (64-bit), Firefox 54.0.1 (32-bit)

### What OS are you using?

Windows 8.1 (64-bit)

**Comment by amsheehan** [comment]
You're pretty much there with understanding how `mdc-theme` works. I think the biggest gap in understanding might be the assumption that MDC Web is going to set dark theme background colors. If you are using a dark theme, you will need to set your dark theme colors yourself. There are a few examples of this in the demos.

The best way to use theme colors is to include all of the `scss` files in your project and then override the theme variables immediately after. That way unless there are some other implementation specific challenges, your theme colors should be applied correctly to the components.

**Comment by ZhugeSong** [comment]
Thanks for reading my wall of text.

I explained myself poorly. I didn't expect to automatically get a dark background color just by using the dark theme class; I thought that was simply for supporting when `--mdc-theme-background` was set to a dark color, which I have done in my case.

Notably, it looks like the drawer component uses the theme (dark or not) the way I would expect: it applies `--mdc-theme-background` for the background, then `--mdc-theme-text-primary-on-background` to the text, which makes sense; all you need to do is properly set those colors.

The card component, on the other hand, doesn't use `--mdc-theme-background`, so why is it using `--mdc-theme-text-primary-on-background`? This happens regardless of my use of the `mdc-theme--dark` helper class.

**Comment by lynnjepsen** [comment]
`--mdc-theme-background` does mean "the background color for your application. This is the color on top of which your UI is drawn."

I think drawer is a special case. I still need to confirm with our design team, but it looks like drawer takes the same `--mdc-theme-background` for it's background. I am guessing this is because it is a large component that is almost part of the background...but still confirming.

I think mdc-card has a CSS bug. I think mdc-card should change `mdc-theme-prop(color, text-primary-on-background)` to `mdc-theme-prop(color, text-primary-on-light)`. In your [codepen](https://codepen.io/ZhugeSong/pen/WOyoBz) you already specify a very dark grey for `--mdc-theme-text-primary-on-light`. With a fix to our mdc-card code, your existing theme would make the card readable. And you can still set `--mdc-theme-background` to near black, and `--mdc-theme-text-primary-on-background` to white.

I'm going to open a new issue for mdc-card in particular, and get a PR out for that. I'm also going to tag this as 'needs-design-guidance' so we can confirm that drawer is using 'background' correctly.

**Comment by ZhugeSong** [comment]
Thanks, that clarifies a lot. I appreciate your detailed response!

I will be interested to hear the final result regarding the drawer; I happen to agree that the drawer is a bit of a special case, and that using the background color from the theme there is fine. That said, after taking a look at it again it seems to be styling the text with different color variables than I had expected.

```
+-------------------------+--------------------------------------------+------------------------------------------------------+
| Theme Setting           | Default (Light)                            | `mdc-theme--dark` (Dark)                             |
+-------------------------+--------------------------------------------+------------------------------------------------------+
| Drawer Header Color     | Default (probably black)                   | `--mdc-theme-text-primary-on-dark`                   |
|                         | [Potentially unreadable, but probably not] | [Acceptable, dark theme should have dark background, |
|                         |                                            |  but why not just use primary on background color?]  |
+-------------------------+--------------------------------------------+------------------------------------------------------+
| Drawer List Item Color  | `--mdc-theme-text-primary-on-background`   | `--mdc-theme-text-primary-on-dark`                   |
|                         | [Good, picks right text for background]    | [Acceptable, dark theme should have dark background, |
|                         |                                            |  but why not just use primary on background color?]  |
+-------------------------+--------------------------------------------+------------------------------------------------------+
| Drawer Background Color | `--mdc-theme-background`                   | `--mdc-theme-background`                             |
+-------------------------+--------------------------------------------+------------------------------------------------------+
```

If the drawer is intended to be using `--mdc-theme-background` for the background (which is fine with me), it should probably also use `--mdc-theme-text-primary-on-background`, regardless of whether `mdc-theme--dark` is set.

**Comment by lynnjepsen** [comment]
I talked with our design team, and it sounds like a navigational drawer can be _any_ color. I'm going to file another bug to fix our Sass variables such that developers can override the color of a navigational drawer. We'll be sure to double check the text-on-* properties when we make this change.

**Comment by ZhugeSong** [comment]
Cool, thanks for your help!

**Comment by aaronhudon** [comment]
@lynnjepsen would you be able to provide a guide on how to apply a color palette chosen from https://material.io/color/ and the correct css variables that need to be set?

**Comment by ZhugeSong** [comment]
@aaronhudon Start with looking at the [Usage information for mdc-theme](https://github.com/material-components/material-components-web/tree/master/packages/mdc-theme#usage); it has a pretty good overview of all the variables you need to set.

If you are using pure CSS, you'll have to set the main theme colors (primary, background, accent) as well as the all of the text colors. If you are using SCSS, you can just set the main theme color variables and I believe the text colors will be calculated for you if you do not specify them.

**Comment by aaronhudon** [comment]
@ZhugeSong thanks for the reply, i've started to muddle through it and things are OK.  was just hoping that a best-practices tutorial exists.  Perhaps I'll create one!

**Comment by TimeBandit** [comment]
I have this at the top of my SCSS file yet the theme is still default. Am I missing something here?

`$mdc-theme-primary: #F08A5D;
$mdc-theme-secondary: #B83B5E;
$mdc-theme-background: #F9ED69;
@import "~material-components-web/dist/material-components-web";`
