### ISSUE TITLE
Textarea not displaying accurate placeholder font on Android

### ISSUE THREAD

**Issue by cgfarmer4** [material-components/material-components-web#903]
I have a textarea with the following markup:

```
<div class="mdc-textfield mdc-textfield--fullwidth mdc-textfield--upgraded">
      <input class="mdc-textfield__input" name="title" id="title" type="text" aria-label="Title" placeholder="Title">
    </div>

<div class="mdc-textfield mdc-textfield--multiline mdc-textfield--fullwidth mdc-textfield--upgraded" id="descriptionContainer">
      <textarea class="mdc-textfield__input" id="description" name="description" rows="8" cols="40" aria-label="Description" placeholder="Description"></textarea>
    </div>
```

It looks right everywhere but for some reason is a little off on Android. I can't figure it out as I've looked at the markup / css about 30x now. The fact it works right on Desktop Chrome and iOS is the most baffling. Bug?

##### Android

![browser-chrometabbedactivity-07042017162649](https://user-images.githubusercontent.com/336449/27844398-1b1c7736-60d6-11e7-8a63-21032a3ae7aa.png)

##### Desktop

![screen shot 2017-07-04 at 4 25 45 pm](https://user-images.githubusercontent.com/336449/27844400-225072d2-60d6-11e7-9ec6-a379dcec1839.png)

**Comment by touficbatache** [comment]
I can confirm this bug. But please next time, use the template provided for submitting issues as it provides clearer information on which OS, browser, etc this issue/bug is affecting.

**Comment by touficbatache** [comment]
Could this be fixed by adding a `mdc-typography` mixin to the textfield/textarea?

**Comment by cgfarmer4** [comment]
Apologies for the quick bug write up. 

But yes, that fixes it! Thank you for your time.

**Comment by touficbatache** [comment]
No problem :smiley: This issue shouldn't be closed as it needs to be fixed.

**Comment by amsheehan** [comment]
Bug indeed. Would either of you mind submitting a pull request for this? Thanks!

**Comment by cgfarmer4** [comment]
Awesome. I see where the issue is since the demos appeared to work fine and thats what was confusing me the most. On the demos [here](https://material-components-web.appspot.com/textfield.html), the `.mdc-typography` class attached to the body of the HTML. 

Is that a best practice?

**Comment by touficbatache** [comment]
@amsheehan What should the PR change?

**Comment by amsheehan** [comment]
@cgfarmer4 Yes, that would be one of the preferred ways to use it. That said, it should "just work", so when @touficbatache's PR gets merged the issue should be moot.

**Comment by touficbatache** [comment]
@amsheehan Why not just merge it now? 😃

**Comment by amsheehan** [comment]
There may be a small change to make 😄

**Comment by touficbatache** [comment]
What is it? I can change it

**Comment by amsheehan** [comment]
I left a comment on the PR

**Comment by cgfarmer4** [comment]
Thanks guys, loving the framework!
