### ISSUE TITLE
List end detail has a wrong padding

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#904]
### What MDC-Web Version are you using?

> 0.14.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> All OS

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/list.html
> 2. Scroll down to the **End Detail** section
> 3. Observe the end detail item's location

### What is the expected behavior?

> The end detail item should be 16px away from the end of the list

### What is the actual behavior?

> The end detail item should be 32px away from the end of the list

### Any other information you believe would be useful?

> This could easily be fixed by removing the `margin-right: 16px` from the `mdc-list-item__end-detail` class as the `mdc-list` class already has a padding of 16px on the right. Would you like a PR?

**Comment by amsheehan** [comment]
Yes please! Good catch.

**Comment by touficbatache** [comment]
Done :smiley:
