### ISSUE TITLE
improve form, buttons, links

### ISSUE THREAD

**Issue by broros** [material-components/material-components-web#907]
Can you make it easier to implement into third party frameworks?

** forms should work without classes, ids
** buttons should work without classes
** `<li>` list items

**Comment by Garbee** [comment]
We require targets to work to keep things separated and non-conflicting with other projects. If you don't want to use the class targets for styling then you can use Sass to setup your targets how you want for styling plain elements.

"Easier to integrate" however, is actually done by requiring the classes. This avoids style collisions that developers don't expect so you aren't needing to override various parts of one tool or another. By removing the classes, it ends up being more work and more confusing for people to integrate with other tools.

**Comment by amsheehan** [comment]
We agree with Garbee. If you have any other suggestions though about how to make framework integration easier, we're going to leave this thread open as a `discussion`

Thanks for filing!

**Comment by broros** [comment]
you are thinking that people are going to use more than one styling framework per project.. but this is not the case.

**Comment by Garbee** [comment]
It very much is the case. Or people just want to get one or two components into another framework. Hence why MCW is a library of components and not a framework.

This is directly from experience with MDL. I say people will mix things because they do. Whether it is expected or not.

**Comment by hugufc** [comment]
@amsheehan There's something like a policy or expiring time to close a Discussion?

**Comment by lynnjepsen** [comment]
I'm closing this discussion since there hasn't been any discussion since three days ago. The consensus is that MDC Web is a library of components, not a framework. MDC Web uses classes to avoids style collisions with other tool or frameworks.
