### ISSUE TITLE
mdc-toolbar/README.md/Adapter: `hasClass` method should return boolean instead of void

### ISSUE THREAD

**Issue by lewisle** [material-components/material-components-web#920]
### What MDC-Web Version are you using?

> [0.14.0](https://github.com/material-components/material-components-web/compare/v0.13.0...v0.14.0)

### What browser(s) is this bug affecting?

> Any

### What OS are you using?

> MacOS

### What are the steps to reproduce the bug?

> 1. From repo root, navigate to `packages/mdc-toolbar/README.md`
> 2. Go to [Adapter section](https://github.com/material-components/material-components-web/blob/master/packages/mdc-toolbar/README.md#adapter)
> 3. Observe the first method signature, `hasClass`.

### What is the expected behavior?

> `hasClass` should return a boolean value

### What is the actual behavior?

> `hasClass` returns a void

**Comment by lynnjepsen** [comment]
Thanks for filing this. Looks like a bug in our documentation. Feel free to send us a PR fixing the README!

**Comment by lewisle** [comment]
Yeah I proposed #921 to fix this
