### ISSUE TITLE
suggestion - the documents or not at all clear 

### ISSUE THREAD

**Issue by bhvreddy** [material-components/material-components-web#927]
documentation for material component is really complex- there are lot of issues, more over some places its really hard to move on .. wish document will get easy

**Comment by Garbee** [comment]
Do you have any examples you can point to that are difficult to understand? Being able to show what you're not understanding will help us document things better overall. We are always shooting for easy to understand documentation, that's why it exists. But, what different people think is easy varies. So having concrete examples with context helps us understand how to write things more clearly.

Thank you.

**Comment by bhvreddy** [comment]
its mostly like where modules uses , it confuse a lot, 

e.g. like in https://material.io/components/web/catalog/buttons/icon-toggle-buttons/
suggest to install npm install --save @material/icon-toggle then when 
use `import {MDCIconToggle} from 'mdc-icon-toggle';`  where is mdc-icon-toggle , in @material/icon-toggle ,  later ended with import {MDCIconToggle} from '@material/icon-toggle';  took lot of time to get this, in the same way https://material.io/components/web/catalog/drawers/ .. so many places where ever module uses it look lot of time to get in..   

**complete documentation is not in one way.  there may be multiple way to do single thing. but that not documented well** 
https://material.io/components/web/catalog/drawers/

**Comment by bhvreddy** [comment]
if added example, at least some video, blog tutorials on how to use those modules it will be easy

Thank you.

**Comment by Garbee** [comment]
> so many places where ever module uses it look lot of time to get in..

I don't feel like teaching developers how JavaScript modules work is really something the project needs to take on. We should certainly have a section in the getting started of "Things to know" before using the library with links to better resources for learning that stuff. Covering it internally though is asking a bit too much.

**Comment by touficbatache** [comment]
@bhvreddy To make it simpler, go to https://unpkg.com/material-components-web@latest/dist/, download the `material-components-web.css` and the `material-components-web.js` files and import them as normal js and css files in your html file. Then you can use `data-mdc-auto-init` (it can be found on every component's documentation page) on MDC Components that need JS for example: Textfields, Ripples, Buttons, etc...

**Comment by lynnjepsen** [comment]
> video, blog tutorials on how to use those modules it will be easy

We don't currently have the bandwidth to generate this kind of material. Instead we focus on good documentation, and using modern/friendly technologies like [ES6](https://babeljs.io/learn-es2015/), [Sass](http://sass-lang.com/guide), and [NPM](https://docs.npmjs.com/getting-started/what-is-npm). 

If you find bugs in our documentation, please file specific issues. Or submit a PR to fix them!

**Comment by bhvreddy** [comment]
@Garbee , i am not asking to explain how to use modules or any thing, 

**i am just saying the documents are bit confused**.   ( as it confused i feel examples or a blog is there it will be **easy** for developers to work on - that's what i feel  -  and i know that not easy ) 

any how 
Thank all
