### ISSUE TITLE
Unhandled Promise rejection: Failed to load

### ISSUE THREAD

**Issue by mtr986** [material-components/material-components-web#932]
Hi, I am getting unhandled and live server not responding due to mdc.select.min.css find in @material>select. the following issue started out of blue just by restarting the computer. i can see in the file structure of @material that mdc.select.min.css should be in select>dist folder. but still getting the error. I have spent 4 hours with no luck.

Failed to load resource: the server responded with a status of 404 (Not Found)

:4200/node_modules//dist/mdc.select.min.css Failed to load resource: the server responded with a status of 404 (Not Found)

polyfills.bundle.js:3057 Unhandled Promise rejection: Failed to load ../../../../../node_modules//dist/mdc.select.min.css ; Zone: ; Task: Promise.then ; Value: Failed to load ../../../../../node_modules//dist/mdc.select.min.css undefined

api.onUnhandledError @ polyfills.bundle.js:3057
polyfills.bundle.js:3059 Error: Uncaught (in promise): Failed to load ../../../../../node_modules//dist/mdc.select.min.css

at resolvePromise (polyfills.bundle.js:3184)
at resolvePromise (polyfills.bundle.js:3155)
at polyfills.bundle.js:3232
at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.bundle.js:2838)
at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (polyfills.bundle.js:2605)
at drainMicroTaskQueue (polyfills.bundle.js:2998)
at XMLHttpRequest.ZoneTask.invoke (polyfills.bundle.js:2904)
api.onUnhandledError @ polyfills.bundle.js:3059
](url)

*********************
angular-cli.json
********************
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "edrop"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
       "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "styles.css"
      ],
      "scripts": [],

      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

**Comment by yeelan0319** [comment]
Hi @mtr986 ,
Took a quick look, the path looks a bit suspicious to me: 

`../../../../../node_modules//dist/mdc.select.min.css ` 

it has double // before dist and don't have `@material` specified. 

Also, in your angular-cli.json config, it seems `$schema` have same double // pattern, `"$schema": "./node_modules//lib/config/schema.json"`...

Could you check above and see if that solve your problem?
Otherwise, could you leave more information about how you include `mdc.select` in the project?

**Comment by kfranqueiro** [comment]
Given that this didn't receive any further response, I'm closing the issue.

As mentioned previously, this seems like an issue with the path being used to reference the CSS; I'd expect it to look more like `.../node_modules/@material/select/dist/mdc.select.min.css`.
