### ISSUE TITLE
Why the site can not visit?

### ISSUE THREAD

**Issue by f2ex** [material-components/material-components-web#937]
Visited the [material.io](https://material.io/components/web/) today, but there was a 404 error, the website address changed?

**Comment by spyhole** [comment]
the link is blank too,  "https://material.io/components/"

**Comment by f2ex** [comment]
@spyhole The text is hidden and it looks like it is being revised?
[Site screenshot](http://imgur.com/a/egvoq)

**Comment by touficbatache** [comment]
Yeah, it returns a 404 error. Strange.

**Comment by didierfranc** [comment]
Down

**Comment by touficbatache** [comment]
Not down anymore... Just the components site seems blank

**Comment by didierfranc** [comment]
<img width="717" alt="screen shot 2017-07-13 at 11 45 53" src="https://user-images.githubusercontent.com/14132464/28160560-e63e92d2-67c0-11e7-94d2-7c98fc66f219.png">

```
https://material.io/components/web/catalog/
```

**Comment by spyhole** [comment]
Does this mean that a revolutionary version is coming soon? (^-^)

**Comment by lynnjepsen** [comment]
Site is back up! Sorry for the inconvenience.
