### ISSUE TITLE
 UglifyJs Unexpected token: name in vue.js

### ISSUE THREAD

**Issue by bernessco** [material-components/material-components-web#938]
When i try to build vue project i get this:
```
ERROR in static/js/vendor.6478674a299b30d86169.js from UglifyJs
Unexpected token: name (storedTransformPropertyName_) [./~/@material/drawer/util.js:20,0][static/js/vendor.6478674a299b30d86169.js:2723,4]
```
I tried to set bable-loader presets to es2015, but it seems that these files ether don't go trough it or something else is happening, that i can't work it out.

**Comment by Shyam-Chen** [comment]
see #929

**Comment by bernessco** [comment]
Thanks it worked by adding resolve to bable-loader
