### ISSUE TITLE
Dialog buttons should use primary color

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#940]
### What MDC-Web Version are you using?

> 0.15.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> Windows 7 / Android 7.0

### What are the steps to reproduce the bug?

> 1. Go to http://material-components-web.appspot.com/dialog.html
> 2. Observe the component's behavior

### What is the expected behavior?

> The button text should use the primary color

### What is the actual behavior?

> The button text is black

### Any other information you believe would be useful?

> All the photos show a dialog with colored buttons: https://material.io/guidelines/components/dialogs.html

**Comment by lynnjepsen** [comment]
Our http://material-components-web.appspot.com sets it's primary color to black. So this is working as intended.

`--mdc-theme-primary: #212121;`
