### ISSUE TITLE
Buttons no longer use the Roboto / theme font

### ISSUE THREAD

**Issue by qkjosh** [material-components/material-components-web#942]
### What MDC-Web Version are you using?

Using material/button 0.3.9

### What browser(s) is this bug affecting?

Chrome 59.0.3071.115  / Firefox 54.0.1

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Compile the mdc-button.scss file.

### What is the expected behavior?

Buttons styled with .mdc-button should use the Roboto font.

### What is the actual behavior?

Button elements switch back to a sans-serif font if using normalize.css, or Arial if not.

### Any other information you believe would be useful?

It looks like in PR #871 the dependency on mdc-typography was removed, but now normalize.css and/or the browser default styles have more specific rules for button elements that changes the font-family. Links with the .mdc-button class still get the correct font, because they inherit from body. You can see this in the components catalog: https://material-components-web.appspot.com/button.html 

For now, adding a typography class like .mdc-typography--body1 will fix the issue, but it would be nice to have the old behaviour where buttons use the Roboto / theme font by default.

**Comment by lynnjepsen** [comment]
Definitely looks like a bug. Thanks for filing this!
