### ISSUE TITLE
.mdc-slider__thumb-container should set #user-select property to none

### ISSUE THREAD

**Issue by jecisc** [material-components/material-components-web#945]
### What MDC-Web Version are you using?

v0.15.0

### What browser(s) is this bug affecting?

Firefox v54.0.1

### What OS are you using?

Windows 7

### What are the steps to reproduce the bug?

In the slider [demo](https://material-components-web.appspot.com/slider.html) just click on the "Discrete Slider" and move fast.  

### What is the expected behavior?

A popup appear and should not be selectable. 

### What is the actual behavior?

If I move fast, the text in the popup is selected. 

### Any other information you believe would be useful?

.mdc-slider__thumb-container class should use the "user-select" property with none. 
https://developer.mozilla.org/fr/docs/Web/CSS/user-select

**Comment by lynnjepsen** [comment]
adding `user-select: none` to `mdc-slider__thumb-container` seems correct. Happy to accept a PR for this!
