### ISSUE TITLE
Expansion Panel Component (accordion) ?

### ISSUE THREAD

**Issue by oneezy** [material-components/material-components-web#957]
This may or may have not have been addressed already, so I apologize in advance..

But what's up with an expansion panel/ accordion component? Is there plans to create one?

**Comment by touficbatache** [comment]
This component will be added in October: https://www.pivotaltracker.com/story/show/132790479

**Comment by lynnjepsen** [comment]
+1 to touficbatache's reply. Pivotal tracker shows when components will be built, or feature requests will be added to components, or bugs will be fixed.

**Comment by devagg-ar** [comment]
Any updates? Nothing on pivotaltracker.

**Comment by touficbatache** [comment]
@devagg-ar Yes, #2020

**Comment by devagg-ar** [comment]
@touficbatache Can we expect it in next release? Merging of pull is pending.

**Comment by griest024** [comment]
@aggarwaldev I'm moving it to code review now.
