### ISSUE TITLE
title hint is not hidden, when texts

### ISSUE THREAD

**Issue by bhvreddy** [material-components/material-components-web#967]
created a [demo](http://plnkr.co/edit/LUdJH5?p=preview)

https://material.io/components/web/catalog/input-controls/text-fields/

**Comment by touficbatache** [comment]
You're not using JS with the component, that's CSS only. Please follow the template the next time you want to submit a new issue as it makes more clear what the issue is.

**Comment by lynnjepsen** [comment]
Like @touficbatache said, Hint text is in a `mdc-textfield__label` element is only supported if you attach JavaScript to the root `mdc-textfield` element.

Here's the documentation for MDC Textfield with JavaScript: https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#single-line---with-javascript

If you want MDC Textfields without JavaScript, please use the `placeholder` attribute, as you did in your demo.

Here's the documentation for MDC Textfield without JavaScript: https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#single-line---gracefully-degraded
