### ISSUE TITLE
material.io icons incorrect

### ISSUE THREAD

**Issue by cbogwill** [material-components/material-components-web#970]
Not sure if this is the proper forum or not.  On material.io/icons, if you search for sentiment, you see 5 icons.  When you download the SVG version of them, they are all slightly different from what is shown when using the Icon Font.  

For example, 'sentiment dissatisfied' shows the frown of 'sentiment very dissatisfied', but with x's for eyes.

**Comment by Garbee** [comment]
The [Material Icons](https://github.com/google/material-design-icons) repository is the place to file issues relating to the icons.

**Comment by cbogwill** [comment]
Sorry.  Thanks for the direction!
