### ISSUE TITLE
Make button stateful

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#985]
- [ ] Make necessary changes to button style to have proper default state
- [ ] Make `mdc-ripple` be stateful

**Comment by Garbee** [comment]
Why introduce a new inner element exactly? The original was designed to explicitly avoid this for simplicity. I'm also not seeing where the new stroke style would demand it.

**Comment by yeelan0319** [comment]
@Garbee The changes was original made for applying states (via shade) to buttons.

And you are exactly right that we also want to avoid breaking changes and remain the possibility for a simple, generic button, so after some serious discussion, we decided to move away from the breaking changes. I will close those PRs and send out an update one later on for that!

Thanks for the comments again.

**Comment by Garbee** [comment]
The state shades were already there (for CSS-only) via pseudo elements. Unless in some refactoring that was removed. The ripple upgrade on button should disable the pseudo elements for CSS-only states and use JS events to handle state class changes.

The new stroke system, appears to just be adding a border. Not sure why that would require a new inner node. But without seeing the in-development spec for that component modification I can't be sure whether a new inner node makes sense for some function of it or not.

**Comment by kfranqueiro** [comment]
I think this issue is obsolete now, between further research on how we'll implement states, and the new issue #1564.
