### ISSUE TITLE
Create new button style: stroked button

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#987]
- [ ] Create new stroked button modifier
- [ ] Update README.md
- [ ] Update demo page

See prototype [here](https://codepen.io/yeelan0319/pen/jwQaxw)

**Comment by touficbatache** [comment]
Why? It's not in the Material Design Guidelines!

**Comment by Garbee** [comment]
This demo is probably for a future component update. :wink: one of the benefits of being a product of the same team now.

**Comment by touficbatache** [comment]
Yes, I know... But it's not in the MD Guidelines so I was wondering why you would add it?

**Comment by Garbee** [comment]
> But it's not in the MD Guidelines so I was wondering why you would add it?

To which I responded:

> probably for a future component update.

The MCW team now is a direct part of the MD team. So they can see and know what is happening before the changes are rolled out externally. Letting the design team get valuable implementation-level feedback before it is recommended that developers carry things out that are difficult to do across the various platforms.
