### ISSUE TITLE
Toolbar icon class names could be tweaked

### ISSUE THREAD

**Issue by Garbee** [material-components/material-components-web#994]
The toolbar currently usinges `_icon` for the elements to trigger actions. While this is drawn directly from the specification, it could lead developers to thinking when developing that only icons should be put in here. This may cause inferior UXes for users. On a desktop where plenty of space is available, showing whole words for triggers can be a huge leap forward to help users understand the applications functions at a quick glance. For example, if you use a non-persistent drawer on desktop as well showing "Menu" in place of the hamburger menu icon is much more user friendly in some cases. Whether or not the MD specification agrees with it.

My recommendation is that the class names be renamed from `__icon` to something more generic like `__action`. This helps convey the node should trigger some action to be performed. It seems more semantic to developers and designers as they are building to keep the context in their minds of what the node exists for.

**Comment by yeelan0319** [comment]
Thanks @Garbee. 

We reached out to our designer for clarification. Our designers agreed that there is more space for putting text on toolbar on desktop, so this is a reasonable consideration. However, it is hard to ensure the visual quality as easy as using an self-explanatory icon. So it is exactly MD's intention of using icons but not text in toolbar and we would like to follow that guidance until we have a better way to define how text might be used in toolbar.
